[GStreamer][Westeros] Initial playbin3 support
WebKit/WebKit pull request #10076
Opened 2023-02-14 07:46 UTC by calvaris

#### cbe3a0cb3a842c14ce778a123a4b72b80100b96f
<pre>
[GStreamer][Westeros] Initial playbin3 support
<a href="https://bugs.webkit.org/show_bug.cgi?id=252230">https://bugs.webkit.org/show_bug.cgi?id=252230</a>

Reviewed by NOBODY (OOPS!).

Added support to handle the westeros sink caps in playbin3.

* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:
(WebCore::MediaPlayerPrivateGStreamer::createGSTPlayBin):
(WebCore::MediaPlayerPrivateGStreamer::elementSetupCallback):
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h:
</pre>

2023-02-14 07:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cbe3a0cb3a842c14ce778a123a4b72b80100b96f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-14 07:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/79096f1498afe31b0cf18b2d9b6133484f995409. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-14 12:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/af6af0240e727b50722f5278d34c69955ffb3713. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-16 11:51 UTC, philn requested changes

2023-02-16 11:51 UTC, philn commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    g_signal_connect_swapped(m_pipeline.get(), "element-setup", G_CALLBACK(elementSetupCallback), this);
ifdef this please

2023-02-16 11:51 UTC, philn commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +void MediaPlayerPrivateGStreamer::elementSetupCallback(MediaPlayerPrivateGStreamer* player, GstElement* element, GstElement* pipeline)
ifdef this please

2023-02-16 14:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/29b72b390317201a4298078f5caf33ec7ca41fb5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-16 14:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/29b72b390317201a4298078f5caf33ec7ca41fb5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-16 14:55 UTC, philn approved these changes
Thanks :)

2023-02-16 15:08 UTC, calvaris commented
Yeah, I gave it another spin, cause I realized that that signal was already in use to it didn't hurt to refactor a bit more.

2023-02-16 15:12 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    // Configure Westeros sink before it allocates resources.
Just changed this comment to have it according WK coding style.

2023-02-16 15:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c4ba4ef38bed094892900a192a6a19af94c6fba7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10076

2023-02-16 17:05 UTC, webkit-commit-queue commented
Committed 260373@main (0a2f95456a87): <https://commits.webkit.org/260373@main>

Reviewed commits have been landed. Closing PR #10076 and removing active labels.

2023-02-16 17:05 UTC, merged