[JSC][32bit] Enable wasm signaling memory
WebKit/WebKit pull request #10086
Opened 2023-02-14 14:33 UTC by mikhailramalho

#### ad17368e4bdbc6099f02e6c3871b05926893bcea
<pre>
[JSC][32bit] Enable wasm signaling memory
<a href="https://bugs.webkit.org/show_bug.cgi?id=244843">https://bugs.webkit.org/show_bug.cgi?id=244843</a>

Reviewed by Yusuke Suzuki.

Enable wasm signaling memory on 32bit architectures. The only thing we
need to do is to limit the &quot;fast mapped memory&quot; size to 2GB, that way
we can fit that plus the redzone pages inside a 32bit pointer. This is
OK because our memory limit was already 2GB anyway
(MAX_ARRAY_BUFFER_SIZE).

* JSTests/wasm.yaml: unskip shared memory tests on arm.
* JSTests/wasm/stress/shared-memory-errors.js: ditto.
* JSTests/wasm/stress/shared-wasm-memory-buffer.js: ditto.
* Source/JavaScriptCore/wasm/WasmMemory.cpp: use a fast memory mapped
* size of 2GB for 32bit architectures.
* (JSC::Wasm::Memory::fastMappedBytes):
* Source/WTF/wtf/PlatformEnable.h: enable wasm memory signaling on
* 32bit.
* Source/JavaScriptCore/runtime/BufferMemoryHandle.cpp:
(JSC::BufferMemoryHandle::fastMappedRedzoneBytes):
* Source/JavaScriptCore/runtime/Options.cpp:
(JSC::Options::notifyOptionsChanged):

Canonical link: <a href="https://commits.webkit.org/260483@main">https://commits.webkit.org/260483@main</a>
</pre>

2023-02-14 14:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1aeb2c0f60aa0eeba5cdbb86be0bd01698710cb1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-14 14:38 UTC, mikhailramalho commented
This is the same patch created by Xan, rebased to ToT.

After talking with Justin, we decided to send the patch again for review as he doesn't have any concerns about it anymore.

I also tested it in ARMv7 and can confirm that the signals are captured by `trapHandler` in `WasmFaultSignalHandler.cpp` and handled accordingly.

2023-02-14 14:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ddf827d2e96165c0c55f6c0233848882d2d82318. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-15 20:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/868eb7484b3b155e405e5e1bf2b69402aecadae0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-16 17:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/abe35975badebf6ece4e9e1894367c04f2d2cbf8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-16 19:54 UTC, Constellation approved these changes
r=me. Please ensure that fast memory is not enabled. Wasm fast memory is not available on 32bit, but signaling memory (used for shared memory with bound checking) is available.

2023-02-16 20:18 UTC, mikhailramalho commented
I double-checked it and wasm fast memory is disabled by default:
```
bool canUseWebAssemblyFastMemory()
{
    // Gigacage::hasCapacityToUseLargeGigacage is determined based on EFFECTIVE_ADDRESS_WIDTH.
    // If we have enough address range to potentially use a large gigacage,
    // then we have enough address range to useWebAssemblyFastMemory.
    return Gigacage::hasCapacityToUseLargeGigacage;
}
```
and `constexpr bool hasCapacityToUseLargeGigacage = BOS_EFFECTIVE_ADDRESS_WIDTH > 36;`

But now that you mentioned it, I realized that `fastMappedRedzoneBytes()` should be `0` when fast memory is disabled.

2023-02-17 21:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/60aea6c76eb195e908dd9f8541eafe59c9fa0262. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-17 21:45 UTC, Constellation requested changes

2023-02-17 21:45 UTC, Constellation commented on Source/JavaScriptCore/runtime/Options.cpp
> +
This is wrong. It will break `= false` test case.
Do,

```
#CPU(ADDRESS32)
Options::useWebAssemblyFastMemory() = false
#end
```

2023-02-17 21:45 UTC, Constellation commented on Source/JavaScriptCore/runtime/BufferMemoryHandle.cpp
> +    return 0;
This is not correct. If this code is used, since this is *fast* memory code, it should return the correct size.

2023-02-17 23:16 UTC, Constellation approved these changes
r=me

2023-02-17 23:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/109c9195969768357d0dafadf2597543149e4811. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10086

2023-02-18 01:33 UTC, webkit-commit-queue commented
Committed 260483@main (ad17368e4bdb): <https://commits.webkit.org/260483@main>

Reviewed commits have been landed. Closing PR #10086 and removing active labels.

2023-02-18 01:33 UTC, merged