Remove Windows WebKitLegacy code
WebKit/WebKit pull request #10162
Opened 2023-02-15 20:44 UTC by brentfulgham

#### e8d1d8bce1e8c7a41f9af20bd710bbf27e4b11a4
<pre>
Remove Windows WebKitLegacy code
<a href="https://bugs.webkit.org/show_bug.cgi?id=252336">https://bugs.webkit.org/show_bug.cgi?id=252336</a>

Reviewed by NOBODY (OOPS!).

WebKitLegacy code is no longer used on any Windows port. We can now delete
the relevant code.

* Source/WebKitLegacy/PlatformWin.cmake: Removed.
* Source/WebKitLegacy/WebKitLegacy.vcxproj/WebKitLegacy.proj: Removed.
* Source/WebKitLegacy/cf/WebCoreSupport/WebInspectorClientCF.cpp:
* Source/WebKitLegacy/win/AccessibleBase.cpp: Removed.
* Source/WebKitLegacy/win/AccessibleBase.h: Removed.
* Source/WebKitLegacy/win/AccessibleDocument.cpp: Removed.
* Source/WebKitLegacy/win/AccessibleDocument.h: Removed.
* Source/WebKitLegacy/win/AccessibleImage.cpp: Removed.
* Source/WebKitLegacy/win/AccessibleImage.h: Removed.
* Source/WebKitLegacy/win/AccessibleTextImpl.cpp: Removed.
* Source/WebKitLegacy/win/AccessibleTextImpl.h: Removed.
* Source/WebKitLegacy/win/BackForwardList.cpp: Removed.
* Source/WebKitLegacy/win/BackForwardList.h: Removed.
* Source/WebKitLegacy/win/CFDictionaryPropertyBag.cpp: Removed.
* Source/WebKitLegacy/win/CFDictionaryPropertyBag.h: Removed.
* Source/WebKitLegacy/win/COMEnumVariant.h: Removed.
* Source/WebKitLegacy/win/COMPropertyBag.h: Removed.
* Source/WebKitLegacy/win/COMVariantSetter.h: Removed.
* Source/WebKitLegacy/win/CodeAnalysisConfig.h: Removed.
* Source/WebKitLegacy/win/DOMCSSClasses.cpp: Removed.
* Source/WebKitLegacy/win/DOMCSSClasses.h: Removed.
* Source/WebKitLegacy/win/DOMCoreClasses.cpp: Removed.
* Source/WebKitLegacy/win/DOMCoreClasses.h: Removed.
* Source/WebKitLegacy/win/DOMEventsClasses.cpp: Removed.
* Source/WebKitLegacy/win/DOMEventsClasses.h: Removed.
* Source/WebKitLegacy/win/DOMHTMLClasses.cpp: Removed.
* Source/WebKitLegacy/win/DOMHTMLClasses.h: Removed.
* Source/WebKitLegacy/win/DefaultDownloadDelegate.cpp: Removed.
* Source/WebKitLegacy/win/DefaultDownloadDelegate.h: Removed.
* Source/WebKitLegacy/win/DefaultPolicyDelegate.cpp: Removed.
* Source/WebKitLegacy/win/DefaultPolicyDelegate.h: Removed.
* Source/WebKitLegacy/win/ForEachCoClass.cpp: Removed.
* Source/WebKitLegacy/win/ForEachCoClass.h: Removed.
* Source/WebKitLegacy/win/FullscreenVideoController.cpp: Removed.
* Source/WebKitLegacy/win/FullscreenVideoController.h: Removed.
* Source/WebKitLegacy/win/Interfaces/AccessibilityDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/Accessible2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/Accessible2_2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleApplication.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleEditableText.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleRelation.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleStates.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleText.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/AccessibleText2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/Accessible2/IA2CommonTypes.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/AccessibleComparable.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMCSS.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMCore.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMEvents.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMExtensions.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMHTML.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMRange.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/DOMWindow.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IGEN_DOMObject.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebApplicationCache.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebArchive.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebBackForwardList.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebBackForwardListPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebCache.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebCoreStatistics.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebDataSource.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebDatabaseManager.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebDesktopNotificationsDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebDocument.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebDownload.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebEditingDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebEmbeddedView.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebError.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebErrorPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFormDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFrame.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFrameLoadDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFrameLoadDelegatePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFrameLoadDelegatePrivate2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFramePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebFrameView.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebGeolocationPolicyListener.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebGeolocationPosition.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebGeolocationProvider.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHTMLRepresentation.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHTTPURLResponse.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHistory.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHistoryDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHistoryItem.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHistoryItemPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebHistoryPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebInspector.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebInspectorPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebJavaScriptCollector.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebKitStatistics.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebMutableURLRequest.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebMutableURLRequestPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebNavigationData.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebNotification.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebNotificationCenter.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebNotificationObserver.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebPolicyDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebPolicyDelegatePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebPreferences.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebPreferencesPrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebResource.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebResourceLoadDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebResourceLoadDelegatePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebResourceLoadDelegatePrivate2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebScriptObject.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebScriptWorld.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebSecurityOrigin.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebSerializedJSValue.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebSerializedJSValuePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebTextRenderer.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebUIDelegate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebUIDelegate2.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebUIDelegatePrivate.idl: Removed.
* Source/WebKitLegacy/win/Interfaces/IWebURLAuthenticatio [...]

2023-02-15 20:56 UTC, fujii commented
You can remove this code too. But, I don't mind landing this patch as is. LGTM.
https://github.com/WebKit/WebKit/blob/e87820646ce924819148b2900a4458d63950672f/Source/WebKitLegacy/CMakeLists.txt#L44-L48

2023-02-15 20:56 UTC, fujii approved these changes

2023-02-15 20:57 UTC, brentfulgham commented
> You can remove this code too. But, I don't mind landing this patch as is. LGTM.

Oh, I'll add it. I have some small include order cleanups that might work in `WebInspectorClientCF.cpp`, and I'll do both.

2023-02-15 21:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e8d1d8bce1e8c7a41f9af20bd710bbf27e4b11a4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10162

2023-02-15 21:46 UTC, donny-dont commented
Oh the only thing of note is that we need those image resources to go somewhere in the end.

2023-02-15 21:47 UTC, brentfulgham commented
> Oh the only thing of note is that we need those image resources to go somewhere in the end.

Which images?

2023-02-15 21:59 UTC, fujii commented
Don't worry. It's not a blocker of this.

2023-02-15 22:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4f3b70c64841ef71c738a477f683a28ed174e578. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10162

2023-02-15 23:47 UTC, fujii requested changes
Please just remove the icons. Some of them are obsolete. I will check and readd later.

2023-02-16 20:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8e94d08d326cad8f3b0512541fc4038440219521. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10162

2023-02-16 21:14 UTC, fujii approved these changes

2023-02-16 22:34 UTC, webkit-commit-queue commented
Committed 260397@main (252ee7ef89ec): <https://commits.webkit.org/260397@main>

Reviewed commits have been landed. Closing PR #10162 and removing active labels.

2023-02-16 22:34 UTC, merged