[GLib] Warning on WebKitNetworkSession documentation
WebKit/WebKit pull request #10299
Opened 2023-02-17 22:08 UTC by aperezdc

#### 9e0f5790eb66bb9edb808427ae89aa323745f122
<pre>
[GLib] Warning on WebKitNetworkSession documentation
<a href="https://bugs.webkit.org/show_bug.cgi?id=252468">https://bugs.webkit.org/show_bug.cgi?id=252468</a>

Reviewed by NOBODY (OOPS!).

* Source/WebKit/gtk/migrating-to-webkitgtk-6.0.md: Change link to
  webkit_network_session_get_default to use an [id@&lt;...&gt;] reference,
  it seems gi-docgen is getting confused by the exported GI namespace
  being WebKit2, but the reference using WebKit.&lt;...&gt; and the function
  being a &quot;static method&quot; which does not take an instance as first
  parameter.
</pre>

2023-02-17 22:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9e0f5790eb66bb9edb808427ae89aa323745f122. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10299

2023-02-17 23:28 UTC, mcatanzaro commented
> it seems gi-docgen is getting confused by the exported GI namespace being WebKit2

Uhh this is bad, it should have been changed to `WebKit`

2023-02-17 23:29 UTC, mcatanzaro commented
And it looks like it has. Are you sure that's what's wrong?

2023-02-17 23:32 UTC, mcatanzaro commented
OK I think I found the problem. Try this:

```
diff --git a/Source/WebKit/gtk/urlmap.js.in b/Source/WebKit/gtk/urlmap.js.in
index a0bfdaa3ab8e..d1bb86d433ca 100644
--- a/Source/WebKit/gtk/urlmap.js.in
+++ b/Source/WebKit/gtk/urlmap.js.in
@@ -11,6 +11,6 @@ baseURLs = [
   ["Gtk", "https://docs.gtk.org/gtk@GTK_API_VERSION@/"],
   ["JavaScriptCore", "../javascriptcoregtk" + baseURLApiLevelSuffix],
   ["Soup", "https://libsoup.org/libsoup-3.0/"],
-  ["WebKit2", "../webkit@WEBKITGTK_API_INFIX@gtk" + baseURLApiLevelSuffix],
-  ["WebKit2WebExtension", "../webkit@WEBKITGTK_API_INFIX@gtk-web-extension" + baseURLApiLevelSuffix]
+  ["WebKit@WEBKITGTK_API_INFIX@", "../webkit@WEBKITGTK_API_INFIX@gtk" + baseURLApiLevelSuffix],
+  ["WebKit@WEBKITGTK_API_INFIX@WebExtension", "../webkit@WEBKITGTK_API_INFIX@gtk-web-extension" + baseURLApiLevelSuffix]
 ]
```

2023-02-18 21:50 UTC, aperezdc commented
> OK I think I found the problem. Try this:
> 
> ```
> diff --git a/Source/WebKit/gtk/urlmap.js.in b/Source/WebKit/gtk/urlmap.js.in
> index a0bfdaa3ab8e..d1bb86d433ca 100644
> --- a/Source/WebKit/gtk/urlmap.js.in
> +++ b/Source/WebKit/gtk/urlmap.js.in
> @@ -11,6 +11,6 @@ baseURLs = [
>    ["Gtk", "https://docs.gtk.org/gtk@GTK_API_VERSION@/"],
>    ["JavaScriptCore", "../javascriptcoregtk" + baseURLApiLevelSuffix],
>    ["Soup", "https://libsoup.org/libsoup-3.0/"],
> -  ["WebKit2", "../webkit@WEBKITGTK_API_INFIX@gtk" + baseURLApiLevelSuffix],
> -  ["WebKit2WebExtension", "../webkit@WEBKITGTK_API_INFIX@gtk-web-extension" + baseURLApiLevelSuffix]
> +  ["WebKit@WEBKITGTK_API_INFIX@", "../webkit@WEBKITGTK_API_INFIX@gtk" + baseURLApiLevelSuffix],
> +  ["WebKit@WEBKITGTK_API_INFIX@WebExtension", "../webkit@WEBKITGTK_API_INFIX@gtk-web-extension" + baseURLApiLevelSuffix]
>  ]
> ```

While your diff is needed anyway, it won't silence the warning and we should make a separate PR to land it.

That is because this is with `build-webkit --gtk`, which builds the **old API**, where the GI namespace is indeed `WebKit2`. This means that now the _same_ documentation source can get built with either the `WebKit` (new API) or the `WebKit2` namespace, so we _need_ to avoid using `[...@WebKit.Foo.bar]` for links. Instead, we can either use `[...@Foo.bar]`, or C identifiers/names like `[id@webkit_foo_bar]` and `[class@WebKitFoo]` (note that there is no dot in the link, `gi-docgen` then will do the right thing!)

2023-02-19 01:05 UTC, mcatanzaro commented
Ugh, I assumed that the migration guide would only be in the new documentation and not the old documentation. :(

2023-02-19 22:18 UTC, aperezdc commented
> Ugh, I assumed that the migration guide would only be in the new documentation and not the old documentation. :(

Well, I suppose we could conditionally list it in the generated `.toml` file with the documentation generation settings&mdash;it's already a template.

2023-02-19 22:51 UTC, mcatanzaro commented
If it's not too much work, that would be the ideal solution.

2023-02-27 21:08 UTC, mcatanzaro commented
> If it's not too much work, that would be the ideal solution.

I guess you didn't find a chance to try this yet?

2023-03-01 16:02 UTC, mcatanzaro requested changes
I think the old API version should really not build the migration docs. They are not relevant to users of the old API. Having to remember that the migration docs should be compatible with both APIs makes linking unnecessarily difficult.

2023-03-03 16:48 UTC, mcatanzaro commented
fyi: I needed to fix this as part of https://bugs.webkit.org/show_bug.cgi?id=226665, so if I manage to succeed there, this will be solved too.

2023-03-09 14:52 UTC, mcatanzaro commented
> fyi: I needed to fix this as part of https://bugs.webkit.org/show_bug.cgi?id=226665, so if I manage to succeed there, this will be solved too.

Oops, I managed to mess that up, but have followed up in https://github.com/WebKit/WebKit/pull/11295. Let's land that instead.

2023-03-09 14:52 UTC, closed without merging