Call function to restrict image decoders for all clients
WebKit/WebKit pull request #1051
Opened 2022-05-26 15:56 UTC by pvollan

#### 726703c0a065236e9f8ae88b73a4d96e44c4f250
<pre>
Call function to restrict image decoders for all clients
<a href="https://bugs.webkit.org/show_bug.cgi?id=240958">https://bugs.webkit.org/show_bug.cgi?id=240958</a>
&lt;rdar://93794556&gt;

Reviewed by NOBODY (OOPS!).

Call function to restrict image decoders for all clients on iOS. We previously only did this for Mail,
since Mail needs to decode HEIC images. Decoding of HEIC images should be possible for all clients,
and we call the function to restrict image decoders to be able to decode the HEIC images in the
WebContent process without IOKit access, since there is no IOKit access.

* Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm:
(WebKit::WebProcessPool::platformInitializeWebProcess):
</pre>

2022-05-26 21:58 UTC, smfr requested changes
I really want us to rename "restrictImageAndVideoDecoders" before making this change. It does not mean we do additional restriction of image decoders; it means we call some SPI which is only about video decoders, and actually increases, not decreases the number of decoders available.

2022-05-26 22:21 UTC, pvollan commented
> I really want us to rename "restrictImageAndVideoDecoders" before making this change. It does not mean we do additional restriction of image decoders; it means we call some SPI which is only about video decoders, and actually increases, not decreases the number of decoders available.

That makes sense! I'll come up with a more accurate name.

Thanks for reviewing!

2022-05-27 03:34 UTC, nmoucht commented
I think it would be useful to explain why we are enabling this only on iOS in the commit message. Seems strange to allow decoding in Web Content on iOS but not macOS.

2022-05-27 03:44 UTC, nmoucht requested changes
I think it would be useful to explain why we are enabling this only on iOS in the commit message. Seems strange to allow decoding in Web Content on iOS but not macOS.

2022-05-27 14:38 UTC, pvollan commented
> I think it would be useful to explain why we are enabling this only on iOS in the commit message. Seems strange to allow decoding in Web Content on iOS but not macOS.

That is a good point, will fix!

Thanks for reviewing!

2022-05-27 14:48 UTC, pvollan commented
I uploaded a new patch, renaming the function, in case this function call is still needed.

2022-06-01 21:55 UTC, geoffreygaren commented on Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
> +        enableDecodingHEIC();
Note to all readers, including myself: enableDecodingHEIC() does three things:
(1) Adds HEIC to the list of allowed video formats. (HEIC is absent by default. Also, adding HEIC as a video format does not add it as an image format. A separate call to setAdditionalSupportedImageTypes is required for that.)
(2) Removes a bunch of other video formats from the list of allowed video formats.
(3) Asks Video Toolbox, if invoked, to run in-process without use of hardware devices or IOSurface.

2022-06-01 21:56 UTC, geoffreygaren commented on Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
> +        enableDecodingHEIC();
Also: (3) is the primary motivation for this patch. It fixes a sandbox violation when blocking IOKit in WebContent.

2022-06-01 23:15 UTC, geoffreygaren approved these changes
Can you update the commit message to explain that the main motivation here is to avoid using IOKit when decoding HEIC or JPEG with aux HEIC, and to explain that enableDecodingHEIC() has that effect, in addition to enabling decoding HEIC?

r=me

2022-06-01 23:15 UTC, geoffreygaren commented on Source/WebKit/WebProcess/cocoa/WebProcessCocoa.mm
> +        enableDecodingHEIC();
Given this behavior, I think a nice follow-up would be to rename enableDecodingHEIC() again (sorry!) like so:

setVideoDecodingBehaviors(bool allowHEIC, bool allowIOKit)

2022-06-01 23:56 UTC, pvollan commented
> Can you update the commit message to explain that the main motivation here is to avoid using IOKit when decoding HEIC or JPEG with aux HEIC, and to explain that enableDecodingHEIC() has that effect, in addition to enabling decoding HEIC?
> 
> r=me

Sounds good! I will update the commit message and create a follow up patch, adding the function

setVideoDecodingBehaviors(bool allowHEIC, bool allowIOKit)

Thanks for reviewing!

2022-06-03 15:55 UTC, merged

2022-06-03 15:55 UTC, webkit-early-warning-system commented
Committed r295213 (251270@main): <https://commits.webkit.org/251270@main>

Reviewed commits have been landed. Closing PR #1051 and removing active labels.