Remove support for Microsoft My Day
WebKit/WebKit pull request #10576
Opened 2023-02-23 14:33 UTC by AtariDreams

#### 4ab39a6f90995b22b4c18ca2acdc77bd4f9ece47
<pre>
Remove support for Microsoft My Day
<a href="https://bugs.webkit.org/show_bug.cgi?id=252816">https://bugs.webkit.org/show_bug.cgi?id=252816</a>

Reviewed by NOBODY (OOPS!).

Microsoft My Day no longer exists, and is now a feature that is part of
Outlook. We can remove this check.
</pre>

2023-02-23 14:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4ab39a6f90995b22b4c18ca2acdc77bd4f9ece47. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-02-23 15:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f8416a6b87297bf49f1d69d2f4580d2f20511eb9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-22 22:11 UTC, karlcow approved these changes
* MSN Messenger became Windows Live Messenger and the [final release was on August 7, 2012](https://en.wikipedia.org/wiki/Windows_Live_Messenger). So yes safe to remove it. 
* [Microsoft To Do](https://todo.microsoft.com/tasks/) seems to includes a "My Day" feature, which is probably wildly different than the previous one. It was part of Entourage before that but was discontinued in 2008. Safe to remove.

2023-03-24 13:18 UTC, AtariDreams commented
Can we merge these changes then?

2023-03-24 14:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a895242f1ca86f3148983c0511c75b1fd3e240ab. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-26 19:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/68c57c78282ae8b2ee9fc6320cd9cdb9f6b22126. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-26 23:59 UTC, karlcow commented
I let @brentfulgham validate the last step for C++ code side.

2023-03-29 13:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/539105308846382f934aadc3b8fcc30e17715425. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-29 15:12 UTC, AtariDreams commented
Failures are unrelated to changes. However, I have to adjust the commit message, so there will be one more force-push.

2023-03-29 15:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/833b7ba4c34f89cd2fd4246cc7034414a90bfda0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-29 15:34 UTC, AtariDreams commented
@brentfulgham Could we please merge this?

2023-03-29 17:51 UTC, brentfulgham requested changes
I think this looks good, but I'd like you to remove the unneeded changes in `defaultLoadDeferringEnabled` and `defaultWindowFocusRestricted`, and revise the return value for `defaultUsePreHTML5ParserQuirks` as I suggest in the detailed notes.

Once those changes are in place I think this is ready to land.

2023-03-29 17:51 UTC, brentfulgham commented on Source/WebKitLegacy/mac/WebView/WebPreferencesDefaultValues.mm
> +    return !isAdobeInstaller;
This change is unnecessary. `WebCore::MacApplication::isAdobeInstaller` already caches its value.

2023-03-29 17:51 UTC, brentfulgham commented on Source/WebKitLegacy/mac/WebView/WebPreferencesDefaultValues.mm
> +    return !isHRBlock;
This change is unnecessary. `WebCore::MacApplication::isHRBlock` already caches its value.

2023-03-29 17:51 UTC, brentfulgham commented on Source/WebKitLegacy/mac/WebView/WebPreferencesDefaultValues.mm
> -        && (WebCore::MacApplication::isMicrosoftMyDay());
Yeah, `WEBKIT_FIRST_VERSION_WITH_HTML5_PARSER` is from 2010 so this is good to remove.

2023-03-29 17:51 UTC, brentfulgham commented on Source/WebKitLegacy/mac/WebView/WebPreferencesDefaultValues.mm
> -        && (WebCore::MacApplication::isMicrosoftMyDay());
In fact, that indicates that it should be safe to remove the `needsOutlookQuirksScript` Quirk, which would be a nice follow-up to this patch.

2023-03-29 17:51 UTC, brentfulgham commented on Source/WebKitLegacy/mac/WebView/WebPreferencesDefaultValues.mm
> +    return isAppleMail;
This should just become:

```
return webcore::MacApplication::isAppleMail();
```

2023-03-30 17:32 UTC, AtariDreams commented
Done! @brentfulgham

2023-03-30 17:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9090540d71660e9c9a7960735ba6692c52a022aa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-30 18:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/86970d3c93d9ff9a52e11fae7e8d6ae2072f8fd6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-30 18:53 UTC, brentfulgham approved these changes
Looks good!

2023-03-30 18:56 UTC, AtariDreams commented
@brentfulgham Can we please merge this?

2023-03-30 19:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/932e05d971649810f0152d760acf419320090d04. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10576

2023-03-30 22:17 UTC, brentfulgham commented
> @AtariDreams - do you want me to add 'merge-queue' label?

We can do that once the bots have finished processing.

2023-03-30 22:23 UTC, Ahmad-S792 commented
> > @AtariDreams - do you want me to add 'merge-queue' label?
> 
> We can do that once the bots have finished processing.

Yes - I was asking just to confirm that there are no more commits coming. :-)

2023-03-31 01:23 UTC, AtariDreams commented
> > > @AtariDreams - do you want me to add 'merge-queue' label?
> > 
> > 
> > We can do that once the bots have finished processing.
> 
> Yes - I was asking just to confirm that there are no more commits coming. :-)

No more commits

2023-03-31 08:49 UTC, Ahmad-S792 commented
@brentfulgham - I am marking this commit as 'merge-queue' after checking on results.webkit.org for failing `mac-AS-debug-WK2` test `fast/text/web-font-load-invisible-during-loading.html` and it seems that it failed on other commits as well and suggesting it to be flaky failure.

2023-03-31 09:13 UTC, webkit-commit-queue commented
Committed 262393@main (e5c038660e27): <https://commits.webkit.org/262393@main>

Reviewed commits have been landed. Closing PR #10576 and removing active labels.

2023-03-31 09:13 UTC, merged