Remove and Replace respondsToSelector calls where they are not needed
WebKit/WebKit pull request #10628
Opened 2023-02-24 01:11 UTC by AtariDreams

Some cases, we know they exist because of the headers containing them. Others are just a case of @available being a better fit

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-02-24 02:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a8475cd89735b016bcb0b7021b99a2131a8be7a0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 02:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4c0f75d8d5ed99940fc0faf601c7801c40f98d56. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 03:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8ee2d92cd3c3c998dafb98ac2c13f9e4b59d4240. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 04:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6205d86295aef280d8d0ad33a70ec2216faea979. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 05:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bafaf6e505a445141c3ef88d2887bad28f44d639. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 14:00 UTC, AtariDreams commented
Nothing I do style-wise gets the style guide to be happy even if I do clang-format.

2023-02-24 15:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e5f14f59427ab4ba3e3a643b7b3f506d69dff710. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-24 21:25 UTC, geoffreygaren commented
For the cases where the respondsToSelector check was removed entirely, I think we need case-by-case explanation of why that's OK, ideally with compile-time verification.

For the cases where the respondsToSelector check was replaced by an OS version check, I think we need an explanation of why an OS version check is preferred. Usually we recommend a direct check for feature availability because a direct check avoids some potential mistakes in indirectly mapping feature availability to OS version, and because a direct check supports developers who may be developing with framework roots that don't match the OS version number.

2023-02-24 21:26 UTC, geoffreygaren requested changes
r-

2023-02-25 15:42 UTC, AtariDreams commented
> r-

I can do the OS availability one actually; for some reason on Monterey (I don't know where I messed up but) xcode was throwing errors about it not being available. Maybe I should have put the compiler directive telling it to ignore unguarded uses?

2023-02-27 04:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/af60e01c5a46fa60ab370d7b6826a57764e22a44. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-27 13:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1900fe6660514a0e00b7e9ce5ba34e5b9481dcad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-27 15:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/58d3c4ef25344a9aef06ee78a08c2e89262fbec2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-02-28 21:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9f1f1818dc22af8303dd1a34424e99a35ab8bfd7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-01 00:23 UTC, AtariDreams commented
@geoffreygaren

2023-03-05 20:26 UTC, AtariDreams commented
@aproskuryakov Thoughts on this?

2023-03-05 20:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8c9f84b743fe7c42cad3c4c7167b9d4d54a47d62. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-06 14:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8655263a6f6e53fff17f42fb600d4166059b8105. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-06 23:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7aedede7818aa4e64cfa91c2982039735d389a64. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-07 13:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/483c59a724b1e6a018e1501df8e4f4148791d1bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-07 17:50 UTC, AtariDreams commented
@geoffreygaren All ready!

2023-03-08 18:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ffc2a0cd6f71441f73f0ce75bdb447b6da4d4803. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-09 16:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f82da42aa867e048ea457d92ea05761d18baf5f3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-26 19:30 UTC, AtariDreams commented
@geoffreygaren

2023-03-31 16:04 UTC, AtariDreams commented
@geoffreygaren What are your thoughts on this?

2023-03-31 16:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b2b3135556efb10487323ca202705c4e204a4f67. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10628

2023-03-31 16:27 UTC, geoffreygaren commented
I don't think my comments have been addressed. Closing PR to reduce impact on EWS.

2023-03-31 16:27 UTC, closed without merging

2023-04-02 00:10 UTC, AtariDreams commented
> I don't think my comments have been addressed. Closing PR to reduce impact on EWS.

I addressed every single one though. See the commit message, with every single case backed up with reasoning.