Fix build error with MEDIA_STREAM=OFF
WebKit/WebKit pull request #10640
Opened 2023-02-24 10:33 UTC by psaavedra

#### fb75504ec9df8b7bbeec1628c7f8f6c5da6d9ccf
<pre>
Fix build error with MEDIA_STREAM=OFF
<a href="https://bugs.webkit.org/show_bug.cgi?id=252892">https://bugs.webkit.org/show_bug.cgi?id=252892</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/platform/audio/gstreamer/AudioSourceProviderGStreamer.cpp:
(WebCore::AudioSourceProviderGStreamer::~AudioSourceProviderGStreamer):
</pre>

2023-02-24 10:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fb75504ec9df8b7bbeec1628c7f8f6c5da6d9ccf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10640

2023-02-24 14:12 UTC, philn requested changes

2023-02-24 14:12 UTC, philn commented on Source/WebCore/platform/audio/gstreamer/AudioSourceProviderGStreamer.cpp
> +#endif
This #endif needs to move one line up

2023-02-24 15:16 UTC, psaavedra commented on Source/WebCore/platform/audio/gstreamer/AudioSourceProviderGStreamer.cpp
> +#endif
right!

2023-02-24 15:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa5f4540e200c296ad1283b74fd0bbdf2561fb3f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10640

2023-02-24 15:40 UTC, philn approved these changes

2023-02-25 23:12 UTC, webkit-commit-queue commented
Committed 260843@main (f86d288403ee): <https://commits.webkit.org/260843@main>

Reviewed commits have been landed. Closing PR #10640 and removing active labels.

2023-02-25 23:12 UTC, merged