Port HTTPHeaderNames to the new serialization format
WebKit/WebKit pull request #10723
Opened 2023-02-27 12:48 UTC by gavin-apple

#### a272f6d9fb1eb8ca66d3735e0c3d3b3b4f85f0f9
<pre>
Port HTTPHeaderNames to the new serialization format
<a href="https://bugs.webkit.org/show_bug.cgi?id=252984">https://bugs.webkit.org/show_bug.cgi?id=252984</a>
rdar://105970730

Reviewed by NOBODY (OOPS!).

Ports the HTTPHeaderNames enum to the new serialization format.

* Source/WebCore/platform/network/HTTPParsers.h:
* Source/WebCore/platform/network/create-http-header-name-table:
* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/Scripts/generate-serializers.py:
(parse_serialized_types):
(main):
</pre>

2023-02-27 12:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a272f6d9fb1eb8ca66d3735e0c3d3b3b4f85f0f9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-02-27 15:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/565e11ffeb6d57f9dd7e25308a740abf2d281cce. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-02-27 15:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/565e11ffeb6d57f9dd7e25308a740abf2d281cce. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-02-27 15:42 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/501ec2bc057bf5d6dd1ca676bf8b467e7dca6215)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/109801 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/18915 "Built successfully") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/42536 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/1266 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; 'python3 Tools/Scripts/git-webkit ...'; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated wpe dependencies; Failed to compile WebKit; Reverted pull request changes; Updated wpe dependencies; Running compile-webkit-without-change") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/113753 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/20383 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/10113 "Built successfully") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/102072 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Failed to compile WebKit; Reverted pull request changes; Updated gtk dependencies; Running compile-webkit-without-change") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/115549 "Passed tests") | [⏳ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-WK2-Tests-EWS "Waiting to run tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/43/builds/42536 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/36/builds/102072 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Failed to compile WebKit; Reverted pull request changes; Updated gtk dependencies; Running compile-webkit-without-change") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/5/builds/113258 "Passed tests") | [⏳ 🧪 api-ios](https://ews-build.webkit.org/#/builders/API-Tests-iOS-Simulator-EWS "Waiting to run tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/43/builds/42536 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/36/builds/102072 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Failed to compile WebKit; Reverted pull request changes; Updated gtk dependencies; Running compile-webkit-without-change") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/11639 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/43/builds/42536 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-WK2-Tests-EWS "Waiting to run tests") | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-9-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/43/builds/42536 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/14042 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | | | 
| | | | | </details>

2023-02-27 16:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dd8c82ca105bf1204e1dd15dd8dab13b7ef11532. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-02-27 16:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dd8c82ca105bf1204e1dd15dd8dab13b7ef11532. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-02-27 19:56 UTC, achristensen07 requested changes

2023-02-27 19:56 UTC, achristensen07 commented on Source/WebKit/DerivedSources-input.xcfilelist
> +$(BUILT_PRODUCTS_DIR)/DerivedSources/WebCore/HTTPHeaderNames.serialization.in
I think this needs to use WEBCORE_PRIVATE_HEADERS_DIR to not break the internal build.

2023-02-27 19:56 UTC, achristensen07 commented on Source/WebKit/DerivedSources.make
> +	$(BUILT_PRODUCTS_DIR)/DerivedSources/WebCore/HTTPHeaderNames.serialization.in \
ditto

2023-03-01 16:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/019481f9b4531a58ce6982abeb0cd30ec00756ee. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-01 17:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13ba87859ffcd63997484ab45b58f5ab8574de2d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-01 18:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a99fbbfe029dbc610bd532a5862a65301a802937. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-01 19:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20b558cb9aed28e20e67e3b6f4088f9f82efa1e5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-01 20:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b384acdd05f9c65f06122c24ecf601c63cc67441. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-01 20:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b384acdd05f9c65f06122c24ecf601c63cc67441. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-02 15:20 UTC, achristensen07 requested changes

2023-03-02 15:20 UTC, achristensen07 commented on Source/WebCore/WebCore.xcodeproj/project.pbxproj
> +	objectVersion = 51;
Let's not change this in this PR.

2023-03-02 15:20 UTC, achristensen07 commented on Source/WebKit/DerivedSources-output.xcfilelist
> +$(BUILT_PRODUCTS_DIR)/DerivedSources/WebKit//Users/gavin/code/wk_dev3/OpenSource/WebKitBuild/Debug/DerivedSources/WebKit/HTTPHeaderNames.serialization.in
These are not correct.  It should especially not contain "gavin"

2023-03-02 15:20 UTC, achristensen07 commented on Source/WebKit/DerivedSources-output.xcfilelist
> +$(BUILT_PRODUCTS_DIR)/DerivedSources/WebKit//Users/gavin/code/wk_dev3/OpenSource/WebKitBuild/Debug/DerivedSources/WebKit/HTTPHeaderNames.serialization.in
I think just remove these. It 's correct below.

2023-03-02 15:20 UTC, achristensen07 commented on Source/WebKit/DerivedSources.make
> +all : $(BUILT_PRODUCTS_DIR)/DerivedSources/WebKit/HTTPHeaderNames.serialization.in
I think you need to remove $(BUILT_PRODUCTS_DIR)/DerivedSources/WebKit/

2023-03-02 15:20 UTC, achristensen07 commented on Source/WebKit/DerivedSources.make
> +$(BUILT_PRODUCTS_DIR)/DerivedSources/WebKit/HTTPHeaderNames.serialization.in : $(BUILT_PRODUCTS_DIR)/WebCore.framework/PrivateHeaders/HTTPHeaderNames.in $(WebKit2)/Scripts/create-http-header-serializ
I don't think $(BUILT_PRODUCTS_DIR)/WebCore.framework/PrivateHeaders/ is the correct place in the internal build.  use $(WebCorePrivateHeaders)

2023-03-02 16:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7948cc9e725e4b77ec30aab651b109ca26a558b7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-02 16:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e74d12567d37cf10e4e802c57b0cd57178fb5686. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-09 14:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1bbbbe77afc840724ccd069d0297c770d26fe83d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-09 15:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/efc8666aab6d33ee1c337449b44037379cf27c99. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-09 15:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/074335f859421127be8b65a574b48a5169c43aa7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-09 16:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ecba4327009a8d93e79778babad98c85328bc67. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10723

2023-03-10 15:01 UTC, gavin-apple commented
I'm still planning on adding a unit tests to validate create-http-header-serialization-interface.py

2023-08-15 14:55 UTC, gavin-apple commented
Simon has landed for me.

2023-08-15 14:55 UTC, closed without merging