Make Gerald Squelart a committer.
WebKit/WebKit pull request #10972
Opened 2023-03-03 00:04 UTC by squelart

#### 834784231c39a1db245705a3842d59b632e06807
<pre>
Make Gerald Squelart a committer.
<a href="https://bugs.webkit.org/show_bug.cgi?id=253278">https://bugs.webkit.org/show_bug.cgi?id=253278</a>
rdar://problem/106169023

Reviewed by NOBODY (OOPS!).

* metadata/contributors.json:
</pre>

2023-03-03 00:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/834784231c39a1db245705a3842d59b632e06807. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/10972

2023-03-03 00:13 UTC, nt1m requested changes
Requesting changes until this has gone through the formal process

2023-03-15 23:30 UTC, squelart commented
> Requesting changes until this has gone through the formal process

It looks like I'm in the list now. 😄

2023-03-15 23:36 UTC, nt1m approved these changes

2023-03-15 23:41 UTC, webkit-commit-queue commented
Committed 261721@main (711e7205b8ae): <https://commits.webkit.org/261721@main>

Reviewed commits have been landed. Closing PR #10972 and removing active labels.

2023-03-15 23:42 UTC, merged