Add proxy support to webkitscmpy's GitHub client
WebKit/WebKit pull request #1109
Opened 2022-05-27 18:58 UTC by alancoon

#### e60ec5decff7f1fab91d33d43d4ff40c73826bc4
<pre>
Add proxy support to webkitscmpy&apos;s GitHub client
<a href="https://bugs.webkit.org/show_bug.cgi?id=241031">https://bugs.webkit.org/show_bug.cgi?id=241031</a>

Reviewed by NOBODY (OOPS!).

Allow for the passing of proxy settings to the GitHub client. Use
requests.Session to pass the proxy settings to all requests made.

* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/remote/git_hub.py:
(GitHub.PRGenerator.create):
(GitHub.PRGenerator.update):
(GitHub.__init__):
(GitHub.request):
(GitHub._count_for_ref):
(GitHub._branches_for):
</pre>

2022-05-31 14:32 UTC, JonWBedard requested changes
Need to rebase this on [251070@main](https://commits.webkit.org/251070@main)

2022-06-01 02:13 UTC, alancoon commented
> Need to rebase this on [251070@main](https://commits.webkit.org/251070@main)

Those changes were to `Tools/Scripts/libraries/webkitbugspy/webkitbugspy/github.py`, whereas these changes alter `Tools/Scripts/libraries/webkitscmpy/webkitscmpy/remote/git_hub.py`.

2022-06-01 17:40 UTC, JonWBedard commented
> > Need to rebase this on [251070@main](https://commits.webkit.org/251070@main)
> 
> Those changes were to `Tools/Scripts/libraries/webkitbugspy/webkitbugspy/github.py`, whereas these changes alter `Tools/Scripts/libraries/webkitscmpy/webkitscmpy/remote/git_hub.py`.

I think the `webkitbugspy/github.py` stuff needs the proxy too, since `webkitbugspy/github.py` is the base class for `webkitscmpy/remote/git_hub.py`

2022-06-01 19:21 UTC, alancoon commented
> > > Need to rebase this on [251070@main](https://commits.webkit.org/251070@main)
> > 
> > 
> > Those changes were to `Tools/Scripts/libraries/webkitbugspy/webkitbugspy/github.py`, whereas these changes alter `Tools/Scripts/libraries/webkitscmpy/webkitscmpy/remote/git_hub.py`.
> 
> I think the `webkitbugspy/github.py` stuff needs the proxy too, since `webkitbugspy/github.py` is the base class for `webkitscmpy/remote/git_hub.py`

I see, depending on how the client uses the `github.Tracker` class, they may wind up calling requests to GitHub.com, in which case we'd need to also proxy the calls

2022-06-01 20:04 UTC, JonWBedard commented
> > ...
> 
> I see, depending on how the client uses the `github.Tracker` class, they may wind up calling requests to GitHub.com, in which case we'd need to also proxy the calls

Right, the real concern I have is the fact that PRs are actually implemented as issues under the hood, so there are a lot of scripts that interact with GitHub Issues when you wouldn't expect them to.

2022-06-06 20:47 UTC, JonWBedard approved these changes
This is a large enough change that we probably need to increment minor versions in:
```
Tools/Scripts/libraries/webkitbugspy/setup.py
Tools/Scripts/libraries/webkitbugspy/webkitbugspy/__init__.py
Tools/Scripts/libraries/webkitscmpy/setup.py
Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py
```

2022-06-06 20:47 UTC, JonWBedard commented on Tools/Scripts/libraries/webkitbugspy/webkitbugspy/github.py
> +                 version_color=DEFAULT_VERSION_COLOR, session=None):
If we're going to add a newline here, can we do something like this:
```
def __init__(
    self, url, users=None, res=None,
    component_color=DEFAULT_COMPONENT_COLOR,
    version_color=DEFAULT_VERSION_COLOR,
    session=None,
):
```

2022-06-07 03:43 UTC, merged

2022-06-07 03:43 UTC, webkit-early-warning-system commented
Committed r295325 (251349@main): <https://commits.webkit.org/251349@main>

Reviewed commits have been landed. Closing PR #1109 and removing active labels.