[popover] Throw exception when calling dialog.show() on an open popover
WebKit/WebKit pull request #11199
Opened 2023-03-07 23:51 UTC by nt1m

#### 3dedbc753d04fb92334cc97dac3ae3ada4c3f6aa
<pre>
[popover] Throw exception when calling dialog.show() on an open popover
<a href="https://bugs.webkit.org/show_bug.cgi?id=253538">https://bugs.webkit.org/show_bug.cgi?id=253538</a>
rdar://106383178

Reviewed by NOBODY (OOPS!).

<a href="https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-show">https://html.spec.whatwg.org/multipage/interactive-elements.html#dom-dialog-show</a>

* Source/WebCore/html/HTMLDialogElement.cpp:
(WebCore::HTMLDialogElement::show):
* Source/WebCore/html/HTMLDialogElement.h:
</pre>

2023-03-07 23:52 UTC, cdumez requested changes
Missing test coverage.

2023-03-07 23:52 UTC, cdumez commented on Source/WebCore/html/HTMLDialogElement.cpp
> +        return Exception { InvalidStateError };
Please pass in an exception string.

2023-03-07 23:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3dedbc753d04fb92334cc97dac3ae3ada4c3f6aa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11199

2023-03-08 00:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a1792562b0c217dca6d16c7c72b5269b5e2c332c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11199

2023-03-08 00:40 UTC, heycam approved these changes

2023-03-08 02:39 UTC, merged

2023-03-08 02:39 UTC, webkit-commit-queue commented
Committed 261351@main (af0daf6f720f): <https://commits.webkit.org/261351@main>

Reviewed commits have been landed. Closing PR #11199 and removing active labels.