Fixes navigator.credentials.preventSilentAccess()
WebKit/WebKit pull request #11303
Opened 2023-03-09 17:02 UTC by lukewarlow

#### f44d4f422b95db3dfec2f5eb9fe96c376f4cbd0c
<pre>
Fixes navigator.credentials.preventSilentAccess()
<a href="https://bugs.webkit.org/show_bug.cgi?id=242002">https://bugs.webkit.org/show_bug.cgi?id=242002</a>

Reviewed by NOBODY (OOPS!).

This change makes the function resolve rather than throw matching the spec.

* Source/WebCore/Modules/credentialmanagement/CredentialsContainer.cpp:
(WebCore::CredentialsContainer::preventSilentAccess const):
</pre>

2023-03-09 17:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f44d4f422b95db3dfec2f5eb9fe96c376f4cbd0c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11303

2023-03-12 01:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0c40228d830a20bda54f3bef2f6195ba14dd5643. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11303

2023-05-01 03:09 UTC, cdumez requested changes
How is this correct? Now we resolve the promise, making it look like we actually support `preventSilentAccess()`. However, our implementation does nothing. Unless the spec says that calling this function should do nothing besides resolving the promise, I don't think the claim in your commit log is true.

2023-05-01 03:10 UTC, cdumez reviewed
Please clarify.

2023-05-01 08:06 UTC, lukewarlow commented
Currently Safari exposes a function that unconditionally throws which also makes it look like it supports functionality that it doesn't. This change matches Firefox behaviour (they also don't Implement this functionality) so is mostly an interop fix. The current behaviour breaks feature detection meaning you have to also try catch the code.

No where in the specification does it allow for throwing a not implemented exception. The algorithm from my reading does allow for the function to have no effect though which is what I mean by match the spec.

The alternative fix would be to no longer web expose this function which would also fix feature detection I'm happy with either solution so if you'd prefer that I can change this PR (idk quite how to go about not exposing the function)

2023-05-01 08:07 UTC, lukewarlow commented
@cdumez hopefully clarified above

2023-05-01 15:15 UTC, cdumez commented
> Currently Safari exposes a function that unconditionally throws which also makes it look like it supports functionality that it doesn't. This change matches Firefox behaviour (they also don't Implement this functionality) so is mostly an interop fix. The current behaviour breaks feature detection meaning you have to also try catch the code.

We throw with a NotSupportedError, which makes feature detection really easy. It is also pretty common that we add stubs for functions have have them reject promises in such way.

By doing nothing and resolving the promise, we make it look like we support this operation, even though we do not. This, in my opinion, actually does break feature detection.

I don't work in this area of the code so I'll defer to @pascoej (who I think may be the current maintainer). My personal preference would be that we add proper support for this (though I realize it is more work).

2023-05-01 15:45 UTC, cdumez commented
> > We throw with a NotSupportedError, which makes feature detection really easy. It is also pretty common that we add stubs for functions have have them reject promises in such way.
> 
> As a web developer I expect a web exposed function to be implemented. So I can check for its existence before executing the code.
> 
> > By doing nothing and resolving the promise, we make it look like we support this operation, even though we do not. This, in my opinion, actually does break feature detection.
> 
> By calling this code I expect the browser to not allow silent access to the credentials, this only applies afaik to password credentials which Safari doesn't support. So by calling this function and having it resolve, it works exactly as expected it no longer allows silent access (because it in fact doesn't allow any access). Firefox behaves like this currently.
> 
> > I don't work in this area of the code so I'll defer to @pascoej (who I think may be the current maintainer). My personal preference would be that we add proper support for this (though I realize it is more work).

Ok. I think this makes sense but I'll let @pascoej do the formal review.
Thanks for clarifying. I agree that ideally we wouldn't have exposed an API we don't implement. However, since it was exposed years ago, it would probably be riskier to stop exposing it now.

> I personally would prefer a full password credential implementation too but I assumed WebKit was against this idea hence not implementing it to start with?

No idea what the story behind this is. I assumed we simply hadn't gotten around to implementing it yet.

2023-05-22 18:43 UTC, pascoej approved these changes

2023-05-22 19:37 UTC, webkit-commit-queue commented
Committed 264345@main (40294715d0c0): <https://commits.webkit.org/264345@main>

Reviewed commits have been landed. Closing PR #11303 and removing active labels.

2023-05-22 19:37 UTC, merged