Prefer member function find over std::find
WebKit/WebKit pull request #11406
Opened 2023-03-11 21:43 UTC by AtariDreams

<pre>Prefer member function find over std::find
https://bugs.webkit.org/show_bug.cgi?id=253764

Reviewed by NOBODY (OOPS!).

Member function is O(log(n)) while static is O(n).

* Source/WebGPU/WebGPU/Adapter.mm:(hasFeature): Prefer member find over std::find.
* Source/WebGPU/WebGPU/Device.mm:(hasFeature): Ditto.
</pre>

2023-03-12 01:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/199e354d45d92d0714de3e40fc70a799c15eeca4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11406

2023-03-12 01:05 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/8a2eaf8b8a8bb4176c72558642f9093460a63284)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [⏳ 🧪 style ](https://ews-build.webkit.org/#/builders/Style-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Monterey-Release-Build-EWS "Waiting in queue, processing has not started yet") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/87/builds/3826 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/120700 "Built successfully") 
| [⏳ 🧪 bindings ](https://ews-build.webkit.org/#/builders/Bindings-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/86/builds/3631 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Monterey-Release-Build-EWS "Waiting in queue, processing has not started yet") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/105086 "Built successfully") | 
| [⏳ 🧪 webkitpy ](https://ews-build.webkit.org/#/builders/WebKitPy-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Monterey-Release-Build-EWS "Waiting in queue, processing has not started yet") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/35/builds/45718 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Monterey-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/API-Tests-GTK-EWS "Waiting to run tests") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-Build-EWS "Waiting in queue, processing has not started yet") | | 
| [⏳ 🧪 services ](https://ews-build.webkit.org/#/builders/Services-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-9-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Monterey-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-9-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | | | | </details>

2023-03-12 15:11 UTC, mwyrzykowski requested changes
There is nothing wrong with this change however the commit message is inaccurate.

The implementation of `Vector::find` is:

```
    return findIf([&](auto& item) {
        return item == value;
    });
```
and the implementation of `findIf` is:
```
    for (size_t i = 0; i < size(); ++i) {
        if (matches(at(i)))
            return i;
    }
```

which is still O(N), not O(log(N))

2023-03-12 15:14 UTC, AtariDreams commented
> There is nothing wrong with this change however the commit message is inaccurate.
> 
> The implementation of `Vector::find` is:
> 
> ```
>     return findIf([&](auto& item) {
>         return item == value;
>     });
> ```
> 
> and the implementation of `findIf` is:
> 
> ```
>     for (size_t i = 0; i < size(); ++i) {
>         if (matches(at(i)))
>             return i;
>     }
> ```
> 
> which is still O(N), not O(log(N))

This is find, not findIf though?

2023-03-12 15:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2e2735cc3b9636d68864aa7525f4db866e2013bf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11406

2023-03-12 15:30 UTC, mwyrzykowski requested changes
Please reread my initial comment

2023-03-12 15:31 UTC, mwyrzykowski commented
> > There is nothing wrong with this change however the commit message is inaccurate.
> > The implementation of `Vector::find` is:
> > ```
> >     return findIf([&](auto& item) {
> >         return item == value;
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the implementation of `findIf` is:
> > ```
> >     for (size_t i = 0; i < size(); ++i) {
> >         if (matches(at(i)))
> >             return i;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is still O(N), not O(log(N))
> 
> This is find, not findIf though?

find calls findIf. The container type is WTF::Vector

2023-03-12 15:32 UTC, AtariDreams commented
@mwyrzykowski I apologize. Addressing the commit message now.

2023-03-12 15:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f380dc65b0039155f953747e79cf1a9288a80307. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11406

2023-03-12 15:51 UTC, AtariDreams commented
> > > There is nothing wrong with this change however the commit message is inaccurate.
> > > The implementation of `Vector::find` is:
> > > ```
> > >     return findIf([&](auto& item) {
> > >         return item == value;
> > >     });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > and the implementation of `findIf` is:
> > > ```
> > >     for (size_t i = 0; i < size(); ++i) {
> > >         if (matches(at(i)))
> > >             return i;
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > which is still O(N), not O(log(N))
> > 
> > 
> > This is find, not findIf though?
> 
> find calls findIf. The container type is WTF::Vector

Is this good now?

2023-03-12 16:02 UTC, AtariDreams commented
@mwyrzykowski Do you think we could merge this now?

2023-03-13 13:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9922efe2016c5672a8438ff700a99c13cdffee53. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11406

2023-03-13 14:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/87cdc612103fd30eb88d376790fc9ed254fa1e94. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11406

2023-03-13 16:46 UTC, mwyrzykowski requested changes
I would prefer we close this PR. Usually a PR is not opened for a two line stylistic cleanup with no meaningful impact.

Rather this can be cleaned up stylistically when this code is modified in a meaningful way in the future.

2023-03-13 16:47 UTC, closed without merging