[GStreamer] Unmute doesn't work
WebKit/WebKit pull request #11419
Opened 2023-03-12 16:42 UTC by philn

#### 5f3026c691780771e6005250bcee8a1cbd1059a5
<pre>
[GStreamer] Unmute doesn&apos;t work
<a href="https://bugs.webkit.org/show_bug.cgi?id=253769">https://bugs.webkit.org/show_bug.cgi?id=253769</a>

Reviewed by NOBODY (OOPS!).

The player now maintains an internal variable for the audio sink mute state, in order to avoid
false-positive mute change notifications. Receiving a notify::mute signal from the pipeline doesn&apos;t
necessarily means the mute state has changed, for instance the PulseAudio sink emits that signal
unconditionally before starting up.

* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:
(WebCore::MediaPlayerPrivateGStreamer::isMuted const):
(WebCore::MediaPlayerPrivateGStreamer::setMuted):
(WebCore::MediaPlayerPrivateGStreamer::notifyPlayerOfMute):
(WebCore::MediaPlayerPrivateGStreamer::handleMessage):
(WebCore::MediaPlayerPrivateGStreamer::setStreamVolumeElement):
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h:
</pre>

2023-03-12 16:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5f3026c691780771e6005250bcee8a1cbd1059a5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11419

2023-03-13 06:22 UTC, carlosgcampos approved these changes

2023-03-13 07:41 UTC, calvaris requested changes

2023-03-13 07:41 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    m_player->muteChanged(static_cast<bool>(isMuted));
If you use `m_isMuted` you won't need to cast.

2023-03-13 07:41 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    g_object_set(m_volumeElement.get(), "mute", m_isMuted, nullptr);
please, assign m_muted to a `gboolean` to set it. sizes of types differ and the compiler won't help you with this cast unless you do it explicitly. You could be assigning 3 bytes of garbage, resulting on possibly not muting.

2023-03-13 09:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0983a56eb424d641a203611b979fc8d1821b7212. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11419

2023-03-14 10:26 UTC, calvaris approved these changes

2023-03-14 10:26 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +    isMuted = static_cast<bool>(value);
I don't think you need to `static_cast` here. The compiler will handle it. The problem is when you pass a pointer and read from that.

2023-03-14 10:26 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h
> +
Maybe remove this empty line.

2023-03-14 11:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0060617f39fa4c1590441993f51441b6f1131281. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11419

2023-03-14 16:51 UTC, webkit-commit-queue commented
Committed 261635@main (7e9d65f61a53): <https://commits.webkit.org/261635@main>

Reviewed commits have been landed. Closing PR #11419 and removing active labels.

2023-03-14 16:51 UTC, merged