WebCore: Prefer mutableCopy over mutableCopyWithZone
WebKit/WebKit pull request #11440
Opened 2023-03-13 14:33 UTC by AtariDreams

#### aa1de73a1dbde894a2d2ed642ba9d5aace3a353b
<pre>
WebCore: Prefer mutableCopy over mutableCopyWithZone
<a href="https://bugs.webkit.org/show_bug.cgi?id=253825">https://bugs.webkit.org/show_bug.cgi?id=253825</a>

Reviewed by NOBODY (OOPS!).

mutableCopyWithZone is not overridden nor is the zone parameter even
acknowledged anymore by the Objective-C runtime. We should replace calls
to this with calls to mutableCopy.

* Source\WebCore\platform\mac\WebNSAttributedStringExtras.mm:
  (attributedStringByStrippingAttachmentCharacters): Replace
  mutableCopyWithZone with mutableCopy.

* Source\WebCore\platform\network\cocoa\WebCoreNSURLSession.mm:
  (initWithSession): Ditto.
</pre>

2023-03-13 14:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/aa1de73a1dbde894a2d2ed642ba9d5aace3a353b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-13 14:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/90ecbf914b4327e2d8228188e2e43fc8e5ef0c76. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-13 15:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e5d922086f4c8bba05de6ff6c16000cdd8bcc9c2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-13 15:45 UTC, AtariDreams commented
@cdumez Thoughts?

2023-03-13 16:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f089b389a9947f03f1571bb565c0c8669aa4d92. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-14 15:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c39a8b38bf3ec57bf7bebfda3b2ecffe1b2f32e1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-22 15:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/59aa9f7b917414772d23ca7000f20d8ba41340ae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-24 16:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bebdccc283dc61ab229e2e5c47e8a42a30059248. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-24 16:35 UTC, AtariDreams commented
@aproskuryakov What are your thoughts on this?

2023-03-24 16:39 UTC, cdumez requested changes

2023-03-24 16:39 UTC, cdumez commented on Source/WebCore/platform/mac/WebNSAttributedStringExtras.mm
> +        NSMutableAttributedString *newAttributedString = [attributedString mutableCopy];
Wes would adopt as soon as we create the copy. Not sure why you made this change. It is leak-prone to adopt later on.

2023-03-24 16:40 UTC, AZero13 commented on Source/WebCore/platform/mac/WebNSAttributedStringExtras.mm
> +        NSMutableAttributedString *newAttributedString = [attributedString mutableCopy];
Fixed!

2023-03-24 16:42 UTC, cdumez approved these changes
LGTM

2023-03-24 16:43 UTC, AtariDreams commented
Thank you!

2023-03-24 16:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad97b9b0d65c92aac05f7a367a00f6ffc6f14483. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11440

2023-03-24 17:47 UTC, webkit-commit-queue commented
Committed 262083@main (c0b2221b92ed): <https://commits.webkit.org/262083@main>

Reviewed commits have been landed. Closing PR #11440 and removing active labels.

2023-03-24 17:47 UTC, merged