Set the traffic class of the NW WebRTC backend based on WebRTC backend DSCP information
WebKit/WebKit pull request #11649
Opened 2023-03-17 13:12 UTC by youennf

#### 51c4e45400a9953900408217cb4ac5b9a74f5f86
<pre>
Set the traffic class of the NW WebRTC backend based on WebRTC backend DSCP information
<a href="https://bugs.webkit.org/show_bug.cgi?id=254072">https://bugs.webkit.org/show_bug.cgi?id=254072</a>
rdar://106722223

Reviewed by Alex Christensen.

Set traffic class based on provided DSCP values for TCP and UDP nw sockets.

* Source/WebKit/NetworkProcess/webrtc/NetworkRTCTCPSocketCocoa.mm:
(WebKit::NetworkRTCTCPSocketCocoa::setOption):
* Source/WebKit/NetworkProcess/webrtc/NetworkRTCUDPSocketCocoa.mm:
(WebKit::NetworkRTCUDPSocketCocoaConnections::setOption):
* Source/WebKit/NetworkProcess/webrtc/NetworkRTCUtilitiesCocoa.h:
* Source/WebKit/NetworkProcess/webrtc/NetworkRTCUtilitiesCocoa.mm:
(WebKit::trafficClassFromDSCP):

Canonical link: <a href="https://commits.webkit.org/261917@main">https://commits.webkit.org/261917@main</a>
</pre>

2023-03-17 13:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ccb13d825312d42bffd942c359c6292d6bea9dba. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11649

2023-03-17 15:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8202ecb40146457d122ca6429c652ff497b4aee1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11649

2023-03-17 15:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0cb82082792dda4a96a1b9bc7689dfc392aaa25d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11649

2023-03-20 17:54 UTC, achristensen07 requested changes

2023-03-20 17:54 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCTCPSocketCocoa.mm
> +    auto trafficClass = trafficClassFromDSCP(static_cast<rtc::DiffServCodePoint>(value));
Can the parameter type be an rtc::DiffServCodePoint instead of an int?

2023-03-20 17:54 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCUDPSocketCocoa.mm
> +            nw_connection_reset_traffic_class(nwConnection, *protectedThis->m_trafficClass);
Can we use nw_parameters_set_traffic_class also in this case before starting the connection, instead of starting the connection then calling nw_connection_reset_traffic_class immediately upon start?

2023-03-20 17:54 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCUtilitiesCocoa.mm
> +    case rtc::DiffServCodePoint::DSCP_AF42:
This could be combined with the previous one.  Why don't we want to do anything for DSCP_AF43?

2023-03-20 17:54 UTC, achristensen07 commented on Source/WebKit/Platform/spi/Cocoa/NWSPI.h
> +#define SO_TC_BK_SYS 100
I believe these are defined in sys/socket.h so shouldn't need to be redefined in an SPI header.

2023-03-20 19:14 UTC, achristensen07 approved these changes
Approved once comments are responded to

2023-03-21 07:24 UTC, youennf commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCTCPSocketCocoa.mm
> +    auto trafficClass = trafficClassFromDSCP(static_cast<rtc::DiffServCodePoint>(value));
DiffServCodePoint is only if option is OPT_DSCP.
In the future, there might be other option values we want to use.

2023-03-21 07:24 UTC, youennf commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCUDPSocketCocoa.mm
> +            nw_connection_reset_traffic_class(nwConnection, *protectedThis->m_trafficClass);
This connection is created from receiving packets, we do not have any nw_parameters in this code path.

2023-03-21 07:28 UTC, youennf commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCUtilitiesCocoa.mm
> +    case rtc::DiffServCodePoint::DSCP_AF42:
Will do.
The mapping of priority to DSCP is defined in https://datatracker.ietf.org/doc/html/rfc8837#name-dscp-mappings.
Libwebrtc is only using AF41/AF42 for video high/very high.

2023-03-21 07:29 UTC, youennf commented on Source/WebKit/Platform/spi/Cocoa/NWSPI.h
> +#define SO_TC_BK_SYS 100
The public socket.h does not seem to have it.
It has service class/type but not traffic class, which is at a lower level.

2023-03-21 14:42 UTC, merged

2023-03-21 14:43 UTC, webkit-commit-queue commented
Committed 261917@main (51c4e45400a9): <https://commits.webkit.org/261917@main>

Reviewed commits have been landed. Closing PR #11649 and removing active labels.