Wrap captured variable with WeakPtr in GPUProcess::initializeGPUProcess
WebKit/WebKit pull request #11852
Opened 2023-03-23 05:51 UTC by jace0x21

#### f156b6fbe198a58780389f95b5d366f91a622caf
<pre>
Wrap captured variable with WeakPtr in GPUProcess::initializeGPUProcess
<a href="https://bugs.webkit.org/show_bug.cgi?id=254316">https://bugs.webkit.org/show_bug.cgi?id=254316</a>
rdar://107117855

Reviewed by NOBODY (OOPS!).

We are storing a lambda with a captured variable. We should use a
smart pointer here so we can check if this is alive before accessing it.

* Source/WebKit/GPUProcess/GPUProcess.cpp:
(WebKit::GPUProcess::initializeGPUProcess):
</pre>

2023-03-23 05:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f156b6fbe198a58780389f95b5d366f91a622caf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11852

2023-03-23 06:00 UTC, rniwa commented on Source/WebKit/GPUProcess/GPUProcess.cpp
> +        if (process) {
We should store this process in RefPtr like so:
if (RefPtr process = weakProcess.get()) {
    process->parentProcessConnection()...
}

2023-03-23 07:05 UTC, rniwa approved these changes

2023-03-24 23:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b2e51cc001a91b5c1f39bcc6b428099f944aabbc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11852

2023-03-28 15:11 UTC, youennf requested changes

2023-03-28 15:11 UTC, youennf commented on Source/WebKit/GPUProcess/GPUProcess.cpp
> +    CoreAudioSharedUnit::unit().setStatusBarWasTappedCallback([weakProcess = WeakPtr<GPUProcess> { *this }](auto completionHandler) {
```suggestion
    CoreAudioSharedUnit::unit().setStatusBarWasTappedCallback([weakProcess = WeakPtr { *this }] (auto completionHandler) {
```

2023-03-28 15:11 UTC, youennf commented on Source/WebKit/GPUProcess/GPUProcess.cpp
> +            completionHandler();
We need to call completionHandler outside the if statement.

2023-03-28 16:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cdbf986449104d9868b75f38ca1ad46a758e9bda. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11852

2023-03-29 19:04 UTC, youennf approved these changes

2023-03-30 07:44 UTC, webkit-commit-queue commented
Committed 262314@main (c27c56bff56c): <https://commits.webkit.org/262314@main>

Reviewed commits have been landed. Closing PR #11852 and removing active labels.

2023-03-30 07:44 UTC, merged