Avoid doing event-related work for CSS transitions when no event listener is registered
WebKit/WebKit pull request #11961
Opened 2023-03-25 02:02 UTC by cdumez

#### 7eedf56c9eab82857b2ece7b1779a39584452a32
<pre>
Avoid doing event-related work for CSS transitions when no event listener is registered
<a href="https://bugs.webkit.org/show_bug.cgi?id=254454">https://bugs.webkit.org/show_bug.cgi?id=254454</a>
rdar://107077986

Reviewed by NOBODY (OOPS!).

Avoid doing event-related work for CSS transitions when no event listener is
registered for these.

* Source/WebCore/animation/DeclarativeAnimation.cpp:
(WebCore::DeclarativeAnimation::invalidateDOMEvents):
* Source/WebCore/animation/DocumentTimeline.h:
* Source/WebCore/animation/WebAnimation.cpp:
(WebCore::WebAnimation::cancel):
* Source/WebCore/dom/EventNames.h:
(WebCore::EventNames::isTransitionAnimationEventType const):
* Source/WebCore/dom/Node.cpp:
(WebCore::tryAddEventListener):
* Source/WebCore/page/LocalDOMWindow.cpp:
(WebCore::LocalDOMWindow::addEventListener):
</pre>

2023-03-25 02:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7eedf56c9eab82857b2ece7b1779a39584452a32. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 04:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dac670b7db8d4678a7f0706ec5c9f1256d8714eb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 16:24 UTC, cdumez commented
A/B testing says this is a 0.38% progression on M1 and a 0.7% progression on iPhone.

2023-03-25 16:59 UTC, graouts commented
Thanks for doing this work, the A/B numbers you report suggest it's a great idea to do this. However, I have a few concerns:

1. this patch says it's about CSS Transitions but also deals with the `cancel` event which is an `AnimationPlaybackEvent`. I think this should either be strictly focused on `TransitionEvent` or include all `AnimationPlaybackEvent` types, including `finish` and `remove`. See https://drafts.csswg.org/web-animations-1/#animation-playback-events-section.
2. what about events for CSS Animations?
3. it doesn't seem obvious to me that we should track whether animation targets have registered event listeners on the `DocumentTimeline`. It would seem more logical to me to check this per `DeclarativeAnimation` in `DeclarativeAnimation::invalidateDOMEvents()`, and maybe have a flag on `Styleable` to track these. This will also apply for CSS Animation events. For `AnimationPlaybackEvent` the target is `WebAnimation`.
4. could we move the logic of `EventNames::isTransitionAnimationEventType()` to `CSSTransitionEvent`?

2023-03-25 17:00 UTC, graouts requested changes
Thanks for doing this work, the A/B numbers you report suggest it's a great idea to do this. However, I have a few concerns:

1. this patch says it's about CSS Transitions but also deals with the `cancel` event which is an `AnimationPlaybackEvent`. I think this should either be strictly focused on `TransitionEvent` or include all `AnimationPlaybackEvent` types, including `finish` and `remove`. See https://drafts.csswg.org/web-animations-1/#animation-playback-events-section.
2. what about events for CSS Animations?
3. it doesn't seem obvious to me that we should track whether animation targets have registered event listeners on the `DocumentTimeline`. It would seem more logical to me to check this per `DeclarativeAnimation` in `DeclarativeAnimation::invalidateDOMEvents()`, and maybe have a flag on `Styleable` to track these. This will also apply for CSS Animation events. For `AnimationPlaybackEvent` the target is `WebAnimation`.
4. could we move the logic of `EventNames::isTransitionAnimationEventType()` to `CSSTransitionEvent`?

2023-03-25 17:06 UTC, cdumez commented
> Thanks for doing this work, the A/B numbers you report suggest it's a great idea to do this. However, I have a few concerns:
> 
> 1. this patch says it's about CSS Transitions but also deals with the `cancel` event which is an `AnimationPlaybackEvent`. I think this should either be strictly focused on `TransitionEvent` or include all `AnimationPlaybackEvent` types, including `finish` and `remove`. See https://drafts.csswg.org/web-animations-1/#animation-playback-events-section.

Transisitions events and cancel are the only ones that fire on Speedometer. I wanted to include cancel because Speedometer covers it. I can look into adding finish and remove if it feels cleaner.

> 2. what about events for CSS Animations?

They do not happen during Speedometer. Checking for them will have a cost and will result in no win on Speedometer.
This is why I didn't cover them.

> 3. it doesn't seem obvious to me that we should track whether animation targets have registered event listeners on the `DocumentTimeline`. It would seem more logical to me to check this per `DeclarativeAnimation` in `DeclarativeAnimation::invalidateDOMEvents()`, and maybe have a flag on `Styleable` to track these. This will also apply for CSS Animation events. For `AnimationPlaybackEvent` the target is `WebAnimation`.
> 4. could we move the logic of `EventNames::isTransitionAnimationEventType()` to `CSSTransitionEvent`?

We could. I don't feel strongly either way but there was precedent to add such convenience functions to EventNames().

2023-03-25 17:11 UTC, graouts commented
> > Thanks for doing this work, the A/B numbers you report suggest it's a great idea to do this. However, I have a few concerns:
> > 
> > 1. this patch says it's about CSS Transitions but also deals with the `cancel` event which is an `AnimationPlaybackEvent`. I think this should either be strictly focused on `TransitionEvent` or include all `AnimationPlaybackEvent` types, including `finish` and `remove`. See https://drafts.csswg.org/web-animations-1/#animation-playback-events-section.
> 
> Transisitions events and cancel are the only ones that fire on Speedometer. I wanted to include cancel because Speedometer covers it. I can look into adding finish and remove if it feels cleaner.

That's fine by me, but I think we want the bug name to reflect this. Maybe make this patch title more about dealing with Speedometer than about CSS Transitions?

> > 2. what about events for CSS Animations?
> 
> They do not happen during Speedometer. Checking for them will have a cost and will result in no win on Speedometer. This is why I didn't cover them.

Are you saying that implementing similar logic for CSS Animations may have a negative impact on Speedometer because we already know that Speedometer does not use any CSS Animation?

While I understand the primary focus here is to improve the Speedometer score, CSS Animations are pretty pervasive on the Web and so if those CSS Transition checks are a performance win for Speedometer, shouldn't we want to generalize this logic to benefit the Web at large?

> > 3. it doesn't seem obvious to me that we should track whether animation targets have registered event listeners on the `DocumentTimeline`. It would seem more logical to me to check this per `DeclarativeAnimation` in `DeclarativeAnimation::invalidateDOMEvents()`, and maybe have a flag on `Styleable` to track these. This will also apply for CSS Animation events. For `AnimationPlaybackEvent` the target is `WebAnimation`.
> > 4. could we move the logic of `EventNames::isTransitionAnimationEventType()` to `CSSTransitionEvent`?
> 
> We could. I don't feel strongly either way but there was precedent for adding such convenience functions to EventNames().

It's not a big deal either way, I can see valid reasons to have it on both `EventNames` and `CSSTransitionEvent`.

2023-03-25 17:46 UTC, cdumez commented
Antoine found a few issues. I am working on a new iteration.

2023-03-25 20:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f72a78b53197428dc2c9fba00e0a6261cf9b08b0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 20:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f72a78b53197428dc2c9fba00e0a6261cf9b08b0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 20:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9c16ba2bbc1dcbaa5f985600f7c7b66dc18fc94c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 20:32 UTC, graouts approved these changes

2023-03-25 20:32 UTC, graouts commented on Source/WebCore/animation/DeclarativeAnimation.cpp
> +        if (m_owningElement->document().hasListenerType(Document::TRANSITION_ANIMATION_LISTENER)) {
Maybe add this condition to the `else if (is<CSSTransition>(this))` statement to avoid a single, big nested `if`?

2023-03-25 20:32 UTC, graouts commented on Source/WebCore/dom/EventNames.h
> +    bool isTransitionAnimationEventType(const AtomString& eventType) const;
I suggest to use either `isCSSTransitionEventType` (matching our internal class name) or `isTransitionEventType` (matching the IDL interface name).

2023-03-25 20:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cb0d409f1163a9e3b817bf41b3679d5ccef020ea. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 20:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cb0d409f1163a9e3b817bf41b3679d5ccef020ea. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 20:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/61767e1738a049c28c6c3af937f45c9e4d6227fa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 21:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/30f4f624995a285945e4d7e5634b15b7acc126c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/11961

2023-03-25 21:08 UTC, cdumez commented
Upstream WPT PR: https://github.com/web-platform-tests/wpt/pull/39206

2023-03-26 00:48 UTC, webkit-commit-queue commented
Committed 262123@main (43ea8744bc60): <https://commits.webkit.org/262123@main>

Reviewed commits have been landed. Closing PR #11961 and removing active labels.

2023-03-26 00:48 UTC, merged