[EME] media/encrypted-media/mock-MediaKeySession-generateRequest.html is a flaky crash
WebKit/WebKit pull request #12111
Opened 2023-03-29 14:13 UTC by calvaris

#### 3286618471ed1f34265d0018a0a4700492714040
<pre>
[EME] media/encrypted-media/mock-MediaKeySession-generateRequest.html is a flaky crash
<a href="https://bugs.webkit.org/show_bug.cgi?id=251550">https://bugs.webkit.org/show_bug.cgi?id=251550</a>

Reviewed by NOBODY (OOPS!).

We need to bail out with empty IDs.

* Source/WebCore/Modules/encryptedmedia/MediaKeySession.cpp:
(WebCore::MediaKeySession::stop):
</pre>

2023-03-29 14:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3286618471ed1f34265d0018a0a4700492714040. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12111

2023-03-29 16:18 UTC, jernoble commented
I don't understand how m_sessionId would be empty and m_closed would be true. This doesn't seem to be the right way to fix a crash in the Mock CDM. Shouldn't this be something like: 
```
--- a/Source/WebCore/testing/MockCDMFactory.cpp
+++ b/Source/WebCore/testing/MockCDMFactory.cpp
@@ -71,7 +71,8 @@ bool MockCDMFactory::hasSessionWithID(const String& id)
 
 void MockCDMFactory::removeSessionWithID(const String& id)
 {
-    m_sessions.remove(id);
+    if (!id.isEmpty())
+        m_sessions.remove(id);
 }
```

2023-03-30 06:37 UTC, calvaris commented
> I don't understand how m_sessionId would be empty and m_closed would be true. This doesn't seem to be the right way to fix a crash in the Mock CDM. Shouldn't this be something like:
> 
> ```
> --- a/Source/WebCore/testing/MockCDMFactory.cpp
> +++ b/Source/WebCore/testing/MockCDMFactory.cpp
> @@ -71,7 +71,8 @@ bool MockCDMFactory::hasSessionWithID(const String& id)
>  
>  void MockCDMFactory::removeSessionWithID(const String& id)
>  {
> -    m_sessions.remove(id);
> +    if (!id.isEmpty())
> +        m_sessions.remove(id);
>  }
> ```

The answer is that the session ID is never set in that case so that instance has no session ID. We can fix the crash both ways.

2023-03-30 10:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1a858c54e8aafa082f6e96a657f18a178a812db3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12111

2023-03-30 15:37 UTC, jernoble requested changes

2023-03-30 15:37 UTC, jernoble commented on Source/WebCore/Modules/encryptedmedia/MediaKeySession.cpp
> +    if (m_closed || m_sessionId.isEmpty()) {
This still seems wrong. m_sessionId isn't set until deep in a string of callbacks. Bailing out here means that sessionWasClosed() would potentially never be called, and therefore m_closed will never be set.

Given that the changes to the Mock are sufficient to fix this, I'd recommend just dropping this part of the patch.

2023-03-31 10:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13387dcbbdd57c610a0641c00603ce35a0698eb7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12111

2023-04-11 08:22 UTC, calvaris commented
@jernoble this would be ready for review.

2023-04-11 08:46 UTC, jernoble approved these changes

2023-04-11 09:42 UTC, webkit-commit-queue commented
Committed 262819@main (cc44de0d9d44): <https://commits.webkit.org/262819@main>

Reviewed commits have been landed. Closing PR #12111 and removing active labels.

2023-04-11 09:42 UTC, merged