Fix the iOS16 and macOS Ventura builds
WebKit/WebKit pull request #12160
Opened 2023-03-30 05:52 UTC by robert-jenner

#### 06b473f23f2082a920f61d6d68d62d8000fdf1ff
<pre>
Fix the iOS16 and macOS Ventura builds
<a href="https://bugs.webkit.org/show_bug.cgi?id=254720">https://bugs.webkit.org/show_bug.cgi?id=254720</a>
rdar://107145727

Reviewed by NOBODY (OOPS!).

Changed needed to get iOS 16.4 and macOS Ventura 13.3 to build WebKit.

* Source/JavaScriptCore/API/ObjCCallbackFunction.mm:
(objCCallbackFunctionForInvocation):
* Source/ThirdParty/libwebrtc/Source/third_party/boringssl/src/crypto/x509/t_x509.c:
(X509_NAME_print):
* Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp8/encoder/onyx_if.c:
(encode_frame_to_data_rate):
* Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_encodeframe.c:
(compute_frame_aq_offset):
* Source/ThirdParty/libwebrtc/Source/third_party/libvpx/source/libvpx/vp9/encoder/vp9_ratectrl.c:
(vp9_encodedframe_overshoot):
* Source/WebCore/editing/cocoa/DataDetection.mm:
(WebCore::buildQuery):
</pre>

2023-03-30 05:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/06b473f23f2082a920f61d6d68d62d8000fdf1ff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12160

2023-04-03 18:29 UTC, emw-apple approved these changes
Changes seem fine to me. The libwebrtc fixes seem objectively correct, so I would think we should upstream the change. @youennf, would we normally do this?

2023-04-03 22:42 UTC, ddkilzer requested changes
Why are these only showing up now?  What changed?

Normally the third-party projects have upstream changes that can/should be merged.

2023-04-03 22:47 UTC, aproskuryakov commented
> What changed?

This is for iOS 16.4, macOS Ventura 13.3, and aligned Xcode. WebKit has never built in open source configuration with these.

2023-04-03 22:52 UTC, ddkilzer commented
> This is for iOS 16.4, macOS Ventura 13.3, and aligned Xcode. WebKit has never built in open source configuration with these.

It's rather unsettling that we've never seen these warnings before now.

The JavaScriptCore and WebCore changes look okay.  (Someone probably changed the loop iteration mechanism in the past, but didn't remove the unneeded variables.)

I'm concerned about the `boringssl` and `libvpx` changes as we don't know if they're unused due to a bad merge, or if upstream just hasn't enabled unused variable warnings.  We should research those to see if they were fixed upstream, and to make sure we're not missing uses of those variables.

2023-04-03 23:55 UTC, closed without merging