Define _GNU_SOURCE
WebKit/WebKit pull request #1221
Opened 2022-06-01 20:41 UTC by jvoisin

This is needed for using `pthread_getname_np`, since this function is a nonstandard GNU extension.

2022-06-02 10:24 UTC, Constellation commented
Hi! Thanks, please check https://github.com/WebKit/WebKit/wiki/Contributing to upload a commit with specific format. WebKit requires a specific commit message format ;)

2022-06-02 10:25 UTC, Constellation requested changes
Need conforming commit message.

2022-06-02 10:25 UTC, Constellation commented
CC @JonWBedard

2022-06-04 14:19 UTC, jvoisin commented
Superseded by #1309

2022-06-04 14:19 UTC, closed without merging