Prefer uncheckedArgument over argument where possible for callFrame
WebKit/WebKit pull request #12279
Opened 2023-04-01 23:11 UTC by AtariDreams

This saves us the extra work of an if-statement check.

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-04-01 23:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/90a7f9fd7c1506f906e4f096039055bfe14c87ba. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-01 23:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ee2ae2a8267f9df9ce462ae6509e0c41f0b27b06. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-01 23:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/68eba1f3d623035c89b273fed2ca34e67b420104. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-01 23:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/94d98be7628d1fa5b6012cc280836893448a029c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 00:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3e3c7a772739de2fe5c15adafebd4b4c4ce57b39. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 02:50 UTC, geoffreygaren requested changes
I don't love the idea of mass-modifying hand-written bounds checks in JavaScriptCore. Any mistake would turn into a pretty serious security bug.

Have you measured a performance benefit to this patch?

I'm going to say r- for now since the patch did not include a performance measurement when it was posted.

2023-04-02 17:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a56b7deb305c656e17ebe3a1e6200b8fc7444276. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 17:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7ebb19a88704bfcec0ad4ecbf53287c2bc0d2973. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 17:24 UTC, AtariDreams commented
> I don't love the idea of mass-modifying hand-written bounds checks in JavaScriptCore. Any mistake would turn into a pretty serious security bug.
> 
> Have you measured a performance benefit to this patch?
> 
> I'm going to say r- for now since the patch did not include a performance measurement when it was posted.

Every single case can be backed up with why argument need not be checked, because they are always after a call to argumentCount that results in the function or codebranch being left if there are is an insufficient number of arguments

2023-04-02 20:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20e652bc91be885f9ade8c784cb19dad939d7635. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 20:36 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/5cfc3f831a117943d756fed5271204eaff14ebc2)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/1697 "1 style error") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/1728 "Build is in progress. Recent messages:OS: Monterey (12.6), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/1786 "Build is in progress. Recent messages:OS: Monterey (12.6.3), Xcode: 13.4.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/2620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/1820 "Build is in progress. Recent messages:Printed configuration; Skipping applying patch since patch_id isn't provided; Running checkout-pull-request") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/1677 "Build is in progress. Recent messages:OS: Unknown (10.15.7), Xcode: 11.7") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/1795 "Build is in progress. Recent messages:OS: Monterey (12.6), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/1792 "Build is in progress. Recent messages:OS: Ventura (13.2), Xcode: 14.2; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/2620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/1712 "Build is in progress. Recent messages:OS: Unknown (10.15.7), Xcode: 11.7; Skipping applying patch since patch_id isn't provided; Running checkout-pull-request") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/23/builds/1795 "Build is in progress. Recent messages:OS: Monterey (12.6), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/14/builds/1786 "Build is in progress. Recent messages:OS: Monterey (12.6.3), Xcode: 13.4.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/2458 "Build is in progress. Recent messages:Failed to print configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/23/builds/1795 "Build is in progress. Recent messages:OS: Monterey (12.6), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/14/builds/1786 "Build is in progress. Recent messages:OS: Monterey (12.6.3), Xcode: 13.4.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/2458 "Build is in progress. Recent messages:Failed to print configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/1556 "Build is in progress. Recent messages:OS: Monterey (12.6.1), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/14/builds/1786 "Build is in progress. Recent messages:OS: Monterey (12.6.3), Xcode: 13.4.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/2458 "Build is in progress. Recent messages:Failed to print configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/1590 "Build is in progress. Recent messages:OS: Monterey (12.6.1), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/16/builds/1792 "Build is in progress. Recent messages:OS: Ventura (13.2), Xcode: 14.2; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/1752 "Build is in progress. Recent messages:Printed configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-jsc") | 
| [⏳ 🧪 services ](https://ews-build.webkit.org/#/builders/Services-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/1508 "Build is in progress. Recent messages:OS: Monterey (12.6.1), Xcode: 14.0; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![ [...]

2023-04-02 20:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3df96b4e968f0b014e2e4cde984f6f08d457fdb4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 20:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c12c60549887294e455e94a9e79c96abb3ca8f8a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 20:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5eed39f0041e6e698761b3a5c3a52f8a6e943adc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-02 20:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff8f5bbe81be96f59ffa006e5f88ae50aba600b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-03 02:41 UTC, rkirsling commented on Source/JavaScriptCore/dfg/DFGOSREntry.cpp
> +            value = callFrame->uncheckedArgument(argument - 1);
The first case in the patch already appears to go against the claim: This code has not checked `callFrame->argumentCount()`, and indeed, the comment tells us that what we're doing is seeing whether the actual values match our predictions. Presumably, this means that the even the actual argument _count_ may differ from the predicted one.

2023-04-03 16:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d2a37afe059aecf60337835f48789ec706548d76. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-03 17:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/387d3bf5ff14810312689aa8fe79833d96f050c8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12279

2023-04-03 18:12 UTC, closed without merging