Set the number of boundArgs when setting it
WebKit/WebKit pull request #12282
Opened 2023-04-02 00:36 UTC by AtariDreams

The number is kept at 0 for some reason when it should not be.

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-04-02 00:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9ccd4cd8ee4fd1df3f4a5ac14bcaf4a16e3649e1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-02 02:54 UTC, geoffreygaren requested changes
Please explain the purpose of this change in the commit message.

2023-04-02 17:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/354aee81e5f5f94098331f2922f519232faf0197. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-03 17:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/356d3514c2d0ae92e021286bc5ba6049d7efea1d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-17 19:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9ad1e21e94b1e5b99025579412039127b9640932. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-17 19:10 UTC, AtariDreams commented
@geoffreygaren Done!

2023-04-17 19:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1161157fecfb631eea5c5dd7514cb8e48504b088. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-17 19:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ec24a3b319eedfc911883577a4f6321b08aa7e41. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-17 19:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f3d6d8843af2292849b6efbc617a3b53037ca646. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-18 04:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0d18cc661c2adafac0bade1ad825b96601aeaea9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-04-18 13:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/894cab30c4aa9af3e9fa4d5ee77199cbbb976917. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12282

2023-05-16 07:43 UTC, Constellation approved these changes
r=me

2023-05-16 08:31 UTC, webkit-commit-queue commented
Committed 264109@main (81d93da03d83): <https://commits.webkit.org/264109@main>

Reviewed commits have been landed. Closing PR #12282 and removing active labels.

2023-05-16 08:31 UTC, merged