Check for jsValue first before checking for isNull
WebKit/WebKit pull request #12281
Opened 2023-04-02 00:27 UTC by AtariDreams

Otherwise, isUndefined will just crash.

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-04-02 00:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ce450aeab1e8c52d301a5e9ff663d5f4a1587a8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 00:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b901771ab9cdbed67034168a3c66b63d041ac055. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 02:54 UTC, geoffreygaren requested changes
Please explain the purpose of this change in the commit message.

2023-04-02 15:24 UTC, AtariDreams commented
> Please explain the purpose of this change in the commit message.

jsValue being null means this will crash.

2023-04-02 15:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1916da3599685382d203c3c8b3b79a1a3830ba75. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 15:30 UTC, AtariDreams commented
> Please explain the purpose of this change in the commit message.

Done!

2023-04-02 15:31 UTC, AtariDreams commented
Proposal: Cherry pick this commit to the codebase that will be compiled for Safari 16.5, because this fixes a nullptr issue and has no other change in behavior.

2023-04-02 15:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a44559d63734b0132c0f881f42588c440ffdd5af. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 15:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a57ed3eed09827f805ac8d0159eb60f1940278b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 15:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a32c03e28b165ad84864a4be85294a81a278186. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 15:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20ab020eddd2bf23e65de141496f46a534d1f1c9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 16:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f1fe4232aa4beb29a27afb9548521076118910a0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 17:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/814a9bde967f5ab264fdff6ab7c40e54f8425cf9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 18:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/81c87a6510d1e6d6fdee2c8c54c09cc14afe5a18. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-02 20:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e663659476b0c13dd28e5122c85a5a9e9c8aced2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12281

2023-04-03 10:36 UTC, Constellation requested changes
No, undefined is not a pointer. So this patch does not change anything.

2023-04-03 16:45 UTC, AtariDreams commented
JSValue being null means isUndefined cannot be called, correct?

2023-04-03 17:10 UTC, Constellation commented
No

2023-04-03 18:11 UTC, geoffreygaren commented
Closing to reduce impact on EWS.

2023-04-03 18:11 UTC, closed without merging