iOS 16.4 and macOS Ventura 13.3 build fix for third-party (254951)
WebKit/WebKit pull request #12344
Opened 2023-04-03 23:28 UTC by robert-jenner

#### 3984fa4212b25fab5f83ab082e4bbb95a85556f9
<pre>
iOS 16.4 and macOS Ventura 13.3 build fix for third-party (254951)
<a href="https://bugs.webkit.org/show_bug.cgi?id=254951">https://bugs.webkit.org/show_bug.cgi?id=254951</a>
rdar://107582190

Reviewed by NOBODY (OOPS!).

Build fix to ignore set, but un-used variables that cause build failures in third-party.

* Source/ThirdParty/libwebrtc/Configurations/Base.xcconfig:
</pre>

2023-04-03 23:29 UTC, JonWBedard approved these changes

2023-04-03 23:31 UTC, ddkilzer requested changes
r=me, but you need to make the requested change.

2023-04-03 23:31 UTC, ddkilzer commented on Source/ThirdParty/libwebrtc/Configurations/Base.xcconfig
> +WARNING_CFLAGS = $(inherited) $(WK_FIXME_WARNING_CFLAGS) -Wexit-time-destructors -Wglobal-constructors -Wthread-safety -Wno-unused-but-set-variable;
This `-Wno-unused-but-set-variable` needs to go in `WK_FIXME_WARNING_CFLAGS` below.

2023-04-03 23:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3984fa4212b25fab5f83ab082e4bbb95a85556f9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12344

2023-04-03 23:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ea82fa0c342b1fda735a09b2f54aca32036431a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12344

2023-04-03 23:59 UTC, ddkilzer approved these changes
r=me

2023-04-04 01:04 UTC, webkit-commit-queue commented
Committed 262552@main (951180b3bdc6): <https://commits.webkit.org/262552@main>

Reviewed commits have been landed. Closing PR #12344 and removing active labels.

2023-04-04 01:04 UTC, merged