Add nullptr checks to ScriptExecutable::newCodeBlockFor
WebKit/WebKit pull request #12420
Opened 2023-04-05 20:14 UTC by hyjorc1

#### bbc5209a20d5052dea693e6638c9bdc87d7ef538
<pre>
Add nullptr checks to ScriptExecutable::newCodeBlockFor
<a href="https://bugs.webkit.org/show_bug.cgi?id=255044">https://bugs.webkit.org/show_bug.cgi?id=255044</a>
rdar://104937190

Reviewed by NOBODY (OOPS!).

This is a speculative fix for a crash due to a nullptr of unlinkedCodeBlock
when creating code block in ScriptExecutable::newCodeBlockFor. The existing
implementation has four paths to create a code block, however only the last
one is guarded by a nullptr check for unlinkedCodeBlock. This fix is to add
nullptr guards of unlinkedCodeBlock for the other three code block creation paths.

* Source/JavaScriptCore/runtime/ScriptExecutable.cpp:
(JSC::ScriptExecutable::newCodeBlockFor):
</pre>

2023-04-05 20:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bbc5209a20d5052dea693e6638c9bdc87d7ef538. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-05 20:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1ea49251ed5dbe297adb96d3ca7b96fe82ab7459. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-07 18:19 UTC, Constellation requested changes
Discussed offline. We should make this never nullptr or we should make it work even if it gets nullptr. Throwing an error is semantically incorrect.

2023-04-09 23:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cfc9f2a2d9067c3050092e78e45b3123eb0596db. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-09 23:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1934596c452b90b6c35c677e5bcfba743a726f08. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 15:34 UTC, MenloDorian commented
Let's change the title to "Regenerate ModuleProgramExecutable unlinkedCodeBlock after being destroyed by low memory cleaning".

2023-04-10 15:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8c1b5a2ed462d7866333cef556a63971389c80c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 16:51 UTC, Constellation commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +UnlinkedModuleProgramCodeBlock* ModuleProgramExecutable::generateOrGetUnlinkedCodeBlock(JSGlobalObject* globalObject, ThrowScope& throwScope, ParserError& error)
Do not take `ThrowScope& throwScope`. If the function throws an error, you should define in as `auto scope = DECLARE_THROW_SCOPE(vm)` instead.

2023-04-10 16:51 UTC, Constellation commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +UnlinkedModuleProgramCodeBlock* ModuleProgramExecutable::generateOrGetUnlinkedCodeBlock(JSGlobalObject* globalObject, ThrowScope& throwScope, ParserError& error)
Do not take `ThrowScope& throwScope`. If the function throws an error, you should define in as `auto scope = DECLARE_THROW_SCOPE(vm)` instead.

2023-04-10 16:51 UTC, Constellation commented on Source/JavaScriptCore/runtime/ScriptExecutable.cpp
> +        if (UNLIKELY(!unlinkedCodeBlock))
Why is this necessary? If the function is `generateOrGetUnlinkedCodeBlock`, we should always call it since it becomes `get`.

2023-04-10 17:00 UTC, MenloDorian requested changes

2023-04-10 17:00 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +UnlinkedModuleProgramCodeBlock* ModuleProgramExecutable::generateOrGetUnlinkedCodeBlock(JSGlobalObject* globalObject, ThrowScope& throwScope, ParserError& error)
The best common practice is to DECLARE_THROW_SCOPE in this function itself instead of passing it in.  There are very few places where it makes sense to pass it in.  This is not one.

2023-04-10 17:00 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +    m_moduleEnvironmentSymbolTable.set(vm, this, symbolTable->cloneScopePart(globalObject->vm()));
Don't need `globalObject->vm()`.  You already have `vm`.

2023-04-10 17:00 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ScriptExecutable.cpp
> +        }
You can just `RELEASE_ASSERT(unlinkedCodeBlock)` instead in the if block after `generateOrGetUnlinkedCodeBlock` above.

2023-04-10 18:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7dc54af363d6f06c470d1e2930a290da14c17405. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 18:57 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ScriptExecutable.cpp
> +    ASSERT(unlinkedCodeBlock);
Let's do this separately as it introduces risks.

2023-04-10 19:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1bfcbc852f1738f46814818c18b153628987ca7f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 19:31 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.h
> +    UnlinkedModuleProgramCodeBlock* getUnlinkedCodeBlock(JSGlobalObject*);
nit: I would prefer that you add an enum class here like this:
```
enum class PossibleExceptionsExpected { Yes, No };
```

... and pass that into `getUnlinkedCodeBlock`.

2023-04-10 19:31 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
>      }
Here inside this if block, `RELEASE_ASSERT(possibleExceptionsExpected == PossibleExceptionsExpected::Yes)`.

2023-04-10 19:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d1e7e587baf8fb6a740b53a394428c11754f7eca. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 19:50 UTC, MenloDorian approved these changes
r=me

2023-04-10 19:50 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +    auto throwScope = DECLARE_THROW_SCOPE(vm);
nit: FYI, we don't strictly need this, since this function doesn't itself throw, its children does.  However, having it does not hurt anything.

2023-04-10 19:50 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +    executable->finishCreation(globalObject->vm());
nit: if you keep the above ThrowScope, then you can use `vm` here.

2023-04-10 19:50 UTC, MenloDorian commented on Source/JavaScriptCore/runtime/ModuleProgramExecutable.cpp
> +    RELEASE_AND_RETURN(throwScope, executable);
nit: if you remove the above ThrowScope, then make this a plain `return`.

2023-04-10 20:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/75e8f0e27d9702a92962919ebb1ed65d82802678. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12420

2023-04-10 20:54 UTC, Constellation approved these changes
r=me

2023-04-10 22:15 UTC, webkit-commit-queue commented
Committed 262788@main (e9cb06ebfbf5): <https://commits.webkit.org/262788@main>

Reviewed commits have been landed. Closing PR #12420 and removing active labels.

2023-04-10 22:15 UTC, merged