Correct PDF Plugin descriptions returned by navigator.plugins[x].description
WebKit/WebKit pull request #12512
Opened 2023-04-07 16:56 UTC by brentfulgham

#### 4df23807c1d4c8061452b36a27447a3f8b2a9f0d
<pre>
Correct PDF Plugin descriptions returned by navigator.plugins[x].description
<a href="https://bugs.webkit.org/show_bug.cgi?id=255155">https://bugs.webkit.org/show_bug.cgi?id=255155</a>
&lt;rdar://problem/107756651&gt;

Reviewed by NOBODY (OOPS!).

In Bug 254189 we corrected a bug where the name of the WebKit Built-in PDF plugin was localized
for the user&apos;s settings, which confused some anti-fraud software because the specification requires
the name to be in plain English text.

While that issue was fixed, the specification also requires a consistent English label, &quot;Portable
Document Format&quot; be returned by the &apos;description&apos; property of the plugin. This is currently localized
in Safari, leading to some anti-fraud software failing.

This patch modifies only the return value from Navigator.plugins[].description, so that other
elements of the Browser UI can correctly localize the description.

* Source/WebCore/page/Navigator.cpp:
(WebCore::Navigator::initializePluginAndMimeTypeArrays):
</pre>

2023-04-07 16:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4df23807c1d4c8061452b36a27447a3f8b2a9f0d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12512

2023-04-07 19:23 UTC, geoffreygaren approved these changes
r=me

Can you add a regression test for this?

2023-04-08 00:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eda20bc4b4667e4938b1c45e8643ccc3498c2ee3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12512

2023-04-09 23:27 UTC, karlcow requested changes
@brentfulgham the plugin test is failing.

2023-04-10 16:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/81a578a986f8d8a8e685316583a4c787a74b78ff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12512

2023-04-10 16:08 UTC, brentfulgham commented
> @brentfulgham the plugin test is failing.

I moved the test to a sub-directory, but forgot to adjust the include paths for the JS test files. Corrected in current change.

2023-04-10 17:56 UTC, brentfulgham commented
GTK's API test failures are not related to this string localization change and new web test case.

2023-04-10 18:43 UTC, webkit-commit-queue commented
Committed 262779@main (1cc30ed20c25): <https://commits.webkit.org/262779@main>

Reviewed commits have been landed. Closing PR #12512 and removing active labels.

2023-04-10 18:43 UTC, merged