Screen orientation type should be counter-clockwise
WebKit/WebKit pull request #12687
Opened 2023-04-13 05:16 UTC by marcoscaceres

#### 8e166b1b35a599890ac4b60b539e211b8540f56b
<pre>
Screen orientation type should be counter-clockwise
<a href="https://bugs.webkit.org/show_bug.cgi?id=255388">https://bugs.webkit.org/show_bug.cgi?id=255388</a>
rdar://107976966

Reviewed by NOBODY (OOPS!).

Now reports &quot;landscape-primary&quot; when the device is turned to the left and
&quot;landscape-secondary&quot; when the device is turned to the right. This matches
the behavior of the other platforms and aligns with the updated W3C Spec:
<a href="https://github.com/w3c/screen-orientation/issues/247">https://github.com/w3c/screen-orientation/issues/247</a>

* Source/WebCore/platform/ios/ScreenOrientationProviderIOS.mm:
(WebCore::ScreenOrientationProvider::platformCurrentOrientation):
* Tools/WebKitTestRunner/ios/TestControllerIOS.mm:
(WTR::TestController::lockScreenOrientation):
</pre>

2023-04-13 05:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8e166b1b35a599890ac4b60b539e211b8540f56b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12687

2023-04-13 05:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/378fb8060a13a4c00cb81ef04e61d8caf8229963. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12687

2023-04-13 05:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/95834e545e646601bafac28dd353650d0af514c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12687

2023-04-13 13:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6d84798bcf4a2d5e5f4b7d42f2bd063864c9c137. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12687

2023-04-13 20:17 UTC, cdumez requested changes
I think you'll need to update this function too:
`static UIInterfaceOrientationMask toUIInterfaceOrientationMask(WebCore::ScreenOrientationType orientation)`
in PageClientIOS.mm

2023-04-13 21:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9f173f5b37a8fdb0db985342d4f03069f0559b71. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12687

2023-04-13 21:30 UTC, cdumez approved these changes
LGTM

2023-04-14 01:12 UTC, webkit-commit-queue commented
Committed 262940@main (9a0e8865a0f5): <https://commits.webkit.org/262940@main>

Reviewed commits have been landed. Closing PR #12687 and removing active labels.

2023-04-14 01:12 UTC, merged

2023-11-18 00:34 UTC, nima-ap commented
Hey there.
In which iOS/Safari update was this released?
And in general, what is the recommended way to determine the answer to this kind of question?
I'm not able to find a mention to this fix in the official changelogs https://developer.apple.com/documentation/safari-release-notes

2024-01-27 23:37 UTC, neave commented
> Hey there. In which iOS/Safari update was this released? And in general, what is the recommended way to determine the answer to this kind of question? I'm not able to find a mention to this fix in the official changelogs https://developer.apple.com/documentation/safari-release-notes

This change was released in Safari 17 (iOS 17.0), as far as I can tell.