data: URL base64 handling different from atob()
WebKit/WebKit pull request #12693
Opened 2023-04-13 08:02 UTC by annevk

#### 2518c514c679b98cbad35cddfc51d1f3148cea13
<pre>
data: URL base64 handling different from atob()
<a href="https://bugs.webkit.org/show_bug.cgi?id=175568">https://bugs.webkit.org/show_bug.cgi?id=175568</a>
rdar://107982669

Reviewed by Alex Christensen.

We really shouldn&apos;t have different modes of decoding data: URLs.

<a href="https://bugs.webkit.org/show_bug.cgi?id=211671">https://bugs.webkit.org/show_bug.cgi?id=211671</a> fixed a set of web-platform-tests by introducing a new fetch-specific code path. It was not investigated whether the existing code path ought to be changed as well, apart from determining that there was no test coverage for the difference.

This commit adds test coverage and aligns WebKit with other browsers and the Fetch standard by removing the legacy code path altogether.

* LayoutTests/imported/w3c/web-platform-tests/fetch/data-urls/navigate.window-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/fetch/data-urls/navigate.window.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/fetch/data-urls/navigate.window.js: Added.
(forEach):
(async input):
* LayoutTests/imported/w3c/web-platform-tests/fetch/data-urls/w3c-import.log:

These changes are being upstreamed via <a href="https://github.com/web-platform-tests/wpt/pull/39542.">https://github.com/web-platform-tests/wpt/pull/39542.</a>

* Source/WebCore/loader/ResourceLoader.cpp:
(WebCore::ResourceLoader::loadDataURL):
* Source/WebCore/platform/graphics/avfoundation/objc/WebCoreAVFResourceLoader.mm:
(WebCore::DataURLResourceMediaLoader::DataURLResourceMediaLoader):
* Source/WebCore/platform/network/DataURLDecoder.cpp:
(WebCore::DataURLDecoder::decodeSynchronously):
(WebCore::DataURLDecoder::decode):
(WebCore::DataURLDecoder::decodeBase64): Deleted.
* Source/WebCore/platform/network/DataURLDecoder.h:
* Source/WebKit/NetworkProcess/soup/NetworkDataTaskSoup.cpp:
(WebKit::NetworkDataTaskSoup::resume):
* Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp:
(WebKit::WebLoaderStrategy::loadDataURLSynchronously):

Canonical link: <a href="https://commits.webkit.org/262976@main">https://commits.webkit.org/262976@main</a>
</pre>

2023-04-13 08:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a04d474a4d621a228371667a46a7c7d9c5bf7ed7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12693

2023-04-13 17:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3de0f8f9bf7a0264fe6529bf595fc2b5a3549f27. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12693

2023-04-13 20:18 UTC, achristensen07 requested changes
This should mention https://bugs.webkit.org/show_bug.cgi?id=211671 in the commit message, why we didn't do this then, and why we are doing this now.

This needs a unit test that exercises the changed behavior and a mention of how other browsers behave in the same conditions.

2023-04-14 11:31 UTC, annevk commented
Thanks for the initial review! I mainly put this up to see if the bots would discover anything I hadn't.

Per the tests I just put up at https://github.com/web-platform-tests/wpt/pull/39542 (and will incorporate in this PR later on) we do appear to be the odd one out in this behavior. I also discovered that `Base64DecodeOptions::DiscardVerticalTab` is misnamed, but that can be tackled separately.

2023-04-14 12:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b5641532a10d54dd3afc73bb54e527bac9907967. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12693

2023-04-14 16:02 UTC, achristensen07 approved these changes

2023-04-14 17:54 UTC, webkit-commit-queue commented
Committed 262976@main (2518c514c679): <https://commits.webkit.org/262976@main>

Reviewed commits have been landed. Closing PR #12693 and removing active labels.

2023-04-14 17:54 UTC, merged