[GTK] Allow using epoll-shim when eventfd is not available.
WebKit/WebKit pull request #12778
Opened 2023-04-16 15:06 UTC by ajacoutot

https://bugs.webkit.org/show_bug.cgi?id=253794

Reviewed by NOBODY (OOPS!).

OpenBSD does not have eventfd(2) but instead relies on an external implementation (library) called epoll-shim.
epoll-shim already comes with it's "read" definition which clashes with WebKit: webkitgtk40-2.39.91/webkitgtk-2.39.91/Source/WebCore/platform/graphics/iso/ISOBox.h:71:33: error: no member named 'read' in 'JSC::DataView'

Using @no-unify prevents tainting the rest of the unified code and allows the build to succeed.

* Source/WebCore/SourcesGTK.txt:

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-04-16 15:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6386f4e7cd4feee145a107c1bbc110ef5ce325ec. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12778

2023-04-21 09:04 UTC, aperezdc requested changes
@ajacoutot Thanks for the patch. The change looks good to me, but we would need the commit log formatted according to the WebKit guidelines. You will ned a bug id from [Bugzilla](https://bugs.webkit.org) and then you can use `Scripts/Tools/git-webkit commit --amend -i <bugid>` to have a commit log template prepared for you to fill, then use `Scripts/Tools/git-webkit pfr` to push the PR to GitHub 🏗️

2023-04-22 12:17 UTC, ajacoutot commented
@aperezdc hmm but I could swear I did just this.
Oh well, I will go and try again.

2023-04-22 12:23 UTC, ajacoutot commented
I don't mean to understand that stuff... I did run webkit-git setup in the past.

```
$ ./Tools/Scripts/git-webkit commit --amend -i 253794                                                
  Running status to find changed, added, or removed files.
  No changes found.
  Running status to find changed, added, or removed files.
  Reviewing diff to determine which lines changed.
  Extracting affected function names from source files.
  Change author: Antoine Jacoutot <ajacoutot@openbsd.org>.
[eng/GTK-fails-to-build-error-no-member-named-read-in-JSCDataView 0dab7f150ff7] [GTK] Allow using epoll-shim when eventfd is not available. https://bugs.webkit.org/show_bug.cgi?id=253794
 Date: Sat Apr 22 14:20:01 2023 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
$ ./Tools/Scripts/git-webkit pfr                      
branch 'main' set up to track 'origin/main'.
Downloading pycodestyle-2.5.0...
Installing pycodestyle-2.5.0...
Installed pycodestyle-2.5.0!
    Found 1 commit...
Total errors found: 0 in 1 files
'origin' is not a remote in this repository. Have you run `git-webkit setup` yet?
```

2023-04-24 10:40 UTC, aperezdc commented
@ajacoutot You may need to run `git-webkit setup` again, some things have changed in the tooling and re-running will update the configuration (no worries, you should not lose work or existing configuration, but you might be asked to create a new GitHub token).

2023-04-24 13:05 UTC, ajacoutot commented
Same thing.
I will just trash this PR and try again when I find some time.
Thanks @aperezdc

2023-04-24 13:06 UTC, closed without merging

2023-04-24 13:21 UTC, aperezdc commented
@ajacoutot I may submit this myself, crediting yoiu as the authoir of course. I hope you won't mind.

2023-04-24 13:26 UTC, ajacoutot commented
I don't mind at all :-)