[WGSL] Preserve binary operation precedence
WebKit/WebKit pull request #12796
Opened 2023-04-17 13:49 UTC by tadeuzagallo

#### a83d687f368615fff4bb4c14a826b7b043576c1b
<pre>
[WGSL] Preserve binary operation precedence
<a href="https://bugs.webkit.org/show_bug.cgi?id=255517">https://bugs.webkit.org/show_bug.cgi?id=255517</a>
rdar://108136098

Reviewed by NOBODY (OOPS!).

Binary operations should be parenthesized when serializing in order
to preserve their precedence.

* Source/WebGPU/WGSL/Metal/MetalFunctionWriter.cpp:
(WGSL::Metal::FunctionDefinitionWriter::visit):
</pre>

2023-04-17 13:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a83d687f368615fff4bb4c14a826b7b043576c1b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12796

2023-04-17 16:58 UTC, mwyrzykowski commented
Looks like a WGSL test is failing with this change

2023-04-17 22:45 UTC, djg commented
Instead of parenthesizing expressions, should we instead be introducing temporaries and writing a kind of SSA-form?

Eg. `a + b * c` becomes
```
tmp0 = b * c;
tmp1 = a + tmp0;
```

2023-04-18 04:04 UTC, djg approved these changes

2023-04-18 04:36 UTC, mwyrzykowski requested changes
Change seems fine but a WGSL test is failing

2023-04-18 07:21 UTC, tadeuzagallo commented
> Change seems fine but a WGSL test is failing

Oops, will fix it.

> Instead of parenthesizing expressions, should we instead be introducing temporaries and writing a kind of SSA-form?

We can do that, and we'll need to add a pass to modify expressions either way (e.g. we can't serialize `float % float`), but I still don't have any concrete examples of where it'd be necessary to break the expressions up. I'm not opposed at all, I was just waiting until I saw a case where it was clear to me why we'd need that, and this change was so trivial I figured we might as well fix it in the meantime.

2023-04-18 10:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d0b06779e8cbf2fc8e0dcca776ecf9229e453d19. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12796

2023-04-18 15:19 UTC, mwyrzykowski approved these changes

2023-04-18 19:52 UTC, webkit-commit-queue commented
Committed 263092@main (0efe0345caa6): <https://commits.webkit.org/263092@main>

Reviewed commits have been landed. Closing PR #12796 and removing active labels.

2023-04-18 19:52 UTC, merged