[JSC] Inline ProxyObject's "has" trap in DFG / FTL
WebKit/WebKit pull request #12849
Opened 2023-04-18 07:57 UTC by shvaikalesh

#### de353009d843a7fd3b6719604f3da8917cd16985
<pre>
[JSC] Inline ProxyObject&apos;s &quot;has&quot; trap in DFG / FTL
<a href="https://bugs.webkit.org/show_bug.cgi?id=255583">https://bugs.webkit.org/show_bug.cgi?id=255583</a>
&lt;rdar://problem/108185228&gt;

Reviewed by NOBODY (OOPS!).

This change:
  a) makes InByVariant store CallLinkStatus, adding the now necessary explicit copy constructor;
  b) makes InByStatus handle ProxyObjectAccessCase, passing down CallLinkStatus::ExitSiteData;
  c) teaches DFG to inline ProxyObjectHas access case trap as Call, as it&apos;s already done for [[Get]] and [[Set]];
  d) adds ProxyObjectHasCall type to InlineCallFrame to handle inlined call frame correctly for DFG / FTL OSR exit.

                                   ToT                      patch

proxy-has-hit                39.0235+-0.0870     ^     12.3855+-0.0213        ^ definitely 3.1507x faster
proxy-has-miss              159.1689+-0.5865     ^    111.1327+-0.3547        ^ definitely 1.4322x faster
proxy-has-miss-handler       41.5165+-0.0694     ^     10.5006+-0.0386        ^ definitely 3.9537x faster

&lt;geometric&gt;                  63.6490+-0.0969     ^     24.3581+-0.0370        ^ definitely 2.6130x faster

* JSTests/microbenchmarks/proxy-has-hit.js:
* JSTests/microbenchmarks/proxy-has-miss-handler.js:
* JSTests/microbenchmarks/proxy-has-miss.js:
* Source/JavaScriptCore/bytecode/InByStatus.cpp:
(JSC::InByStatus::computeFor):
(JSC::InByStatus::computeForStubInfo):
(JSC::InByStatus::merge):
(JSC::InByStatus::filter):
(JSC::InByStatus::dump const):
(JSC::InByStatus::computeForStubInfoWithoutExitSiteFeedback): Deleted.
* Source/JavaScriptCore/bytecode/InByStatus.h:
* Source/JavaScriptCore/bytecode/InByVariant.cpp:
(JSC::InByVariant::InByVariant):
(JSC::InByVariant::operator=):
* Source/JavaScriptCore/bytecode/InByVariant.h:
(JSC::InByVariant::callLinkStatus const):
* Source/JavaScriptCore/bytecode/InlineCallFrame.cpp:
(WTF::printInternal):
* Source/JavaScriptCore/bytecode/InlineCallFrame.h:
(JSC::InlineCallFrame::callModeFor):
(JSC::InlineCallFrame::specializationKindFor):
* Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:
(JSC::DFG::ByteCodeParser::inlineCall):
(JSC::DFG::ByteCodeParser::handleInByForProxyObject):
(JSC::DFG::ByteCodeParser::handleInById):
* Source/JavaScriptCore/dfg/DFGOSRExitCompilerCommon.cpp:
(JSC::DFG::callerReturnPC):
* Source/JavaScriptCore/runtime/JSGlobalObject.h:
* Source/JavaScriptCore/runtime/JSGlobalObjectInlines.h:
(JSC::JSGlobalObject::performProxyObjectHasFunctionConcurrently const):
</pre>

2023-04-18 07:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/de353009d843a7fd3b6719604f3da8917cd16985. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12849

2023-04-24 06:52 UTC, Constellation requested changes

2023-04-24 06:52 UTC, Constellation commented on Source/JavaScriptCore/bytecode/InByVariant.cpp
>  bool InByVariant::attemptToMerge(const InByVariant& other)
You also need to handle `m_callLinkStatus` in `attemptToMerge`, `dumpInContext`, and `finalize`. See GetByVariant implementation.

2024-10-03 08:30 UTC, shvaikalesh commented
Superseded by https://github.com/WebKit/WebKit/pull/30785.

2024-10-03 08:30 UTC, closed without merging