REGRESSION(262632@main?): [ iOS ] 2X imported/w3c/web-platform-tests/screen-orientation (layout-tests) are consistent text failures
WebKit/WebKit pull request #12909
Opened 2023-04-19 13:42 UTC by marcoscaceres

#### c560a0ffbfedde8a53297a487d29b65fabe59dec
<pre>
REGRESSION(262632@main?): [ iOS ] 2X imported/w3c/web-platform-tests/screen-orientation (layout-tests) are consistent text failures
<a href="https://bugs.webkit.org/show_bug.cgi?id=255631">https://bugs.webkit.org/show_bug.cgi?id=255631</a>
rdar://108231120

Reviewed by NOBODY (OOPS!).

The utils file didn&apos;t get updated, causing some tests to stall.
Additionally, some of the tests where not pressing on the correct (iframe) contexts.

* LayoutTests/imported/w3c/web-platform-tests/screen-orientation/nested-documents.html:
* LayoutTests/imported/w3c/web-platform-tests/screen-orientation/onchange-event-subframe.html:
* LayoutTests/imported/w3c/web-platform-tests/screen-orientation/resources/orientation-utils.js:
* LayoutTests/imported/w3c/web-platform-tests/screen-orientation/unlock.html:
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/screen-orientation/nested-documents-expected.txt:
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/screen-orientation/onchange-event-subframe-expected.txt:
* LayoutTests/platform/ios/imported/w3c/web-platform-tests/screen-orientation/unlock-expected.txt:
</pre>

2023-04-19 14:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2b2f9352b6ce3349b60251f10e8149aea782e09b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12909

2023-04-19 20:05 UTC, marcoscaceres commented
gtk failures seem unrelated.

2023-04-20 02:05 UTC, cdumez requested changes
You need to drop those tests from LayoutTests/platform/ios/TestExpectations now that you fixed them

2023-04-20 22:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a5967d9e04bc95deb99b2912eedd4ad6ea608d29. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12909

2023-04-20 22:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5b21f161d70248e0b8d84842b5a51313aa4ec6a2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12909

2023-04-20 22:31 UTC, cdumez commented on LayoutTests/platform/ios/TestExpectations
> -webkit.org/b/255704 [ Debug ] editing/inserting/insert-img-uneditable-canonical-position-crash.html [ Skip ]
Really?

2023-04-20 22:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4ce2fb2ef50ef0eee29e9dd596e43a56c857b162. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/12909

2023-04-20 22:37 UTC, marcoscaceres commented on LayoutTests/platform/ios/TestExpectations
> -webkit.org/b/255704 [ Debug ] editing/inserting/insert-img-uneditable-canonical-position-crash.html [ Skip ]
Oh! too quick. Bad rebased. All good now.

2023-04-20 22:37 UTC, cdumez approved these changes
LGTM

2023-04-21 08:58 UTC, webkit-commit-queue commented
Committed 263224@main (40235be133be): <https://commits.webkit.org/263224@main>

Reviewed commits have been landed. Closing PR #12909 and removing active labels.

2023-04-21 08:58 UTC, merged