[webkitscmpy] Generate commit message template
WebKit/WebKit pull request #13
Opened 2021-09-30 19:04 UTC by JonWBedard

#### 587d4ede9469826cba463c132052d4eae4935396
```
[webkitscmpy] Generate commit message template
https://bugs.webkit.org/show_bug.cgi?id=231023
<rdar://problem/83722871>

Reviewed by NOBODY (OOPS!).

* Tools/Scripts/git-webkit: Use prepare-ChangeLog to generate commit messages.
* Tools/Scripts/libraries/webkitcorepy/setup.py: Add inspect2 dependency.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/__init__.py: Ditto.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/mocks/local/git.py:
(Git.__init__): Add unbound status mock.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/__init__.py:
(main): Pass prepare_commit_message to sub-programs.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py:
(prepare_commit_message_main): Stand-alone function generating commit messages.
(Setup.git): If prepare_commit_message is passed, create a stand-alone
prepare-commit-msg script in .git/hooks.
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/setup_unittest.py:
(prepare_commit_message):
(TestSetup.test_commit_message):
```

2021-10-11 16:13 UTC, huskyroll requested changes
Make sure we align our internal markings for the review needing changes with GitHubs

2021-10-13 01:57 UTC, kocsenc requested changes

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/git-webkit
> +    content = []
Could probably be more descriptive here. `commit_message` maybe?

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/git-webkit
> +            if line.startswith(' ' * 8):
Not sure if worth breaking out that 8 into it's variable since it's used a couple times here.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +    if not file_name:
nit: add whitespace between the `if` statements because there is a `return` above. This is 100% style/preference but I think it helps isolate the code as a return conditional.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +        sys.stderr.write('No commit message file provided to prepare-commit-msg\n')
I doubt this would ever happen right? git will _always_ guarantee a file to write on, even if it's empty.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +        return 1
Ditto whitespace style nit.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +    with open(file_name, 'w') as file:
code smell to use keyword `file` as a variable name. Maybe just `f`? or `commit_message_file` if we wanna go more verbose.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +            prepare_commit_message = inspect.getsource(prepare_commit_message)
So, although clever, what benefits are we getting from having the `prepare-commit-msg` script a function as opposed to a standalone file?

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +            if not os.path.exists(os.path.dirname(pcm_file)):
If the `.git/hooks` path doesn't exist it means something else is wrong - we may be hiding other issues here but probably OK to leave.

2021-10-13 01:57 UTC, kocsenc commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +            with open(pcm_file, 'w') as file:
Ditto re: `file` -> `f`

2021-10-13 16:29 UTC, JonWBedard commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +            prepare_commit_message = inspect.getsource(prepare_commit_message)
Most of the time projects are defining `prepare-commit-msg`, they're only doing so for one repository. This means that you can take advantage of the fact that you know how your repository is setup up and that `.git/hooks` is in a predictable location relative to your scripts. The problem we have in `git-webkit` is that we want it to work regardless of the repository we're targeting, which means that we know where `webkitscmpy` is when we run `git-webkit setup`, but _not_ when we actually run `prepare-commit-msg`. If we generate `prepare-commit-msg` like this, it lets us embed the known location of things in `prepare-commit-msg` based on the content of `git-webkit setup`. At the moment, we're only leveraging this in `Tools/Scripts/git-webkit`, but I suspect we will leverage it here in the near future when (hopefully) `webkitscmpy` owns commit message generation directly instead of relying on a perl script.

2021-10-13 16:49 UTC, JonWBedard commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/setup.py
> +            prepare_commit_message = inspect.getsource(prepare_commit_message)
Worth calling out the other two approaches here, though: jinja templates or laying down a config file in `hooks` with information linking back to the location `git-webkit setup` is called from

2021-10-16 04:26 UTC, kocsenc approved these changes
This looks clean. It's easier to follow than the previous version with not many drawbacks. r=me

2021-10-18 16:24 UTC, huskyroll approved these changes

2021-10-18 16:27 UTC, huskyroll approved these changes
Fix the conflicts and we can land it!

2021-10-19 17:43 UTC, dewei-zhu approved these changes
r=me

2021-10-19 20:12 UTC, JonWBedard commented
Landed https://commits.webkit.org/243242@main (207619accb133fa58c610ec4a3c0d480b4e7555e)

2021-10-19 20:12 UTC, closed without merging