[EWS] Re-enable build retry for PRs
WebKit/WebKit pull request #130
Opened 2022-02-08 15:51 UTC by JonWBedard

#### a161b383ee5588146bd0295a5cad71e87ce7eabb
<pre>
[EWS] Re-enable build retry for PRs
<a href="https://bugs.webkit.org/show_bug.cgi?id=236300">https://bugs.webkit.org/show_bug.cgi?id=236300</a>
&lt;rdar://problem/88628832 &gt;

Reviewed by Aakash Jain.

* Tools/CISupport/ews-build/steps.py:
(AnalyzeCompileWebKitResults.analyzeResults): Enable retry for PRs with failing builds.
(CleanGitRepo.run): Abort any failed rebases.
* Tools/CISupport/ews-build/steps_unittest.py:

Canonical link: <a href="https://commits.webkit.org/247222@main">https://commits.webkit.org/247222@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@289737">https://svn.webkit.org/repository/webkit/trunk@289737</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

2022-02-08 19:34 UTC, jain-aakash requested changes
This seems unnecessary to add a variable/flag to enable/disable RETRIES. Changing its value with require buildbot restart. So, in production we can either keep it true or false. We should just decide which behavior we want and use that one, instead of adding ability to flip-flop between the behavior.

Maybe such behavior is needed for testing, in that case, you can probably have it as a local change on uat instance. If there is an explicit need for this, please let me know, currently the bug description and PR description doesn't specify the need for this.

2022-02-08 20:55 UTC, JonWBedard commented
> This seems unnecessary to add a variable/flag to enable/disable RETRIES. Changing its value with require buildbot restart. So, in production we can either keep it true or false. We should just decide which behavior we want and use that one, instead of adding ability to flip-flop between the behavior.
> 
> Maybe such behavior is needed for testing, in that case, you can probably have it as a local change on uat instance. If there is an explicit need for this, please let me know, currently the bug description and PR description doesn't specify the need for this.

I'm not sure if such behavior is actually needed in the long term. But it's useful for bringing up our PR queues in the immediate present. It not obvious what the right rebasing behavior is when we're testing PRs. Rather than have to re-litigate all of these "disable retries for PRs" questions if we decide to rebase PRs in EWS, we can just flip the flag.

2022-02-11 18:20 UTC, JonWBedard commented
I re-purposed this PR, we really just need to re-enable the retry once #135 lands

2022-02-11 23:11 UTC, jain-aakash approved these changes

2022-02-14 04:24 UTC, JonWBedard commented
https://ews-build.webkit-uat.org/#/builders/45/builds/104 is a good example of this on the UAT instance, before I land it tomorrow morning.

2022-02-14 15:28 UTC, merged

2022-02-14 15:28 UTC, JonWBedard commented
Landed https://commits.webkit.org/247222@main (a161b383ee5588146bd0295a5cad71e87ce7eabb)!