Drop unnecessary NodeWithIndex::m_haveIndex data member
WebKit/WebKit pull request #13072
Opened 2023-04-22 19:29 UTC by Ahmad-S792

<pre>
Drop unnecessary NodeWithIndex::m_haveIndex data member
<a href="https://bugs.webkit.org/show_bug.cgi?id=255829">https://bugs.webkit.org/show_bug.cgi?id=255829</a>

Reviewed by NOBODY (OOPS!).

Merge - <a href="https://chromium.googlesource.com/chromium/blink/+/4534831b29f809b7b6c6a6b1e61d716c854035ca">https://chromium.googlesource.com/chromium/blink/+/4534831b29f809b7b6c6a6b1e61d716c854035ca</a>

Drop unnecessary NodeWithIndex::m_haveIndex data member. Since
Node::computeNodeIndex() returns an unsigned integer but NodeWithIndex::m_index is
signed, we can simply set m_index to -1 until it is lazily set.

* Source/WebCore/dom/NodeWithIndex.h: As above
</pre>

2023-04-22 19:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/53aee6c9d8b39eb4742894b34449a22bfa11478e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13072

2023-04-22 20:50 UTC, cdumez requested changes
We prefer to avoid special values like this. You could switch to using Markable though if you would like to avoid the extra data member.

2023-04-22 20:59 UTC, cdumez commented
I think using `Markable<unsigned>` would likely be appropriate here.

2023-04-26 04:18 UTC, rniwa commented on Source/WebCore/dom/NodeWithIndex.h
>      mutable int m_index;
We should use Markable for this.

2023-04-26 04:38 UTC, cdumez commented on Source/WebCore/dom/NodeWithIndex.h
>      mutable int m_index;
What I said :p

2023-06-02 23:50 UTC, closed without merging