[JSC] JSON.parse should use simple recursion until it hits soft-recursion threshold
WebKit/WebKit pull request #13480
Opened 2023-05-05 04:21 UTC by Constellation

#### 13b815d697614e7578f2ce2f40712a779af8c25e
<pre>
[JSC] JSON.parse should use simple recursion until it hits soft-recursion threshold
<a href="https://bugs.webkit.org/show_bug.cgi?id=256349">https://bugs.webkit.org/show_bug.cgi?id=256349</a>
rdar://108930906

Reviewed by NOBODY (OOPS!).

Let&apos;s do super simple JSON.parse until it hits soft-recursion threshold. Our existing code
handles JSON.parse without recursion, this is great, but it is very complicated. And most of
JSON can be parsed with recursion with the current stack capacity. Let&apos;s start with super
simple recursion path, and check soft stack limit carefully. And if we hit, then stop the
recursion and fallback to our generic code. Good thing is that JSON&apos;s leaf object creation
is isolated, so we can start this generic code at any time. We can repeatedly enter and exit
this.

* Source/JavaScriptCore/runtime/LiteralParser.cpp:
(JSC::LiteralParser&lt;CharType&gt;::tryJSONPParse):
(JSC::LiteralParser&lt;CharType&gt;::Lexer::next):
(JSC::LiteralParser&lt;CharType&gt;::parseRecursivelyEntry):
(JSC::LiteralParser&lt;CharType&gt;::parseRecursively):
(JSC::LiteralParser&lt;CharType&gt;::parse):
* Source/JavaScriptCore/runtime/LiteralParser.h:
(JSC::LiteralParser::tryLiteralParse):
</pre>

2023-05-05 04:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13b815d697614e7578f2ce2f40712a779af8c25e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 05:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/40f007659f49717fd731fc38294f97d9fbc96159. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 05:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cc31a6a5f4e672720e0a439f6e08826b01da264e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 05:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6e1d8cc46b4b614c7335eac6bcec8f2cdc5da578. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 05:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/815f6671de118f17f2b3780a9e6fff5b85b82be5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 07:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6806709246793a337f03388402d7e8ba7f282d83. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 18:07 UTC, aproskuryakov requested changes
With this PR, we lose basically all automated testing for the complex code path, which seems not OK.

I think that WebKitTestRunner has to disable the fast path by default, and have a test or two to explicitly verify that it works. And probably something for JSC tests too.

2023-05-05 18:27 UTC, shvaikalesh approved these changes

2023-05-05 18:28 UTC, shvaikalesh commented
+1 on what Alexey said, yet r=me on the logic itself.

2023-05-05 22:57 UTC, Constellation commented
> With this PR, we lose basically all automated testing for the complex code path, which seems not OK.
> 
> I think that WebKitTestRunner has to disable the fast path by default, and have a test or two to explicitly verify that it works. And probably something for JSC tests too.

Sounds good to add option for testing. I think the opposite testing environment will be better: fast path by default, and adding tests for the slow path since the actual user configuration is fast path.

2023-05-05 23:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/965e60c717c0bc3645d7e0b0f1293dad52339bc0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13480

2023-05-05 23:17 UTC, aproskuryakov approved these changes

2023-05-06 02:34 UTC, webkit-commit-queue commented
Committed 263744@main (3a9af6136197): <https://commits.webkit.org/263744@main>

Reviewed commits have been landed. Closing PR #13480 and removing active labels.

2023-05-06 02:34 UTC, merged