Remove NetworkResourceLoader::m_resultingClientIdentifier
WebKit/WebKit pull request #13490
Opened 2023-05-05 08:29 UTC by youennf

#### adc8537fffdbdbf4c15e1005cab0bfe863bedaf0
<pre>
Remove NetworkResourceLoader::m_resultingClientIdentifier
<a href="https://bugs.webkit.org/show_bug.cgi?id=256357">https://bugs.webkit.org/show_bug.cgi?id=256357</a>
rdar://problem/108937686

Reviewed by NOBODY (OOPS!).

We no longer need NetworkResourceLoader::m_resultingClientIdentifier:
- We are consistently storing the identifier inside NetworkResourceLoader parameters.
- On same origin redirections, we reuse the same identifier and are doing so even if transferring to another web process.
- On cross origin redirections, we should not reuse the same identifier and use a different NetworkResourceLoader.

* Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp:
(WebKit::ServiceWorkerFetchTask::startFetch):
* Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerConnection.cpp:
(WebKit::WebSWServerConnection::createFetchTask):
</pre>

2023-05-05 08:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/adc8537fffdbdbf4c15e1005cab0bfe863bedaf0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13490

2023-05-05 12:09 UTC, youennf commented
http/tests/privateClickMeasurement/ failure is unrelated

2023-05-12 14:28 UTC, achristensen07 requested changes
I would expect a change in NetworkResourceLoader.h too

2023-05-12 14:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ab8728a53cf7ec9a9da0bfae12fab01f7265c33e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13490

2023-05-23 16:29 UTC, achristensen07 approved these changes

2023-05-24 06:48 UTC, webkit-commit-queue commented
Committed 264461@main (fd2fc6d0680b): <https://commits.webkit.org/264461@main>

Reviewed commits have been landed. Closing PR #13490 and removing active labels.

2023-05-24 06:48 UTC, merged