disable enforcement of audio/video sink setup for some platforms
WebKit/WebKit pull request #13612
Opened 2023-05-09 00:01 UTC by emutavchi

#### bf72c0513747ae58d98bc5e5eb42abf5e847d9d2
<pre>
disable enforcement of audio/video sink setup for some platforms

This solves several cases:

- secondary (video only/pip) playback: audio sink allocates resources in
ready state (as part of auto audio sink detection), which interferes
with the main playback.

- &quot;external&quot; playback, or playback with other sink elements: in this
case we want playbin2 to autoplug needed elements.

<a href="https://bugs.webkit.org/show_bug.cgi?id=256482">https://bugs.webkit.org/show_bug.cgi?id=256482</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:
(WebCore::MediaPlayerPrivateGStreamer::createAudioSink):
(WebCore::MediaPlayerPrivateGStreamer::gstreamerPositionFromSinks const):
(WebCore::MediaPlayerPrivateGStreamer::handleMessage):
(WebCore::MediaPlayerPrivateGStreamer::createHolePunchVideoSink):
</pre>

2023-05-09 00:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bf72c0513747ae58d98bc5e5eb42abf5e847d9d2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13612

2023-05-09 14:48 UTC, calvaris requested changes
Title of the PR has to be in the first line of the commit log. Bug URL has to be in the second line of the log. After these two lines you need to have `Reviewed by NOBODY (OOPS!).`, then the bug explanation (remove the second OOPS line as you already have the explanation.

Please, check some other commits to have an idea of how to do it.

2023-05-09 14:48 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +                // Detect a audio sink element
Comment needs to end with a .

2023-05-09 14:49 UTC, calvaris commented
Ah, and PR title, first line of the commit log and title of the bugzilla bug have to be the same.

2023-05-09 18:43 UTC, emutavchi commented
@calvaris I've updated the PR. hopefully I got it right this time.

2023-05-10 11:49 UTC, calvaris approved these changes
One you push the list last change, I'll already ask the merge queue to merge it. Thanks.

2023-05-10 11:49 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +                // Detect a audio sink element.
Sorry to not have noticed this before because I asked you already once to change this line:

Detect "an" audio sink element.

2023-05-11 11:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b4bf638e839558cb17f8fa639272a39601100895. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13612

2023-05-11 11:39 UTC, emutavchi commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +                // Detect a audio sink element.
Done

2023-05-11 15:32 UTC, calvaris approved these changes

2023-05-11 16:24 UTC, webkit-commit-queue commented
Committed 263972@main (bfa95384feb8): <https://commits.webkit.org/263972@main>

Reviewed commits have been landed. Closing PR #13612 and removing active labels.

2023-05-11 16:25 UTC, merged