[WebGPU] Rename the setting from just "WebGPU" to "WebGPUEnabled"
WebKit/WebKit pull request #13680
Opened 2023-05-10 04:46 UTC by litherum

#### 859b4e5a603743d4fb5065a01720211b3e371733
<pre>
[WebGPU] Rename the setting from just &quot;WebGPU&quot; to &quot;WebGPUEnabled&quot;
<a href="https://bugs.webkit.org/show_bug.cgi?id=256575">https://bugs.webkit.org/show_bug.cgi?id=256575</a>
rdar://109134933

Reviewed by NOBODY (OOPS!).

This is so we can say settings().webGPUEnabled() instead of settings().webGPU(),
which is a bit more ergonomic.

* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WebCore/Modules/WebGPU/GPU.idl:
* Source/WebCore/Modules/WebGPU/GPUAdapter.idl:
* Source/WebCore/Modules/WebGPU/GPUAdapterInfo.idl:
* Source/WebCore/Modules/WebGPU/GPUAddressMode.idl:
* Source/WebCore/Modules/WebGPU/GPUAutoLayoutMode.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroup.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroupDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroupEntry.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroupLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroupLayoutDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUBindGroupLayoutEntry.idl:
* Source/WebCore/Modules/WebGPU/GPUBlendComponent.idl:
* Source/WebCore/Modules/WebGPU/GPUBlendFactor.idl:
* Source/WebCore/Modules/WebGPU/GPUBlendOperation.idl:
* Source/WebCore/Modules/WebGPU/GPUBlendState.idl:
* Source/WebCore/Modules/WebGPU/GPUBuffer.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferBinding.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferBindingLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferBindingType.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferMapState.idl:
* Source/WebCore/Modules/WebGPU/GPUBufferUsage.idl:
* Source/WebCore/Modules/WebGPU/GPUCanvasCompositingAlphaMode.idl:
* Source/WebCore/Modules/WebGPU/GPUCanvasConfiguration.idl:
* Source/WebCore/Modules/WebGPU/GPUColorDict.idl:
* Source/WebCore/Modules/WebGPU/GPUColorTargetState.idl:
* Source/WebCore/Modules/WebGPU/GPUColorWrite.idl:
* Source/WebCore/Modules/WebGPU/GPUCommandBuffer.idl:
* Source/WebCore/Modules/WebGPU/GPUCommandBufferDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUCommandEncoder.idl:
* Source/WebCore/Modules/WebGPU/GPUCommandEncoderDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUCommandsMixin.idl:
* Source/WebCore/Modules/WebGPU/GPUCompareFunction.idl:
* Source/WebCore/Modules/WebGPU/GPUCompilationInfo.idl:
* Source/WebCore/Modules/WebGPU/GPUCompilationMessage.idl:
* Source/WebCore/Modules/WebGPU/GPUCompilationMessageType.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePassDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePassEncoder.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePassTimestampLocation.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePassTimestampWrite.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePipeline.idl:
* Source/WebCore/Modules/WebGPU/GPUComputePipelineDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUCullMode.idl:
* Source/WebCore/Modules/WebGPU/GPUDebugCommandsMixin.idl:
* Source/WebCore/Modules/WebGPU/GPUDepthStencilState.idl:
* Source/WebCore/Modules/WebGPU/GPUDevice.idl:
* Source/WebCore/Modules/WebGPU/GPUDeviceDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUDeviceLostInfo.idl:
* Source/WebCore/Modules/WebGPU/GPUDeviceLostReason.idl:
* Source/WebCore/Modules/WebGPU/GPUErrorFilter.idl:
* Source/WebCore/Modules/WebGPU/GPUExtent3DDict.idl:
* Source/WebCore/Modules/WebGPU/GPUExternalTexture.idl:
* Source/WebCore/Modules/WebGPU/GPUExternalTextureBindingLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUExternalTextureDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUFeatureName.idl:
* Source/WebCore/Modules/WebGPU/GPUFilterMode.idl:
* Source/WebCore/Modules/WebGPU/GPUFragmentState.idl:
* Source/WebCore/Modules/WebGPU/GPUFrontFace.idl:
* Source/WebCore/Modules/WebGPU/GPUImageCopyBuffer.idl:
* Source/WebCore/Modules/WebGPU/GPUImageCopyExternalImage.idl:
* Source/WebCore/Modules/WebGPU/GPUImageCopyTexture.idl:
* Source/WebCore/Modules/WebGPU/GPUImageCopyTextureTagged.idl:
* Source/WebCore/Modules/WebGPU/GPUImageDataLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUIndexFormat.idl:
* Source/WebCore/Modules/WebGPU/GPUInternalError.idl:
* Source/WebCore/Modules/WebGPU/GPULoadOp.idl:
* Source/WebCore/Modules/WebGPU/GPUMapMode.idl:
* Source/WebCore/Modules/WebGPU/GPUMipmapFilterMode.idl:
* Source/WebCore/Modules/WebGPU/GPUMultisampleState.idl:
* Source/WebCore/Modules/WebGPU/GPUObjectBase.idl:
* Source/WebCore/Modules/WebGPU/GPUObjectDescriptorBase.idl:
* Source/WebCore/Modules/WebGPU/GPUOrigin2DDict.idl:
* Source/WebCore/Modules/WebGPU/GPUOrigin3DDict.idl:
* Source/WebCore/Modules/WebGPU/GPUOutOfMemoryError.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineBase.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineDescriptorBase.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineError.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineErrorInit.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineErrorReason.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUPipelineLayoutDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUPowerPreference.idl:
* Source/WebCore/Modules/WebGPU/GPUPredefinedColorSpace.idl:
* Source/WebCore/Modules/WebGPU/GPUPrimitiveState.idl:
* Source/WebCore/Modules/WebGPU/GPUPrimitiveTopology.idl:
* Source/WebCore/Modules/WebGPU/GPUProgrammablePassEncoder.idl:
* Source/WebCore/Modules/WebGPU/GPUProgrammableStage.idl:
* Source/WebCore/Modules/WebGPU/GPUQuerySet.idl:
* Source/WebCore/Modules/WebGPU/GPUQuerySetDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUQueryType.idl:
* Source/WebCore/Modules/WebGPU/GPUQueue.idl:
* Source/WebCore/Modules/WebGPU/GPURenderBundle.idl:
* Source/WebCore/Modules/WebGPU/GPURenderBundleDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPURenderBundleEncoder.idl:
* Source/WebCore/Modules/WebGPU/GPURenderBundleEncoderDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPURenderEncoderBase.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassColorAttachment.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassDepthStencilAttachment.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassEncoder.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassLayout.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassTimestampLocation.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPassTimestampWrite.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPipeline.idl:
* Source/WebCore/Modules/WebGPU/GPURenderPipelineDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPURequestAdapterOptions.idl:
* Source/WebCore/Modules/WebGPU/GPUSampler.idl:
* Source/WebCore/Modules/WebGPU/GPUSamplerBindingLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUSamplerBindingType.idl:
* Source/WebCore/Modules/WebGPU/GPUSamplerDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUShaderModule.idl:
* Source/WebCore/Modules/WebGPU/GPUShaderModuleCompilationHint.idl:
* Source/WebCore/Modules/WebGPU/GPUShaderModuleDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUShaderStage.idl:
* Source/WebCore/Modules/WebGPU/GPUStencilFaceState.idl:
* Source/WebCore/Modules/WebGPU/GPUStencilOperation.idl:
* Source/WebCore/Modules/WebGPU/GPUStorageTextureAccess.idl:
* Source/WebCore/Modules/WebGPU/GPUStorageTextureBindingLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUStoreOp.idl:
* Source/WebCore/Modules/WebGPU/GPUSupportedFeatures.idl:
* Source/WebCore/Modules/WebGPU/GPUSupportedLimits.idl:
* Source/WebCore/Modules/WebGPU/GPUTexture.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureAspect.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureBindingLayout.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureDimension.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureFormat.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureSampleType.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureUsage.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureView.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureViewDescriptor.idl:
* Source/WebCore/Modules/WebGPU/GPUTextureViewDimension.idl: [...]

2023-05-10 04:47 UTC, smfr approved these changes

2023-05-10 04:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/859b4e5a603743d4fb5065a01720211b3e371733. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13680

2023-05-11 17:10 UTC, mwyrzykowski requested changes
This seems to cause a regression in the tests:

FAIL :serialize: assert_unreached:
 3  - EXCEPTION: WebGPU device failed to initialize with Error "No WebGPU implementation found"; not retrying
 4    assert@http://127.0.0.1:8000/webgpu/common/util/util.js:37:20

2023-05-12 21:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0e17518984ae0ea83f16e00101ce8ac0af15b59d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13680

2023-05-12 22:14 UTC, mwyrzykowski approved these changes

2023-05-12 22:48 UTC, webkit-commit-queue commented
Committed 264033@main (529569b68016): <https://commits.webkit.org/264033@main>

Reviewed commits have been landed. Closing PR #13680 and removing active labels.

2023-05-12 22:48 UTC, merged