Fix off-by-one in WTF::findIgnoringASCIICaseWithoutLength
WebKit/WebKit pull request #13710
Opened 2023-05-10 19:47 UTC by jjgriego

#### cdf5f4bc3f5cd29f071a1888d41d55e22d1a2ef4
<pre>
Fix off-by-one in WTF::findIgnoringASCIICaseWithoutLength
<a href="https://bugs.webkit.org/show_bug.cgi?id=256606">https://bugs.webkit.org/show_bug.cgi?id=256606</a>

A needle identical to the haystack won&apos;t be found by this function because of
the length comparison used. Luckily, this function is unused except in testb3,
so nothing else really needs to be changed.

* Source/WTF/wtf/text/StringCommon.h:
(WTF::findIgnoringASCIICaseWithoutLength):
</pre>

2023-05-10 21:03 UTC, Ahmad-S792 commented
@jjgriego - Missing `Reviewed by NOBODY (OOPS!).` line in commit message.

2023-05-10 21:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13a5c681c87eaf8fb8d932b9bd4db4d4df78aef5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13710

2023-05-10 21:05 UTC, jjgriego commented
> @jjgriego - Missing `Reviewed by NOBODY (OOPS!).` line in commit message.

oof, fixed; thanks

2023-05-10 23:31 UTC, pxlcoder commented on Source/WTF/wtf/text/StringCommon.h
> +    return matchLength <= searchLength ? findIgnoringASCIICase(source, matchCharacters, 0, searchLength, matchLength) : notFound;
Can we add a test for this in `Tools/TestWebKitAPI/Tests/WTF/StringCommon.cpp`?

2023-05-10 23:36 UTC, cdumez requested changes
Needs a test.

2023-05-11 21:13 UTC, cdumez commented
@jjgriego Are you able to add the following API test to `Tools/TestWebKitAPI/Tests/WTF/StringCommon.cpp`?
```
TEST(WTF_StringCommon, FindIgnoringASCIICaseWithoutLengthFullMatch)
{
    EXPECT_EQ(WTF::findIgnoringASCIICaseWithoutLength("foo", "foo"), 0U);
}
```

Should be enough to get this patch landed.

2023-05-15 20:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/95820d6f851e15ed1f3e6c3a6be539bbba765c7a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13710

2023-05-15 20:08 UTC, jjgriego commented
Done, sorry for the delay

2023-05-15 20:11 UTC, cdumez approved these changes
LGTM

2023-05-15 20:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4ec75e9aa552455a3ff2c87a7fb4705c92606190. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13710

2023-05-15 23:20 UTC, webkit-commit-queue commented
Committed 264088@main (d565c2070f7a): <https://commits.webkit.org/264088@main>

Reviewed commits have been landed. Closing PR #13710 and removing active labels.

2023-05-15 23:20 UTC, merged