[css-grid][masonry] Containing block for items in a masonry columns grid should be the grid's content box logical width
WebKit/WebKit pull request #13720
Opened 2023-05-10 21:21 UTC by sgill26

#### 2e6fb8fd76bbe3a5921a0f92618c349023a3e10c
<pre>
[css-grid][masonry] Containing block for items in a masonry columns grid should be the grid&apos;s content box logical width
<a href="https://bugs.webkit.org/show_bug.cgi?id=256611">https://bugs.webkit.org/show_bug.cgi?id=256611</a>
rdar://109170495

Reviewed by NOBODY (OOPS!).

The masonry spec states, &quot;The containing block for a grid item is
formed by its grid area in the grid axis and the grid container’s
content-box in the masonry axis.&quot;

This means that for a grid that has masonry columns specified, the
masonry axis will be in the logical width direction of the grid. The
items should have their containing block set to the content box logical
box of the grid.

We can modify GridTrackSizingAlgorithm::gridAreaBreadthForChild to
return this value when the grid is a masonry columns grid since normally
the grid area would be used as the containing block in non-masonry
grids. This allows the rest of the code to use the grid area sizes of
the containing block in both masonry and non-masonry scenarios.
Previously, this function would have attempted to compute the
value by iterating over the tracks in the specified direction, but there
are no tracks in the masonry direction so we use the logic specified by
the masonry spec instead.

However, in order for this change to work properly we had to make a
change in RenderGrid::layoutMasonry by removing code that was
incorrectly overriding the logical width of the grid. The previous code
was attempting to set the logical width of the grid to the masonry
content size when the grid had masonry columns specified and an auto
logical width. There were 2 main issues with this piece of code:
1.) m_masonryLayout.gridContentSize() will always return 0 since we
actually haven&apos;t performed masonry layout at this point
2.) The grid shouldn&apos;t be overriding its logical width like this anyways
and it should instead be set by sized by the rules of the formatting
context it is participating in (e.g. block or inline layout).

By removing this code we can get the actual width of the grid later on
when we call m_renderGrid-&gt;contentLogicalWidth() rather than the
incorrect 0 value that it was being set to.

The following example highlights the changes that were made.
&lt;style&gt;
grid {
    display: grid;
    grid-template-columns:masonry;
    grid-template-rows: auto;
}
&lt;/style&gt;
&lt;grid&gt;
    &lt;svg width=&quot;100&quot; height=&quot;100&quot; viewBox=&quot;0 0 1 1&quot; style=&quot;width: 100%; max-width: 100px; background: green;&quot;&gt;&lt;/svg&gt;
&lt;/grid&gt;

By removing the extra code in RenderGrid::layoutMasonry, the grid will
get sizes as a block level box in the block formatting context it is
participating in, giving it a logical width that takes up its available
space. The svg&apos;s containing block logical width is set to its value so
it is able to resolve its percentage width to the correct value whereas
before the containing block logical width would have been 0px.

<a href="https://drafts.csswg.org/css-grid-3/#containing-block">https://drafts.csswg.org/css-grid-3/#containing-block</a>

* LayoutTests/TestExpectations:
* LayoutTests/imported/w3c/web-platform-tests/css/css-grid/masonry/tentative/masonry-columns-item-containing-block-is-grid-content-width-expected.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-grid/masonry/tentative/masonry-columns-item-containing-block-is-grid-content-width.html: Added.
* Source/WebCore/rendering/GridTrackSizingAlgorithm.cpp:
(WebCore::GridTrackSizingAlgorithm::gridAreaBreadthForChild const):
* Source/WebCore/rendering/GridTrackSizingAlgorithm.h:
* Source/WebCore/rendering/RenderGrid.cpp:
(WebCore::RenderGrid::layoutMasonry):
</pre>

2023-05-10 21:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2e6fb8fd76bbe3a5921a0f92618c349023a3e10c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13720

2023-05-10 22:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/01f0bec180ede5b961c03a3d9cb9b9b4475bf01d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13720

2023-05-11 22:20 UTC, mattwoodrow approved these changes

2023-05-11 22:32 UTC, stwrt requested changes
Still reviewing this. Just noticed this small thing so far.

2023-05-11 22:32 UTC, stwrt commented on Source/WebCore/rendering/GridTrackSizingAlgorithm.cpp
> +        return m_renderGrid->contentLogicalWidth();
Add new line here.

2023-05-11 23:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a7a8f8e10fb64fac1d641a7e1d4067a2ddbc16f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13720

2023-05-12 14:41 UTC, webkit-commit-queue commented
Committed 264011@main (ff409be22993): <https://commits.webkit.org/264011@main>

Reviewed commits have been landed. Closing PR #13720 and removing active labels.

2023-05-12 14:41 UTC, merged