???
WebKit/WebKit pull request #13866
Opened 2023-05-14 23:24 UTC by mattwoodrow

#### 254bbc29a13819e2ce3ddfe68e6de977ab438c69
<pre>
???
</pre>

2023-05-14 23:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/254bbc29a13819e2ce3ddfe68e6de977ab438c69. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/13866

2023-05-15 06:46 UTC, dcrousso requested changes
the primary purpose of the Graphics Tab (and really Web Inspector in general) is to be able to help expose what's happening at the API boundary between JS and WebKit (specifically WebCore in this case).  we try not to expose information that is an internal implementation detail of WebKit or things not usable/actionable/etc. by the developer as if there is nothing for the developer to do with the information then ultimately we've not actually helped them.

is `PlaceholderRenderingContext` actually exposed to the web anywhere?  or is it just something that WebKit uses internally for `transferControlToOffscreen`?

if the former, you'll also need to add `InspectorInstrumentation` hooks inside `PlaceholderRenderingContext` in order for this to actually work.  i'd recommend adding a test similar to `LayoutTests/inspector/canvas/create-context-2d.html` to verify that this is necessary and working correctly.

if the latter, i dont think we should bother exposing it in Web Inspector as doing so would not provide any benefit to the developer since there's nothing they could do with that information

AFAICT from looking at WebKit code right now, it seems like the latter

2023-05-15 21:20 UTC, mattwoodrow commented
> the primary purpose of the Graphics Tab (and really Web Inspector in general) is to be able to help expose what's happening at the API boundary between JS and WebKit (specifically WebCore in this case). we try not to expose information that is an internal implementation detail of WebKit or things not usable/actionable/etc. by the developer as if there is nothing for the developer to do with the information then ultimately we've not actually helped them.
> 
> is `PlaceholderRenderingContext` actually exposed to the web anywhere? or is it just something that WebKit uses internally for `transferControlToOffscreen`?
> 
> if the former, you'll also need to add `InspectorInstrumentation` hooks inside `PlaceholderRenderingContext` in order for this to actually work. i'd recommend adding a test similar to `LayoutTests/inspector/canvas/create-context-2d.html` to verify that this is necessary and working correctly.
> 
> if the latter, i dont think we should bother exposing it in Web Inspector as doing so would not provide any benefit to the developer since there's nothing they could do with that information
> 
> AFAICT from looking at WebKit code right now, it seems like the latter

It is indeed the latter, the spec says that the canvas goes into 'placeholder' mode, but there's no exposed rendering context for that type.

I thought it was somewhat weird that the author would know they have an HTMLCanvas DOM object (which displays visible content onscreen), but not have it show up in the inspector's list of canvases at all.

The current patch makes it appear in the graphics tab (and show what content it contains), but doesn't support recording or any useful actions (since as you say, there aren't any).

I'm more than happy to change this patch to just avoid the crash (which I think is debug builds only), and continue to not expose these canvases if you think that's preferable.

2023-05-15 21:21 UTC, mattwoodrow commented
Maybe it'd be better to handle the OffscreenCanvas properly, and just add some notation/breadcrumb to it that shows the link to the (placeholder) HTMLCanvas.

2023-05-16 17:28 UTC, dcrousso commented
> I'm more than happy to change this patch to just avoid the crash (which I think is debug builds only), and continue to not expose these canvases if you think that's preferable.

yeah IMO if there's nothing for the developer to do then i'd probably err on the side of not showing anything at all

FWIW a `<canvas>` that has not yet called `getContext` will not appear in the Graphics Tab either, so it's perhaps a bit not entirely out of left field to show nothing for things that dont have anything actionable

2023-05-18 01:54 UTC, closed without merging