REGRESSION(2.41.x): [GTK] Crash in GraphicsContextGLGBM::allocateDrawBufferObject
WebKit/WebKit pull request #14066
Opened 2023-05-19 10:27 UTC by carlosgcampos

#### 765bc240e5a4ba66393cd067140bc1c47233ca68
<pre>
REGRESSION(2.41.x): [GTK] Crash in GraphicsContextGLGBM::allocateDrawBufferObject
<a href="https://bugs.webkit.org/show_bug.cgi?id=255398">https://bugs.webkit.org/show_bug.cgi?id=255398</a>

Reviewed by NOBODY (OOPS!).

GBMBufferSwapchain::getBuffer() can return nullptr for several reasons,
so we need to handle that case in
GraphicsContextGLGBM::allocateDrawBufferObject(). This also adds error
messages for the cases where getBuffer() returns nullptr, and returns
earlier without creating any buffer when the given format is
unsupported.

* Source/WebCore/platform/graphics/gbm/GBMBufferSwapchain.cpp:
(WebCore::isBufferFormatSupported):
(WebCore::GBMBufferSwapchain::getBuffer):
* Source/WebCore/platform/graphics/gbm/GraphicsContextGLGBM.cpp:
(WebCore::GraphicsContextGLGBM::allocateDrawBufferObject):
</pre>

2023-05-19 10:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/765bc240e5a4ba66393cd067140bc1c47233ca68. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14066

2023-05-22 06:50 UTC, zdobersek requested changes

2023-05-22 06:50 UTC, zdobersek commented on Source/WebCore/platform/graphics/gbm/GBMBufferSwapchain.cpp
> +    }
This position can unnecessarily leave live buffer objects that would otherwise be destroyed in the next if-clause.

2023-05-25 14:43 UTC, mcatanzaro commented
I'm not sure if this is actually a regression from 2.41.1 after all, so I've removed that from the title of the bug. I might have assumed so because of GBM stuff in the backtrace.

2023-05-25 16:20 UTC, mcatanzaro commented
Tested this. Confirmed the bug is fixed.

2023-05-26 05:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f7a6eb2923fff231499c9d1d79ce31988244395b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14066

2023-05-26 15:51 UTC, mcatanzaro approved these changes
I think we should land this now to get it into the imminent 2.40.2 release. Zan, if this lands before you get a chance to provide further feedback, Carlos will need to follow up.

2023-05-29 07:57 UTC, webkit-commit-queue commented
Committed 264648@main (153153309cef): <https://commits.webkit.org/264648@main>

Reviewed commits have been landed. Closing PR #14066 and removing active labels.

2023-05-29 07:57 UTC, merged