???
WebKit/WebKit pull request #14308
Opened 2023-05-24 21:38 UTC by mwyrzykowski

#### 50df9469317c22c6c03c42e76e396dc61db04e09
<pre>
???
</pre>

2023-05-24 21:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/50df9469317c22c6c03c42e76e396dc61db04e09. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14308

2023-05-24 22:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4f4c30f9e8e95d5cf0dc4cc7447b06a0d20fa22f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14308

2023-05-24 22:26 UTC, grorg approved these changes
Could you add to the commit message that the reason you're doing the swizzling is that this is an SPI we can't yet put into the ANGLE project?

2023-05-24 22:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/98bc09bc990f65f6f85f6b7a330b8808cdbf40d3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14308

2023-05-25 07:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/80be443f3c5a0349d443d755f81e152e4ed52ce4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14308

2023-05-25 11:24 UTC, kkinnunen-apple requested changes
I think this will affect all command queues, not just WebGL ones.
Maybe we should really correctly plumb this through the ANGLE?

2023-05-25 15:38 UTC, kkinnunen-apple commented
I can check if I can mock up EGL_IMG_context_priority tomorrow

2023-10-20 17:40 UTC, mwyrzykowski commented
I don't think this is needed, closing

2023-10-20 17:40 UTC, closed without merging