Add `-printir` flag to testb3.
WebKit/WebKit pull request #14304
Opened 2023-05-24 20:00 UTC by jjgriego

#### 762f3d761602ac4518e4baf1d387213ff2c104ea
<pre>
Add `-printir` flag to testb3.
<a href="https://bugs.webkit.org/show_bug.cgi?id=257277">https://bugs.webkit.org/show_bug.cgi?id=257277</a>

Reviewed by NOBODY (OOPS!).

For verifying the changes we&apos;d like to make to testb3, we need the initial B3
graph of each procedure compiled during the test.

This isn&apos;t easily achieved with existing runtime options;
`dumpGraphAfterEachPhase` produces much more output than is needed to verify the
changes to testb3, setting only the `shouldDumpIR` flag on the procedure
achieves the desired behavior.

If needed, we can make things work without this but it&apos;s relatively simple.

* Source/JavaScriptCore/b3/B3Procedure.h:
* Source/JavaScriptCore/b3/testb3.h:
(compileProc):
* Source/JavaScriptCore/b3/testb3_1.cpp:
(main):
</pre>
https://github.com/WebKit/WebKit/commit/762f3d761602ac4518e4baf1d387213ff2c104ea

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/7793 "1 style error") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/8067 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/8248 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/9435 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/7941 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/10057 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/7987 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/10803 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/7930 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/9038 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/7144 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/9547 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/6346 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/10/builds/7093 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/14752 "Passed tests") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/6653 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/7492 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/7220 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/10621 "Passed tests") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/7377 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/7716 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/17/builds/6288 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/7951 "Built successfully") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/7042 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/1818 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/11252 "Built successfully") | | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/24/builds/8164 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/7448 "Built successfully") | | [✅ 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/3/builds/1966 "Passed tests") |

2023-05-26 03:30 UTC, Constellation requested changes
We should not have

2023-05-26 03:30 UTC, Constellation commented on Source/JavaScriptCore/b3/testb3.h
> +inline bool g_dumpB3AfterGeneration = false;
This looks wrong. This kind of this should be represented as Options.

2023-05-26 03:30 UTC, Constellation commented on Source/JavaScriptCore/b3/testb3_1.cpp
> +            g_dumpB3AfterGeneration = true;
And if there is an option, this flag is not necessary. We can just pass an option via environment variable.

2023-07-26 19:23 UTC, jjgriego commented
Will re-submit with this as a runtime option, if that's better.

2023-07-26 19:23 UTC, closed without merging