[GLIB] GResources being re-regenerated due to bad dependency file
WebKit/WebKit pull request #14523
Opened 2023-05-31 04:39 UTC by lauromoura

#### 9d46690c21c5474c741176a0bbb774adf66d25a1
<pre>
[GLIB] GResources being re-regenerated due to bad dependency file
<a href="https://bugs.webkit.org/show_bug.cgi?id=257516">https://bugs.webkit.org/show_bug.cgi?id=257516</a>

Reviewed by NOBODY (OOPS!).

Add a workaround script for glib-compile-resources issue <a href="https://gitlab.gnome.org/GNOME/glib/-/issues/2829">https://gitlab.gnome.org/GNOME/glib/-/issues/2829</a>

The script will fix the dependency rule while this is sorted in glib,
avoiding unnecessary recompilations by rewriting the dep file target.

* Source/WebKit/InspectorGResources.cmake:
* Source/WebKit/ModernMediaControlsGResources.cmake:
* Source/WebKit/PdfJSGResources.cmake:
* Source/WebKit/PlatformGTK.cmake:
* Source/WebKit/PlatformWPE.cmake:
* Tools/glib/fix-glib-resource-deps-target: Added.
</pre>

2023-05-31 04:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9d46690c21c5474c741176a0bbb774adf66d25a1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14523

2023-05-31 07:33 UTC, carlosgcampos approved these changes

2023-05-31 14:29 UTC, mcatanzaro reviewed
Isn't this going to break as soon as we fix glib-compile-resources? I'm not sure this workaround is really advisable. We'll certainly need to remove it as soon as glib is fixed unless you add a test to see whether the dep file is buggy or not.

As for the relative path issue, we need a bug report either to glib or to ninja. Probably glib, assuming GCC uses relative paths in depfiles generated with `gcc -M -MF`. glib should match what GCC does.

2023-05-31 15:12 UTC, mcatanzaro reviewed
Can you test to see what happens when your script runs on a depfile that is already fixed, to simulate what happens when the bug is fixed in glib? I'm afraid it's going to result in build failures.

Unnecessary rebuilds are annoying, but not as annoying as build failures.

2023-05-31 20:06 UTC, mcatanzaro requested changes
So we definitely need the fixes to add the two missing `$`

I see you have written this in such a way that it won't break when the GLib bug is fixed (I didn't look closely enough, sorry) so I suppose it's OK... but I'd still prefer to fix the underlying bugs instead. I've just submitted https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3460 which leaves us with the relative path issue. I guess next step is to decide whether that's a bug in ninja, or glib-compile-resources, or if it's caused by us passing absolute paths to glib-compile-resources.

2023-06-01 03:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/86eec72a6ebdd5cd5c3ef5edb69f900d052cd854. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14523

2023-06-01 03:48 UTC, lauromoura commented
> I see you have written this in such a way that it won't break when the GLib bug is fixed (I didn't look closely enough, sorry) so I suppose it's OK... but I'd still prefer to fix the underlying bugs instead. I've just submitted https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3460 which leaves us with the relative path issue. I guess next step is to decide whether that's a bug in ninja, or glib-compile-resources, or if it's caused by us passing absolute paths to glib-compile-resources.

 A few tweaks:

- Avoid rewriting the file if it isn't starting with the known issue
- rename the script to match other scripts naming in same folder
- Add the scripts to the dist manifest
- Avoid returning an error of something bad happens. At worst, the dep file will be already broke and the rebuilds will occur.

2023-06-01 15:36 UTC, mcatanzaro commented
So my GLib merge request has already landed. You can try adding https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3460.patch to the WebKit runtime now.

2023-06-07 15:34 UTC, mcatanzaro commented
I found [this ninja bug](https://github.com/ninja-build/ninja/issues/1251), which is a rabbit hole containing additional links to various CMake issues and merge requests, most notably [these](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6143) [two](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6148). And that first one looks like it should comprehensively resolve this by ensuring that ninja will recognize each custom command output by both absolute and relative path. Those fixes are included in CMake 3.21.

However, using CMake 3.26.4 and the updated glib-compile-resources, I unfortunately still see the unnecessary rebuilds. :(

It might be nicer to work around this problem by passing a relative path as the target when calling glib-compile-resources, which is easy to do and should probably resolve this issue. That seems like a fragile solution, though it's probably _slighty_ nicer than adding your script. Opinions?

Regardless, we should definitely remember to land your other fixes from this pull request. Do you want to land these parts separately now, since they don't have to wait for us to agree on what to do regarding the relative paths problem?

```
diff --git a/Source/WebKit/InspectorGResources.cmake b/Source/WebKit/InspectorGResources.cmake
index b8be58ac4073..ded677c228a6 100644
--- a/Source/WebKit/InspectorGResources.cmake
+++ b/Source/WebKit/InspectorGResources.cmake
@@ -11,7 +11,7 @@ macro(WEBKIT_BUILD_INSPECTOR_GRESOURCES _derived_sources_dir)
     add_custom_command(
         OUTPUT ${_derived_sources_dir}/InspectorGResourceBundle.c ${_derived_sources_dir}/InspectorGResourceBundle.deps
         DEPENDS ${_derived_sources_dir}/InspectorGResourceBundle.xml
-        DEPFILE {_derived_sources_dir}/InspectorGResourceBundle.deps
+        DEPFILE ${_derived_sources_dir}/InspectorGResourceBundle.deps
         COMMAND glib-compile-resources --generate --sourcedir=${_derived_sources_dir}/InspectorResources/WebInspectorUI --target=${_derived_sources_dir}/InspectorGResourceBundle.c --dependency-file=${_derived_sources_dir}/InspectorGResourceBundle.deps ${_derived_sources_dir}/InspectorGResourceBundle.xml
         VERBATIM
     )
diff --git a/Source/WebKit/ModernMediaControlsGResources.cmake b/Source/WebKit/ModernMediaControlsGResources.cmake
index 2cd6db1a5d6f..52648aa5bf63 100644
--- a/Source/WebKit/ModernMediaControlsGResources.cmake
+++ b/Source/WebKit/ModernMediaControlsGResources.cmake
@@ -10,7 +10,7 @@ macro(WEBKIT_BUILD_MODERN_MEDIA_CONTROLS_GRESOURCES _derived_sources_dir)
     add_custom_command(
         OUTPUT ${_derived_sources_dir}/ModernMediaControlsGResourceBundle.c ${_derived_sources_dir}/ModernMediaControlsGResourceBundle.deps
         DEPENDS ${_derived_sources_dir}/ModernMediaControlsGResourceBundle.xml
-        DEPFILE {_derived_sources_dir}/ModernMediaControlsGResourceBundle.deps
+        DEPFILE ${_derived_sources_dir}/ModernMediaControlsGResourceBundle.deps
         COMMAND glib-compile-resources --generate --sourcedir=${WEBCORE_DIR}/Modules/modern-media-controls/images/adwaita --target=${_derived_sources_dir}/ModernMediaControlsGResourceBundle.c --dependency-file=${_derived_sources_dir}/ModernMediaControlsGResourceBundle.deps ${_derived_sources_dir}/ModernMediaControlsGResourceBundle.xml
         VERBATIM
     )
diff --git a/Source/WebKit/PdfJSGResources.cmake b/Source/WebKit/PdfJSGResources.cmake
index ba2cafa27e3b..3aada353fc65 100644
--- a/Source/WebKit/PdfJSGResources.cmake
+++ b/Source/WebKit/PdfJSGResources.cmake
@@ -30,7 +30,7 @@ macro(WEBKIT_BUILD_PDFJS_GRESOURCES _derived_sources_dir)
         OUTPUT ${_derived_sources_dir}/PdfJSGResourceBundleExtras.c ${_derived_sources_dir}/PdfJSGResourceBundleExtras.deps
         DEPENDS ${_derived_sources_dir}/PdfJSGResourceBundleExtras.xml
         DEPFILE ${_derived_sources_dir}/PdfJSGResourceBundleExtras.deps
-        COMMAND glib-compile-resources --generate --sourcedir=${WEBCORE_DIR}/Modules/pdfjs-extras --target=${_derived_sources_dir}/PdfJSGResourceBundleExtras.c ${_derived_sources_dir}/PdfJSGResourceBundleExtras.xml
+        COMMAND glib-compile-resources --generate --sourcedir=${WEBCORE_DIR}/Modules/pdfjs-extras --target=${_derived_sources_dir}/PdfJSGResourceBundleExtras.c --dependency-file=${_derived_sources_dir}/PdfJSGResourceBundleExtras.deps ${_derived_sources_dir}/PdfJSGResourceBundleExtras.xml
         VERBATIM
     )
 endmacro()
 ```

2023-06-23 19:57 UTC, mcatanzaro commented
I've split the misc fixes out to https://bugs.webkit.org/show_bug.cgi?id=258478

2023-07-03 19:23 UTC, mcatanzaro commented
I'm going to go ahead and close this.

 * glib-compile-resources is fixed in https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3460
 * Other misc issues fixed via https://github.com/WebKit/WebKit/pull/15259
 * Remaining problem here is the relative vs. absolute paths, which still needs to be solved. https://bugs.webkit.org/show_bug.cgi?id=257516 not closed

2023-07-03 19:23 UTC, closed without merging