Web Inspector: Resizing Debugger Resource/Scope Chain column doesn't survive the change of tab
WebKit/WebKit pull request #14865
Opened 2023-06-12 15:48 UTC by rcaliman-apple

#### 9dff08b75a58dbcb738b350c6119ac8f855c6baa
<pre>
Web Inspector: Resizing Debugger Resource/Scope Chain column doesn&apos;t survive the change of tab
<a href="https://bugs.webkit.org/show_bug.cgi?id=256691">https://bugs.webkit.org/show_bug.cgi?id=256691</a>
rdar://109253229

Reviewed by NOBODY (OOPS!).

The width of the details sidebar for the Sources tab resets to its minimum width when navigating
to a tab without sidebar panels (Console, Network) or to a tab with a collapsed details sidebar (Graphics, Storage).

Navigating between tabs with visible details sidebar (Sources, Elements) doesn&apos;t reset the sidebar width.

--- Symptom 1

When a tab without visible sidebar panels is selected, the details sidebar gets collapsed:
- [TabBrowser._showDetailsSidebarPanelsForTabContentView():L471-L473](<a href="https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/TabBrowser.js#L471-L473)">https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/TabBrowser.js#L471-L473)</a>
- [ContentBrowserTabContentView.showDetailsSidebarPanels():L195-L196](<a href="https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/ContentBrowserTabContentView.js#L195-L196)">https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/ContentBrowserTabContentView.js#L195-L196)</a>

--- Symptom 2

The `width` getter for `SingleSidebar` returns it from the corresponding DOM node:

```
get width()
{
    return this.element.offsetWidth;
}
```

The `width` setter calls `SingleSidebar._recalculateWidth(newWidth = this.width)`
to write the value to the inline style of the DOM node:

[SingleSidebar._recalculateWidth():L175-L192](<a href="https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js#L175C5-L192)">https://github.com/WebKit/WebKit/blob/fc2cbdef688b134951ca32f386632379ea8cf49f/Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js#L175C5-L192)</a>

That default function parameter, `newWidth = this.width`, is the source of the issue.

--- Explanation of issue

When the sidebar is collapsed, the layout step is skipped in `SingleSidebar._recalculateWidth()`:

```
if (this.collapsed)
    return;

if (this._navigationBar)
    this._navigationBar.needsLayout(WI.View.LayoutReason.Resize);

if (this.selectedSidebarPanel)
    this.selectedSidebarPanel.needsLayout(WI.View.LayoutReason.Resize);
```

That means that, even though, there&apos;s a non-zero `newWidth` on the element,
the `.collapsed` CSS class on the sidebar makes its `offsetWidth` equal to zero.

When sidebar panels are added in `ContentBrowserTabContentView.showDetailsSidebarPanels()`,
they trigger layout via this call chain:

`SingleSidebar.insertSidebarPanel()`
-&gt; `SingleSidebar.didInsertSidebarPanel()`
-&gt; `SingleSidebar._recalculateWidth(newWidth = this.width)`

But in this call there is no value for `newWidth`, so it uses the default function paramter
which calls the `SingleSidebar.width` getter that returns zero (the DOM node&apos;s actual `offsetWidth`).

Luckily, there&apos;s also an immutable minimum width on the sidebar styles set by `SingleSidebar._recalculateWidth():

```
    this.element.style.width = `${newWidth}px`; // this is 0px
    this.element.style.minWidth = `${this.minimumWidth}px`; // this is 250px
```

This allows the sidebar content to be shown but at a different size than the one set when resizing the sidebar.

--- Solution

Remove the default function parameter from `SingleSidebar._recalculateWidth(newWidth = this.width)`
and only apply `newWidth` when it&apos;s explicitly passed along.

The other calls to `SingleSidebar._recalculateWidth()` in response to adding a sidebar panel
have the intent to schedule layout, not to set the sidebar width (hence the use of the default parameter).

* Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js:
(WI.SingleSidebar.prototype.didInsertSidebarPanel):
(WI.SingleSidebar.prototype._recalculateWidth):
</pre>

2023-06-12 15:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9dff08b75a58dbcb738b350c6119ac8f855c6baa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14865

2023-06-12 15:53 UTC, rcaliman-apple commented
## Screen recording of issue 

The width of the Sources sidebar resets when toggling to the Network tab, but not to the Elements tab.

https://github.com/WebKit/WebKit/assets/105809798/87247dfe-1abc-42db-ba43-cd5f5bd64b41


## Screen recording of fix

https://github.com/WebKit/WebKit/assets/105809798/f2e30811-ed9d-48de-9ca1-b4ea0eb4dfba

2023-06-12 16:57 UTC, dcrousso requested changes
do we know when this regressed?  i coulda sworn this has not been an issue in the past 🤔

2023-06-12 16:57 UTC, dcrousso commented on Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js
> +            this.element.style.minWidth = `${this.minimumWidth}px`;
i feel like we should still apply this even if `newWidth` is not provided as otherwise we may not account for the `WI.NavigationBar` changing if a `WI.SidebarPanel` is added/removed

2023-06-12 16:57 UTC, dcrousso commented on Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js
> +        if (newWidth) {
what if someone explicitly calls `.width = 0`?

2023-06-13 17:19 UTC, rcaliman-apple commented
> do we know when this regressed? i coulda sworn this has not been an issue in the past 🤔

Likely regressed by https://bugs.webkit.org/show_bug.cgi?id=227707 - "Web Inspector: Elements Tab Details Sidebar navigation items sometime wrap to a second line" from July 2021.

I can't get a build that old to verify. But removing the calls to `this._recalculateWidth()` in  `didInsertSidebarPanel()` and `didRemoveSidebarPanel()` solves this issue while reintroducing a variant of the previous one.

2023-06-13 17:25 UTC, rcaliman-apple commented on Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js
> +            this.element.style.minWidth = `${this.minimumWidth}px`;
GitHub shows the entire block of code between `{}` for that comment and that makes it ambiguous.
Do you mean still apply minimum width even when `newWidth` is not provided? I assume so, but just checking.

2023-06-13 17:26 UTC, rcaliman-apple commented on Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js
> +        if (newWidth) {
They shouldn't, that's what `WI.Sidebar.collapsed = true` is for :)
But I get your point, I'll make the check more explicit.

2023-06-13 17:49 UTC, rcaliman-apple commented
How about this other approach in this latest patch: 

since the goal is to avoid overwriting its element's width to zero, why not just skip the calls to `this._recalculateWidth()` after inserting or removing panels while the sidebar is collapsed?

This leaves the other use cases untouched.

2023-06-13 20:23 UTC, dcrousso commented on Source/WebInspectorUI/UserInterface/Views/SingleSidebar.js
> +            this.element.style.minWidth = `${this.minimumWidth}px`;
yeah i was only referring to the line dealing with `minWidth`

2023-06-13 20:25 UTC, dcrousso approved these changes
yeah i like this approach a bit better

just for the sake of future proofing tho we may wanna insert a `console.assert(newWidth)` inside `_recalculateWidth` to make it clear to callers (and to catch scenarios like this) that it must be a nonzero value

2023-06-14 11:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/25e9ba688e78fbb28fd092fbbd711a93246537c4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/14865

2023-06-14 12:20 UTC, webkit-commit-queue commented
Committed 265152@main (8303e810a680): <https://commits.webkit.org/265152@main>

Reviewed commits have been landed. Closing PR #14865 and removing active labels.

2023-06-14 12:20 UTC, merged