setSelectionRange will reset the m_latestFocusTrigger variable, causing the subsequently focused element to match the :focus-visible selector
WebKit/WebKit pull request #15092
Opened 2023-06-19 14:07 UTC by ntdiary

#### 3d85c92f718f3ce85c7e71c800810dfde1669403
<pre>
setSelectionRange will reset the m_latestFocusTrigger variable, causing the subsequently focused element to match the :focus-visible selector
<a href="https://bugs.webkit.org/show_bug.cgi?id=256929">https://bugs.webkit.org/show_bug.cgi?id=256929</a>
&lt;<a href="https://rdar.apple.com/problem/109803748">rdar://problem/109803748</a>&gt;

Reviewed by Ryosuke Niwa.

This patch adds ForBindings to differentiate when setSelectionRange is called from Javascript.
In this way, if it is called from Javascript and focus occurs,
its behavior can be consistent with Element::focusForBindings.

* LayoutTests/fast/selectors/focus-visible-setSelectionRange-expected.txt: Added.
* LayoutTests/fast/selectors/focus-visible-setSelectionRange.html: Added.
* Source/WebCore/editing/FrameSelection.cpp:
(WebCore::FrameSelection::moveWithoutValidationTo):
(WebCore::FrameSelection::setSelectionWithoutUpdatingAppearance):
(WebCore::FrameSelection::setFocusedElementIfNeeded):
* Source/WebCore/editing/FrameSelection.h:
* Source/WebCore/html/HTMLInputElement.cpp:
(WebCore::HTMLInputElement::setSelectionRangeForBindings):
* Source/WebCore/html/HTMLTextAreaElement.cpp:
(WebCore::HTMLTextAreaElement::setSelectionRangeForBindings):
* Source/WebCore/html/HTMLTextAreaElement.h:
* Source/WebCore/html/HTMLTextAreaElement.idl:
* Source/WebCore/html/HTMLTextFormControlElement.cpp:
(WebCore::HTMLTextFormControlElement::setSelectionRange):
* Source/WebCore/html/HTMLTextFormControlElement.h:

Canonical link: <a href="https://commits.webkit.org/270043@main">https://commits.webkit.org/270043@main</a>
</pre>

2023-06-19 14:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b6caf25f4d97b875781f4b89d45c9954fcc73cff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-06-20 09:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d53303516d26a8b36a48829ffb156a5007767f71. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-06-20 17:21 UTC, rniwa commented on Source/WebCore/editing/FrameSelection.cpp
> +                CheckedRef(m_document->page()->focusController())->setFocusedElement(target, *m_document->frame(), { { }, { }, { }, FocusTrigger::Bindings, { } });
This is not bindings. Why are we using FocusTrigger::Bindings?

2023-06-21 16:10 UTC, ntdiary commented on Source/WebCore/editing/FrameSelection.cpp
> +                CheckedRef(m_document->page()->focusController())->setFocusedElement(target, *m_document->frame(), { { }, { }, { }, FocusTrigger::Bindings, { } });
https://github.com/WebKit/WebKit/blob/5512c619b8aa9d8129d15c540158fb6bf32bbee7/Source/WebCore/dom/Document.cpp#L4988-L4989
Now, only `FocusTrigger::Bindings` won't reset the `m_latestFocusTrigger` variable.If we feel it does not conform to the semantics, how about trying to add a new enum value?

2023-06-21 22:50 UTC, rniwa commented on Source/WebCore/editing/FrameSelection.cpp
> +                CheckedRef(m_document->page()->focusController())->setFocusedElement(target, *m_document->frame(), { { }, { }, { }, FocusTrigger::Bindings, { } });
We should probably do that. But more importantly, why is not resetting m_latestFocusTrigger right for all calls of this function? This function is called whenever selection is changed. If the problem here lies when this function is called by setSelectionRange then we need a more targeted code change instead.

2023-06-26 15:16 UTC, ntdiary commented on Source/WebCore/editing/FrameSelection.cpp
> +                CheckedRef(m_document->page()->focusController())->setFocusedElement(target, *m_document->frame(), { { }, { }, { }, FocusTrigger::Bindings, { } });
Sorry for the delay, I'm still delving deeper into the relevant code and change history, hope to have a good understanding by this weekend. : )

2023-09-26 02:06 UTC, jeet-dhandha commented
@rniwa Just wondering if some people are using this implementation as a way focus inputs, wouldn't this break things for them ?

2023-10-09 14:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c7fb5471c4cbc2607e7c4b9bb0f89ebcc65dd7b1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-10-13 21:44 UTC, rniwa commented on Source/WebCore/html/HTMLTextFormControlElement.h
> +    bool isForBindings { false };
Please don't add a new public boolean member variable like this.
Instead, we should be passing this argument across function calls.

2023-10-13 21:45 UTC, rniwa requested changes
r- because we don't want to be adding a new boolean member to `HTMLTextFormControlElement` like this.

2023-10-14 08:35 UTC, ntdiary commented on Source/WebCore/html/HTMLTextFormControlElement.h
> +    bool isForBindings { false };
> Please don't add a new public boolean member variable like this. Instead, we should be passing this argument across function calls.

Thank you very much for your advice! I didn't know about this before and will try to remove it later.

2023-10-14 17:35 UTC, ntdiary commented on Source/WebCore/html/HTMLTextFormControlElement.h
> +    bool isForBindings { false };
Hi, @rniwa, I mistakenly thought we would not want to change the function signature, so I added that `protected` member variable. This is my first WebKit PR, not too familiar with the coding conventions yet 😅. 

> we should be passing this argument across function calls.

Does this mean I can append an argument to these functions?
```c++
// HTMLTextFormControlElement.h
void setSelectionRange(unsigned start, unsigned end, const String& direction, const AXTextStateChangeIntent& = AXTextStateChangeIntent());
WEBCORE_EXPORT bool setSelectionRange(unsigned start, unsigned end, TextFieldSelectionDirection = SelectionHasNoDirection, SelectionRevealMode = SelectionRevealMode::DoNotReveal, const AXTextStateChangeIntent& = AXTextStateChangeIntent());
```
Or we just should avoid public member variable (but allow private one), then I can add a new `protected` function and have `input` and `textarea` call it?
```c++
// HTMLTextFormControlElement.h
void setSelectionRange(unsigned start, unsigned end, const String& direction, bool isForBindings = false);
```

2023-10-16 06:19 UTC, rniwa commented on Source/WebCore/html/HTMLTextFormControlElement.h
> +    bool isForBindings { false };
Adding a new argument to the function seems fine. Don't add a new state to HTMLTextFormControlElement, let alone a public state variable.

2023-10-17 22:19 UTC, rniwa commented on Source/WebCore/editing/FrameSelection.h
> +    bool m_isForBindings { false };
Please don't add a new state like this to FrameSelection.

2023-10-17 22:20 UTC, rniwa requested changes
r- because of a new state being added to FrameSelection.

2023-10-17 23:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0178ef9cdd362b80cf7fc5c913c3c8671f3dda12. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-10-17 23:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0178ef9cdd362b80cf7fc5c913c3c8671f3dda12. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-10-17 23:41 UTC, rniwa commented on LayoutTests/fast/selectors/focus-visible-setSelectionRange-expected.txt
> +Click me
Why there is no output for this test??

2023-10-17 23:43 UTC, rniwa commented on Source/WebCore/editing/FrameSelection.cpp
> +void FrameSelection::moveWithoutValidationTo(const Position& base, const Position& extent, bool selectionHasDirection, bool shouldSetFocus, SelectionRevealMode revealMode, const AXTextStateChangeInte
Please add an enum class like this:
```
enum class ForBindings : bool { No, Yes };
```

2023-10-18 00:00 UTC, rniwa commented on Source/WebCore/editing/FrameSelection.h
> +    void moveWithoutValidationTo(const Position&, const Position&, bool selectionHasDirection, bool shouldSetFocus, SelectionRevealMode, const AXTextStateChangeIntent& = AXTextStateChangeIntent(), bo
Other than adding a new boolean, we should probably add a new value of `SetSelectionOption` instead.
e.g. `SetSelectionOption::IsScriptTriggered` or `SetSelectionOption::ForBindings`

2023-10-18 00:00 UTC, rniwa commented on LayoutTests/fast/selectors/focus-visible-setSelectionRange.html
> +            UIHelper.activateElement(initial);
No curly braces around a single line statement.

2023-10-24 12:59 UTC, ntdiary commented on LayoutTests/fast/selectors/focus-visible-setSelectionRange-expected.txt
> +Click me
Hi, could you explain what "output" means? 🤔

2023-10-24 16:31 UTC, rniwa commented on LayoutTests/fast/selectors/focus-visible-setSelectionRange-expected.txt
> +Click me
Hm... there is output now. I guess it was an issue with my browser.

2023-10-27 07:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/94404dbd761c3a62eba367d8725d00c98310de87. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15092

2023-10-27 09:21 UTC, ntdiary commented on Source/WebCore/editing/FrameSelection.h
> +    void moveWithoutValidationTo(const Position&, const Position&, bool selectionHasDirection, bool shouldSetFocus, SelectionRevealMode, const AXTextStateChangeIntent& = AXTextStateChangeIntent(), bo
To distinguish it from the existing `SetSelectionOption::IsUserTriggered`, I chose `SetSelectionOption::ForBindings`.

2023-10-31 16:58 UTC, ntdiary commented on Source/WebCore/editing/FrameSelection.h
> +    void moveWithoutValidationTo(const Position&, const Position&, bool selectionHasDirection, bool shouldSetFocus, SelectionRevealMode, const AXTextStateChangeIntent& = AXTextStateChangeIntent(), bo
As `moveWithoutValidationTo` is only called in `HTMLTextFormControlElement.cpp`, and `shouldSetFocus` and `SelectionRevealMode` are both used to set `SetSelectionOption`, I move the logic for these two parameters into `HTMLTextFormControlElement.cpp`. If you think we should not do this, please feel free to let me know. : )

2023-11-01 05:20 UTC, rniwa approved these changes

2023-11-01 06:09 UTC, webkit-commit-queue commented
Committed 270043@main (3d85c92f718f): <https://commits.webkit.org/270043@main>

Reviewed commits have been landed. Closing PR #15092 and removing active labels.

2023-11-01 06:09 UTC, merged