Remove duplicate check in 'checkInvalidControlsAndCollectUnhandled' function 'if' clause
WebKit/WebKit pull request #15663
Opened 2023-07-08 08:12 UTC by Ahmad-S792

<pre>
Remove duplicate check in 'checkInvalidControlsAndCollectUnhandled' function 'if' clause
<a href="https://bugs.webkit.org/show_bug.cgi?id=259010">https://bugs.webkit.org/show_bug.cgi?id=259010</a>

Reviewed by NOBODY (OOPS!).

This patch just remove 'duplicate' check from 'if' clause.

* Source/WebCore/html/HTMLFormElement.cpp: (HTMLFormElement::checkInvalidControlsAndCollectUnhandled):
</pre>

2023-07-08 08:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0689923695461e4792e6171037a3991994f76865. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15663

2023-07-08 08:21 UTC, nt1m approved these changes

2023-07-08 09:37 UTC, nt1m requested changes
Ah the test failures reveal that this is actually not a duplicate check.

`!control->checkValidity(&unhandledInvalidControls)` can change the value of `control->form()` it seems.

2023-07-08 09:40 UTC, Ahmad-S792 commented
> Ah the test failures reveal that this is actually not a duplicate check.
> 
> `!control->checkValidity(&unhandledInvalidControls)` can change the value of `control->form()` it seems.

Fair! I checked with @rniwa on Slack, hence, I started with this PR. It's fine. I can close it with this comment on the bug.

2023-07-08 09:43 UTC, nt1m commented
@Ahmad-S792 (I think it be worth adding a comment clarifying why there are "duplicate" checks, to avoid confusion for anyone reading this code)

2023-07-08 09:46 UTC, nt1m commented
Something like:
```
// checkValidity() can trigger events that change the DOM hence why we check for control->form() twice.
```

Alternatively, I _think_ it might be possible to remove the duplicate check, but removing the first one, not the one after `checkValidity()`

2023-07-08 09:46 UTC, Ahmad-S792 commented
> ```
> // checkValidity() can trigger events that change the DOM hence why we check for control->form() twice.
> ```

Let me run these tests on local and will either comment or remove first check. :-)

2023-07-08 10:04 UTC, Ahmad-S792 commented
> > ```
> > // checkValidity() can trigger events that change the DOM hence why we check for control->form() twice.
> > ```
> 
> Let me run these tests on local and will either comment or remove first check. :-)

@nt1m - even removing from start lead to test failure (fast/forms/checkValidity-handler-updates-dom.html), so I think we can just update with comment to make it clearer for future. :-)

2023-07-08 10:05 UTC, nt1m commented
Sounds good, thanks for checking!

2023-07-09 14:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1c2b88fd8771c77511399769b9106625254f38ae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/15663

2023-07-09 18:42 UTC, nt1m approved these changes

2023-07-09 18:46 UTC, webkit-commit-queue commented
Committed 265890@main (e7780d735de3): <https://commits.webkit.org/265890@main>

Reviewed commits have been landed. Closing PR #15663 and removing active labels.

2023-07-09 18:46 UTC, merged