[GLib] Use correct number of webviews for TestWebsiteData/handle-corrupted-local-storage
WebKit/WebKit pull request #16286
Opened 2023-08-01 20:19 UTC by abstractmachines

#### 804a5f9d0e93f821eca46c5135d0bc52106d0419
<pre>
[GLib] Use correct number of webviews for TestWebsiteData/handle-corrupted-local-storage
<a href="https://bugs.webkit.org/show_bug.cgi?id=259701">https://bugs.webkit.org/show_bug.cgi?id=259701</a>

Reviewed by NOBODY (OOPS!).

We added a test for handling corrupted local storage when we added the
GLib feature in 259573@main a few months ago in January.

It seems that this test has never succeeded since introduced according to
WPE API test reports (`wk-bot-digest` for the last several thousand CI
runs including this commit 259573@main); note that for WPE the new GLib API
is running on the bots by default build per OptionsWPE.cmake
`SET_AND_EXPOSE_TO_BUILD(ENABLE_2022_GLIB_API ON)`.

The reason this test wasn&apos;t passing is because of the lack of multiple
webViews on the test per PR feedback here:
<a href="https://github.com/WebKit/WebKit/pull/8716#pullrequestreview-1252862997">https://github.com/WebKit/WebKit/pull/8716#pullrequestreview-1252862997</a>
1. Make malformed file (done in original test)
2. Create first webview and load webpage to store - not done ...
3. Create second webview (done in original test).

This PR adds in step 2 missing from our original path in 259573@main;
this PR does this for GLib, but similar work was done for Cocoa test
coverage in 262161@main in February; that PR was a followup to 259573@main.

Now the test is running in WPE for both the new GLib API and the old/
deprecated GLib API.

* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebsiteData.cpp:
(testWebViewHandleCorruptedLocalStorage): Add first webView per above

* Tools/TestWebKitAPI/glib/TestExpectations.json: remove WPE API failing
expectation for this test that was added in a meta-gardening bug
b/256557 a couple of months ago in May.
</pre>

2023-08-01 20:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/804a5f9d0e93f821eca46c5135d0bc52106d0419. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16286

2023-08-02 01:14 UTC, mcatanzaro requested changes
But the existing code _does_ use two web views: (1) `test->m_webView`, (2) the local variable `webView`. So something more must be going on here?

2023-08-04 18:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/626cf5c49d62aabcd6f6d582662619578335de1e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16286

2023-08-04 18:44 UTC, abstractmachines commented
> But the existing code _does_ use two web views: (1) `test->m_webView`, (2) the local variable `webView`. So something more must be going on here?

Thanks so much for the Slack discussion earlier :) (And, for the excellent docs you've left on API migrations in the codebase that helped my research). I've made changes per our discussion and updated the PR description as well!

2023-08-07 08:28 UTC, carlosgcampos approved these changes

2023-08-07 08:32 UTC, webkit-commit-queue commented
Committed 266631@main (97e6ebdc6b25): <https://commits.webkit.org/266631@main>

Reviewed commits have been landed. Closing PR #16286 and removing active labels.

2023-08-07 08:32 UTC, merged