Fix build failure when gstreamer support is disabled
WebKit/WebKit pull request #16398
Opened 2023-08-04 19:17 UTC by mattst88

https://bugs.gentoo.org/911663

* Source/WebCore/loader/MixedContentChecker.cpp:

---

This appears to be a regression from 2.40.4 to 2.40.5.

I tried using `Tools/Scripts/git-webkit pull-request` but couldn't get it to work because I couldn't figure out how to tell it to make this pull request against the `webkitglib/2.40` branch instead of master.

cc: @mcatanzaro

2023-08-04 19:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/579c71253ce288e35d29695b305d7d05a85fc82f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16398

2023-08-05 10:34 UTC, clopez commented
Please rebase this PR on top of the last version of the main branch and force-push it

2023-08-05 10:35 UTC, clopez requested changes
need rebase

2023-08-05 10:41 UTC, clopez commented
Ups, sorry I see this is a merge to the stable branches.. forget my previous comment

2023-08-05 10:41 UTC, clopez approved these changes

2023-08-08 08:12 UTC, philn commented
I don't think the merge bot can commit/push on non-main branches? cc @carlosgcampos

2023-08-08 15:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/115310f439ad0806568ddc398e58709b00647ef0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16398

2023-08-08 15:57 UTC, philn commented
And we need a WebKit bug for this, sorry for the bureaucracy.

2023-08-08 15:57 UTC, mattst88 commented
> I have no idea. We can try but the changelog is not properly formatted. It will fail first due to that.

Do you mean the `    * Source/WebCore/loader/MixedContentChecker.cpp:` portion? That looks the same as others in git log...

> It needs the line Reviewed by NOBODY (OOPS!). in the git commit message.

I've added this now.

2023-08-08 15:58 UTC, mattst88 commented
No problem. I'll file one and update the commit message.

2023-08-08 16:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9ea311b64e2b902737e86bc42fc109af2e8f8b52. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16398

2023-08-08 23:41 UTC, clopez commented
let's try 🤞

2023-08-08 23:52 UTC, webkit-commit-queue commented
merge-queue failed to commit PR to repository. To retry, remove any blocking labels and re-apply merge-queue label

2023-08-08 23:55 UTC, clopez commented
Mmm.. it seems it didn't worked.

The commit-queue bot tried it 3 times but it ended failing, details at: https://ews-build.webkit.org/#/builders/22/builds/1731

Sorry for the mess.  I will ask someone with direct commit rights to push this manually.

2023-08-09 09:51 UTC, clopez commented
Merged in 2.40 branch as f5ceef5bf2e3c4d7203a37b9e2d2fdd9b1bb2732'

2023-08-09 09:51 UTC, closed without merging

2023-08-09 18:11 UTC, mattst88 commented
Thanks everyone!

2023-08-10 21:26 UTC, mcatanzaro commented
For future reference, the problem was merge queue didn't have permission to push to webkitglib/* branches. We'll change this.