Generated attribute setters for nullable types silently fail
WebKit/WebKit pull request #16495
Opened 2023-08-08 22:57 UTC by rreno

#### fd18c0a539ec4698f8161a427198d8fe35c64f4c
<pre>
Generated attribute setters for nullable types silently fail
<a href="https://bugs.webkit.org/show_bug.cgi?id=259947">https://bugs.webkit.org/show_bug.cgi?id=259947</a>
rdar://113591277

Reviewed by NOBODY (OOPS!).

We aren&apos;t allowing `null` or empty strings as attribute values for
nullable attributes. This will check if the attribute is nullable in
the code generator and if so pass along a nullopt instead of silently
failing. Preserves the existing behavior for non-nullable attributes.

* Source/WebCore/bindings/scripts/CodeGeneratorJS.pm:
(GenerateAttributeSetterBodyDefinition):
</pre>

2023-08-08 22:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fd18c0a539ec4698f8161a427198d8fe35c64f4c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-08 22:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fd8ae5382350134e351ae92de3d5d2d1cba1ccff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-08 23:00 UTC, cdumez requested changes

2023-08-08 23:00 UTC, cdumez commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +            if (!$attribute->type->isNullable) {
This is not correct. We should not be calling parseEnumeration() at all if the input is null or undefined.

Now if the input is an invalid string, you'll implicitly convert to null which is not spec compliant.

2023-08-08 23:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/50de27a087e3737d95c7e44b10bb9d666437d071. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-09 00:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c69ff1d7907c42945b0d11868d58e1067b326713. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-09 00:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8fdaa87553321a9d3859952c1be20b14654021d0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-09 01:08 UTC, cdumez commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +
I think it would be nice to add an anonymous function here to avoid code duplication:
```
my $generateFunctionString = sub {
    my $nativeValue = shift;

    my ($baseFunctionName, @arguments) = $codeGenerator->SetterExpression(\%implIncludes, $interface->type->name, $attribute);
    push(@arguments, $nativeValue);
    my $functionName = GetFullyQualifiedImplementationCallName($interface, $attribute, $baseFunctionName, "impl", $conditional);
    AddAdditionalArgumentsForImplementationCall(\@arguments, $interface, $attribute, "impl", "lexicalGlobalObject", "", "thisObject");
    return "${functionName}(" . join(", ", @arguments) . ")";
};
```

2023-08-09 01:08 UTC, cdumez commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +                my $functionString = "${functionName}(" . join(", ", @arguments) . ")";
`my $functionString = generateFunctionString("std::nullopt");`

2023-08-09 01:08 UTC, cdumez commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +
And this at line 5718:
```
`my $functionString = generateFunctionString(PassArgumentExpression("nativeValue", $attribute));`
```

2023-08-09 01:10 UTC, cdumez commented
> We aren't allowing `null` or empty strings as attribute values in the
> setter for nullable enum attributes.

I don't think the commit log is completely accurate anymore. an empty string should not get converted to null.

2023-08-09 04:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9d66c258d50ed92c0cdaa1ea4d981630b3450761. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-09 05:04 UTC, rreno commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +
I didn't know about anonymous functions in Perl - pretty cool. Though the syntax for actually calling it was a bit unexpeceted (`$generateFunctionString->("std::nullopt");`)

2023-08-09 05:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/36b75155e96ea858ced4b70107ebab6369017088. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16495

2023-08-09 05:07 UTC, cdumez commented on Source/WebCore/bindings/scripts/CodeGeneratorJS.pm
> +
I think `&$generateFunctionString("std::nullopt");` would work too but yes, it's Perl :/

2023-08-09 05:11 UTC, cdumez approved these changes
LGTM

2023-08-09 15:08 UTC, webkit-commit-queue commented
Committed 266726@main (23551a03b824): <https://commits.webkit.org/266726@main>

Reviewed commits have been landed. Closing PR #16495 and removing active labels.

2023-08-09 15:08 UTC, merged