[CSS] @font-palette-values family-name supports multiple values
WebKit/WebKit pull request #16564
Opened 2023-08-10 15:16 UTC by mdubet

#### 83db139305cad9bc26aae1844c44a43b12e5d986
<pre>
[CSS] @font-palette-values family-name supports multiple values
<a href="https://bugs.webkit.org/show_bug.cgi?id=252569">https://bugs.webkit.org/show_bug.cgi?id=252569</a>
rdar://105975619

Reviewed by Tim Nguyen.

This patch allows @font-palette-values family-name descriptor to have
a list of family names (per spec).

<a href="https://drafts.csswg.org/css-fonts-4/#family-name-syntax">https://drafts.csswg.org/css-fonts-4/#family-name-syntax</a>

* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/font-palette-36-expected.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/font-palette-36-ref.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/font-palette-36.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/parsing/font-palette-values-invalid-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/parsing/font-palette-values-valid-expected.txt:
* Source/WebCore/css/CSSFontPaletteValuesRule.cpp:
(WebCore::CSSFontPaletteValuesRule::fontFamily const):
(WebCore::CSSFontPaletteValuesRule::cssText const):
(WebCore::CSSFontPaletteValuesRule::~CSSFontPaletteValuesRule): Deleted.
* Source/WebCore/css/CSSFontSelector.cpp:
(WebCore::CSSFontSelector::addFontPaletteValuesRule):
* Source/WebCore/css/CSSProperties.json:
* Source/WebCore/css/StyleRule.cpp:
(WebCore::StyleRuleFontPaletteValues::create):
(WebCore::StyleRuleFontPaletteValues::StyleRuleFontPaletteValues):
* Source/WebCore/css/StyleRule.h:
* Source/WebCore/css/parser/CSSParserImpl.cpp:
(WebCore::CSSParserImpl::consumeFontFeatureValuesRule):
(WebCore::CSSParserImpl::consumeFontPaletteValuesRule):
* Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp:
(WebCore::CSSPropertyParserHelpers::consumeFamilyNameListRaw):
(WebCore::CSSPropertyParserHelpers::consumeFamilyNameList):
* Source/WebCore/css/parser/CSSPropertyParserHelpers.h:

Canonical link: <a href="https://commits.webkit.org/267411@main">https://commits.webkit.org/267411@main</a>
</pre>

2023-08-10 15:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8411879fbb75ffe3eff088b038970227cd547bbe. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16564

2023-08-10 16:37 UTC, nt1m reviewed
Can we add a reftest for this feature?

2023-08-10 16:37 UTC, nt1m commented on Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp
> +    if (!genericFontFamily(range.peek().id()).isNull())
Would be good to add a parsing subtest for this.

2023-08-10 17:25 UTC, mdubet commented on Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp
> +    if (!genericFontFamily(range.peek().id()).isNull())
There is already a test for that.

2023-08-10 17:26 UTC, nt1m commented on Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp
> +    if (!genericFontFamily(range.peek().id()).isNull())
That we reject generic font families?

2023-08-10 17:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3018f22278009738e65be63104109b20bb54437c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16564

2023-08-10 17:27 UTC, nt1m approved these changes
Please export this WPT

2023-08-10 17:28 UTC, mdubet commented on Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp
> +    if (!genericFontFamily(range.peek().id()).isNull())
Yes https://github.com/web-platform-tests/wpt/blob/29bc632bd38bf33bd475ef5b925fcea029cf6249/css/css-fonts/parsing/font-palette-values-invalid.html#L22

2023-08-10 17:32 UTC, nt1m commented on Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp
> +    if (!genericFontFamily(range.peek().id()).isNull())
ah sounds good, thanks!

2023-08-10 23:03 UTC, nt1m requested changes
Some failures need to be looked at

2023-08-29 12:40 UTC, mdubet commented on LayoutTests/imported/w3c/web-platform-tests/css/css-fonts/parsing/font-palette-values-invalid-expected.txt
> -PASS CSS Fonts Module Level 4: parsing @font-palette-values 1
We have another issue here (which was hidden by our bug of bug) https://bugs.webkit.org/show_bug.cgi?id=260066

2023-08-29 17:07 UTC, nt1m approved these changes

2023-08-29 18:16 UTC, webkit-commit-queue commented
Committed 267411@main (83db139305ca): <https://commits.webkit.org/267411@main>

Reviewed commits have been landed. Closing PR #16564 and removing active labels.

2023-08-29 18:16 UTC, merged

2023-08-30 01:12 UTC, nt1m commented
@mdubet Can you export this to WPT?

2023-08-30 08:52 UTC, mdubet commented
https://github.com/web-platform-tests/wpt/pull/41708/files?w=1