Increase probability of PGM activation from 1/1000 to 1/100
WebKit/WebKit pull request #16805
Opened 2023-08-17 20:55 UTC by ddkilzer

#### 679d3cd60a7a7708ead8972be196c850dda03fe0
<pre>
Increase probability of PGM activation from 1/1000 to 1/100
<a href="https://bugs.webkit.org/show_bug.cgi?id=260362">https://bugs.webkit.org/show_bug.cgi?id=260362</a>
&lt;rdar://114042901&gt;

Reviewed by NOBODY (OOPS!).

* Source/bmalloc/libpas/src/libpas/pas_probabilistic_guard_malloc_allocator.c:
(pas_probabilistic_guard_malloc_initialize_pgm):
- Change probability from 1000 to 100.
</pre>

2023-08-17 20:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/679d3cd60a7a7708ead8972be196c850dda03fe0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/16805

2023-08-17 21:59 UTC, stwrt commented
Having tested this with a 100% percent probability before I don't believe this would cause any performance concerns. I am not opposed to running with a higher probability chance.

2023-08-18 22:22 UTC, aproskuryakov commented
Could you please elaborate on how this wouldn't cause performance concerns even at 100%?

2023-08-22 17:15 UTC, stwrt commented
> Could you please elaborate on how this wouldn't cause performance concerns even at 100%?

Because we allocate with PGM infrequently. When writing this Yusuke and I ensured there would be no performance/memory regression when this feature was activated.

This just changes how much we turn it on; not how much we allocate (which could cause a regression).

2023-08-22 17:31 UTC, ddkilzer commented
> Could you please elaborate on how this wouldn't cause performance concerns even at 100%?

In a nutshell, there are two steps that must succeed before any libpas allocation is guarded:

1. There is a 1/1000 chance that the launch of a process that uses the libpas allocator will make libpas PGM active.  (This is what this PR proposes to change to 1/100.)
2. Once libpas PGM is active in a process, there is a 1/4000 to 1/5000 chance (value in the range [4000-5000) chosen randomly once) that a given libpas allocation will be guarded.  (This is not changing.)

So what Brandon is suggesting is that even if we enabled libpas PGM for every process launch where the libpas allocator is used, there's still only a 1/4000-1/5000 chance that a given allocation is guarded.  (However, he didn't test that scenario—he only tested 1/100.)

2023-08-22 17:55 UTC, aproskuryakov commented
So why not make it 100%? I don't understand what the trade-off is, as you seem to propose a course of action consistent with having a trade-off, but saying that there isn't any.

2023-08-24 20:45 UTC, ddkilzer commented
> So why not make it 100%?

Because that was a speculative statement instead of what Brandon actually tested.  I was under the assumption that we would want to test 100% activation before adopting it.  (I try to explain this in further detail below.)

> I don't understand what the trade-off is, as you seem to propose a course of action consistent with having a trade-off, but saying that there isn't any.

I think you're conflating statements from Brandon vs. statements from me.

Brandon said that he doesn't think there's a trade-off for 100% activation, but he only tested 1/1000 (0.1%) and 1/100 (1%) and saw no difference between those two rates.  He did not test the 100% activation rate, so I consider that an "unknown", not "no known trade-off".

2023-08-24 20:53 UTC, johnwilander commented
> Could you please elaborate on how this wouldn't cause performance concerns even at 100%?

As I understand it, there are two gates that lower us from doing it _all the time_. One for even enabling it in a process, and a second one controlling what portion of allocations gets guarded.

What Brandon is saying is that even if we turn it on for all processes, the low number of allocations for which we guard guarantees that we don't regress performance or memory according to Brandon's testing.

I'm much in favor of this change and requested it. We need the the bug reports.

2023-08-24 22:17 UTC, aproskuryakov commented
Yes, I understand that there are two separate gates. What I don't understand is how we decide when to stop increasing the number that's being increased here. 

Is the proposal to keep increasing the number until something bad (and unpredictable) happens?

If anything, having this number below 100% is a liability. We don't continuously retest whether PGM causes an observable usability regression, so we could cause a bad day for 1% of our users.

2023-08-25 00:21 UTC, johnwilander commented
> Yes, I understand that there are two separate gates. What I don't understand is how we decide when to stop increasing the number that's being increased here.
> 
> Is the proposal to keep increasing the number until something bad (and unpredictable) happens?

From my viewpoint, we should increase the number until we get a steady stream of PGM bug reports. I don’t believe the absence of reports reflects an absence of bugs.

2023-08-25 15:04 UTC, aproskuryakov commented
I don't see a path forward for this PR when there is absolutely no explanation of how we arrive at the magic number 1/100.

2023-08-25 15:09 UTC, johnwilander commented
> I don't see a path forward for this PR when there is absolutely no explanation of how we arrive at the magic number 1/100.

What would convince you to allow us to try a higher magic number than today? As said, I see a huge benefit in finding more bugs that may be exploitable, so for me increasing those chances is the driver.

2023-08-25 15:13 UTC, aproskuryakov commented
I feel like I explained it several times already. Clearly, you find increasing the number dangerous, as you are not proposing to increase it to 1, only to 0.01. Please explain your decision making process. Why 0.01, and not 0.02, or 0.1, or 0.001?

Why you say "try a higher magic number", what does that mean exactly? How will you know that you attempted to raise it too high?

2023-08-28 22:12 UTC, MenloDorian approved these changes
r=me

2023-08-28 22:18 UTC, aproskuryakov requested changes
Obviously, my comments above indicate r-, at least until there is a good explanation.

2023-08-28 22:19 UTC, webkit-commit-queue commented
Committed 267366@main (df67bee62e85): <https://commits.webkit.org/267366@main>

Reviewed commits have been landed. Closing PR #16805 and removing active labels.

2023-08-28 22:19 UTC, merged

2023-08-28 22:22 UTC, aproskuryakov commented
(and since I lost the race with CQ, reverting this)

2023-08-30 01:24 UTC, ddkilzer commented
New pull request here:  https://github.com/WebKit/WebKit/pull/17212