[CSS] Always serialize implicit nesting selector/rule
WebKit/WebKit pull request #17064
Opened 2023-08-25 09:57 UTC by mdubet

#### 24ab5d6c968528de7e0c66ae301fc40a86b7399d
<pre>
[CSS] Always serialize implicit nesting selector/rule
<a href="https://bugs.webkit.org/show_bug.cgi?id=260707">https://bugs.webkit.org/show_bug.cgi?id=260707</a>
rdar://112900363

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/cssom-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/invalid-inner-rules-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/invalidation-003-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/invalidation-004-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/nesting-layer-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/parsing-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/parsing.html:
* LayoutTests/imported/w3c/web-platform-tests/css/css-nesting/serialize-group-rules-with-decls-expected.txt:
* Source/WebCore/css/CSSGroupingRule.cpp:
(WebCore::CSSGroupingRule::cssTextForDeclsAndRules const):
* Source/WebCore/css/CSSStyleRule.cpp:
(WebCore::CSSStyleRule::generateSelectorText const):
* Source/WebCore/css/parser/CSSParserSelector.cpp:
(WebCore::CSSParserSelector::hasExplicitNestingParent const):
* Source/WebCore/css/parser/CSSParserSelector.h:
(WebCore::CSSParserSelector::selector const):
* Source/WebCore/css/parser/CSSSelectorParser.cpp:
(WebCore::CSSSelectorParser::consumeNestedComplexSelector):
(WebCore::CSSSelectorParser::resolveNestingParent):
</pre>

2023-08-25 10:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/24ab5d6c968528de7e0c66ae301fc40a86b7399d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-30 13:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8417e54f4d935077b0baa2444c07b8ada4ec3550. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-30 14:34 UTC, anttijk commented
`Explanation of why this fixes the bug (OOPS!).`

OOPS!

2023-08-30 14:37 UTC, anttijk approved these changes
Please write some comments explaining the change. Looks fine otherwise.

2023-08-30 14:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/363425b6c68704e5cfac80f53d0b072682dd9b87. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-30 15:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b2c0e7bdf625c959c7bbbe234ced6e34910af3af. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-30 17:25 UTC, patrickangle requested changes

2023-08-30 17:25 UTC, patrickangle commented on LayoutTests/inspector/css/getMatchedStylesForNodeNestingStyleGrouping-expected.txt
> +PASS: Selector text should be "& .innerA".
This doesn't seem right. Web Inspector should show _authored styles_ and _not_ the serialized style, which in this case wouldn't include the implicit ampersand.

2023-08-30 18:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8a811418cac71100a47a43cd7c3548be373f92bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-31 18:51 UTC, patrickangle approved these changes

2023-08-31 19:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1d427432840f13dbe15162f641ccdf39c8ef8f86. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17064

2023-08-31 23:22 UTC, webkit-commit-queue commented
Committed 267531@main (41f7a301e412): <https://commits.webkit.org/267531@main>

Reviewed commits have been landed. Closing PR #17064 and removing active labels.

2023-08-31 23:22 UTC, merged