Increase probability of PGM activation from 1/1000 to 1/100
WebKit/WebKit pull request #17212
Opened 2023-08-30 01:24 UTC by ddkilzer

#### dfba6f450b137cb361c79bfd2bf342d2b19b7a6d
<pre>
Increase probability of PGM activation from 1/1000 to 1/100
<a href="https://bugs.webkit.org/show_bug.cgi?id=260362">https://bugs.webkit.org/show_bug.cgi?id=260362</a>
&lt;rdar://114042901&gt;

Reviewed by Mark Lam.

* Source/bmalloc/libpas/src/libpas/pas_probabilistic_guard_malloc_allocator.c:
(pas_probabilistic_guard_malloc_initialize_pgm):
- Change probability from 1000 to 100.
</pre>

2023-08-30 01:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dfba6f450b137cb361c79bfd2bf342d2b19b7a6d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17212

2023-08-30 01:28 UTC, ddkilzer commented
The info that was missing from https://github.com/WebKit/WebKit/pull/16805 was that @stwrt and @Constellation already did test libpas PGM with a 100% activation rate (which was the concern that @aproskuryakov had), and it showed no regressions.

This is now documented in comments via https://github.com/WebKit/WebKit/pull/17205 as well.

2023-08-30 01:48 UTC, johnwilander approved these changes
r=me

2023-08-30 02:02 UTC, aproskuryakov requested changes
> The info that was missing from https://github.com/WebKit/WebKit/pull/16805 was that @stwrt and @Constellation already did test libpas PGM with a 100% activation rate (which was the concern that @aproskuryakov had), and it showed no regressions.

Let's increase it to 100% then, not to 1%.

2023-08-30 02:08 UTC, MenloDorian commented
> > The info that was missing from #16805 was that @stwrt and @Constellation already did test libpas PGM with a 100% activation rate (which was the concern that @aproskuryakov had), and it showed no regressions.
> 
> Let's increase it to 100% then, not to 1%.

Alexey, there's no reason to increase it to 100%.  The 1% is conservative, and is all we need.  To increase it beyond that is to take unnecessary risk.

2023-08-30 02:09 UTC, MenloDorian approved these changes

2023-08-30 15:10 UTC, aproskuryakov commented
This doesn't add up. Per David's comment, 100% activation rate was tested, so what risk are you concerned about? And on the other hand, this was described as something to "try" in the previous PR, without any explanation of what feedback loop would be used to determine if trying proved to be successful or not.

There is a high bar for enabling potentially destructive experiments on users, and this clearly doesn't begin to approach the level or rigor needed for such.

2023-08-30 18:09 UTC, brentfulgham approved these changes
Looks good to me. r=me

2023-08-30 18:10 UTC, brentfulgham commented
> This doesn't add up. Per David's comment, 100% activation rate was tested, so what risk are you concerned about?

2023-08-30 18:21 UTC, aproskuryakov commented
Thank you, overloading telemetry channels makes some sense. Could you please DM me a link to you performance testing to review?

2024-07-17 20:53 UTC, ddkilzer commented
This PR was posted when only large allocations were supported by libpas PGM.

Now that small allocations are supported by libpas PGM via 8abe4988433e70fd4884abc737594c6b665f2e39 (see PR https://github.com/WebKit/WebKit/pull/30058), we should hold off on this change.

2024-07-17 20:53 UTC, closed without merging