Explicit tmp register for offlineasm instructions
WebKit/WebKit pull request #17231
Opened 2023-08-30 17:32 UTC by iangrunert

#### 47de51f033acbe144add3dcaec9ed2533dd3313c
<pre>
Explicit tmp register for offlineasm instructions
<a href="https://bugs.webkit.org/show_bug.cgi?id=260869">https://bugs.webkit.org/show_bug.cgi?id=260869</a>

Reviewed by NOBODY (OOPS!).

In offlineasm we reserve r11 as a scratch register on x86, for
truncatef2q, truncated2q, cq2f, cq2d, absf, absd, negf, negd.

We can change those instructions to take an additional GPR for use
as a scratch register, and return the power to choose when to use r11
to the programmer.

In arm this is usually a no-op for the tmp register, as there is a 1:1
mapping to an arm instruction. Mostly a change for x86_64.

Combined changes:
* Source/JavaScriptCore/llint/InPlaceInterpreter.asm:
* Source/JavaScriptCore/llint/WebAssembly.asm:
* Source/JavaScriptCore/llint/WebAssembly64.asm:
* Source/JavaScriptCore/offlineasm/registers.rb:
* Source/JavaScriptCore/offlineasm/x86.rb:
</pre>

2023-08-30 17:41 UTC, jjgriego commented on Source/JavaScriptCore/llint/WebAssembly.asm
> +#if X86_64
drive-by note: these files don't get run through the c preprocessor, you need to use offlineasm syntax (see e.g. in the above hunk, for `if X86_64`)

2023-08-30 17:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/27b6cad722aa6824fae334bd36f36c06b911b131. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17231

2023-09-08 18:01 UTC, Constellation requested changes
It should take wasm scratch register.

2023-09-08 18:33 UTC, iangrunert commented
I can use ws1 here if that's preferred? I was concerned that switching from r11 to ws1 (r10) for these instructions may break some callers, though it looks like it may be safe.

2023-09-18 22:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7eeab038350f0522db70829917f9c686e9cf522d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17231

2023-09-21 23:02 UTC, Constellation commented
I think using r11 for ws2 is wrong. r11 is assembler internal register. Why not using the other `ws0` or `ws1` registers and keep r11 as is. `r11` must be hidden from WebAssembly.asm etc. as the same to what MacroAssemblerX86 is doing.

2023-09-21 23:03 UTC, Constellation commented
MacroAssembler needs to keep this scratch register. Otherwise, we cannot do various other operations safely.

2023-09-22 00:45 UTC, iangrunert commented
The idea here was to make it clear when r11 was being used, such that on Windows we could use r11 for ws1 in WebAssembly.asm. I was unaware that MacroAssemblerX86_64 required r11 for other operations, I'd assumed it's primary purpose was for the usages I could see in offlineasm's x86.rb.

I guess it's back to the drawing board for figuring out how to deal with ws1 on Windows, this approach is a non-starter then.

2023-09-22 00:45 UTC, closed without merging