Build a specific version of webpushd for the WK_RELOCATABLE_FRAMEWORKS build
WebKit/WebKit pull request #17323
Opened 2023-09-01 03:09 UTC by beidson

#### ecf26bc70eb10303802c73eefb917d4bacf56c67
<pre>
Build a specific version of webpushd for the WK_RELOCATABLE_FRAMEWORKS build
<a href="https://bugs.webkit.org/show_bug.cgi?id=261010">https://bugs.webkit.org/show_bug.cgi?id=261010</a>
rdar://114801730

Reviewed by NOBODY (OOPS!).

This patch does two buckets of things for the WK_RELOCATABLE_FRAMEWORKS build:
1 - WebPushDaemon listens on a different service name, connects to apsd with a different service name, and creates a seperate push database.
2 - webpushd has a different product name, install location, different sandbox profile, and different launchd plist

* Source/WebKit/Configurations/BaseTarget.xcconfig:
* Source/WebKit/Configurations/WebKit.xcconfig:
* Source/WebKit/Configurations/webpushd.xcconfig:
* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources-output.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/NetworkProcess/mac/com.apple.WebKit.NetworkProcess.sb.in:
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Source/WebKit/webpushd/WebPushDaemonMain.mm:
(WebKit::applySandbox):
(WebKit::WebPushDaemonMain):
* Source/WebKit/webpushd/com.apple.webkit.webpushd.relocatable.mac.plist: Added.
* Source/WebKit/webpushd/mac/com.apple.WebKit.webpushd.relocatable.mac.sb.in: Added.
</pre>

2023-09-01 03:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ecf26bc70eb10303802c73eefb917d4bacf56c67. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17323

2023-09-01 04:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/33c6e66013010c1d6804c4bbd6886c8155404053. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17323

2023-09-01 17:22 UTC, achristensen07 approved these changes

2023-09-01 17:22 UTC, achristensen07 commented on Source/WebKit/webpushd/WebPushDaemonMain.mm
> +garbageline
remove

2023-09-01 17:22 UTC, achristensen07 commented on Source/WebKit/webpushd/WebPushDaemonMain.mm
> +#if defined(RELOCATABLE_WEBPUSHD)
I like #ifdef better, but this is fine.
Also, we might want to make this fit into the USE(RELOCATABLE_WEBPUSHD) convention we have elsewhere.

2023-09-01 17:22 UTC, achristensen07 commented on Source/WebKit/webpushd/WebPushDaemonMain.mm
> +            String pushDatabasePath = FileSystem::pathByAppendingComponents(libraryPath, { "WebKit"_s, "WebPush"_s, "PushDatabase.relocatable.db"_s });
It would be slightly more concise to just have the ASCIILiteral have 2 definitions instead of duplicating the whole line.

2023-09-01 17:22 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/mac/com.apple.WebKit.NetworkProcess.sb.in
> +(allow mach-lookup (global-name "com.apple.webkit.webpushd.relocatable.service"))
We don't need both of these.  We will only ever need one or the other.

2023-09-01 17:32 UTC, emw-apple commented on Source/WebKit/WebKit.xcodeproj/project.pbxproj
> +		5124D5272AA19DCB005229E1 /* com.apple.WebKit.webpushd.relocatable.mac.sb */ = {isa = PBXFileReference; lastKnownFileType = text; name = com.apple.WebKit.webpushd.relocatable.mac.sb; path = ../../..
Bad path! I think this needs to be:

```suggestion
		5124D5272AA19DCB005229E1 /* com.apple.WebKit.webpushd.relocatable.mac.sb */ = {isa = PBXFileReference; lastKnownFileType = text; name = com.apple.WebKit.webpushd.relocatable.mac.sb; path = DerivedSources/WebKit/com.apple.WebKit.webpushd.relocatable.mac.sb; sourceTree = BUILT_PRODUCTS_DIR; };
```

2023-09-01 17:36 UTC, emw-apple requested changes
Marking r- to make sure you get signoff from me on the build system bits.

One of the other things to note is that WK_RELOCATABLE_FRAMEWORKS includes Debug/Release ("at-desk") builds. Naively, it seems like we would want Debug/Release webpushd to behave like the STP/relocatable variant, since it has to do similar things like coexist with the webpushd provided by the system.

2023-09-02 15:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/068bd678c037ec0430e86ea85d8bddffc9116ed4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17323

2023-09-02 17:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2e14ab2161674d92c3d178eabd0f79185ffa320c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17323

2023-09-05 16:46 UTC, emw-apple approved these changes

2023-09-05 17:29 UTC, webkit-commit-queue commented
Committed 267636@main (fdabe492fd9a): <https://commits.webkit.org/267636@main>

Reviewed commits have been landed. Closing PR #17323 and removing active labels.

2023-09-05 17:29 UTC, merged