adoptedStyleSheets (ObservableArray) has non-writable length
WebKit/WebKit pull request #17350
Opened 2023-09-01 17:48 UTC by cdumez

#### 179d4dc6688a5163c36a22eb15dbd0389c5be3d2
<pre>
adoptedStyleSheets (ObservableArray) has non-writable length
<a href="https://bugs.webkit.org/show_bug.cgi?id=260716">https://bugs.webkit.org/show_bug.cgi?id=260716</a>
rdar://114822538

Reviewed by NOBODY (OOPS!).

Make adoptedStyleSheets (ObservableArray)&apos;s length property settable to
match Blink and Gecko.

* LayoutTests/cssom/observable-array-setter-expected.txt: Added.
* LayoutTests/cssom/observable-array-setter.html: Added.
* Source/WebCore/bindings/js/JSObservableArray.cpp:
(JSC::JSObservableArray::getOwnPropertySlot):
(JSC::JSObservableArray::put):
* Source/WebCore/bindings/js/JSObservableArray.h:
* Source/WebCore/css/CSSStyleSheetObservableArray.cpp:
(WebCore::CSSStyleSheetObservableArray::setLength):
* Source/WebCore/css/CSSStyleSheetObservableArray.h:
</pre>

2023-09-01 17:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/179d4dc6688a5163c36a22eb15dbd0389c5be3d2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17350

2023-09-01 17:59 UTC, Constellation requested changes

2023-09-01 17:59 UTC, Constellation commented on Source/WebCore/bindings/js/JSObservableArray.cpp
> +    }
I think `::defineOwnProperty` implementation and `deleteProperty`'s length support is necessary, so let's add them.
Can you also include tests for them?

2023-09-01 18:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/60076141ae10a744e672c947383afe3e17b00a9b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17350

2023-09-02 02:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/44af4328b6a0303e8f9b4097153fa94b8eb868e6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17350

2023-09-02 05:26 UTC, cdumez commented
This new iteration should align us pretty well with the spec and has much more testing. PTAL

2023-09-03 09:51 UTC, Constellation approved these changes
r=me

2023-09-03 16:25 UTC, webkit-commit-queue commented
Committed 267594@main (8e072e6f9bed): <https://commits.webkit.org/267594@main>

Reviewed commits have been landed. Closing PR #17350 and removing active labels.

2023-09-03 16:25 UTC, merged