Stripping whitespace in <animate> values attribute should use stripLeadingAndTrailingMatchedCharacters(isHTMLSpace<UChar>)
WebKit/WebKit pull request #1746
Opened 2022-06-23 22:11 UTC by nt1m

#### 0916b76c70baf822c2e5d6e95bf664581cf9b53b
<pre>
Stripping whitespace in &lt;animate&gt; values attribute should use stripLeadingAndTrailingMatchedCharacters(isHTMLSpace&lt;UChar&gt;)
<a href="https://bugs.webkit.org/show_bug.cgi?id=241867">https://bugs.webkit.org/show_bug.cgi?id=241867</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/svg/SVGAnimationElement.cpp:
(WebCore::SVGAnimationElement::attributeContainsJavaScriptURL const):
(WebCore::SVGAnimationElement::parseAttribute):
</pre>

2022-06-23 22:33 UTC, cdumez requested changes

2022-06-23 22:33 UTC, cdumez commented on Source/WebCore/svg/SVGAnimationElement.cpp
> +            if (WTF::protocolIsJavaScript(innerValue.stripLeadingAndTrailingMatchedCharacters(isHTMLSpace<UChar>)))
Why?

StringView::stripWhiteSpace() is already an alias for StringView::stripLeadingAndTrailingMatchedCharacters(isHTMLSpace<UChar>) AFAIK. The new code is less concise and should have identical.

I may be missing something but then again, the change log doesn't explain anything.

2022-06-23 22:37 UTC, cdumez commented on Source/WebCore/svg/SVGAnimationElement.cpp
> +            if (WTF::protocolIsJavaScript(innerValue.stripLeadingAndTrailingMatchedCharacters(isHTMLSpace<UChar>)))
Oh:

```
StringView StringView::stripWhiteSpace() const
{
    return stripLeadingAndTrailingMatchedCharacters(isASCIISpace<UChar>);
}
```

So stripWhiteSpace() strips ASCII spaces and your new patch only strips HTML spaces.

2022-06-23 22:47 UTC, cdumez approved these changes
OK. That said, I am not 100% sure that we're meant to use HTML spaces. I found this in the SMIL spec (which the SVG spec seems to reference):
```
S              ::= (#x20 | #x9 | #xD | #xA)+ /* from [[XML11]](https://www.w3.org/TR/SMIL3/smil30.html#smil-refs-ref-XML11) */
```

2022-06-23 23:03 UTC, weinig commented
This is testable, so really needs a test.

2022-06-24 15:04 UTC, darinadler commented
I agree with Sam. We need the tests even more than we need debate about which is correct.

Separately, I also think we should rename functions that say “space” to specify which definition: HTML, ASCII, Unicode, HTTP at least I believe have four different definitions of “what is a space”.

2022-06-24 15:14 UTC, darinadler commented
HTTP: 09/0A/0D/20
HTML: 09/0A/0C/0D/20
ASCII: 09/0A/0B/0C/0D/20
Unicode: same as ASCII plus **many** non-ASCII characters

From the BNF above it looks like SMIL matches HTTP, not HTML.

Tests need to include U+000B and U+000C to verify they are not treated as spaces.

2022-06-24 17:04 UTC, darinadler commented
Low priority i guess, no rush, but sure would be nice to have this exactly right instead of just “close enough”.

2022-06-24 17:05 UTC, darinadler commented
The pull request as is is already valuable because it stops the code from incorrectly stripping U+000B, and otherwise does no harm.

2022-06-24 17:06 UTC, darinadler approved these changes

2022-06-24 17:10 UTC, cdumez commented
> The pull request as is is already valuable because it stops the code from incorrectly stripping U+000B, and otherwise does no harm.

Not only that, this patch aligns our behavior with Blink (they are using `StripWhiteSpace(IsHTMLSpace<UChar>)`).

2022-06-24 20:52 UTC, webkit-commit-queue commented
Committed 251835@main (e41bfba750f7): <https://commits.webkit.org/251835@main>

Reviewed commits have been landed. Closing PR #1746 and removing active labels.

2022-06-24 20:52 UTC, merged