[GTK][WPE] Add separate setting and API to control IndexedDB API
WebKit/WebKit pull request #17858
Opened 2023-09-18 13:52 UTC by pgorszkowski-igalia

#### 962362406461ebf2269abc6e88382df7bcb19698
<pre>
[GTK][WPE] Add separate setting and API to control IndexedDB API
<a href="https://bugs.webkit.org/show_bug.cgi?id=261669">https://bugs.webkit.org/show_bug.cgi?id=261669</a>

Reviewed by NOBODY (OOPS!).

After <a href="https://bugs.webkit.org/show_bug.cgi?id=245484">https://bugs.webkit.org/show_bug.cgi?id=245484</a> we need to add a separate
setting and API to control visibility of the indexedDB API (<a href="https://www.w3.org/TR/IndexedDB/).">https://www.w3.org/TR/IndexedDB/).</a>

By default IndexedDB API is enabled. To change that we can use runtime flag:
&quot;enable-indexeddb-api&quot; or by calling &quot;webkit_settings_set_enable_indexeddb_api&quot;.

* Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp:
(webKitSettingsSetProperty):
(webKitSettingsGetProperty):
(webkit_settings_class_init):
(webkit_settings_get_enable_indexeddb_api):
(webkit_settings_set_enable_indexeddb_api):
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp:
(testWebViewEnableIndexedDBAPI):
(beforeAll):
</pre>

2023-09-18 13:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/962362406461ebf2269abc6e88382df7bcb19698. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17858

2023-09-18 14:29 UTC, mcatanzaro requested changes
The existing enable-html5-database setting already exists for enabling/disabled IndexedDB. If that no longer works after [254772@main](https://commits.webkit.org/254772@main), then it's a serious regression that we need to fix before making any further changes.

 * This is missing `Since: 2.44` tags on the new methods and the new property
 * I would rename `enable-indexeddb-api` to just `enable-indexeddb` to simplify the name.
 * You should definitely deprecate the existing html5-database setting if adding this replacement.
 * I'm not convinced it really makes sense to add a new setting that has effectively no behavior difference vs. the existing setting. WebSQL is no longer supported, and the html5-database setting is documented to only affect IndexedDB nowadays. Your new setting has a better name, but that's not really sufficient justification for new APIs.

I think my preference would be:

 * Fix, make sure to unbreak the existing html5-database setting if it's broken
 * Rename the setting in a future API version, e.g. by adding a new preprocessor guard `ENABLE_FUTURE_GLIB_API` and making the changes conditional on that. Then 5-10 years from now, if WebKitGTK still exists, we can flip that flag and get the nicer names. There are a few other APIs that I'd like to rename....

2023-09-18 14:30 UTC, mcatanzaro commented
Regarding the build failures: you forgot to update WebKitSettings.h.in

2023-09-18 15:29 UTC, pgorszkowski-igalia commented
> The existing enable-html5-database setting already exists for enabling/disabled IndexedDB. If that no longer works after [254772@main](https://commits.webkit.org/254772@main), then it's a serious regression that we need to fix before making any further changes.
> 
>     * This is missing `Since: 2.44` tags on the new methods and the new property
> 
>     * I would rename `enable-indexeddb-api` to just `enable-indexeddb` to simplify the name.
> 
>     * You should definitely deprecate the existing html5-database setting if adding this replacement.
> 
>     * I'm not convinced it really makes sense to add a new setting that has effectively no behavior difference vs. the existing setting. WebSQL is no longer supported, and the html5-database setting is documented to only affect IndexedDB nowadays. Your new setting has a better name, but that's not really sufficient justification for new APIs.
> 
> 
> I think my preference would be:
> 
>     * Fix, make sure to unbreak the existing html5-database setting if it's broken
> 
>     * Rename the setting in a future API version, e.g. by adding a new preprocessor guard `ENABLE_FUTURE_GLIB_API` and making the changes conditional on that. Then 5-10 years from now, if WebKitGTK still exists, we can flip that flag and get the nicer names. There are a few other APIs that I'd like to rename....

"enable-html5-database" setting is used (with/without my change) for enabling/disabling deprecated Web SQL database interface(which is deprecated) (https://www.w3.org/TR/webdatabase/)
Without my change there is no possibility to disable IndexedDB API in runtime (it is possible in build time by changing proper value in UnifiedWebPreferences.yaml).

2023-09-18 16:55 UTC, mcatanzaro commented
> "enable-html5-database" setting is used (with/without my change) for enabling/disabling deprecated Web SQL database interface(which is deprecated) (https://www.w3.org/TR/webdatabase/)

And yet, the documentation of `WebKitSettings:enable-html5-database` says:

> Whether to enable HTML5 client-side SQL database support (IndexedDB).

And the documentation of `webkit_settings_get_enable_html5_database()` says:

> Returns: %TRUE if IndexedDB support is enabled or %FALSE otherwise.

So the required behavior is not in doubt. :)

The documentation does not mention WebSQL anymore because WebKit does not support WebSQL anymore.

> Without my change there is no possibility to disable IndexedDB API in runtime (it is possible in build time by changing proper value in UnifiedWebPreferences.yaml).

If the existing setting is broken, we need to fix it, because that's what all existing applications expect.

2023-09-19 07:27 UTC, pgorszkowski-igalia commented
> Regarding the build failures: you forgot to update WebKitSettings.h.in

Interesting, I have errors if I build webkit with flatpak. If I build it with my system libs, it builds without errors.

2023-09-19 07:52 UTC, pgorszkowski-igalia commented
My concerns about using `enable-html5-database` for enabling/disabling `indexedDBAPI` was because `enable-html5-database` is used indirectly also in case of WebSQL(but only if `webSQLEnabled` is on): 
`webkit_settings_set_enable_html5_database` modifies `databasesEnabled`, `databasesEnabled` is used in WebPage.cpp to set availability of databases: 
`DatabaseManager::singleton().setIsAvailable(store.getBoolValueForKey(WebPreferencesKey::databasesEnabledKey()));`
and finally `DatabaseManager::singleton().isAvailable` is used in `LocalDOMWindowWebDatabase::openDatabase` (which is used if `webSQLEnabled` is on - the deprecated global setting which is by default false).

So as conclusion: due to the fact that by default WebSQL is disabled, and `enable-html5-database` should be used only for indexedDB I will reuse it for modifying the setting: `IndexedDBAPI`. As a separate ticket, we should clean up things with `DatabaseManager::singleton()::isAvailable` in case of `LocalDOMWindowWebDatabase::openDatabase` (it is currently disabled code so nothing crucial).

2023-09-19 08:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/79631af1bfa83554c51f6974d8c1a2cc2bef201a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/17858

2023-09-19 12:59 UTC, mcatanzaro commented
> Probably we should also remove setting: DatabasesEnabled or make it deprecated.

Yeah, it's really confusing to have so many settings. Ideally we would have only one setting for IndexedDB.

I had thought the WebSQL support had been completely removed. Surprised that's still around. Anyway, as long as it's always off, it's no problem.

2023-09-19 13:13 UTC, mcatanzaro reviewed
OK, the changes look good now. The commit message needs to be updated since you've completely rewritten this patch, though.

Does the test fail without your changes to WebKitSettings.cpp? My assumption is that the databasesEnabled setting disables all other database settings, so that it would still effectively enable/disable IndexedDB? If so, then your test should pass either way and the changes to WebKitSettings.cpp are optinal. If not, then the enable-html5-database setting has been broken since 2.40, which is unfortunate. Oh well, at least we'll have a good test now.

2023-09-19 13:47 UTC, pgorszkowski-igalia commented
> OK, the changes look good now. The commit message needs to be updated since you've completely rewritten this patch, though.

yes, I was waiting for your acceptance. I will update also the bug report topic

2023-09-19 14:01 UTC, pgorszkowski-igalia commented
> Does the test fail without your changes to WebKitSettings.cpp? My assumption is that the databasesEnabled setting disables all other database settings, so that it would still effectively enable/disable IndexedDB? If so, then your test should pass either way and the changes to WebKitSettings.cpp are optinal. If not, then the enable-html5-database setting has been broken since 2.40, which is unfortunate. Oh well, at least we'll have a good test now.

Without my changes in WebKitSettings.cpp, my test fails. `enable-html5-database` has been broken since the beginning in case of IndexedDB API.

2023-09-19 17:32 UTC, mcatanzaro approved these changes

2023-09-19 19:42 UTC, webkit-commit-queue commented
Committed 268142@main (c58657f2f72f): <https://commits.webkit.org/268142@main>

Reviewed commits have been landed. Closing PR #17858 and removing active labels.

2023-09-19 19:42 UTC, merged