Regression(247804@main): Network process is terminated while fetching website data
WebKit/WebKit pull request #1792
Opened 2022-06-25 04:28 UTC by szewai

#### 947807430f54a53b4c3d4ec4b0bba9e9fbac6255
<pre>
Regression(247804@main): Network process is terminated while fetching website data
<a href="https://bugs.webkit.org/show_bug.cgi?id=241830">https://bugs.webkit.org/show_bug.cgi?id=241830</a>

Reviewed by NOBODY (OOPS!).

229885@main moves the ownership of NetworkProcessProxy from WebProcessPool to WebsiteDataStore, and we started to have
an issue that network process never exits, because we have default WebsiteDataStore that is never destroyed.
236145@main tries to make network process exit by setting NetworkProcessProxy::defaultNetworkProcess() to null when last
WebProcessPool is gone. However, it didn&apos;t achieve the goal, because it failed to clear the reference in
WebsiteDataStore, which means network process can stay as long as default WebsiteDataStore.
247804@main fixes the issue above by clearing the reference in WebsiteDataStore and now network process will actually
be terminated when last WebProcessPool is destroyed. However, network process can be terminated when WebsiteDataStore is
using it (e.g. waiting for task reply as in new test).

We may fix this issue by protecting NetworkProcessProxy when WebsiteDataStore is using network process, but this is
non-intuitive and with this approach we may accidentally introduce the bug again (i.e. we fail to protect
NetworkProcessProxy in some case and network process gets terminated while in use). Also, network process can carry
some session states in memory, so it feels weird that the states are lost while WebsiteDataStore is stil alive. The
correct solution may be let default WebsiteDataStore be destroyed when it&apos;s not in use.

Therefore, to fix existing bug, the patch restores the old behavior: network process is terminated when last
WebsiteDataStore using it is destroyed.

* Source/WebKit/UIProcess/Network/NetworkProcessProxy.cpp:
(WebKit::NetworkProcessProxy::defaultNetworkProcess):
(WebKit::NetworkProcessProxy::ensureDefaultNetworkProcess):
* Source/WebKit/UIProcess/Network/NetworkProcessProxy.h:
* Source/WebKit/UIProcess/WebProcessPool.cpp:
(WebKit::WebProcessPool::~WebProcessPool):
* Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp:
(WebKit::protectedDefaultDataStore):
(WebKit::globalDefaultDataStore):
(WebKit::WebsiteDataStore::defaultDataStore):
(WebKit::WebsiteDataStore::deleteDefaultDataStoreForTesting):
(WebKit::WebsiteDataStore::removeNetworkProcessReference): Deleted.
* Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.h:
(WebKit::WebsiteDataStore::networkProcessIfExists):
* Tools/TestWebKitAPI/Tests/WebKitCocoa/NetworkProcess.mm:
(TEST):
* Tools/TestWebKitAPI/Tests/WebKitCocoa/WKWebsiteDatastore.mm:
(TestWebKitAPI::TEST):
</pre>

2022-06-27 14:54 UTC, cdumez requested changes
You needed to modify NetworkProcess.TerminateWhenUnused API which is evidence that you regressed things.

You managed to keep the test "mostly" passing by calling [WKWebsiteDataStore _deleteDefaultDataStoreForTesting], which is something clients cannot do.

So the result with this patch is the same as with the last patch, the network process doesn't exit if the default data store was ever used, which is not OK.

2022-06-27 15:11 UTC, szewai commented
> You needed to modify NetworkProcess.TerminateWhenUnused API which is evidence that you regressed things.
> 
> You managed to keep the test "mostly" passing by calling [WKWebsiteDataStore _deleteDefaultDataStoreForTesting], which is something clients cannot do.
> 
> So the result with this patch is the same as with the last patch, the network process doesn't exit if the default data store was ever used, which is not OK.

Discussion is here: https://a1391192.slack.com/archives/CUQM01M6W/p1655995279995689?thread_ts=1655921145.491589&cid=CUQM01M6W... (I don't see your comment there so I assumed no objection.)

2022-06-27 16:57 UTC, cdumez commented
> > You needed to modify NetworkProcess.TerminateWhenUnused API which is evidence that you regressed things.
> > You managed to keep the test "mostly" passing by calling [WKWebsiteDataStore _deleteDefaultDataStoreForTesting], which is something clients cannot do.
> > So the result with this patch is the same as with the last patch, the network process doesn't exit if the default data store was ever used, which is not OK.
> 
> Discussion is here: https://a1391192.slack.com/archives/CUQM01M6W/p1655995279995689?thread_ts=1655921145.491589&cid=CUQM01M6W... (I don't see your comment there so I assumed no objection.)

At the risk of repeating myself, I don't think it is acceptable to leak the network process if the default data store has ever been used. I haven't seen any argument that would convince me otherwise.

We used to get this right so we can get this right again.

2022-06-29 20:06 UTC, szewai commented
> > > You needed to modify NetworkProcess.TerminateWhenUnused API which is evidence that you regressed things.
> > > You managed to keep the test "mostly" passing by calling [WKWebsiteDataStore _deleteDefaultDataStoreForTesting], which is something clients cannot do.
> > > So the result with this patch is the same as with the last patch, the network process doesn't exit if the default data store was ever used, which is not OK.
> > 
> > 
> > Discussion is here: https://a1391192.slack.com/archives/CUQM01M6W/p1655995279995689?thread_ts=1655921145.491589&cid=CUQM01M6W... (I don't see your comment there so I assumed no objection.)
> 
> At the risk of repeating myself, I don't think it is acceptable to leak the network process if the default data store has ever been used. I haven't seen any argument that would convince me otherwise.
> 
> We used to get this right so we can get this right again.

Based on our in-person discussion today, we are going to do this as first step.

I added loggings to constructor and destructor of WebsiteDataStore.

2022-06-29 20:09 UTC, cdumez approved these changes
LGTM with typo fix.

2022-06-29 20:09 UTC, cdumez commented on Source/WebKit/UIProcess/Network/NetworkProcessProxy.cpp
> +    auto& networkProcesss = defaultNetworkProcess();
Typo: networkProcesss

2022-06-30 06:34 UTC, webkit-commit-queue commented
Committed 251983@main (5867c9a72edd): <https://commits.webkit.org/251983@main>

Reviewed commits have been landed. Closing PR #1792 and removing active labels.

2022-06-30 06:34 UTC, merged