[WGSL] Bring ruby DSL syntax closer to WGSL
WebKit/WebKit pull request #18084
Opened 2023-09-22 16:29 UTC by tadeuzagallo

#### 53842b95112dee819c1d581caef0d3b722432053
<pre>
[WGSL] Bring ruby DSL syntax closer to WGSL
<a href="https://bugs.webkit.org/show_bug.cgi?id=261954">https://bugs.webkit.org/show_bug.cgi?id=261954</a>
rdar://115897869

Reviewed by NOBODY (OOPS!).

Just a small cosmetic update to the ruby DSL, which makes the way types are written
more similar to WGSL. This makes it easier to translate the declarations from the
spec into our DSL (and hopefully a little more readable).

* Source/WebGPU/WGSL/Constraints.cpp:
(WGSL::concretize):
* Source/WebGPU/WGSL/Overload.cpp:
(WGSL::OverloadResolver::materialize const):
* Source/WebGPU/WGSL/Overload.h:
* Source/WebGPU/WGSL/TypeCheck.cpp:
(WGSL::TypeChecker::vectorFieldAccess):
(WGSL::TypeChecker::allocateSimpleConstructor):
* Source/WebGPU/WGSL/TypeDeclarations.rb:
* Source/WebGPU/WGSL/TypeStore.cpp:
(WGSL::TypeStore::vectorType):
(WGSL::TypeStore::matrixType):
(WGSL::TypeStore::textureType):
* Source/WebGPU/WGSL/TypeStore.h:
* Source/WebGPU/WGSL/generator/main.rb:
</pre>

2023-09-22 16:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/53842b95112dee819c1d581caef0d3b722432053. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18084

2023-09-24 23:42 UTC, djg commented
EWS seems really unhappy about the ruby changes.

2023-09-25 03:11 UTC, djg requested changes
The C++ changes look fine. I've looked at the Ruby changes. Is `AggregateConstructor` used at all? I'd like to see a fixed build first.

2023-09-25 05:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0c81df65a99ddc26a2e77362e02049d3b577857d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18084

2023-09-25 05:48 UTC, tadeuzagallo commented
> The C++ changes look fine. I've looked at the Ruby changes. Is `AggregateConstructor` used at all? I'd like to see a fixed build first.

My last fixes didn't get pushed 🥲 Uploading now

2023-09-25 08:34 UTC, djg approved these changes
:shipit:

2023-09-25 09:51 UTC, webkit-commit-queue commented
Committed 268392@main (fdfe9a0be986): <https://commits.webkit.org/268392@main>

Reviewed commits have been landed. Closing PR #18084 and removing active labels.

2023-09-25 09:51 UTC, merged