HighlightRegister should be renamed to HighlightRegistry.
WebKit/WebKit pull request #18531
Opened 2023-10-03 03:47 UTC by megangardner

#### 284303da4c4ca7ed1f59748cf0d7aa9ff3e7a2bc
<pre>
HighlightRegister should be renamed to HighlightRegistry.
<a href="https://bugs.webkit.org/show_bug.cgi?id=262522">https://bugs.webkit.org/show_bug.cgi?id=262522</a>
rdar://116262991

Reviewed by NOBODY (OOPS!).

HighlightRegister is the old version, need to rename to HighlightRegistry
to be compliant with he current spec.

* Source/WebCore/Modules/highlight/HighlightRegistry.cpp: Renamed from Source/WebCore/Modules/highlight/HighlightRegister.cpp.
(WebCore::HighlightRegistry::initializeMapLike):
(WebCore::HighlightRegistry::setFromMapLike):
(WebCore::HighlightRegistry::clear):
(WebCore::HighlightRegistry::remove):
(WebCore::HighlightRegistry::setHighlightVisibility):
(WebCore::annotationHighlightKey):
(WebCore::HighlightRegistry::addAnnotationHighlightWithRange):
* Source/WebCore/Modules/highlight/HighlightRegistry.h: Renamed from Source/WebCore/Modules/highlight/HighlightRegister.h.
(WebCore::HighlightRegistry::create):
(WebCore::HighlightRegistry::isEmpty const):
(WebCore::HighlightRegistry::highlightsVisibility const):
(WebCore::HighlightRegistry::map const):
(WebCore::HighlightRegistry::highlightNames const):
* Source/WebCore/Modules/highlight/HighlightRegistry.idl: Renamed from Source/WebCore/Modules/highlight/HighlightRegister.idl.
</pre>

2023-10-03 03:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/284303da4c4ca7ed1f59748cf0d7aa9ff3e7a2bc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-03 03:50 UTC, pxlcoder approved these changes
Might be nice to link to the spec in the commit message: https://drafts.csswg.org/css-highlight-api/#registration

2023-10-03 03:51 UTC, rr-codes approved these changes

2023-10-03 15:38 UTC, smfr requested changes
This is missing a bunch of places that use the old name (e.g. in Document.cpp)

2023-10-03 17:42 UTC, megangardner commented
> This is missing a bunch of places that use the old name (e.g. in Document.cpp)

Ugh, the script always leaves everything else behind when you change file names. Pushing again with all changes...

2023-10-03 17:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cbd4d6ec1089d941de90b7bd2534b4ccda63af79. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-03 18:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/01ae36586add260e650395b8daac035c05143fb9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-03 20:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c5d5ed43373c35a87e2e80f086d6670b9891b998. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-03 21:10 UTC, aprotyas approved these changes

2023-10-03 23:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ed0a168c9fb712203e0ec0b3f96133ec358bf135. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-04 14:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bc0686c800f84979e5759d78ce6bdd2516fdda2c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-04 17:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b2c11439b2b0d3f3d814bc2abaa578684b64c340. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-04 19:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3cbdeb77b9469e2695ca10e392cc895f0a3a0779. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/18531

2023-10-04 21:11 UTC, webkit-commit-queue commented
Committed 268873@main (5c10221be14f): <https://commits.webkit.org/268873@main>

Reviewed commits have been landed. Closing PR #18531 and removing active labels.

2023-10-04 21:11 UTC, merged