Make Alan Coon (@alancoon) a committer.
WebKit/WebKit pull request #1876
Opened 2022-06-28 23:06 UTC by alancoon

#### a225e02f8de6e666b19b097abeb0813d5b21d783
<pre>
Make Alan Coon (@alancoon) a committer.
</pre>

2022-06-28 23:09 UTC, alancoon commented
@JonWBedard is this the correct way to request this?

2022-06-29 15:22 UTC, JonWBedard commented
> @JonWBedard is this the correct way to request this?

From the technical perspective, yes, but we need to jump through the policy hoops as well, per https://webkit.org/commit-and-review-policy/

2022-06-29 15:23 UTC, JonWBedard requested changes
We need to follow our committer and reviewer policy.

2022-06-29 16:00 UTC, JonWBedard commented
> #### [a225e02](https://github.com/WebKit/WebKit/commit/a225e02f8de6e666b19b097abeb0813d5b21d783)
> Make Alan Coon (@alancoon) a committer.

Will need either a "Reviewed by" or "Unreviewed" in this commit message.

2022-06-29 16:01 UTC, JonWBedard commented
> We need to follow our committer and reviewer policy.

Looks like @alancoon was already (as of 2018) a committer, we just hadn't updated contributors.json

2022-07-13 00:16 UTC, merged