[libpas] pas_utils.c fails to build due to missing parameter names in pas_crash_with_info_impl()
WebKit/WebKit pull request #1878
Opened 2022-06-28 23:36 UTC by aperezdc

#### cdd415106886103664383bf0f345c494d2901e89
<pre>
[libpas] pas_utils.c fails to build due to missing parameter names in pas_crash_with_info_impl()
<a href="https://bugs.webkit.org/show_bug.cgi?id=242090">https://bugs.webkit.org/show_bug.cgi?id=242090</a>

Reviewed by NOBODY (OOPS!).

* Source/bmalloc/libpas/src/libpas/pas_utils.c:
(pas_crash_with_info_impl): Add missing parameter names, and use them
in void statements to avoid compiler warnings about unused variables.
</pre>

2022-06-29 00:52 UTC, Constellation commented
> #### [cdd4151](https://github.com/WebKit/WebKit/commit/cdd415106886103664383bf0f345c494d2901e89)
> [libpas] pas_utils.c fails to build due to missing parameter names in pas_crash_with_info_impl()
> https://bugs.webkit.org/show_bug.cgi?id=242090[](https://bugs.webkit.org/show_bug.cgi?id=242090)
> 
> Reviewed by NOBODY (OOPS!).
> 
> * Source/bmalloc/libpas/src/libpas/pas_utils.c:
> (pas_crash_with_info_impl): Add missing parameter names, and use them
> in void statements to avoid compiler warnings about unused variables.

Why does it cause warnings? They are not used, and they do not have parameter names. I think this code should be fine.

2022-06-29 00:53 UTC, Constellation requested changes

2022-06-29 00:53 UTC, Constellation commented on Source/bmalloc/libpas/src/libpas/pas_utils.c
> +PAS_NEVER_INLINE PAS_NO_RETURN static void pas_crash_with_info_impl(uint64_t reason, uint64_t misc1, uint64_t misc2, uint64_t misc3, uint64_t misc4, uint64_t misc5, uint64_t misc6)
Let's suppress warnings instead. We strongly want to keep this function having only `__builtin_trap`.

2022-06-29 09:03 UTC, aperezdc commented
> > #### [cdd4151](https://github.com/WebKit/WebKit/commit/cdd415106886103664383bf0f345c494d2901e89)
> > [libpas] pas_utils.c fails to build due to missing parameter names in pas_crash_with_info_impl()
> > [https://bugs.webkit.org/show_bug.cgi?id=242090[](https://bugs.webkit.org/show_bug.cgi?id=242090)](https://bugs.webkit.org/show_bug.cgi?id=242090%5B%5D(https://bugs.webkit.org/show_bug.cgi?id=242090))
> > Reviewed by NOBODY (OOPS!).
> > 
> > * Source/bmalloc/libpas/src/libpas/pas_utils.c:
> >   (pas_crash_with_info_impl): Add missing parameter names, and use them
> >   in void statements to avoid compiler warnings about unused variables.
> 
> Why does it cause warnings? They are not used, and they do not have parameter names. I think this code should be fine.

This source file is C (not C++), and parameter names in function declarations are mandatory. At least until [the C2x spec](https://en.wikipedia.org/wiki/C2x) is published and used in WebKit.

I remember seeing warnings about “C source being compiled in C++ mode” shown during compilation in the past so that's why we haven't seen the errors before.

I can change the void statements to `PAS_UNUSED_PARAM`, or wrap the function declaration between `PAS_IGNORE_GCC_WARNINGS_{BEGIN,END}`. Which approach would we prefer here?

2022-06-29 17:11 UTC, Constellation commented
> I can change the void statements to `PAS_UNUSED_PARAM`, or wrap the function declaration between `PAS_IGNORE_GCC_WARNINGS_{BEGIN,END}`. Which approach would we prefer here?

`PAS_IGNORE_GCC_WARNINGS_{BEGIN,END}` is better.

2022-06-29 17:12 UTC, Constellation requested changes

2022-06-29 17:12 UTC, Constellation commented on Source/bmalloc/libpas/src/libpas/pas_utils.c
> +PAS_NEVER_INLINE PAS_NO_RETURN static void pas_crash_with_info_impl(uint64_t reason, uint64_t misc1, uint64_t misc2, uint64_t misc3, uint64_t misc4, uint64_t misc5, uint64_t misc6)
OK, let's use `PAS_IGNORE_GCC_WARNINGS_{BEGIN,END}`

2022-06-30 00:41 UTC, Constellation approved these changes
r=me

2022-06-30 10:06 UTC, aperezdc commented
> r=me

Thanks @Constellation!

2022-06-30 10:56 UTC, webkit-commit-queue commented
Committed 251986@main (ff4150d0f6d4): <https://commits.webkit.org/251986@main>

Reviewed commits have been landed. Closing PR #1878 and removing active labels.

2022-06-30 10:56 UTC, merged