[JSC][armv7] Reserve `d14` as a scratch register for wasm JITs
WebKit/WebKit pull request #19234
Opened 2023-10-18 17:24 UTC by jjgriego

#### a864f296d9fe6c9032815ea90aa5a901f2bdc316
<pre>
[JSC][armv7] Reserve `d14` as a scratch register for wasm JITs
<a href="https://bugs.webkit.org/show_bug.cgi?id=263324">https://bugs.webkit.org/show_bug.cgi?id=263324</a>

Reviewed by NOBODY (OOPS!).

We really need an extra FP scratch register for wasm BBQ on armv7. In
particular, we use the `nonPreservedNonArgumentFPR0` for this purpose, but we
also ended up using register currently singled out as the
`nonPreservedNonArgumentFPR0`, `d7` as an argument register in BBQ JIT contexts.

To avoid the overlap, reserve `d14` as a scratch register--we copy exactly the
approach used to reserve `d15` as a scratch FPR for the macroassembler [1]:
though the register is callee-save in the platform ABI, we save/restore only at
VM entry/exit and the register is volatile in VM contexts.

[1] <a href="https://commits.webkit.org/250952@main">https://commits.webkit.org/250952@main</a>

* Source/JavaScriptCore/jit/FPRInfo.h:
* Source/JavaScriptCore/jit/RegisterSet.cpp:
(JSC::RegisterSetBuilder::vmCalleeSaveRegisters):
* Source/JavaScriptCore/llint/LowLevelInterpreter.asm:
* Source/JavaScriptCore/offlineasm/arm.rb:
</pre>

2023-10-18 17:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a864f296d9fe6c9032815ea90aa5a901f2bdc316. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19234

2023-10-18 17:46 UTC, Constellation requested changes
macroClobberedFPRs etc. needs to be changed. Can you grep all `fpTempRegister` sites, and fix that? I think we should define `fpTempRegister2` for ARMv7 and use it in the same way to RISCV.

2023-10-18 18:22 UTC, jjgriego commented
Sorry, just to make sure we're on the page: I want `d14` to be the `wasmScratchFPR` of the wasm BBQ JIT (hence the change to `nonPreservedNonArgumentFPR0`, not as an extra scratch in the macro assembler.

I suppose there's nothing _wrong_ with making it available in the macro assembler, but we still need a FPR higher than d7 (the last argument reg) for the wasmScratchFPR

2023-10-24 00:48 UTC, justinmichaud approved these changes
r=me

2023-10-25 14:51 UTC, jjgriego commented
going ahead and merging; like I said, the intent isn't to use this in the macro assembler so I don't think we need to add to macroClobberedRegisters

2023-10-25 15:21 UTC, webkit-commit-queue commented
Committed 269762@main (1ff6d45f35c1): <https://commits.webkit.org/269762@main>

Reviewed commits have been landed. Closing PR #19234 and removing active labels.

2023-10-25 15:21 UTC, merged