Web Inspector: Add Versioned Protocol for iOS 17.0 and macOS 14.0
WebKit/WebKit pull request #19670
Opened 2023-10-28 01:07 UTC by rcaliman-apple

#### 33f74da2d26c4d7a5a769e5afa67bdb3466173bb
<pre>
Web Inspector: Add Versioned Protocol for iOS 17.0 and macOS 14.0
<a href="https://bugs.webkit.org/show_bug.cgi?id=263814">https://bugs.webkit.org/show_bug.cgi?id=263814</a>
rdar://117611260

Reviewed by NOBODY (OOPS!).

Add legacy protocol definitions used while inspecting iOS 17.0 and macOS 14.0.

* Source/WebInspectorUI/UserInterface/Protocol/Legacy/macOS/14.0/InspectorBackendCommands.js: Added.
* Source/WebInspectorUI/Versions/Inspector-macOS-14.0.json: Added.
</pre>

2023-10-28 01:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/33f74da2d26c4d7a5a769e5afa67bdb3466173bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19670

2023-10-30 18:43 UTC, burg requested changes
The title mentions adding protocols for macOS and iOS, but I only see macOS versions here. Please add the iOS versions as well.

2023-10-31 19:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eb584750a660cf25f4dec086b6aa9ea90c6be3d8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19670

2023-10-31 19:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7159e3058f1e221d9ed0c5eeeb07bbc1823a8d27. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19670

2023-10-31 19:37 UTC, rcaliman-apple commented
@burg Needed some time to get a hold of the iOS protocol files. Added now and ready for review.

2023-11-01 20:12 UTC, burg approved these changes

2023-11-02 16:39 UTC, webkit-commit-queue commented
Committed 270112@main (edf420d77ee8): <https://commits.webkit.org/270112@main>

Reviewed commits have been landed. Closing PR #19670 and removing active labels.

2023-11-02 16:39 UTC, merged