[GStreamer] Cannot play mp4 videos in Element: Received unexpected 200 HTTP status code for range request
WebKit/WebKit pull request #19687
Opened 2023-10-29 10:02 UTC by philn

#### e14eade027dd52bed716a363020274b96ee7d36d
<pre>
[GStreamer] Cannot play mp4 videos in Element: Received unexpected 200 HTTP status code for range request
<a href="https://bugs.webkit.org/show_bug.cgi?id=221622">https://bugs.webkit.org/show_bug.cgi?id=221622</a>

Reviewed by NOBODY (OOPS!).

<a href="https://tools.ietf.org/id/draft-ietf-httpbis-p5-range-09.html#header.content-range">https://tools.ietf.org/id/draft-ietf-httpbis-p5-range-09.html#header.content-range</a>
If the server ignores a byte - range - spec because it is syntactically invalid, the
server SHOULD treat the request as if the invalid Range header field did not
exist. Normally, this means return a 200 response containing the full entity.

* Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp:
(CachedResourceStreamingClient::responseReceived):
</pre>

2023-10-29 10:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e14eade027dd52bed716a363020274b96ee7d36d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19687

2023-10-30 09:37 UTC, calvaris commented
I think @ntrrgc had an opinion about this.

2023-10-30 11:52 UTC, ntrrgc requested changes
Safari doesn't support media from servers without Content-Range support. Content-Range is needed for reasonable seek support. To support media without Content-Range it's necessary to store the entire file in memory, and a seek to time can only be implemented by downloading the entire file from the start.

2023-10-30 12:02 UTC, ntrrgc commented
If you really want to support servers without Content-Range support, the following issues need to be addressed:

1. If any RAM or file system cache is used, there must be a relatively small file size limit under which playback will be refused (if the server declares `Content-Length`) or aborted (if the server doesn't declare `Content-Length` but such length is reached). This must be communicated to users and developers through the browser console.
2. The pipeline must ensure no further seeks are sent to the source element. Instead, seeks to the future must be satisfied by waiting until buffering reaches the requested position, and seeks to the past must be satisfied from cached media. Otherwise, casual generous seeking from users would be very unresponsive and consume a lot of unnecessary network data.

2023-10-30 12:12 UTC, philn commented
> Safari doesn't support media from servers without Content-Range support.

Are you sure about this?

2023-10-30 12:17 UTC, ntrrgc commented
> > Safari doesn't support media from servers without Content-Range support.
> 
> Are you sure about this?

Yes, pretty much. For instance: https://stephenweiss.dev/safari-streaming-video

2023-10-30 13:28 UTC, closed without merging

2023-10-31 19:56 UTC, ntrrgc commented
@eric-carlson What do you mean with synthesizing range requests? I see a `RangeRequestSynthesisWithoutContentLength` test that removes the `Content-Length` header. Is the purpose of that make WebKit believe the content is a live stream and therefore shouldn't receive seeks?