Drop ARM softfp bot
WebKit/WebKit pull request #1984
Opened 2022-07-01 09:04 UTC by aoikonomopoulos

#### d9bff13c342b999640e7d5b5354c22053cc3503b
<pre>
Drop ARM softfp bot
<a href="https://bugs.webkit.org/show_bug.cgi?id=242236">https://bugs.webkit.org/show_bug.cgi?id=242236</a>

Reviewed by NOBODY (OOPS!).

The softfp ARMv7 bot has been kept around to ensure that things would
work for users that are depend on vendor libraries that require the
softfp ABI. Recent changes broke softfp and we&apos;re no longer aware of any
users for it. Bug 242172 drops JSC support for the softfp ABI; this bug
is about removing the corresponding buildbot from build.webkit.org.

* Tools/CISupport/build-webkit-org/config.json:
</pre>

2022-07-01 12:55 UTC, clopez approved these changes

2022-07-01 13:25 UTC, aperezdc requested changes
Ahhh, I didn't notice this one and made almost the same changes in #1991 

I do notice that this version is missing the edit in `Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js`, which I expect we want.

2022-07-04 10:11 UTC, aoikonomopoulos commented
> Ahhh, I didn't notice this one and made almost the same changes in #1991
> 
> I do notice that this version is missing the edit in `Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js`, which I expect we want.

We do, updated the PR.

2022-07-04 11:01 UTC, aperezdc reviewed
LGTM, you may want to get a final r+ from @aj062 or @JonWBedard

2022-07-04 12:02 UTC, aj062 commented on Tools/CISupport/build-webkit-org/config.json
> -                      "workernames": ["jsconly-linux-igalia-bot-5"]
Do you want to delete "jsconly-linux-igalia-bot-5" bot from this config.json, or assign it to some other queue or just leave it as is for now?

2022-07-04 12:02 UTC, aj062 approved these changes

2022-07-04 12:10 UTC, aoikonomopoulos commented on Tools/CISupport/build-webkit-org/config.json
> -                      "workernames": ["jsconly-linux-igalia-bot-5"]
Oops. I guess it's best that we just delete it and ask for a new worker if we ever need an extra one. Updating the PR shortly.

2022-07-04 12:33 UTC, webkit-commit-queue commented
Committed 252115@main (a5dc4a302620): <https://commits.webkit.org/252115@main>

Reviewed commits have been landed. Closing PR #1984 and removing active labels.

2022-07-04 12:33 UTC, merged

2022-07-04 13:35 UTC, aj062 commented
Restarted buildbot to pick up this change.