Add 2d-transform-inline-js.html for WPT test
WebKit/WebKit pull request #19896
Opened 2023-11-02 18:24 UTC by joone

#### 0d71af52b6fa440f214e42bd4f1dcd13fdbccaa9
<pre>
Add 2d-transform-inline-js.html for WPT test
<a href="https://bugs.webkit.org/show_bug.cgi?id=263699">https://bugs.webkit.org/show_bug.cgi?id=263699</a>
<a href="https://rdar.apple.com/problem/117523629">rdar://problem/117523629</a>

Reviewed by NOBODY (OOPS!).

This test ensures that getComputedStyle provides a valid transform value
for inline elements. Originally written for WebKit, it is rewritten for
WPT since such a test didn&apos;t exist there.

 * LayoutTests/imported/w3c/web-platform-tests/css/css-transforms/2d-transform-inline-js-expected.txt: Added.
 * LayoutTests/imported/w3c/web-platform-tests/css/css-transforms/2d-transform-inline-js.html: Added.
</pre>

2023-11-02 18:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0d71af52b6fa440f214e42bd4f1dcd13fdbccaa9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19896

2023-11-02 18:27 UTC, joone commented
@graouts PTAL

2023-11-02 21:28 UTC, graouts commented
You'll need to upstream this test, the script `export-w3c-test-changes` will help, although it's fine to do it manually as well.

2023-11-03 05:01 UTC, joone commented
> You'll need to upstream this test, the script `export-w3c-test-changes` will help, although it's fine to do it manually as well.

Done: https://github.com/web-platform-tests/wpt/pull/42936

2023-11-03 09:36 UTC, graouts requested changes
The test content itself looks good. However, I believe WPT tests use 2-space indent whereas your content seems to be using tabs. I think it would be good to address this.

2023-11-03 16:52 UTC, joone commented
Okay, I have reformatted the tabs to two spaces.

2023-11-04 19:42 UTC, graouts requested changes

2023-11-04 19:42 UTC, graouts commented on LayoutTests/imported/w3c/web-platform-tests/css/css-transforms/2d-transform-inline-js.html
> +		  .container {
That whole part still has tabs I'm afraid.

```suggestion
  <head>
    <title>JS test: Inline renderer must return the correct computed transform</title>
    <link rel="author" title="Joone Hur" href="https://joone.github.io">
    <link rel="help" href="https://drafts.csswg.org/css-transforms-1/#serialization-of-the-computed-value">
    <link rel="help" href="https://drafts.csswg.org/css-transforms-1/#serialization-of-transform-functions">
    <script src="/resources/testharness.js"></script>
    <script src="/resources/testharnessreport.js"></script>
    <meta name="assert" content="Asserting that you can apply transform to an inline element and it show up in CSS computed values as a matrix">
    <style>
      .container {
```

2023-11-04 19:42 UTC, graouts commented on LayoutTests/imported/w3c/web-platform-tests/css/css-transforms/2d-transform-inline-js.html
> +	</head>
More tabs here.

```suggestion
    </style>
  </head>
```

2023-11-04 19:42 UTC, graouts commented on LayoutTests/imported/w3c/web-platform-tests/css/css-transforms/2d-transform-inline-js.html
> +      let testCases = [
Total nit: you can use `const` here.

2023-11-07 00:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/70f76f79c08da71a7e06305a8f1494609cb7ccd5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19896

2023-11-07 00:30 UTC, joone commented
My patch was not updated in the previous pull request. Thanks for the review!

2023-11-07 07:41 UTC, graouts approved these changes

2023-11-07 07:42 UTC, graouts commented
> I only updated https://github.com/web-platform-tests/wpt/pull/42936/files in the previous PR. In this case, should I update my patch in both PRs?

If you used `export-w3c-test-changes`, I believe you can run it again and it will update the WPT PR.

2023-11-07 19:31 UTC, joone commented
Okay, I've updated my PR in https://github.com/web-platform-tests/wpt/pull/42936  Thanks!

2023-11-10 19:54 UTC, webkit-commit-queue commented
Committed 270557@main (f998524614f7): <https://commits.webkit.org/270557@main>

Reviewed commits have been landed. Closing PR #19896 and removing active labels.

2023-11-10 19:54 UTC, merged