Fix incorrect storage of AudioSourceProviderGStreamer
WebKit/WebKit pull request #19920
Opened 2023-11-03 00:29 UTC by mcatanzaro

#### 6f249dec888427d81fb0e519976c4d529387dc82
<pre>
Fix incorrect storage of AudioSourceProviderGStreamer
<a href="https://bugs.webkit.org/show_bug.cgi?id=264119">https://bugs.webkit.org/show_bug.cgi?id=264119</a>

Reviewed by NOBODY (OOPS!)

We cannot store refcounted objects in a std::unique_ptr since the object
may be deleted with an outstanding reference.

* Source/WebCore/platform/audio/gstreamer/AudioSourceProviderGStreamer.h:
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:
(WebCore::MediaPlayerPrivateGStreamer::ensureAudioSourceProvider):
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h:
</pre>

2023-11-03 00:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6f249dec888427d81fb0e519976c4d529387dc82. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19920

2023-11-03 08:12 UTC, philn approved these changes

2023-11-03 08:14 UTC, calvaris requested changes
You can't do this because AudioSourceProviderGStreamer can inherit from WebAudioSourceProvider and AudioSourceProvider. The first is ref counted, the latter isn't. If you fix the first, you can screw the latter. Further changes are needed.

2023-11-03 13:31 UTC, mcatanzaro commented
> You can't do this because AudioSourceProviderGStreamer can inherit from WebAudioSourceProvider and AudioSourceProvider. The first is ref counted, the latter isn't. If you fix the first, you can screw the latter. Further changes are needed.

Thanks for catching this.

2023-11-03 15:27 UTC, mcatanzaro commented
So WebAudioSourceProvider doesn't add any functionality on top of AudioSourceProvider besides refcounting, and doesn't depend on `ENABLE(MEDIA_STREAM)`. We should be able to inherit from it unconditionally.

2023-11-03 15:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/79039ae081588ef5ec1d16105e44694cb06de1eb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/19920

2023-11-06 08:54 UTC, philn commented
@calvaris are you going to review this?

2023-11-06 09:24 UTC, calvaris approved these changes
This lgtm but I would like @philn to agree, as he knows more about this area.

2023-11-06 10:48 UTC, philn approved these changes

2023-11-06 15:30 UTC, webkit-commit-queue commented
Committed 270266@main (0f803ec2d5e6): <https://commits.webkit.org/270266@main>

Reviewed commits have been landed. Closing PR #19920 and removing active labels.

2023-11-06 15:31 UTC, merged