REGRESSION(269235@main?):[ Monterey+ ] http/tests/security/xss-DENIED-script-inject-into-inactive-window2-pson.html is flaky recently
WebKit/WebKit pull request #20092
Opened 2023-11-07 08:56 UTC by sideshowbarker

#### d5d550594a72b07d3236bf56deeae8538f6df9fc
<pre>
REGRESSION(269235@main?):[ Monterey+ ] http/tests/security/xss-DENIED-script-inject-into-inactive-window2-pson.html is flaky recently
<a href="https://bugs.webkit.org/show_bug.cgi?id=263879">https://bugs.webkit.org/show_bug.cgi?id=263879</a>

Reviewed by NOBODY (OOPS!).

This change updates the
http/tests/security/xss-DENIED-script-inject-into-inactive-window2-pson.html
test to ensure it consistently passes.

* LayoutTests/http/tests/security/xss-DENIED-script-inject-into-inactive-window2-pson.html:
</pre>

2023-11-07 08:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5d550594a72b07d3236bf56deeae8538f6df9fc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20092

2023-11-07 16:13 UTC, cdumez requested changes
It looks like it essentially disables the test?

It doesn't seem to wait for the load to have completed anymore before injecting the script.

2023-11-07 17:57 UTC, sideshowbarker commented
> It looks like it essentially disables the test?
> 
> It doesn't seem to wait for the load to have completed anymore before injecting the script.

It’s not clear to me how to make it wait for the load to be completed. And specifically, it’s not clear to me that checking `window.opener.document.location.href` is the right way to check that the load is completed.

Is there some other way to detect when the load has completed?

As far as what the current `window.opener.document.location.href` check is doing: `http://127.0.0.1:8000/security/xss-DENIED-script-inject-into-inactive-window2-pson.html` is the URL of the document that initiated the test — what becomes the `window.opener` document — so it seems like the `openerDocument.location.href == "http://127.0.0.1:8000/security/xss-DENIED-script-inject-into-inactive-window2-pson.html"` maybe well _always_ evaluate to true.

Or if it’s not initially true, then I wonder what else it would ever be. Maybe null? If it starts out as null, then maybe the check should instead be `if (openerDocument.location.href !== null)` or just `if (openerDocument.location.href)`.

And that makes me wonder if it would be sufficient just to check that `window.opener` is non-null — or maybe `window.opener && window.opener.location`.

I had naïvely imagined that it might be possible to check that the opener location is `http://localhost:8000/security/resources/innocent-victim.html`. But when stepping through the test as it runs and looking at the location value, as far as I can see, it never becomes `http://localhost:8000/security/resources/innocent-victim.html`.

So if that location value never becomes `http://localhost:8000/security/resources/innocent-victim.html`, how can we know that the window is ever being navigated to that document in order for it to be loaded?

When I run the test manually, what I observe when looking at the URLs in the address bar is that the original `http://127.0.0.1:8000/security/xss-DENIED-script-inject-into-inactive-window2-pson.html` does actually end up getting navigated to `http://localhost:8000/security/resources/innocent-victim.html` — after it first pops up another window/tab to `http://localhost:8000/security/xss-DENIED-script-inject-into-inactive-window2-pson.html`.

But I don’t know how to programmatically detect the URL change to `http://localhost:8000/security/resources/innocent-victim.html`. Nor is it clear to me that even if I could programmatically detect the URL change, whether that would be sufficient for ensuring that the expected load has actually occurred…

2023-11-13 19:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bcd9510add86d09033d7ab56c69758c5f688ad04. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20092

2023-11-13 21:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4a5e6206dd2a86cfc90298d15a11a558e6ee66e7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20092

2023-11-13 21:14 UTC, cdumez approved these changes
LGTM if the bots are happy.

2023-11-13 21:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/91ca8f47780108a9bebadff3ecf98bd3702224df. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20092

2023-11-15 01:21 UTC, merged

2023-11-15 01:21 UTC, webkit-commit-queue commented
Committed 270737@main (c586c6d289d7): <https://commits.webkit.org/270737@main>

Reviewed commits have been landed. Closing PR #20092 and removing active labels.