Generate serialization for NSLocale
WebKit/WebKit pull request #20549
Opened 2023-11-15 18:35 UTC by sheeparegreat

#### 301d1b71e4a96281a7c591e1f9c694fdbfdb459c
<pre>
Generate serialization for NSLocale
<a href="https://bugs.webkit.org/show_bug.cgi?id=264886">https://bugs.webkit.org/show_bug.cgi?id=264886</a>
<a href="https://rdar.apple.com/118464614">rdar://118464614</a>

Reviewed by NOBODY (OOPS!).

* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/Shared/Cocoa/ArgumentCodersCocoa.h:
* Source/WebKit/Shared/Cocoa/ArgumentCodersCocoa.mm:
(IPC::typeFromObject):
* Source/WebKit/Shared/Cocoa/CoreIPCLocale.h: Added.
(WebKit::CoreIPCLocale::isValidIdentifier):
(WebKit::CoreIPCLocale::CoreIPCLocale):
(WebKit::CoreIPCLocale::toID const):
(WebKit::CoreIPCLocale::identfier const):
(WebKit::CoreIPCLocale::replacement):
* Source/WebKit/Shared/Cocoa/CoreIPCLocale.serialization.in: Added.
* Source/WebKit/Shared/Cocoa/CoreIPCNSCFObject.h:
* Source/WebKit/Shared/Cocoa/CoreIPCNSCFObject.mm:
(WebKit::valueFromID):
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Tools/TestWebKitAPI/Tests/IPC/IPCSerialization.mm:
(TEST):
</pre>

2023-11-15 18:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/301d1b71e4a96281a7c591e1f9c694fdbfdb459c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20549

2023-11-17 23:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b3ea37bb8665672dc9545d4fc740eeb556660da5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20549

2023-11-27 04:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/83838330f2dd39f3af518a8c9f91b482d89bf33e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20549

2023-11-27 21:57 UTC, achristensen07 requested changes

2023-11-27 21:57 UTC, achristensen07 commented on Source/WebKit/Shared/Cocoa/CoreIPCLocale.h
> +        if ([[NSLocale availableLocaleIdentifiers] containsObject:identifier])
I think all objc code should go into the .mm file.

2023-11-27 21:57 UTC, achristensen07 commented on Source/WebKit/Shared/Cocoa/CoreIPCLocale.h
> +    static std::optional<String> replacement(String identifier);
This needs a better name that indicates what it does.  It should probably also take a const String&

2023-11-27 21:57 UTC, achristensen07 commented on Source/WebKit/Shared/Cocoa/CoreIPCLocale.mm
> +        { "ber-Latn_MA"_s, "ber_Latn_MA"_s },
It is almost certainly a bad idea to hard code such a large list of identifiers here.  Can we derive this from a framework somewhere, or replace "replacement" with a framework call?

If there is a finite, known, and never updated set of locales, it should be an enum value.

2023-11-29 04:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6e6121a54989550283e61dbd078f95762c771861. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20549

2023-11-29 04:37 UTC, sheeparegreat commented
Updated PR with changes and added more context in the comment about the lookup list.

2023-11-29 17:59 UTC, beidson approved these changes

2023-11-29 23:25 UTC, webkit-commit-queue commented
Committed 271308@main (ef1d1f5915d3): <https://commits.webkit.org/271308@main>

Reviewed commits have been landed. Closing PR #20549 and removing active labels.

2023-11-29 23:25 UTC, merged