[GStreamer] Fix applying video decoder limit in unified build
WebKit/WebKit pull request #20541
Opened 2023-11-15 16:36 UTC by blino

#### 659b0bd9a853f843349ab6cadb0f349fc03d2042
<pre>
[GStreamer] Fix applying video decoder limit in unified build
<a href="https://bugs.webkit.org/show_bug.cgi?id=264878">https://bugs.webkit.org/show_bug.cgi?id=264878</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/platform/SourcesGStreamer.txt:
If GStreamerRegistryScanner.cpp is built in unified files, the
COMPILE_DEFINITIONS are not applied, so VIDEO_DECODING_LIMIT is
ineffective.
</pre>

2023-11-15 16:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/659b0bd9a853f843349ab6cadb0f349fc03d2042. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20541

2023-11-15 19:42 UTC, mcatanzaro requested changes
If this was hard to fix any other way, I would approve this, but I'm going to suggest the definition should be set globally instead. That's easy enough to do. Restricting the definition to just one source file is just not a good enough reason to remove a file from the unified build.

2023-11-16 08:51 UTC, blino commented
> If this was hard to fix any other way, I would approve this, but I'm going to suggest the definition should be set globally instead. That's easy enough to do. Restricting the definition to just one source file is just not a good enough reason to remove a file from the unified build.

I can do this, but there are already plenty of `@no-unify` files in `Source/WebCore/platform/SourcesGStreamer.txt`, including `platform/audio/gstreamer/WebKitWebAudioSourceGStreamer.cpp` for the `GLIB_DISABLE_DEPRECATION_WARNINGS=1` definition.

2023-11-16 09:07 UTC, calvaris requested changes
Well, I agree with Michael here. 

> I can do this, but there are already plenty of `@no-unify` files in `Source/WebCore/platform/SourcesGStreamer.txt`, including `platform/audio/gstreamer/WebKitWebAudioSourceGStreamer.cpp` for the `GLIB_DISABLE_DEPRECATION_WARNINGS=1` definition.

Regarding this. It is different. One is to hide a build error, which is a footgun and the other one is enabling deprecated APIs.

2023-11-16 10:27 UTC, philn commented
> > If this was hard to fix any other way, I would approve this, but I'm going to suggest the definition should be set globally instead. That's easy enough to do. Restricting the definition to just one source file is just not a good enough reason to remove a file from the unified build.
> 
> I can do this, but there are already plenty of `@no-unify` files in `Source/WebCore/platform/SourcesGStreamer.txt`, including `platform/audio/gstreamer/WebKitWebAudioSourceGStreamer.cpp` for the `GLIB_DISABLE_DEPRECATION_WARNINGS=1` definition.

We can't unify builds of GObject sub-classes, that's why those are marked `@no-unify`.

2023-11-16 11:59 UTC, blino commented
Should I use `list(APPEND WebCore_PRIVATE_DEFINITIONS  ...)` or `add_definitions(...)` then?

2023-11-16 14:14 UTC, mcatanzaro commented
> Should I use list(APPEND WebCore_PRIVATE_DEFINITIONS  ...) 

This way is preferred.

(BTW the preferred way to suppress deprecated declaration warnings is to use `ALLOW_DEPRECATED_DECLARATIONS_BEGIN/END`. Removing a file from unified build is acceptable only when there's really no other good way to suppress the warning. And yes, files that implement GObjects cannot be unified, although I don't remember why.)

2023-11-16 14:31 UTC, philn commented
iirc it's because of the `parent_class` static variable.

2023-11-16 15:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/88411a512b881779e9d6e9e41c92c630400f6623. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20541

2023-11-16 17:23 UTC, mcatanzaro approved these changes

2023-11-16 20:31 UTC, webkit-commit-queue commented
Committed 270842@main (85e79c913425): <https://commits.webkit.org/270842@main>

Reviewed commits have been landed. Closing PR #20541 and removing active labels.

2023-11-16 20:31 UTC, merged