Use dynamicDowncast<T> more in RenderTheme
WebKit/WebKit pull request #20862
Opened 2023-11-24 09:21 UTC by annevk

#### 767a69e82222ff2ea56464771d500ea49a71610c
<pre>
Use dynamicDowncast&lt;T&gt; more in RenderTheme
<a href="https://bugs.webkit.org/show_bug.cgi?id=265299">https://bugs.webkit.org/show_bug.cgi?id=265299</a>

Reviewed by NOBODY (OOPS!).

A few instances of downcast&lt;T&gt; remain due to asserts or not being
preceded by an equivalent is&lt;T&gt; check.

Also use RefPtr where possible and use clearer variable names for
impacted methods.

* Source/WebCore/rendering/RenderTheme.cpp:
(WebCore::RenderTheme::autoAppearanceForElement const):
(WebCore::RenderTheme::extractControlStyleForRenderer const):
(WebCore::RenderTheme::isChecked const):
(WebCore::RenderTheme::isIndeterminate const):
(WebCore::RenderTheme::isEnabled const):
(WebCore::RenderTheme::isFocused const):
(WebCore::RenderTheme::isPresenting const):
(WebCore::RenderTheme::hasListButton const):
(WebCore::RenderTheme::hasListButtonPressed const):
(WebCore::RenderTheme::paintSliderTicks):
* Source/WebCore/rendering/RenderThemeIOS.mm:
(WebCore::RenderThemeIOS::adjustTextFieldStyle const):
(WebCore::RenderThemeIOS::paintTextFieldDecorations):
(WebCore::RenderThemeIOS::adjustMenuListButtonStyle const):
(WebCore::RenderThemeIOS::paintSliderTrack):
(WebCore::RenderThemeIOS::paintProgressBar):
(WebCore::RenderThemeIOS::isSubmitStyleButton const):
(WebCore::RenderThemeIOS::paintAttachment):
(WebCore::RenderThemeIOS::paintMeter):
(WebCore::RenderThemeIOS::paintSliderTicks):
* Source/WebCore/rendering/RenderThemeMac.mm:
(WebCore::RenderThemeMac::paintAttachment):
</pre>

2023-11-24 09:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/767a69e82222ff2ea56464771d500ea49a71610c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20862

2023-11-27 15:30 UTC, cdumez requested changes

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    if (RefPtr input = dynamicDowncast<HTMLInputElement>(*elementPtr)) {
`*elementPtr` -> `element`

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    if (RefPtr select = dynamicDowncast<HTMLSelectElement>(*elementPtr)) {
`*elementPtr` -> `element`

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +        if (RefPtr button = dynamicDowncast<SearchFieldResultsButtonElement>(*elementPtr)) {
`*elementPtr` -> `element`

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    if (RefPtr input = dynamicDowncast<HTMLInputElement>(renderer.node()))
This is a little more concise:
```
RefPtr input = dynamicDowncast<HTMLInputElement>(renderer.node());
return input && input->isPresentingAttachedView();
```

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    if (RefPtr input = dynamicDowncast<HTMLInputElement>(*(renderer.generatingNode())))
Can be written on 2 lines like above.

also, you introduced a bug here. The previous code used to null check `renderer.generatingNode()`, now it no longer does.

I would use:
```
RefPtr input = dynamicDowncast<HTMLInputElement>(renderer.generatingNode());
return input && input->list();
```

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    RefPtr input = dynamicDowncast<HTMLInputElement>(*(renderer.generatingNode()));
Same bug as above, you are now assuming `renderer.generatingNode()` is non-null, which likely isn't OK or `renderer.generatingNode()` would return a C++ reference, not a raw pointer.

Should be:
```
RefPtr input = dynamicDowncast<HTMLInputElement>(renderer.generatingNode());
return input && buttonElement->active();
```

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderTheme.cpp
> +    if (RefPtr buttonElement = input->dataListButtonElement())
This is not strictly needed as we're calling a trivial getter on buttonElement.

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderThemeIOS.mm
> +    auto* renderSlider = dynamicDowncast<RenderSlider>(&box);
`&box` -> `box` or you're doing an unnecessary null check.

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderThemeIOS.mm
> +    auto* renderProgress = dynamicDowncast<RenderProgress>(&renderer);
`&renderer` -> `renderer`

2023-11-27 15:30 UTC, cdumez commented on Source/WebCore/rendering/RenderThemeIOS.mm
> +    auto* renderMeter = dynamicDowncast<RenderMeter>(&renderer);
`&renderer` -> `renderer`

2023-11-27 16:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7ec7ab186168bb7b90ae2f80d27766643ec31e30. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20862

2023-11-27 16:10 UTC, cdumez approved these changes
LGTM with fix.

2023-11-27 16:10 UTC, cdumez commented on Source/WebCore/rendering/RenderThemeIOS.mm
> +        return true;
This used to return false and now it returns true?

2023-11-27 16:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad5bac8581c0d97fdb0e517afbe455b9dd28848a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20862

2023-11-27 17:16 UTC, annevk commented
@darinadler maybe you could review the changes to Ref/RefPtr Chris handed to me? (If you don't end up having time that's okay. I'll merge this tomorrow provided it's all green. But this seems like the kind of thing you might want to have input on, even post landing.)

2023-11-27 17:19 UTC, cdumez commented
Note that constness matching was already done in downcast / dynamicDowncast when using raw pointers:
```
// Safe downcasting functions.
template<typename Target, typename Source>
inline match_constness_t<Source, Target>& downcast(Source& source)
{
    static_assert(!std::is_same_v<Source, Target>, "Unnecessary cast to same type");
    static_assert(std::is_base_of_v<Source, Target>, "Should be a downcast");
    ASSERT_WITH_SECURITY_IMPLICATION(is<Target>(source));
    return static_cast<match_constness_t<Source, Target>&>(source);
}
template<typename Target, typename Source>
inline match_constness_t<Source, Target>* downcast(Source* source)
{
    static_assert(!std::is_same_v<Source, Target>, "Unnecessary cast to same type");
    static_assert(std::is_base_of_v<Source, Target>, "Should be a downcast");
    ASSERT_WITH_SECURITY_IMPLICATION(!source || is<Target>(*source));
    return static_cast<match_constness_t<Source, Target>*>(source);
}

template<typename Target, typename Source>
inline match_constness_t<Source, Target>* dynamicDowncast(Source& source)
{
    static_assert(!std::is_same_v<Source, Target>, "Unnecessary cast to same type");
    static_assert(std::is_base_of_v<Source, Target>, "Should be a downcast");
    return is<Target>(source) ? &static_cast<match_constness_t<Source, Target>&>(source) : nullptr;
}
template<typename Target, typename Source>
inline match_constness_t<Source, Target>* dynamicDowncast(Source* source)
{
    static_assert(!std::is_same_v<Source, Target>, "Unnecessary cast to same type");
    static_assert(std::is_base_of_v<Source, Target>, "Should be a downcast");
    return is<Target>(source) ? static_cast<match_constness_t<Source, Target>*>(source) : nullptr;
}
```

However, the overloads taking smart pointers were failing to do so, making them more annoying to use.

2023-11-27 17:36 UTC, darinadler approved these changes
Yes, those `Ref.h` and `RefPtr.h` changes seem right.

2023-11-27 21:52 UTC, webkit-commit-queue commented
Committed 271170@main (b6d576d54824): <https://commits.webkit.org/271170@main>

Reviewed commits have been landed. Closing PR #20862 and removing active labels.

2023-11-27 21:52 UTC, merged