Dispatch NavigateEvent on same-document navigations and implement navigation.currentEntry
WebKit/WebKit pull request #20952
Opened 2023-11-27 21:18 UTC by TingPing

#### 9324a79e22056ad0eb0bc5b09b5cc873db8a55fa
<pre>
Dispatch NavigateEvent on same-document navigations and implement navigation.currentEntry
<a href="https://bugs.webkit.org/show_bug.cgi?id=265401">https://bugs.webkit.org/show_bug.cgi?id=265401</a>

Reviewed by NOBODY (OOPS!).

When NavigationAPI is enabled this will track same-document navigations, setting currentEntry,
and dispatch NavigateEvent with the proper NavigationDestination.

* LayoutTests/TestExpectations:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/commit-behavior/after-transition-push-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/commit-behavior/after-transition-reload-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/commit-behavior/after-transition-replace-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/commit-behavior/after-transition-traverse-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/anchor-click-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/constructor-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/history-back-same-doc-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/history-pushState-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/history-replaceState-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/location-api-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/navigation-back-forward-same-doc-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/navigation-navigate-replace-intercept-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/navigation-navigate-replace-same-doc-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/currententrychange-event/navigation-navigate-same-doc-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/click-samedocument-crossorigin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/click-samedocument-crossorigin-sameorigindomain.sub-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/location-samedocument-crossorigin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/location-samedocument-crossorigin-sameorigindomain.sub-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/open-samedocument-crossorigin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/open-samedocument-crossorigin-sameorigindomain.sub-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/submit-samedocument-crossorigin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/cross-window/submit-samedocument-crossorigin-sameorigindomain.sub-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-after-dispatch-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-and-navigate-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-canceled-event-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-handler-null-or-undefined-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-navigation-back-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-same-document-history-back-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-anchor-fragment-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-anchor-userInitiated-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-destination-after-detach-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-destination-dynamic-index-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-destination-getState-back-forward-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-history-back-after-fragment-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-history-back-after-pushState-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-history-back-cross-document-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-history-back-noop-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-iframe-location-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-location-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-navigation-back-cross-document-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-navigation-back-same-document-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-navigation-back-same-document-in-iframe-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-svg-anchor-fragment-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-window-open-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigate-window-open-self-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-back-same-document-preventDefault-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-in-iframe-same-document-preventDefault-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-navigates-top-and-same-doc-child-and-cross-doc-child-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-same-document-preventDefault-multiple-windows-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-top-cancels-cross-document-child-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/same-url-replace-cross-document-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/same-url-replace-same-document-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-activation/activation-push-cross-origin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-activation/activation-replace-cross-origin-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-activation/activation-replace-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-history-entry/after-detach-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-history-entry/current-basic-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-history-entry/entries-across-origins-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigation-history-entry/entries-after-javascript-url-navigation-expected.txt:
* LayoutTests/ [...]

2023-11-27 21:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9324a79e22056ad0eb0bc5b09b5cc873db8a55fa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-27 21:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c3f1594293cde6d71ba250091e9d8a8b76eec2de. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-27 21:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8f692c72ffc72eeb229af53058037048cc0bdbb1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-28 02:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/85929bf1ab2244285feab7b547165cacdf8b1610. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-28 15:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7f17381aa5b7998b76143a7dadbe9c73f652b8c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-28 15:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7f17381aa5b7998b76143a7dadbe9c73f652b8c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-28 17:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e13737c3e856d8bbf1f6aadae5ccd6167c7c48c1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-11-30 19:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/66a8fa48b243def98547f1c245cbbacc6fbb7d49. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-12-01 17:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4d88174745e4b6113e5af717007f7c08b0745041. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-12-06 20:46 UTC, cdumez commented
wk1 failures look real?

2023-12-07 17:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5283b095aa0e29c91e809a744385cbc08f18255a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2023-12-08 16:35 UTC, TingPing commented
@cdumez All green now.

2024-01-08 19:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/93ea61045f18cd418f0fbc6f722222ccffb14ab1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-08 23:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d4d67f065d307d56ccd1e12fc81bab6e78770abc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-09 15:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a092c6c8122733491a06e6ac642d40f183a31d72. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-09 19:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/785baff38335ade720dc8c87e21143780dffda16. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-09 19:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/785baff38335ade720dc8c87e21143780dffda16. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-10 02:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d22bd2681363c48e4aa1dd182636af15ba43908f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-10 02:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d22bd2681363c48e4aa1dd182636af15ba43908f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/20952

2024-01-17 11:26 UTC, rwlbuis commented on Source/WebCore/loader/NavigationController.h
> +};
I am not sure why we need this class? Can't we base entries on HistoryItems?

2024-01-17 11:27 UTC, rwlbuis commented on Source/WebCore/loader/NavigationController.h
> +    RefPtr<NavigationEntry> m_currentEntry;
Have you considered avoiding this member variable and just keep entries on the Navigation object?

2024-01-17 11:27 UTC, rwlbuis commented on Source/WebCore/page/NavigationHistoryEntry.cpp
> +    , m_sameDocument(isSameDocument)
I think we should have consistent naming here, so either sameDocument or isSameDocument everywhere.

2024-01-17 11:58 UTC, rwlbuis commented on Source/WebCore/page/NavigationHistoryEntry.h
> +    int64_t index() const { return m_index; };
I think this can maybe better ask the Navigation object for the index, since otherwise it may get get decoupled (this is what chromium does).

2024-01-17 14:17 UTC, TingPing commented on Source/WebCore/loader/NavigationController.h
> +};
I guess we could, I don't understand the benefit there. `HistoryItem` is a fairly big class full of unrelated properties and I think we may have to add Navigation specific properties to it then.

2024-01-17 14:52 UTC, rwlbuis commented on Source/WebCore/loader/NavigationController.h
> +};
Well, HistoryItem is already created so I think we may be able to use that. I am only recently looking at the spec/implementation, but I think concentrating things on the entries in Navigation object itself may be worth it, at least that is my first approach here:
https://github.com/WebKit/WebKit/pull/22865

2024-01-17 19:29 UTC, achristensen07 requested changes

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/page/Navigation.cpp
> +    if (!window()->frame())
May as well null check window() as well.

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/page/NavigationDestination.h
> +    int64_t m_index { -1 };
It feels like we should use std::optional<size_t> instead of int64_t

2024-01-17 19:29 UTC, achristensen07 commented on Source/WTF/wtf/text/WTFString.h
> +inline bool operator<(const String& lhs, const String& rhs)
This seems a little too general.  Instead, could we use a comparator in the definition of the type of m_navigations

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/FrameLoader.h
> +    const std::unique_ptr<NavigationController> m_navigation;
Since this is guaranteed to never be null, why not use UniqueRef?

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.cpp
> +    URL newURL { entry->url() };
If we are assuming the entry is never null here, the parameter type should be a Ref

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.cpp
> +RefPtr<NavigationEntry> NavigationEntry::create(const String& url, const String& key)
This can return a Ref because it can't return null.

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.cpp
> +RefPtr<NavigationEntry> FrameLoader::NavigationController::addEntry(const String& url)
Ref

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.cpp
> +std::tuple<const RefPtr<NavigationEntry>, int64_t> FrameLoader::NavigationController::currentEntry() const
Since we can never have one without the other and there are only 2, could this be a std::optional<std::pair<Ref<NavigationEntry>, size_t>> instead?

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.cpp
> +NavigationEntry::NavigationEntry(const String& url, const String& key)
In the header it says the first parameter is "id" but here it is "url".  That needs correcting.

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.h
> +    String m_id;
Can this be a UUID instead of a String?
Also, can all these be const?

2024-01-17 19:29 UTC, achristensen07 commented on Source/WebCore/loader/NavigationController.h
> +    LocalFrame& m_frame;
Let's make this a WeakRef instead to prevent storing raw pointers.

2024-03-08 19:42 UTC, closed without merging