Deploy more smart pointers in WebInspectorInterruptDispatcher.cpp
WebKit/WebKit pull request #21228
Opened 2023-12-03 04:00 UTC by abigailfox

#### b87469816d725c56f23afd20fd58eb2d4c7aea61
<pre>
Deploy more smart pointers in WebInspectorInterruptDispatcher.cpp
<a href="https://bugs.webkit.org/show_bug.cgi?id=265741">https://bugs.webkit.org/show_bug.cgi?id=265741</a>
<a href="https://rdar.apple.com/119084025">rdar://119084025</a>

Reviewed by NOBODY (OOPS!).

* Source/WebKit/WebProcess/Inspector/WebInspectorInterruptDispatcher.cpp:
(WebKit::WebInspectorInterruptDispatcher::notifyNeedDebuggerBreak):
</pre>

2023-12-03 04:10 UTC, cdumez requested changes
LGTM but maybe you could do slightly bigger patches? Like whole files at once instead of a patch per function?

2023-12-04 00:47 UTC, abigailfox commented
I'm doing it one per file, some of these files only had one result on the static analyzer though

2023-12-04 01:34 UTC, cdumez approved these changes

2023-12-04 01:41 UTC, webkit-commit-queue commented
Committed 271452@main (b56c49e49d12): <https://commits.webkit.org/271452@main>

Reviewed commits have been landed. Closing PR #21228 and removing active labels.

2023-12-04 01:41 UTC, merged