[Merge-Queue] Add ValidateCommitterAndReviewer
WebKit/WebKit pull request #214
Opened 2022-03-21 20:11 UTC by JonWBedard

#### 0ad57da25b97257eb70fd7a8d47b7c53555389bd
<pre>
[Merge-Queue] Add ValidateCommitterAndReviewer
<a href="https://bugs.webkit.org/show_bug.cgi?id=238150">https://bugs.webkit.org/show_bug.cgi?id=238150</a>
&lt;rdar://problem/90587620 &gt;

Reviewed by Aakash Jain.

* Tools/CISupport/ews-build/factories.py:
(CommitQueueFactory.__init__): Rename ValidateCommiterAndReviewer to ValidateCommiterAndReviewer.
(MergeQueueFactory.__init__): Add ValidateCommitterAndReviewer, PrintConfiguration, CleanGitRepo,
CheckOutSource, FetchBranches, ShowIdentifier, VerifyGitHubIntegrity, UpdateWorkingDirectory
and CheckOutPullRequest.
* Tools/CISupport/ews-build/factories_unittest.py:
(TestExpectedBuildSteps): Add Merge-Queue step names.
* Tools/CISupport/ews-build/steps.py:
(GitHubMixin.get_pr_json): Retry tied to attempt not index.
(GitHubMixin.get_reviewers): Get list of reviewers for pull-request in repository.
(ValidateCommitterAndReviewer): Renamed from ValidateCommiterAndReviewer, inherit from GitHubMixin.
(ValidateCommitterAndReviewer.__init__): Rename ValidateCommiterAndReviewer.
(ValidateCommitterAndReviewer.fail_build): Block pull request, differentiate comment for pull
request and patch.
(ValidateCommitterAndReviewer.start): Support pull requests.
(ValidateCommiterAndReviewer): Renamed to ValidateCommitterAndReviewer.
* Tools/CISupport/ews-build/steps_unittest.py:

Canonical link: <a href="https://commits.webkit.org/248712@main">https://commits.webkit.org/248712@main</a>
git-svn-id: <a href="https://svn.webkit.org/repository/webkit/trunk@291619">https://svn.webkit.org/repository/webkit/trunk@291619</a> 268f45cc-cd09-0410-ab3c-d52691b4dbfc
</pre>

2022-03-21 20:21 UTC, JonWBedard commented
Some examples:
https://ews-build.webkit-uat.org/#/builders/85/builds/59
https://ews-build.webkit-uat.org/#/builders/85/builds/58
https://ews-build.webkit-uat.org/#/builders/85/builds/55

2022-03-22 14:07 UTC, jain-aakash requested changes

2022-03-22 14:07 UTC, aj062 commented on Tools/CISupport/ews-build/steps.py
> +        reviews_url = '{}/pulls/{}/reviews'.format(api_url, pr_number)
Let's use python 3 f-string here to improve readability.

2022-03-22 14:07 UTC, aj062 commented on Tools/CISupport/ews-build/steps.py
> +            comment += '\n\nRejecting attachment {} from commit queue.'.format(patch_id)
Let's use python 3 f-string here to improve readability.

2022-03-22 14:07 UTC, aj062 commented on Tools/CISupport/ews-build/steps.py
> +            '@' if pr_number else '', email, status, Contributors.url,
@email seems misleading here, while it would be username for pr workflow. can rename to something like: email_or_username or username

2022-03-22 14:07 UTC, aj062 commented on Tools/CISupport/ews-build/steps.py
> +            comment += '\n\nRejecting {} from merge queue.'.format(self.getProperty('github.head.sha', '#{}'.format(pr_number)))
'#{}'.format(pr_number) => f'PR #{pr_number}'

2022-03-22 14:07 UTC, aj062 commented on Tools/CISupport/ews-build/steps.py
> +        else:
In general, instead of having this else case scattered throughout so many build-steps. It might be a good idea to check this early-on (e.g.: in ValidateChange step), and set a boolean property, e.g.: is_pr_workflow. Then all these build-steps can simply do:
```
if self.getProperty('is_pr_workflow'):
   ...
else:
  ...
```

2022-03-22 14:08 UTC, aj062 approved these changes
r+ with comments.

2022-03-22 15:26 UTC, merged

2022-03-22 15:26 UTC, JonWBedard commented
Landed https://commits.webkit.org/248712@main (0ad57da25b97)!