[NetworkProcess] Unhandled network process message 'NetworkStorageManager_DisconnectFromStorageArea'
WebKit/WebKit pull request #21437
Opened 2023-12-07 14:11 UTC by csaavedra

https://bugs.webkit.org/show_bug.cgi?id=265994

Reviewed by NOBODY (OOPS!).

There was no handling of NetworkStorageManager messages in the network process connection to the web process, add it where it should be.

* Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.cpp: (WebKit::NetworkConnectionToWebProcess::didReceiveMessage):
* Source/WebKit/NetworkProcess/storage/NetworkStorageManager.h:

2023-12-07 14:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4f9d45279a33dc77f34988633fec97b9e2887dbd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21437

2023-12-07 14:14 UTC, csaavedra commented
I'm having a hard time believing that something like this would go unnoticed, but as I commented in bugzilla, I detected this while running API tests in debug mode:

```
Unhandled network process message 'NetworkStorageManager_DisconnectFromStorageArea'
SHOULD NEVER BE REACHED
/app/webkit/Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.cpp(340) : virtual void WebKit::NetworkConnectionToWebProcess::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
Mesa: The provided filesystem timestamp for the cache is bogus! Disabling On-disk cache.
1   0x7f8128f6aadd WTFCrash
2   0x7f81332f75bd WTF::isIntegralOrPointerType()
3   0x7f8133c9143e WebKit::NetworkConnectionToWebProcess::didReceiveMessage(IPC::Connection&, IPC::Decoder&)
4   0x7f813417c925 IPC::Connection::dispatchMessage(IPC::Decoder&)
5   0x7f813417cb70 IPC::Connection::dispatchMessage(std::unique_ptr<IPC::Decoder, std::default_delete<IPC::Decoder> >)
6   0x7f813417cf2e IPC::Connection::dispatchOneIncomingMessage()
7   0x7f813417c568 operator()
8   0x7f8134183ce2 call
9   0x7f812795c98d WTF::Function<void ()>::operator()() const
10  0x7f8129006f07 WTF::RunLoop::performWork()
11  0x7f81290c0474 operator()
12  0x7f81290c0498 _FUN
13  0x7f81290c0407 operator()
14  0x7f81290c0455 _FUN
15  0x7f8124917d36 g_main_context_dispatch
16  0x7f81249752b8 g_main_context_iterate.isra.0
17  0x7f81249173ff g_main_loop_run
18  0x7f81290c0ac8 WTF::RunLoop::run()
19  0x7f813401bdad WebKit::AuxiliaryProcessMainBase<WebKit::NetworkProcess, false>::run(int, char**)
20  0x7f8134018ef6 int WebKit::AuxiliaryProcessMain<WebKit::NetworkProcessMainSoup>(int, char**)
21  0x7f813400a8af WebKit::NetworkProcessMain(int, char**)
22  0x562df2678959 main
23  0x7f8121b5208a __libc_start_call_main
24  0x7f8121b5214b __libc_start_main
25  0x562df2678875 _start
```

2023-12-07 14:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e5f30a92af795b83f8a67bc83a73a2f2ea7122c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21437

2023-12-12 11:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3c0e063f18134ef8643af6606b9d828916a7bf25. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21437

2023-12-12 11:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3c0e063f18134ef8643af6606b9d828916a7bf25. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21437

2023-12-12 17:56 UTC, szewai requested changes
This fix is not right, because NetworkStorageManager is a WorkQueueMessageReceiver and it is added to connection by `addWorkQueueMessageReceiver`.
The issue is likely caused by `addWorkQueueMessageReceiver ` called after receiving message, or `removeWorkQueueMessageReceiver` called before receiving message, so connection does not know how to handle the message.

2023-12-13 16:55 UTC, csaavedra commented
> This fix is not right, because NetworkStorageManager is a WorkQueueMessageReceiver and it is added to connection by `addWorkQueueMessageReceiver`. The issue is likely caused by `addWorkQueueMessageReceiver ` called after receiving message, or `removeWorkQueueMessageReceiver` called before receiving message, so connection does not know how to handle the message.

From the message being received I would say this is happening after message receiver is removed. Would you say this might be specific to the finalization process of the network process in linux ports? cc @TingPing

2024-04-23 19:39 UTC, mcatanzaro commented
https://bugs.webkit.org/show_bug.cgi?id=252489 looks similar

2025-01-20 09:42 UTC, closed without merging