[MSE] Build without ManagedMSE support is broken
WebKit/WebKit pull request #21589
Opened 2023-12-10 10:58 UTC by philn

#### 91fd2154874587bc4f12d639fbf10103f016c57a
<pre>
[MSE] Build without ManagedMSE support is broken
<a href="https://bugs.webkit.org/show_bug.cgi?id=266174">https://bugs.webkit.org/show_bug.cgi?id=266174</a>

Reviewed by NOBODY (OOPS!).

The ManagedMediaSourceEnabled preference cannot be exposed only for MANAGED_MEDIA_SOURCE due to its
usage in *Track+MediaSource.idl files. So its conditional is now MEDIA_SOURCE and the default value
takes into account the ENABLE(MANAGED_MEDIA_SOURCE) ifdef.

* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WebCore/Modules/mediasource/SourceBuffer.cpp:
(WebCore::SourceBuffer::appendBufferInternal):
* Source/WebKit/Shared/WebPreferencesDefaultValues.cpp:
(WebKit::defaultManagedMediaSourceEnabled):
* Source/WebKit/Shared/WebPreferencesDefaultValues.h:
</pre>

2023-12-10 10:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/91fd2154874587bc4f12d639fbf10103f016c57a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21589

2023-12-11 09:21 UTC, calvaris approved these changes
lgtm but maybe you want to wait for @jyavenard 's blessing.

2023-12-11 09:40 UTC, jyavenard requested changes

2023-12-11 09:40 UTC, jyavenard commented on Source/WebCore/Modules/mediasource/SourceBuffer.cpp
> +#if ENABLE(MANAGED_MEDIA_SOURCE)
isn't this the only thing preventing compilation if MMS is disabled?
why not limit to this single liner?

2023-12-11 09:40 UTC, jyavenard commented on Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
> +  condition: ENABLE(MEDIA_SOURCE)
I don't see why this is needed

2023-12-11 09:40 UTC, jyavenard commented on Source/WebKit/Shared/WebPreferencesDefaultValues.cpp
> +#if ENABLE(MEDIA_SOURCE)
this seems broken, this method should only be enabled if MMS is compiled in

2023-12-11 09:43 UTC, jyavenard commented
I would remove the entire MANAGED_MEDIA_SOURCE as it will now be part of the official MSE spec. So if we build MEDIA_SOURCE we also build MANAGED_MEDIA_SOURCE

2023-12-11 09:49 UTC, philn commented
I'll rework this then. Thanks for the feedback.

2023-12-11 10:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2774998b5aa477af41beb02206f7224c5c3e8b43. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21589

2023-12-11 10:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2774998b5aa477af41beb02206f7224c5c3e8b43. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21589

2023-12-11 10:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4ffe41acebfd24137ac00acef373a5d4e89edd04. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21589

2023-12-12 21:16 UTC, jyavenard approved these changes

2023-12-13 09:27 UTC, webkit-commit-queue commented
Committed 271975@main (8cac4a32fbd6): <https://commits.webkit.org/271975@main>

Reviewed commits have been landed. Closing PR #21589 and removing active labels.

2023-12-13 09:27 UTC, merged