[WPE] Update Cog version for the WebKit build
WebKit/WebKit pull request #21744
Opened 2023-12-13 17:56 UTC by clopez

#### adf76c33434b61e61dc5176f6fadfd7432d8505b
<pre>
[WPE] Update Cog version for the WebKit build
<a href="https://bugs.webkit.org/show_bug.cgi?id=266351">https://bugs.webkit.org/show_bug.cgi?id=266351</a>

Reviewed by NOBODY (OOPS!).

This updates Cog for the WPE build to the last one
(0~0.19.1-1-g843f874)

This fixes an issue with the DRM plugin for the RPi4
that causes Cog to not output anything on the screen.

Cog now depends on libportal, that is also added to
the Flatpak SDK

* Tools/PlatformWPE.cmake:
* Tools/buildstream/elements/sdk-platform.bst:
* Tools/buildstream/elements/sdk/libportal.bst: Added.
</pre>

2023-12-13 17:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/adf76c33434b61e61dc5176f6fadfd7432d8505b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21744

2023-12-13 18:23 UTC, philn commented
Thanks! Can you split this in 2 PRs please? Otherwise we risk to have broken bots until the SDK update is deployed.

2023-12-13 19:07 UTC, mcatanzaro approved these changes

2023-12-13 19:14 UTC, philn requested changes

2023-12-13 19:14 UTC, philn commented on Tools/PlatformWPE.cmake
> +        set(WPE_COG_TAG "843f874484d09b9e492683a50f4707e584e3fcb6")
This in separate PR please.

2023-12-13 20:01 UTC, clopez commented
Sure, I will leave this PR for updating the Cog version and add a new one for the SDK update.

2023-12-13 20:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad3f05efc858cd038906ffc59641bef58d0243fd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21744

2023-12-13 20:12 UTC, clopez commented
This PR is now only for updating Cog (EWS is expected to fail until the new SDK is deployed).

The PR for updating the SDK is at: https://github.com/WebKit/WebKit/pull/21750

2023-12-13 21:04 UTC, aperezdc commented
You may also pass `-Dlibportal=disabled` to the Meson invocation in the patch that updates the Cog tag/commit, handle adding the library to the SDK, and re-enable the option later. If you are not in a hurry, updating the SDK first as you are currently planning is fine, of course.

2023-12-14 16:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d16315089cb7322ce13255e4db8dec5fdcc28e51. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/21744

2023-12-14 16:45 UTC, philn approved these changes

2023-12-14 17:45 UTC, webkit-commit-queue commented
Committed 272046@main (8b23edce907a): <https://commits.webkit.org/272046@main>

Reviewed commits have been landed. Closing PR #21744 and removing active labels.

2023-12-14 17:45 UTC, merged