Remove -ftree-sra workaround
WebKit/WebKit pull request #22205
Opened 2023-12-22 20:12 UTC by AtariDreams

<pre>
Remove -ftree-sra workaround
https://bugs.webkit.org/show_bug.cgi?id=146440

Reviewed by NOBODY (OOPS!).

Since we are not compiling for i386 anymore, we can remove this workaround.

* Source/WebCore/CMakeLists.txt: Remove -ftree-sra workaround.
</pre>

2023-12-22 20:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fdf7f929e852ab337daecb491c90a63e8e713f90. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22205

2023-12-24 12:53 UTC, Constellation requested changes
> Since we are not compiling for i386 anymore, we can remove this workaround.

No. Apple ports do not support it. But other ports do.

2023-12-24 14:22 UTC, AtariDreams commented
> > Since we are not compiling for i386 anymore, we can remove this workaround.
> 
> No. Apple ports do not support it. But other ports do.

Okay, but given how tests have passed, it means the crashing has stopped. So, this bug has been fixed considering how severe the miscompilation bug was

2023-12-24 14:23 UTC, AtariDreams commented
@Constellation Bug status is RESOLVED FIXED

2023-12-24 14:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/05edb8fc4a5fe24f466e03f1cc0f5b8f967088d7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22205

2023-12-24 21:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa6a11e6a2e8b5035854ddafa4bc797259ca8965. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22205

2023-12-24 21:22 UTC, Ahmad-S792 commented
I added few engineers (responsible for non-Apple ports) from Sony & Red Hat to comment whether it is something can be done in 'review' queue.

2023-12-24 21:31 UTC, fujii commented
https://bugs.webkit.org/show_bug.cgi?id=146440 was closed because the -ftree-sra workaround has landed. Please don't reuse the bug id.

2023-12-25 14:19 UTC, mcatanzaro requested changes
I see there has been no investigation to determine if the original bug has been fixed, so no, we cannot remove this.

My guess is it's _probably_ OK to remove, but that is a low confidence guess, and we should be confident before potentially breaking WebKit for users....

2023-12-25 14:22 UTC, mcatanzaro commented
> Okay, but given how tests have passed, it means the crashing has stopped. So, this bug has been fixed considering how severe the miscompilation bug was

The Linux EWS are all x86_64 bots, and the bug title itself says the bug was specific to 32-bit systems....

2023-12-25 14:22 UTC, closed without merging