Make compareExchangeWeak have relaxed memory order after failure.
WebKit/WebKit pull request #22248
Opened 2023-12-27 05:03 UTC by AtariDreams

<pre>
Make compareExchangeWeak have relaxed memory order after failure.
https://bugs.webkit.org/show_bug.cgi?id=266910

Reviewed by NOBODY (OOPS!).

The value expectedOrActual is not used again, so who cares when it is assigned to? What only matters is the memory order for if the assignment to value succeeds.

* Source/WTF/wtf/Atomics.h:
(WTF::Atomic::compareExchangeWeak): Made failure relaxed.
</pre>

2023-12-27 05:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/377b47b0ad02f5088581f5285c52958c5a4cb104. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 05:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/373e6ac4969cfd976581272288fb32f1daa957f3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 05:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c54fdef3f51415d2cb6826fdd75c1591f3eb56ed. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 05:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/093b0384832bff38ef7f5ebe8eb053f0f8deacce. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 13:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/49eb2c33b1b69daae687489700c965a89a0256b8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 14:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0abcd2760a7aefd75ce0e83d9279e5f646e4a723. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 15:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4cf9cb99a82c14a12dff826a85d584e735443c3f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-27 16:28 UTC, AtariDreams commented
@mwyrzykowski Thoughts on this?

2023-12-27 20:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/962438c60b65e1de5ca0f0076b2bd59348f42e2c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-28 00:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2a4dfea6c941858980f43964675e3d365bf2c52e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2023-12-28 16:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6c7654833e46bfc118de5ae3939eb8449540ec3f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2024-04-04 22:05 UTC, mcatanzaro requested changes
But in the failure case, you still very much care about the load (read) operation, so I think this should use `std::memory_order_acquire`.

2024-04-04 22:28 UTC, mcatanzaro commented
Actually wait, I think you can only use `std::memory_order_acquire` for failure if the caller specifies a memory order that is weaker than `std::memory_order_seq_cst`. When the memory order is `std::memory_order_seq_cst` we have to respect that. Right?

Also, I just found #22049, which indicates you already knew that it was necessary to use `std::memory_order_acquire` in the failure case, right?

2024-08-18 19:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1bc6ebde0b54972c05b851a6d42d7c2c2377d315. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22248

2024-08-18 23:15 UTC, mcatanzaro requested changes
Now your commit is just removing an unused function, but the title does not reflect this.

I think it's OK to leave it there. It's not useful, but it's not hurting anything either, and removing it isn't an improvement.

2024-08-19 12:38 UTC, mcatanzaro commented
> But in the failure case, you still very much care about the load (read) operation, so I think this should use std::memory_order_acquire.

Wait, I think I was just confused when I wrote this? Surely you were correct the first time? When the operation fails, the result is indeed discarded. The whole point of WTF::Atomic is to wrap std::atomic but not change the expected value when the atomic operation fails. Since `expectedOrActual` is discarded, using relaxed memory order on failure seems fine. Right?

> I think it's OK to leave it there. It's not useful, but it's not hurting anything either, and removing it isn't an improvement.

It actually is an improvement, because specifying the memory order to use on failure, then discarding the result, is not useful, so it doesn't make sense to ever use it. What I would do is combine the current version of your pull request and the older version as well: both remove the unused version of this function, and also change the memory order on failure to relaxed.

2024-08-19 13:52 UTC, mcatanzaro commented
> Wait, I think I was just confused when I wrote this? Surely you were correct the first time? When the operation fails, the result is indeed discarded. The whole point of WTF::Atomic is to wrap std::atomic but not change the expected value when the atomic operation fails. Since expectedOrActual is discarded, using relaxed memory order on failure seems fine. Right?

Nope, this is wrong. The surrounding code may expect the memory order that the caller specified. Otherwise, updates to other non-atomic values might not be properly seen by other threads. Surely we need to always be at least as strict as requested by the caller.

We both made a pretty serious mistake here. Bluntly, perhaps neither of us is smart enough to risk touching memory order. :) This is dangerous stuff. I am going to close this pull request because I think there is nothing more to do here. Keeping the unused four-argument `compareExchangeWeak` seems harmless; maybe somebody will need it in the future.

2024-08-19 13:52 UTC, closed without merging