Disable AES-CFB by default.
WebKit/WebKit pull request #22309
Opened 2024-01-02 18:32 UTC by nmahendru

#### 714cb93986b1baa9e5e9def20e79b516e56b98c2
<pre>
Disable AES-CFB by default.
Need the bug URL (OOPS!).
Include a Radar link (OOPS!).

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* LayoutTests/crypto/subtle/aes-cbc-cfb-decrypt-malformed-parameters.html:
* LayoutTests/crypto/subtle/aes-cbc-cfb-encrypt-malformed-parameters.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-export-key-jwk-length-128.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-export-key-jwk-length-192.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-export-key-jwk-length-256.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-export-raw-key.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-key-encrypt-decrypt.html:
* LayoutTests/crypto/subtle/aes-cfb-generate-key.html:
* LayoutTests/crypto/subtle/aes-cfb-import-jwk-key-length-128.html:
* LayoutTests/crypto/subtle/aes-cfb-import-jwk-key-length-192.html:
* LayoutTests/crypto/subtle/aes-cfb-import-jwk-key-length-256.html:
* LayoutTests/crypto/subtle/aes-cfb-import-key-decrypt.html:
* LayoutTests/crypto/subtle/aes-cfb-import-key-encrypt.html:
* LayoutTests/crypto/subtle/aes-cfb-import-key-unwrap-jwk-key.html:
* LayoutTests/crypto/subtle/aes-cfb-import-key-unwrap-raw-key.html:
* LayoutTests/crypto/subtle/aes-cfb-import-key-wrap-jwk-key.html:
* LayoutTests/crypto/subtle/aes-cfb-import-raw-key.html:
* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WebCore/crypto/SubtleCrypto.cpp:
(WebCore::isAESCFBWebCryptoDeprecated):
(WebCore::normalizeCryptoAlgorithmParameters):
(WebCore::isSupportedExportKey):
</pre>

2024-01-02 19:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/da8b5939e3a66f2ac338a1a2e692047f8f8a6017. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22309

2024-01-02 19:29 UTC, pascoej commented
r+ assuming the bots all go green

2024-01-02 19:29 UTC, pascoej approved these changes

2024-01-02 19:29 UTC, pascoej commented on Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
> +  humanReadableDescription: "Enable DepreAES-CFB Web Crypto"
"Enable DepreAES-CFB" typo

2024-01-02 20:26 UTC, Ahmad-S792 commented
@nitinseshadri - the commit mentions 'Pull Request' with link containing 'k' in the end, which is broken. Can you instead of 'Pull Request' refer to '[259018@main](https://commits.webkit.org/259018@main)' (canonical link)? It is not standard but just usually what I have seen in other commits.

2024-01-02 22:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/14817c7df4a30e5307173aa101b44be5d540cbbd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22309

2024-01-02 22:35 UTC, pascoej requested changes
Please squash into one commit before this can land (One commit per final-version of a PR is standard.)

2024-01-03 04:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dabe019d10e0b4b14e3a3b151a6e1d4d737f7029. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22309

2024-01-03 04:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dabe019d10e0b4b14e3a3b151a6e1d4d737f7029. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22309

2024-01-03 05:01 UTC, nmahendru commented
> Please squash into one commit before this can land (One commit per final-version of a PR is standard.)

done.

2024-01-03 05:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a9b27a2e13e812ac10cf05d6fb9a36bc7b4595ff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22309

2024-01-03 17:36 UTC, pascoej approved these changes

2024-01-03 18:16 UTC, webkit-commit-queue commented
Committed 272615@main (572fec1979ec): <https://commits.webkit.org/272615@main>

Reviewed commits have been landed. Closing PR #22309 and removing active labels.

2024-01-03 18:16 UTC, merged