Revert 270416@main - Broke cmd-click navigation on fragment links.
WebKit/WebKit pull request #22451
Opened 2024-01-05 23:28 UTC by megangardner

#### 8bd38fa4b7e6b4ea6ac40368811c40595d0c1904
<pre>
Revert 270416@main - Broke cmd-click navigation on fragment links.
<a href="https://bugs.webkit.org/show_bug.cgi?id=267156">https://bugs.webkit.org/show_bug.cgi?id=267156</a>
<a href="https://rdar.apple.com/119079650">rdar://119079650</a>

Reviewed by NOBODY (OOPS!).

This change cause command-clicking on a fragment link to navigate the main page as well
and the page on the newly opened tab. Reverting until we find another solution that
doesn&apos;t cause this regression.

* LayoutTests/http/tests/navigation/fragment-navigation-policy-ignore-expected.txt: Added.
* LayoutTests/http/tests/navigation/fragment-navigation-policy-ignore.html: Added.
* Source/WTF/wtf/cocoa/RuntimeApplicationChecksCocoa.h:
* Source/WebKit/WebProcess/WebCoreSupport/WebFrameLoaderClient.cpp:
(WebKit::WebFrameLoaderClient::dispatchDecidePolicyForNavigationAction):
* Tools/TestWebKitAPI/Tests/WebKitCocoa/StorageQuota.mm:
* Tools/TestWebKitAPI/cocoa/TestNavigationDelegate.h:
* Tools/TestWebKitAPI/cocoa/TestNavigationDelegate.mm:
(-[TestNavigationDelegate _webView:navigation:didSameDocumentNavigation:]): Deleted.
(-[TestNavigationDelegate waitForDidSameDocumentNavigation]): Deleted.
(-[WKWebView _test_waitForDidSameDocumentNavigation]): Deleted.
</pre>

2024-01-05 23:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8bd38fa4b7e6b4ea6ac40368811c40595d0c1904. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22451

2024-01-05 23:45 UTC, aprotyas reviewed
LGTM with the build fix

2024-01-05 23:45 UTC, aprotyas commented on Source/WebKit/WebProcess/WebCoreSupport/WebFrameLoaderClient.cpp
> +        auto sendResult = webPage->sendSync(Messages::WebPageProxy::DecidePolicyForNavigationActionSync(m_frame->info(), documentLoader ? documentLoader->navigationID() : 0, navigationActionData, ori
Looks like we need just a bit more than a clean revert here

```suggestion
        auto sendResult = webPage->sendSync(Messages::WebPageProxy::DecidePolicyForNavigationActionSync(m_frame->info(), documentLoader ? documentLoader->navigationID() : 0, navigationActionData, originatingFrameInfoData, originatingPageID, navigationAction.originalRequest(), request, IPC::FormDataReference { request.httpBody() }));
```

2024-01-10 21:15 UTC, achristensen07 requested changes
This is being fixed another way in https://github.com/WebKit/WebKit/pull/22458

2025-06-13 21:53 UTC, megangardner commented
Since this was fixed another way, this pull request should be discarded.

2025-06-13 21:53 UTC, closed without merging