RE-BASELINE: REGRESSION(267516@main): [ macOS wk2 ] editing/input/caret-at-the-edge-of-contenteditable.html is constantly failing.
WebKit/WebKit pull request #22723
Opened 2024-01-12 20:15 UTC by bls1999

#### 261cda5838b120f0e8c95fe66a4b517069356766
<pre>
RE-BASELINE: REGRESSION(267516@main): [ macOS wk2 ] editing/input/caret-at-the-edge-of-contenteditable.html is constantly failing.
<a href="https://bugs.webkit.org/show_bug.cgi?id=267461">https://bugs.webkit.org/show_bug.cgi?id=267461</a>
<a href="https://rdar.apple.com/120913774">rdar://120913774</a>

Reviewed by NOBODY (OOPS!).

Correcting errant baseline migration from OpenSource expectations migration at 267516@main.

* LayoutTests/platform/mac-ventura-wk1/editing/input/caret-at-the-edge-of-contenteditable-expected.txt: Renamed from LayoutTests/platform/mac-monterey/editing/input/caret-at-the-edge-of-contenteditable-expected.txt.
* LayoutTests/platform/mac-ventura/editing/input/caret-at-the-edge-of-contenteditable-expected.txt: Removed.
* LayoutTests/platform/mac-wk2/TestExpectations:
* LayoutTests/platform/mac-wk2/editing/input/caret-at-the-edge-of-contenteditable-expected.txt:
* LayoutTests/platform/mac/editing/input/caret-at-the-edge-of-contenteditable-expected.txt: Removed.
</pre>

2024-01-12 20:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/261cda5838b120f0e8c95fe66a4b517069356766. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-12 22:14 UTC, robert-jenner requested changes
I checked out your PR on a machine running Ventura and ran it. The result I got was that it passes on Ventura WK1, but it still fails on Ventura WK2. So it looks like you will need to set a specific rebaseline for Ventura WK2 in order to fix it there. But so far this change did fix it for Ventura WK1.

2024-01-13 01:08 UTC, bls1999 commented
> I checked out your PR on a machine running Ventura and ran it. The result I got was that it passes on Ventura WK1, but it still fails on Ventura WK2. So it looks like you will need to set a specific rebaseline for Ventura WK2 in order to fix it there. But so far this change did fix it for Ventura WK1.

Thanks! I'll let this run through EWS and see what the text diff is so I can make the proper adjustment.

2024-01-13 01:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9ec0fe7c64032e1c193cea69ea48fc4cd3e1ba64. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-13 01:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9ec0fe7c64032e1c193cea69ea48fc4cd3e1ba64. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 16:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f736faf5e1b167a5f89169771d16dfc73a7c8fea. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 16:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f736faf5e1b167a5f89169771d16dfc73a7c8fea. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 17:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d69cbba2d80a0d2375879b6734db394dd7e84884. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 17:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d69cbba2d80a0d2375879b6734db394dd7e84884. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 20:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/69edf056105fa20dafa097a2ccf5ecbca07c0d4b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 20:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/69edf056105fa20dafa097a2ccf5ecbca07c0d4b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22723

2024-01-16 20:17 UTC, webkit-commit-queue commented
Committed 273087@main (292595cd441a): <https://commits.webkit.org/273087@main>

Reviewed commits have been landed. Closing PR #22723 and removing active labels.

2024-01-16 20:17 UTC, merged