Generate serialization for WebCore::Payment, WebCore::PaymentContact, and WebCore::PaymentMerchantSession
WebKit/WebKit pull request #22916
Opened 2024-01-18 16:40 UTC by sheeparegreat

#### 7269c159dea28fa4dcf9ae31ff8f331f1fcf6b44
<pre>
Generate serialization for WebCore::Payment, WebCore::PaymentContact, and WebCore::PaymentMerchantSession
<a href="https://bugs.webkit.org/show_bug.cgi?id=267703">https://bugs.webkit.org/show_bug.cgi?id=267703</a>
<a href="https://rdar.apple.com/121195605">rdar://121195605</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/Modules/applepay/Payment.h:
* Source/WebCore/Modules/applepay/PaymentContact.h:
* Source/WebCore/Modules/applepay/PaymentMerchantSession.h:
* Source/WebKit/Shared/Cocoa/WebCoreArgumentCodersCocoa.mm:
(IPC::getClass&lt;PKPayment&gt;): Deleted.
(IPC::getClass&lt;PKPaymentMerchantSession&gt;): Deleted.
(IPC::getClass&lt;PKPaymentMethod&gt;): Deleted.
(IPC::ArgumentCoder&lt;WebCore::Payment&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;WebCore::Payment&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;WebCore::PaymentContact&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;WebCore::PaymentContact&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;WebCore::PaymentMerchantSession&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;WebCore::PaymentMerchantSession&gt;::decode): Deleted.
* Source/WebKit/Shared/Cocoa/WebCoreArgumentCodersCocoa.serialization.in:
* Source/WebKit/Shared/WebCoreArgumentCoders.h:
</pre>

2024-01-18 16:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7269c159dea28fa4dcf9ae31ff8f331f1fcf6b44. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22916

2024-01-18 17:02 UTC, aprotyas reviewed
LGTM

2024-01-22 20:34 UTC, achristensen07 requested changes

2024-01-22 20:34 UTC, achristensen07 commented on Source/WebCore/Modules/applepay/Payment.h
> +    friend struct IPC::ArgumentCoder<Payment, void>;
Let's instead make pkPayment() return a RetainPtr.  Same with the others.

2024-01-23 16:49 UTC, achristensen07 requested changes

2024-01-23 16:49 UTC, achristensen07 commented on Source/WebKit/Shared/Cocoa/WebCoreArgumentCodersCocoa.serialization.in
> +    [Precondition='PAL::isPassKitCoreFrameworkAvailable()', SecureCodingAllowed=[PAL::getPKPaymentClass()], Validator='pkPayment'] RetainPtr<PKPayment> pkPayment();
The validators are not equivalent to what was there before.  decoder.decodeWithAllowedClasses<T> returns an optional<RetainPtr<T>>.  Same with WebCore::PaymentMethod whose validator should be removed.  Null is ok, decode failure is not.

2024-01-25 05:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4dc79c545b89d280aaa9d07e7a2788b340bbdee4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/22916

2024-01-25 17:33 UTC, achristensen07 approved these changes

2024-01-25 17:36 UTC, webkit-commit-queue commented
Committed 273512@main (2a16c10dc012): <https://commits.webkit.org/273512@main>

Reviewed commits have been landed. Closing PR #22916 and removing active labels.

2024-01-25 17:36 UTC, merged