[masonry] Update to modern track sizing algorithm during accumulating track sizes
WebKit/WebKit pull request #23217
Opened 2024-01-25 02:50 UTC by stwrt

#### a4334c5a4587f786dc3c1159e849bd9d6efda3ec
<pre>
[masonry] Update to modern track sizing algorithm during accumulating track sizes
<a href="https://bugs.webkit.org/show_bug.cgi?id=268050">https://bugs.webkit.org/show_bug.cgi?id=268050</a>

Reviewed by NOBODY (OOPS!).

Update to the new track sizing algorithm. All elements participate that are definite inside the track,
and those that are indefinite.

* Source/WebCore/rendering/GridTrackSizingAlgorithm.cpp:
(WebCore::GridTrackSizingAlgorithm::accumulateIntrinsicSizesForTrack):
</pre>

2024-01-25 02:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a4334c5a4587f786dc3c1159e849bd9d6efda3ec. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23217

2024-01-25 21:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e935c2c449bd60adb63a708d3615be1eb3e16c7f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23217

2024-01-25 21:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e935c2c449bd60adb63a708d3615be1eb3e16c7f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23217

2024-01-25 23:12 UTC, sgill26 requested changes
Let's make sure we have a WPT export for these active also

2024-01-25 23:12 UTC, sgill26 commented on LayoutTests/imported/w3c/web-platform-tests/css/css-grid/masonry/tentative/gap/masonry-gap-001.html
Could you put the explanation for the test changes into the commit message (both for the changes to the masonry-gap test and masonry-track-sizing-overflow ones)? I'm assuming it is related to the spec change but it's a little hard to figure out how the changes correspond to it so I think extra information here would help

2024-01-26 00:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4b4ee6d0b26873887c825d467ce5109257835513. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23217

2024-01-26 00:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4b4ee6d0b26873887c825d467ce5109257835513. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23217

2024-01-26 05:33 UTC, stwrt commented
WPT Export
https://github.com/web-platform-tests/wpt/pull/44218

2024-01-26 05:51 UTC, sgill26 approved these changes

2024-01-26 06:35 UTC, webkit-commit-queue commented
Committed 273551@main (7719c4262533): <https://commits.webkit.org/273551@main>

Reviewed commits have been landed. Closing PR #23217 and removing active labels.

2024-01-26 06:35 UTC, merged