Implement currentStackPointer for Linux/LoongArch64
WebKit/WebKit pull request #23282
Opened 2024-01-26 02:19 UTC by xiangzhai

Implement currentStackPointer for Linux/LoongArch64
https://bugs.webkit.org/show_bug.cgi?id=268131

Reviewed by NOBODY.

Implement currentStackPointer for Linux/LoongArch64 to fix the build error.

* Source/WTF/wtf/StackPointer.cpp:

2024-01-26 02:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/30fff374dd9dfb91986588c0bdba3bd9bc456d49. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23282

2024-02-02 22:50 UTC, Constellation requested changes
Thanks. Please follow to https://webkit.org/contributing-code/ to use the defined commit message format etc. (And use `git-webkit` command to update PR). WebKit commit requires specific commit message format & PR format.

2024-02-04 01:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6c104bd74d8b410bc4c550c78cb7e035e1a12245. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23282

2024-02-04 02:00 UTC, xiangzhai commented
Hi @Constellation 

Thanks for your review!

I have updated the commit message.

Thanks,
Leslie Zhai

2024-02-23 08:03 UTC, xiangzhai commented
PING

2024-02-28 02:10 UTC, xiangzhai commented
Hi @Constellation

Could you review my patch please?

Thanks,
Leslie Zhai

2024-02-29 21:09 UTC, MenloDorian approved these changes
r=me

2024-03-02 02:51 UTC, xiangzhai commented
Hi @MenloDorian

Could you commit the patch on my behalf please? or wait for @Constellation review?

Thanks,
Leslie Zhai

2024-03-27 17:26 UTC, Constellation approved these changes
r=me

2024-03-27 17:54 UTC, webkit-commit-queue commented
Committed 276739@main (f27ad76123d4): <https://commits.webkit.org/276739@main>

Reviewed commits have been landed. Closing PR #23282 and removing active labels.

2024-03-27 17:54 UTC, merged