[GStreamer][VideoCapture] VideoTrackPrivateGStreamer: Only enqueueTask in callbacks when not on MainThread
WebKit/WebKit pull request #2329
Opened 2022-07-12 18:50 UTC by jameshilliard

#### 033de5eb1bec2d1b2d5bc4715801fa0a6a8ac83d
<pre>
[GStreamer][VideoCapture] VideoTrackPrivateGStreamer: Only enqueueTask in callbacks when not on MainThread
<a href="https://bugs.webkit.org/show_bug.cgi?id=242644">https://bugs.webkit.org/show_bug.cgi?id=242644</a>

Reviewed by NOBODY (OOPS!).

If we receive a callback while isMainThread() is already true we
should execute the callback function directly as AbortableTaskQueue
expects isMainThread() to be false.

Fixes the following assert:
ASSERTION FAILED: !isMainThread()
/app/webkit/Source/WebCore/platform/AbortableTaskQueue.h(124) : void WebCore::AbortableTaskQueue::enqueueTask(WTF::Function&lt;void()&gt;&amp;&amp;)
1   0x10f16c73 WTFCrash
2   0xd923126 /app/webkit/WebKitBuild/Debug/lib/libWPEWebKit-1.1.so.0(+0x90d0126) [0xd923126]
3   0x1122626e /app/webkit/WebKitBuild/Debug/lib/libWPEWebKit-1.1.so.0(+0xc9d326e) [0x1122626e]
4   0x112a7b79 /app/webkit/WebKitBuild/Debug/lib/libWPEWebKit-1.1.so.0(+0xca54b79) [0x112a7b79]
5   0x112a7bbd /app/webkit/WebKitBuild/Debug/lib/libWPEWebKit-1.1.so.0(+0xca54bbd) [0x112a7bbd]
6   0x19839fef g_closure_invoke
7   0x1984cf16 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x28f16) [0x1984cf16]
8   0x19853c0c g_signal_emit_valist
9   0x19853d63 g_signal_emit
10  0x1983ed84 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1ad84) [0x1983ed84]
11  0x16150c08 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x44c08) [0x16150c08]
12  0x19840f1a g_object_notify_by_pspec
13  0x4063c688 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstplayback.so(+0x43688) [0x4063c688]
14  0x1619a126 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x8e126) [0x1619a126]
15  0x15f41896 g_hook_list_marshal
16  0x16199895 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x8d895) [0x16199895]
17  0x1619c68d /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x9068d) [0x1619c68d]
18  0x1619d26e /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x9126e) [0x1619d26e]
19  0x1619d728 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x91728) [0x1619d728]
20  0x1619b000 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x8f000) [0x1619b000]
21  0x161a6780 gst_pad_push_event
22  0x1619cbec /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x90bec) [0x1619cbec]
23  0x1619d26e /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x9126e) [0x1619d26e]
24  0x1619d728 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x91728) [0x1619d728]
25  0x1619b000 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x8f000) [0x1619b000]
26  0x161a6780 gst_pad_push_event
27  0x161a6d62 /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x9ad62) [0x161a6d62]
28  0x161a2d6e gst_pad_forward
29  0x161a2eb5 gst_pad_event_default
30  0x1619cbec /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x90bec) [0x1619cbec]
31  0x1619d26e /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0(+0x9126e) [0x1619d26e]
==74== Invalid write of size 4
==74==    at 0x10F16C78: WTFCrash (Assertions.cpp:328)
==74==    by 0xD923125: WTFCrashWithInfo(int, char const*, char const*, int) (Assertions.h:754)
==74==    by 0x1122626D: WebCore::AbortableTaskQueue::enqueueTask(WTF::Function&lt;void ()&gt;&amp;&amp;) (AbortableTaskQueue.h:124)
==74==    by 0x112A7B78: WebCore::VideoTrackPrivateGStreamer::VideoTrackPrivateGStreamer(WTF::WeakPtr&lt;WebCore::MediaPlayerPrivateGStreamer, WTF::EmptyCounter&gt;, unsigned int, _GstStream*)::{lambda(WebCore::VideoTrackPrivateGStreamer*)#2}::operator()(WebCore::VideoTrackPrivateGStreamer*) const (VideoTrackPrivateGStreamer.cpp:60)
==74==    by 0x112A7BBC: WebCore::VideoTrackPrivateGStreamer::VideoTrackPrivateGStreamer(WTF::WeakPtr&lt;WebCore::MediaPlayerPrivateGStreamer, WTF::EmptyCounter&gt;, unsigned int, _GstStream*)::{lambda(WebCore::VideoTrackPrivateGStreamer*)#2}::_FUN(WebCore::VideoTrackPrivateGStreamer*) (VideoTrackPrivateGStreamer.cpp:60)
==74==    by 0x19839FEE: g_closure_invoke (gclosure.c:830)
==74==    by 0x1984CF15: signal_emit_unlocked_R (gsignal.c:3742)
==74==    by 0x19853C0B: g_signal_emit_valist (gsignal.c:3497)
==74==    by 0x19853D62: g_signal_emit (gsignal.c:3553)
==74==    by 0x1983ED83: g_object_dispatch_properties_changed (gobject.c:1212)
==74==    by 0x16150C07: gst_object_dispatch_properties_changed (gstobject.c:455)
==74==    by 0x19840F19: g_object_notify_by_spec_internal (gobject.c:1305)
==74==    by 0x19840F19: g_object_notify_by_pspec (gobject.c:1415)
==74==    by 0x4063C687: gst_parse_pad_update_tags (gstparsebin.c:3961)
==74==    by 0x4063C687: gst_parse_pad_event (gstparsebin.c:4060)
==74==    by 0x1619A125: probe_hook_marshal (gstpad.c:3664)
==74==    by 0x15F41895: g_hook_list_marshal (ghook.c:672)
==74==    by 0x16199894: do_probe_callbacks (gstpad.c:3848)
==74==    by 0x1619C68C: gst_pad_send_event_unchecked (gstpad.c:5872)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x1619CBEB: gst_pad_send_event_unchecked (gstpad.c:5900)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x161A6D61: event_forward_func (gstpad.c:3125)
==74==    by 0x161A2D6D: gst_pad_forward (gstpad.c:3079)
==74==    by 0x161A2EB4: gst_pad_event_default (gstpad.c:3176)
==74==    by 0x1619CBEB: gst_pad_send_event_unchecked (gstpad.c:5900)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x161A6D61: event_forward_func (gstpad.c:3125)
==74==    by 0x161A2D6D: gst_pad_forward (gstpad.c:3079)
==74==    by 0x161A2EB4: gst_pad_event_default (gstpad.c:3176)
==74==    by 0x1619CBEB: gst_pad_send_event_unchecked (gstpad.c:5900)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x161A6D61: event_forward_func (gstpad.c:3125)
==74==    by 0x161A2D6D: gst_pad_forward (gstpad.c:3079)
==74==    by 0x161A2EB4: gst_pad_event_default (gstpad.c:3176)
==74==    by 0x1619CBEB: gst_pad_send_event_unchecked (gstpad.c:5900)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x1619CBEB: gst_pad_send_event_unchecked (gstpad.c:5900)
==74==    by 0x1619D26D: gst_pad_push_event_unchecked (gstpad.c:5544)
==74==    by 0x1619D727: push_sticky (gstpad.c:4047)
==74==    by 0x1619AFFF: events_foreach (gstpad.c:608)
==74==    by 0x161A677F: check_sticky (gstpad.c:4106)
==74==    by 0x161A677F: gst_pad_push_event (gstpad.c:5675)
==74==    by 0x11310D74: webkitMediaStreamSrcTrackEnded(_WebKitMediaStreamSrc*, InternalSource&amp;) (GStreamerMediaStreamSource.cpp:791)
==74==    by 0x11310F79: InternalSource::trackEnded(WebCore::MediaStreamTrackPrivate&amp;) (GStreamerMediaStreamSource.cpp:812)
==74==    by 0x14A385B6: auto WebCore::MediaStreamTrackPrivate::endTrack()::{lambda(auto:1&amp;)#1}::operator()&lt;WebCore::MediaStreamTrackPrivate::Observer&gt;(WebCore::MediaStreamTrackPrivate::Observer&amp;) const (MediaStreamTrackPrivate.cpp:155)
==74==    by 0x14A385E9: WTF::Detail::CallableWrapper&lt;WebCore::MediaStre [...]

2022-07-13 12:01 UTC, ntrrgc requested changes
> If we receive a callback while isMainThread() is already true we
> should execute the callback function directly as AbortableTaskQueue
> expects isMainThread() to be false.

While a change like this, on the surface, seems to make intuitive sense, it's worth asking: why are those handlers being called from the main thread in this case?

If you look at the traceback in your PR, you'll notice this occurs inside `webkitMediaStreamSrcTrackEnded`. Do these notifications therefore still need to be handled or would be better ignored? What are the consequences from handling or ignoring them? Is there a possibility of deadlocks in the main-thread code path?

To code therefore needs comments, explaining:
1. In what situations each code path is traversed, as this is likely not immediately obvious to the reader, and there are significant threading consequences from doing things in the streaming thread vs doing them in the main thread. The reader should also be able to gather which code path is the frequent one and which one is the exceptional path (e.g. ran only on termination).
2. Any relevant consequences of calling updateConfigurationFromCaps(), especially in the unusual main-thread.

2022-07-13 13:36 UTC, jameshilliard commented
> Do these notifications therefore still need to be handled or would be better ignored?

It seems `webkitMediaStreamSrcTrackEnded` is deliberately updating the tags, at least best I can tell.

> What are the consequences from handling or ignoring them?

It seems like ignoring them is not what is intended by `webkitMediaStreamSrcTrackEnded` but you might be right that they should be ignored, it's also rather unclear why I'm the only one that seems to have hit this particular assert.

> Is there a possibility of deadlocks in the main-thread code path?

Oh that does seem to be happening as well(although some of those issues seem to be somewhat pre-existing), I've been working on tracking issues down there, I don't think this makes the situation worse however since one can't even call `AbortableTaskQueue` from the main thread without hitting an assert.

> The reader should also be able to gather which code path is the frequent one and which one is the exceptional path (e.g. ran only on termination).

Well starting/stopping video streams tends to be relatively symmetrical in frequency, and these callbacks seem to be used only during stream startup/caps negotiation and stream shutdown from what I can tell.

2022-07-21 02:15 UTC, jameshilliard commented
> Is there a possibility of deadlocks in the main-thread code path?

Well this does actually appear to fix a deadlock, see #2605.

2022-08-20 07:42 UTC, jameshilliard commented
closing as #2605 is now merged which appears to fix the issue

2022-08-20 07:42 UTC, closed without merging