DRY out queuePopoverToggleEventTask & queueDetailsToggleEventTask
WebKit/WebKit pull request #23361
Opened 2024-01-27 22:05 UTC by keithamus

```
DRY out queuePopoverToggleEventTask & queueDetailsToggleEventTask
https://bugs.webkit.org/show_bug.cgi?id=268230

Reviewed by NOBODY (OOPS!).

DRY out the two ToggleEventTasks by making queuePopoverToggleEventTask,
adding the state to elementRareData.

* Source/WebCore/dom/Element.cpp:
(WebCore::Element::toggleEventData const):
(WebCore::Element::setToggleEventData):
(WebCore::Element::clearToggleEventData):
* Source/WebCore/dom/Element.h:
* Source/WebCore/dom/ElementRareData.cpp:
* Source/WebCore/dom/ElementRareData.h:
(WebCore::ElementRareData::toggleEventData):
(WebCore::ElementRareData::setToggleEventData):
(WebCore::ElementRareData::clearToggleEventData):
(WebCore::ElementRareData::useTypes const):
* Source/WebCore/dom/NodeRareData.h:
* Source/WebCore/dom/PopoverData.h:
(WebCore::PopoverData::queuedToggleEventData const): Deleted.
(WebCore::PopoverData::setQueuedToggleEventData): Deleted.
(WebCore::PopoverData::clearQueuedToggleEventData): Deleted.
* Source/WebCore/dom/ToggleEvent.h:
* Source/WebCore/html/HTMLDetailsElement.cpp:
(WebCore::HTMLDetailsElement::attributeChanged):
(WebCore::HTMLDetailsElement::queueDetailsToggleEventTask): Deleted.
* Source/WebCore/html/HTMLDetailsElement.h:
* Source/WebCore/html/HTMLElement.cpp:
(WebCore::HTMLElement::queueToggleEventTask):
(WebCore::HTMLElement::showPopover):
(WebCore::HTMLElement::hidePopoverInternal):
(WebCore::HTMLElement::queuePopoverToggleEventTask): Deleted.
* Source/WebCore/html/HTMLElement.h:

```

2024-01-27 22:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/325dd9116cf09f7be21c769c0f8ebc6d56ee6d07. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-01-27 22:10 UTC, nt1m reviewed
This results in a change of behavior I believe, if you queue this sequence of calls:

```
showPopover()
details.open = false;
```

Your patch would result in a single toggle event with oldState = true; newState = false; whereas the current code would emit 2 toggle events.

2024-01-29 09:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/55a1cc31ba1ca6ae795a5137a7e65127b5f0da1c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-01-29 09:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3cf0b66188e8397317f46d8cd77d527690f2c260. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-01-29 09:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8c0712514a0510fa7f32fc24b97bfc5976a09da4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-18 16:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/40176a0ff91652301326a064e2cbf280114a0fa5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-18 17:42 UTC, nt1m commented
> What does DRY mean?

Do not repeat yourself, though I suppose we can just say "De-duplicate" instead

2024-11-18 17:44 UTC, darinadler commented
This seems like a good change. Concentrating the implementation details so they are not scattered across so many files and classes is great. It does seem like the 5 possible states of an optional ToggleEventData are using more than the roughly 2.3 bits of rare data it should take to store them, thanks to the relative lack of efficiency of an `optional` `struct` containing two `bool` data members, along with a flag bit — about 25 bits. Maybe we can find a more efficient way to store the state while only having an effect on a tiny bit of innermost code.

2024-11-18 17:50 UTC, keithamus commented
I'm sure I could squeeze it into a u8 but I worry about the readability of such changes.

2024-11-18 17:56 UTC, nt1m commented
@keithamus What is the correct behavior when you quickly expand a details element or open a dialog element, followed by calling showPopover() on it? Right now we would emit two events, now we would coalesce them into one. Is that the correct behavior? Can we write some WPT for this?

2024-11-18 17:59 UTC, keithamus commented
@nt1m the correct behaviour is to coalesce. There are some WPTs written. I am happy to sync them and fix those cases, but I'd prefer to do one step at a time.

2024-11-18 18:03 UTC, nt1m commented
> @nt1m the correct behaviour is to coalesce. There are some WPTs written. I am happy to sync them and fix those cases, but I'd prefer to do one step at a time.

I'd be curious to see the WPTs that mix popover toggle events and details/dialog toggle events, because this PR changes the behavior when you mix those.

2024-11-18 18:08 UTC, keithamus commented
Oh I think I see what you mean now. Calling `.showPopover()` on an already open `<dialog>` element will throw an error.

2024-11-18 18:13 UTC, darinadler commented
> I'm sure I could squeeze it into a u8 but I worry about the readability of such changes.

The way to make such things readable is to put all of that logic into one getter and one setter function that must do absolutely nothing else other than extracting and storing the data. Then have all the rest of the code work via those. That still doesn’t tell us how important it is to save the storage, though. Long term it can be quite important to not bloat the size of things like `ElementRareData` and using 10x as many bits as we need may eventually add up.

2024-11-19 11:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cea020e29e071610a2b625929f05054c78ad81bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-19 12:18 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/342520e5ef7c4fb0cc5cf82064bf41157b957c40)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/77104 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/56139 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/81662 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/28383 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/79221 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/65287 "Build is in progress. Recent messages:OS: Sonoma (14.6), Xcode: 15.4") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/4435 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/81662 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 win-tests](https://ews-build.webkit.org/#/builders/59/builds/28383 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/80171 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/65287 "Build is in progress. Recent messages:OS: Sonoma (14.6), Xcode: 15.4") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/81662 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/65287 "Build is in progress. Recent messages:OS: Sonoma (14.6), Xcode: 15.4") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/26709 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/65287 "Build is in progress. Recent messages:OS: Sonoma (14.6), Xcode: 15.4") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/83089 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/4484 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/4435 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/83089 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/4639 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/83089 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/30019 "Build is in progress. Recent messages:") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/4430 "Build is in progress. Recent messages:OS: Sequoia (15.0.1), Xcode: 16.0") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/7246 "Build is in progress. Recent messages:") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/4450 "Build is in progress. Recent messages:") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/7885 "Build is in progress. Recent messages:") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b [...]

2024-11-19 12:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1e818edf5f5b57571d11e442c4586f8f9dac5711. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-19 12:26 UTC, keithamus commented
Okay I've had another go at simplifying, this time the PopoverData & HTMLDetailsElement keep a RefPtr to a new ToggleEventTask class which itself retains the logic & state of prior events. It should address the issue @nt1m raised around popover & details (as they now can hold their own independent instance).

2024-11-19 13:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/703ac89ef364f5725ec5844804da645cd03d7f96. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-19 15:39 UTC, darinadler approved these changes

2024-11-19 15:39 UTC, darinadler commented on Source/WebCore/dom/PopoverData.h
> +#include "ToggleEvent.h"
We should avoid including this by forward declaring `ToggleEventTask` and having `ensureToggleEventTask` and the `PopoverData` constructor and destructor not be inlined. Can still use `default`, but in the `.cpp` file.

Doing this as we go helps prevent compile time slowdowns that accrue over time when we unnecessarily add header includes to headers.

2024-11-19 15:39 UTC, darinadler commented on Source/WebCore/dom/ToggleEvent.h
> +#include <wtf/RefCounted.h>
This include isn’t needed if we are including `Element.h`.

2024-11-19 15:39 UTC, darinadler commented on Source/WebCore/dom/ToggleEvent.h
> +class ToggleEventTask final: public RefCounted<ToggleEventTask> {
Seems to me this would be better in a separate header file. Almost no code needs to know about both `ToggleEventTask` and `ToggleEvent`.

2024-11-19 15:39 UTC, darinadler commented on Source/WebCore/html/HTMLElement.h
> +enum class ToggleState : bool;
The forward declarations should not be mixed in with actual definitions. `FireEvenfs`, `FocusPreviousElement`, and `PopoverState` should be moved out of this paragraph and below all the forward declarations.

2024-11-19 16:00 UTC, darinadler requested changes
Need to fix the Safer C++ build failures

2024-11-19 18:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/15447ffa9e3dda599ee8dc54ccab5ce48582be88. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-19 18:15 UTC, keithamus commented
@darinadler addressed all comments by splitting out the files. Let me know your thoughts, thanks!

2024-11-19 19:58 UTC, darinadler approved these changes

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEvent.h
> +#include "Element.h"
This shouldn’t be added here; no reason it’s needed any more.

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.cpp
> +    if (m_data)
WebKit style uses early return rather than nesting all the logic of the function
```
if (!m_data)
    return;
```

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.cpp
> +    if (RefPtr element = m_element.get()) {
```
RefPtr element = m_element.get();
if (!element)
    return;
```

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.cpp
> +            if (RefPtr element = m_element.get())
Consider that here too, although it’s the least fancy one.
```
RefPtr element = m_element.get();
if (!element)
    return;
```

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.h
> +#include "Element.h"
Still including `Element.h` here even though we are forward declaring it. Should not do both!

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.h
> +#include "Event.h"
No reason to include `Event.h` here!

2024-11-19 19:58 UTC, darinadler commented on Source/WebCore/html/HTMLElement.h
>  enum class FireEvents : bool { No, Yes };
`SelectionRenderingBehavior` should come before this. All forward declarations before any non-forward declarations.

2024-11-19 23:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/138d40d79e93ec38f7b029c19dc6e8fa188d8db7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-19 23:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/834bbddd5d3d20e976c71d353bd160937e27027a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-20 10:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/64e7e57aaef2c38675909bc37d62922d2f234926. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-20 13:02 UTC, darinadler approved these changes

2024-11-20 13:02 UTC, darinadler commented on Source/WebCore/dom/ToggleEventTask.h
> +#include <wtf/RefCounted.h>
Do not need this include if we are also including `Element.h`.

2024-11-20 13:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2195aa48555ff63ddf35d64e0dee861e18c57801. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-20 13:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dc71dc7be8c59e7d18f13e3e577253bfead6713a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-20 13:56 UTC, darinadler approved these changes

2024-11-20 21:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/94a31d9010e05ed8f22020bd4393a4036bc90ed0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23361

2024-11-20 21:42 UTC, darinadler commented
Would love to know what changed in that last revision — too bad the GitHub compare feature doesn’t show me that!

2024-11-20 22:28 UTC, keithamus commented
> Would love to know what changed in that last revision — too bad the GitHub compare feature doesn’t show me that, because mostly I just see the rebasing!

Yes it's an unfortunate diff from the force push. The merge conflict was as follows, in `HTMLDetailsElement.cpp`:

```diff
<<<<<<< HEAD
                m_defaultSlot->removeInlineStyleProperty(CSSPropertyContentVisibility);
                queueDetailsToggleEventTask(DetailsState::Closed, DetailsState::Open);
=======
                root->appendChild(*m_defaultSlot);
                queueDetailsToggleEventTask(ToggleState::Closed, ToggleState::Open);
>>>>>>> dc71dc7be8c5 (Deduplicate logic from queuePopoverToggleEventTask & queueDetailsToggleEventTask)
                if (document().settings().detailsNameAttributeEnabled() && !attributeWithoutSynchronization(nameAttr).isEmpty()) {
                    ShouldNotFireMutationEventsScope scope(document());
                    for (auto& otherDetailsElement : otherElementsInNameGroup())
                        otherDetailsElement->removeAttribute(openAttr);
                }
            } else {
<<<<<<< HEAD
                m_defaultSlot->setInlineStyleProperty(CSSPropertyContentVisibility, CSSValueHidden);
                queueDetailsToggleEventTask(DetailsState::Open, DetailsState::Closed);
=======
                root->removeChild(*m_defaultSlot);
                queueDetailsToggleEventTask(ToggleState::Open, ToggleState::Closed);
>>>>>>> dc71dc7be8c5 (Deduplicate logic from queuePopoverToggleEventTask & queueDetailsToggleEventTask)
```

2024-11-21 01:01 UTC, webkit-commit-queue commented
Committed 286884@main (9cf5cec66cd0): <https://commits.webkit.org/286884@main>

Reviewed commits have been landed. Closing PR #23361 and removing active labels.

2024-11-21 01:01 UTC, merged