Web Inspector: align runtimes in the audit tests
WebKit/WebKit pull request #23387
Opened 2024-01-28 18:15 UTC by francescorn

#### 3ae1e4089ac387d5226a07ab223df3e4b7a063cc
<pre>
Web Inspector: align runtimes in the audit tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=268257#c2">https://bugs.webkit.org/show_bug.cgi?id=268257#c2</a>

Reviewed by NOBODY (OOPS!).

Change text-align:center to text-align:right and remove display:inline-block to align the runtimes
in .content-view.audit-test-case &gt; header &gt; .metadata &gt; .duration in AuditTestCaseContentView.css.

* Source/WebInspectorUI/UserInterface/Views/AuditTestCaseContentView.css:
(.content-view.audit-test-case &gt; header &gt; .metadata &gt; .duration):
</pre>

2024-01-28 18:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ae1e4089ac387d5226a07ab223df3e4b7a063cc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23387

2024-01-28 18:19 UTC, francescorn commented
Safari 17.3 on the left and mini-browser on the right with my changes to align the runtimes:
<img width="2559" alt="audit_tab_runtime_safari_left_and_minibrowser_right" src="https://github.com/WebKit/WebKit/assets/113309999/3ab9cfd2-c738-4d47-958d-c0b86aef8ad9">

2024-01-28 18:28 UTC, francescorn commented
Ready for a review.

2024-02-04 05:38 UTC, dcrousso requested changes
personally i like the look of it better when center aligned as these values aren't necessarily meant to be compared (which is a benefit of right alignment with numbers, i.e. "which of these values is smallest/largest").  i think it also breaks the "grid" we have where the result level `WI.ScopeBar` and run date being aligned right and the pass percentage and run time being center aligned.  i dunno.  it just feels a bit weird to me.

can you explain the motivation for this change and/or why you feel the new UI is better?

2024-02-06 19:12 UTC, francescorn commented
@dcrousso I think the runtimes look better end-aligned because the web developer or user can quickly scan over each element because the 0ms runtimes stick out a little bit  in the center, whereas everything else in the right of the audit tab are right or end aligned.

2024-02-06 19:13 UTC, francescorn commented
@dcrousso It is also more responsive to the user or web developer minimizing to the left and right having the elements on the right in the audit tab being either right or end aligned.

2024-02-25 16:23 UTC, dcrousso approved these changes
i tried living with this for a bit and i think ive changed my mind and agree that it'd be better to align right

2024-02-25 16:35 UTC, Ahmad-S792 commented
@francescorn - Bug URL has fragment (#c2). Don't know whether it will work in merge-queue or not. If you can update, it would be great but if `merge-queue` can ignore it then I don't know but might need input from someone else.

2024-02-25 20:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/52cade33041baa2c348e2fd066b5529836b9cdc1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23387

2024-02-25 20:55 UTC, stwrt commented
Added to merge-queue. Was reviewed by Devin, and was passing test cases.

2024-02-25 21:52 UTC, webkit-commit-queue commented
Committed 275298@main (7b4e559c1d8a): <https://commits.webkit.org/275298@main>

Reviewed commits have been landed. Closing PR #23387 and removing active labels.

2024-02-25 21:52 UTC, merged