Fix event.relatedTarget for focusin event when shadow tree state was changed by the focus event
WebKit/WebKit pull request #2354
Opened 2022-07-13 01:50 UTC by nt1m

#### e729a9a9ae53782edb9e60f53407f131dedb8ef3
<pre>
Fix event.relatedTarget for focusin event when shadow tree state was changed by the focus event
<a href="https://bugs.webkit.org/show_bug.cgi?id=242671">https://bugs.webkit.org/show_bug.cgi?id=242671</a>
&lt;rdar://95524130&gt;

Reviewed by NOBODY (OOPS!).

relatedTarget for FocusEvent corresponds to the element that was previously focused, but if that element was moved out of a shadow tree, or in, the tree walk walking up to the nearest shadow host will be wrong.

* Source/WebCore/dom/Document.cpp:
(WebCore::Document::setFocusedElement):
</pre>

2022-07-13 04:23 UTC, darinadler approved these changes

2022-07-18 21:08 UTC, rniwa requested changes
As we discussed elsewhere, I don't think this change is right.

2022-07-19 18:27 UTC, rniwa approved these changes
r=me assuming no perf regression.

2022-07-20 04:06 UTC, webkit-commit-queue commented
Committed 252631@main (73d8160d105b): <https://commits.webkit.org/252631@main>

Reviewed commits have been landed. Closing PR #2354 and removing active labels.

2022-07-20 04:06 UTC, merged