If testRunner.notifyDone is called in a different site isolated process than testRunner.waitUntilDone, layout test doesn't complete
WebKit/WebKit pull request #23589
Opened 2024-01-31 16:52 UTC by rreno

#### f7058fae218ac88776714507ed84b382e925b2ff
<pre>
If testRunner.notifyDone is called in a different site isolated process than testRunner.waitUntilDone, layout test doesn&apos;t complete
<a href="https://rdar.apple.com/121682316">rdar://121682316</a>
<a href="https://bugs.webkit.org/show_bug.cgi?id=268471">https://bugs.webkit.org/show_bug.cgi?id=268471</a>

Reviewed by NOBODY (OOPS!).

Before site isolation both an iframe and parent frame lived in the same
process and so used the same Injected Bundle. Done notifications worked
because even if the child frame was finishing the test it was able to
access a pointer to the main frame and dump appropriately. In site
isolation a cross origin iframe lives in a different process and so does
not have access to the main frame&apos;s pointer.

This change bypasses a main frame check when a frame is wrapping up after a
call to testRunner.notifyDone if it is not in the main frame&apos;s process.
This will allow the frame to send the &quot;Done&quot; notification to the UI
process which can handle notifications to the other web content
processes to finish the test.

* LayoutTests/http/tests/site-isolation/notify-done-expected.txt: Added.
* LayoutTests/http/tests/site-isolation/notify-done.html: Added.
* LayoutTests/http/tests/site-isolation/resources/frame-notify-done.html: Added.
* Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleFrame.cpp:
(WKBundleFrameIsRemote):
* Source/WebKit/WebProcess/InjectedBundle/API/c/WKBundleFrame.h:
* Source/WebKit/WebProcess/WebPage/WebFrame.cpp:
(WebKit::WebFrame::isRemoteFrame const):
* Source/WebKit/WebProcess/WebPage/WebFrame.h:
* Tools/WebKitTestRunner/InjectedBundle/InjectedBundlePage.cpp:
(WTR::InjectedBundlePage::dump):
</pre>

2024-01-31 17:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f7058fae218ac88776714507ed84b382e925b2ff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23589

2024-01-31 17:20 UTC, rreno commented
Oh there's an easier way to do this.

2024-01-31 18:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a0bc1150d2b1d3fb9b0b4809e5510886a1216370. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23589

2024-01-31 18:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8484166badc823f15105eabaa5cea8ce8b63e8d7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23589

2024-01-31 19:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fbc2754daeb5630ce4978233edf2c94a7c763af0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23589

2024-01-31 20:03 UTC, achristensen07 requested changes

2024-01-31 20:03 UTC, achristensen07 commented on LayoutTests/http/tests/site-isolation/notify-done-expected.txt
> +I am a simple document that calls notifyDone when loaded.
This gets the output from the wrong process.  The whole point is that if we're not in the main frame process we need to send a message to the main frame process and get output from that process.

2024-02-05 16:49 UTC, rreno commented
Will fix this with a different PR.

2024-02-05 16:49 UTC, closed without merging