Replace bzero with memset, since bzero is deprecated
WebKit/WebKit pull request #236
Opened 2022-03-31 21:34 UTC by GameCubeGBA

2022-03-31 21:49 UTC, JonWBedard commented
Thank you for your interest in contributing to the WebKit project!

We're still in the process of bringing up our infrastructure and documentation to support GitHub workflows. Things should be usable, though. https://github.com/WebKit/WebKit/wiki/Contributing contains our documentation for contributing to the project from GitHub. If you don't want to deal with our new (and potentially buggy) workflows, https://webkit.org/getting-started/ has our documentation on the bug.webkit.org based patch workflow.

2022-04-12 09:19 UTC, Constellation reviewed
Thanks! Could you follow to https://github.com/WebKit/WebKit/wiki/Contributing 's procedure to upload PR?
1. Open a corresponding bugs.webkit.org bug
2. Use `git-webkit` tool to upload PR

2022-04-12 09:24 UTC, Constellation requested changes

2022-04-12 09:24 UTC, Constellation commented on ManualTests/NPN_Invoke/main.c
> + terms, Apple grants you a personal, non-exclusive license, under Apple�s copyrights in
Let's remove this change.

2022-04-12 09:24 UTC, Constellation commented on PerformanceTests/JetStream2/wasm/TSF/tsf_fsdb.c
Let's not change files under `PerformanceTests/JetStream2`. We are including wasm files, which is compiled from this code. So changing this makes one-on-one corresponding between wasm and C++ broken.
And since wasm file is already compiled, we do not need to care about bzero deprecation here.

2022-04-12 09:24 UTC, Constellation commented on PerformanceTests/JetStream2/wasm/TSF/tsf_reflect.c
>                            "tsf_reflect_create()");
Ditto. Let's not change files under `PerformanceTests/JetStream2`.

2022-04-12 09:24 UTC, Constellation commented on Websites/browserbench.org/JetStream2.0/wasm/TSF/tsf_fsdb.c
>      struct addrinfo *result,*cur;
Ditto. Let's not change files under `Websites/browserbench.org/JetStream2.0`

2022-04-12 09:24 UTC, Constellation commented on Websites/browserbench.org/JetStream2.0/wasm/TSF/tsf_reflect.c
>                            "tsf_reflect_create()");
Ditto.

2022-04-27 12:39 UTC, mcatanzaro commented
Hi, thanks for contributing to WebKit. I'm going to close this for now, but feel free to reopen if you get a chance to respond to the feedback received above.

2022-04-27 12:39 UTC, closed without merging