[GTK][WPE] Fix undefined reference to 'shm_open' and 'shm_unlink'
WebKit/WebKit pull request #23739
Opened 2024-02-02 13:48 UTC by dpino

#### 668d31363aa5a339e30c9d1b17b82514d46f00ad
<pre>
[GTK][WPE] Fix undefined reference to &apos;shm_open&apos; and &apos;shm_unlink&apos;
<a href="https://bugs.webkit.org/show_bug.cgi?id=268619">https://bugs.webkit.org/show_bug.cgi?id=268619</a>

Reviewed by NOBODY (OOPS!).

Functions &apos;shm_open&apos; and &apos;shm_unlink&apos; are defined in librt.

* Source/cmake/OptionsGTK.cmake:
* Source/cmake/OptionsWPE.cmake:
</pre>

2024-02-02 13:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/668d31363aa5a339e30c9d1b17b82514d46f00ad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23739

2024-02-02 14:03 UTC, aperezdc requested changes
Needing `librt` for `shm_{open,unlink}` is a GNUism. There is nothing that prevents other C libraries from providing the symbols in the main `libc.so` shared object. In fact both Musl and uCLibc do that, and we support them; OpenBSD also stashes these symbols in `libc.so`, and so on.

What we need to do is check with CMake whether the functions exist without linking any particular library, and if that failed then try whether `librt` provides the symbols.

We have such code in `Source/WebKit/CMakeLists.txt`, around line 664:

```cmake
if (UNIX)                                                                                                                                                                       
    check_function_exists(shm_open SHM_OPEN_EXISTS)
    if (NOT SHM_OPEN_EXISTS)
        set(CMAKE_REQUIRED_LIBRARIES rt)
        check_function_exists(shm_open SHM_OPEN_REQUIRES_LIBRT)
        if (SHM_OPEN_REQUIRES_LIBRT)
            list(APPEND WebKit_PRIVATE_LIBRARIES rt)
        endif ()
        unset(CMAKE_REQUIRED_LIBRARIES)
    endif ()  
endif ()
```

You would need to investigate why the snippet above is not working as intended. I see the missing symbols were only used in `Source/WebKit/` and the `SharedMemory` classes were moved recently to WebCore... I suspect moving this snippet to `Source/WebCore/CMakeLists.txt` and adjusting so it applies to the `WebCore` target would be the proper fix.

2024-02-02 16:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b0df95241e2ab3a30b0cd72979f7855642fa08a0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/23739

2024-02-02 16:40 UTC, dpino commented
I added several `messages` in `Source/WebKit/CMakeLists.txt` to debug whether `rt' was added to WebKit_PRIVATE_LIBRARIES, which it was the case. Example:

```
- Using source list file: platform/SourcesGLib.txt
### shm_open EXISTS
### append rt to WebKit_PRIVATE_LIBRARIES
-- Using platform-specific CMakeLists: /home/pwuser/webkit/Source/WebKit/PlatformGTK.cmake
-- Using source list file: Sources.txt
-- Using source list file: Platform/Sources.txt
```

However, it doesn't seem this is enough as `rt` is missing in several targets (WPEPlatform and TestWebCore).

2024-02-02 21:58 UTC, aperezdc commented
> I added several `messages` in `Source/WebKit/CMakeLists.txt` to debug whether `rt' was added to WebKit_PRIVATE_LIBRARIES, which it was the case. Example:
> 
> ```
> - Using source list file: platform/SourcesGLib.txt
> ### shm_open EXISTS
> ### append rt to WebKit_PRIVATE_LIBRARIES
> -- Using platform-specific CMakeLists: /home/pwuser/webkit/Source/WebKit/PlatformGTK.cmake
> -- Using source list file: Sources.txt
> -- Using source list file: Platform/Sources.txt
> ```
> 
> However, it doesn't seem this is enough as `rt` is missing in several targets (WPEPlatform and TestWebCore).

I think that when the WebCore library is built as a static library, we need to add `rt` as a `PUBLIC` library by listing it in `WebCore_LIBRARIES`, so CMake will add it to the linker command line for any target that depends on WebCore (either directly or transively). The patch in https://github.com/WebKit/WebKit/pull/23746 adds `rt` to `WebCore_PRIVATE_LIBRARIES` (same as was being done before) which is the right choice when WebCore is built as a _shared_ library.

2024-02-03 09:42 UTC, dpino commented
https://github.com/WebKit/WebKit/pull/23746 was enough to fix the build failure in the bots. Closing PR.

2024-02-03 09:42 UTC, closed without merging