[LBSE]
WebKit/WebKit pull request #2383
Opened 2022-07-13 22:04 UTC by nikolaszimmermann

#### 854d07c997c731aa618d401ad30adb5772fd083d
<pre>
[LBSE] Cleanup RenderSVGContainer related code
<a href="https://bugs.webkit.org/show_bug.cgi?id=242718">https://bugs.webkit.org/show_bug.cgi?id=242718</a>

Reviewed by NOBODY (OOPS!).

This unifies the main pieces of the container child layout logic in
RenderSVGContainer::layout(), in such a way that the logic is more
straightforward to follow (not having critical pieces of the logic
sprinkled across RenderSVG(Transformable|Viewport)Container) and to
assure that sensitive flags like &apos;m_didTransformToRootUpdate&apos; and
&apos;m_isLayoutSizeChanged&apos; are computed and stored in one place
instead of one per container renderer.

Use SetScope&lt;&gt; instead of manual updates of these flags to avoid uny
undefined states.

The RenderSVGContainer layout logic now looks almost identical to
RenderSVGRoot - the LBSE variants are clean &amp; small compared to their
LegacyRenderSVG* counterparts.

Covered by existing tests, that were broken under LBSE before.
(No progressions as the affected tests are still broken compared
to legacy, due to other reasons, e.g. missing &lt;image&gt; support).

* Source/WebCore/rendering/svg/RenderSVGContainer.cpp:
(WebCore::RenderSVGContainer::layout):
(WebCore::RenderSVGContainer::calculateViewport): Deleted.
* Source/WebCore/rendering/svg/RenderSVGContainer.h:
(WebCore::RenderSVGContainer::isLayoutSizeChanged const):
(WebCore::RenderSVGContainer::didTransformToRootUpdate const):
(WebCore::RenderSVGContainer::updateLayoutSizeIfNeeded):
* Source/WebCore/rendering/svg/RenderSVGTransformableContainer.cpp:
(WebCore::RenderSVGTransformableContainer::graphicsElement const):
(WebCore::RenderSVGTransformableContainer::additionalContainerTranslation const):
(WebCore::RenderSVGTransformableContainer::updateFromStyle):
(WebCore::RenderSVGTransformableContainer::updateLayerTransform):
(WebCore::RenderSVGTransformableContainer::applyTransform const):
(WebCore::RenderSVGTransformableContainer::calculateViewport): Deleted.
(WebCore::RenderSVGTransformableContainer::layoutChildren): Deleted.
(WebCore::RenderSVGTransformableContainer::styleWillChange): Deleted.
* Source/WebCore/rendering/svg/RenderSVGTransformableContainer.h:
</pre>
----------------------------------------------------------------------
#### f839f21e7f144dddddc61f02831601a6d34895d0
<pre>
[LBSE] Cleanup RenderSVGRoot code
<a href="https://bugs.webkit.org/show_bug.cgi?id=242715">https://bugs.webkit.org/show_bug.cgi?id=242715</a>

Reviewed by NOBODY (OOPS!).

Cleanup the convoluted RenderSVGRoot code, get rid of the
viewBox transformations, which are going to be replaced
soon by a proper implementation, that only uses CSS Transforms
to realize viewBox.

For now get rid of the half-baked implementation, and report
correct metrics again for RenderSVGRoot (invariant under viewBox).

Update existing LBSE text expectations. Rendering is not affected
since there is no viewBox support during painting yet.

* Source/WebCore/rendering/RenderLayerModelObject.cpp:
(WebCore::RenderLayerModelObject::layerTransform const):
* Source/WebCore/rendering/RenderLayerModelObject.h:
* Source/WebCore/rendering/svg/RenderSVGRoot.cpp:
(WebCore::RenderSVGRoot::updateLayoutSizeIfNeeded):
(WebCore::RenderSVGRoot::layout):
(WebCore::RenderSVGRoot::layoutChildren):
(WebCore::RenderSVGRoot::updateFromStyle):
(WebCore::RenderSVGRoot::updateLayerTransform):
(WebCore::RenderSVGRoot::clippedOverflowRect const):
(WebCore::RenderSVGRoot::computeViewportSize const):
(WebCore::RenderSVGRoot::overflowClipRect const):
(WebCore::RenderSVGRoot::absoluteRects const):
(WebCore::RenderSVGRoot::absoluteQuads const):
(WebCore::RenderSVGRoot::updateLayerInformation): Deleted.
(WebCore::RenderSVGRoot::computeTransformationMatrices): Deleted.
(WebCore::RenderSVGRoot::currentViewportSize const): Deleted.
* Source/WebCore/rendering/svg/RenderSVGRoot.h:
* Source/WebCore/rendering/svg/SVGLayerTransformUpdater.h:
(WebCore::SVGLayerTransformUpdater::SVGLayerTransformUpdater):
(WebCore::SVGLayerTransformUpdater::layerTransformChanged const):
</pre>
----------------------------------------------------------------------
#### dbb74b1c30eb5ddf3473230a46a6f7b929fa7b9c
<pre>
[LBSE] Move the SVGLayerTransformUpdater class in its own file
<a href="https://bugs.webkit.org/show_bug.cgi?id=242682">https://bugs.webkit.org/show_bug.cgi?id=242682</a>

Reviewed by NOBODY (OOPS!).

RenderSVGRoot needs to use SVGLayerTransformUpdater as well in future,
so move the class in its own file.

* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebCore/rendering/svg/RenderSVGContainer.cpp:
(WebCore::SVGLayerTransformUpdater::SVGLayerTransformUpdater): Deleted.
(WebCore::SVGLayerTransformUpdater::~SVGLayerTransformUpdater): Deleted.
* Source/WebCore/rendering/svg/SVGLayerTransformUpdater.h: Added.
(WebCore::SVGLayerTransformUpdater::SVGLayerTransformUpdater):
(WebCore::SVGLayerTransformUpdater::~SVGLayerTransformUpdater):
</pre>

2022-07-13 22:09 UTC, nikolaszimmermann commented
This depends on PR #2360 and PR #2382 and therefore includes them, to be able to test this patch with the CI.

2022-07-14 11:49 UTC, nikolaszimmermann commented
After the last rebase, this only depends on PR 2382 and therefore includes it, to be able to test this patch with the CI. merge-queue is already processing it, will rebase once more, to be able to land it afterwards.

2022-07-14 13:45 UTC, nikolaszimmermann commented
This patch is now independent from other PRs.

2022-07-14 13:49 UTC, rwlbuis commented on Source/WebCore/rendering/svg/RenderSVGTransformableContainer.cpp
> +        setHasSVGTransform();
is this change needed?

2022-07-14 13:51 UTC, rwlbuis requested changes
Note in commit message uny -> any.

2022-07-14 17:22 UTC, nikolaszimmermann commented on Source/WebCore/rendering/svg/RenderSVGTransformableContainer.cpp
> +        setHasSVGTransform();
Consistency, all other call sites use this order (See updateSVGTransformFlags())

2022-07-14 17:36 UTC, rwlbuis approved these changes
LGTM.

2022-07-14 17:48 UTC, nikolaszimmermann commented
> Note in commit message uny -> any.
Will push that change and invoke merge-queue, thanks a lot!

2022-07-14 18:26 UTC, merged

2022-07-14 18:26 UTC, webkit-commit-queue commented
Committed 252466@main (0113dff599ec): <https://commits.webkit.org/252466@main>

Reviewed commits have been landed. Closing PR #2383 and removing active labels.