Change install location of WebKit process extensions
WebKit/WebKit pull request #24033
Opened 2024-02-07 21:59 UTC by pvollan

#### 077e30931fcc19a9da69f585c9a0e186df7d6a6b
<pre>
Change install location of WebKit process extensions
<a href="https://bugs.webkit.org/show_bug.cgi?id=268946">https://bugs.webkit.org/show_bug.cgi?id=268946</a>
<a href="https://rdar.apple.com/122422447">rdar://122422447</a>

Reviewed by NOBODY (OOPS!).

* Source/WebKit/Configurations/BaseExtension.xcconfig:
</pre>

2024-02-07 23:34 UTC, emw-apple approved these changes

2024-02-08 00:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/077e30931fcc19a9da69f585c9a0e186df7d6a6b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-08 04:53 UTC, pvollan commented
Thanks for reviewing!

2024-02-08 23:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a74f5a8ee98f32ecac1b900a525d73f31aa0e636. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-09 19:43 UTC, emw-apple requested changes
I think you can do this with `create-symlink-to-altroot.sh` instead of adding a bespoke script (which hardcodes the OS cryptex path…). I'd prefer we integrate with our existing logic here!

You'd need to add a "Create Symlink to Alt Root Path" script phase to each extension target (can copy from WebKit), and the following build settings:
```
ALTERNATE_ROOT_PATH = $(WK_ALTERNATE_WEBKIT_SDK_PATH)$(SYSTEM_LIBRARY_DIR)/ExtensionKit/Extensions

OUTPUT_ALTERNATE_ROOT_PATH = $(OUTPUT_ALTERNATE_ROOT_PATH_$(USE_SYSTEM_CONTENT_PATH)_$(WK_NOT_$(WK_USE_OVERRIDE_FRAMEWORKS_DIR)));
OUTPUT_ALTERNATE_ROOT_PATH_YES_YES = $(DSTROOT)$(ALTERNATE_ROOT_PATH)/$(FULL_PRODUCT_NAME);
```

2024-02-10 02:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3226d5f76d8d46097493caa44b520488db599037. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-10 02:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5853457c58f72ddb82a7941f090c0f27232210f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-10 02:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/da8fb98a133aa62b909b230f4375af2468105255. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-10 05:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7d2ff6d6d7d5591c7844baaa3f1d8e302f8027d9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-10 05:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1b1cb1cd214db06aa58b9efff33dd0c8750711ef. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24033

2024-02-10 19:30 UTC, emw-apple approved these changes

2024-02-10 20:29 UTC, pvollan commented
Thanks for reviewing!

2024-02-10 20:35 UTC, webkit-commit-queue commented
Committed 274425@main (994eca410af6): <https://commits.webkit.org/274425@main>

Reviewed commits have been landed. Closing PR #24033 and removing active labels.

2024-02-10 20:35 UTC, merged