[GStreamer][WPE] Replace platform ifdefs with runtime quirks
WebKit/WebKit pull request #24337
Opened 2024-02-13 11:45 UTC by philn

#### 2caf487d7880d7065f76f4d86fd05ab268c534f9
<pre>
[GStreamer][WPE] Replace platform ifdefs with runtime quirks
<a href="https://bugs.webkit.org/show_bug.cgi?id=269287">https://bugs.webkit.org/show_bug.cgi?id=269287</a>

Reviewed by NOBODY (OOPS!).

Compile-time quirks prevent re-usability of the same binaries across different platforms (using
containers). The proposed solution is to always compile those, they don&apos;t depend on any specific
APIs so that shouldn&apos;t be an issue. Then at runtime quirks can be tweaked using the
WEBKIT_GST_QUIRKS and WEBKIT_GST_HOLE_PUNCH environment variables.

* Source/WebCore/platform/SourcesGStreamer.txt:
* Source/WebCore/platform/audio/gstreamer/AudioDestinationGStreamer.cpp:
(WebCore::AudioDestinationGStreamer::AudioDestinationGStreamer):
* Source/WebCore/platform/audio/gstreamer/AudioFileReaderGStreamer.cpp:
(WebCore::decodebinAutoplugSelectCallback):
(WebCore::AudioFileReader::~AudioFileReader):
(WebCore::AudioFileReader::decodeAudioForBusCreation):
* Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp:
(WebCore::ensureGStreamerInitialized):
(WebCore::registerWebKitGStreamerElements):
* Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp:
(WebCore::GStreamerRegistryScanner::ElementFactories::ElementFactories):
(WebCore::GStreamerRegistryScanner::ElementFactories::hasElementForCaps const):
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp:
(WebCore::MediaPlayerPrivateGStreamer::MediaPlayerPrivateGStreamer):
(WebCore::MediaPlayerPrivateGStreamer::createAudioSink):
(WebCore::MediaPlayerPrivateGStreamer::naturalSize const):
(WebCore::MediaPlayerPrivateGStreamer::handleMessage):
(WebCore::MediaPlayerPrivateGStreamer::configureElement):
(WebCore::MediaPlayerPrivateGStreamer::configureElementPlatformQuirks):
(WebCore::MediaPlayerPrivateGStreamer::createGSTPlayBin):
(WebCore::MediaPlayerPrivateGStreamer::swapBuffersIfNeeded):
(WebCore::setRectangleToVideoSink):
(WebCore::MediaPlayerPrivateGStreamer::isHolePunchRenderingEnabled const):
(WebCore::MediaPlayerPrivateGStreamer::createHolePunchVideoSink):
(WebCore::MediaPlayerPrivateGStreamer::shouldIgnoreIntrinsicSize):
(WebCore::MediaPlayerPrivateGStreamer::createVideoSink):
* Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h:
* Source/WebCore/platform/gstreamer/GStreamerHolePunchQuirkBcmNexus.cpp: Added.
(WebCore::GStreamerHolePunchQuirkBcmNexus::setHolePunchVideoRectangle):
* Source/WebCore/platform/gstreamer/GStreamerHolePunchQuirkBcmNexus.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerHolePunchQuirkWesteros.cpp: Added.
(WebCore::GStreamerHolePunchQuirkWesteros::createHolePunchVideoSink):
(WebCore::GStreamerHolePunchQuirkWesteros::setHolePunchVideoRectangle):
* Source/WebCore/platform/gstreamer/GStreamerHolePunchQuirkWesteros.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirkAmLogic.cpp: Added.
(WebCore::GStreamerQuirkAmLogic::GStreamerQuirkAmLogic):
(WebCore::GStreamerQuirkAmLogic::createWebAudioSink):
(WebCore::GStreamerQuirkAmLogic::configureElement):
* Source/WebCore/platform/gstreamer/GStreamerQuirkAmLogic.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirkBcmNexus.cpp: Added.
(WebCore::GStreamerQuirkBcmNexus::GStreamerQuirkBcmNexus):
(WebCore::GStreamerQuirkBcmNexus::isHardwareAccelerated):
* Source/WebCore/platform/gstreamer/GStreamerQuirkBcmNexus.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirkBroadcom.cpp: Added.
(WebCore::GStreamerQuirkBroadcom::GStreamerQuirkBroadcom):
(WebCore::GStreamerQuirkBroadcom::configureElement):
(WebCore::GStreamerQuirkBroadcom::isHardwareAccelerated):
* Source/WebCore/platform/gstreamer/GStreamerQuirkBroadcom.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirkRealtek.cpp: Added.
(WebCore::GStreamerQuirkRealtek::GStreamerQuirkRealtek):
(WebCore::GStreamerQuirkRealtek::createWebAudioSink):
(WebCore::GStreamerQuirkRealtek::configureElement):
(WebCore::GStreamerQuirkRealtek::isHardwareAccelerated):
* Source/WebCore/platform/gstreamer/GStreamerQuirkRealtek.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp: Added.
(WebCore::GStreamerQuirkWesteros::GStreamerQuirkWesteros):
(WebCore::GStreamerQuirkWesteros::configureElement):
(WebCore::GStreamerQuirkWesteros::isHardwareAccelerated):
* Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.h: Added.
* Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp: Added.
(WebCore::GStreamerQuirksManager::singleton):
(WebCore::GStreamerQuirksManager::GStreamerQuirksManager):
(WebCore::GStreamerQuirksManager::isEnabled const):
(WebCore::GStreamerQuirksManager::createWebAudioSink):
(WebCore::GStreamerQuirksManager::createHolePunchVideoSink):
(WebCore::GStreamerQuirksManager::setHolePunchVideoRectangle):
(WebCore::GStreamerQuirksManager::configureElement):
(WebCore::GStreamerQuirksManager::isHardwareAccelerated const):
(WebCore::GStreamerQuirksManager::supportsVideoHolePunchRendering const):
(WebCore::GStreamerQuirksManager::audioVideoDecoderFactoryListType const):
(WebCore::GStreamerQuirksManager::disallowedWebAudioDecoders const):
* Source/WebCore/platform/gstreamer/GStreamerQuirks.h: Added.
(WebCore::GStreamerQuirk::isPlatformSupported const):
(WebCore::GStreamerQuirk::createWebAudioSink):
(WebCore::GStreamerQuirk::configureElement):
(WebCore::GStreamerQuirk::isHardwareAccelerated):
(WebCore::GStreamerQuirk::audioVideoDecoderFactoryListType const):
(WebCore::GStreamerQuirk::disallowedWebAudioDecoders const):
(WebCore::GStreamerHolePunchQuirk::createHolePunchVideoSink):
(WebCore::GStreamerHolePunchQuirk::setHolePunchVideoRectangle):
* Source/cmake/OptionsWPE.cmake:
</pre>

2024-02-13 11:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2caf487d7880d7065f76f4d86fd05ab268c534f9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-02-13 13:52 UTC, aperezdc reviewed
I like where this is going, and the reduction of build-time options is very welcome 👏🏼 &mdash; I left only a small comment, because somebody more familiar with our GStreamer multimedia code should take a look, too.

2024-02-13 13:52 UTC, aperezdc commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +        UNUSED_VARIABLE(quirksManager);
Any reason to not go with `maybe_unused`?

```suggestion
        [[maybe_unused]] auto& quirksManager = GStreamerQuirksManager::singleton();
```

2024-02-13 14:55 UTC, philn commented on Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.cpp
> +        UNUSED_VARIABLE(quirksManager);
No special reason :)

2024-03-07 12:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ea69f4577d1cd6cc994bfedfdd5f478f0d49468d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-12 16:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f9675d3990875cf6b967a1c2a4280ed0cc4a8d4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-13 09:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ba326c4ac150e6954c1dc568128f58ea4bb1ee12. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-13 10:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/31ad3cfe93119c12225a221dab434abd65b19dc2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-13 13:01 UTC, calvaris requested changes
You forgot at least `USE(WESTEROS_SINK)` so we'll have to fix this.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +        if (GST_CLOCK_TIME_IS_VALID(videoPosition) && (!GST_CLOCK_TIME_IS_VALID(gstreamerPosition) || (m_playbackRate >= 0 && videoPosition > gstreamerPosition) || (m_playbackRate < 0 && videoPositio
this line is too long

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
> +            this);
This can be the same line, no need to change.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirkAmLogic.cpp
> +    ASSERT_WITH_MESSAGE(sink, "amlhalasink should be available in the system but it is not");
I would do this RELEASE_ASSERT . It's a big configuration problem, enough to crash.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirkRealtek.cpp
> +    ASSERT_WITH_MESSAGE(sink, "rtkaudiosink should be available in the system but it is not");
ditto

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp
> +    gst_object_unref(gst_plugin_feature_load(GST_PLUGIN_FEATURE(westerosFactory.get())));
I think it would be more elegant to just use a smart ptr here but no strong opinion.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp
> +    for (auto* t = gst_element_factory_get_static_pad_templates(westerosFactory.get()); t; t = g_list_next(t)) {
/me dreams with a c++ iterator for GList.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp
> +        defaultCaps = adoptGRef(gst_caps_merge(gst_caps_ref(m_sinkCaps.get()), defaultCaps.leakRef()));
I like this line, it's like a textbook exercise of GRefPtr. Right or wrong? I think it is right!

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +        }
Let's ASSERT_NOT_REACHED here.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +                GST_WARNING("Unknown quirk requested: %s. Skipping", identifier.toStringWithoutCopying().ascii().data());
Let's ASSERT_NOT_REACHED here.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +                GST_WARNING("Quirk %s was requested but is not supported on this platform. Skipping", quirk->identifier());
ditto.

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +    }
ditto

2024-03-13 13:01 UTC, calvaris commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +        GST_WARNING("HolePunch quirk %s un-supported.", identifier.toStringWithoutCopying().ascii().data());
ditto

2024-03-13 13:23 UTC, philn commented on Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp
> +    gst_object_unref(gst_plugin_feature_load(GST_PLUGIN_FEATURE(westerosFactory.get())));
I wasn't confident touching this code from the original ifdefs.

2024-03-13 13:24 UTC, philn commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +        }
Why?

2024-03-13 13:24 UTC, philn commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +                GST_WARNING("Unknown quirk requested: %s. Skipping", identifier.toStringWithoutCopying().ascii().data());
Why?

2024-03-13 13:24 UTC, philn commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +                GST_WARNING("Quirk %s was requested but is not supported on this platform. Skipping", quirk->identifier());
ditto :)

2024-03-13 13:25 UTC, philn commented on Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
> +    }
I don't see the point of asserting in these places. They're valid code paths, not unexpected behaviours.

2024-03-13 13:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f569216b44195726381957b9e474177139981ce. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-13 15:46 UTC, calvaris approved these changes

2024-03-13 20:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2a0df697326d64c6a63505a30053bd80001b4e82. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24337

2024-03-14 09:33 UTC, webkit-commit-queue commented
Committed 276080@main (5813c1e253b0): <https://commits.webkit.org/276080@main>

Reviewed commits have been landed. Closing PR #24337 and removing active labels.

2024-03-14 09:33 UTC, merged