[GStreamer][VideoCapture] VideoTrackPrivateGStreamer: Assert that we are not on the main thread when we enqueueTask from a callback
WebKit/WebKit pull request #2447
Opened 2022-07-15 08:42 UTC by jameshilliard

#### 9c677e32a2de47db72e977c825e453770e5699fe
<pre>
[GStreamer][VideoCapture] VideoTrackPrivateGStreamer: Assert that we are not on the main thread when we enqueueTask from a callback
<a href="https://bugs.webkit.org/show_bug.cgi?id=242794">https://bugs.webkit.org/show_bug.cgi?id=242794</a>

Reviewed by NOBODY (OOPS!).

This should make threading issues in the callbacks easier to identify.

Also log an error message to make this easier to identify on release builds.

* Source/WebCore/platform/graphics/gstreamer/VideoTrackPrivateGStreamer.cpp:
(WebCore::VideoTrackPrivateGStreamer::VideoTrackPrivateGStreamer):
</pre>
https://github.com/False/commit/9c677e32a2de47db72e977c825e453770e5699fe

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/83335 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/27300 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/14673 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/91363 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/145246 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/87355 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/25625 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/23106 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/75513 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/87911 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/88930 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/20845 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/70866 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/21119 "Passed tests") | 
| | [⏳ 🧪 api-ios](https://ews-build.webkit.org/#/builders/API-Tests-iOS-Simulator-EWS "Waiting to run tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/76734 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/64276 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/23794 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/10589 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/23695 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/11474 "Passed tests") | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3529 "Failed to checkout and rebase branch from PR 2447") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/25263 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/34612 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/25199 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/30851 "Passed tests") | |

2022-07-15 10:03 UTC, calvaris requested changes
I think an ASSERT is enough. I don't think it is good to assert in release mode.

2022-07-15 16:36 UTC, jameshilliard commented
> I don't think it is good to assert in release mode.

Well hitting the assert conditions seems to trigger a severe resource leak so I'm thinking probably a good idea to assert in release mode as it's otherwise somewhat non-obvious that there's an issue coming from this callback as the resource leak typically won't immediately be noticeable otherwise. Maybe keep it in release mode until we're fairly confident the triggering conditions have been eliminated?

2022-07-18 09:21 UTC, calvaris commented
> Well hitting the assert conditions seems to trigger a severe resource leak so I'm thinking probably a good idea to assert in release mode as it's otherwise somewhat non-obvious that there's an issue coming from this callback as the resource leak typically won't immediately be noticeable otherwise. Maybe keep it in release mode until we're fairly confident the triggering conditions have been eliminated?

No. Asserting on release should be only for trully fatal errors that can lead to a disaster. A resource leak does not sound like that and can lead to a terrible user experience if this is not fixed before the next release. Let's just assert on debug, as requested, and you can keep that locally if you need to debug in release mode.

2022-07-18 09:46 UTC, jameshilliard commented
> errors that can lead to a disaster

Well...it seems to usually lead to that fairly quickly from my testing.

> A resource leak does not sound like that and can lead to a terrible user experience if this is not fixed before the next release.

It's a pretty bad leak, browser effectively fails fairly quickly a lot of the time due to resource exhaustion.

> Let's just assert on debug, as requested, and you can keep that locally if you need to debug in release mode.

Maybe we should log an error in both release and debug along with the debug assert?

2022-07-19 06:03 UTC, calvaris commented
> > Let's just assert on debug, as requested, and you can keep that locally if you need to debug in release mode.
> 
> Maybe we should log an error in both release and debug along with the debug assert?

This sounds reasonable.

2022-07-20 06:26 UTC, calvaris approved these changes

2022-07-21 02:16 UTC, jameshilliard commented
So this issue was preventing the capture pipeline from stopping, see #2605.

2022-10-22 17:20 UTC, Ahmad-S792 commented
Removing - merge-queue since this needs to be rebased before it can be merged.

2022-10-22 17:26 UTC, jameshilliard commented
Closing as superseded by #2605.

2022-10-22 17:26 UTC, closed without merging