[GTK][WPE] Revamp focus rings
WebKit/WebKit pull request #2450
Opened 2022-07-15 16:11 UTC by Exalm

https://github.com/WebKit/WebKit/commit/7b0b46471b84e160998f0497e224ad1a0eddef21

```
https://bugs.webkit.org/show_bug.cgi?id=241228

Reviewed by NOBODY (OOPS!).

Use semi-transparent accent-colored focus rings, like macOS or GTK4.
Round them for radios and scales. Make sure to support CSS accent-color
for checks, radios and scales.

Use the same opacity as the libadwaita high contrast style and not the
regular one - the regular one doesn't work well on colorful backgrounds
like most webpages. This is also closer to the macOS style.

Make ThemeAdwaita::focusColor() private as it's both unused and doesn't
make much sense to be called from outside anymore.

This should fix the issue with modern media controls turning black
when focused.

* Source/WebCore/platform/adwaita/ThemeAdwaita.cpp:
(WebCore::ThemeAdwaita::focusColor):
(WebCore::getRectRadius):
(WebCore::ThemeAdwaita::paintFocus):
(WebCore::ThemeAdwaita::paintCheckbox):
(WebCore::ThemeAdwaita::paintRadio):
(WebCore::ThemeAdwaita::paintButton):
* Source/WebCore/platform/adwaita/ThemeAdwaita.h:
* Source/WebCore/rendering/RenderElement.cpp:
(WebCore::usePlatformFocusRingColorForOutlineStyleAuto):
(WebCore::useShrinkWrappedFocusRingForOutlineStyleAuto):
* Source/WebCore/rendering/RenderThemeAdwaita.cpp:
(WebCore::RenderThemeAdwaita::platformFocusRingColor const):
(WebCore::RenderThemeAdwaita::systemColor const):
(WebCore::RenderThemeAdwaita::paintTextField):
(WebCore::RenderThemeAdwaita::paintMenuList):
(WebCore::RenderThemeAdwaita::paintSliderTrack):
```

2022-07-15 16:14 UTC, Exalm commented
Looks like I don't have access to add labels or assign myself, as the template says.

2022-07-15 16:15 UTC, Exalm commented
(I opened this one manually since `git-webkit pr` just hanged)

2022-07-18 06:42 UTC, carlosgcampos requested changes
Looks good to me.

2022-07-18 06:42 UTC, carlosgcampos commented on Source/WebCore/platform/adwaita/ThemeAdwaita.cpp
> +        radius = 2;
```suggestion
    float radius = round ? getRectRadius(rect, offset) : 2;
```

2022-07-18 06:42 UTC, carlosgcampos commented on Source/WebCore/platform/adwaita/ThemeAdwaita.cpp
> +            radius = 2;
```suggestion
        float radius = round ? getRectRadius(rect, 0) : 2;
```

2022-07-18 06:42 UTC, carlosgcampos commented on Source/WebCore/platform/adwaita/ThemeAdwaita.h
> +    static void paintFocus(GraphicsContext&, const Vector<FloatRect>&, const Color&, bool round = false);
I would use an enum here instead of a boolean, for example:

enum class PaintRounded : bool { No, Yes };

2022-07-19 07:54 UTC, carlosgcampos approved these changes

2022-07-19 13:35 UTC, merged

2022-07-19 13:35 UTC, webkit-commit-queue commented
Committed 252596@main (c63818df574b): <https://commits.webkit.org/252596@main>

Reviewed commits have been landed. Closing PR #2450 and removing active labels.