[Cocoa] Add more PlatformColor tests
WebKit/WebKit pull request #24693
Opened 2024-02-18 01:01 UTC by ddkilzer

#### 2254e4ab72ae0dd597bf7f98a3cfcbde1b5ccf3d
<pre>
[Cocoa] Add more PlatformColor tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=269652">https://bugs.webkit.org/show_bug.cgi?id=269652</a>
&lt;<a href="https://rdar.apple.com/123166372">rdar://123166372</a>&gt;

Reviewed by NOBODY (OOPS!).

* Source/WebCore/PAL/pal/spi/ios/UIKitSPI.h:
- Switch to use private header to define methods on internal SDKs.
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
- Make UIFoundationSoftLink.h a private header for use in TestWebKitAPI
  project.
* Source/WebCore/editing/cocoa/AttributedString.h:
(PlatformNSColor): Add.
(PlatformNSColorClass):
- Fix definition of PlatformNSColorClass and add PlatformNSColor.  These
  are identical to PlatformColor[Class] on macOS, but different on iOS
  Family.
* Source/WebCore/platform/ios/UIFoundationSoftLink.mm:
- Export WebCore::getNSColorClass() for use in TestWebKitAPI.
* Tools/TestWebKitAPI/TestWebKitAPI.xcodeproj/project.pbxproj:
- Add CocoaColorTests.mm.
* Tools/TestWebKitAPI/Tests/IPC/IPCSerialization.mm:
(wkCocoaPlatformColor_isEqual): Add.
(wkNSShadow_isEqual): Add.
(operator==):
- Add/swizzle -isEqual: methods for PlatformColor, PlatformNSColor and
  NSShadow to properly handle comparison of the many subclasses of
  PlatformColor and PlatformNSColor.
(TEST(IPCSerialization, NSShadow)):
- Add more tests with different PlatformColor and PlatformNSColor
  variations.
(TEST(IPCSerialization, Platform_CocoaColor)): Add.
(TEST(IPCSerialization, Platform_NSColor_calibrated)): Add.
- Add serialization tests for PlatformColor and PlatformNSColor.
* Tools/TestWebKitAPI/Tests/WebCore/cocoa/CocoaColorTests.mm: Add.
(TEST(Color, Platform_Color)):
(TEST(Color, Platform_NSColor)):
- Add tests to convert from PlatformColor and PlatformNSColor to
  WebCore::Color to PlatformColor and back to WebCore::Color.
</pre>

2024-02-18 01:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2254e4ab72ae0dd597bf7f98a3cfcbde1b5ccf3d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24693

2024-02-18 18:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/08bdf5fdda05b53667bcb83687dc17aceb254048. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24693

2024-02-19 20:13 UTC, achristensen07 requested changes
I don't think this is needed, but happy to chat in person.

2024-02-22 23:33 UTC, ddkilzer commented
Closing this after discussing it with Alex.  If there are issues in PlatformCocoaColor classes, tests should be aimed at specific bugs (not general Cocoa ->`WebCore::Color`->Cocoa translation), and not in IPC Serialization tests.

2024-02-22 23:33 UTC, ddkilzer commented
Closing this after discussing it with Alex.  If there are issues in PlatformCocoaColor classes, tests should be aimed at specific bugs (not general Cocoa ->`WebCore::Color`->Cocoa translation), and not in IPC Serialization tests.

2024-02-22 23:33 UTC, closed without merging