[JSC] Different @@species getter for each constructor
WebKit/WebKit pull request #24705
Opened 2024-02-18 08:51 UTC by sosukesuzuki

#### 9c99737fd2d825b16daf7e8931842b4d2a2c4448
<pre>
[JSC] Different @@species getter for each constructor
<a href="https://bugs.webkit.org/show_bug.cgi?id=267039">https://bugs.webkit.org/show_bug.cgi?id=267039</a>

Reviewed by NOBODY (OOPS!).

In JavaScriptCore, `Object.getOwnPropertyDescriptor(Array, Symbol.species).get === Object.getOwnPropertyDescriptor(RegExp, Symbol.species).get` evaluates to true.
This patch change the @@species getters of each constructor to be different objects, so that the result of this expression becomes false.
Remove the global `m_speciesGetterSetter` and create `m_arraySpeciesGetterSetter` and `m_regExpSpeciesGetterSetter` and ... for each constructor.
Instead of passing the `GetterSetter*` type values as arguments to the create function of each constructor, refer to them from the `globalObject`.

* JSTests/stress/species-equivalence-typedarray.js: Added.
(shouldBe):
(readTypedArraySymbolSpeciesGetter):
(runTest):
* JSTests/stress/species-equivalence.js: Added.
(shouldNotBe):
(readSymbolSpeciesGetter):
(runTest):
* Source/JavaScriptCore/runtime/ArrayConstructor.cpp:
(JSC::ArrayConstructor::finishCreation):
* Source/JavaScriptCore/runtime/ArrayConstructor.h:
* Source/JavaScriptCore/runtime/BigIntConstructor.h:
* Source/JavaScriptCore/runtime/BooleanConstructor.cpp:
(JSC::BooleanConstructor::create):
* Source/JavaScriptCore/runtime/BooleanConstructor.h:
* Source/JavaScriptCore/runtime/DateConstructor.h:
* Source/JavaScriptCore/runtime/ErrorConstructor.h:
* Source/JavaScriptCore/runtime/FinalizationRegistryConstructor.h:
* Source/JavaScriptCore/runtime/JSArrayBufferConstructor.cpp:
(JSC::JSGenericArrayBufferConstructor&lt;sharingMode&gt;::finishCreation):
* Source/JavaScriptCore/runtime/JSArrayBufferConstructor.h:
* Source/JavaScriptCore/runtime/JSGlobalObject.cpp:
(JSC::JSGlobalObject::init):
(JSC::JSGlobalObject::visitChildrenImpl):
(JSC::JSGlobalObject::tryInstallSpeciesWatchpoint):
(JSC::JSGlobalObject::installArraySpeciesWatchpoint):
(JSC::JSGlobalObject::tryInstallArrayBufferSpeciesWatchpoint):
(JSC::JSGlobalObject::tryInstallTypedArraySpeciesWatchpoint):
(JSC::JSGlobalObject::installTypedArrayConstructorSpeciesWatchpoint):
* Source/JavaScriptCore/runtime/JSGlobalObject.h:
(JSC::JSGlobalObject::arraySpeciesGetterSetter const):
(JSC::JSGlobalObject::typedArraySpeciesGetterSetter const):
(JSC::JSGlobalObject::regExpSpeciesGetterSetter const):
(JSC::JSGlobalObject::mapSpeciesGetterSetter const):
(JSC::JSGlobalObject::setSpeciesGetterSetter const):
(JSC::JSGlobalObject::promiseSpeciesGetterSetter const):
(JSC::JSGlobalObject::speciesGetterSetter const): Deleted.
* Source/JavaScriptCore/runtime/JSGlobalObjectInlines.h:
(JSC::JSGlobalObject::arrayBufferSpeciesGetterSetter const):
* Source/JavaScriptCore/runtime/JSInternalPromiseConstructor.cpp:
(JSC::JSInternalPromiseConstructor::create):
* Source/JavaScriptCore/runtime/JSInternalPromiseConstructor.h:
* Source/JavaScriptCore/runtime/JSPromiseConstructor.cpp:
(JSC::JSPromiseConstructor::create):
(JSC::JSPromiseConstructor::finishCreation):
* Source/JavaScriptCore/runtime/JSPromiseConstructor.h:
* Source/JavaScriptCore/runtime/JSTypedArrayViewConstructor.cpp:
(JSC::JSTypedArrayViewConstructor::finishCreation):
* Source/JavaScriptCore/runtime/JSTypedArrayViewConstructor.h:
* Source/JavaScriptCore/runtime/MapConstructor.cpp:
(JSC::MapConstructor::finishCreation):
* Source/JavaScriptCore/runtime/MapConstructor.h:
* Source/JavaScriptCore/runtime/NumberConstructor.cpp:
(JSC::NumberConstructor::create):
* Source/JavaScriptCore/runtime/NumberConstructor.h:
* Source/JavaScriptCore/runtime/RegExpConstructor.cpp:
(JSC::RegExpConstructor::finishCreation):
* Source/JavaScriptCore/runtime/RegExpConstructor.h:
* Source/JavaScriptCore/runtime/SetConstructor.cpp:
(JSC::SetConstructor::finishCreation):
* Source/JavaScriptCore/runtime/SetConstructor.h:
* Source/JavaScriptCore/runtime/ShadowRealmConstructor.h:
* Source/JavaScriptCore/runtime/StringConstructor.cpp:
(JSC::StringConstructor::create):
* Source/JavaScriptCore/runtime/StringConstructor.h:
* Source/JavaScriptCore/runtime/SymbolConstructor.h:
* Source/JavaScriptCore/runtime/WeakMapConstructor.h:
* Source/JavaScriptCore/runtime/WeakObjectRefConstructor.h:
* Source/JavaScriptCore/runtime/WeakSetConstructor.h:
</pre>

2024-02-18 08:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9c99737fd2d825b16daf7e8931842b4d2a2c4448. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24705

2024-02-19 15:38 UTC, kmiller68 requested changes
Thanks for the patch! I have one comment.

2024-02-19 15:38 UTC, kmiller68 commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    macro(JSPromise, promise) \
I think we don't need these saved on the global object as we don't watchpoint them so we should save a little memory. Can you construct these in the respective finishCreation instead?

2024-02-19 16:33 UTC, sosukesuzuki commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    macro(JSPromise, promise) \
Thank you for your review! Like this?

```diff
void RegExpConstructor::finishCreation(VM& vm, RegExpPrototype* regExpPrototype)
{
    Base::finishCreation(vm, 2, vm.propertyNames->RegExp.string(), PropertyAdditionMode::WithoutStructureTransition);
    ASSERT(inherits(info()));

    putDirectWithoutTransition(vm, vm.propertyNames->prototype, regExpPrototype, PropertyAttribute::DontEnum | PropertyAttribute::DontDelete | PropertyAttribute::ReadOnly);
-   putDirectNonIndexAccessorWithoutTransition(vm, vm.propertyNames->speciesSymbol, globalObject->regExpSpeciesGetterSetter(), PropertyAttribute::Accessor | PropertyAttribute::ReadOnly | PropertyAttribute::DontEnum);
+   GetterSetter* speciesGetterSetter = GetterSetter::create(vm, globalObject, JSFunction::create(vm, globalObject, 0, "get [Symbol.species]"_s, globalFuncSpeciesGetter, ImplementationVisibility::Public, SpeciesGetterIntrinsic), nullptr);
+   putDirectNonIndexAccessorWithoutTransition(vm, vm.propertyNames->speciesSymbol, speciesGetterSetter, PropertyAttribute::Accessor | PropertyAttribute::ReadOnly | PropertyAttribute::DontEnum)
;
```

2024-02-19 16:41 UTC, sosukesuzuki commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    macro(JSPromise, promise) \
We need to pass an instance of `speciesGetterSetter` as an argument to `tryInstallSpeciesWatchpoint`. If we create them in `finishCreation`, how can we get that instance from the global object side?

https://github.com/WebKit/WebKit/blob/9c99737fd2d825b16daf7e8931842b4d2a2c4448/Source/JavaScriptCore/runtime/JSGlobalObject.cpp#L2770

2024-02-19 17:17 UTC, hyjorc1 commented
From the commit message:
> This patch change the @@species getters of each constructor to be different objects ...

change -> changes

2024-02-19 18:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9149ee93ab27819dba2c37a2495d8148445f1a62. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24705

2024-02-19 18:55 UTC, kmiller68 commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    macro(JSPromise, promise) \
That code looks right.

Just for the ones that aren't passed to `tryInstallSpeciesWatchpoint`, namely for RegExp, Map, Set, and Promise.

2024-02-19 19:43 UTC, sosukesuzuki commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    macro(JSPromise, promise) \
Thank you! Updated

2024-02-19 19:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/08b3b8262aef2a2d6da0f6e2499c7ac7f89413a5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24705

2024-02-20 15:53 UTC, kmiller68 requested changes
One minor change otherwise LGTM.

2024-02-20 15:53 UTC, kmiller68 commented on Source/JavaScriptCore/runtime/JSGlobalObject.h
> +    inline GetterSetter *arrayBufferSpeciesGetterSetter(ArrayBufferSharingMode) const;
Should be: `inline GetterSetter* arrayBufferSpeciesGetterSetter(ArrayBufferSharingMode) const;`

2024-02-20 16:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/06a33afe5b8ad64adb9587a0895c11f88e1341d2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24705

2024-02-20 16:55 UTC, kmiller68 approved these changes
r=me.

2024-02-20 16:57 UTC, kmiller68 commented
Ping me if you when you're ready for me to commit queue this.

2024-02-20 17:02 UTC, sosukesuzuki commented
@kmiller68 Thank you for letting me know. I'm ready on my end, but we might need to wait for the CI to complete? This is my first PR to WebKit so I'm not familiar with the process yet.

2024-02-20 17:03 UTC, kmiller68 commented
No worries. `safe-merge-queue` label will wait for CI to finish before merging. Thanks again for the patch!

2024-02-20 21:16 UTC, webkit-commit-queue commented
Committed 275064@main (d91d519d4b06): <https://commits.webkit.org/275064@main>

Reviewed commits have been landed. Closing PR #24705 and removing active labels.

2024-02-20 21:16 UTC, merged