Add invoke defaults for popovers and dialogs
WebKit/WebKit pull request #24707
Opened 2024-02-18 10:52 UTC by keithamus

```
Add invoke defaults for popovers and dialogs
https://bugs.webkit.org/show_bug.cgi?id=263513

Reviewed by NOBODY (OOPS!).

This adds the `handleInvokeInternal` logic to show/hide popovers on
HTMLElement, and the `handleInvokeInternal` logic for HTMLDialogElement
t showmodal/close a dialog.

* LayoutTests/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-dialog-behavior.tentative-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-dialog-behavior.tentative.html: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-popover-behavior.tentative-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-popover-behavior.tentative.html:
* Source/WebCore/html/HTMLDialogElement.cpp:
(WebCore::HTMLDialogElement::handleInvokeInternal):
* Source/WebCore/html/HTMLDialogElement.h:
* Source/WebCore/html/HTMLElement.cpp:
(WebCore::HTMLElement::handleInvokeInternal):
* Source/WebCore/html/HTMLElement.h:
(WebCore::HTMLElement::handleInvokeInternal): Deleted.
* Source/WebCore/html/HTMLFormControlElement.cpp:
(WebCore::HTMLFormControlElement::handleInvokeAction):

```

2024-02-18 10:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a9ba08ffe39cae4b83d8e4f35175b47a4277f706. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 15:24 UTC, lukewarlow commented on Source/WebCore/html/HTMLDialogElement.cpp
> +    bool shouldClose = equalIgnoringASCIICase(action, "auto"_s) ||
should be `autoAtom()` instead of "auto"_s

2024-02-18 15:25 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    bool shouldShowPopover = equalIgnoringASCIICase(action, "auto"_s) ||
ditto. Should also declare atom strings for the other values.

2024-02-18 15:31 UTC, lukewarlow commented
You're missing a change to Document::handlePopoverLightDismiss aswell which I think is probably partially the cause of the failing tests

2024-02-18 15:43 UTC, lukewarlow commented
I happened to implement the popover defaults today before I saw you were doing it. Here's my branch https://github.com/webkit/webKit/compare/lukewarlow:invokers-popover-defaults which includes the light dismiss fix.

2024-02-18 16:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4998085b548935361124f0a6bff3815ebfd0a105. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 16:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ddd90d25aa408e282f3f1cbf49412c55761a901. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 17:02 UTC, lukewarlow commented on LayoutTests/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-popover-behavior.tentative-expected.txt
> +PASS invoking (as auto) closed popover opens
Are you able to now remove the additional expected file specific to ios?

2024-02-18 17:49 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    auto popoverState = popoverData();
nit: maybe call this popoverData so it's not confused with `popoverState()`

2024-02-18 17:58 UTC, lukewarlow commented
FocusController.cpp includes a reference to popoverTargetElement() inside of `invokerForPopoverShowingState` so it might be worth investigating that and changing as appropriate.

2024-02-18 18:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/933a439b7fa7b2f8b6f09375a5719a3f26577b95. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 18:24 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    if (popoverState && popoverState->visibilityState() == PopoverVisibilityState::Hidden && shouldShowPopover) {
Nit this could be:

`if (!isPopoverShowing() && shouldShowPopover)`

2024-02-18 18:25 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    if (popoverState && popoverState->visibilityState() == PopoverVisibilityState::Showing && shouldHidePopover) {
nit this could be:

`if (isPopoverShowing() && shouldHIdePopover)`

2024-02-18 20:49 UTC, lukewarlow commented
If you copy the following files to this branch, (also delete the actual.txt because it's not needed) then this branch should pass these pipelines.

https://github.com/WebKit/WebKit/blob/d8d6b77c7958093cdb822348866022d9da250975/LayoutTests/platform/ios/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-dialog-behavior.tentative-expected.txt

https://github.com/WebKit/WebKit/blob/d8d6b77c7958093cdb822348866022d9da250975/LayoutTests/platform/ios/imported/w3c/web-platform-tests/html/semantics/invokers/invoketarget-on-popover-behavior.tentative-expected.txt

2024-02-18 20:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7236a2c436c6a92a01d44453a7f8a6bb8ffe8180. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 21:00 UTC, lukewarlow commented
https://github.com/WebKit/WebKit/pull/24712 - will cause even more conflicts so might be worth waiting on that to get in and then dealing with conflicts in one go.

2024-02-18 21:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/18ded72e6be8d2ca5b9bbe228109292ba3acacf5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 21:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1d1eaafc9da4aaab964d4629740f17786aefc7f7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 21:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/deab82318dbc1613e3d122e47e234b1e6e9bfdcf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 21:21 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    if (!isPopoverShowing() && shouldShowPopover)
Needs a { on the end

2024-02-18 21:21 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.cpp
> +    if (isPopoverShowing() && shouldHidePopover)
ditto

2024-02-18 21:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bab1143458dbaf49247ac043d7c73ade7f1060d9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-02-18 22:39 UTC, lukewarlow commented
See html/semantics/popovers/resources for some helper files that might allow your popover invoker tests to run properly on iOS (assuming it's a test issue not a code issue).

No need to do in this PR if you don't want but might be useful nonetheless.

2024-02-18 23:21 UTC, lukewarlow commented on Source/WebCore/html/HTMLElement.h
> +    virtual bool handleInvokeInternal(const HTMLFormControlElement* invoker, const AtomString&);
The current change should be moved to the Element.h file.
The below change should be made here.

```suggestion
   bool handleInvokeInternal(const HTMLFormControlElement* invoker, const AtomString&) override;
```

2024-02-18 23:25 UTC, lukewarlow commented on Source/WebCore/dom/Document.cpp
> +                            if (RefPtr popover = button->invokeTargetElement(); popover && isShowingAutoPopover(*popover))
As invokeTargetElement now returns Element we need to dynamicDowncast it to HTMLElement as that's what isShowingAutoPopover() takes.

```suggestion
                            if (RefPtr popover = dynamicDowncast<HTMLElement>(button->invokeTargetElement()); popover && isShowingAutoPopover(*popover))
```

2024-03-06 22:46 UTC, lukewarlow commented
I've pushed up the popover defaults separately in #25553 with the conflicts fixed.

Once that's merged this can be rebased (with it's bug URL changed to https://bugs.webkit.org/show_bug.cgi?id=270602) and can just be dialog changes.

2024-05-15 10:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9d26beb451de0474eeca7d934aaae924e92ea281. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-05-15 10:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c50e6253146f9c21fc0107ab07fa7db4b01120b5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-05-15 12:24 UTC, lukewarlow requested changes

2024-05-15 12:24 UTC, lukewarlow commented on Source/WebCore/html/HTMLFormControlElement.cpp
> +        return InvokeAction::ShowModal;
```suggestion
        return InvokeAction::Close;
```

2024-05-15 13:35 UTC, lukewarlow approved these changes

2024-05-15 13:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ae8ffa589e8f81cec98150d3048fcd1cce4f0d81. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-05-17 11:18 UTC, annevk approved these changes
The iOS test issue needs to be addressed.

Modulo that and modulo the boolean nits this looks reasonable to me.

2024-05-17 11:18 UTC, annevk commented on Source/WebCore/html/HTMLDialogElement.cpp
> +        const bool shouldClose = action == InvokeAction::Auto || action == InvokeAction::Close;
I think this should just be `auto`, maybe `bool`, but not `const`. Same below.

2024-05-17 17:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/apple/WebKit/commit/9d89c303fb118db771c7613313fb69e33abfc3e4. Live statuses available at the PR page, https://github.com/apple/WebKit/pull/24707

2024-05-18 21:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/26243fa2e9282c7396e5eaeff79c1d9782144e31. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/24707

2024-05-18 21:47 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/78b174fe3284a8c9f617c9d99f2b1a80e8578562)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [  ~~🧪 style~~](https://ews-build.webkit.org/#/builders/38/builds/51934 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 ios~~](https://ews-build.webkit.org/#/builders/48/builds/31240 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/55/builds/4297 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/5/builds/55196 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/59/builds/2624 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/9/builds/54240 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 ios-sim~~](https://ews-build.webkit.org/#/builders/49/builds/37620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/2337 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/5/builds/55196 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 wincairo-tests~~](https://ews-build.webkit.org/#/builders/59/builds/2624 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/11/builds/54032 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/49/builds/37620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/55/builds/4297 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/5/builds/55196 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/49/builds/37620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/55/builds/4297 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🛠 wpe-cairo~~](https://ews-build.webkit.org/#/builders/65/builds/815 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/49/builds/37620 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/55/builds/4297 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/44/builds/27050 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/2337 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🧪 services ](https://ews-build.webkit.org/#/builders/Services-EWS "Waiting in queue, processing has not started yet") | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/46/builds/28287 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/55/builds/4297 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [  ~~🛠 watch~~](https://ews-build.webkit.org/#/builders/43/builds/29188 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/45/builds/28024 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | | </details>

2024-05-19 10:51 UTC, webkit-commit-queue commented
Committed 278970@main (dbcbbe87dd98): <https://commits.webkit.org/278970@main>

Reviewed commits have been landed. Closing PR #24707 and removing active labels.

2024-05-19 10:51 UTC, merged