<rdar://96239333> Linker picks up .order files automatically, please do not hardcode their paths
WebKit/WebKit pull request #2488
Opened 2022-07-16 17:42 UTC by ddkilzer

#### 2f7616cf326195428a1580228b3fd0cfe21e63fa
<pre>
&lt;rdar://96239333&gt; Linker picks up .order files automatically, please do not hardcode their paths

Reviewed by NOBODY (OOPS!).

* Source/JavaScriptCore/Configurations/JavaScriptCore.xcconfig:
* Source/WebCore/Configurations/WebCore.xcconfig:
* Source/WebKit/Configurations/WebKit.xcconfig:
* Source/WebKitLegacy/mac/Configurations/WebKitLegacy.xcconfig:
- Remove $(SDKROOT) path from order files for iOS SDK.
- The macOS SDK variants are kept so that their *.order files
  may be removed independently.
</pre>

2022-07-16 18:34 UTC, aproskuryakov requested changes, later dismissed
What's been blocking this (for years) was performance testing. It has to be manual, as we don't have the automation for it.

2022-07-16 18:41 UTC, ddkilzer commented
> What's been blocking this (for years) was performance testing. It has to be manual, as we don't have the automation for it.

If the new (replacement) files are already in place in the SDK (apparently they appear inside a framework bundle, like `WebCore.framework/WebCore.order`), why can't this patch simply be perf tested on a new enough SDK?

The default WebKit build would use the original `*.order` files, and the WebKit build with the patch would use the new `*.order` files in the framework bundles.

2022-07-16 19:54 UTC, aproskuryakov commented
We don't have any perf testing for this, neither pre- nor post-commit.

2022-07-16 19:58 UTC, aproskuryakov commented
Actually, never mind, I didn't look closely enough - this is iOS only.

2022-07-17 03:07 UTC, ddkilzer commented
The "ios-wk2" failure looks like it might be a flakey test?

> Layout test failure:
> 
> - [fast/text/international/system-language/han-text-style.html](https://github.com/WebKit/WebKit/blob/main/LayoutTests/fast/text/international/system-language/han-text-style.html) ([test history](https://results.webkit.org/?suite=layout-tests&test=fast/text/international/system-language/han-text-style.html))

2023-01-10 16:42 UTC, ddkilzer commented
Closing this because I'm unclear what the next steps are, and I'm probably not set up to do the testing myself.

2023-04-12 20:03 UTC, johnwilander approved these changes
r=me

2023-04-12 20:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4e2be51ad68d48a6ac39f2e00100b6960e5fd520. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/2488

2023-04-12 20:59 UTC, webkit-commit-queue commented
Committed 262885@main (2d11fa935f31): <https://commits.webkit.org/262885@main>

Reviewed commits have been landed. Closing PR #2488 and removing active labels.

2023-04-12 21:00 UTC, merged

2023-04-15 03:13 UTC, ddkilzer commented
This was backed out in d249ff68976a9929a9438676f30a39df7b7cda73, but is being relanded with a build fix in <https://github.com/WebKit/WebKit/pull/12767>.