[JSC] Fold empty string + value in bytecode generator
WebKit/WebKit pull request #25002
Opened 2024-02-23 07:26 UTC by Constellation

#### 45f347ec3500982501f0525bd5a821f1fe3addd2
<pre>
[JSC] Fold empty string + value in bytecode generator
<a href="https://bugs.webkit.org/show_bug.cgi?id=269974">https://bugs.webkit.org/show_bug.cgi?id=269974</a>
<a href="https://rdar.apple.com/123492788">rdar://123492788</a>

Reviewed by NOBODY (OOPS!).

This pattern is too much seen in the wild. So let&apos;s do optimization in bytecode generator level since it is too simple.
When we see `&quot;&quot; + value`, we generate `to_string` bytecode for value.

* JSTests/stress/empty-string-add-to-string.js: Added.
(test1):
(test2):
(shouldBe):
* Source/JavaScriptCore/bytecompiler/BytecodeGenerator.cpp:
(JSC::BytecodeGenerator::emitBinaryOp):
</pre>

2024-02-23 07:40 UTC, rkirsling approved these changes
Awesome idea!

2024-02-23 07:56 UTC, shvaikalesh requested changes
Most likely I'm missing here something obvious, yet semantically `"" + x` isn't the same as `@toString(x)`: `+` passes `"default"` hint to `ToPrimitive`, which calls `valueOf` before `toString`, while `@toString(x)` calls them in different order.

2024-02-23 08:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/df099d6be618d3246e97382eb2fb7e6ca04513b0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25002

2024-02-23 08:16 UTC, shvaikalesh approved these changes

2024-02-23 08:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3927396e334a2c46c4b6f5af1db5758fc7d94eda. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25002

2024-02-23 10:26 UTC, merged

2024-02-23 10:26 UTC, webkit-commit-queue commented
Committed 275230@main (4b665f046f0d): <https://commits.webkit.org/275230@main>

Reviewed commits have been landed. Closing PR #25002 and removing active labels.

2024-02-24 19:59 UTC, Jarred-Sumner commented
very nice, minifiers do this everywhere