REGRESSION(274824@main): [MSE][GStreamer][Debug] SHOULD NEVER BE REACHED in MediaPlayerPrivateGStreamerMSE::buffered()
WebKit/WebKit pull request #25012
Opened 2024-02-23 15:21 UTC by obyknovenius

#### 7c773a6d9f372dac89b45f36d4d78eb3b7cb9999
<pre>
REGRESSION(274824@main): [MSE][GStreamer][Debug] SHOULD NEVER BE REACHED in MediaPlayerPrivateGStreamerMSE::buffered()
<a href="https://bugs.webkit.org/show_bug.cgi?id=269988">https://bugs.webkit.org/show_bug.cgi?id=269988</a>

Reviewed by NOBODY (OOPS!).

Since 271111@main, we verify that the `buffered()` method of the
`MediaPlayerPrivateMediaSourceX` classes is never called
because when a `MediaSource` object is in use, the `HTMLMediaElement`
retrieves the buffered directly from it.

While this is true, the `buffered()` method is also used in
`MediaPlayerPrivateInterface::extraMemoryCost().

Since `HTMLMediaElement` has access to `buffered()` now, it is possible
to calculate `extraMemoryCost` directly in
`HTMLMediaElement::pauseAfterDetachedTask()` instead.

* Source/WebCore/html/HTMLMediaElement.cpp:
(WebCore::HTMLMediaElement::pauseAfterDetachedTask):
* Source/WebCore/platform/graphics/MediaPlayer.cpp:
(WebCore::MediaPlayer::totalBytes const):
(WebCore::MediaPlayer::extraMemoryCost const): Deleted.
* Source/WebCore/platform/graphics/MediaPlayer.h:
* Source/WebCore/platform/graphics/MediaPlayerPrivate.h:
(WebCore::MediaPlayerPrivateInterface::extraMemoryCost const): Deleted.
* Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.h:
* Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaSourceAVFObjC.mm:
(WebCore::MediaPlayerPrivateMediaSourceAVFObjC::extraMemoryCost const): Deleted.
* Source/WebCore/platform/graphics/avfoundation/objc/MediaPlayerPrivateMediaStreamAVFObjC.h:
* Source/WebKit/WebProcess/GPU/media/MediaPlayerPrivateRemote.cpp:
(WebKit::MediaPlayerPrivateRemote::extraMemoryCost const): Deleted.
* Source/WebKit/WebProcess/GPU/media/MediaPlayerPrivateRemote.h:
</pre>

2024-02-23 15:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7c773a6d9f372dac89b45f36d4d78eb3b7cb9999. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25012

2024-02-24 04:14 UTC, jyavenard requested changes
this feels very wrong.

The memory used by a MediaSource shouldn't be accounted for the memory of a HTMLMediaElement.
The buffered range is also irrelevant to the memory usage of the HTMLMediaElement when it comes to MSE. The memory size is already accounted by each SourceBuffer.

If it was used by the MediaPlayerPrivateGStreamerMSE, the fix for this issue is to overload extramMemoryCost() like MediaPlayerPrivateMediaSourceAVFObjC or MediaPlayerPlayerMediaStreamAVFObjC and return 0.

In addition using this totalDuration / duration() is a nonsensical value that doesn't represent the memory usage of anything.

It should be ditched IMHO, but that's a different issue altogether

2024-02-26 09:33 UTC, obyknovenius commented
@jyavenard Thank you for your honest review. I am new to MSE and was trying to fix the crash using common sense. I'll modify this PR to only overload `extraMemoryCost()` in `MediaPlayerPrivateGStreamerMSE`, as you suggested.

2024-02-26 10:23 UTC, philn approved these changes

2024-02-26 14:16 UTC, webkit-commit-queue commented
Committed 275317@main (df3b091edfba): <https://commits.webkit.org/275317@main>

Reviewed commits have been landed. Closing PR #25012 and removing active labels.

2024-02-26 14:16 UTC, merged