Avoid calling SynchronousLoadData CompletionHandler more than once
WebKit/WebKit pull request #25050
Opened 2024-02-24 01:33 UTC by sysrqb

#### bdfde8e40751936c235326a8a61b76653fb306d9
<pre>
Avoid calling SynchronousLoadData CompletionHandler more than once
<a href="https://bugs.webkit.org/show_bug.cgi?id=270030">https://bugs.webkit.org/show_bug.cgi?id=270030</a>
<a href="https://rdar.apple.com/109257007">rdar://109257007</a>

Reviewed by NOBODY (OOPS!).

In some situations, a NetworkResourceLoader may call its SynchronousLoadData&apos;s
delayedReply CompletionHandler more than once. This change prevents that by
tracking if we already sent a synchronous response, and it returns early if so.

* Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp:
(WebKit::sendReplyToSynchronousRequest):
</pre>

2024-02-24 01:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bdfde8e40751936c235326a8a61b76653fb306d9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25050

2024-02-24 01:47 UTC, cdumez requested changes

2024-02-24 01:47 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
>      data.delayedReply = nullptr;
This is not necessary, CompletionHandlers already get nulled out when called.

2024-02-24 01:47 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +    data.wasCompletionHandlerCalled = true;
Not necessary.

2024-02-24 01:47 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +    bool wasCompletionHandlerCalled { false };
Not necessary.

2024-02-24 01:47 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +    if (data.wasCompletionHandlerCalled)
Could just check `if (!data.delayedReply)`.

That said, I am kind of curious how that happens.

2024-02-27 14:03 UTC, sysrqb commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +    if (data.wasCompletionHandlerCalled)
Hrm, good point. I wanted to maintain the invariant `ASSERT(data.delayedReply)`, but obviously I didn't actually do that because we already null it.

2024-02-27 21:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/23aefccf9c05350aa6aec6d11934dc4ee29d6c19. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25050

2024-02-28 21:20 UTC, cdumez approved these changes

2024-02-28 22:38 UTC, webkit-commit-queue commented
Committed 275465@main (e336a8ca8c96): <https://commits.webkit.org/275465@main>

Reviewed commits have been landed. Closing PR #25050 and removing active labels.

2024-02-28 22:38 UTC, merged