CrashTracer: com.apple.WebKit.WebContent at com.apple.WebCore: WebCore::CSSCalcOperationNode::simplifyRecursive
WebKit/WebKit pull request #25330
Opened 2024-03-01 01:52 UTC by nt1m

#### ab128b041700bdaee0ae98fed608729268f7abf6
<pre>
CrashTracer: com.apple.WebKit.WebContent at com.apple.WebCore: WebCore::CSSCalcOperationNode::simplifyRecursive
<a href="https://bugs.webkit.org/show_bug.cgi?id=270296">https://bugs.webkit.org/show_bug.cgi?id=270296</a>
<a href="https://rdar.apple.com/123508905">rdar://123508905</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/css/BasicShapeFunctions.cpp:
(WebCore::valueForBasicShape):
* Source/WebCore/css/BasicShapeFunctions.h:
* Source/WebCore/css/ComputedStyleExtractor.cpp:
(WebCore::valueForPathOperation):
(WebCore::shapePropertyValue):
(WebCore::valueForOffsetShorthand):
</pre>

2024-03-01 01:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ab128b041700bdaee0ae98fed608729268f7abf6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25330

2024-03-04 22:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cde1c1500647995b5164beee6d5d86a4f0c4a6b7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25330

2024-03-06 06:03 UTC, heycam approved these changes
Please use a commit message that describes the change rather than just says "CrashTracer: ...", and include the kinds of values that we are crashing on and how this patch changes our behavior for them.

2024-03-06 06:03 UTC, heycam commented on Source/WebCore/css/ComputedStyleExtractor.cpp
> +            innerList.append(*pathOperation);
Should this whole function return null if pathOperation is null, rather than just skipping serializing that value?

2024-03-06 08:30 UTC, anttijk requested changes

2024-03-06 08:30 UTC, anttijk commented on Source/WebCore/css/ComputedStyleExtractor.cpp
> +static RefPtr<CSSValue> valueForPathOperation(const RenderStyle& style, const PathOperation* operation, SVGPathConversion conversion = SVGPathConversion::None)
This feels like sweeping the bug under the carpet. I don't see an explanation why this is ok.

2024-03-09 15:29 UTC, closed without merging