[Skia] Fix double-free in WebKitTestRunner
WebKit/WebKit pull request #25543
Opened 2024-03-06 19:13 UTC by csaavedra

#### 49c48b9e605adcab4b097d391c249a433c25ff19
<pre>
[Skia] Fix double-free in WebKitTestRunner
<a href="https://bugs.webkit.org/show_bug.cgi?id=270585">https://bugs.webkit.org/show_bug.cgi?id=270585</a>

Reviewed by NOBODY (OOPS!).

Using sk_sp&lt;&gt;::reset() in TestInvocation::dumpPixelsAndCompareWithExpected()
is wrong, because we are receiving a raw pointer that has been obtained with
sk_sp::get(). This method doesn&apos;t increase the reference count for us,
and neither does reset() (it simply adopts the pointer). When
dumpPixelsAndCompareWithExpected() finishes and image goes out of scope,
this will unref() the underlying SkImage, freeing it even if the method
doesn&apos;t own it.

Since windowSnapshotImage() is returning a raw pointer and we&apos;re
just using it as a local variable, we don&apos;t really need
a shared pointer, we can just use it directly without messing with its
refcounting.

* Tools/WebKitTestRunner/skia/TestInvocationSkia.cpp:
(WTR::TestInvocation::dumpPixelsAndCompareWithExpected):
</pre>

2024-03-06 19:17 UTC, csaavedra commented
btw, I bisected the regression to have been introduced in https://commits.webkit.org/274613@main, which is how I found where the issue was.

2024-03-06 19:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/49c48b9e605adcab4b097d391c249a433c25ff19. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25543

2024-03-06 21:45 UTC, aperezdc approved these changes

2024-03-07 08:32 UTC, carlosgcampos commented
Wait, this is right fix for the old api, but not for the new one. The bug is actually in the old API implementation, because snapshot() is expected to return a raw pointer to be adopted by the caller, like in the cairo case.

2024-03-07 08:37 UTC, carlosgcampos requested changes
This is not the right fix, it will break the new api, the bug is actually in HeadlessViewBackend::snapshot(), we should return a reference there.

2024-03-07 10:29 UTC, carlosgcampos approved these changes

2024-03-07 10:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/999bcdefa6d6bdacd778f03a9331497c17f5f835. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25543

2024-03-07 10:36 UTC, webkit-commit-queue commented
Committed 275784@main (669cd08179b2): <https://commits.webkit.org/275784@main>

Reviewed commits have been landed. Closing PR #25543 and removing active labels.

2024-03-07 10:36 UTC, merged