Remove StyleAppearance::CapsLockIndicator
WebKit/WebKit pull request #25709
Opened 2024-03-11 11:56 UTC by annevk

#### d963c9287181f7171019e79d089bd6ed9416b660
<pre>
Remove StyleAppearance::CapsLockIndicator
<a href="https://bugs.webkit.org/show_bug.cgi?id=250725">https://bugs.webkit.org/show_bug.cgi?id=250725</a>
<a href="https://rdar.apple.com/104616561">rdar://104616561</a>

Reviewed by NOBODY (OOPS!).

It&apos;s not used for anything.

* Source/WebCore/css/CSSPrimitiveValueMappings.h:
(WebCore::toCSSValueID):
* Source/WebCore/rendering/RenderTheme.cpp:
(WebCore::RenderTheme::adjustStyle):
(WebCore::RenderTheme::autoAppearanceForElement const):
(WebCore::RenderTheme::createControlPart const):
(WebCore::RenderTheme::paint):
* Source/WebCore/rendering/RenderTheme.h:
(WebCore::RenderTheme::adjustCapsLockIndicatorStyle const): Deleted.
(WebCore::RenderTheme::paintCapsLockIndicator): Deleted.
* Source/WebCore/style/StyleAppearance.cpp:
(WebCore::operator&lt;&lt;):
* Source/WebCore/style/StyleAppearance.h:
* Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in:
</pre>

2024-03-11 15:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d963c9287181f7171019e79d089bd6ed9416b660. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25709

2024-03-11 18:43 UTC, nt1m requested changes
It's used here: https://searchfox.org/wubkat/rev/711120e7edec012527620d07bf63d85713a180fd/Source/WebCore/css/html.css#759 which `RenderTheme::autoAppearanceForElement` converts into `StyleAppearance::CapsLockIndicator`

2024-03-11 20:36 UTC, pxlcoder commented
> It's used here: https://searchfox.org/wubkat/rev/711120e7edec012527620d07bf63d85713a180fd/Source/WebCore/css/html.css#759 which `RenderTheme::autoAppearanceForElement` converts into `StyleAppearance::CapsLockIndicator`

But we don't actually do anything with the `appearance` value? The rendering is done using `content` in that same ruleset.

2024-03-11 20:37 UTC, nt1m commented
> > It's used here: https://searchfox.org/wubkat/rev/711120e7edec012527620d07bf63d85713a180fd/Source/WebCore/css/html.css#759 which `RenderTheme::autoAppearanceForElement` converts into `StyleAppearance::CapsLockIndicator`
> 
> But we don't actually do anything with the `appearance` value? The rendering is done using `content` in that same ruleset.

Should we clean up the UA stylesheet rule then?

2024-03-12 16:22 UTC, nt1m approved these changes
I assume that you've tested that ::-webkit-caps-lock-indicator still looks correct

2024-03-12 18:08 UTC, annevk commented
Yeah it's still there.

2024-03-12 18:51 UTC, webkit-commit-queue commented
Committed 275990@main (d06002e88dea): <https://commits.webkit.org/275990@main>

Reviewed commits have been landed. Closing PR #25709 and removing active labels.

2024-03-12 18:51 UTC, merged