[Skia] Use repeat tile mode when pattern is phased
WebKit/WebKit pull request #25718
Opened 2024-03-11 15:31 UTC by GeorgesStavracas

#### 50e37a4ce6d2ed9113e6507ea76980302025c9da
<pre>
[Skia] Use repeat tile mode when pattern is phased
<a href="https://bugs.webkit.org/show_bug.cgi?id=270795">https://bugs.webkit.org/show_bug.cgi?id=270795</a>

Reviewed by NOBODY (OOPS!).

Otherwise it&apos;ll clamp after translating the source image.

* Source/WebCore/platform/graphics/skia/GraphicsContextSkia.cpp:
(WebCore::GraphicsContextSkia::drawPattern):
</pre>

2024-03-11 15:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/50e37a4ce6d2ed9113e6507ea76980302025c9da. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25718

2024-03-12 08:48 UTC, carlosgcampos requested changes

2024-03-12 08:48 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/skia/GraphicsContextSkia.cpp
>      rect.moveBy(phase);
I see the problem now! We are applying the phase to the tile rect here, *after* computing the tile mode. Just move the tileMode computation after this, and use `rect` instead of `tileRect` and we'll see Adrian's face again.

2024-03-12 11:16 UTC, GeorgesStavracas commented on Source/WebCore/platform/graphics/skia/GraphicsContextSkia.cpp
>      rect.moveBy(phase);
Right! This seems better to me, thanks :)

2024-03-12 11:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8b620c8ba08df6a7da846cffed3f4b15a5b13fd3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25718

2024-03-12 11:51 UTC, carlosgcampos approved these changes

2024-03-12 11:55 UTC, webkit-commit-queue commented
Committed 275972@main (de0adcf1202f): <https://commits.webkit.org/275972@main>

Reviewed commits have been landed. Closing PR #25718 and removing active labels.

2024-03-12 11:55 UTC, merged