[Skia] Add support for favicons on GTK4
WebKit/WebKit pull request #25735
Opened 2024-03-11 18:52 UTC by TingPing

#### d0ffdc7551b5e558dd444afd99908d08a5843c7b
<pre>
[Skia] Add support for favicons on GTK4
<a href="https://bugs.webkit.org/show_bug.cgi?id=270811">https://bugs.webkit.org/show_bug.cgi?id=270811</a>

Reviewed by NOBODY (OOPS!).

* Source/WebCore/PlatformGTK.cmake:
* Source/WebCore/SourcesGTK.txt:
* Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp: Added.
(WebCore::skiaImageToGdkTexture):
* Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.h: Added.
* Source/WebKit/UIProcess/API/glib/WebKitFaviconDatabase.cpp:
(webkitFaviconDatabaseGetFaviconInternal):
(webkit_favicon_database_get_favicon_finish):
</pre>

2024-03-11 18:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d0ffdc7551b5e558dd444afd99908d08a5843c7b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-11 18:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b0b7635c5f51b1a7e73d5d7b9cb3a1d1fc71ab44. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-11 19:08 UTC, GeorgesStavracas commented
LGTM

2024-03-12 00:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/26a1d0cad51c778cd15e84d073ee1a0ea3d6e267. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-12 00:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/98ebd8e702859692a3249f4c8d6187d8f689727f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-12 08:36 UTC, carlosgcampos approved these changes
Excellent, thanks! I have only a few minor comments

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    ASSERT(image);
Pass a reference and we don't need the assert here.

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    ASSERT(image);
Ditto.

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    auto* surface = cairo_image_surface_create_for_data(const_cast<uint8_t*>(data), CAIRO_FORMAT_ARGB32, pixmap.width(), pixmap.height(), pixmap.rowBytes());
You can use `pixmap.writable_addr8()`

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +        cairo_surface_destroy(surface);
You can use RefPtr, for the GTK port it's build with Skia enabled too.

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    }
We don't check failure of set_user_data in other places, I think this can only fail if an invalid surface is passed or in case of OOM

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +cairo_surface_t* skiaImageToCairoSurface(SkImage* image)
This should return `RefPtr<cairo_surface_t>`

2024-03-12 08:36 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitFaviconDatabase.cpp
> +    return image ? skiaImageToCairoSurface(image) : nullptr;
I see here it's more convenient to return the raw pointer, but we might need this helper in other places like snapshots, so better be consistent with `skiaImageToGdkTexture`

2024-03-12 10:45 UTC, TingPing commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    }
Yeah it’s for OOM. Might as well `g_error()` then?

2024-03-12 10:47 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +    }
I think we can just ignore it like we do everywhere else

2024-03-12 12:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6843b379431bdd60e2cd3cef4067196ff418d6d8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-12 12:32 UTC, carlosgcampos requested changes

2024-03-12 12:32 UTC, carlosgcampos commented on Source/WebCore/platform/graphics/gtk/GdkSkiaUtilities.cpp
> +GRefPtr<cairo_surface_t> skiaImageToCairoSurface(SkImage& image)
cairo_surface_t is not a GObject, this should be RefPtr and RefPtrCairo.h needs to be included

2024-03-12 13:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bc9cc536d547dde1777707d358c30b2ee87e8c50. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/25735

2024-03-12 13:03 UTC, carlosgcampos approved these changes

2024-03-12 17:05 UTC, webkit-commit-queue commented
Committed 275982@main (e9c4929afd39): <https://commits.webkit.org/275982@main>

Reviewed commits have been landed. Closing PR #25735 and removing active labels.

2024-03-12 17:05 UTC, merged