Unhandled EbtVoid type for addBinaryMathInternal API for EOpDiv.
WebKit/WebKit pull request #26275
Opened 2024-03-21 22:41 UTC by nishajain61

#### c2f52704bfc40818125f6f48aa816c5140180590
<pre>
Unhandled EbtVoid type for addBinaryMathInternal API for EOpDiv.
<a href="https://bugs.webkit.org/show_bug.cgi?id=271421">https://bugs.webkit.org/show_bug.cgi?id=271421</a>
<a href="https://rdar.apple.com/124085673">rdar://124085673</a>

Reviewed by NOBODY (OOPS!).

Added check for EbtVoid type in addBinaryMathInternal API under ParseContext.

* Source/ThirdParty/ANGLE/src/compiler/translator/ParseContext.cpp:
(sh::TParseContext::addBinaryMathInternal):
</pre>

2024-03-21 22:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c2f52704bfc40818125f6f48aa816c5140180590. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-03-22 07:01 UTC, kkinnunen-apple requested changes
Need to get it landed via upstream. I provided the instructions.

2024-03-22 15:47 UTC, nishajain61 commented
Closing this PR needs to be opened against upstream based on feedback along with a test case.

2024-03-22 19:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8ba14aa78207ca56251f09ab3ffeeb10d3181eae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-03-22 19:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/31d45dd99bac4e486fb3fe538330b54cd4deebe6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-03-26 18:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/99d799b2bbfaa4cc695b5f9a49b388a0c81d8865. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-03-28 23:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/548f8f0a2dd311cab61baeaff3fc5fdc729ff6f0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-03-29 15:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/455ba541156f1e30634fa90daa8bfd1eaa32031a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-04-01 21:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4705ae0417802be0e7c7c2a1ce1f09ff9cb05e09. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-04-02 16:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8065ae84ebcd1350b24d83d8b473915ec5e8fb1c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26275

2024-04-17 23:57 UTC, nishajain61 commented
This change has been landed into ANGLE open source project : https://chromium-review.googlesource.com/c/angle/angle/+/5416376 so closing this PR. Thanks

2024-04-17 23:57 UTC, closed without merging