Call notify_get_state on non main thread
WebKit/WebKit pull request #26556
Opened 2024-03-28 14:29 UTC by pvollan

#### 6ec6d6d3f445cb0a8acfd1c2a34e62d0546a505d
<pre>
Call notify_get_state on non main thread
<a href="https://bugs.webkit.org/show_bug.cgi?id=271827">https://bugs.webkit.org/show_bug.cgi?id=271827</a>
<a href="https://rdar.apple.com/125521998">rdar://125521998</a>

Reviewed by NOBODY (OOPS!).

To avoid blocking the main thread in the UI process, call notify_get_state on a non main thread.

* Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm:
(WebKit::WebProcessPool::registerNotificationObservers):
</pre>

2024-03-28 14:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6ec6d6d3f445cb0a8acfd1c2a34e62d0546a505d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26556

2024-03-28 19:45 UTC, cdumez requested changes

2024-03-28 19:45 UTC, cdumez commented on Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
>          if (status)
This patch seems wrong to me. I don't see how you can check `status` here synchronously on the main thread when it now gets set off the main thread, asynchronously.

2024-03-28 19:47 UTC, cdumez commented on Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
>          if (status)
Ohhh, there are 2 `status` variables, in different scopes. That's bad practice and why I got confused.

2024-03-28 19:52 UTC, cdumez requested changes

2024-03-28 19:52 UTC, cdumez commented on Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
> +                if (!protectedThis->m_processes.isEmpty()) {
This should use `WebProcessPool::sendToAllProcesses()`.

2024-03-28 19:52 UTC, cdumez commented on Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
>          if (status)
So to clarify, I think this is correct but you should rename the variables so they don't have the same name.

2024-03-28 20:27 UTC, pvollan commented on Source/WebKit/UIProcess/Cocoa/WebProcessPoolCocoa.mm
>          if (status)
Ah, that is a good point! I will address this in the upcoming patch.

Thanks for reviewing!

2024-03-29 17:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ea2850e67fed85da8a85935dabfe84242442efe4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26556

2024-03-29 17:42 UTC, cdumez approved these changes
LGTM

2024-03-29 18:06 UTC, pvollan commented
> LGTM

Thanks for reviewing!

2024-03-29 18:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/48715219108eb5a61742125610c17872f259b393. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26556

2024-03-29 21:22 UTC, webkit-commit-queue commented
Committed 276841@main (2349fc0c0311): <https://commits.webkit.org/276841@main>

Reviewed commits have been landed. Closing PR #26556 and removing active labels.

2024-03-29 21:22 UTC, merged