Remove ENABLE_CSS_PAINTING_API build flag
WebKit/WebKit pull request #26627
Opened 2024-03-29 21:41 UTC by donny-dont

#### 12c11a65eb84e72b971ff468c54f79ff9928fba2
<pre>
Remove ENABLE_CSS_PAINTING_API build flag
<a href="https://bugs.webkit.org/show_bug.cgi?id=271913">https://bugs.webkit.org/show_bug.cgi?id=271913</a>

Reviewed by NOBODY (OOPS!).

All ports are building with `ENABLE_CSS_PAINTING_API` as `ON`. Remove the
build option and use the runtime option for controlling use.

* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WTF/wtf/PlatformEnableCocoa.h:
* Source/WebCore/bindings/js/JSPaintRenderingContext2DCustom.cpp:
* Source/WebCore/bindings/js/JSPaintWorkletGlobalScopeCustom.cpp:
* Source/WebCore/bindings/js/WebCoreJSClientData.cpp:
* Source/WebCore/bindings/js/WebCoreJSClientData.h:
* Source/WebCore/css/CSSPaintCallback.h:
* Source/WebCore/css/CSSPaintCallback.idl:
* Source/WebCore/css/CSSPaintImageValue.cpp:
* Source/WebCore/css/CSSPaintImageValue.h:
* Source/WebCore/css/CSSPaintSize.h:
* Source/WebCore/css/CSSPaintSize.idl:
* Source/WebCore/css/CSSValue.cpp:
* Source/WebCore/css/CSSValue.h:
* Source/WebCore/css/CSSValueKeywords.in:
* Source/WebCore/css/DOMCSSNamespace+CSSPainting.idl:
* Source/WebCore/css/DOMCSSPaintWorklet.cpp:
* Source/WebCore/css/DOMCSSPaintWorklet.h:
* Source/WebCore/css/parser/CSSParserContext.cpp:
* Source/WebCore/css/parser/CSSPropertyParserHelpers.cpp:
* Source/WebCore/css/typedom/MainThreadStylePropertyMapReadOnly.cpp:
* Source/WebCore/dom/Document.cpp:
* Source/WebCore/dom/Document.h:
* Source/WebCore/html/CustomPaintCanvas.cpp:
* Source/WebCore/html/CustomPaintCanvas.h:
* Source/WebCore/html/CustomPaintImage.cpp:
* Source/WebCore/html/CustomPaintImage.h:
* Source/WebCore/html/canvas/PaintRenderingContext2D.cpp:
* Source/WebCore/html/canvas/PaintRenderingContext2D.h:
* Source/WebCore/html/canvas/PaintRenderingContext2D.idl:
* Source/WebCore/rendering/style/RenderStyle.cpp:
* Source/WebCore/rendering/style/RenderStyle.h:
* Source/WebCore/rendering/style/StyleImage.h:
* Source/WebCore/rendering/style/StylePaintImage.cpp:
* Source/WebCore/rendering/style/StylePaintImage.h:
* Source/WebCore/style/StyleBuilder.cpp:
* Source/WebCore/style/StyleBuilderState.cpp:
* Source/WebCore/workers/WorkerOrWorkletScriptController.cpp:
* Source/WebCore/worklets/PaintWorkletGlobalScope.cpp:
* Source/WebCore/worklets/PaintWorkletGlobalScope.h:
* Source/WebCore/worklets/PaintWorkletGlobalScope.idl:
* Source/WebCore/worklets/WorkletGlobalScope.h:
* Source/cmake/OptionsGTK.cmake:
* Source/cmake/OptionsMac.cmake:
* Source/cmake/OptionsPlayStation.cmake:
* Source/cmake/OptionsWPE.cmake:
* Source/cmake/OptionsWin.cmake:
* Source/cmake/WebKitFeatures.cmake:
* Tools/Scripts/webkitperl/FeatureList.pm:
</pre>

2024-03-29 21:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/12c11a65eb84e72b971ff468c54f79ff9928fba2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26627

2024-03-29 22:56 UTC, mcatanzaro requested changes
"All ports are building with `ENABLE_CSS_PAINTING_API` as `ON`."

Warning klaxons: looks like this is completely wrong. It's disabled in all CMake ports except macOS (which doesn't matter because production macOS builds don't use CMake). `ENABLE_EXPERIMENTAL_FEATURES` does not get turned on in releases and it probably hasn't been tested anywhere except buildbots.

I would do a separate commit first to enable the build flag, land that first, _then_ remove the build flag. I think it should be safe because the runtime feature is also disabled everywhere except if experimental features are enabled, so in theory it shouldn't matter. But still safer to do in two stages.

2024-03-29 23:07 UTC, mcatanzaro commented on Source/cmake/WebKitFeatures.cmake
> -    WEBKIT_OPTION_DEFINE(ENABLE_CSS_PAINTING_API "Toggle CSS Painting API support" PRIVATE OFF)
i.e. first land a patch changing this to `ON` and changing the various `WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_CSS_PAINTING_API PRIVATE ${ENABLE_EXPERIMENTAL_FEATURES})` to also `ON`. _Then_ land this pull request second.

2024-04-02 20:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/515baaca2892c9f8d05eaf01536a82d4af330cc4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26627

2024-04-03 13:52 UTC, mcatanzaro approved these changes

2024-04-16 22:39 UTC, shallawa commented
What is the rule for removing an `ENABLE()` flag if it is unconditionally set to true? Currently we have all these flags set to true. This list includes `ENABLE_MATHML` and the `ENABLE_OFFSCREEN_CANVAS`.
```
#if !defined(ENABLE_CONTEXT_MENUS)
#define ENABLE_CONTEXT_MENUS 1
#endif

#if !defined(ENABLE_CONTEXT_MENU_EVENT)
#define ENABLE_CONTEXT_MENU_EVENT 1
#endif

#if !defined(ENABLE_CSS_PAINTING_API)
#define ENABLE_CSS_PAINTING_API 1
#endif

#if !defined(ENABLE_CUSTOM_CURSOR_SUPPORT)
#define ENABLE_CUSTOM_CURSOR_SUPPORT 1
#endif

#if !defined(ENABLE_DRAG_SUPPORT)
#define ENABLE_DRAG_SUPPORT 1
#endif

#if !defined(ENABLE_FTPDIR)
#define ENABLE_FTPDIR 1
#endif

#if !defined(ENABLE_INPUT_TYPE_COLOR)
#define ENABLE_INPUT_TYPE_COLOR 1
#endif

#if !defined(ENABLE_MATHML)
#define ENABLE_MATHML 1
#endif

#if !defined(ENABLE_OFFSCREEN_CANVAS)
#define ENABLE_OFFSCREEN_CANVAS 1
#endif

#if !defined(ENABLE_OFFSCREEN_CANVAS_IN_WORKERS)
#define ENABLE_OFFSCREEN_CANVAS_IN_WORKERS 1
#endif

#if !defined(ENABLE_POINTER_LOCK)
#define ENABLE_POINTER_LOCK 1
#endif

#if !defined(ENABLE_TEXT_CARET)
#define ENABLE_TEXT_CARET 1
#endif

#if !defined(ENABLE_TEXT_SELECTION)
#define ENABLE_TEXT_SELECTION 1
#endif

#if !defined(ENABLE_XSLT)
#define ENABLE_XSLT 1
#endif
```
So why do we care about `ENABLE_CSS_PAINTING_API` only and ignore the reset? Or are we planning to remove all of these flags?

2024-04-16 22:48 UTC, donny-dont commented
> What is the rule for removing an `ENABLE()` flag if it is unconditionally set to true? Currently we have all these flags set to true. This list includes `ENABLE_MATHML` and the `ENABLE_OFFSCREEN_CANVAS`.
> ....
> 
> So why do we care about `ENABLE_CSS_PAINTING_API` only and ignore the reset? Or are we planning to remove all of these flags?

@shallawa myself and @annevk have been going through the list and removing `ENABLE`s one by one.

Algorithmically it boils down to. Does the `ENABLE` flag require port specific code? Something like `ENABLE_XSLT` does not pass that because it requires an implementation of `libxslt`, while the CSS Painting API is port agnostic so it passes this check. Does the `ENABLE` flag have a runtime option? Yes for CSS Painting API. Since it passes those checks its up for removal.

2024-04-16 22:57 UTC, shallawa approved these changes

2024-04-17 00:14 UTC, webkit-commit-queue commented
Committed 277584@main (4d1720ec1d0f): <https://commits.webkit.org/277584@main>

Reviewed commits have been landed. Closing PR #26627 and removing active labels.

2024-04-17 00:14 UTC, merged

2024-04-17 06:57 UTC, annevk commented
`PlatformEnable.h` is unfortunately not sufficient to determine if a flag is always true for all ports. You also have to look at the CMake code. And yeah, generally the less branches we have to (pretend to) maintain the better.