[ANGLE]: fix is_always_lock_free assertion on 32 bit arch
WebKit/WebKit pull request #26645
Opened 2024-03-30 08:02 UTC by ThomasDevoogdt

https://bugs.webkit.org/show_bug.cgi?id=252670

Reviewed by NOBODY (OOPS!).

Remove is_always_lock_free assertion from AtomicQueueSerial

Build will fail when compiled on 32 bit architecture. The code will still function on 32 bit architecture but with performance penalty due to lock. But we are not really expecting it actually run on 32 bit platform with vulkan backend (the atomic queue serial is only used by vulkan backend). We could move AtomicQueueSerial into vulkan backend, but that will be a much larger change that I try to avoid. This CL removes the static_assertion and make it 8 bytes aligned as well.

Bug: angleproject:7989
Change-Id: I3c0bd9877c4171485ca1aa9af0cf4621c1c23f56
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/5407870
Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
Commit-Queue: Charlie Lao <cclao@google.com>

Upstream: https://chromium.googlesource.com/angle/angle/+/321c6b63bebce3f31414d8a53fb2f94b5561b818

2024-03-30 08:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4399714e71df34ac53e830ae1f7b2eab93716fa7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26645

2024-03-30 08:04 UTC, ThomasDevoogdt commented
Please, also consider cherry-picking to WebKitGTK 2.44.x.

2024-04-02 18:54 UTC, kkinnunen-apple requested changes
Let's land this as part of a normal ANGLE update.
I'll make a new upstream update once the one pending in #26717 lands.

2024-04-02 18:56 UTC, mcatanzaro commented
I will manually cherry-pick this to webkitglib/2.44 since "fix the bug one way in main and a different way in stable" is not a good match for our label-based backport workflow.

2024-04-02 19:00 UTC, mcatanzaro commented
(Please follow up to make sure this does land in main; otherwise, it will regress in 2.46.)

2024-04-02 19:02 UTC, mcatanzaro commented
Ah wait, I see this already landed in upstream ANGLE. Great. Closing.

2024-04-02 19:02 UTC, closed without merging

2024-04-02 19:07 UTC, ThomasDevoogdt commented
Thanks for taking this up!