Web Inspector: Network Tab: Scope Bar Background Blue
WebKit/WebKit pull request #26743
Opened 2024-04-02 20:08 UTC by francescorn

#### e326b40ec810016f5b589c7663c2b7d557ffdb86
<pre>
Web Inspector: Network Tab: Scope Bar Background Blue
<a href="https://bugs.webkit.org/show_bug.cgi?id=272016">https://bugs.webkit.org/show_bug.cgi?id=272016</a>

Reviewed by NOBODY (OOPS!).

The goal of my pr is to match the navigation tab bars in both light mode and dark mode with the rest of the Web Inspector scope bars:
Add a blue background when a navigation item radio button is selected or hovered.
Set the opacity to 0.8 when a navigation item radio button is hovered but not selected.

* Source/WebInspectorUI/UserInterface/Views/NetworkDetailView.css:
(.network-detail .item):
(.network-detail .item.button):
(.network .network-detail .navigation-bar .item.radio.button.text-only:is(.selected, :hover)):
(.network .network-detail .navigation-bar .item.radio.button.text-only:not(.selected):is(:hover)):
(.network .network-detail .navigation-bar .item.radio.button.text-only.selected): Deleted.
</pre>

2024-04-02 20:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e326b40ec810016f5b589c7663c2b7d557ffdb86. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/26743

2024-04-02 20:23 UTC, francescorn commented
This pr is ready for a review. @dcrousso @patrickangle

Safari 17.4: 
<img width="1214" alt="dark_mode_safari_17.4_network_tab" src="https://github.com/WebKit/WebKit/assets/113309999/ddd8bb98-b2ee-45be-aa34-47eb44e4e068">
<img width="1217" alt="light_mode_safari_17.4_network_tab" src="https://github.com/WebKit/WebKit/assets/113309999/f236b7a0-1c33-4f79-af7f-6cfc263dbb18">

mini-browser: 
<img width="1469" alt="dark_mode_mini-browser_network_tab" src="https://github.com/WebKit/WebKit/assets/113309999/850d0d27-8353-41ee-804a-c58fce16b948">
<img width="1470" alt="light_mode_mini-browser_network_tab" src="https://github.com/WebKit/WebKit/assets/113309999/5cb9ff04-e525-44e0-bd80-909bc11442aa">

2024-04-03 00:28 UTC, the-chenergy commented
Nice 👍 Does this also apply to the scope bar items in the Settings tab?

Do you know why they show up differently in Safari versus in mini-browser? The Safari styles look a little obscure to me, especially on dark mode 🤔

2024-04-04 05:01 UTC, dcrousso requested changes
ive mentioned this in [slack](https://webkit.slack.com/archives/CU65DUH7F/p1712179024368929?thread_ts=1712103460.406009&cid=CU65DUH7F), but i think there's a potential need to have distinct visual differences between the how the developer selects which pane (btw this is the term used in our documentation for this UI) they want to see and similar things like the resource type filter at the top of the Network Tab

for example, we have a "Document" filter and a "Preview" pane selector
![image](https://github.com/WebKit/WebKit/assets/4356609/b02bb14f-bcad-41b5-b100-e59aa22d0269)

im totally fine with allowing the various panes to be controlled by a `WI.ScopeBar` instead, but that would mean the developer could ⌘Click to show multiple panes at the same time (similar to how one can select multiple kinds of filters at the same time)

as things are today, however, im concerned that the same visual treatment for two very different things (i.e. filter vs selector) might be confusing to the developer, especially when they're in such close proximity

2024-04-04 05:01 UTC, dcrousso commented on Source/WebInspectorUI/UserInterface/Views/NetworkDetailView.css
> +    --scope-bar-margin: var(--scope-bar-margin-override, var(--scope-bar-margin-default));
these are not `WI.ScopeBarItem` so why are they using those styles?

2024-04-04 05:01 UTC, dcrousso commented on Source/WebInspectorUI/UserInterface/Views/NetworkDetailView.css
> +    opacity: .8;
Style: missing leading `0`

2024-04-06 20:18 UTC, francescorn commented
I think we should change the other tabs then such as the details sidebar in the elements tab, classes and pseudo in the elements tab, by type and by path in the sources tab, resource and scope chain in the sources tab, events and frames in the timelines tab, and all storage and application cache in the storage tab to the other style. I think the console tab and audits tab are the only tabs that have a selection where you can click Command and select multiple scope bars.

2024-04-17 03:32 UTC, closed without merging