Reduce IPC queue size from 1024 to 128
WebKit/WebKit pull request #27114
Opened 2024-04-10 22:39 UTC by cdumez

#### d10f1423e459c04211a02d036d6f886c4ee976eb
<pre>
Reduce IPC queue size from 1024 to 128
<a href="https://bugs.webkit.org/show_bug.cgi?id=272487">https://bugs.webkit.org/show_bug.cgi?id=272487</a>
<a href="https://rdar.apple.com/125523305">rdar://125523305</a>

Reviewed by NOBODY (OOPS!).

Reduce IPC queue size from 1024 to 128, to reduce memory usage. Once the queue
size is reached, we wake up the process to give it a chance to process the
queue.

* Source/WebKit/Platform/IPC/Connection.cpp:
</pre>

2024-04-10 22:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d10f1423e459c04211a02d036d6f886c4ee976eb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27114

2024-04-10 22:41 UTC, bnham commented
We need to also change this to get the backpressure to kick in faster.

```
    // Change the message queue length for the receive port.
    setMachPortQueueLength(m_receivePort, MACH_PORT_QLIMIT_LARGE);
```

Probably change the second parameter from `MACH_PORT_QLIMIT_LARGE` to 128 to match.

2024-04-10 22:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7e09bbef26de8c1e2dd2a8e0e0269fc2ce1f6fbd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27114

2024-04-10 22:46 UTC, bnham requested changes
We need to also change this to get the backpressure to kick in faster.

```
    // Change the message queue length for the receive port.
    setMachPortQueueLength(m_receivePort, MACH_PORT_QLIMIT_LARGE);
```

Probably change the second parameter from MACH_PORT_QLIMIT_LARGE to 128 to match.

2024-04-10 23:12 UTC, cdumez commented
> We need to also change this to get the backpressure to kick in faster.
> 
> ```
>     // Change the message queue length for the receive port.
>     setMachPortQueueLength(m_receivePort, MACH_PORT_QLIMIT_LARGE);
> ```
> 
> Probably change the second parameter from MACH_PORT_QLIMIT_LARGE to 128 to match.

Good catch, I'm working on updating the PR.

2024-04-10 23:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6e9516282d9f78921339447d0fff29e94abdbb32. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27114

2024-04-10 23:32 UTC, bnham approved these changes

2024-04-11 14:42 UTC, webkit-commit-queue commented
Committed 277383@main (4ef72e9956da): <https://commits.webkit.org/277383@main>

Reviewed commits have been landed. Closing PR #27114 and removing active labels.

2024-04-11 14:42 UTC, merged