[WebKit Container SDK] Release logs are not sent to journald when running within the SDK
WebKit/WebKit pull request #27141
Opened 2024-04-11 09:59 UTC by pgorszkowski-igalia

#### 75ab3576c5b3e7e3b6f7e7836840c66ab3847380
<pre>
[WebKit Container SDK] Release logs are not sent to journald when running within the SDK
<a href="https://bugs.webkit.org/show_bug.cgi?id=272519">https://bugs.webkit.org/show_bug.cgi?id=272519</a>

Reviewed by NOBODY (OOPS!).

With this change, release logs are visible with `journalctl -f` inside WebKit Container SDK.

* Source/WebKit/UIProcess/Launcher/glib/BubblewrapLauncher.cpp:
(WebKit::bubblewrapSpawn):
</pre>

2024-04-11 10:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/75ab3576c5b3e7e3b6f7e7836840c66ab3847380. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27141

2024-04-11 15:43 UTC, mcatanzaro requested changes
No, that's a sandbox escape. You can't give the web process access to the host journal.

2024-04-11 19:56 UTC, mcatanzaro commented
Hm, @pgorszkowski-igalia  pointed out that both of these sockets are mounted by flatpak. Looks like they are intended to be "write-only" in the sense that the application writes its logs to them and does not get to read from it?

Unfortunately I'm unable to find the flatpak code that actually mounts these sockets in flatpak-run.c, where I would expect to see it.

2024-04-11 20:03 UTC, mcatanzaro commented
It's now part of flatpak-run-sockets.c. Should be OK. Sorry for reviewing too quickly.

2024-04-11 20:04 UTC, mcatanzaro approved these changes

2024-04-11 21:14 UTC, TingPing reviewed
👍

2024-04-17 08:40 UTC, webkit-commit-queue commented
Committed 277604@main (80927c1fce59): <https://commits.webkit.org/277604@main>

Reviewed commits have been landed. Closing PR #27141 and removing active labels.

2024-04-17 08:40 UTC, merged