Implement case sensitive modifier (s) in attribute selector
WebKit/WebKit pull request #27188
Opened 2024-04-12 09:16 UTC by karlcow

#### 62796751e19c8dad35440b829ebcf3b36834ec3d
<pre>
Implement case sensitive modifier (s) in attribute selector
<a href="https://bugs.webkit.org/show_bug.cgi?id=272573">https://bugs.webkit.org/show_bug.cgi?id=272573</a>
<a href="https://rdar.apple.com/126331481">rdar://126331481</a>

Reviewed by NOBODY (OOPS!).

This is fixing a couple of WPT tests relative to attribute selector case
sensitivity aka adding the value &quot;s&quot; for case sensitive in rules with
this pattern: [attribute=&quot;Value&quot; s]

It doesn&apos;t fix yet some of the cases when
1. getting CSSRule#cssText
2. getting CSSStyleRule#selectorText
3. setting CSSStyleRule#selectorText

* LayoutTests/imported/w3c/web-platform-tests/css/selectors/attribute-selectors/attribute-case/cssom-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/selectors/attribute-selectors/attribute-case/semantics-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/selectors/attribute-selectors/attribute-case/syntax-expected.txt:
* Source/WebCore/css/parser/CSSSelectorParser.cpp:
(WebCore::CSSSelectorParser::consumeAttributeFlags):
</pre>

2024-04-12 09:19 UTC, karlcow commented
@nt1m if you have ideas on how to fix the remaining FAILs 
I see a part here to rebuild the right string.
https://searchfox.org/wubkat/rev/8ce70fa03821ea1c7a19a3913730ffe6b8a522ed/Source/WebCore/css/CSSSelector.cpp#594-600
where I could add `builder.append(" s]"_s);`
but I don't think it's enough.

2024-04-12 10:39 UTC, Ahmad-S792 commented
@karlcow - could be wrong approach but - 
<img width="848" alt="image" src="https://github.com/WebKit/WebKit/assets/52317531/260ccaf1-30c2-4c5e-af29-e47a3e962da3">

2024-04-12 13:57 UTC, karlcow commented
OK in my latest attempt locally on my patch. I successfully manage to add the `s` but, unfortunately I also now have it as a default and fail the tests where it is not needed.

2024-04-12 14:24 UTC, Ahmad-S792 commented
> (huh. How come your comment @Ahmad-S792 was edited by me. sorry about that. Let's try to fix this mess.)
> 
> I tried this but this is not enough.
> 
> I think there is a question of state to manage at different places. Also it seems in the current code case sensitive is the default. So it needs to handle the two forms with and without the `s` but probably not adding the `s` when it was not there in the first place.
> 
> I want to read the spec too, to make sure this is doing the right thing.

No worries - I was just thinking about rather than introducing new function - just approach it with negative of statement and do it. :-)

2024-04-12 15:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/62796751e19c8dad35440b829ebcf3b36834ec3d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27188

2024-04-13 02:52 UTC, karlcow commented
https://drafts.csswg.org/selectors-4/#attribute-case

2024-04-13 03:22 UTC, nt1m commented
I think implementing serialization correctly is important, can we look at how it's done for the i flag?

2024-04-13 08:59 UTC, karlcow commented
> I think implementing serialization correctly is important, can we look at how it's done for the i flag?

correctly there is a flag to say if the rule is caseSensitive or not. If it detects the case `i` it switches to the caseInsenstive flag with a function. But the default is caseSensitive. The serialization works well.
https://searchfox.org/wubkat/rev/8ce70fa03821ea1c7a19a3913730ffe6b8a522ed/Source/WebCore/css/CSSSelector.cpp#594-600

but it reacts only to a two states thing, so information is lost. The 3 states are: 

* default: caseSensitive
* `i`: caseInsensitive
* `s`: caseSensitive

So probably at the parsing time we need a flag to make it explicit that there was a `s` in there to not loose the information later on when this is being serialized.

2024-04-13 10:45 UTC, karlcow commented
Maybe like 
`enum AttributeMatchType { CaseSensitive, CaseInsensitive };`

we need `enum AttributeCaseFlag { Set, Unset };`

2024-04-13 16:39 UTC, nt1m approved these changes
Ok, I'm a bit less worried about serialization if the default is case sensitive (which mean serialization doesn't change the meaning).

2024-04-14 06:06 UTC, annevk requested changes
Serialization is defined here as far as I know and it doesn't special case these: https://drafts.csswg.org/cssom/#serializing-selectors. However, I think that is a bug.

In particular per https://github.com/w3c/csswg-drafts/issues/2101 the goal of this feature is to enable case-sensitive matching of certain HTML attributes that are currently matched case-insensitively.

I think to fully define that they would also have to change HTML to not override attribute matching when the s modifier is specified. That seems like another bug.

Now finally all this implementation does is treat s the same as the default, but that means the HTML attributes are still matched case-insensitively, which goes against the goal of the feature. I don't think we should ship it in this state.

2024-04-15 02:56 UTC, karlcow commented
> Now finally all this implementation does is treat s the same as the default, but that means the HTML attributes are still matched case-insensitively, which goes against the goal of the feature. I don't think we should support it in this state.

Yes I agree with @annevk here. The logic is currently bizarre.

In the serialization that @annevk is talking about, [the steps are](https://drafts.csswg.org/cssom/#serializing-selectors):

> 5. If the attribute selector has the case-sensitivity flag present, append " i" (U+0020 U+0069) to s.
> 6. Append "]" (U+005D) to s.

BUG 1: It doesn't mention `s` as a possible flag here. 

> to enable case-sensitive matching of certain HTML attributes that are currently matched case-insensitively.

This I need to test further. The code seems to assume case-sensitive by default. 

Relevant code is 
* https://searchfox.org/wubkat/rev/fd9e18c7f3c6303f8a7bb1d8b0af8767bb392410/Source/WebCore/css/SelectorChecker.cpp#608-623
* https://searchfox.org/wubkat/rev/fd9e18c7f3c6303f8a7bb1d8b0af8767bb392410/Source/WebCore/css/parser/CSSSelectorParser.cpp#972-981

```
CSSSelector::AttributeMatchType CSSSelectorParser::consumeAttributeFlags(CSSParserTokenRange& range)
{
    if (range.peek().type() != IdentToken)
        return CSSSelector::CaseSensitive;
    const CSSParserToken& flag = range.consumeIncludingWhitespace();
    if (equalLettersIgnoringASCIICase(flag.value(), "i"_s))
        return CSSSelector::CaseInsensitive;
    m_failedParsing = true;
    return CSSSelector::CaseSensitive;
}
```

2024-04-15 03:01 UTC, karlcow commented
I'm setting this as merging blocked to avoid any mistakes. 
And I will open the relevant bugs on the specifications.

2024-04-15 05:19 UTC, annevk commented
I looked it up, the code ends up using `HTMLDocument::isCaseSensitiveAttribute()`. https://github.com/web-platform-tests/wpt/pull/43709 has some tests for it I wrote a while back that I suppose you could expand with `s` tests to see what implementations do.

2024-04-15 07:48 UTC, karlcow commented
For 

> I think to fully define that they would also have to change HTML to not override attribute matching when the s modifier is specified. That seems like another bug.

And

> Now finally all this implementation does is treat `s` the same as the default, but that means the HTML attributes are still matched case-insensitively, which goes against the goal of the feature. 

I need to create more tests and explore what each browsers are doing. I will check what @annevk mentioned too.

2024-12-06 16:26 UTC, ExE-Boss commented
One attribute which is matched case‑insensitively by default in HTML[^1] is `type` because of `<input>` elements, but this conflicts with the case‑sensitive use of the `type` attribute in the `<ol>` and `<li>` elements, where `type="a"` and `type="A"` mean `list‑style‑type: lower‑alpha` and `list‑style‑type: upper‑alpha` respectively, but without support for the `s` flag, this can only be done in the UA stylesheet, which has special rules for setting the `list‑style‑type` CSS property.

--------------------------------------------------------------------------------

From <https://html.spec.whatwg.org/multipage/rendering.html#decohints>:
```css
ol[type="1"], li[type="1"] { list-style-type: decimal; }
ol[type=a s], li[type=a s] { list-style-type: lower-alpha; }
ol[type=A s], li[type=A s] { list-style-type: upper-alpha; }
ol[type=i s], li[type=i s] { list-style-type: lower-roman; }
ol[type=I s], li[type=I s] { list-style-type: upper-roman; }
```

[^1]: https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-selectors

2024-12-06 16:47 UTC, ExE-Boss commented
These parts of selector matching have to be updated to take the explicit case‑sensitive flag into account: <https://github.com/WebKit/WebKit/blob/d4f8ca8ffac838dd9db82dc67b830005a1d230e7/Source/WebCore/css/SelectorChecker.cpp#L646-L651> <https://github.com/WebKit/WebKit/blob/d4f8ca8ffac838dd9db82dc67b830005a1d230e7/Source/WebCore/css/SelectorChecker.cpp#L762-L768>

2026-05-14 13:15 UTC, closed without merging

2026-05-14 13:16 UTC, karlcow commented
fixed by @anttijk in https://github.com/WebKit/WebKit/pull/64914