[WebGPU] Update CTS tests
WebKit/WebKit pull request #27205
Opened 2024-04-12 20:57 UTC by tadeuzagallo

#### 3a1614f52bba85e4e27eaa24e2c93e0abcfbecbe
<pre>
[WebGPU] Update CTS tests
<a href="https://bugs.webkit.org/show_bug.cgi?id=272604">https://bugs.webkit.org/show_bug.cgi?id=272604</a>
<a href="https://rdar.apple.com/126372152">rdar://126372152</a>

Reviewed by NOBODY (OOPS!).

Update WebGPU CTS to the latest revision using import-webgpu-cts.

* LayoutTests/http/tests/webgpu/common/framework/fixture.js:
Truncated due to commit message length, it was an auto import using import-webgpu-cts
</pre>

2024-04-12 20:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3a1614f52bba85e4e27eaa24e2c93e0abcfbecbe. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27205

2024-04-12 21:54 UTC, mwyrzykowski approved these changes

2024-04-12 21:57 UTC, mwyrzykowski commented on LayoutTests/http/tests/webgpu/common/internal/websocket_logger.js
> - * MANUALLY-GENERATED - DO NOT OVERWRITE with the webgpu-cts-import script.
Can we revert this file before merging please? I forgot about that

2024-04-12 21:57 UTC, mwyrzykowski requested changes
Can we revert 
LayoutTests/http/tests/webgpu/common/internal/websocket_logger.js

before merging? Otherwise the output doesn't match. I forgot about that issue.

2024-04-14 17:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/858622cda0baa446693e31e0788dbe9b3211b6a3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27205

2024-04-14 17:19 UTC, tadeuzagallo commented
I updated it just in case, but it looks like they added a flag and the logging is off by default, so maybe we can update the file in the future?

2024-04-14 18:34 UTC, mwyrzykowski approved these changes
Thank you!

2024-04-14 18:36 UTC, mwyrzykowski commented
> I updated it just in case, but it looks like they added a flag and the logging is off by default, so maybe we can update the file in the future?

Oh nice sorry didn’t realize that!

2024-04-15 11:40 UTC, webkit-commit-queue commented
Committed 277493@main (9c724a5a370c): <https://commits.webkit.org/277493@main>

Reviewed commits have been landed. Closing PR #27205 and removing active labels.

2024-04-15 11:40 UTC, merged