REGRESSION(274201@main): Error embedding AT-SPI socket: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner
WebKit/WebKit pull request #27741
Opened 2024-04-25 14:35 UTC by aperezdc

#### ec3d8dac190f860eb8145d3a025f367d81b08afe
<pre>
REGRESSION(274201@main): Error embedding AT-SPI socket: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner
<a href="https://bugs.webkit.org/show_bug.cgi?id=273245">https://bugs.webkit.org/show_bug.cgi?id=273245</a>

Reviewed by NOBODY (OOPS!).

Disable connecting to the accessibility socket when running the GTK4
port under Flatpak. This avoids spamming with warnings while still
having accessibility support in other typical setup i.e. for users of
distribution packages.

* Source/WebKit/UIProcess/gtk/WebPageProxyGtk.cpp:
(WebKit::WebPageProxy::bindAccessibilityTree):
</pre>

2024-04-25 14:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ec3d8dac190f860eb8145d3a025f367d81b08afe. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27741

2024-04-25 14:56 UTC, mcatanzaro approved these changes

2024-04-25 14:56 UTC, mcatanzaro requested changes
OK, Carlos Garcia says he sees the same warning outside of flatpak, so this didn't work after all. We must still not understand what's going on well enough....

2024-04-25 20:32 UTC, GeorgesStavracas commented
I'm investigating this issue. I think GTK3 + ATK also has the exact same problem in Flatpak sandboxes, the only difference is that it doesn't log a warning.

2024-04-26 05:40 UTC, carlosgcampos commented
I haven't said I've seen the same warning, I've said I've seen a warning, but I don't know if it's the same, next time I see it I'll check what it says exactly

2024-04-26 14:20 UTC, mcatanzaro commented
I think you'd know if you were seeing this one. This one prints every time a new web process gets created.

2024-04-26 14:20 UTC, mcatanzaro approved these changes

2024-04-26 19:32 UTC, webkit-commit-queue commented
Committed 278054@main (bfbc2e6fa7ad): <https://commits.webkit.org/278054@main>

Reviewed commits have been landed. Closing PR #27741 and removing active labels.

2024-04-26 19:32 UTC, merged

2024-04-26 21:57 UTC, aperezdc commented
Backported as commit 40ff10f0156bb3bae91a752df3f9984b0e464dfc into the 2.44 release branch.