Decoupling from-font resolution from FontCascadeFonts::primaryFont
WebKit/WebKit pull request #27829
Opened 2024-04-27 03:00 UTC by vitorroriz

#### 20ac840fb990a42748a7a8e76595b8e367bd9797
<pre>
Decoupling from-font resolution from FontCascadeFonts::primaryFont
<a href="https://bugs.webkit.org/show_bug.cgi?id=273339">https://bugs.webkit.org/show_bug.cgi?id=273339</a>
<a href="https://rdar.apple.com/127132471">rdar://127132471</a>

font-size-adjust from-font resolution was fixed by [1]. It now works correctly and
it uses the primary font for resolution. However, this patch changed FontCascadeFonts::primaryFont
to receive a mutable (non-const) FontCascadeDescription object, such that it could resolve the
from-font reference after the primary font is resolved.

This means that now FontCascadeFonts::primaryFont does two different things:
a) resolving and caching a font as the primary font
b) resolving from-font according to the primary font if necessary

The (a) part of primaryFont doesn&apos;t require a mutable FontCascadeDescription.
We can update FontCascadeDescription to have a method for resolving font-size-adjust
from-font at the point where we own a mutable FontCascadeDescription instead.

This allows us to compute the primaryFont itself from places where we only have access
to a const FontCascadeDescription. This is for example, required for solving
<a href="https://bugs.webkit.org/show_bug.cgi?id=273233">https://bugs.webkit.org/show_bug.cgi?id=273233</a>, where we need to access to primaryFont
from FontCascadeFonts::glyphDataForVariant

This patch should have no side effects, as it is a preparation
for solving 273233.

[1] <a href="https://commits.webkit.org/269041@main">https://commits.webkit.org/269041@main</a>

* Source/WebCore/css/ComputedStyleExtractor.cpp:
(WebCore::fontSizeAdjustFromStyle):
* Source/WebCore/platform/graphics/FontCascade.h:
(WebCore::FontCascade::primaryFont const):
* Source/WebCore/platform/graphics/FontCascadeDescription.cpp:
(WebCore::FontCascadeDescription::resolveFontSizeAdjustFromFontIfNeeded):
* Source/WebCore/platform/graphics/FontCascadeDescription.h:
* Source/WebCore/platform/graphics/FontCascadeFonts.h:
(WebCore::FontCascadeFonts::primaryFont):
* Source/WebCore/platform/graphics/FontSizeAdjust.h:
(WebCore::FontSizeAdjust::computeValue const):
(WebCore::FontSizeAdjust::resolveFromFontIfNeeded):
(WebCore::FontSizeAdjust::shouldResolveFromFont const):
(WebCore::FontSizeAdjust::resolve const): Deleted.
</pre>

2024-04-27 03:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20ac840fb990a42748a7a8e76595b8e367bd9797. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27829

2024-04-27 03:17 UTC, cdumez commented on Source/WebCore/platform/graphics/FontCascade.h
> +    const auto& font = protectedFonts()->primaryFont(m_fontDescription);
We normally omit the `const`.

2024-04-29 15:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0084934b51858b038843e1d2a831846137fb33b9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27829

2024-04-29 17:41 UTC, brentfulgham requested changes
I'd like you to restore the original `resolve` name, and avoid adding the `bool` to `FontSizeAdjust`, since it already stores the `value` in the equivalent of a `std::optional`.

2024-04-29 17:41 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool hasFromFontResolved { false };
I think this might be better with the name `hasResolvedFromFont`.

2024-04-29 17:41 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    std::optional<float> computeValue(float computedSize, const FontMetrics& fontMetrics) const
I think the original name `resolve` seems right, especially when it is used in a method called `resolveFromFontIfNeeded`.

2024-04-29 17:41 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool hasFromFontResolved { false };
We do not need this `bool` to indicate the font has been resolved -- `Markable` is a flavor of `std::optional`, so we just need to check it as a `bool`, or `value_or`, or whatever.

2024-04-29 17:41 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool shouldResolveFromFont() const { return isFromFont() && !hasFromFontResolved; }
So this should just be:
```
{ return isFromFont() && !value; }
```

2024-04-29 17:41 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +        hasFromFontResolved = true;
Once you assign `value` you don't need the separate `bool`. That's the whole point of `std::optional` (and therefore `Markable`).

2024-04-29 18:13 UTC, vitorroriz commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool hasFromFontResolved { false };
This is a good idea, the only issue is that in the case that the value can't be resolved due to the font not having a metric, we would always try to resolve it again.

That said, currently we would always assigned to metricValue before (default is  xHeight()) so I think we can still apply your suggestion.

2024-04-29 18:46 UTC, brentfulgham commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool hasFromFontResolved { false };
Ah! I see. So we can't tell the difference between the font being unresolved, and the font not having a metric? So the case would be a 'FromFont' type that doesn't have a relevant metric? Is that an allowable state?

2024-04-29 20:45 UTC, brentfulgham approved these changes
Thank you for updating the patch. r=me!

2024-04-29 21:26 UTC, vitorroriz commented on Source/WebCore/platform/graphics/FontSizeAdjust.h
> +    bool hasFromFontResolved { false };
I've edit my comment, I meant when font-size-adjust has no declared metric. However, looking again at specification, this is an optional parameter for the property, which is default to xHeight, so your suggestion is correct indeed.

2024-04-29 21:29 UTC, webkit-commit-queue commented
No reviewer information in commit message, blocking PR #27829

2024-04-29 21:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f53e50d179cb7f39f873cdb8ac376cd85f864072. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27829

2024-04-29 22:45 UTC, webkit-commit-queue commented
Committed 278130@main (f923c324da2f): <https://commits.webkit.org/278130@main>

Reviewed commits have been landed. Closing PR #27829 and removing active labels.

2024-04-29 22:45 UTC, merged