[GTK] Don't notify cursor when cursorRect is default-initialized
WebKit/WebKit pull request #27988
Opened 2024-05-01 17:45 UTC by taoky

#### e0f27ce086a12c63dc2695151b3087c2c369e6aa
<pre>
[GTK] Don&apos;t notify cursor when cursorRect is default-initialized
<a href="https://bugs.webkit.org/show_bug.cgi?id=218148">https://bugs.webkit.org/show_bug.cgi?id=218148</a>

Reviewed by NOBODY (OOPS!).

For input methods in preedit mode, editor state update functions could
get an IntRect that is default-initialized (with x, y, width and height
all 0), which makes the input method popup at the top left corner
instead of its expected position.

* Source/WebKit/UIProcess/API/glib/InputMethodFilter.cpp:
(WebKit::InputMethodFilter::notifyCursorRect): Modified to check if
cursorRect is default-initialized.
</pre>

2024-05-01 17:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e0f27ce086a12c63dc2695151b3087c2c369e6aa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27988

2024-05-01 18:02 UTC, mcatanzaro approved these changes
OK, looks good, thanks.

But consider moving the check up to below `!isEnabled() || !m_context`, since this check is simpler than the distance check?

2024-05-01 18:03 UTC, mcatanzaro commented
I see this is your first contribution. Nice, thanks!

2024-05-01 18:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7e16b47fc8ad966a144838e31030b5b68a079409. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/27988

2024-05-01 18:14 UTC, taoky commented
> OK, looks good, thanks.
> 
> But consider moving the check up to below `!isEnabled() || !m_context`, since this check is simpler than the distance check?

Thanks! I have moved that code above the distance check, and I'm going to sleep so my further response might be delayed for some hours.

2024-05-01 21:42 UTC, mcatanzaro requested changes
Hm, unfortunately there are test failures that we need to investigate/avoid:

/TestWebCore:Color.P3ConversionToSRGB, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/selection/listbox, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/value/basic, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/accessible/event-listener, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/selection/menulist

2024-05-02 06:24 UTC, taoky commented
> Hm, unfortunately there are test failures that we need to investigate/avoid:
> 
> /TestWebCore:Color.P3ConversionToSRGB, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/selection/listbox, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/value/basic, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/accessible/event-listener, /WebKitGTK/TestWebKitAccessibility:/webkit/WebKitAccessibility/selection/menulist

On my laptop these tests also fail before my change (with `run-gtk-tests`):

```
Unexpected failures (16)
    /WebKitGTK/TestWebKitAccessibility
        /webkit/WebKitAccessibility/accessible/state
        /webkit/WebKitAccessibility/accessible/event-listener
        /webkit/WebKitAccessibility/accessible/list-markers
        /webkit/WebKitAccessibility/accessible/state-changed/focus
        /webkit/WebKitAccessibility/text/iterator
        /webkit/WebKitAccessibility/text/attributes
        /webkit/WebKitAccessibility/text/list-markers
        /webkit/WebKitAccessibility/value/basic
        /webkit/WebKitAccessibility/action/basic
        /webkit/WebKitAccessibility/document/basic
        /webkit/WebKitAccessibility/document/load-events
        /webkit/WebKitAccessibility/selection/listbox
        /webkit/WebKitAccessibility/selection/menulist
        /webkit/WebKitAccessibility/table/basic
        /webkit/WebKitAccessibility/collection/get-matches
    /TestWebCore
        Color.P3ConversionToSRGB
```

I would try investigating why they fail though I don't think it's my fault...

2024-05-02 13:38 UTC, mcatanzaro approved these changes
Weird. The list I pasted was the lists of tests that failed with your changes and passed when your patch was reverted. i.e. the CI is smart enough to at least make sure your pull request is to blame before reporting the failure.

But maybe the tests are flaky and you just got really unlucky?

Anyway, all the CI bots are green now, so let's land.

2024-05-02 15:04 UTC, webkit-commit-queue commented
Committed 278261@main (f69bdc37c462): <https://commits.webkit.org/278261@main>

Reviewed commits have been landed. Closing PR #27988 and removing active labels.

2024-05-02 15:04 UTC, merged

2024-05-02 15:25 UTC, taoky commented
> Weird. The list I pasted was the lists of tests that failed with your changes and passed when your patch was reverted. i.e. the CI is smart enough to at least make sure your pull request is to blame before reporting the failure.
> 
> But maybe the tests are flaky and you just got really unlucky?
> 
> Anyway, all the CI bots are green now, so let's land.

Thank you!

The P3 conversion to SRGB test should have been fixed by a5997b3faeb5b7b4e4fcbb77779309e509dd6c92, and the accessibility tests are weird -- locally the test program seems not create the socket (`/run/user/1000/at-spi2-XXXXXX/socket`) and then all tests using at-spi are not working. I have no idea why at-spi does not work, but I believe that this has nothing to do with the `InputMethodFilter` part.