Remove no longer needed testing infrastructure from post-commit OpenSource
WebKit/WebKit pull request #28002
Opened 2024-05-01 20:56 UTC by robert-jenner

#### 2483f2cd592df83a4f90e71b3e3fb1d7ede5e51e
<pre>
Remove no longer needed testing infrastructure from post-commit OpenSource
<a href="https://rdar.apple.com/127372525">rdar://127372525</a>
<a href="https://bugs.webkit.org/show_bug.cgi?id=273562">https://bugs.webkit.org/show_bug.cgi?id=273562</a>

Reviewed by NOBODY (OOPS!).

This fix removes no longer needed testing infrastructure from the configuration. It also adds Ventura JSC testers.

* Tools/CISupport/build-webkit-org/config.json:
* Tools/CISupport/build-webkit-org/factories_unittest.py:
(TestExpectedBuildSteps):
* Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/Dashboard.js:
* Tools/CISupport/build-webkit-org/public_html/dashboard/Styles/Main.css:
(table.queue-grid tr.platform.macos-monterey img.logo): Deleted.
* Tools/CISupport/build-webkit-org/steps_unittest.py:
</pre>

2024-05-01 20:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2483f2cd592df83a4f90e71b3e3fb1d7ede5e51e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28002

2024-05-01 22:06 UTC, ryanhaddad requested changes
Left a few comments, also need to make changes to `Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js` for the queues that are moving.

2024-05-01 22:06 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                  { "name": "bot632", "platform": "*" },
This should be platform: mac-ventura and be moved to the section with the other Ventura bots.

2024-05-01 22:06 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                  { "name": "bot111", "platform": "*" },
This should be platform: mac-ventura and be moved to the section with the other Ventura bots.

2024-05-01 22:06 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                  { "name": "bot105", "platform": "*" },
This should be platform: mac-ventura and be moved to the section with the other Ventura bots.

2024-05-01 22:06 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                  { "name": "bot603", "platform": "*" },
This should be platform: mac-ventura and be moved to the section with the other Ventura bots.

2024-05-01 22:48 UTC, robert-jenner commented
> Left a few comments, also need to make changes to `Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js` for the queues that are moving.

I totally did this, but I forgot to save it as part of this PR. So that update is coming....

2024-05-01 23:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/60450d09c0d932a20b746e1e18432bdf7e479ba3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28002

2024-05-02 00:40 UTC, ryanhaddad approved these changes

2024-05-02 00:43 UTC, webkit-commit-queue commented
Committed 278238@main (d0941d28f74c): <https://commits.webkit.org/278238@main>

Reviewed commits have been landed. Closing PR #28002 and removing active labels.

2024-05-02 00:43 UTC, merged