[JSC] Close the sync iterator when rejected promise is yielded in AsyncFromSyncIterator
WebKit/WebKit pull request #28171
Opened 2024-05-06 13:18 UTC by sosukesuzuki

#### 91756b7c51929f4432de445494d10abd966e82d5
<pre>
[JSC] Close the sync iterator when rejected promise is yielded in AsyncFromSyncIterator
Need the bug URL (OOPS!).

Reviewed by NOBODY (OOPS!).

This patch implements the new normative change[1].
When the AsyncFromSyncIterator yields a rejected promise, it calls the return method of the
underlying syncIterator and closes it.

[1]: <a href="https://github.com/tc39/ecma262/pull/2600">https://github.com/tc39/ecma262/pull/2600</a>

* JSTests/test262/expectations.yaml:
* Source/JavaScriptCore/builtins/AsyncFromSyncIteratorPrototype.js:
(linkTimeConstant.asyncFromSyncIteratorOnRejected):
(return):
(throw):
</pre>

2024-05-06 13:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/92753c477d3e497930f79b8193cddaa59d81b28a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28171

2024-05-06 15:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3298720d95661302576728292143d0e8fafaa3cc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28171

2024-05-06 21:29 UTC, Constellation requested changes
bind is costly operation, so it is not fine. You need to piggy back this as a context somehow.

2024-05-07 00:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3ed45f771865b88071e6b8c818ad6fd3a67db2e4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28171

2024-05-07 00:53 UTC, sosukesuzuki commented on Source/JavaScriptCore/builtins/AsyncFromSyncIteratorPrototype.js
> +    });
@Constellation  I've fixed to create a closure only once inside AsyncFromSyncIterator constructor. What do you think?

2024-05-28 09:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a2102368131156fac20891ba0c3148827f365737. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28171

2024-09-06 08:36 UTC, closed without merging