[JSC] Disable JIT for Windows
WebKit/WebKit pull request #28269
Opened 2024-05-08 01:41 UTC by fujii

#### b925685e5b7d60f9a24ed068586729f8c938346f
<pre>
[JSC] Disable JIT for Windows
<a href="https://bugs.webkit.org/show_bug.cgi?id=254478">https://bugs.webkit.org/show_bug.cgi?id=254478</a>

Reviewed by NOBODY (OOPS!).

Windows JSC JIT is crashing now. &lt;<a href="https://webkit.org/b/273854">https://webkit.org/b/273854</a>&gt;
Disabled JIT for Windows temporarily.

* LayoutTests/platform/wincairo/TestExpectations:
* Source/cmake/OptionsWin.cmake:
* Source/cmake/WebKitFeatures.cmake:
</pre>

2024-05-08 01:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b925685e5b7d60f9a24ed068586729f8c938346f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28269

2024-05-08 22:53 UTC, clopez approved these changes

2024-05-09 01:48 UTC, rkirsling requested changes

2024-05-09 01:48 UTC, rkirsling commented on Source/cmake/OptionsWin.cmake
> -endif ()
Since we ultimately intend to re-enable it, it seems better to just remove the `if` here and leave WebKitFeatures alone.

2024-05-09 01:56 UTC, webkit-commit-queue commented
Committed 278545@main (da80566db803): <https://commits.webkit.org/278545@main>

Reviewed commits have been landed. Closing PR #28269 and removing active labels.

2024-05-09 01:56 UTC, merged