Check that slot + descriptor accesses are made under an Accessor attribute
WebKit/WebKit pull request #28414
Opened 2024-05-10 22:39 UTC by Achierius

#### bce4562bde47db4de45ec667afe9ee503b14a2a0
<pre>
Check that slot + descriptor accesses are made under an Accessor attribute
<a href="https://bugs.webkit.org/show_bug.cgi?id=273576">https://bugs.webkit.org/show_bug.cgi?id=273576</a>
<a href="https://rdar.apple.com/127365044">rdar://127365044</a>

Reviewed by NOBODY (OOPS!).

This should always be the case, so adding asserts here helps document
the invariant and catch bugs elsewhere in the code. We can&apos;t add a
RELEASE_ASSERT right where we want to due to the performance impact,
but adding them here covers the most important code-path with no
measurable slowdown.

* Source/JavaScriptCore/runtime/JSObject.cpp:
(JSC::ordinarySetWithOwnDescriptor):
* Source/JavaScriptCore/runtime/PropertySlot.h:
(JSC::PropertySlot::getValue const):
</pre>

2024-05-10 22:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bce4562bde47db4de45ec667afe9ee503b14a2a0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28414

2024-05-11 01:06 UTC, MenloDorian approved these changes
r=me

2024-05-11 01:38 UTC, Constellation requested changes
Please do not use RELEASE_ASSERT in `PropertySlot::getValue`, which is very hot function.

2024-05-14 00:04 UTC, MenloDorian commented
After some internal discussion, we decided that this is not worth doing.  Will close.

2024-05-14 00:04 UTC, closed without merging