[GStreamer][MSE] SleepDisabler not reliably created when playing YouTube videos, may be created long after video playback starts. HTMLMediaElement::m_player is unexpectedly nullptr!
WebKit/WebKit pull request #28770
Opened 2024-05-19 17:08 UTC by philn

#### de831a564c9f3f361f8b43f4f860bad59de3e734
<pre>
[GStreamer][MSE] SleepDisabler not reliably created when playing YouTube videos, may be created long after video playback starts. HTMLMediaElement::m_player is unexpectedly nullptr!
<a href="https://bugs.webkit.org/show_bug.cgi?id=219354">https://bugs.webkit.org/show_bug.cgi?id=219354</a>

Reviewed by NOBODY (OOPS!).

By notifying the MediaPlayer of successful GStreamer pipeline state changes the HTMLMediaElement
gets another opportunity to update the sleep disabling state. This is done already in the
MediaPlayerPrivateGStreamer::updateStates() method, but for some reason the MSE player has a
different implementation of that method.

* Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp:
(WebCore::MediaPlayerPrivateGStreamerMSE::updateStates):
</pre>

2024-05-19 17:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/de831a564c9f3f361f8b43f4f860bad59de3e734. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-19 17:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cde344bf5abfa6bf5d1b4db2f3aeb79d2c2b9d58. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-19 18:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/355719fe05154113ddd4f8d14632275e7582c7c9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-20 08:04 UTC, calvaris approved these changes

2024-05-20 08:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cdee5cfd7dfee2fa136ac7d00c3ccb6fd68bd0b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-20 09:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d235ea31b869cb984d8590a0ecc49f18f4f081ac. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-20 15:35 UTC, philn commented
@calvaris Can you re-review please? I had to rewrite the patch to avoid doing the notification from `updateStates()`... that was triggering some test failure in the ManagedMSE tests.

2024-05-21 07:26 UTC, calvaris reviewed
I would prefer that @ntrrgc reviews this as she has a better picture of the MSE player reworks but it this can't wait for her, I would need that you explain to me which problem you are trying to solve exactly and why your code solves it.

2024-05-21 07:26 UTC, calvaris commented on Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp
> +    gst_element_get_state(pipeline(), &state, 0, 0);
The first 0 should be a nullptr.

2024-05-21 08:28 UTC, philn commented
This needs another iteration.

2024-05-22 11:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa04fb73a857c0fe56575124233204e9001c4674. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-27 18:55 UTC, philn commented
@ntrrgc can you review this please? 🙏🏻

2024-05-28 03:59 UTC, jyavenard requested changes
That the machine can go to sleep when using MSE and the MediaSource isn't ended is on purpose. We don't want slow network stalling prevent the machine to sleep.
If MediaSource.endOfStream() had been called.

The handling of the media element readyState (and as such playback state), is handled in MediaSource::monitorSourceBuffers and match the specs to the letter.

The reason for not letting it sleep was added in https://bugs.webkit.org/show_bug.cgi?id=140468

2024-05-28 07:34 UTC, philn commented
Is Safari preventing display sleep when playing YT videos?

2024-05-28 08:22 UTC, philn commented
> The handling of the media element readyState (and as such playback state), is handled in MediaSource::monitorSourceBuffers and match the specs to the letter.

Sure, but I also see the AVF MSE player calling readyStateChanged on the MediaPlayer, so the ready state handling is not entirely done at the MediaSource level.

As already stated in the commit message, in our case the GStreamer pipeline state transition to playing state takes some time and that resulted in the MediaPlayer/MediaElement not always being notified playback started. Display sleep would then remain enabled because the MediaPlayerPrivateGStreamerMSE `timeIsProgressing()` would return false even though playback started.

What change are you requesting?

2024-05-30 09:25 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/eea188830775f1705085cd555a4bbc6699d9f99e)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/53677 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/33043 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/6193 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/56958 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/4403 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/55981 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/40529 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/4233 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/56958 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/59/builds/4403 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/55774 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/40529 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/6193 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/56958 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/40529 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/6193 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/2558 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/40529 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/6193 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/58552 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/28840 "Build is in progress. Recent messages:OS: Sonoma (14.4.1), Xcode: 15.3") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/61/builds/4233 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/58552 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/30040 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/6193 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/58552 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/30972 "Build is in progress. Recent messages:Running configuration") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/29817 "Build is in progress. Recent messages:Running configuration") | | | </details>

2024-05-30 11:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/17221f6fb8331968446547ae6e68fdfb4fc69b83. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-05-31 09:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f76a432fe645958bda185f55d0e62b80b80d56f1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28770

2024-06-10 11:51 UTC, philn commented
@ntrrgc or @calvaris r? 🙏🏻

2024-06-12 07:26 UTC, calvaris approved these changes

2024-06-12 08:48 UTC, webkit-commit-queue commented
Committed 279943@main (6a650e644b1c): <https://commits.webkit.org/279943@main>

Reviewed commits have been landed. Closing PR #28770 and removing active labels.

2024-06-12 08:48 UTC, merged