[WebCore] Remove old libxslt workaround
WebKit/WebKit pull request #28970
Opened 2024-05-23 05:19 UTC by AtariDreams

<pre>
[WebCore] Remove old libxslt workaround
https://bugs.webkit.org/show_bug.cgi?id=274573

Reviewed by NOBODY (OOPS!).

libxslt 1.1.13 shipped over a decade ago. We can
remove this code smell now.

* Source/WebCore/xml/XSLTProcessorLibxslt.cpp:
  (WebCore::XSLTProcessor::transformToString):
  Remove old workaround.
</pre>

2024-05-23 05:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/597ea9200ac25064064e67612042f8447a886625. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-18 19:45 UTC, RSilicon commented
Any updates?

2024-08-18 19:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/be3ebe81bb8d0f85aaea8639f899b2bb2c52a29c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-20 15:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4c503908864fb319d5713f1a3b8ade757a038e3d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 01:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9428b8cbd1589871d2f71336768ae424060eaf31. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 10:39 UTC, aperezdc requested changes
From the point of view of the GTK and WPE ports, you would also need to change `Source/cmake/Options{GTK,WPE}.cmake` to check that the libxslt found is version 1.1.13 or newer&mdash;currently we check for 1.1.7 there.

2024-08-26 14:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ebb65320025dd0f2966be8cb1560cccd57a61576. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 14:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/17ba10d7dffe34351c1e4887f684f24c130ae6d3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 14:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9edfe2524a7d0aaee92ff9bec1fed85206ce8fb6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 17:25 UTC, darinadler commented on Source/cmake/OptionsGTK.cmake
> +    find_package(LibXslt 1.1.42 REQUIRED)
EWS seems to have 1.1.38

2024-08-26 17:25 UTC, darinadler commented on Source/cmake/OptionsMac.cmake
> +find_package(LibXslt 1.1.42 REQUIRED)
My macOS Sequoia system seems to have 1.1.35

2024-08-26 17:26 UTC, darinadler requested changes
Need to figure out the right minimum version. Maybe `1.1.13` is the way to go for now?

2024-08-26 17:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/383a60c20ac03dc0b4b76c7706a97f12f350e9b0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 17:53 UTC, RSilicon commented
> > Need to figure out the right minimum version. Maybe 1.1.13 is the way to go for now?
> 
> Yes indeed.
> 
> Requiring 1.1.42 without actually depending on something new in 1.1.42 is not cool.

New idea: make it 1.1.32 to match cmakeWin for consistency. Two birds with one stone.

2024-08-26 17:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1905e27ca8798b890303ef326cccbbc549624cc7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-26 22:12 UTC, aperezdc commented
> > > Need to figure out the right minimum version. Maybe 1.1.13 is the way to go for now?
> > 
> > 
> > Yes indeed.
> > Requiring 1.1.42 without actually depending on something new in 1.1.42 is not cool.
> 
> New idea: make it 1.1.32 to match cmakeWin for consistency. Two birds with one stone.

For the GTK and WPE ports we have a [policy regarding external dependencies](https://docs.webkit.org/Ports/WebKitGTK%20and%20WPE%20WebKit/DependenciesPolicy.html), and while libxslt 1.1.34 is present in both Ubuntu 22.04 and Debian Bookworm (which we currently support) we try to depend on the oldest version of libraries that provide all the features needed by WebKit&mdash;for as long as reasonable.

Therefore, let's leave the required version 1.1.13 for the GTK and WPE ports, as already requested by @mcatanzaro.

2024-08-27 00:27 UTC, mcatanzaro commented
(If you increase the minimum unnecessarily, we just have to add downstream patches to change the minimum version and nothing else. I still have to make this work with libxslt 1.1.28....)

2024-08-27 02:23 UTC, RSilicon commented
> (If you increase the minimum unnecessarily, we just have to add downstream patches to change the minimum version and nothing else. I still have to make this work with libxslt 1.1.28....)

Thanks for this extra context.

2024-08-27 02:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/74d6f1873ea2c2af3659be7a77d2221940ed875b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-27 12:53 UTC, aperezdc reviewed
Patch LGTM from the POV of the GTK and WPE ports now that CMake checks for version `1.1.13`.

The Windows port was already checking for a newer version so I assume there won't be any problem on their end (cc / @donny-dont).

I'll leave the final patch approval to the Apple folks.

2024-08-27 14:08 UTC, darinadler approved these changes

2024-08-27 14:16 UTC, darinadler approved these changes
It’s a bit peculiar to say “code smell” here. I’m honestly not even sure it’s precisely the right term for “remove [harmless] workaround we no longer need”. We’d typically reserve that term for something more consequential if we’d use it at all.

2024-08-27 15:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/12e18eadb92de03b3d307645d80617a047d98c85. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/28970

2024-08-27 18:49 UTC, merged