REGRESSION (iPadOS 17.5): Audio distortion occurs when using AudioContext with a sample rate of 44100Hz and an AudioWorklet
WebKit/WebKit pull request #29048
Opened 2024-05-24 13:25 UTC by jyavenard

#### 1db9959072f632b0e077814a211bce6ad6085b8f
<pre>
REGRESSION (iPadOS 17.5): Audio distortion occurs when using AudioContext with a sample rate of 44100Hz and an AudioWorklet
<a href="https://bugs.webkit.org/show_bug.cgi?id=274507">https://bugs.webkit.org/show_bug.cgi?id=274507</a>
<a href="https://rdar.apple.com/128551401">rdar://128551401</a>

Reviewed by NOBODY (OOPS!).

Following 275262@main, we shared an underlying AudioContext for all AudioContext that have the same
number of channels and sampling rate.
When an AudioWorklet isn&apos;t added to the AudioContext, the rendering is done on a render thread.
But when an AudioWorklet exists, the rendering is performed by the AudioWorkletProcessor which will
be executed on the AudioWorkletGlobalScope.
When the sampling rate of the AudioContext matched the default audio hardware sampling rate (48Khz),
doing it all in the main render thread was okay (though with unnecessary task dispatching), but if
the rate didn&apos;t, an intermediary AudioDestinationResampler was created.
The SharedAudioDestination if used then, would perform the resampling in the audio render thread
and pass the data back to the AudioWorkletGlobalScope to be processed by the AudioWorkletProcessor.
This made some very audible interruptions.

To work around this problem, we only use a SharedAudioDestination if no AudioWorklet exists.
If the AudioContext had first been started without an AudioWorklet, then suspended, and an AudioWorklet
is added, we will tear down the existing SharedAudioDestination and create an unshared AudioDestination.

* Source/WebCore/Modules/webaudio/DefaultAudioDestinationNode.cpp:
(WebCore::DefaultAudioDestinationNode::createDestination):
(WebCore::DefaultAudioDestinationNode::hasAudioWorklet):
(WebCore::DefaultAudioDestinationNode::startRendering):
(WebCore::DefaultAudioDestinationNode::resume):
* Source/WebCore/Modules/webaudio/DefaultAudioDestinationNode.h:
* Source/WebCore/platform/MediaStrategy.h:
* Source/WebCore/platform/audio/SharedAudioDestination.h: Make member atomic, as it&apos;s set on the main thread, and can be read on the render thread.
* Source/WebCore/platform/audio/cocoa/AudioDestinationCocoa.cpp:
(WebCore::AudioDestination::create): Don&apos;t wrap an AudioDestination into a SharedAudioDestination here, instead do so in the WebMediaStrategy.
* Source/WebKit/WebProcess/GPU/media/WebMediaStrategy.cpp:
(WebKit::WebMediaStrategy::createAudioDestination):
* Source/WebKit/WebProcess/GPU/media/WebMediaStrategy.h:
* Source/WebKitLegacy/mac/WebCoreSupport/WebPlatformStrategies.mm:
</pre>

2024-05-24 13:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1db9959072f632b0e077814a211bce6ad6085b8f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29048

2024-05-24 16:31 UTC, jernoble commented
I don't think this is necessary. The underlying problem is that the AudioWorklet dispatch is non-synchronous, so the worklet (usually) doesn't provide data in time (especially if it needs to resample).

2024-05-24 16:32 UTC, jernoble requested changes
Converting the non-synchronous dispatch to a synchronous one seems to fix this bug:

```
diff --git a/Source/WebCore/platform/audio/SharedAudioDestination.cpp b/Source/WebCore/platform/audio/SharedAudioDestination.cpp
index 3c1fb98abacf..ab5c46b7d91c 100644
--- a/Source/WebCore/platform/audio/SharedAudioDestination.cpp
+++ b/Source/WebCore/platform/audio/SharedAudioDestination.cpp
@@ -285,9 +285,13 @@ void SharedAudioDestination::sharedRender(AudioBus* sourceBus, AudioBus* destina
     if (!m_dispatchToRenderThread)
         callRenderCallback(sourceBus, destinationBus, numberOfFrames, outputPosition);
     else {
-        m_dispatchToRenderThread([protectedThis = Ref { *this }, sourceBus = RefPtr { sourceBus }, destinationBus = RefPtr { destinationBus }, numberOfFrames, outputPosition]() mutable {
+        // dispatchToRenderThread() does not run synchronously; it returns before the inner call has been executed.
+        Semaphore renderCallbackSemaphore { 0 };
+        m_dispatchToRenderThread([&renderCallbackSemaphore, protectedThis = Ref { *this }, sourceBus = RefPtr { sourceBus }, destinationBus = RefPtr { destinationBus }, numberOfFrames, outputPosition]() mutable {
             protectedThis->callRenderCallback(sourceBus.get(), destinationBus.get(), numberOfFrames, outputPosition);
+            renderCallbackSemaphore.signal();
         });
+        renderCallbackSemaphore.wait();
     }
 }
 ```

2024-05-24 22:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3fb71fd60bb6e787841ffd61131cb3ab58b27250. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29048

2024-05-24 23:43 UTC, jyavenard commented
> Converting the non-synchronous dispatch to a synchronous one seems to fix this bug:
> 
> ```
> diff --git a/Source/WebCore/platform/audio/SharedAudioDestination.cpp b/Source/WebCore/platform/audio/SharedAudioDestination.cpp
> index 3c1fb98abacf..ab5c46b7d91c 100644
> --- a/Source/WebCore/platform/audio/SharedAudioDestination.cpp
> +++ b/Source/WebCore/platform/audio/SharedAudioDestination.cpp
> @@ -285,9 +285,13 @@ void SharedAudioDestination::sharedRender(AudioBus* sourceBus, AudioBus* destina
>      if (!m_dispatchToRenderThread)
>          callRenderCallback(sourceBus, destinationBus, numberOfFrames, outputPosition);
>      else {
> -        m_dispatchToRenderThread([protectedThis = Ref { *this }, sourceBus = RefPtr { sourceBus }, destinationBus = RefPtr { destinationBus }, numberOfFrames, outputPosition]() mutable {
> +        // dispatchToRenderThread() does not run synchronously; it returns before the inner call has been executed.
> +        Semaphore renderCallbackSemaphore { 0 };
> +        m_dispatchToRenderThread([&renderCallbackSemaphore, protectedThis = Ref { *this }, sourceBus = RefPtr { sourceBus }, destinationBus = RefPtr { destinationBus }, numberOfFrames, outputPosition]() mutable {
>              protectedThis->callRenderCallback(sourceBus.get(), destinationBus.get(), numberOfFrames, outputPosition);
> +            renderCallbackSemaphore.signal();
>          });
> +        renderCallbackSemaphore.wait();
>      }
>  }
> ```

But do we want to block all AudioContext sharing this AudioDestination to be blocking on the one AudioWorklet to do its thing?

in effect we would be serialising every single render that have the same number of channels and sampling rate. 
the AudioWorklet would provide little advantage to a main AudioContext

2024-05-27 03:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c31d7df4499607ff2c6928c8631f76a13d967abc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29048

2024-05-28 16:08 UTC, jernoble approved these changes

2024-05-28 23:28 UTC, webkit-commit-queue commented
Committed 279409@main (d72323075072): <https://commits.webkit.org/279409@main>

Reviewed commits have been landed. Closing PR #29048 and removing active labels.

2024-05-28 23:28 UTC, merged