Add entitlement to give the WebProcess a higher jetsam limit
WebKit/WebKit pull request #29042
Opened 2024-05-24 06:37 UTC by dcrousso

#### f0e281b2885ed9c8776156b0e2c53c226143f8d4
<pre>
Add entitlement to give the WebProcess a higher jetsam limit
<a href="https://bugs.webkit.org/show_bug.cgi?id=274637">https://bugs.webkit.org/show_bug.cgi?id=274637</a>

Reviewed by NOBODY (OOPS!).

Lots of websites (and apps that use web content) could probably benefit from a higher jetsam limit &lt;<a href="https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit">https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit</a>&gt;, similar to how a larger virtual address space is helpful/necessary (see &lt;<a href="https://commits.webkit.org/246553@main">https://commits.webkit.org/246553@main</a>&gt;, &lt;<a href="https://commits.webkit.org/270484@main">https://commits.webkit.org/270484@main</a>&gt;, and &lt;<a href="https://commits.webkit.org/271394@main">https://commits.webkit.org/271394@main</a>&gt;).

* Source/JavaScriptCore/Scripts/process-entitlements.sh:
* Source/WebKit/Scripts/process-entitlements.sh:
</pre>
https://github.com/WebKit/WebKit/commit/f0e281b2885ed9c8776156b0e2c53c226143f8d4

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/52955 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/32292 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/5442 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/56234 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/3678 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/39110 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/3403 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/42958 "Passed tests") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/2365 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/55053 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/30039 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/45711 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/24081 "Passed tests") | 
| [✅ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/52799 "Passed tests") | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/27088 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/64/builds/3030 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/1837 "Built successfully") | 
| [✅ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/46309 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/48944 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/3187 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/57828 "Built successfully") | 
| [✅ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/52468 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/28096 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/3189 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/50353 "Passed tests") | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/29316 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/45927 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/49652 "Passed tests") | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/30235 "Built successfully") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/64772 "Built successfully") | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/29070 "Built successfully") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12298 "Passed tests") |

2024-05-24 06:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f0e281b2885ed9c8776156b0e2c53c226143f8d4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29042

2024-05-24 06:39 UTC, dcrousso commented
im not entirely sure how to test this, but conceptually it strikes me as something that'd be beneficial for a lot of cases, so if anyone has any suggestions for verifying this using OpenSource stuff (i.e. not AppleInternal) then id appreciate it :)

2024-05-24 16:57 UTC, aproskuryakov requested changes
WebContent jetsam limits are deliberately defined elsewhere. I'm not aware of how this particular entitlement works, but it doesn't seem like it can possibly do us any good given that.

2024-05-31 18:09 UTC, MenloDorian commented
hi Devin, to follow up on this, we've researched the use of that entitlement, and indeed, it does not change anything for the WebContent process.  So, there's no point in adding it.  Thanks.

2024-06-01 00:31 UTC, dcrousso commented
ah gotcha.  thanks for taking a look!

2024-06-01 00:31 UTC, closed without merging