isTestServerTrust() in ServiceWorkerBasic.mm should use WTF::bridge_cast<>
WebKit/WebKit pull request #29059
Opened 2024-05-24 16:58 UTC by ddkilzer

#### 90640da0da75182bbe5fce97a1f98cd6d0e3fc67
<pre>
isTestServerTrust() in ServiceWorkerBasic.mm should use WTF::bridge_cast&lt;&gt;
&lt;<a href="https://bugs.webkit.org/show_bug.cgi?id=274659">https://bugs.webkit.org/show_bug.cgi?id=274659</a>&gt;
&lt;<a href="https://rdar.apple.com/128686657">rdar://128686657</a>&gt;

Reviewed by Darin Adler.

* Tools/TestWebKitAPI/Tests/WebKitCocoa/ServiceWorkerBasic.mm:
- Switch from adoptNS() to adoptCF().get(), and use
  WTF::bridge_cast&lt;&gt;() instead of (NSString *) to toll-free bridge the
  CFStringRef to NSString.

Canonical link: <a href="https://commits.webkit.org/279307@main">https://commits.webkit.org/279307@main</a>
</pre>

2024-05-24 18:01 UTC, darinadler requested changes

2024-05-24 18:01 UTC, darinadler commented on Tools/TestWebKitAPI/Tests/WebKitCocoa/ServiceWorkerBasic.mm
> +    if (![adoptNS(bridge_cast(SecCertificateCopySubjectSummary(certificate))) isEqualToString:@"Me"])
Seems like we must do an `adoptCF` here, not an `adoptNS`. Then we can do `bridge_cast` on the result of `get()`.

2024-05-24 18:43 UTC, ddkilzer commented on Tools/TestWebKitAPI/Tests/WebKitCocoa/ServiceWorkerBasic.mm
> +    if (![adoptNS(bridge_cast(SecCertificateCopySubjectSummary(certificate))) isEqualToString:@"Me"])
Yeah, that's a better option in the long run.

2024-05-24 18:45 UTC, darinadler approved these changes

2024-05-25 03:27 UTC, webkit-commit-queue commented
Committed 279307@main (90640da0da75): <https://commits.webkit.org/279307@main>

Reviewed commits have been landed. Closing PR #29059 and removing active labels.

2024-05-25 03:27 UTC, merged