[Win] Enable HAVE_INT128_T
WebKit/WebKit pull request #29168
Opened 2024-05-28 07:31 UTC by fujii

#### 777cac1f310a24b84745858a88d24f605f1f77af
<pre>
[Win] Enable HAVE_INT128_T
<a href="https://bugs.webkit.org/show_bug.cgi?id=274765">https://bugs.webkit.org/show_bug.cgi?id=274765</a>

Reviewed by NOBODY (OOPS!).

Clang-cl has a bug that it generates incorrectly-aligned movaps
instructions. &lt;<a href="https://github.com/llvm/llvm-project/issues/55844">https://github.com/llvm/llvm-project/issues/55844</a>&gt;

We have to specify &apos;alignas(16)&apos; for int128 types.

* Source/WTF/wtf/Int128.h:
* Source/WTF/wtf/UUID.h:
* Source/cmake/OptionsMSVC.cmake:
</pre>

2024-05-28 07:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/777cac1f310a24b84745858a88d24f605f1f77af. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29168

2024-05-28 07:50 UTC, Constellation reviewed
Is it possible to define `UInt128` and `Int128` as `__uint128_t` with `alignas(16)` on MSVC clang environment?

2024-05-28 07:55 UTC, fujii commented
Like this?

~~~patch
diff --git a/Source/WTF/wtf/Int128.h b/Source/WTF/wtf/Int128.h
index 52347dc7e9f1..5b92bf3d75e0 100644
--- a/Source/WTF/wtf/Int128.h
+++ b/Source/WTF/wtf/Int128.h
@@ -1250,8 +1250,8 @@ constexpr Int128Impl operator>>(Int128Impl lhs, int amount) {
 }
 
 #if HAVE(INT128_T)
-using UInt128 = __uint128_t;
-using Int128 = __int128_t;
+using UInt128 = alignas(16) __uint128_t;
+using Int128 = alignas(16) __int128_t;
 #else
 using UInt128 = UInt128Impl;
 using Int128 = Int128Impl;
~~~

This can't compile.

~~~
C:\webkit\Source\WTF\wtf/Int128.h(1253,17): error: 'alignas' attribute cannot be applied to types
 1253 | using UInt128 = alignas(16) __uint128_t;
      |                 ^
C:\webkit\Source\WTF\wtf/Int128.h(1254,16): error: 'alignas' attribute cannot be applied to types
 1254 | using Int128 = alignas(16) __int128_t;
      |                ^
2 errors generated.
~~~

2024-05-28 07:56 UTC, Constellation commented
@fujii Does it work? `using UInt128 = __attribute__((aligned(16))) __uint128_t;`

2024-05-28 07:57 UTC, Constellation commented
(Since this is clang-cl workaround, we can use clang specific attributes)

2024-05-28 08:00 UTC, Constellation commented
Yeah, aligned attribute (GCC / clang extension) should work with using / typedef https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#Common-Type-Attributes-1

2024-05-28 08:02 UTC, Constellation commented
When changing it, let's narrow the scope to clang-cl for now. The other configuration work fine. So let's use

```
#if HAVE(INT128_T)
#if COMPILER(MSVC)
using UInt128 = __attribute__((aligned(16))) __uint128_t;
using Int128 = __attribute__((aligned(16))) __int128_t;
#else
using UInt128 = __uint128_t;
using Int128 = __int128_t;
#end
#else
...
```

2024-05-28 08:28 UTC, Constellation commented
@fujii Can you explain why? It gets compiled in https://gcc.godbolt.org/z/ej87hvd6n
The current approach is requiring scattering this attribute to all places using UInt128. So I don't think this path is viable, and if `__attribute__` does not work, then I think we need to give up using `UInt128` on clang-cl until the LLVM bug gets fixed.

2024-05-28 08:31 UTC, Constellation commented
OK, I think
```
typedef __uint128_t UInt128 __attribute__((aligned(16)));
```
works

2024-05-28 08:31 UTC, Constellation commented
https://gcc.godbolt.org/z/Kbs8Yfve8 (for example, setting 64 for alignment).

2024-05-28 08:36 UTC, Constellation requested changes
Let's annotate `UInt128` / `Int128` with aligned attribute with typedef.
I think putting alignas to all fields using the above types do not work. It also does not guarantee that it works with the pattern passing `UInt128` / `Int128` directly to some parameters. So we need to put alignment requirements to `UInt128` / `Int128` directly.

2024-05-28 14:35 UTC, achristensen07 approved these changes

2024-05-28 20:32 UTC, fujii commented
Supprisingly, your `typedef` trick works. Thank you very much. Will revise the patch.
`alignof(__uint128_t)` is also 16 for clang-cl. clang-cl knows the correct alignment of `__uint128_t`.

2024-05-28 20:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b3c532cb7dd256343325bf7eaa8a32dbe0351123. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29168

2024-05-28 22:07 UTC, Constellation approved these changes
r=me

2024-05-29 01:42 UTC, webkit-commit-queue commented
Committed 279419@main (d06b72cc3780): <https://commits.webkit.org/279419@main>

Reviewed commits have been landed. Closing PR #29168 and removing active labels.

2024-05-29 01:42 UTC, merged