[Navigation] Add fully active document check to the "perform shared checks" algorithm
WebKit/WebKit pull request #29292
Opened 2024-05-30 07:52 UTC by rwlbuis

#### fa8f20ffa7fa6bc5895208058973660af78988ec
<pre>
[Navigation] Add fully active document check to the &quot;perform shared checks&quot; algorithm
<a href="https://bugs.webkit.org/show_bug.cgi?id=274890">https://bugs.webkit.org/show_bug.cgi?id=274890</a>

Reviewed by NOBODY (OOPS!).

WIP.

[1] <a href="https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigateevent-perform-shared-checks">https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigateevent-perform-shared-checks</a>

* LayoutTests/imported/w3c/web-platform-tests/navigation-api/navigate-event/intercept-detach-expected.txt:
* Source/WebCore/page/NavigateEvent.cpp:
(WebCore::NavigateEvent::intercept):
(WebCore::NavigateEvent::scroll):
* Source/WebCore/page/NavigateEvent.h:
* Source/WebCore/page/NavigateEvent.idl:
</pre>

2024-05-30 07:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa8f20ffa7fa6bc5895208058973660af78988ec. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29292

2024-05-30 14:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/792ed995f2dcf03020d1253684919bf8cbf05a15. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29292

2024-05-30 15:49 UTC, TingPing requested changes
LGTM (Did not mean to hit request changes...)

2024-05-31 21:30 UTC, achristensen07 approved these changes

2024-06-01 10:19 UTC, webkit-commit-queue commented
Committed 279613@main (b50dcf22f189): <https://commits.webkit.org/279613@main>

Reviewed commits have been landed. Closing PR #29292 and removing active labels.

2024-06-01 10:19 UTC, merged