Allow TmpPair in Air forms
WebKit/WebKit pull request #29545
Opened 2024-06-05 15:46 UTC by aoikonomopoulos

#### a7357cff95e9b333d1bc0bf9590a3cfa3a31a966
<pre>
Allow TmpPair in Air forms
<a href="https://bugs.webkit.org/show_bug.cgi?id=275164">https://bugs.webkit.org/show_bug.cgi?id=275164</a>

Reviewed by NOBODY (OOPS!).

Let the parser accept TmpPair in Air forms. Implements a pair of Air
forms that use TmpPair as an example. This is only meaningful on
32-bits; if a TmpPair-using form were to accidentally be defined on
64-bits, the generated code would not compile.

* Source/JavaScriptCore/assembler/MacroAssemblerARMv7.h:
(JSC::MacroAssemblerARMv7::move):
* Source/JavaScriptCore/b3/B3LowerToAir32_64.cpp:
* Source/JavaScriptCore/b3/air/AirOpcode.opcodes:
* Source/JavaScriptCore/b3/air/opcode_generator.rb:
</pre>

2024-06-05 21:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/656585d5bbd9743b26782db9a57c12c7424b0a7c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29545

2024-06-05 21:07 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/a7357cff95e9b333d1bc0bf9590a3cfa3a31a966)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/54389 "Passed style check") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/33795 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/6949 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/57668 "Hash a7357cff for PR 29545 does not build (failure)") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/59/builds/5120 "Built successfully") 
| | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/41328 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/5068 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/57668 "Hash a7357cff for PR 29545 does not build (failure)") | [✅ 🧪 wincairo-tests](https://ews-build.webkit.org/#/builders/60/builds/3433 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/56482 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/41328 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/6949 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/57668 "Hash a7357cff for PR 29545 does not build (failure)") | 
| | [❌ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/41328 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/6949 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/3263 "Hash a7357cff for PR 29545 does not build (failure)") | 
| [❌ 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/47750 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/41328 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/6949 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/59259 "Hash a7357cff for PR 29545 does not build (failure)") | 
| [❌ 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/53896 "Hash a7357cff for PR 29545 does not build (failure)") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-17-Build-EWS "Waiting in queue, processing has not started yet") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/61/builds/5068 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/59259 "Hash a7357cff for PR 29545 does not build (failure)") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [❌ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/6949 "Hash a7357cff for PR 29545 does not build (failure)") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/59259 "Hash a7357cff for PR 29545 does not build (failure)") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-10-Build-EWS "Waiting in queue, processing has not started yet") | | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/66195 "Built successfully") | 
| | [❌ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/30557 "Hash a7357cff for PR 29545 does not build (failure)") | | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/12612 "Passed tests") | </details>

2024-06-06 00:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/656585d5bbd9743b26782db9a57c12c7424b0a7c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/29545

2024-06-06 00:54 UTC, Constellation requested changes
I don't think this is right. What we should do is lowering to several Air instruction so that Air can just work without knowing 64bit concept.

2024-06-06 03:02 UTC, Constellation commented
For example, see V8's handling of 64bit values. They have a path lowering it to 32bit handling at the high level phase (e.g. B3). That's the right thing and integrating TmpPair into Air is not the correct direction.

2024-06-06 05:17 UTC, Constellation commented
The only place it needs to see TmpPair is patchpoint because of the leak of info from B3 to Air (not great though). Any other places in Air, TmpPair is not OK.

2024-06-06 08:27 UTC, aoikonomopoulos commented
@Constellation Thanks for taking a look, this is valuable feedback.

Can you briefly explain what the downside of using TmpPairs at the Air level is?

To give some background, I have a complete 32-bit OMG implementation that doesn't use TmpPairs at all, instead lowering to 32-bits everywhere. As you might expect, that significantly complicates the generic code paths for patchpoints, since it breaks the 1-1 correspondence between B3 and Air arguments. It also needs extra care in calling convention code to differentiate between Int64/Double (the `usedWidth` is not enough).

As you say, TmpPair makes everything having to do with Patchpoints more straightforward. I can see how what you suggest (only use TmpPairs for Patchpoints) would work.

The thing is, having `TmpPair` forms would considerably reduce the diff between `B3LowerToAir.cpp` and `B3LowerToAir32_64.cpp`, which would make maintenance much easier going forward. AFAIU we'd still need all the `USE(JSVALUE32_64)` guarded code at program points that branch on `Air::Arg::Kind` in any case, so would be great to understand what it is we'd be losing by allowing `TmpPair` in Air forms.

2024-06-06 18:27 UTC, Constellation commented
> @Constellation Thanks for taking a look, this is valuable feedback.
> 
> Can you briefly explain what the downside of using TmpPairs at the Air level is?
> 
> To give some background, I have a complete 32-bit OMG implementation that doesn't use TmpPairs at all, instead lowering to 32-bits everywhere. As you might expect, that significantly complicates the generic code paths for patchpoints, since it breaks the 1-1 correspondence between B3 and Air arguments. It also needs extra care in calling convention code to differentiate between Int64/Double (the `usedWidth` is not enough).
> 
> As you say, TmpPair makes everything having to do with Patchpoints more straightforward. I can see how what you suggest (only use TmpPairs for Patchpoints) would work.
> 
> The thing is, having `TmpPair` forms would considerably reduce the diff between `B3LowerToAir.cpp` and `B3LowerToAir32_64.cpp`, which would make maintenance much easier going forward. AFAIU we'd still need all the `USE(JSVALUE32_64)` guarded code at program points that branch on `Air::Arg::Kind` in any case, so would be great to understand what it is we'd be losing by allowing `TmpPair` in Air forms.

Air should be aligned to the actual machine code, and int64_t etc. is the high level concept in B3 etc. should represent. Representing it in Air is wrong approach.

2024-06-06 18:29 UTC, Constellation commented
> The thing is, having TmpPair forms would considerably reduce the diff between B3LowerToAir.cpp and B3LowerToAir32_64.cpp

No. 64Bit side does not need TmpPair at all. Integrating it is making 64bit much worse.

2024-06-06 18:31 UTC, Constellation commented
> As you say, TmpPair makes everything having to do with Patchpoints more straightforward. I can see how what you suggest (only use TmpPairs for Patchpoints) would work.

What it should be is reducing patchpoint. TmpPair is not the right thing, and we should minimize the exposure of that.

2024-06-06 18:37 UTC, Constellation commented
I think we should completely remove TmpPair. That's not the right abstraction.

2024-06-06 18:41 UTC, aoikonomopoulos commented
> > The thing is, having TmpPair forms would considerably reduce the diff between B3LowerToAir.cpp and B3LowerToAir32_64.cpp
> 
> No. 64Bit side does not need TmpPair at all. Integrating it is making 64bit much worse.

Just to avoid any misunderstanding `TmpPair` is not even defined on 64-bits. The diff between B3LowerToAir.cpp and B3LowerToAir32_64.cpp would be reduced because the handling of 64-bit values would be uniform between the two files, not because 64-bit would have anything to do with TmpPair.

2024-06-06 19:07 UTC, kmiller68 commented
Yeah, I think I agree with Yusuke. I think the right approach to this is:
    1) Move as many existing watchpoints that are trivial to B3/Air opcodes.
    2) Have a 32-bit only B3 phase that removes all 64-bit GP values/opcodes and replaces them with the 32-bit compatible version.
    2) Depending on the number of remaining patchpoints either split them into 32-bit/64-bit versions or just using the existing ValueReps for pairs of registers.

2024-06-06 19:40 UTC, aoikonomopoulos commented
Thanks for the feedback here and on slack @Constellation and @kmiller68, this was very helpful! Closing this PR.

2024-06-06 19:40 UTC, closed without merging