[Win] Do not downscale drawingArea size by deviceScaleFactor on resize
WebKit/WebKit pull request #30142
Opened 2024-06-25 09:42 UTC by obyknovenius

#### 3837f81b2dc5c69b65ebade6890808e8ea2557b8
<pre>
[Win] Do not downscale drawingArea size by deviceScaleFactor on resize
<a href="https://bugs.webkit.org/show_bug.cgi?id=275845">https://bugs.webkit.org/show_bug.cgi?id=275845</a>

Reviewed by NOBODY (OOPS!).

The `WM_SIZE` message in the Windows API provides the new width and
height of the client area in logical pixels, not physical pixels.

This means that the size values provided by `WM_SIZE` are already
adjusted for the device scale factor on high-DPI screens.

* Source/WebKit/UIProcess/win/WebView.cpp:
(WebKit::WebView::onSizeEvent):
</pre>

2024-06-25 09:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3837f81b2dc5c69b65ebade6890808e8ea2557b8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30142

2024-06-25 20:41 UTC, fujii requested changes
This is a wrong fix.
https://bugs.webkit.org/show_bug.cgi?id=275845#c2 is my suggestion.

2024-07-08 07:33 UTC, mariospr commented
Looks like the fix for https://bugs.webkit.org/show_bug.cgi?id=275845#c2 has landed already (see https://github.com/WebKit/WebKit/pull/30288), maybe this PR can be closed now?

2024-07-08 07:52 UTC, fujii commented
Yup.

2024-07-08 07:52 UTC, closed without merging