[WPE] WPE Platform: add wpe_input_method_context_filter_key_event
WebKit/WebKit pull request #30182
Opened 2024-06-26 08:25 UTC by zhani

https://bugs.webkit.org/show_bug.cgi?id=275893

Reviewed by NOBODY (OOPS!).

Add missing wpe_input_method_context_filter_key_event to WPEPlatform

* Source/WebKit/UIProcess/API/glib/InputMethodFilter.h: (WebKit::InputMethodFilter::setUseWPEPlatformEvents):
* Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in:
* Source/WebKit/UIProcess/API/wpe/InputMethodFilterWPE.cpp: (WebKit::InputMethodFilter::platformEventKeyIsKeyPress const):
* Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp: (WKWPE::m_backend):
* Source/WebKit/UIProcess/API/wpe/WebKitInputMethodContextImplWPE.cpp: (webkitInputMethodContextImplWPEFilterKeyEvent):
(webkit_input_method_context_impl_wpe_class_init):
* Source/WebKit/UIProcess/API/wpe/WebKitInputMethodContextWPE.cpp: (webkit_input_method_context_filter_key_event):
* Source/WebKit/WPEPlatform/wpe/WPEInputMethodContext.cpp: (wpe_input_method_context_filter_key_event):
* Source/WebKit/WPEPlatform/wpe/WPEInputMethodContext.h:
* Tools/TestWebKitAPI/Tests/WebKitGLib/TestInputMethodContext.cpp: (webkitInputMethodContextMockFilterKeyEvent):

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2024-06-26 08:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3531916b5e9be68093b6775cd68abf1e907b05a8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30182

2024-06-26 11:01 UTC, carlosgcampos requested changes

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/InputMethodFilter.h
> +#if PLATFORM(WPE) && ENABLE(WPE_PLATFORM)
```suggestion
#if ENABLE(WPE_PLATFORM)
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in
> +                                     void                            *key_event);
```suggestion
                                     gpointer                         key_event);
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in
> +                                                void                            *key_event);
```suggestion
                                                gpointer                         key_event);
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/InputMethodFilterWPE.cpp
> +        return wpe_event_get_event_type(wpe_platform_event) == WPE_EVENT_KEYBOARD_KEY_DOWN;
```suggestion
        return wpe_event_get_event_type(WPE_EVENT(event)) == WPE_EVENT_KEYBOARD_KEY_DOWN;
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp
>                  webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), false));
```suggestion
                if (!filterResult.handled)
                    webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), false));
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp
>                  webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), webView.m_keyAutoRepeatHandler.keyPress(wpe_event_keyboard_get_keycode(event))));
```suggestion
                if (!filterResult.handled)
                    webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), webView.m_keyAutoRepeatHandler.keyPress(wpe_event_keyboard_get_keycode(event))));
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp
>                  webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), webView.m_keyAutoRepeatHandler.keyPress(wpe_event_keyboard_get_keycode(event))));
You have to pass `filterResult.keyText` instead of `String()`

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitInputMethodContextImplWPE.cpp
> +    return wpe_input_method_context_filter_key_event(priv->context.get(), wpeEvent);
```suggestion
    return wpe_input_method_context_filter_key_event(priv->context.get(), WPE_EVENT(keyEvent));
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/WPEPlatform/wpe/WPEInputMethodContext.cpp
> + *
```suggestion
```

2024-06-26 11:01 UTC, carlosgcampos commented on Source/WebKit/WPEPlatform/wpe/WPEInputMethodContext.cpp
> +    return false;
```suggestion
    return FALSE;
```

2024-06-26 16:18 UTC, zhani commented on Source/WebKit/UIProcess/API/glib/InputMethodFilter.h
> +#if PLATFORM(WPE) && ENABLE(WPE_PLATFORM)
Fixed

2024-06-28 06:56 UTC, zhani commented on Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in
> +                                     void                            *key_event);
Fixed

2024-06-28 06:57 UTC, zhani commented on Source/WebKit/UIProcess/API/glib/WebKitInputMethodContext.h.in
> +                                                void                            *key_event);
Fixed

2024-06-28 06:57 UTC, zhani commented on Source/WebKit/UIProcess/API/wpe/InputMethodFilterWPE.cpp
> +        return wpe_event_get_event_type(wpe_platform_event) == WPE_EVENT_KEYBOARD_KEY_DOWN;
WPEvent is not gobject but boxed type

2024-06-28 06:57 UTC, zhani commented on Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp
>                  webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), false));
Fixed

2024-06-28 06:57 UTC, zhani commented on Source/WebKit/UIProcess/API/wpe/WPEWebView.cpp
>                  webView.page().handleKeyboardEvent(WebKit::NativeWebKeyboardEvent(event, String(), webView.m_keyAutoRepeatHandler.keyPress(wpe_event_keyboard_get_keycode(event))));
Fixed

2024-06-28 06:57 UTC, zhani commented on Source/WebKit/UIProcess/API/wpe/WebKitInputMethodContextImplWPE.cpp
> +    return wpe_input_method_context_filter_key_event(priv->context.get(), wpeEvent);
WPEvent is not gobject but boxed type

2024-06-28 06:58 UTC, zhani commented on Source/WebKit/WPEPlatform/wpe/WPEInputMethodContext.cpp
> +    return false;
Fixed

2024-06-28 07:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b31aba3fe66b80060c2343839bfb2593c56271d8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30182

2024-06-28 08:57 UTC, carlosgcampos approved these changes

2024-06-28 08:57 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/InputMethodFilterWPE.cpp
> +        return wpe_event_get_event_type(wpe_platform_event) == WPE_EVENT_KEYBOARD_KEY_DOWN;
Right, sorry I forgot it

2024-06-28 08:59 UTC, webkit-commit-queue commented
Committed 280448@main (f3070e7128ad): <https://commits.webkit.org/280448@main>

Reviewed commits have been landed. Closing PR #30182 and removing active labels.

2024-06-28 08:59 UTC, merged