Enable text-underline-position: left | right in preview
WebKit/WebKit pull request #30218
Opened 2024-06-27 01:01 UTC by fantasai

#### 4b5afc187317ad735204cabb07b0d5d9b3bfe35c
<pre>
Enable text-underline-position: left | right in preview
<a href="https://bugs.webkit.org/show_bug.cgi?id=245559">https://bugs.webkit.org/show_bug.cgi?id=245559</a>
<a href="https://rdar.apple.com/130621143">rdar://130621143</a>
Reviewed by NOBODY (OOPS!).

Switch CSSTextUnderlinePositionLeftRightEnabled from unstable to preview

* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
</pre>

2024-06-27 01:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4b5afc187317ad735204cabb07b0d5d9b3bfe35c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30218

2024-06-27 01:33 UTC, nt1m approved these changes

2024-06-27 15:39 UTC, stwrt requested changes
Need to update failing WPT test expectations.

2024-06-27 16:17 UTC, nt1m commented
> Need to update failing WPT test expectations.

We should unskip the newly passing rendering tests too

2024-07-23 05:50 UTC, nt1m commented
I think I'll do more work and enable everywhere (not just STP) once I think it's ready

2024-07-23 05:50 UTC, closed without merging