Add reference to Element in `resolveAnchorValue()` for safety
WebKit/WebKit pull request #30404
Opened 2024-07-02 20:30 UTC by RWDavid

#### d22275f364c4a29be5b074cd9a5826c91d3fb864
<pre>
Add reference to Element in `resolveAnchorValue()` for safety
<a href="https://bugs.webkit.org/show_bug.cgi?id=276142">https://bugs.webkit.org/show_bug.cgi?id=276142</a>
<a href="https://rdar.apple.com/130992562">rdar://130992562</a>

Add a Ref to a `const Element&amp;` object that invokes a nontrivial method.

* Source/WebCore/style/AnchorPositionEvaluator.cpp:
(WebCore::Style::AnchorPositionEvaluator::resolveAnchorValue):
</pre>

2024-07-02 20:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d22275f364c4a29be5b074cd9a5826c91d3fb864. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30404

2024-07-02 20:35 UTC, rreno approved these changes

2024-07-02 20:40 UTC, nt1m requested changes
We don't usually use protectors, the element should be protected at the call site level.

2024-07-02 20:42 UTC, nt1m commented
This should turn into a `Ref`: https://searchfox.org/wubkat/rev/8104e1d037fe1ef5d6824f8d893b5df6c2691452/Source/WebCore/style/StyleBuilderConverter.h#269

2024-07-02 20:47 UTC, rreno commented
We should also probably use `protectedDocument` and `checkedStyleScope` since we're holding a reference to a member variable on a heap allocated object in the scope of this function.

2024-07-02 21:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a870ed4b181624918eaff30e52b2f75861ec037. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30404

2024-07-02 21:18 UTC, nt1m approved these changes

2024-07-02 21:18 UTC, nt1m commented on Source/WebCore/style/StyleBuilderConverter.h
> +        RefPtr<const Element> anchorPositionedElement = builderState.element();
```suggestion
        RefPtr anchorPositionedElement = builderState.element();
```

2024-07-02 21:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d38d1f225ca7feca4f6dac435fb2bb560cc1c539. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30404

2024-07-03 00:24 UTC, webkit-commit-queue commented
No reviewer information in commit message, blocking PR #30404

2024-07-03 00:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f3d747398da9590e84f5a0ef4df8f1bf418c865b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30404

2024-07-03 03:12 UTC, webkit-commit-queue commented
Committed 280610@main (2ce73fd81990): <https://commits.webkit.org/280610@main>

Reviewed commits have been landed. Closing PR #30404 and removing active labels.

2024-07-03 03:12 UTC, merged