ref.null accepts invalid type indices
WebKit/WebKit pull request #30529
Opened 2024-07-05 20:54 UTC by danlliu

#### 1401a4266064e0fef09a001564160b950548cf28
<pre>
ref.null accepts invalid type indices
Need the bug URL (OOPS!).
<a href="https://rdar.apple.com/130746860">rdar://130746860</a>

Reviewed by NOBODY (OOPS!).

ref.null only checks the low byte due to casting, meaning that invalid indices could be incorrectly treated as valid reference types.

* Source/JavaScriptCore/wasm/WasmParser.h:
(JSC::Wasm::ParserBase::parseHeapType):
</pre>

2024-07-05 20:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1401a4266064e0fef09a001564160b950548cf28. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30529

2024-07-05 21:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/518a84653e38bfcc043a41e0a6d888ea29307ba2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30529

2024-07-05 21:27 UTC, MenloDorian requested changes

2024-07-05 21:27 UTC, MenloDorian commented on Source/JavaScriptCore/wasm/WasmParser.h
> +            return false;
This solution is fragile.  Let's just make `isValidHeapTypeKind` take an `intptr_t` instead.  It's also weird for `isValidHeapTypeKind` to only take a `TypeKind`, which suggests it's always taking a valid value.  I wonder if there are undefined behavior fallout there.

2024-07-05 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20dd5e17cd3d7617439fefd9eb72b405ef44350d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30529

2024-07-05 21:46 UTC, MenloDorian approved these changes
r=me if EWS bots are happy.

2024-07-08 15:53 UTC, justinmichaud commented
I agree that we shouldn't take a TypeKind, it invites the compiler to assume it takes a valid value. That being said, we should never be passing something larger than a byte into this function, right? If we are, we should check at that point, not inside isValidTypeKind IMO

2024-07-08 17:19 UTC, danlliu commented
One of the main reasons we're passing in a full `intrptr_t` is because future specs may utilize a larger range of values than the current 1-byte values we handle; `isValidTypeKind` should be able to handle any type kind that is parsed from the bytecode, regardless of if it's a byte or larger.

2024-07-08 17:25 UTC, webkit-commit-queue commented
Committed 280743@main (f6a59631fa7d): <https://commits.webkit.org/280743@main>

Reviewed commits have been landed. Closing PR #30529 and removing active labels.

2024-07-08 17:25 UTC, merged