Merge WinPort class into WinCairoPort class
WebKit/WebKit pull request #30588
Opened 2024-07-09 01:21 UTC by fujii

#### 10c81ff9ca5bd3cebfc193a16f05f189a6082ea0
<pre>
Merge WinPort class into WinCairoPort class
<a href="https://bugs.webkit.org/show_bug.cgi?id=271244">https://bugs.webkit.org/show_bug.cgi?id=271244</a>

Reviewed by NOBODY (OOPS!).

Apple Windows port has gone. WinPort class was no longer directly
instantiated. WinCairoPort was the only subclass of it.

* Tools/Scripts/webkitpy/common/system/crashlogs_unittest.py:
* Tools/Scripts/webkitpy/port/win.py:
</pre>

2024-07-09 01:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/10c81ff9ca5bd3cebfc193a16f05f189a6082ea0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30588

2024-07-09 17:15 UTC, donny-dont requested changes
Isn't the end goal to be the `WinPort` in all the tooling?

If there's stuff referencing `WinCairoPort` can't we just do a type alias in Python?

```
WinCairoPort = WinPort
```

2024-07-09 18:06 UTC, gsnedders commented
> Isn't the end goal to be the `WinPort` in all the tooling?

We mostly refer to the port as "WinCairo", don't we? I'd expect us to use that name in the code, too.

2024-07-09 18:48 UTC, donny-dont commented
> > Isn't the end goal to be the `WinPort` in all the tooling?
> 
> We mostly refer to the port as "WinCairo", don't we? I'd expect us to use that name in the code, too.

There's no more AppleWin port and we'd like to move to Skia for rendering so having WinCairo in the code isn't ideal.

2024-07-09 20:19 UTC, fujii commented
I agree Don's opinion that WinCairoPort should be renamed to WinPort. But, the migration steps aren't so simple.
1. Make all scripts accept `--platform=win` as an alias of `--platform=wincairo`
2. Migrate EWS and post-commit buildbot to use `--platform=win`
3. Then, we can remove `--platform=wincairo`
I'd like to land this patch as is as the first step.

2024-07-09 20:50 UTC, donny-dont commented on Tools/Scripts/webkitpy/port/win.py
> +    port_name = "wincairo"
Can't you just make this `class WinPort` and keep your change to the `port_name`?

Again if there are references to `WinCairoPort` can't you do an alias?

2024-07-09 21:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7c34d5297ed7ac430ed651ba4aefd9d2817f5f4d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30588

2024-07-10 20:01 UTC, donny-dont approved these changes

2024-07-10 20:04 UTC, webkit-commit-queue commented
Committed 280831@main (099cdafc1313): <https://commits.webkit.org/280831@main>

Reviewed commits have been landed. Closing PR #30588 and removing active labels.

2024-07-10 20:04 UTC, merged