Dispatch GlobalObjectAvailable to subframes when adding user scripts in top frame only
WebKit/WebKit pull request #3059
Opened 2022-08-05 20:56 UTC by laphets

#### 2be05d926decccc3b99daeead516cd55fb1642b0
<pre>
Dispatch GlobalObjectAvailable to subframes when adding user scripts in top frame only
<a href="https://bugs.webkit.org/show_bug.cgi?id=243606">https://bugs.webkit.org/show_bug.cgi?id=243606</a>
&lt;rdar://73500002&gt;

Currently, when adding content script to top frame only, dispatchGlobalObjectAvailable won&apos;t be
called for its subframes. If user later calls runJavaScriptInFrameInScriptWorld directly in the
subframe using the same world as the content script added to top frame, dispatchGlobalObjectAvailable
won&apos;t be called for the subframe either. As a result, objects that is registered in
dispatchGlobalObjectAvailable callback won&apos;t be available for JavaScript that is executed by
runJavaScriptInFrameInScriptWorld in subframe.
The patch fixes this by explicitly dispatching GlobalObjectAvailable to all the subframes inside
addUserScriptInternal.

Reviewed by NOBODY (OOPS!).

* Source/WebKit/WebProcess/UserContent/WebUserContentController.cpp:
(WebKit::WebUserContentController::addUserScriptInternal):
When user script only injects to top frame, traverse all the subframes under mainframe,
call dispatchGlobalObjectAvailable on each of the subframe using the given world.
</pre>

2022-08-05 21:20 UTC, cdumez commented
@achristensen07 did something similar and may be a good reviewer for this:
```
Call globalObjectIsAvailableForFrame before evaluating JavaScript in newly created worlds
https://bugs.webkit.org/show_bug.cgi?id=208615
<rdar://problem/59406743>
```

2022-08-05 21:39 UTC, xeenon approved these changes
Looks fine to me. Would like the other reviewers to take a look still.

2022-08-05 21:40 UTC, cdumez commented on Source/WebKit/WebProcess/UserContent/WebUserContentController.cpp
> +                for (auto* frame = &mainFrame; frame; frame = frame->tree().traverseNext(&mainFrame)) {
the `&mainFrame` parameter to `traverseNext()` is not needed since you are traversing the whole frame tree.

2022-08-05 21:41 UTC, eepskamp commented
Is it possible to add a test for this change?

2022-08-05 22:29 UTC, laphets commented
> Is it possible to add a test for this change?

@cdumez Do you have any suggestion where is the best place for the test to go.

2022-08-05 23:31 UTC, cdumez commented
> > Is it possible to add a test for this change?
> 
> @cdumez Do you have any suggestion where is the best place for the test to go.

Probably UserContentController.mm would be a good spot as it looks like you are going to test addUserScript on a UserContentController.

2022-08-10 02:34 UTC, cdumez approved these changes
LGTM with change.

2022-08-10 02:34 UTC, cdumez commented on Source/WebKit/WebProcess/UserContent/WebUserContentController.cpp
> +                for (auto* frame = &mainFrame; frame; frame = frame->tree().traverseNext()) {
It is a bit inefficient to check every frame to see if it's the main frame (when we know only the first one is). Would be more efficient to write like so:
```
mainFrame.injectUserScriptImmediately(world.coreWorld(), userScript);
for (auto* frame = mainFrame.tree().traverseNext(); frame; frame = frame->tree().traverseNext())
    frame->loader().client().dispatchGlobalObjectAvailable(world.coreWorld());
```

2022-08-10 17:10 UTC, achristensen07 commented
I don't think this is correct.  GlobalObjectAvailable should be called when the global object is available.  Would it work to instead add this call in WebUserContentController::addContentWorlds?

2022-08-10 17:19 UTC, geoffreygaren commented
I agree with Alex. This doesn't look like the right fix to me. 

addUserScripts() is called by the WebPage constructor. This raises three concerns:
(1) I'm surprised that _any_ subframes exist at that time.
(2) More subframes can be added later by HTML parsing or webpage JavaScript
(3) Subframes can navigate later

I believe this test case only passes because it deliberately calls _addUserScriptImmediately after the navigation is complete. I believe that a test that tested using only public API, or that tested calling _addUserScriptImmediately some time before page load time time, would show all three bugs.

2022-08-10 17:47 UTC, achristensen07 commented
We may also need to call GlobalObjectAvailable for each world when creating a global object for a frame

2022-08-10 17:48 UTC, achristensen07 requested changes

2022-08-10 17:48 UTC, achristensen07 commented on Source/WebKit/WebProcess/UserContent/WebUserContentController.cpp
> +                    frame->loader().client().dispatchGlobalObjectAvailable(world.coreWorld());
Yeah, this isn't the right place for this.

2022-08-10 17:52 UTC, laphets commented
> I agree with Alex. This doesn't look like the right fix to me.
> 
> addUserScripts() is called by the WebPage constructor. This raises three concerns: (1) I'm surprised that _any_ subframes exist at that time. (2) More subframes can be added later by HTML parsing or webpage JavaScript (3) Subframes can navigate later
> 
> I believe this test case only passes because it deliberately calls _addUserScriptImmediately after the navigation is complete. I believe that a test that tested using only public API, or that tested calling _addUserScriptImmediately some time before page load time time, would show all three bugs.

If subframes are added or navigate later, `dispatchGlobalObjectAvailable` will still be called in `FrameLoader::receivedFirstData`?

2022-08-10 23:05 UTC, achristensen07 approved these changes

2022-08-10 23:15 UTC, geoffreygaren commented
> I think what this patch aims to solve is when a user script is added after navigation completes.

Got it. Makes sense. Can you update the commit message to reflect that goal?

2022-08-11 16:53 UTC, merged

2022-08-11 16:53 UTC, webkit-commit-queue commented
Committed 253337@main (4b458ff27f44): <https://commits.webkit.org/253337@main>

Reviewed commits have been landed. Closing PR #3059 and removing active labels.