Web Inspector: Console: add internal properties for registrations of a `FinalizationRegistry`
WebKit/WebKit pull request #30909
Opened 2024-07-17 17:02 UTC by dcrousso

#### 99fb284efa7a96792dd3218b723d99705b21407f
<pre>
Web Inspector: Console: add internal properties for registrations of a `FinalizationRegistry`
<a href="https://bugs.webkit.org/show_bug.cgi?id=276719">https://bugs.webkit.org/show_bug.cgi?id=276719</a>

Reviewed by NOBODY (OOPS!).

Add special handling for `FinalizationRegistry` to make it easier for developers to understand its state (e.g. what is still alive vs what is dead but not yet notified vs etc.).

* Source/JavaScriptCore/inspector/JSInjectedScriptHost.cpp:
(Inspector::JSInjectedScriptHost::getInternalProperties):
Add internal properties for
- `cleanupCallback` to help the developer know what the `FinalizationRegistry` is for if the grab it via some general means (e.g. `queryInstances`).
- `live` is the list of objects that have not been GCd, each showing the `target`, `heldValue`, and (if provided) `unregisterToken`.
- `dead` is the list of metadata for objects that have been GCd (but not yet notified), each showing the `heldValue` and (if provided) `unregisterToken`.

* Source/JavaScriptCore/runtime/JSFinalizationRegistry.h:
* Source/JavaScriptCore/runtime/JSFinalizationRegistry.cpp:
(JSC::JSFinalizationRegistry::forEachLive const): Added.
(JSC::JSFinalizationRegistry::forEachDead const): Added.
Expose ways for callers to get the above data.

* LayoutTests/inspector/model/remote-object/resources/remote-object-utilities.js:
* LayoutTests/inspector/model/remote-object/finalizationregistry.html: Added.
* LayoutTests/inspector/model/remote-object/finalizationregistry-expected.txt: Added.
</pre>

2024-07-18 02:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bc962bc2833d9ef093b24f84281da24cd446c8db. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30909

2024-07-31 17:11 UTC, Constellation requested changes

2024-07-31 17:11 UTC, Constellation commented on Source/JavaScriptCore/inspector/JSInjectedScriptHost.cpp
> +        Locker locker { finalizationRegistry->cellLock() };
You cannot hold a lock while doing JS operations like putDirect etc. it can cause deadlock.

2024-07-31 17:29 UTC, kmiller68 commented on Source/JavaScriptCore/runtime/JSFinalizationRegistry.h
> +    void forEachLive(const Locker<JSCellLock>&, const Function<void(JSCell* target, JSValue heldValue, JSCell* unregisterToken)>&) const;
This could be a ScopedLambda or just lambda instead of a Function.

2024-08-01 02:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2ee336fb0b18cd58d89827c54c8578be24d57c9a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30909

2024-08-07 20:38 UTC, Constellation approved these changes
r=me with comments.

2024-08-07 20:38 UTC, Constellation commented on Source/JavaScriptCore/inspector/JSInjectedScriptHost.cpp
> +            liveArray->putDirectIndex(globalObject, liveIndex++, registrationObject);
This can throw an error, so error check is necessary.

2024-08-07 20:38 UTC, Constellation commented on Source/JavaScriptCore/inspector/JSInjectedScriptHost.cpp
> +            deadArray->putDirectIndex(globalObject, deadIndex++, registrationObject);
Ditto.

2024-08-08 15:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a2c664f65aff8be64cd565e0a4b378445a2eb0d9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/30909

2024-08-08 18:11 UTC, webkit-commit-queue commented
Committed 282000@main (626aa2207e3e): <https://commits.webkit.org/282000@main>

Reviewed commits have been landed. Closing PR #30909 and removing active labels.

2024-08-08 18:11 UTC, merged