Rename WKSafeBrowsingWarning to WKWarningView
WebKit/WebKit pull request #31558
Opened 2024-07-31 20:17 UTC by sysrqb

#### 0e09f8c749d6470981db5f6a0c10afc00f7ca49d
<pre>
Rename WKSafeBrowsingWarning to WKWarningView
<a href="https://bugs.webkit.org/show_bug.cgi?id=277442">https://bugs.webkit.org/show_bug.cgi?id=277442</a>
<a href="https://rdar.apple.com/132924925">rdar://132924925</a>

Reviewed by NOBODY (OOPS!).

Rename WKSafeBrowsingWarning, and associated state, to a more generic name.
This will be useful in future changes.

No other behavioral changes.

* Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm:
(-[WKWebView _showWarningView:completionHandler:]):
(-[WKWebView _showSafeBrowsingWarning:completionHandler:]):
(-[WKWebView _clearWarningView]):
(-[WKWebView _clearSafeBrowsingWarning]):
(-[WKWebView _clearWarningViewIfForMainFrameNavigation]):
(-[WKWebView _clearSafeBrowsingWarningIfForMainFrameNavigation]):
(-[WKWebView _safeBrowsingWarning]):
(-[WKWebView _showWarningViewWithTitle:warning:details:completionHandler:]):
(-[WKWebView _showSafeBrowsingWarningWithTitle:warning:details:completionHandler:]):
(-[WKWebView _showWarningViewWithURL:title:warning:details:completionHandler:]):
(-[WKWebView _showSafeBrowsingWarningWithURL:title:warning:details:completionHandler:]):
(-[WKWebView _showWarningViewWithURL:title:warning:detailsWithLinks:completionHandler:]):
(-[WKWebView _showSafeBrowsingWarningWithURL:title:warning:detailsWithLinks:completionHandler:]):
* Source/WebKit/UIProcess/API/Cocoa/WKWebViewInternal.h:
* Source/WebKit/UIProcess/API/ios/WKWebViewIOS.mm:
(-[WKWebView layoutSubviews]):
(-[WKWebView _computedObscuredInsetForWarningView]):
(-[WKWebView safeAreaInsetsDidChange]):
(-[WKWebView _setObscuredInsets:]):
(-[WKWebView _computedObscuredInsetForSafeBrowsingWarning]): Deleted.
(-[WKWebView _safeBrowsingWarning]): Deleted.
* Source/WebKit/UIProcess/API/mac/WKWebViewMac.mm:
* Source/WebKit/UIProcess/Cocoa/WKWarningView.h: Renamed from Source/WebKit/UIProcess/Cocoa/WKSafeBrowsingWarning.h.
* Source/WebKit/UIProcess/Cocoa/WKWarningView.mm: Renamed from Source/WebKit/UIProcess/Cocoa/WKSafeBrowsingWarning.mm.
(fontOfSize):
(colorForItem):
(-[WKSafeBrowsingExclamationPoint drawRect:]):
(-[WKSafeBrowsingExclamationPoint viewDidChangeEffectiveAppearance]):
(-[WKSafeBrowsingExclamationPoint intrinsicContentSize]):
(makeButton):
(buttonSize):
(makeLabel):
(-[WKWarningViewBox setWarningViewBackgroundColor:]):
(-[WKWarningViewBox updateLayer]):
(-[WKWarningView initWithFrame:safeBrowsingWarning:completionHandler:]):
(-[WKWarningView addContent]):
(-[WKWarningView showDetailsClicked]):
(-[WKWarningView updateContentSize]):
(-[WKWarningView layoutText]):
(-[WKWarningView textView:clickedOnLink:atIndex:]):
(-[WKWarningView layout]):
(-[WKWarningView layoutSubviews]):
(-[WKWarningView textView:shouldInteractWithURL:inRange:interaction:]):
(-[WKWarningView didMoveToWindow]):
(-[WKWarningView dealloc]):
(-[WKWarningView goBackClicked]):
(-[WKWarningView clickedOnLink:]):
(-[WKWarningView forMainFrameNavigation]):
(-[WKWarningViewTextView initWithAttributedString:forWarning:]):
(-[WKWarningViewTextView intrinsicContentSize]):
(-[WKWarningViewTextView clipsToBounds]):
* Source/WebKit/UIProcess/mac/WebViewImpl.h:
* Source/WebKit/UIProcess/mac/WebViewImpl.mm:
(WebKit::WebViewImpl::showWarningView):
(WebKit::WebViewImpl::clearWarningView):
(WebKit::WebViewImpl::clearWarningViewIfForMainFrameNavigation):
(WebKit::WebViewImpl::setFrameSize):
(WebKit::WebViewImpl::accessibilityAttributeValue):
(WebKit::WebViewImpl::nativeMouseEventHandlerInternal):
(WebKit::WebViewImpl::showSafeBrowsingWarning): Deleted.
(WebKit::WebViewImpl::clearSafeBrowsingWarning): Deleted.
(WebKit::WebViewImpl::clearSafeBrowsingWarningIfForMainFrameNavigation): Deleted.
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
</pre>

2024-07-31 20:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0e09f8c749d6470981db5f6a0c10afc00f7ca49d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/31558

2024-07-31 21:21 UTC, achristensen07 requested changes

2024-07-31 21:21 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/Cocoa/WKWebViewInternal.h
> +- (UIView *)_safeBrowsingWarning;
This is suspicious.  Shouldn't we have an NSView property on macOS?

2024-07-31 21:21 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/Cocoa/WKWebViewInternal.h
> +@class WKWarningView;
Could we name this _WKWarningView because it's not intended to be used by third parties?

2024-07-31 21:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/97416b4c313bf703c238cb169f6e887c87d82584. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/31558

2024-07-31 21:27 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/18b005b2730c3405ebe1c90363e8372ad9a81dbd)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/60625 "1 style error") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-17-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/13201 "Build is in progress. Recent messages:OS: Ventura (13.6.7), Xcode: 14.3; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/47660 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-Sonoma-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 wincairo-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/62658 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/47660 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/13201 "Build is in progress. Recent messages:OS: Ventura (13.6.7), Xcode: 14.3; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/47660 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/13201 "Build is in progress. Recent messages:OS: Ventura (13.6.7), Xcode: 14.3; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/47660 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/13201 "Build is in progress. Recent messages:OS: Ventura (13.6.7), Xcode: 14.3; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-1-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Sonoma-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/13201 "Build is in progress. Recent messages:OS: Ventura (13.6.7), Xcode: 14.3; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-17-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-10-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-10-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2024-07-31 21:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c932804009a85f7d3cbe4bf451a0de2bb517280b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/31558

2024-07-31 23:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/618070e1907e2f17e6088c02f999a65727c1daf4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/31558

2024-07-31 23:06 UTC, sysrqb commented on Source/WebKit/UIProcess/Cocoa/_WKWarningView.mm
> +
Style checker wasn't happy with this pre-existing whitespace. Same with the other similar changes.

2024-08-01 15:20 UTC, achristensen07 approved these changes

2024-08-01 16:49 UTC, webkit-commit-queue commented
Committed 281715@main (fc46bbbaea29): <https://commits.webkit.org/281715@main>

Reviewed commits have been landed. Closing PR #31558 and removing active labels.

2024-08-01 16:49 UTC, merged