Remove Cookie Store API Extended Attributes
WebKit/WebKit pull request #32273
Opened 2024-08-15 23:53 UTC by RupinMittal

#### b91024fa2afcbfcae300ef998764cab7e0edb220
<pre>
Remove Cookie Store API Extended Attributes
<a href="https://bugs.webkit.org/show_bug.cgi?id=278198">https://bugs.webkit.org/show_bug.cgi?id=278198</a>
<a href="https://rdar.apple.com/133994044">rdar://133994044</a>

Reviewed by NOBODY (OOPS!).

The document.cookie API exposes only the `name` and `value`
attributes of the cookie. Our position is that we want to do
the same for the new Cookie Store API. Since we do not want
to expose any extra cookie metadata through this API, this
patch removes those extra attributes and their feature flag.
Discussion about WebKit&apos;s standards position on this:
(<a href="https://github.com/WebKit/standards-positions/issues/36)">https://github.com/WebKit/standards-positions/issues/36)</a>

* LayoutTests/imported/w3c/web-platform-tests/cookie-store/cookieListItem_attributes.https.any-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/cookie-store/cookieListItem_attributes.https.any.serviceworker-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/cookie-store/cookieStore_set_arguments.https.any-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/cookie-store/cookieStore_set_arguments.https.any.serviceworker-expected.txt:
* Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml:
* Source/WebCore/Modules/cookie-store/CookieListItem.h:
(WebCore::CookieListItem::CookieListItem):
(): Deleted.
* Source/WebCore/Modules/cookie-store/CookieListItem.idl:
</pre>

2024-08-15 23:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b91024fa2afcbfcae300ef998764cab7e0edb220. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32273

2024-08-15 23:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7f0cfaf9724b6b7ee3dae686e08c8abd4e778c49. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32273

2024-08-15 23:58 UTC, szewai approved these changes
r = me if bots are happy

2024-08-16 02:27 UTC, cdumez requested changes
No, why are we doing this. Please keep those behind a runtime flag.

2024-08-16 02:30 UTC, cdumez commented
We need a new flag to disable the service worker support though, I was hoping this was going to be the next PR.

2024-08-16 05:54 UTC, szewai commented
> No, why are we doing this? Please keep those behind a runtime flag, unless they've been removed from the spec.

Unlike the other parts of the API where we may not have a position yet, we've stated our opposition to these attributes https://github.com/WebKit/standards-positions/issues/36#issuecomment-1620170910 (so does Mozilla), so it seems confusing to have a feature flag (testable status) and implementation in place to indicate interests in shipping this. 

The spec is a proposal, and we will only move subset of it to w3c working group for formal standardization.

2024-08-16 14:55 UTC, cdumez commented
> > No, why are we doing this? Please keep those behind a runtime flag, unless they've been removed from the spec.
> 
> Unlike the other parts of the API where we may not have a position yet, we've stated our opposition to these attributes [WebKit/standards-positions#36 (comment)](https://github.com/WebKit/standards-positions/issues/36#issuecomment-1620170910) (so does Mozilla), so it seems confusing to have a feature flag (testable status) and implementation in place to indicate interests in shipping this.
> 
> The spec is a proposal, and we will only move subset of it to w3c working group for formal standardization.

I still object to this change as long as the spec and the WPT tests haven't been updated. Our opposition is about shipping these and they're already not shipping since they're behind a flag off by default.

2024-11-06 18:26 UTC, RupinMittal commented
We have decided to make this change, so I'm marking this PR as closed.

2024-11-06 18:26 UTC, closed without merging