Don't crash if we can't allocate JIT memory on non-JIT systems
WebKit/WebKit pull request #32487
Opened 2024-08-20 22:29 UTC by danlliu

#### 1c13fc7138ca500f77af87d0ab3b89471c19418b
<pre>
Don&apos;t crash if we can&apos;t allocate JIT memory on non-JIT systems
<a href="https://bugs.webkit.org/show_bug.cgi?id=278421">https://bugs.webkit.org/show_bug.cgi?id=278421</a>
<a href="https://rdar.apple.com/133718210">rdar://133718210</a>

Reviewed by NOBODY (OOPS!).

If we are on a non-JIT platform, we will not be using JIT memory, so
we should not crash because we failed to allocate JIT memory.

* Source/JavaScriptCore/jsc.cpp:
(CommandLine::parseArguments):
</pre>

2024-08-20 22:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1c13fc7138ca500f77af87d0ab3b89471c19418b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32487

2024-08-20 23:04 UTC, Constellation approved these changes
r=me

2024-08-20 23:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/11f44410aede176c763fece44cf7a90461eaa6c0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32487

2024-08-20 23:34 UTC, MenloDorian requested changes

2024-08-20 23:34 UTC, MenloDorian commented on Source/JavaScriptCore/jsc.cpp
> +#if PLATFORM(IOS_FAMILY) && (~PLATFORM(APPLETV) && ~PLATFORM(WATCHOS))
This should be:
```
#if PLATFORM(IOS_FAMILY) && !PLATFORM(APPLETV) && !PLATFORM(WATCHOS)
```

2024-08-20 23:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1d09e74063fec945260ac06e7db976636785fe45. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32487

2024-08-20 23:41 UTC, MenloDorian approved these changes
r=me

2024-08-21 00:26 UTC, webkit-commit-queue commented
Committed 282536@main (e6baf795c1f5): <https://commits.webkit.org/282536@main>

Reviewed commits have been landed. Closing PR #32487 and removing active labels.

2024-08-21 00:26 UTC, merged