Disable use of JSC signal handlers when JIT is disabled.
WebKit/WebKit pull request #32525
Opened 2024-08-21 16:02 UTC by MenloDorian

#### 39cf42fa2544eaec0487f32c8aaa168ebc798446
<pre>
Disable use of JSC signal handlers when JIT is disabled.
<a href="https://bugs.webkit.org/show_bug.cgi?id=278401">https://bugs.webkit.org/show_bug.cgi?id=278401</a>
<a href="https://rdar.apple.com/134053581">rdar://134053581</a>

Reviewed by NOBODY (OOPS!).

We can use JIT disablement as a proxy indicator that use of mach exception handlers are not
allowed in the system.  So, we&apos;ll just disable JSC signal based options when the JIT is disabled.

Note that all places where we disable the JIT (via setting useJIT to false) will be followed by
a call to Options::notifyOptionsChanged().  So, that is the natural place to disable signal
handler based options for this purpose if appropriate.

* Source/JavaScriptCore/runtime/Options.cpp:
(JSC::disableAllSignalHandlerBasedOptions):
(JSC::Options::notifyOptionsChanged):
</pre>

2024-08-21 16:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/39cf42fa2544eaec0487f32c8aaa168ebc798446. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32525

2024-08-21 16:04 UTC, kmiller68 approved these changes
r=me.

2024-08-21 16:55 UTC, Constellation commented on Source/JavaScriptCore/runtime/Options.cpp
> +}
What happens when we are in WebContent process with LDM? We need to enable them.

2024-08-21 17:10 UTC, Constellation requested changes
Yeah, I think we need to enable them on LDM. So this requires some more changes.

2024-08-21 20:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/baaa6aa4381cc32ec16b08ef64401a9a4f4a532d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32525

2024-08-21 20:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b9adec501fef73cd7de742312369a5dfbad3502f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32525

2024-08-21 20:42 UTC, kmiller68 approved these changes

2024-08-21 20:43 UTC, Constellation approved these changes
r=me

2024-08-21 20:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3e980518b4db2a61c53113358fa93fb217ea7225. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32525

2024-08-22 00:25 UTC, webkit-commit-queue commented
Committed 282592@main (1add1eb4c01a): <https://commits.webkit.org/282592@main>

Reviewed commits have been landed. Closing PR #32525 and removing active labels.

2024-08-22 00:25 UTC, merged