Chromium test-case crashes near null under lastHyphenLocation.
WebKit/WebKit pull request #32609
Opened 2024-08-22 21:41 UTC by zakariaridouh

#### 4014d21e0df427970cb05efad4800ea5ff0bcea4
<pre>
Chromium test-case crashes near null under lastHyphenLocation.
<a href="https://bugs.webkit.org/show_bug.cgi?id=202912">https://bugs.webkit.org/show_bug.cgi?id=202912</a>
<a href="https://rdar.apple.com/134527900">rdar://134527900</a>

Reviewed by NOBODY (OOPS!).

Add potential GTK crash test to debug.

* LayoutTests/fast/css/compute-preferred-logical-widths-crash-expected.txt: Added.
* LayoutTests/fast/css/compute-preferred-logical-widths-crash.html: Added.
</pre>

2024-08-22 21:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4014d21e0df427970cb05efad4800ea5ff0bcea4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32609

2024-08-23 14:26 UTC, rreno requested changes
Please improve the commit message. Include the Chromium commit the test came from and what its testing.

2024-08-29 16:49 UTC, Ahmad-S792 commented
@zakariaridouh - It was added in following commit - https://source.chromium.org/chromium/chromium/src/+/012fda7476fc904c76f1a9f2dc82cb92076bddb4

2025-01-15 21:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/495888e579200fadb0674e9d4ba729641557c03e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32609

2025-01-31 01:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/41c6bf6469b12e5017261d7ff626be572d317399. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32609

2025-01-31 01:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/be5b31b5682c6b65bc993c8d23c3668dff88bc2d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32609

2025-02-06 23:35 UTC, rreno approved these changes

2025-02-06 23:49 UTC, webkit-commit-queue commented
Committed 289971@main (96ace0a27658): <https://commits.webkit.org/289971@main>

Reviewed commits have been landed. Closing PR #32609 and removing active labels.

2025-02-06 23:49 UTC, merged