Rename WebPageProxy and LocalFrameLoaderClient functions to be less ambiguous
WebKit/WebKit pull request #32662
Opened 2024-08-24 03:05 UTC by rreno

#### 1cae342738db4147a112b13bfef279998c945b7c
<pre>
Rename WebPageProxy and LocalFrameLoaderClient functions to be less ambiguous
<a href="https://bugs.webkit.org/show_bug.cgi?id=278597">https://bugs.webkit.org/show_bug.cgi?id=278597</a>
<a href="https://rdar.apple.com/134603009">rdar://134603009</a>

Reviewed by NOBODY (OOPS!).

didSameDocumentNavigationForFrameViaJSHistoryAPI might be parsed as
&quot;did same document navigation for &apos;JS History API&apos;&quot;
when in fact it means
&quot;did same document navigation for &apos;JS&apos; OR &apos;JS History API&apos;&quot;.

This patch is a slight rename to the functions and IPC messages to
hopefully be more clear that this represents either a History API or a
client JavaScript-initiated navigation.

* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::didSameDocumentNavigationForFrameViaHistoryAPIOrJS):
(WebKit::WebPageProxy::didSameDocumentNavigationForFrameViaJSHistoryAPI): Deleted.
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/UIProcess/WebPageProxy.messages.in:
* Source/WebKit/WebProcess/WebCoreSupport/WebLocalFrameLoaderClient.cpp:
(WebKit::WebLocalFrameLoaderClient::didSameDocumentNavigationForFrameViaHistoryAPIOrJS):
(WebKit::WebLocalFrameLoaderClient::dispatchDidPushStateWithinPage):
(WebKit::WebLocalFrameLoaderClient::dispatchDidReplaceStateWithinPage):
(WebKit::WebLocalFrameLoaderClient::dispatchDidPopStateWithinPage):
(WebKit::WebLocalFrameLoaderClient::didSameDocumentNavigationForFrameViaJSHistoryAPI): Deleted.
* Source/WebKit/WebProcess/WebCoreSupport/WebLocalFrameLoaderClient.h:
</pre>

2024-08-24 03:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1cae342738db4147a112b13bfef279998c945b7c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32662

2024-08-24 03:09 UTC, cdumez commented
> didSameDocumentNavigationForFrameViaJSHistoryAPI might be parsed as
> "did same document navigation for 'JS History API'"
> when in fact it means
> "did same document navigation for 'JS' OR 'JS History API'".

I don't understand this PR. As far as I know, the function name is accurate. It means that the same document navigation was triggered by the JS history API (e.g. history.pushState).

2024-08-24 03:10 UTC, cdumez requested changes
I think this old name was more accurate?

2024-08-24 03:14 UTC, rreno commented
No this gets triggered from same-document navigations from HTMLElement.click as well.

2024-08-24 03:24 UTC, cdumez commented
> No this gets triggered from same-document navigations from HTMLElement.click as well.

Even so, I don't think "HistoryAPIOrJS" makes sense since the History API is JS.

Let's just rename to `ViaJS` then?

2024-08-24 03:28 UTC, rreno commented
Yes, so `didSameDocumentNavigationForFrameViaJS` omitting the `HistoryAPI`? Happy to make that change.

2024-08-24 03:29 UTC, cdumez commented
> Yes, so `didSameDocumentNavigationForFrameViaJS` omitting the `HistoryAPI`? Happy to make that change.

Yes. I think that's clearer.

2024-08-24 04:31 UTC, cdumez commented
> No this gets triggered from same-document navigations from HTMLElement.click as well.

Seems like the kind of information that would be valuable to have in the commit log message :)

2024-08-24 04:43 UTC, rreno commented
>Seems like the kind of information that would be valuable to have in the commit log message :)

Yes. While I'm trying to make things more clear I could myself be more clear with my intent!

2024-08-24 04:48 UTC, rreno commented
I'm actually questioning the call to `m_client->dispatchDidPopStateWithinPage` in `FrameLoader::loadInSameDocument` which is why this is getting called in the first place.

The path is (omitting some stack frames) `jsHTMLElementPrototypeFunction_click` -> `WebCore::simulateClick` -> `HTMLAnchorElement::handleClick` -> `FrameLoader::changeLocation` -> `FrameLoader::continueFragmentScrollAfterNavigationPolicy` -> `FrameLoader::loadInSameDocument`

2024-08-24 05:15 UTC, rreno commented
OK its probably fine as this call has existed since the History API was added in 2009. That said, `FrameLoader::loadInSameDocument` was probably co-opted for other things beyond its originally intended use over the years and maybe its worth making a change to this function rather than the rename. I'll think on it over the weekend.

2024-09-12 15:40 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/30416feb080993176191b7b2f5aaac733ea08020)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/66661 "Build is in progress. Recent messages:") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-17-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/70695 "Build is in progress. Recent messages:") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/17559 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/70695 "Build is in progress. Recent messages:") | [⏳ 🧪 wincairo-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/69728 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/70695 "Build is in progress. Recent messages:") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/66173 "Build is in progress. Recent messages:") | [⏳ 🧪 ios-wk2-wpt ](https://ews-build.webkit.org/#/builders/iOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/16148 "Build is in progress. Recent messages:") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/72397 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/10618 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/61/builds/17559 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/72397 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/10650 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/72397 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/19283 "Build is in progress. Recent messages:") | | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-17-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-17-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/44103 "Build is in progress. Recent messages:Running configuration") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-10-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2024-09-13 15:14 UTC, cdumez approved these changes

2024-09-13 15:32 UTC, webkit-commit-queue commented
Committed 283623@main (8972ce9795a8): <https://commits.webkit.org/283623@main>

Reviewed commits have been landed. Closing PR #32662 and removing active labels.

2024-09-13 15:32 UTC, merged