The download client should be able to determine if a placeholder should be used
WebKit/WebKit pull request #32777
Opened 2024-08-27 20:38 UTC by pvollan

#### 8c63ced7cc407b6a079ea3101ebbe7e7825030df
<pre>
The download client should be able to determine if a placeholder should be used
<a href="https://bugs.webkit.org/show_bug.cgi?id=278737">https://bugs.webkit.org/show_bug.cgi?id=278737</a>
<a href="https://rdar.apple.com/134794671">rdar://134794671</a>

Reviewed by NOBODY (OOPS!).

The download client should be able to determine if a placeholder should be used. This patch prepares for this
by passing the value from the UI process to the Networking process.

* Source/WebKit/NetworkProcess/Downloads/Download.h:
* Source/WebKit/NetworkProcess/Downloads/DownloadManager.cpp:
(WebKit::DownloadManager::publishDownloadProgress):
* Source/WebKit/NetworkProcess/Downloads/DownloadManager.h:
* Source/WebKit/NetworkProcess/Downloads/PendingDownload.cpp:
(WebKit::PendingDownload::publishProgress):
(WebKit::PendingDownload::didBecomeDownload):
* Source/WebKit/NetworkProcess/Downloads/PendingDownload.h:
* Source/WebKit/NetworkProcess/Downloads/cocoa/DownloadCocoa.mm:
(WebKit::Download::publishProgress):
* Source/WebKit/NetworkProcess/NetworkProcess.cpp:
(WebKit::NetworkProcess::publishDownloadProgress):
* Source/WebKit/NetworkProcess/NetworkProcess.h:
* Source/WebKit/NetworkProcess/NetworkProcess.messages.in:
* Source/WebKit/UIProcess/Downloads/DownloadProxy.h:
(WebKit::DownloadProxy::setUseDownloadPlaceholder):
* Source/WebKit/UIProcess/Downloads/DownloadProxyCocoa.mm:
(WebKit::DownloadProxy::publishProgress):
</pre>

2024-08-27 20:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8c63ced7cc407b6a079ea3101ebbe7e7825030df. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-28 15:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4983819a5a08bad3e66b2f4dd8df9e8ffff77caa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-28 16:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff80a014098890505267e2db256dbba8d7c28dc4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-28 17:35 UTC, achristensen07 requested changes

2024-08-28 17:35 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/Cocoa/WKDownloadDelegate.h
> +- (void)download:(WKDownload *)download decidePlaceholderPolicy:(WK_SWIFT_UI_ACTOR void (^)(WKPlaceholderPolicy))completionHandler;
This needs WK_API_AVAILABLE

2024-08-28 17:35 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/Cocoa/_WKDownload.mm
> +    _download->_download->publishProgress(URL, false);
Could you give false a name?

2024-08-28 17:35 UTC, achristensen07 commented on Source/WebKit/UIProcess/Downloads/DownloadProxy.cpp
> +                    publishProgress(URL::fileURLWithFileSystemPath(destination), usePlaceholder == WebKit::UseDownloadPlaceholder::Yes);
I think publishProgress needs to be part of the completion handler.  We shouldn't send the destination to the network process without the placeholder policy.

2024-08-28 21:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2663ae4677f27ab35f4763da202b6519c1508142. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-28 22:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/debbafe5f45c02e3307f526dcdfc203abc1f7052. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-28 22:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eef5028f7d5a91b4c4983ac1d1f58d7adbb38e2b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-29 01:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f153844c9062e5541f8bbf73b5ecc7323831b828. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-29 16:04 UTC, achristensen07 requested changes
This needs a test that makes sure the delegate is actually called.

2024-08-29 16:04 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/Cocoa/WKDownloadDelegatePrivate.h
> +- (void)download:(WKDownload *)download _decidePlaceholderPolicy:(WK_SWIFT_UI_ACTOR void (^)(_WKPlaceholderPolicy))completionHandler WK_API_AVAILABLE(WK_MAC_TBA, WK_IOS_TBA);
Underscore needs to be before the first part of the selector.  _download:decidePlaceholderPolicy:
SPI probably doesn't need WK_SWIFT_UI_ACTOR

2024-08-29 16:04 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/Downloads/PendingDownload.h
> +    UseDownloadPlaceholder m_useDownloadPlaceholder { false };
UseDownloadPlaceholder::No

2024-08-29 16:04 UTC, achristensen07 commented on Source/WebKit/UIProcess/Downloads/DownloadProxy.cpp
> +                publishProgress(URL::fileURLWithFileSystemPath(destination), usePlaceholder);
I think we should remove this and just add another parameter to the completionHandler instead.  That'll be a little tricky with _WKDownload still existing, but we'll soon remove _WKDownload's ability to publish progress.

2024-08-29 21:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e3144fcb4fce015ee7c97ce51f5d78f5578d662a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-29 23:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a3b2992ede609a5323507bdc8e12bb18fff04641. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-29 23:57 UTC, pvollan commented on Source/WebKit/UIProcess/API/Cocoa/WKDownloadDelegatePrivate.h
> +- (void)download:(WKDownload *)download _decidePlaceholderPolicy:(WK_SWIFT_UI_ACTOR void (^)(_WKPlaceholderPolicy))completionHandler WK_API_AVAILABLE(WK_MAC_TBA, WK_IOS_TBA);
Fixed in latest patch!

Thanks for reviewing!

2024-08-30 00:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/227afc9c10be770ad1d771fd8a151541997ba245. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-30 16:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/138c7419c888f6623c565a91cf36370d91dcff63. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-08-30 16:33 UTC, achristensen07 approved these changes

2024-08-30 18:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/87cae751e7b70bdaa1f2e6801f006f08a724eb20. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-09-01 17:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/158000cbf746f5652e58973c7d88a5f4fded3574. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-09-01 22:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fad6993143022b4d3cc126601f71ae95b0cbea5e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/32777

2024-09-01 23:14 UTC, webkit-commit-queue commented
Committed 283043@main (e3fcc5543b97): <https://commits.webkit.org/283043@main>

Reviewed commits have been landed. Closing PR #32777 and removing active labels.

2024-09-01 23:15 UTC, merged