[WebCore] Remove tertiarySystemFillColor selector check
WebKit/WebKit pull request #33015
Opened 2024-09-01 23:53 UTC by RSilicon

<pre>[WebCore] Remove tertiarySystemFillColor selector check
https://bugs.webkit.org/show_bug.cgi?id=278999

Reviewed by NOBODY (OOPS!).

tertiarySystemFillColor is supported on macOS 13 and up.

* Source/WebCore/rendering/mac/RenderThemeMac.mm: (WebCore::RenderThemeMac::systemColor const): Remove selector check.
</pre>

2024-09-01 23:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f932334d7868f72568a44f17ea186bdac861b947. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-02 14:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a573e40b8721ebfb59a67fe61790b2dd94b09a07. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-02 14:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7e4274f3c36e9ebdbd47c5af17e44517891c5714. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-02 17:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cf3b1971f1a8fe03b9d5d4519464473c5ae56e90. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-02 19:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/48f953f023892ae3409086008f478ecb602d36e4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-02 21:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/19deba749cd94877f8c17743ebab1e7e1da2033b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-03 03:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3c6c2ed69df17babce10e69aa7ae4e56c215cd94. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-03 04:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1abebc0d1e16bea15dbafe9575a1b34bff0585a1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-03 14:48 UTC, RSilicon commented
@pxlcoder Thoughts on this?

2024-09-03 16:25 UTC, Ahmad-S792 commented
Link - https://developer.apple.com/documentation/uikit/uicolor/3255076-tertiarysystemfill

2024-09-03 16:26 UTC, Ahmad-S792 commented
@RSilicon - I think you are using the same bug for another PR as well. Can you create newer bug for this or for other one?

2024-09-03 18:11 UTC, RSilicon commented
> https://bugs.webkit.org/show_bug.cgi?id=278999

No I am not. This is meant for this.

2024-09-03 18:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/78b55166f16f84fd85a7bbd30033cceee802750a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-03 18:29 UTC, RSilicon commented
> Link - https://developer.apple.com/documentation/uikit/uicolor/3255076-tertiarysystemfill

Added to PR message.

2024-09-03 19:58 UTC, pxlcoder requested changes
It's fine to remove the selector check, since `HAVE(NSCOLOR_FILL_COLOR_HIERARCHY)` will protect us on older OSes.

But the commit message is wrong. The documentation link is incorrect, since the link is for UIKit. The code is here private AppKit API that was only added in macOS 14 (which is the other incorrect bit, as the commit message references "macOS 13").

Requesting changes for the commit message, I will approve once that is fixed.

2024-09-03 20:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/282543fee4cfcf1cb3b0b157a0a7a47b980e3114. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33015

2024-09-03 20:52 UTC, RSilicon commented
> It's fine to remove the selector check, since `HAVE(NSCOLOR_FILL_COLOR_HIERARCHY)` will protect us on older OSes.
> 
> But the commit message is wrong. The documentation link is incorrect, since the link is for UIKit. The code is here private AppKit API that was only added in macOS 14 (which is the other incorrect bit, as the commit message references "macOS 13").
> 
> Requesting changes for the commit message, I will approve once that is fixed.

Done!

2024-09-03 20:53 UTC, pxlcoder approved these changes

2024-09-03 21:40 UTC, webkit-commit-queue commented
Committed 283115@main (84c6a1eb31e3): <https://commits.webkit.org/283115@main>

Reviewed commits have been landed. Closing PR #33015 and removing active labels.

2024-09-03 21:40 UTC, merged