dladukedev.com shows white for 5 seconds.
WebKit/WebKit pull request #33163
Opened 2024-09-05 02:25 UTC by mattwoodrow

#### 37ac83fc2506084e898e1c69ac095aeab5b04410
<pre>
dladukedev.com shows white for 5 seconds.
<a href="https://bugs.webkit.org/show_bug.cgi?id=279165">https://bugs.webkit.org/show_bug.cgi?id=279165</a>
&lt;<a href="https://rdar.apple.com/135315499">rdar://135315499</a>&gt;
Include a Radar link (OOPS!).

Reviewed by NOBODY (OOPS!).

Render blocking prevents the page from being displayed until the timeout.

The page has a &lt;link rel=expect&gt; render blocking link that never gets resolved.

Render blocking for &lt;link&gt; should only be in place while the Document&apos;s ready state is &apos;loading&apos;, and should be removed once the page is fully loaded.

No new test, because I haven&apos;t figured out to write a decent one for it. Reftests ignore render blocking since they&apos;re not waiting on rAF.

* Source/WebCore/dom/Document.cpp:
(WebCore::Document::setReadyState):
(WebCore::Document::processInternalResourceLinks):
* Source/WebCore/dom/Document.h:
* Source/WebCore/html/HTMLAnchorElement.cpp:
(WebCore::HTMLAnchorElement::attributeChanged):
(WebCore::HTMLAnchorElement::insertedIntoAncestor):
</pre>

2024-09-05 02:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/37ac83fc2506084e898e1c69ac095aeab5b04410. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33163

2024-09-05 07:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e288b11d247afcfb14e715500d5ed80d6dcee060. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33163

2024-09-05 13:50 UTC, nt1m approved these changes
Would be really good to have some kind of test here.

2024-09-05 14:01 UTC, nt1m requested changes
This seems to fail tests

2024-09-05 22:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/287e95131e33ecc9ed94bc5a564f86e436e69a79. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33163

2024-09-05 22:53 UTC, mattwoodrow commented
> This seems to fail tests

Indeed! Fixed now, and added a test.

2024-09-06 00:35 UTC, nt1m approved these changes

2024-09-06 02:42 UTC, webkit-commit-queue commented
Committed 283246@main (64c4d3857e78): <https://commits.webkit.org/283246@main>

Reviewed commits have been landed. Closing PR #33163 and removing active labels.

2024-09-06 02:42 UTC, merged