[scroll-animations] Add ScrollTimeline and ViewTimeline to AnimationTimelinesController
WebKit/WebKit pull request #33424
Opened 2024-09-10 21:39 UTC by nmoucht

#### da8506fafb9615a65f39aff8084e4235743c06f4
<pre>
[scroll-animations] Add ScrollTimeline and ViewTimeline to AnimationTimelinesController
<a href="https://bugs.webkit.org/show_bug.cgi?id=279468">https://bugs.webkit.org/show_bug.cgi?id=279468</a>
<a href="https://rdar.apple.com/135751833">rdar://135751833</a>

Reviewed by NOBODY (OOPS!).

Add newly created ScrollTimeline and ViewTimeline objects to AnimationTimelinesController.

* Source/WebCore/animation/ScrollTimeline.cpp:
(WebCore::ScrollTimeline::ScrollTimeline):
* Source/WebCore/animation/ViewTimeline.cpp:
(WebCore::ViewTimeline::ViewTimeline):
</pre>

2024-09-10 21:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/da8506fafb9615a65f39aff8084e4235743c06f4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33424

2024-09-10 22:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8f72f04144e1f4bcd03cbf09384cf8e0aaf5089b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33424

2024-09-11 03:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4f7fcca1d6b4e9268a58091b36461e49f69b04e8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33424

2024-09-11 08:10 UTC, graouts requested changes

2024-09-11 08:10 UTC, graouts commented on Source/WebCore/animation/ViewTimeline.cpp
> +        m_subject->document().ensureTimelinesController().addTimeline(*this);
Ditto about using `protectedDocument()`.

2024-09-11 08:10 UTC, graouts commented on Source/WebCore/animation/ScrollTimeline.cpp
> +        m_source->document().ensureTimelinesController().addTimeline(*this);
Use `protectedDocument()` instead.

2024-09-11 08:10 UTC, graouts commented on Source/WebCore/animation/ScrollTimeline.cpp
> +        m_source->document().ensureTimelinesController().addTimeline(*this);
Use `protectedDocument()` instead.

2024-09-11 08:10 UTC, graouts commented on Source/WebCore/animation/ViewTimeline.cpp
> +        m_subject->document().ensureTimelinesController().addTimeline(*this);
Ditto about using `protectedDocument()`.

2024-09-11 17:01 UTC, nmoucht commented on Source/WebCore/animation/ViewTimeline.cpp
> +        m_subject->document().ensureTimelinesController().addTimeline(*this);
Fixed.

2024-09-11 17:01 UTC, nmoucht commented on Source/WebCore/animation/ScrollTimeline.cpp
> +        m_source->document().ensureTimelinesController().addTimeline(*this);
Fixed.

2024-09-11 17:01 UTC, nmoucht commented on Source/WebCore/animation/ScrollTimeline.cpp
> +        m_source->document().ensureTimelinesController().addTimeline(*this);
Fixed.

2024-09-11 17:02 UTC, nmoucht commented on Source/WebCore/animation/ViewTimeline.cpp
> +        m_subject->document().ensureTimelinesController().addTimeline(*this);
Fixed.

2024-09-11 19:42 UTC, graouts approved these changes

2024-09-11 20:27 UTC, webkit-commit-queue commented
Committed 283500@main (b88277880690): <https://commits.webkit.org/283500@main>

Reviewed commits have been landed. Closing PR #33424 and removing active labels.

2024-09-11 20:27 UTC, merged