Port WebExtensionCocoa to C++
WebKit/WebKit pull request #33446
Opened 2024-09-11 06:17 UTC by ItsJamie9494

#### 23a23ecbb5ddaccabae181b67de32cc97e2edbae
<pre>
Port WebExtensionCocoa to C++
<a href="https://webkit.org/b/279491">https://webkit.org/b/279491</a>

Reviewed by NOBODY (OOPS!).

This creates a C++ WebExtension manifest parser class, and fixes any integration with the manifest parser throughout WebKit.

* Source/WTF/wtf/JSONValues.cpp:
(WTF::JSONImpl::Value::operator==):
* Source/WTF/wtf/JSONValues.h:
(WTF::JSONImpl::Value::operator! const):
* Source/WebKit/Platform/cocoa/CocoaHelpers.h:
* Source/WebKit/Platform/cocoa/CocoaHelpers.mm:
(WebKit::toDataMap):
* Source/WebKit/Shared/Extensions/WebExtensionPermission.cpp: Added.
(WebKit::WebExtensionPermission::activeTab):
(WebKit::WebExtensionPermission::alarms):
(WebKit::WebExtensionPermission::clipboardWrite):
(WebKit::WebExtensionPermission::contextMenus):
(WebKit::WebExtensionPermission::cookies):
(WebKit::WebExtensionPermission::declarativeNetRequest):
(WebKit::WebExtensionPermission::declarativeNetRequestFeedback):
(WebKit::WebExtensionPermission::declarativeNetRequestWithHostAccess):
(WebKit::WebExtensionPermission::menus):
(WebKit::WebExtensionPermission::nativeMessaging):
(WebKit::WebExtensionPermission::notifications):
(WebKit::WebExtensionPermission::scripting):
(WebKit::WebExtensionPermission::sidePanel):
(WebKit::WebExtensionPermission::storage):
(WebKit::WebExtensionPermission::tabs):
(WebKit::WebExtensionPermission::unlimitedStorage):
(WebKit::WebExtensionPermission::webNavigation):
(WebKit::WebExtensionPermission::webRequest):
* Source/WebKit/Shared/Extensions/WebExtensionPermission.h: Added.
* Source/WebKit/Shared/Extensions/WebExtensionUtilities.cpp: Added.
(WebKit::filterObjects):
(WebKit::makeStringVector):
* Source/WebKit/Shared/Extensions/WebExtensionUtilities.h:
* Source/WebKit/Shared/Extensions/_WKWebExtensionLocalization.mm:
(-[_WKWebExtensionLocalization _localizationDictionaryForWebExtension:withLocale:]):
* Source/WebKit/Sources.txt:
* Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm:
(+[WKWebExtension extensionWithAppExtensionBundle:completionHandler:]):
(+[WKWebExtension extensionWithResourceBaseURL:completionHandler:]):
(-[WKWebExtension _initWithAppExtensionBundle:error:]):
(-[WKWebExtension _initWithResourceBaseURL:error:]):
(-[WKWebExtension _initWithManifestDictionary:resources:]):
(-[WKWebExtension _initWithResources:]):
(-[WKWebExtension manifest]):
(-[WKWebExtension iconForSize:]):
(-[WKWebExtension actionIconForSize:]):
(-[WKWebExtension errors]):
* Source/WebKit/UIProcess/API/Cocoa/WKWebExtensionAction.mm:
(-[WKWebExtensionAction iconForSize:]):
* Source/WebKit/UIProcess/Extensions/Cocoa/API/WebExtensionContextAPIActionCocoa.mm:
(WebKit::WebExtensionContext::actionSetIcon):
(WebKit::WebExtensionContext::actionGetPopup): Deleted.
(WebKit::WebExtensionContext::actionSetPopup): Deleted.
(WebKit::WebExtensionContext::actionOpenPopup): Deleted.
(WebKit::WebExtensionContext::actionGetBadgeText): Deleted.
(WebKit::WebExtensionContext::actionSetBadgeText): Deleted.
(WebKit::WebExtensionContext::actionGetEnabled): Deleted.
(WebKit::WebExtensionContext::actionSetEnabled): Deleted.
(WebKit::WebExtensionContext::fireActionClickedEventIfNeeded): Deleted.
* Source/WebKit/UIProcess/Extensions/Cocoa/API/WebExtensionContextAPIScriptingCocoa.mm:
(WebKit::WebExtensionContext::createInjectedContentForScripts):
* Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm:
(WebKit::WebExtensionAction::WebExtensionAction):
(WebKit::WebExtensionAction::clearCustomizations):
(WebKit::WebExtensionAction::icon):
(WebKit::WebExtensionAction::setIcons):
(WebKit::WebExtensionAction::popupWebViewInspectionName):
(WebKit::WebExtensionAction::label const):
* Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm:
(WebKit::WebExtension::WebExtension):
(WebKit::WebExtension::resourceTypeForPath):
(WebKit::WebExtension::resourceDataForPath):
(WebKit::WebExtension::recordError):
(WebKit::WebExtension::imageForPath):
(WebKit::WebExtension::bestImageInIconsDictionary):
(WebKit::WebExtension::bestImageForIconVariants):
(WebKit::WebExtension::manifestParsedSuccessfully): Deleted.
(WebKit::WebExtension::parseManifest): Deleted.
(WebKit::WebExtension::manifest): Deleted.
(WebKit::WebExtension::serializeManifest): Deleted.
(WebKit::WebExtension::manifestVersion): Deleted.
(WebKit::WebExtension::isWebAccessibleResource): Deleted.
(WebKit::WebExtension::populateWebAccessibleResourcesIfNeeded): Deleted.
(WebKit::WebExtension::resourceFileURLForPath): Deleted.
(WebKit::WebExtension::resourceStringForPath): Deleted.
(WebKit::WebExtension::hasRequestedPermission const): Deleted.
(WebKit::toAPI): Deleted.
(WebKit::WebExtension::createError): Deleted.
(WebKit::WebExtension::errors): Deleted.
(WebKit::WebExtension::displayName): Deleted.
(WebKit::WebExtension::displayShortName): Deleted.
(WebKit::WebExtension::displayVersion): Deleted.
(WebKit::WebExtension::displayDescription): Deleted.
(WebKit::WebExtension::version): Deleted.
(WebKit::WebExtension::populateExternallyConnectableIfNeeded): Deleted.
(WebKit::WebExtension::populateDisplayStringsIfNeeded): Deleted.
(WebKit::WebExtension::contentSecurityPolicy): Deleted.
(WebKit::WebExtension::populateContentSecurityPolicyStringsIfNeeded): Deleted.
(WebKit::WebExtension::icon): Deleted.
(WebKit::WebExtension::actionIcon): Deleted.
(WebKit::WebExtension::displayActionLabel): Deleted.
(WebKit::WebExtension::actionPopupPath): Deleted.
(WebKit::WebExtension::hasAction): Deleted.
(WebKit::WebExtension::hasBrowserAction): Deleted.
(WebKit::WebExtension::hasPageAction): Deleted.
(WebKit::WebExtension::populateActionPropertiesIfNeeded): Deleted.
(WebKit::WebExtension::hasSidebar): Deleted.
(WebKit::WebExtension::sidebarIcon): Deleted.
(WebKit::WebExtension::sidebarDocumentPath): Deleted.
(WebKit::WebExtension::sidebarTitle): Deleted.
(WebKit::WebExtension::populateSidebarPropertiesIfNeeded): Deleted.
(WebKit::WebExtension::populateSidebarActionProperties): Deleted.
(WebKit::WebExtension::populateSidePanelProperties): Deleted.
(WebKit::WebExtension::bestSizeInIconsDictionary): Deleted.
(WebKit::WebExtension::pathForBestImageInIconsDictionary): Deleted.
(WebKit::WebExtension::bestImageForIconsDictionaryManifestKey): Deleted.
(WebKit::toColorSchemes): Deleted.
(WebKit::WebExtension::iconsDictionaryForBestIconVariant): Deleted.
(WebKit::WebExtension::bestImageForIconVariantsManifestKey): Deleted.
(WebKit::WebExtension::hasBackgroundContent): Deleted.
(WebKit::WebExtension::backgroundContentIsPersistent): Deleted.
(WebKit::WebExtension::backgroundContentUsesModules): Deleted.
(WebKit::WebExtension::backgroundContentIsServiceWorker): Deleted.
(WebKit::WebExtension::backgroundContentPath): Deleted.
(WebKit::WebExtension::generatedBackgroundContent): Deleted.
(WebKit::WebExtension::populateBackgroundPropertiesIfNeeded): Deleted.
(WebKit::WebExtension::hasInspectorBackgroundPage): Deleted.
(WebKit::WebExtension::inspectorBackgroundPagePath): Deleted.
(WebKit::WebExtension::populateInspectorPropertiesIfNeeded): Deleted.
(WebKit::WebExtension::hasOptionsPage): Deleted.
(WebKit::WebExtension::hasOverrideNewTabPage): Deleted.
(WebKit::WebExtension::optionsPagePath): Deleted.
(WebKit::WebExtension::overrideNewTabPagePath): Deleted.
(WebKit::WebExtension::populatePagePropertiesIfNeeded): Deleted.
(WebKit::WebExtension::commands): Deleted.
(WebKit::WebExtension::hasCommands): Deleted.
(WebKit::parseCommandShortcut): Deleted.
(WebKit::WebExtension::populateCommandsIfNeeded): Deleted.
(WebKit::WebExtension::staticInjectedContents): Deleted.
(WebKit::WebExtension::hasStaticInjectedContentForURL): Deleted.
(WebKit::WebExtension::hasStaticInjectedContent): Deleted.
(WebKit::WebExtension::parseDeclarativeNetRequestRulesetDictionary): Deleted.
(WebKit::WebExtension::populateDeclarativeNetRequestPropertiesIfNeeded): Deleted.
(WebKit::WebExtension::declarativeNetRequestRulesets): Deleted.
(WebKit::WebExtension::declarativeNetRequestRuleset): Deleted.
(WebKit::WebExtension::Inject [...]

2024-09-11 06:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/23a23ecbb5ddaccabae181b67de32cc97e2edbae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33446

2024-09-11 18:05 UTC, xeenon requested changes
Thanks for doing this! We would love to make this code more cross-platform going forward.

I only made it about halfway through before stopping after many suggestions. I think it is going to be easier to do this more piecemeal — moving some functions over to C++ at a time so it is easier to review and land without breaking / regressing extensions for Cocoa platforms.

As-is I have a number of concerns that this will break a number of things in various ways. Hopefully we have enough API test coverage to alleviate most of that concern, but we can always use more tests and I'm sure we don't cover all cases currently.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/Platform/cocoa/CocoaHelpers.mm
> +}
No need to get `allKeys`, iterating a dictionary iterates the keys already. There is also no guarantee the keys will be strings, so the type should be checked/casted for the key as well. Also `NSString` can be treated as a `String` for simple casts, so no need to wrap in `String()` constructor.

I'm also pretty sure this is not being used correctly yet, since it is being used for the `m_resources` cache, which can contain more than string values in tests. In addition to strings, we put `NSData`, `NSDictionary` and `NSArray` values in there that get converted to strings / data as needed. So just handling string values will drop things on the floor and cause test failures.

You will likely need something closer to this:

```suggestion
HashMap<String, std::span<const uint8_t>> toDataMap(NSDictionary *dictionary)
{
    HashMap<String, std::span<const uint8_t>> result;
    result.reserveInitialCapacity(dictionary.count);

    for (id key in dictionary) {
        auto *keyString = dynamic_objc_cast<NSString>(key);
        if (!keyString)
            continue;

        id value = dictionary[key];
        std::span<const uint8_t> dataSpan;

        if (auto *valueString = dynamic_objc_cast<NSString>(value)) {
            dataSpan = String(valueString).utf8().span();
            result.add(keyString, dataSpan);
            continue;
        }

        if (auto *valueData = dynamic_objc_cast<NSData>(value)) {
            dataSpan = std::span<const uint8_t>(reinterpret_cast<const uint8_t*>(valueData.bytes), valueData.length);
            result.add(keyString, dataSpan);
            continue;
        }

        if ([value isKindOfClass:[NSDictionary class]] || [value isKindOfClass:[NSArray class]]) {
            NSError *error;
            auto *jsonData = encodeJSONData(value, JSONOptions::FragmentsAllowed, &error);
            if (!jsonData || error)
                continue;

            dataSpan = std::span<const uint8_t>(reinterpret_cast<const uint8_t*>(jsonData.bytes), jsonData.length);
            result.add(keyString, dataSpan);
            continue;
        }
    }

    return result;
}
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/Shared/Extensions/WebExtensionUtilities.cpp
> +        if (!value)
This can't be `null` since it is a `Ref`, or is this `JSON::Value::operator!()`?

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/Shared/Extensions/WebExtensionUtilities.cpp
> +    return vector;
```suggestion
    Vector<String> vector;
    size_t count = array.length();
    vector.reserveInitialCapacity(count);

    for (Ref value : array) {
        if (auto string = value->asString(); !string.isNull())
            vector.append(WTFMove(string));
    }

    vector.shrinkToFit();
    return vector;
```

Important part is:

```c++
    size_t count = array.length();
```

Or use `auto`.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/Shared/Extensions/_WKWebExtensionLocalization.mm
> -
Please keep spacing.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/Shared/Extensions/_WKWebExtensionLocalization.mm
> -
Ditto on spacing.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
>              completionHandler(nil, error);
`__autoreleasing` isn't needed if it isn't being used as an out parameter. Also use `auto *` when possible. But this can just be one line.

```suggestion
            completionHandler(nil, wrapper(result->errors().last()));
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +        RefPtr result = WebKit::WebExtension::createWithURL(URL(resourceBaseURL));
`NSURL *` will bridge to `URL` without the constructor needed.

```suggestion
        RefPtr result = WebKit::WebExtension::createWithURL(resourceBaseURL);
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +            return;
This needs to call the `completionHandler` with `nil` and some error.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
>              completionHandler(nil, error);
```suggestion
            completionHandler(nil, wrapper(result->errors().last()));
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +        }
```suggestion
        if (error)
            *error = wrapper(result->errors().last());
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    Ref result = WebKit::WebExtension::create(appExtensionBundle);
This is unfortunate, we will be throwing away the wrapper that was allocated and returning a new object. `constructInWrapper` should be used still if possible.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    RefPtr result = WebKit::WebExtension::createWithURL(URL(resourceBaseURL));
Ditto about `constructInWrapper`.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +        }
```suggestion
        if (error)
            *error = wrapper(result->errors().last());
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/WebExtension.h
> +    explicit WebExtension(const Resources&);
Should make these so they can be r-value references so the data can be moved.

```suggestion
    explicit WebExtension(const JSON::Value& manifest, const Resources&&);
    explicit WebExtension(const Resources&&);
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/WebExtension.h
> +    std::span<const uint8_t> resourceDataForPath(String, RefPtr<API::Error> *, CacheResult = CacheResult::No, SuppressNotFoundErrors = SuppressNotFoundErrors::No);
These could be changed to return `Expected<…, Ref<API::Error>>`. Taking a pointer to a `RefPtr` is an anti-pattern.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    API::Object::constructInWrapper<WebKit::WebExtension>(self, *manifestData, resourcesData);
Should be able to `WTFMove(resourcesData)` with my other suggestion.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    API::Object::constructInWrapper<WebKit::WebExtension>(self, resourcesData);
Ditto on move.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    return dictionary;
This is incorrect. `serializeManifest()` returns JSON data, while `NSKeyedUnarchiver` expects Cocoa encoded data and will not work on JSON.

This will be something like this:
```suggestion
    return parseJSON(self._protectedWebExtension->serializeManifest());
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    return self._protectedWebExtension->icon(WebCore::FloatSize(size.width, size.height))->image().get();
`FloatSize` has a `CGSize` constructor.
```suggestion
    return self._protectedWebExtension->icon(size)->image().get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    return self._protectedWebExtension->actionIcon(WebCore::FloatSize(size.width, size.height))->image().get();
```suggestion
    return self._protectedWebExtension->actionIcon(size)->image().get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    return createNSArray(self._protectedWebExtension->errors(), [] (auto&& child) -> id {
```suggestion
    return createNSArray(self._protectedWebExtension->errors(), [](auto&& child) -> id {
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtension.mm
> +    }).autorelease();
This is ARC code, can just return `get()`.
```suggestion
    }).get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/API/Cocoa/WKWebExtensionAction.mm
> +    return self._protectedWebExtensionAction->icon(WebCore::FloatSize(size.width, size.height))->image().get();
```suggestion
    return self._protectedWebExtensionAction->icon(size)->image().get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    if (*m_customIcons == *icons)
Should not need the `*`?
```suggestion
    if (m_customIcons == icons)
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +            result = extensionContext()->extension().bestImageForIconVariants(&*m_customIconVariants, idealSize, [&](RefPtr<API::Error> *error) {
`&*m_customIconVariants` implies this can be handled better, I'll comment at the implementation. Should also not take a pointer to a `RefPtr` for the error.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    if (*m_customIconVariants == *iconVariants)
```suggestion
    if (m_customIconVariants == iconVariants)
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    }
Should use `asArray()` and `length()`? Also you forgot the else case.
```suggestion
    if (auto array = iconVariants->asArray(); array.length())
        m_customIconVariants = iconVariants;
    else
        m_customIconVariants = JSON::Value::null();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    m_cachedIconIdealSize = WebCore::FloatSize();
```suggestion
    m_cachedIconScales = { };
    m_cachedIconIdealSize = { };
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    if (auto *defaultLabel = (__bridge NSString *)extensionContext()->extension().displayActionLabel().createCFString().get(); defaultLabel.length || fallback == FallbackWhenEmpty::No)
Can cast `String` to `NSString`.
```suggestion
    if (auto *defaultLabel = static_cast<NSString *>(extensionContext()->extension().displayActionLabel()); defaultLabel.length || fallback == FallbackWhenEmpty::No)
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    String manifestData = resourceStringForPath("manifest.json"_s, nullptr);
```suggestion
    auto manifestData = resourceStringForPath("manifest.json"_s, nullptr);
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    NSString *ns_path = path.createNSStringWithoutCopying().get();
```suggestion
    auto *pathString = path.createNSStringWithoutCopying().get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    else if (auto *fileURL = (__bridge NSURL *)resourceFileURLForPath(path)->createCFURL().get())
Can cast `URL` to `NSURL`.
```suggestion
    else if (auto *fileURL = static_cast<NSURL *>(resourceFileURLForPath(path)))
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    NSString *ns_path = (__bridge NSString *)path.createCFString().get();
```suggestion
    auto *pathString = static_cast<NSString *>(path);
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +std::span<const uint8_t> WebExtension::resourceDataForPath(String path, RefPtr<API::Error> *outError, CacheResult cacheResult, SuppressNotFoundErrors suppressErrors)
This should return `Expected<std::span<const uint8_t>, Ref<API::Error>>` and drop the `outError` parameter.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        return std::span<const uint8_t>();
```suggestion
        return { };
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    else {
You can keep this as-is, it will cast `URL` to `NSURL *` in the assignment to `resourceURL`.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        return std::span<const uint8_t>();
```suggestion
        return { };
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        return std::span<const uint8_t>();
```suggestion
        return { };
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        return std::span<const uint8_t>();
```suggestion
        return { };
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    auto ns_data = retainPtr(resultData);
Please don't use `ns_*` names. `platformData` or `cocoaData` or anything else is better.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    RELEASE_LOG_ERROR(Extensions, "Error recorded: %{public}@", privacyPreservingDescription(::WebKit::wrapper(error)));
```suggestion
    RELEASE_LOG_ERROR(Extensions, "Error recorded: %{public}@", privacyPreservingDescription(wrapper(error)));
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    NSData *imageData = ::WebKit::wrapper(API::Data::create(resourceDataForPath(imagePath, outError, CacheResult::Yes))).get();
```suggestion
    auto *imageData = wrapper(API::Data::create(resourceDataForPath(imagePath, outError, CacheResult::Yes))).get();
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +RefPtr<WebCore::Icon> WebExtension::imageForPath(String imagePath, RefPtr<API::Error> *outError, WebCore::FloatSize sizeForResizing)
Should return `Expected<Ref<WebCore::Icon>, Ref<API::Error>>` and drop the `ourError` param.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +RefPtr<WebCore::Icon> WebExtension::bestImageInIconsDictionary(JSON::Value& value, WebCore::FloatSize idealSize, const Function<void(RefPtr<API::Error> *)>& reportError)
Should pass a `Ref<API::Error>&&` to the lambda instead, since it is only called when an error occurs.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +RefPtr<WebCore::Icon> WebExtension::bestImageForIconVariants(RefPtr<JSON::Value> value, WebCore::FloatSize idealSize, const Function<void(RefPtr<API::Error> *)>& reportError)
Should pass a Ref<API::Error>&& to the lambda instead, since it is only called when an error occurs.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        return nullptr;
This should be `asArray()` and `length()`.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +            [lightImage->image().get() drawInRect:rect];
No need for `get()` when it is calling a method.
```suggestion
            [darkImage->image() drawInRect:rect];
        else
            [lightImage->image() drawInRect:rect];
```

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +    return WebCore::Icon::create([NSImage imageWithSize:imageSize flipped:NO drawingHandler:^BOOL(NSRect rect) {
This block needs to be using `makeBlockPtr` to properly capture the `lightImage` and `darkImage`. They will not capture correctly otherwise.

2024-09-11 18:05 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionCocoa.mm
> +        auto result = bestImageForIconVariants(iconDictionary, idealSize, [&](auto error) {
```suggestion
        auto result = bestImageForIconVariants(iconDictionary, idealSize, [&](auto&& error) {
```

2024-09-11 19:17 UTC, ItsJamie9494 commented on Source/WebKit/Shared/Extensions/WebExtensionUtilities.cpp
> +        if (!value)
yes, this is checking to see if the JSON::Value type is JSON::Value::Type::Null with operator!.

2024-09-11 20:04 UTC, ItsJamie9494 commented
> I only made it about halfway through before stopping after many suggestions. I think it is going to be easier to do this more piecemeal — moving some functions over to C++ at a time so it is easier to review and land without breaking / regressing extensions for Cocoa platforms.

for this PR, do we want to try and keep it or split it into smaller PRs? I'm perfectly fine with opening smaller PRs on some of the individual changes if that's easier for you to review.

2024-09-11 22:31 UTC, xeenon commented
> > I only made it about halfway through before stopping after many suggestions. I think it is going to be easier to do this more piecemeal — moving some functions over to C++ at a time so it is easier to review and land without breaking / regressing extensions for Cocoa platforms.
> 
> for this PR, do we want to try and keep it or split it into smaller PRs? I'm perfectly fine with opening smaller PRs on some of the individual changes if that's easier for you to review.

Yeah I think smaller PRs to move some functions at a time and closing this PR would be best.

2024-09-12 15:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8883ca813a36e201cb4a53727f7747171cc3379d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33446

2024-09-12 15:11 UTC, ItsJamie9494 commented
> Yeah I think smaller PRs to move some functions at a time and closing this PR would be best.

I spent a bit of time last night trying to figure out if it's possible to split this PR up. Unfortunately, from what I can tell, it would be very difficult to do. m_manifest is an NSDictionary in the main branch, and if I don't change that from an NSDictionary, there's not much to port. Changing the NSDictionary to something non-Cocoa would result in more or less the same PR, as it would require changing almost all of the WebExtension{Cocoa} files to use the non-Cocoa APIs.

2024-09-12 16:01 UTC, xeenon commented
> > Yeah I think smaller PRs to move some functions at a time and closing this PR would be best.
> 
> I spent a bit of time last night trying to figure out if it's possible to split this PR up. Unfortunately, from what I can tell, it would be very difficult to do. m_manifest is an NSDictionary in the main branch, and if I don't change that from an NSDictionary, there's not much to port. Changing the NSDictionary to something non-Cocoa would result in more or less the same PR, as it would require changing almost all of the WebExtension{Cocoa} files to use the non-Cocoa APIs.

Can it be done in a way where the manifest is added as an JSON object tree, while also having a parallel dictionary copy for Cocoa in the meantime? That way all dictionary use does not need converted at once. Then migrate categories of the parsing over to the JSON objects in smaller batches.

As-is this PR is unreviewable. Even if the build passed, I would still have concerns on subtle breakage that isn't covered by API tests.

2024-09-12 16:06 UTC, xeenon commented on Source/WebKit/UIProcess/Extensions/Cocoa/WebExtensionActionCocoa.mm
> +    if (auto *defaultLabel = static_cast<NSString *>(extensionContext()->extension().displayActionLabel().createCFString().get(); defaultLabel.length || fallback == FallbackWhenEmpty::No))
This is likely one source of build issues.
```suggestion
    if (auto *defaultLabel = static_cast<NSString *>(extensionContext()->extension().displayActionLabel()); defaultLabel.length || fallback == FallbackWhenEmpty::No)
```

2024-09-12 16:30 UTC, ItsJamie9494 commented
We absolutely could do that, I just wasn't sure if that was a viable option initially. If you're ok with having the two parallel dictionaries, I can add that and do this in pieces.

On Thu, 12 Sep 2024, at 09:02, Timothy Hatcher wrote:
> 
> 
>>> Yeah I think smaller PRs to move some functions at a time and closing this PR would be best.
>>> 
>> I spent a bit of time last night trying to figure out if it's possible to split this PR up. Unfortunately, from what I can tell, it would be very difficult to do. m_manifest is an NSDictionary in the main branch, and if I don't change that from an NSDictionary, there's not much to port. Changing the NSDictionary to something non-Cocoa would result in more or less the same PR, as it would require changing almost all of the WebExtension{Cocoa} files to use the non-Cocoa APIs.
>> 
> Can it be done in a way where the manifest is added as an JSON object tree, while also having a parallel dictionary copy for Cocoa in the meantime? That way all dictionary use does not need converted at once. Then migrate categories of the parsing over to the JSON objects in smaller batches.
> 
> As-is this PR is unreviewable. Even if the build passed, I would still have concerns on subtle breakage that isn't covered by API tests.
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/WebKit/WebKit/pull/33446#issuecomment-2346687422>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFJ3XAVCHOGCWFSHIZK574TZWG3ITAVCNFSM6AAAAABOAGQFXWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBWGY4DONBSGI>.
> You are receiving this because you were assigned.Message ID: ***@***.***>
>

2024-09-12 19:14 UTC, closed without merging