[WPE] Upgrade our custom run-benchmark plans to use MotionMark 1.3.1
WebKit/WebKit pull request #33970
Opened 2024-09-20 08:54 UTC by nikolaszimmermann

#### 44e56c7b4db5cb6cf8cfe6888c931f85719203ae
<pre>
[WPE] Upgrade our custom run-benchmark plans to use MotionMark 1.3.1
<a href="https://bugs.webkit.org/show_bug.cgi?id=280051">https://bugs.webkit.org/show_bug.cgi?id=280051</a>

Reviewed by NOBODY (OOPS!).

Switch our custom run-benchmark plans to use MotionMark 1.3.1.
Unlike the Apple ports, we want to keep the name &apos;motionmark-1.3&apos; and
not add a .1 prefix, since that requires a reconfiguration of the bots.
We only want to upgrade the underlying plans to use MotionMark 1.3.1,
instead of 1.3. This has the main benefit that we can run individual
subtests, and get the right &apos;canvas size&apos;, which is one of the 1.3.1
fixes.

* Tools/Scripts/webkitpy/benchmark_runner/data/patches/extra/MotionMark1.3-15FPS.patch:
* Tools/Scripts/webkitpy/benchmark_runner/data/patches/extra/MotionMark1.3-60FPS.patch:
* Tools/Scripts/webkitpy/benchmark_runner/data/plans/motionmark1.3-15fps.plan:
* Tools/Scripts/webkitpy/benchmark_runner/data/plans/motionmark1.3-60fps.plan:
</pre>

2024-09-20 08:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/44e56c7b4db5cb6cf8cfe6888c931f85719203ae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33970

2024-09-20 09:34 UTC, carlosgcampos approved these changes

2024-09-23 12:57 UTC, clopez requested changes
Change looks ok, but we need to also rename the files to be consistent

So file `motionmark1.3-60fps.plan` should be renamed as `motionmark1.3.1-60fps.plan` and same for `-15fps` version

And I would also rename the patch files to contain the `1.3.1` string on it.

And on the runner we later have to modify the name of the plan from `motionmark-1.3-60fps` to `motionmark-1.3.1-60fps`  and same for `-15fps` version

This is a new version of the benchmark so it should be reflected as a change on the plan name

If we want to keep the old version around (1.3) instead of renaming the files we can add new ones. But i don't see a need to keep the old version so we can just rename them.

By the way, we also should change the plan name of the default motionmark that we pass to the runner, now it should be `motionmark-1.3.1` instead of `motionmark-1.3`

2024-09-23 13:45 UTC, nikolaszimmermann commented
I think we should stop the work on this for now, and look into just halving the FPS (30 FPS) by somehow moving into low-power mode, to fix the rAF() cadence to match the FPS we set, and make the score computation reliable.

2024-09-23 21:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7a897aa6b0adb59ebc1d62c737c445e41942c63a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33970

2024-09-23 22:16 UTC, smfr approved these changes

2024-09-24 07:53 UTC, nikolaszimmermann commented
Will correct the outdated commit message, then land.

2024-09-24 07:54 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/01dbef192a33e3551df76326d7a61081dcbb915f)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/68593 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/47985 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/70710 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/55781 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/19554 "Build is in progress. Recent messages:") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/71660 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/55781 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitpy](https://ews-build.webkit.org/#/builders/6/builds/68104 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/55781 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/55781 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-1-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/61/builds/19554 "Build is in progress. Recent messages:") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-1-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/21252 "Build is in progress. Recent messages:Running configuration") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/43786 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/44860 "Build is in progress. Recent messages:Running configuration") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/46054 "Build is in progress. Recent messages:Running configuration") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/44602 "Build is in progress. Recent messages:Running configuration") | | | </details>

2024-09-24 08:20 UTC, webkit-commit-queue commented
Committed 284147@main (de6e87fb4c3c): <https://commits.webkit.org/284147@main>

Reviewed commits have been landed. Closing PR #33970 and removing active labels.

2024-09-24 08:20 UTC, merged