Use adoptOSObject, not adoptNS, to handle dispatch queues
WebKit/WebKit pull request #33994
Opened 2024-09-20 20:11 UTC by RSilicon

<pre>Use adoptOSObject, not adoptNS, to handle dispatch queues
https://bugs.webkit.org/show_bug.cgi?id=280082

Reviewed by NOBODY (OOPS!).

Otherwise it will call the wrong release.

* Source/WebKit/UIProcess/ios/WKWebGeolocationPolicyDeciderIOS.mm:
  (-[WKWebGeolocationPolicyDecider init]): OSObjectPtr.
* Source/WebKitLegacy/mac/WebView/WebPreferences.mm:
  (WebPreferencesPrivate::WebPreferencesPrivate): Ditto.
</pre>

2024-09-20 20:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2c9e3451ba02b9e00e0cc53b286b09ab643c4ed9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33994

2024-09-20 20:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/562cafbf451cd537d5ec6146f031082033903e24. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33994

2024-09-20 20:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/93ce7bcfbdffaf9788f949959b8096d531e84bf5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33994

2024-09-20 22:57 UTC, bnham approved these changes
LGTM. Please fix the import order issue before landing.

2024-09-21 01:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3cf06ad228e63e44d6e0ea3b34d3815f05289d63. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33994

2024-09-21 01:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e050ab78cff00f0f9805bac0418614bfeada5160. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/33994

2024-09-21 17:25 UTC, RSilicon commented
> LGTM. Please fix the import order issue before landing.

Fixed!

2024-09-21 22:12 UTC, RSilicon commented
@bnham Can we please merge this?

2024-09-28 18:34 UTC, bnham commented
I added this to the merge queue.

> Otherwise it will call the wrong release.

OSObjects are Objective-C objects, so there is no "wrong release". If you send it a `-release` message to an OSObject in Objective-C, it's equivalent to calling `os_release` on the underlying object.

2024-09-28 18:43 UTC, bnham requested changes
This change is not necessary. Dispatch queues are OSObjects, and OSObjects are Objective-C objects. You can send -retain and -release to OSObjects like you can to any other Objective-C object. You do not need to use os_retain/os_release (or dispatch_retain/dispatch_release). In fact if you look at the implementation if dispatch_retain/dispatch_release you can see that in many cases it literally just calls -retain/-release.

2024-09-30 17:26 UTC, AreaZR commented
> This change is not necessary. Dispatch queues are OSObjects, and OSObjects are Objective-C objects. You can send -retain and -release to OSObjects like you can to any other Objective-C object. You do not need to use os_retain/os_release (or dispatch_retain/dispatch_release). In fact if you look at the implementation if dispatch_retain/dispatch_release you can see that in many cases it literally just calls -retain/-release.

"in many cases" And there appears to be an exception to that that involves checking the struct and that's why I wanted to err on the safe side.

2024-10-10 14:49 UTC, closed without merging