[TZone] Add TZone annotations to the platform classes for device motion, scrolling and orientation
WebKit/WebKit pull request #34263
Opened 2024-09-25 23:46 UTC by msaboff

#### 5aee3fcd987b1eb53cbf763ad4fbde2f9eb74647
<pre>
[TZone] Add TZone annotations to the platform classes for device motion, scrolling and orientation
<a href="https://bugs.webkit.org/show_bug.cgi?id=280367">https://bugs.webkit.org/show_bug.cgi?id=280367</a>
<a href="https://rdar.apple.com/136715489">rdar://136715489</a>

Reviewed by NOBODY (OOPS!).

Added TZone annotations for the device classes that inherit from DeviceClient.

* Source/WebCore/dom/DeviceMotionClient.h:
* Source/WebCore/dom/DeviceOrientationClient.h:
* Source/WebCore/platform/ios/DeviceMotionClientIOS.h:
* Source/WebCore/platform/ios/DeviceMotionClientIOS.mm:
* Source/WebCore/platform/ios/DeviceOrientationClientIOS.h:
* Source/WebCore/platform/ios/DeviceOrientationClientIOS.mm:
* Source/WebCore/platform/ios/MotionManagerClient.h:
* Source/WebCore/platform/ios/ScrollAnimatorIOS.h:
* Source/WebCore/platform/ios/ScrollAnimatorIOS.mm:
* Source/WebCore/platform/mac/ScrollAnimatorMac.h:
* Source/WebCore/platform/mac/ScrollAnimatorMac.mm:
* Source/WebCore/platform/mock/DeviceOrientationClientMock.cpp:
* Source/WebCore/platform/mock/DeviceOrientationClientMock.h:
</pre>

2024-09-25 23:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5aee3fcd987b1eb53cbf763ad4fbde2f9eb74647. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/34263

2024-09-26 00:07 UTC, Constellation approved these changes
rs=me

2024-09-26 16:34 UTC, MenloDorian requested changes
You've got a bug

2024-09-26 16:34 UTC, MenloDorian commented on Source/WebCore/dom/DeviceMotionClient.h
> +    WTF_MAKE_TZONE_ALLOCATED_INLINE(DeviceClient);
This should be `DeviceMotionClient`.

2024-09-27 02:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/60cfbd977800053739ee625db57fd339ef4008b7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/34263

2024-09-27 02:56 UTC, msaboff commented
> You've got a bug

Fixed.  Posted updated PR.

2024-09-27 05:53 UTC, MenloDorian approved these changes
r=me

2024-09-27 15:41 UTC, webkit-commit-queue commented
Committed 284363@main (5d40aae3f7f8): <https://commits.webkit.org/284363@main>

Reviewed commits have been landed. Closing PR #34263 and removing active labels.

2024-09-27 15:41 UTC, merged