[WPE][Debug] ASSERTION FAILED: canSafelyBeUsed()
WebKit/WebKit pull request #34451
Opened 2024-09-30 15:36 UTC by obyknovenius

#### bc6a7fd38b2a1241f02f6c25858f490153d87269
<pre>
[WPE][Debug] ASSERTION FAILED: canSafelyBeUsed()
<a href="https://bugs.webkit.org/show_bug.cgi?id=280617">https://bugs.webkit.org/show_bug.cgi?id=280617</a>

Reviewed by NOBODY (OOPS!).

`AcceleratedSurfaceLibWPE::initialize()` might be called from non-main thread.

* Source/WebKit/WebProcess/WebPage/libwpe/AcceleratedSurfaceLibWPE.cpp:
(WebKit::AcceleratedSurfaceLibWPE::initialize):
</pre>
https://github.com/WebKit/WebKit/commit/bc6a7fd38b2a1241f02f6c25858f490153d87269

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/69439 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/48839 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/22112 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/73522 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/20597 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/56640 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/20448 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/55227 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/13686 "Passed tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/72505 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/47/builds/44551 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/59951 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/35705 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/42/builds/41218 "Passed tests") | | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/18974 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/63159 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/63/builds/17726 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/75233 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/87/builds/13421 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/62/builds/16948 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/62895 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/86/builds/13460 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/60034 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/62801 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/88/builds/10820 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/119/builds/4435 "Passed tests") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/44/builds/44643 "Built successfully") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/46/builds/45717 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/43/builds/46912 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/45/builds/45458 "Built successfully") | | |

2024-09-30 15:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bc6a7fd38b2a1241f02f6c25858f490153d87269. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/34451

2024-09-30 15:54 UTC, mcatanzaro requested changes
I think this only hides the problem. An object that inherits from CanMakeWeakPtr just cannot be safely used on secondary threads; it's racy. You would need to switch MessageReceiver to use CanMakeThreadSafeWeakPtr instead, but that would be a performance hit for all of WebKit.

Normally I would advise copying only the data you need instead of using the WebPage object on multiple threads, but copying a file descriptor value from one thread to another without synchronization isn't safe either.

I think this is going to need some investigation to resolve properly.

2024-09-30 15:57 UTC, mcatanzaro commented
If AcceleratedSurface can be used on multiple threads at once, then we need a strategy to ensure `m_webPage` and `m_client` are only used on the correct thread.

2024-09-30 16:43 UTC, csaavedra commented
> I think this only hides the problem. An object that inherits from CanMakeWeakPtr just cannot be safely used on secondary threads; it's racy. You would need to switch MessageReceiver to use CanMakeThreadSafeWeakPtr instead, but that would be a performance hit for all of WebKit.

I'm not familiar with the specifics of this code or why it's called from different threads, but I think it's correct to hold a smart pointer in the stack for the page object, because you're calling a non-trivial method on it. (https://github.com/WebKit/WebKit/wiki/Safer-CPP-Guidelines#when-calling-a-non-trivial-member-function-on-an-object-hold-a-smart-pointer-to-the-object-on-the-stack) That's independent from what you comment, which might also be true and need further work.

2024-09-30 16:50 UTC, cdumez commented on Source/WebKit/WebProcess/WebPage/libwpe/AcceleratedSurfaceLibWPE.cpp
> +    m_backend = wpe_renderer_backend_egl_target_create(dupCloseOnExec(Ref { m_webPage.get() }->hostFileDescriptor()));
If this function is called on a background thread, then it is definitely not OK to ref the WebPage here. You're only supposed to ref the WebPage on the main thread.

2024-09-30 16:53 UTC, cdumez commented
> I think this only hides the problem. An object that inherits from CanMakeWeakPtr just cannot be safely used on secondary threads; it's racy. You would need to switch MessageReceiver to use CanMakeThreadSafeWeakPtr instead, but that would be a performance hit for all of WebKit.

`CanMakeThreadSafeWeakPtr` is not a thing. The refcount of `CanMakeWeakPtr` *is* thread safe by default. However, this only means you can pass WeakPtrs back and forth between threads. You're still only supposed to use (dereference) the WeakPtr on the thread where the object is constructed / destroyed (in this case the main thread of the WebPage object).

2024-09-30 16:55 UTC, cdumez commented
> s called from different threads, but I think it's correct to hold a smart pointer in the stack for the page object, because you're calling a non-trivial method on it. (https://github.com/WebKit/WebKit/wiki/Safer-CPP-Guidelines#when-calling-a-non-trivial-member-function-on-an-object-hold-a-smart-pointer-to-the-object-on-the-stack) That's independent from what you comment, which might also be true and need further work.

Calling `WeakPtr<WebPage>::get()` off the main thread is racy since the WebPage can get destroyed at any point on the main thread. As a result, constructing a RefPtr to the WebPage off the main thread from a WeakPtr is NOT safe. Not too mention that it could cause the WebPage to get destroyed on a background thread, which wouldn't be safe either.

2024-09-30 16:58 UTC, cdumez requested changes
r- since the PR is not safe.

I'm not super familiar with this code so I'm not sure what's the best way to fix it but here are a few ideas:
- Dispatch to the main thread to get the host file descriptor
- Store the host file descriptor some place where you can access it off the main thread (likely with locking)
- Call this function on the main thread.

2024-09-30 17:08 UTC, mcatanzaro commented
Unfortunately I think all of AcceleratedSurface will need to be audited. I'm not even sure what can or cannot get called off the main thread.

2024-10-02 08:44 UTC, obyknovenius commented
Closing in favor of https://github.com/WebKit/WebKit/pull/34497.

2024-10-02 08:44 UTC, closed without merging