Unreviewed, reverting 284276@main (290d009f7b35)
WebKit/WebKit pull request #34975
Opened 2024-10-10 13:35 UTC by magomez

#### 75162a5e191919a7a93cd271744642bc601e1fdf
<pre>
Unreviewed, reverting 284276@main (290d009f7b35)
<a href="https://bugs.webkit.org/show_bug.cgi?id=281222">https://bugs.webkit.org/show_bug.cgi?id=281222</a>

Broke the build in multiple platforms that can&apos;t provide the libspiel dependency

Reverted change:

    [WPE][GTK] Speech synthesis using libspiel
    <a href="https://bugs.webkit.org/show_bug.cgi?id=270742">https://bugs.webkit.org/show_bug.cgi?id=270742</a>
    284276@main (290d009f7b35)
</pre>

2024-10-10 13:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/47953ffdeb61519410ccb68e7796816a25738892. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/34975

2024-10-10 13:47 UTC, philn requested changes
As mentioned already, the flite support will be brought back using a cmake option. No need to revert this.

2024-10-10 13:54 UTC, magomez commented
> As mentioned already, the flite support will be brought back using a cmake option. No need to revert this.

@philn this has been broken for a while now, and has already consumed a lot of hours from people trying to workaround it one way or another. Please, let's just revert to end this problem and you can then, with more time, add a new version that supports both spiel and flite.

2024-10-10 14:00 UTC, philn approved these changes

2024-10-10 14:05 UTC, mcatanzaro commented
I don't understand how this can be taking hours of effort? It just requires a single build flag to disable?

In the absolute worst case where we're unable to change build flags for some extremely strange reason, we could simply define the feature to OFF rather than ON by default? That would surely solve things without needing to revert?

2024-10-11 06:12 UTC, webkit-commit-queue commented
No reviewer information in commit message, blocking PR #34975. Details: [Build #10915](https://ews-build.webkit.org/#/builders/22/builds/10915)

2024-10-11 06:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b180bc7facd7eac942c229e4d8b5de7d7a915d81. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/34975

2024-10-11 06:31 UTC, webkit-commit-queue commented
Committed 285005@main (41cdaf7d0058): <https://commits.webkit.org/285005@main>

Reviewed commits have been landed. Closing PR #34975 and removing active labels.

2024-10-11 06:31 UTC, merged