[Gardening][macOS wk2] imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-same-document-preventDefault-multiple-windows.html is a flaky failure.
WebKit/WebKit pull request #35505
Opened 2024-10-20 22:46 UTC by iidmsa

#### ecb2503490c9941dff43430b51fe4d4788bf7a68
<pre>
[Gardening][macOS wk2] imported/w3c/web-platform-tests/navigation-api/navigate-event/navigation-traverseTo-same-document-preventDefault-multiple-windows.html is a flaky failure.
<a href="https://bugs.webkit.org/show_bug.cgi?id=281840">https://bugs.webkit.org/show_bug.cgi?id=281840</a>
<a href="https://rdar.apple.com/problem/138286271">rdar://problem/138286271</a>

Unreviewed test gardening.

Setting test expectations.

* LayoutTests/platform/mac-wk2/TestExpectations:
</pre>

2024-10-20 22:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ecb2503490c9941dff43430b51fe4d4788bf7a68. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/35505

2024-10-21 15:42 UTC, bls1999 requested changes
This appears to only be occurring on Ventura. Is the expectation correct?

2024-10-21 15:56 UTC, iidmsa commented
> This appears to only be occurring on Ventura. Is the expectation correct?

I see. It says `Expected: TIMEOUT PASS`

2024-10-21 17:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/01eaa0e6089f8561a68510673dd85875e2fd6aba. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/35505

2024-10-21 17:10 UTC, iidmsa commented
> This appears to only be occurring on Ventura. Is the expectation correct?

Appropriate changes have been applied. Thank you for pointing that out.

2024-10-21 17:16 UTC, bls1999 approved these changes
LGTM!

2024-10-21 17:19 UTC, webkit-commit-queue commented
Test gardening commit 285514@main (b8dceccc0512): <https://commits.webkit.org/285514@main>

Reviewed commits have been landed. Closing PR #35505 and removing active labels.

2024-10-21 17:19 UTC, merged