[WebXR] Use minimum near clip plane distance from the system for clamping
WebKit/WebKit pull request #35933
Opened 2024-10-30 06:43 UTC by achan00

#### f1da3ec9143894ac14dac838147eb4f81f3e3c0d
<pre>
[WebXR] Use minimum near clip plane distance from the system for clamping
<a href="https://bugs.webkit.org/show_bug.cgi?id=282321">https://bugs.webkit.org/show_bug.cgi?id=282321</a>
<a href="https://rdar.apple.com/138811538">rdar://138811538</a>

Reviewed by NOBODY (OOPS!).

Instead of hardcoding the minimum near clip plane distance, allow the system
to pass that value via XRDeviceInfo. WebXRSession will get that value
from PlatformXR::Device::minimumNearClipPlane().

* Source/WebCore/Modules/webxr/WebXRSession.cpp:
(WebCore::WebXRSession::WebXRSession):
(WebCore::WebXRSession::applyPendingRenderState):
Set the PlatformXR::RequestData based on the depth range from m_activeRenderState
after the values are clamped.
* Source/WebCore/platform/xr/PlatformXR.h:
(PlatformXR::Device::minimumNearClipPlane const):
* Source/WebKit/Shared/XR/XRDeviceInfo.h:
* Source/WebKit/Shared/XR/XRDeviceProxy.cpp:
(WebKit::XRDeviceProxy::XRDeviceProxy):
* Source/WebKit/Shared/XR/XRDeviceProxy.h:
* Source/WebKit/Shared/XR/XRSystem.serialization.in:
</pre>

2024-10-30 06:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f1da3ec9143894ac14dac838147eb4f81f3e3c0d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/35933

2024-10-30 13:58 UTC, svillar requested changes
The spec mentions that "The values MUST be determined by the user agent and MUST be non-negative." so we should enforce that restriction instead of blindly trusting what's coming from the platform layer

2024-10-30 23:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f32da2dcf568ac8ceffe9cd580ac7f2f81505dab. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/35933

2024-10-30 23:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9e5de05329463c75463670ab4e5428964577ecf8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/35933

2024-10-31 03:26 UTC, mwyrzykowski approved these changes

2024-10-31 14:25 UTC, achan00 commented
> The spec mentions that "The values MUST be determined by the user agent and MUST be non-negative." so we should enforce that restriction instead of blindly trusting what's coming from the platform layer

Added the non-negative enforcement. Thanks for taking a look!

2024-10-31 15:17 UTC, webkit-commit-queue commented
Committed 285955@main (d0b1b549a5d4): <https://commits.webkit.org/285955@main>

Reviewed commits have been landed. Closing PR #35933 and removing active labels.

2024-10-31 15:17 UTC, merged

2024-11-06 08:50 UTC, svillar commented on Source/WebCore/Modules/webxr/WebXRSession.cpp
> +        m_minimumNearClipPlane = minimumNearClipPlaneFromPlatform;
A bit late, but the preferred idiom in WebKit I think would be

m_minimumNearClipPlane = std::max(0, device.minimumNearClipPlane());