Source/WebKit: Implement theme color retrieval API
WebKit/WebKit pull request #36049
Opened 2024-11-01 17:44 UTC by fredldotme

#### de7db90f10449c33a0374277d3f16fe8f7c382bd
<pre>
Source/WebKit: Implement theme color retrieval API

Implements a property &quot;theme-color&quot; and a getter function webkit_web_view_get_theme_color()
for retrieving the web view&apos;s page theme color, with property changes for notification.
</pre>

2024-11-01 17:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/de7db90f10449c33a0374277d3f16fe8f7c382bd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-11-01 17:49 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/54038a62a85adbc030edb74e415481a62d26b9e9)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/74504 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/53933 "Build is in progress. Recent messages:OS: Sonoma (14.5), Xcode: 15.4") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/78903 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/25742 "Build is in progress. Recent messages:Printed configuration") 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/63066 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/1718 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/78903 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 win-tests](https://ews-build.webkit.org/#/builders/59/builds/25742 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/77571 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/63066 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/78903 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/63066 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/24075 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/63066 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/80412 "Build is in progress. Recent messages:Printed configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/1821 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/1718 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/80412 "Build is in progress. Recent messages:Printed configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/1969 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/80412 "Build is in progress. Recent messages:Printed configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/27315 "Build is in progress. Recent messages:Running configuration") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/1786 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/4573 "Build is in progress. Recent messages:") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/1814 "Build is in progress. Recent messages:") | | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2024-11-01 18:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/88691745345d3445119042b47c81219b626d6f3e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-11-01 18:45 UTC, aperezdc requested changes
@fredldotme Thanks for sending this, patch looks quite good already. 

I left an important comment about memory allocation&mdash;kind of expected because we have an “interesting” mixture of memory methods (system allocator via GLib, WebKit's bmalloc/fastMalloc/libpas which sometimes might fallback to the system allocator, and the C++ standard `new`/`delete`), but you managed to have the rest of things spot-on 👍🏼 

Could you please go through the comments and update the patch? I appreciate you taking the time.

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +    PROP_THEME_COLOR,
You may remove the empty line right above this one.

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +        WebKitColor* color = new WebKitColor;
We need to be consistent in the memory allocator being used.

Looking at `Source/WebKit/UIProcess/API/wpe/WebKitColor.cpp` it turns out that the `webkit_color_free()` function calls `WTF::fastFree()`, so this will allocate using the allocator used by the `new` operator, which usually won't be the same used by `WTF::fastFree` when the `GValue` that takes ownership of the boxed `WebKitColor` value destroys it.

So what we want here is `WTF::fastMalloc()`. It would be nicer to have a `webkit_color_new()` helper function, but I think we rather leave that for a separate patch, instead let's do this:

```suggestion
        auto* color = static_cast<WebKitColor*>(fastMalloc(sizeof(WebKitColor)));
```

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +     * Since: TBD
The next major release series will be 2.48, therefore:

```suggestion
     * Since: 2.48
```

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> + * Gets the theme color that is specified by the content it the @web_view.
Is the “it” a typo? I suppose you wanted to use “in”:

```suggestion
 * Gets the theme color that is specified by the content in the @web_view.
```

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +    flushPendingThemeColorChange();
Is this not needed for the GTK port?

2024-11-01 18:45 UTC, aperezdc commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> + * Since: tbd
Same as above:

```suggestion
 * Since: 2.48
```

2024-11-01 18:50 UTC, aperezdc commented
Also, there's this bit [reported](https://ews-build.webkit.org/#/builders/5/builds/78912) by the EWS:

```
/app/webkit/Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp: In function ‘void webkitWebViewGetProperty(GObject*, guint, GValue*, GParamSpec*)’:
/app/webkit/Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:1182:5: error: jump to case label
 1182 |     default:
      |     ^~~~~~~
/app/webkit/Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:1178:22: note:   crosses initialization of ‘WebKitColor* color’
 1178 |         WebKitColor* color = new WebKitColor;
      |                      ^~~~~
```

An option for this is adding braces around this `case`:

```cpp
case PROP_COLOR_THEME: {  // <-- This brace
    auto* color = static_cast<WebKitColor*>(fastMalloc(sizeof(WebKitColor)));
    // ...
    break;
}  // <-- and this one.
```

2024-11-01 18:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/463644d81078f7732709b8f4f0a9932d43731299. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-11-01 18:59 UTC, fredldotme commented
Addressed the review comments so far. One particular thing I want to point out is that I've enabled the color change flush on GTK as well, but I haven't tested it there, so changing the commit title might be up for review team or me having to adapt the message locally.

2024-11-01 19:16 UTC, aperezdc requested changes
@fredldotme Just one more small change request, I went to check how other ports do things and didn't notice one thing before.

Could you also add the `[GTK]` tag in the commit log summary line, please?

My apologies for making you go through another round of changes 🙏🏼

2024-11-01 19:16 UTC, aperezdc commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +    flushPendingThemeColorChange();
I went to double check and this should be moved into `DrawingAreaCoordinatedGraphics::display()`, next to the call to `flushPendingEditorStateUpdate()`. All the other ports do such updates in their DrawingArea implementation. Once moved, then the call does not need to be guarded with `PLATFORM(GTK) || PLATFORM(WPE)`.

2024-11-01 19:30 UTC, mcatanzaro commented
WebKitColor is a WPE-only type. The GTK version would need to use GdkRGBA instead. You can look at webkit_web_view_set_background_color() and webkit_web_view_get_background_color() for examples.

2024-11-02 07:36 UTC, aperezdc commented
One more thing: currently the `WebPage::flushPendingThemeColorChange()` function is guarded with `PLATFORM(MAC)` so you will need to change it to be `PLATFORM(MAC) || PLATFORM(WPE) || PLATFORM(GTK)`.

2024-12-04 15:05 UTC, spacecat commented
Hi, just wondering if this PR is about `theme-color` that it currently not working in my Next.js 14 app in Safari Version 18.1.1 (20619.2.8.11.12)?

It says here it should work:

https://caniuse.com/?search=theme-color
https://css-tricks.com/meta-theme-color-and-trickery/

I looked here as well: https://developer.apple.com/documentation/safari-technology-preview-release-notes
but could not find anything on "theme-color"

2024-12-04 16:09 UTC, mcatanzaro commented
This pull request is for WebKitGTK. It won't affect Safari at all.

2024-12-04 17:58 UTC, fredldotme commented
I'm also open for suggestions, you should have commit access to this branch already if I'm not mistaken.

2024-12-05 12:52 UTC, spacecat commented
> This pull request is for WebKitGTK. It won't affect Safari at all.

Where do I report issues for Safari then? Can you please share a link?

2024-12-05 16:03 UTC, mcatanzaro commented
Sure: https://webkit.org/reporting-bugs/

2024-12-20 03:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/54907ea90d273eb4a701330b881f8cd9ae1c00ae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-20 03:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/585e4d7cdda84ee5dd88580012b41c62d793a251. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-20 03:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3613a7a8e0afe6248ab57b80a4b9ab9733c816a7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-20 12:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e1f4a0d748f84c37f2e0fc759ed28acee999259f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-22 09:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/01fc345ace45efc16ded54afbc77b3500410f84f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-22 10:58 UTC, fredldotme commented
@aperezdc This is ready now IMO.

Since this has additional files changed, and I presume the PR should match that, I am wondering how to get the latest commit message in the PR message if that matters.

2024-12-22 10:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5293defb13906b8dcd577b58d7fd7df73dbd6ad1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2024-12-22 11:27 UTC, fredldotme commented
As a matter of fact, wait a minute. I have figured something.

My recent changes to clean up problematic code ended up making the implementation half-way working. Need to add a fix still.

It's about setting the property to propagate a change event.

2025-01-04 05:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0455b07f66dd8a298e194673c7e2527dda9ab140. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-01-04 05:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0455b07f66dd8a298e194673c7e2527dda9ab140. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-01-04 14:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5b87380dace867489ee7f8b43e89cbe959c1332e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-01-04 14:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5b87380dace867489ee7f8b43e89cbe959c1332e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-22 21:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a2c37855e1d07f53a6568bffeebdd03299a63044. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-23 09:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4749ca1741b10d5afec205f545991cd3ba9b460d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-23 10:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fe8d5c9f1e915b143ffafe2173538787c8cc95eb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-23 10:26 UTC, fredldotme commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +    flushPendingThemeColorChange();
I've tried this and once moved it didn't flush the theme color state, the theme color stayed invalid. Only from here would it actually do the right thing.

2025-05-23 11:42 UTC, aperezdc requested changes
I think this is looking good, but I would like to request one last change, to handle the case in which WebKit cannot determine the page theme color, because that is an acceptable case.

@carlosgcampos @mcatanzaro Would you please take a look to rubber-stamp the patch, and have a second approval, as preferred for API additions?

2025-05-23 11:42 UTC, aperezdc commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +    g_return_if_fail(page.themeColor().isValid());
Checking the implementation of `Page::themeColor()` and `Document::themeColor()` I see that there are two cases in which the color may end up being invalid:

- There is no top-level `Document` (for example: may happen during loads, temporarily)
- The theme color cannot be determined (not declared with the corresponding `<meta>` element, no app-manifest, etc.)

These are cases that we should handle. The `Color` class has a comment telling that it can represent a *Special "invalid color" state, treated as transparent black but distinguishable*.

Taking the above into account, I think this function should return `gboolean` to indicate whether the color is valid. In case of getting an invalid color, fill the `WebKitColor`, with `red = green = blue = alpha = 0.0`.

2025-05-23 13:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5dd6e28e39424b84d05a38e4aa039520ef8a32a6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-23 18:57 UTC, aperezdc requested changes
@fredldotme Just one last little bit: you forgot to document what the returned boolean means.

2025-05-23 18:57 UTC, aperezdc commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> + *
We are missing here a `Returns:` annotation:

```suggestion
 *
 * Returns: Whether the currently loaded page defines a theme color.
 *
```

2025-05-24 04:57 UTC, fredldotme commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> + *
Done.

2025-05-24 09:57 UTC, aperezdc approved these changes
Thanks again for the update @fredldotme, approved!

@carlosgcampos Could you have a look and comment whether the API addition is okay for you as well?

2025-05-25 06:26 UTC, carlosgcampos requested changes
Thanks for the patch. I have a few minor comments and a question, but the most important thing is that this is new API, so a new API test is required.

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +        static_cast<GParamFlags>(WEBKIT_PARAM_READABLE));
```suggestion
        WEBKIT_PARAM_READABLE);
```

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +webkit_web_view_get_theme_color(WebKitWebView* webView, WebKitColor* color)
```suggestion
gboolean webkit_web_view_get_theme_color(WebKitWebView* webView, WebKitColor* color)
```

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +    g_return_val_if_fail(WEBKIT_IS_WEB_VIEW(webView), false);
color isn't nullable, so we should add a g_return_val_if_fail for the color too. However, I wonder if it should be nullable instead, if you just want to check whether the page defines a theme color.

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +        webkitColorFillFromWebCoreColor(tmpColor, color);
This should be documented. Why do we fill the color with transparent black? I would expect the color not to be filled at all, but if we want to do this we should say it in the documentation.

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +        return false;
```suggestion
        return FALSE;
```

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +    return true;
```suggestion
    return TRUE;
```

2025-05-25 06:26 UTC, carlosgcampos commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Why do we need this here? It's already called by the drawing area right after updateRedering().

2025-05-25 06:27 UTC, carlosgcampos commented
Please, also remove the [GTK] from the commit message, since this is WPE only in the end.

2025-05-25 10:05 UTC, fredldotme commented
> Please, also remove the [GTK] from the commit message, since this is WPE only in the end.

It's not in the commit message rather than the PR message. Removed it from there.

2025-05-25 10:06 UTC, fredldotme commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
I left the second place in for review, this one is the one that works, the one triggered from the drawing area doesn't. Should I remove it from the drawing area?

2025-05-25 10:09 UTC, fredldotme commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +    g_return_val_if_fail(WEBKIT_IS_WEB_VIEW(webView), false);
I suppose that was @aperezdc intention.

2025-05-25 10:10 UTC, fredldotme commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +        webkitColorFillFromWebCoreColor(tmpColor, color);
Did this per @aperezdc request. Added a note to the docs.

2025-05-25 10:43 UTC, fredldotme commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Left the intact one in there, removed the one from the drawing area. I suppose if this gets ported to GTK you might want to find a better spot to put the flush operation.

2025-05-25 20:58 UTC, aperezdc commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +        webkitColorFillFromWebCoreColor(tmpColor, color);
> This should be documented. Why do we fill the color with transparent black? I would expect the color not to be filled at all, but if we want to do this we should say it in the documentation.

Because when you get the property using i.e. `g_object_get()` there is no way of telling the caller “there was't a color defined”, so one needs to fill the returned color with something. WebCore's `Color` class uses transparent black in that case, which IMO it makes sense in this case: if one “sees“ a transparent color, that would not really make much sense for a theme color, so that's kind of a neutral value for an invalid color.

2025-05-26 05:45 UTC, carlosgcampos commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Then we need to understand why it doesn't work there, maybe we are missing other updateRendering callers.

2025-05-26 05:45 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp
> +        webkitColorFillFromWebCoreColor(tmpColor, color);
Makes sense, let's just document it then.

2025-05-27 19:22 UTC, mcatanzaro commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Also, unless you understand why this is not needed for macOS, the guard should be:

```
#if PLATFORM(MAC) || PLATFORM(WPE)
```

2025-05-27 19:26 UTC, mcatanzaro commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Well, I see the reason: macOS does this in `TiledCoreAnimationDrawingArea::updateRendering`. Ideally we would parallel that to reduce odds of platform-specific bugs, but I see you've already tried....

2025-05-28 05:11 UTC, carlosgcampos commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
The parallel in our case would be LayerTreeHost::flushLayers, where it was in a previous version of the patch.

2025-05-28 12:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4056e06d1236ab063a40c0d660e14af16639c657. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-28 12:10 UTC, fredldotme commented on Source/WebKit/WebProcess/WebPage/WebPage.cpp
> +
Clarification: Previously it was in `DrawingAreaCoordinatedGraphics.cpp`, but I've since moved the flush operation over to `LayerTreeHost::flushLayers`. Doesn't seem to be problematic.

2025-05-31 08:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5a59d6629b602d604a11690b5fb08d25fb10d560. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-05-31 14:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/998e4ed4fd1ab44f1b962df7eb714cca0d2f31d2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-02 04:01 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/70955fa417e0ff263bdbd532707b7e2cb427c9f6)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/105864 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/25615 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/16008 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/111061 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/56461 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/107905 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/26207 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/34118 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/80409 "Passed tests") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/108870 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/20612 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/95531 "Passed tests") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/60725 "Found 1 new API test failure: /WPE/TestWebKitWebView:/webkit/WebKitWebView/theme-color (failure)") | 
| | [⏳ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-WPT-WK2-Tests-EWS "Waiting to run tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/13629 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/55899 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/90009 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/13666 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/113911 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/33004 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/24334 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/89488 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/33368 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/91761 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89159 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34028 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/11835 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/28531 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/32929 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/38340 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/32675 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/36024 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/34273 "Built successfully") | | | </details>

2025-06-02 05:21 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/c2e85948d3561d66b5d9cd793255aa9f91401c6f)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/105866 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/25617 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/16010 "Built successfully") | [❌ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/111063 "Hash c2e85948 for PR 36049 does not build (failure)") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/56463 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/107907 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/26211 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/34120 "Built successfully") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/111063 "Hash c2e85948 for PR 36049 does not build (failure)") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/108872 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/20618 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/95534 "Passed tests") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/111063 "Hash c2e85948 for PR 36049 does not build (failure)") | 
| | [⏳ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-WPT-WK2-Tests-EWS "Waiting to run tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/13632 "Passed tests") | [❌ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/55901 "Hash c2e85948 for PR 36049 does not build (failure)") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/90014 "Passed tests") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/136/builds/13669 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/113913 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/33006 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/122/builds/24336 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/89491 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/33370 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/91764 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89162 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34031 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/11838 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/28536 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/32931 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/38342 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/32677 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/36026 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/34275 "Built successfully") | | | </details>

2025-06-02 06:16 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/e4cacadf74bb74ff2886c1fcbf8d221543ec9cf9)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/105867 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/25618 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/16011 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/111064 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/56464 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/107908 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/26362 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/34121 "Built successfully") | [❌ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/80414 "Found 2 new test failures: imported/w3c/web-platform-tests/html/semantics/forms/constraints/infinite_backtracking.html imported/w3c/web-platform-tests/service-workers/service-worker/redirected-response.https.html (failure)") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/108873 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/20790 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/95535 "Passed tests") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/60730 "Found 1 new API test failure: /WPE/TestWebKitWebView:/webkit/WebKitWebView/theme-color (failure)") | 
| | [💥 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/20409 "An unexpected error occured. Recent messages:Printed configuration") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/13634 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/55902 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/90173 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/13670 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/113914 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/33007 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/24338 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/89492 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/33371 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/91765 "Passed tests") | [❌ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89163 "Found 101 new API test failures: /TestWebKit:WebKit.PageLoadDidChangeLocationWithinPage, /TestWebKit:WebKit.AboutBlankLoad, /TestWebKit:WebKit.PreventEmptyUserAgent, /TestWebKit:WebKit.PrivateBrowsingPushStateNoHistoryCallback, /WebKitGTK/TestInputMethodContext:/webkit/WebKitInputMethodContext/content-type, /WebKitGTK/TestUIClient:/webkit/WebKitWebView/pointer-lock-permission-request, /TestWebKit:WebKit.HitTestResultNodeHandle, /TestWebKit:WebKit2TextFieldBeginAndEditEditingTest.TextFieldDidBeginShouldNotBeDispatchedForAlreadyFocusedField, /TestWebKit:WebKit.Find, /WebKitGTK/TestWebProcessExtensions:/webkit/WebKitWebProcessExtension/dom-input-element-is-user-edited ... (failure)") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34032 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/11839 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/28537 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/32932 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/38343 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/32678 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/36027 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/34276 "Built successfully") | | | </details>

2025-06-02 07:47 UTC, carlosgcampos requested changes

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +    webkit_web_view_get_theme_color(test->m_webView.get(), &rgba);
```suggestion
    g_assert_false(webkit_web_view_get_theme_color(test->m_webView.get(), &rgba));
```

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +    test->wait(1);
I don't think we should wait 1 second if it can be avoided, could we just monitor the property by connecting to the notify signal and start the run loop until the signal is emitted?

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +    test->showInWindow();
Why do we need this at this point?

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +
```suggestion
```

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +    webkit_web_view_get_theme_color(test->m_webView.get(), &rgba);
```suggestion
    g_assert_true(webkit_web_view_get_theme_color(test->m_webView.get(), &rgba));
```

2025-06-02 07:47 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +}
We could also check that the theme color changes again if we load a different page with a different theme color and another with no theme color

2025-06-07 09:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c2d8a17c9b9c415d01f188cc2e795197fd451343. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-07 09:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3a25f37e44eb68e4a5c4cb0c309c79950db78055. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-07 10:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/25316056af5bbb1a206d53fcbade857612235d41. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-07 15:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5f0570f2bf132f61bf1ea070790a1cdd658e416. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-09 07:28 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/c34cf491df3c5ba62347e2017690a382115fb75e)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/106861 "2 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/26596 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/16993 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/112067 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/57443 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/108882 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/27264 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/35097 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/81148 "Passed tests") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/109847 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/21647 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/96417 "Passed tests") | [❌ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/61489 "Found 1 new API test failure: /WPE/TestWebKitWebView:/webkit/WebKitWebView/theme-color (failure)") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/21091 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/14526 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/56895 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/90988 "Passed tests") | [❌ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/14553 "Found 2 new test failures: imported/w3c/web-platform-tests/css/css-pseudo/highlight-custom-properties-dynamic-001.html imported/w3c/web-platform-tests/css/css-view-transitions/rotated-cat-off-top-edge.html (failure)") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/115045 "Build is being retried. Recent messages:Printed configuration; Running apply-patch; Checked out pull request; Failed to compile WebKit; Failed to compile WebKit; Unable to build WebKit without PR, retrying build (failure)") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/33982 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/25074 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/90208 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/34348 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/92648 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89918 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34849 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/12663 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/29677 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/33906 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/39336 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/33653 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/37006 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/35262 "Built successfully") | | | </details>

2025-06-09 11:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a54f9a73abb3e814b7463a61fc516eec23e2f74c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-09 11:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a54f9a73abb3e814b7463a61fc516eec23e2f74c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-09 11:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/34beefc4214d6c4eca76d38bddf22ceebf8249ad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-09 11:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/34beefc4214d6c4eca76d38bddf22ceebf8249ad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36049

2025-06-09 11:47 UTC, fredldotme commented
I'd be glad if somebody could give some insight into the styling issue. I can't see a relation between error output and actual file:line.

2025-06-09 11:59 UTC, carlosgcampos commented on Tools/TestWebKitAPI/Tests/WebKitGLib/TestWebKitWebView.cpp
> +    WebKitColor targetColor {0.0, 0.0, 0.0, 0.0};
```suggestion
    WebKitColor targetColor { 0.0, 0.0, 0.0, 0.0 };
```

2025-06-09 14:17 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/860876abeb1164cbb1ed1c550e057db274ccafb0)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/106914 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/26625 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/17022 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/112123 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/57477 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/108911 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/27293 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/35127 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/81190 "Passed tests") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/109876 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/21671 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/96441 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/61531 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/21114 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/14550 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/56924 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/91013 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/14577 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/115110 "Build is being retried. Recent messages:Printed configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request; Failed to compile WebKit; Failed to compile WebKit; Unable to build WebKit without PR, retrying build (failure)") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/34011 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/25098 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/90243 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/34378 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/92672 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89954 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34873 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/12687 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/29721 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/33935 "Built successfully") | [  ~~🛠 mac-safer-cpp~~](https://ews-build.webkit.org/#/builders/120/builds/39387 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/33683 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/37035 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/35312 "Built successfully") | | | </details>

2025-06-09 15:24 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/e695a2ca6befb0b5d80874e872e9266139c73271)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/106928 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/26635 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/17032 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/112135 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/57488 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/108921 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/27307 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/35137 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/81199 "Passed tests") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/109886 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/21682 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/96450 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/61540 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/21125 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/14559 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/56934 "Built successfully") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/91029 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/14586 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/115136 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/34021 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/25105 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/90252 "Passed tests") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/34389 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/92680 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/89963 "Passed tests") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/34882 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/12696 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/29735 "The change is no longer eligible for processing.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/33945 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/39400 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/33693 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/37045 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/35325 "Built successfully") | | | </details>

2025-06-10 05:34 UTC, carlosgcampos approved these changes

2025-06-10 05:34 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +     * WebKitWebView::theme-color:
```suggestion
     * WebKitWebView:theme-color:
```

2025-06-10 05:34 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
> +     * WebKitWebView::theme-color:
I'm sorry I didn't notice this before `::` is used for signals

2025-06-10 11:39 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/da8019d4a6faee74ff52ff9bfbff1fb3d6a48492)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/107125 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/26822 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/17221 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/112335 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/57672 "Built successfully") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/109105 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/27493 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/35325 "Built successfully") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/81325 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/110070 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/132/builds/21820 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/96593 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/61687 "Passed tests") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/133/builds/21243 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/14721 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/57119 "Built successfully") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/91171 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/14742 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/115428 "Built successfully") | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/34205 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/122/builds/25206 "Passed tests") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/90370 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/34579 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/92845 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/21/builds/90103 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/126/builds/35033 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/12809 "Passed tests") | [  ~~🛠 playstation~~](https://ews-build.webkit.org/#/builders/134/builds/29934 "The change is no longer eligible for processing.") | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/17323 "Built successfully and passed tests") | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/34130 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/39594 "Built successfully") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/33877 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/37229 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/35523 "Built successfully") | | | </details>

2025-06-10 12:28 UTC, webkit-commit-queue commented
Committed 296035@main (2246a2aa28d5): <https://commits.webkit.org/296035@main>

Reviewed commits have been landed. Closing PR #36049 and removing active labels.

2025-06-10 12:29 UTC, merged