ARMv7: handle wide Air::Arg offsets
WebKit/WebKit pull request #36092
Opened 2024-11-02 14:54 UTC by aoikonomopoulos

#### ed35c35d4579549d7f86dbf788ebbf5c8cbb5aa1
<pre>
ARMv7: handle wide Air::Arg offsets
<a href="https://bugs.webkit.org/show_bug.cgi?id=282490">https://bugs.webkit.org/show_bug.cgi?id=282490</a>

Reviewed by NOBODY (OOPS!).

Functions with massive numbers of arguments may generate moves using
unrepresentable offsets on ARMv7.

Lower those offsets when generating code from Air, so that we can use
the extendedOffsetAddrRegister(), which we reserve for use in this file,
so that we can lower wide frame pointer-based offsets (see
<a href="https://commits.webkit.org/258279@main).">https://commits.webkit.org/258279@main).</a>

* Source/JavaScriptCore/b3/air/AirAllocateRegistersAndStackAndGenerateCode.cpp:
(JSC::B3::Air::lowerInstOffsets):
(JSC::B3::Air::GenerateAndAllocateRegisters::generate):
* Source/JavaScriptCore/b3/testb3_failingArmV7Tests.inc:
</pre>

2024-11-02 14:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ed35c35d4579549d7f86dbf788ebbf5c8cbb5aa1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36092

2024-11-04 12:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c7295f3f72b73c253a1e5a40c984026b5d6e59fb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36092

2024-11-04 15:20 UTC, justinmichaud reviewed
I think this should be a separate pass, so that we don’t clutter up the register allocators. Thoughts?

2024-11-05 16:18 UTC, Constellation requested changes
Why is the change necessary for 64bit?

2024-11-06 10:36 UTC, aoikonomopoulos commented
> I think this should be a separate pass, so that we don’t clutter up the register allocators. Thoughts?

The issue with that is that there's nothing to lower a `CallArg` with a  wide offset to, until after registers get allocated, and that's pretty late (shortly before the call to `inst.generate()` in `AirAllocateRegistersAndStackAndGenerateCode.cpp`).

2024-12-18 10:12 UTC, aoikonomopoulos commented
Closing in favor of https://github.com/WebKit/WebKit/pull/38128.

2024-12-18 10:12 UTC, closed without merging