[Gardening][iOS macOS] `transitions/created-while-suspended.html` passes on iOS and macOS release platforms
WebKit/WebKit pull request #36238
Opened 2024-11-06 01:21 UTC by iidmsa

#### 9aceea080a07bd0eb8ed30194d67d85199f39762
<pre>
[Gardening][iOS macOS] `transitions/created-while-suspended.html` passes on iOS and macOS release platforms
<a href="https://bugs.webkit.org/show_bug.cgi?id=184608">https://bugs.webkit.org/show_bug.cgi?id=184608</a>

Unreviewed test gardening.

Updating test expectations.

* LayoutTests/platform/ios/TestExpectations:
* LayoutTests/platform/mac/TestExpectations:
</pre>

2024-11-06 01:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9aceea080a07bd0eb8ed30194d67d85199f39762. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36238

2024-11-07 17:19 UTC, bls1999 requested changes
@iidmsa and I spoke on Slack -- I verified this is passing on iOS debug and they're going to verify it's passing on macOS debug.

2024-11-07 18:22 UTC, iidmsa commented
> @iidmsa and I spoke on Slack -- I verified this is passing on iOS debug and they're going to verify it's passing on macOS debug.

I confirm the test is passing on macOS debug.

2024-11-07 18:23 UTC, bls1999 approved these changes

2024-11-07 18:25 UTC, webkit-commit-queue commented
Test gardening commit 286290@main (5b38ba99c55b): <https://commits.webkit.org/286290@main>

Reviewed commits have been landed. Closing PR #36238 and removing active labels.

2024-11-07 18:25 UTC, merged