[CMake] Integrate vcpkg into Windows build
WebKit/WebKit pull request #36366
Opened 2024-11-08 03:10 UTC by donny-dont

#### 596b3428a41fcb7351268904c4d408afe62a4be0
<pre>
[CMake] Integrate vcpkg into Windows build
<a href="https://bugs.webkit.org/show_bug.cgi?id=282800">https://bugs.webkit.org/show_bug.cgi?id=282800</a>

Reviewed by NOBODY (OOPS!).

TBD

* Source/cmake/OptionsWin.cmake:
* vcpkg-configuration.json: Added.
* vcpkg.json: Added.
</pre>

2024-11-08 03:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/596b3428a41fcb7351268904c4d408afe62a4be0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-08 03:10 UTC, donny-dont commented
Needs to be rebased after https://github.com/WebKit/WebKit/pull/36365 lands

2024-11-08 03:11 UTC, donny-dont commented
To run create a directory to do the build in and invoke cmake directly replacing the path to your webkit checkout

```
cmake -DPORT="Win" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake" -G Ninja -DDEVELOPER_MODE=ON -DENABLE_EXPERIMENTAL_FEATURES=ON <path-to-WebKit-checkout>
```

2024-11-08 18:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/efba267c2882f32521f7f054cde06ed651a994d5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-09 01:12 UTC, donny-dont commented
Ok so this works locally but will require some changes to the bots to support it.

2024-11-09 01:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/085b077d3d317c91e9859628af9addfb6add9ee9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-11 00:43 UTC, fujii requested changes
I don't like this approach.
* Buildbot workers have to compile all required libraries. But, we have no enough VM resources.
* It increases the built artifact size if all compiled DLL are copies to `bin` directory.
I think current WebKitRequirements64.zip approach is better.

2024-11-11 04:48 UTC, fujii commented
I tried `build-webkit --debug` on my PC, and got an error.

~~~
[3632/6915] Linking CXX shared library bin\WebCore.dll
FAILED: bin/WebCore.dll lib/WebCore.lib
C:\Windows\system32\cmd.exe /C "cd . && C:\tools\cmake\bin\cmake.exe -E vs_link_dll --intdir=Source\WebCore\CMakeFiles\WebCore.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\WebCore.rsp  /out:bin\WebCore.dll /implib:lib\WebCore.lib /pdb:bin\WebCore.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  /DEBUG /OPT:NOICF /OPT:REF /INCREMENTAL:NO /DELAYLOAD:d3d9.dll /DELAYLOAD:dxva2.dll /DELAYLOAD:evr.dll /DELAYLOAD:mf.dll /DELAYLOAD:mfplat.dll && C:\Windows\system32\cmd.exe /C "cd /D C:\webkit\wb\WebKitBuild\Debug\Source\WebCore && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile -executionpolicy Bypass -file "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/vcpkg/scripts/buildsystems/msbuild/applocal.ps1" -targetBinary C:/webkit/wb/WebKitBuild/Debug/bin/WebCore.dll -installedDir C:/webkit/wb/WebKitBuild/Debug/vcpkg_installed/x64-windows/debug/bin -OutVariable out""
LINK: command "C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\WebCore.rsp /out:bin\WebCore.dll /implib:lib\WebCore.lib /pdb:bin\WebCore.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /DEBUG /OPT:NOICF /OPT:REF /INCREMENTAL:NO /DELAYLOAD:d3d9.dll /DELAYLOAD:dxva2.dll /DELAYLOAD:evr.dll /DELAYLOAD:mf.dll /DELAYLOAD:mfplat.dll /MANIFEST:EMBED,ID=2" failed (exit code 1) with the following output:
lld-link: error: /failifmismatch: mismatch detected for '_ITERATOR_DEBUG_LEVEL':
>>> Source\WebCore\PAL\pal\CMakeFiles\PAL.dir\.\win\LoggingWin.cpp.obj has value 0
>>> woff2dec.lib(woff2_dec.cc.obj) has value 2
ninja: build stopped: subcommand failed.
~~~

2024-11-11 04:55 UTC, fujii commented
* How and when should buildbot workers wipe out `%USERPROFILE%/AppData/Local/vcpkg` directory?

2024-11-13 00:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/89c7498d57b6a7d540c2f3b903af11b8e2389170. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-13 00:53 UTC, donny-dont commented
> I tried `build-webkit --debug` on my PC, and got an error.
> 
> ```
> [3632/6915] Linking CXX shared library bin\WebCore.dll
> FAILED: bin/WebCore.dll lib/WebCore.lib
> C:\Windows\system32\cmd.exe /C "cd . && C:\tools\cmake\bin\cmake.exe -E vs_link_dll --intdir=Source\WebCore\CMakeFiles\WebCore.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\WebCore.rsp  /out:bin\WebCore.dll /implib:lib\WebCore.lib /pdb:bin\WebCore.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  /DEBUG /OPT:NOICF /OPT:REF /INCREMENTAL:NO /DELAYLOAD:d3d9.dll /DELAYLOAD:dxva2.dll /DELAYLOAD:evr.dll /DELAYLOAD:mf.dll /DELAYLOAD:mfplat.dll && C:\Windows\system32\cmd.exe /C "cd /D C:\webkit\wb\WebKitBuild\Debug\Source\WebCore && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile -executionpolicy Bypass -file "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/vcpkg/scripts/buildsystems/msbuild/applocal.ps1" -targetBinary C:/webkit/wb/WebKitBuild/Debug/bin/WebCore.dll -installedDir C:/webkit/wb/WebKitBuild/Debug/vcpkg_installed/x64-windows/debug/bin -OutVariable out""
> LINK: command "C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo @CMakeFiles\WebCore.rsp /out:bin\WebCore.dll /implib:lib\WebCore.lib /pdb:bin\WebCore.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /DEBUG /OPT:NOICF /OPT:REF /INCREMENTAL:NO /DELAYLOAD:d3d9.dll /DELAYLOAD:dxva2.dll /DELAYLOAD:evr.dll /DELAYLOAD:mf.dll /DELAYLOAD:mfplat.dll /MANIFEST:EMBED,ID=2" failed (exit code 1) with the following output:
> lld-link: error: /failifmismatch: mismatch detected for '_ITERATOR_DEBUG_LEVEL':
> >>> Source\WebCore\PAL\pal\CMakeFiles\PAL.dir\.\win\LoggingWin.cpp.obj has value 0
> >>> woff2dec.lib(woff2_dec.cc.obj) has value 2
> ninja: build stopped: subcommand failed.
> ```

This is resolved now

2024-11-14 00:47 UTC, fujii commented on Tools/Scripts/update-webkit-win-libs.py
Don't remove this file. You can remove this file after deploying EWS and post-commit Buildbot.
And, I think we should keep this file with a content invoking "vcpkg install" for layout test buildbot rather than including all dependent DLL to a zip file.

2024-11-14 00:48 UTC, fujii requested changes
Why don't you use GitHub packages binary cache?

2024-11-16 02:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0e8ae69e1f49b6f73d197c1018b9989ebee20970. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-16 02:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1703a09e7668a7d3c072433e21728568b44a97b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-16 02:38 UTC, donny-dont reviewed
Expanded the use of `vcpkg.json` so we can use it for feature selection.

2024-11-16 02:38 UTC, donny-dont commented on vcpkg.json
> +    },
@fujii @tats-u with `vcpkg` you can add features for the build. In this case it'll use the upstream `vcpkg` registry to build with avif support.

The `build-webkit` script would need to have knowledge of this going forward.

2024-11-16 02:38 UTC, donny-dont commented on vcpkg.json
> +    },
@fujii please confirm these are the features you are expecting for harfbuzz.

2024-11-19 19:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/49fd63e810b696979e74637bd097f392dc397222. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2024-11-19 20:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a7621046152e1a0d00e8f96ca951d31c999a9e57. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-17 00:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/39f45deb2d2f8d8292d21d1828e2912860352aad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-17 00:37 UTC, donny-dont commented
This is now ready to land. The vcpkg configuration corresponds with https://github.com/WebKitForWindows/WebKitRequirements/releases/tag/v2025.01.16

2025-01-17 01:03 UTC, fujii commented on Tools/Scripts/webkitdirs.pm
> +        push @args, '-DVCPKG_TARGET_TRIPLET=x64-windows-webkit'
Why do you have to create a new triplet `x64-windows-webkit`? Use built-in triplet `x64-windows`.

2025-01-17 01:03 UTC, fujii commented on Tools/Scripts/webkitdirs.pm
> +        push @args, '-DVCPKG_TARGET_TRIPLET=x64-windows-webkit'
`vcpkg help triplet` for more info.

2025-01-17 01:12 UTC, fujii commented on Tools/Scripts/webkitdirs.pm
> +sub vcpkgArgsFromFeatures(\@;$)
vcpkgArgsFromFeatures is useless. It just returns a constant string.
I think we don't have to add avif and skia now. It's easy to add them later.

2025-01-17 01:57 UTC, donny-dont commented on Tools/Scripts/webkitdirs.pm
> +sub vcpkgArgsFromFeatures(\@;$)
I haven't gotten around to looking for feature flags yet so this is stubbed out.

2025-01-17 01:57 UTC, donny-dont commented on Tools/Scripts/webkitdirs.pm
> +        push @args, '-DVCPKG_TARGET_TRIPLET=x64-windows-webkit'
Its required to replace `zlib` with `zlib-ng` see https://github.com/microsoft/vcpkg/pull/43147

2025-01-17 02:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ca32e77c48b8f18a98df9e0f03d479d7aaf20322. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-17 02:07 UTC, donny-dont commented on Tools/Scripts/webkitdirs.pm
> +        push @args, '-DCMAKE_TOOLCHAIN_FILE="' . $ENV{VCPKG_ROOT} . '\\scripts\\buildsystems\\vcpkg.cmake"';
Should probably add an error if `VCPKG_ROOT` is not set.

2025-01-17 05:39 UTC, fujii commented
> This is now ready to land. 

Not ready to land. Debug build is very crashy. I'm seeing 4 problems.
1. `ASSERTION FAILED: result` in `void WebKit::FrameLoadState::removeObserver(FrameLoadStateObserver &)`
2.  "array subscript out of range" in `std::array<unsigned char,3>::operator[]` Signal::Unknown in SignalHandlers::forEachHandler
3. `abort()` in libcurl
4. `Expression: Offset out of range in span::subspan(offset, count)` for `fast/canvas/canvas-blending-shadow.html`

2025-01-17 06:54 UTC, fujii commented on Tools/Scripts/webkitdirs.pm
> +sub vcpkgArgsFromFeatures(\@;$)
Then, let's remove it for now.

2025-01-17 21:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b110f07a3f9f3f9a80d8423a73350b82497cc2cd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-17 22:21 UTC, donny-dont commented
Artifacts have the .dll files in them https://ews-build.webkit.org/#/builders/60/builds/24128/steps/12/logs/stdio

2025-01-21 19:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9199ffcd2bbb1780b5240dc0cc76512305659f5f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-21 19:08 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/9199ffcd2bbb1780b5240dc0cc76512305659f5f)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/85728 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/87769 "Build is in progress. Recent messages:") | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-Sequoia-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/88733 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 ios-wk2-wpt ](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 🧪 jsc](https://ews-build.webkit.org/#/builders/20/builds/78736 "Build is in progress. Recent messages:") | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/84715 "Build is in progress. Recent messages:") | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-2-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Sequoia-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-intel-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 playstation ](https://ews-build.webkit.org/#/builders/PlayStation-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/107104 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/35/builds/107104 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2025-01-21 19:15 UTC, donny-dont commented
> > This is now ready to land.
> 
> Not ready to land. Debug build is very crashy. I'm seeing 4 problems.
> 
> 1. `ASSERTION FAILED: result` in `void WebKit::FrameLoadState::removeObserver(FrameLoadStateObserver &)`
> 2. "array subscript out of range" in `std::array<unsigned char,3>::operator[]` Signal::Unknown in SignalHandlers::forEachHandler
> 3. `abort()` in libcurl
> 4. `Expression: Offset out of range in span::subspan(offset, count)` for `fast/canvas/canvas-blending-shadow.html`

More crashes should be expected with this. Its switching the runtime to debug, hence the STL crashes, and all the third party libraries to debug. This should be landed and those can be bugs to work on.

2025-01-21 19:29 UTC, foopoiuyt commented on Tools/Scripts/build-webkit
> +if (isAnyWindows() && ! defined $ENV{"VCPKG_ROOT"}) {
isAnyWindows seems to be "is running on windows or cygwin as it checks $^O, not doing the windows port (which I think is isWin).  This seems wrong since I think we only want to be using vcpkg for the one port.

2025-01-21 19:31 UTC, foopoiuyt commented on Tools/Scripts/download-github-release.py
> -#! /usr/bin/env python3
This looks to be used downstream, so should have that resolved before removing the file.

2025-01-21 19:34 UTC, foopoiuyt commented on Tools/Scripts/webkitdirs.pm
> +    if (isAnyWindows()) {
As above, this seems like a bad choice of condition as it appears to be based on what OS perl was built for. We presumably want to do this for the windows port or jsconly on windows but not for another port that happens to be being built on windows.

2025-01-21 19:37 UTC, foopoiuyt commented on Tools/Scripts/webkitdirs.pm
> +    my $avif = 0;
Are these intended to be the default values? It seems unfortunate to encode a default in an additional place.

2025-01-21 20:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/54d00b6ec955d9b6c38007cd31ad33dcbe004850. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-21 22:24 UTC, donny-dont commented on Tools/Scripts/webkitdirs.pm
> +    my $avif = 0;
Yep there really isnt any way around that without parsing the CMake files.

2025-01-21 22:26 UTC, donny-dont commented on Tools/Scripts/download-github-release.py
> -#! /usr/bin/env python3
Pretty sure we stopped using GitHub releases internally so this script is of no use to it.

2025-01-21 23:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4c51c12898a12a7262cba3029af45093b7f10f0e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-21 23:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4c51c12898a12a7262cba3029af45093b7f10f0e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-21 23:17 UTC, donny-dont commented
Alrighty tested with JSCOnly builds on Windows and the Windows port build.

@fujii please finish review.

2025-01-21 23:36 UTC, fujii commented
This is still too unstable to land. I will debug the bugs if you won't. But, I'm a bit busy. Please wait.

2025-01-21 23:52 UTC, donny-dont commented
> This is still too unstable to land. I will debug the bugs if you won't. But, I'm a bit busy. Please wait.

Again the runtime is changing for everything so Debug builds will find new issues. Those issues are outside this patch and can be addressed as they are found.

The Release build functions as expected.

2025-01-23 17:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f60c50cc4705a69df96dcd29e47d2ea4927b6d5e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-23 17:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f60c50cc4705a69df96dcd29e47d2ea4927b6d5e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-29 19:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5046384884c4ff3ab1b29564b9785687cb5e2d46. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-01-30 07:23 UTC, fujii commented
Oh, no. One more problem has come. https://bugs.webkit.org/show_bug.cgi?id=286727#c4
Using Debug CRT seems to be a bad idea. Could we keep using Release CRT even for Debug builds?

2025-01-30 19:37 UTC, donny-dont commented
> Oh, no. One more problem has come. https://bugs.webkit.org/show_bug.cgi?id=286727#c4 Using Debug CRT seems to be a bad idea. Could we keep using Release CRT even for Debug builds?

Using the debug CRT is going to turn up actual issues. The bug you pointed to is a legitimate bug. This is why I want to just land this and open up bugs as they arise.

2025-02-08 18:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/73235c3fb96ec0bde667a6059f05b621e421967a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-02-11 21:18 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/8b91e74cbcea1ada7c1363ec383d45c58523768d)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/89375 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/8900 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/91426 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/9287 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/17177 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/92377 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/9287 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/9287 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/39243 "Build is in progress. Recent messages:") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/9287 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/96190 "Build is in progress. Recent messages:Running configuration") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/88151 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/16556 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/17177 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/96190 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/16811 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/96190 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/44214 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 playstation ](https://ews-build.webkit.org/#/builders/PlayStation-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/16569 "Build is in progress. Recent messages:OS: Sequoia (15.2), Xcode: 16.2") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/110644 "Build is in progress. Recent messages:") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/35/builds/110644 "Build is in progress. Recent messages:") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 [...]

2025-02-13 01:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/091aed9f8e15efb0ff9dd2d1cf2e3fbb268c31ed. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-02-13 01:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/65724c858b002c981ae8e80882db0abd12c4f7d3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-02-13 01:53 UTC, donny-dont reviewed
~~This forces release libraries for the moment until the curl issue is resolved. There could be other asserts being hit in other libraries that will not be caught at this time because of `VCPKG_BUILD_TYPE` being set.~~

This doesn't work due to libwoff2 requiring static linkage. So removing comments.

2025-02-13 01:53 UTC, donny-dont commented on WebKitLibraries/triplets/x64-windows-webkit.cmake
> +message(WARNING "Overriding VCPKG_BUILD_TYPE to ${VCPKG_BUILD_TYPE} due to an issue in ${_BAD_PORT} v${_BAD_VERSION}")
This will force all ports to be built with release only.

I tried having just curl specified this way but when it got to WebKit it used all release libraries and didn't mix and match so might as well optimize for this case.

2025-02-13 01:53 UTC, donny-dont commented on WebKitLibraries/triplets/x64-windows-webkit.cmake
> +endif ()
This is a sanity check to see if the version was modified. If so it directs the person making the modification to check the debug build and make a judgement call on whether or not this entire thing can be removed.

2025-02-13 19:58 UTC, fujii requested changes
`build-webkit --debug` fails. Please test debug build&test before updating this PR.

I'm maintaining 14 Windows buildbot workers. Downloading tarball from official servers will make them flaky.
We should use [Binary Caching](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching).

2025-02-14 17:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9594fed5f5be5be34ee237d7503b6841cefcc514. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-02-14 18:07 UTC, donny-dont commented
> `build-webkit --debug` fails. Please test debug build&test before updating this PR.

For cases where WebKit needs to be debugged but a third party library has a large issue in debug, like the one with curl currently, a developer can manually invoke CMake to do a release build with debug information.

```
cmake -DPORT="Win" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE="C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-webkit -G Ninja -DDEVELOPER_MODE=ON -DENABLE_EXPERIMENTAL_FEATURES=ON -DVCPKG_MANIFEST_FEATURES=web;jpeg-xl;lcms;cairo;woff2 "C:/webkit"
```

Any new crashes that are found by switching to the debug runtime and debug libraries are bugs and should be triaged and assigned out. This is a big enough change that bugs are expected. Better to get all windows contributors on it rather than just you.

> I'm maintaining 14 Windows buildbot workers. Downloading tarball from official servers will make them flaky. We should use [Binary Caching](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching).

There is already binary caching by default in vcpkg. It uses the file system for a local cache. When there's a cache miss it will trigger a full build of the requirements. If the WebKitBuild directory is completely removed that cache is still there and will be restored.

Here is a [full vcpkg build](https://ews-build.webkit.org/#/builders/59/builds/37203/steps/13/logs/stdio) on EWS. And one where [vcpkg restores from cache](https://ews-build.webkit.org/#/builders/59/builds/39726/steps/13/logs/stdio). After the initial cost of building restores are done in less than a second.

Almost all the vcpkg ports get their sources from GitHub. If GitHub went down so downloads were unavailable its unlikely WebKit builds would be functional since its on GitHub. So your hypothetical worst case where there's a cache miss and a download issue occurs is as theoretical as the WebKitRequirements64.zip failing to download.

I plan on adding a GitHub packages NuGet feed to do caching across bots. By using docker images the build environments will be identical so the caching there should work and it would be one build for all the bots. This patch needs to land so I can work on turning it on within a docker image.

Again there is no reason this patch shouldn't land.

2025-02-20 00:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/edfa3f4845476913dfd5093ad1fe6e6b5456a5b2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-03-24 21:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa9fcdd426b97c9f7afb7d5d6ff1535bc733f5b0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-03-25 20:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5639869d99f207b1ef5001534a9868bebdc83b7e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-04-01 17:13 UTC, iangrunert commented
Any update on this @fujii ? I don't think the USE_SKIA build works on main at the moment because the latest WebKitRequirements doesn't include harfbuzz. I think this patch would fix that and make it easier to update the dependencies over time.

2025-04-04 03:10 UTC, donny-dont commented
> `build-webkit --debug` fails. Please test debug build&test before updating this PR.
> 
> I'm maintaining 14 Windows buildbot workers. Downloading tarball from official servers will make them flaky. We should use [Binary Caching](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching).

I updated the Docker images in [docker-webkit-dev](https://github.com/WebKitForWindows/docker-webkit-dev) and did a build of this patch locally. The first one put artifacts at [WebKitForWindows](https://github.com/orgs/WebKitForWindows/packages) (note that it may not be visible to those without permissions). The second one restored them. See the output 👇 

```
PS C:\webkit> perl .\Tools\Scripts\build-webkit --generate-project-only
+  cmake -DPORT="Win" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-webkit -G Ninja -DDEVELOPER_MODE=ON -DENABLE_EXPERIMENTAL_FEATURES=ON -DVCPKG_MANIFEST_FEATURES=web;jpeg-xl;lcms;cairo;woff2 "C:/webkit"
-- Running vcpkg install
Fetching registry information from https://github.com/WebKitForWindows/WebKitRequirements (HEAD)...
Fetching registry information from https://github.com/microsoft/vcpkg (HEAD)...
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.24).
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.24/PowerShell-7.2.24-win-x64.zip -> PowerShell-7.2.24-win-x64.zip
Successfully downloaded PowerShell-7.2.24-win-x64.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v24.9.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.09/7z2409.exe -> 7z2409.7z.exe
Successfully downloaded 7z2409.7z.exe
Extracting 7zip...
A suitable version of 7zr was not found (required v24.9.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.09/7zr.exe -> 44d8504a-7zr.exe
Successfully downloaded 44d8504a-7zr.exe
Compiler found: C:/MSVS/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x64-windows-webkit...
Compiler found: C:/MSVS/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    brotli:x64-windows-webkit@1.1.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\4e5b5ae1ad26c80535c893cc0307121f0398549e
    cairo:x64-windows-webkit@1.18.2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\d66ade1c9bb9ec902032fad20ac0d975208fedb4
    curl[core,http3,ipv6,libressl]:x64-windows-webkit@8.13.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\cc5115020dc054ffead1ff27fb41a39b9ef9c31b
  * highway:x64-windows-webkit@1.2.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\6084fa0969d208dd78997f44e8b4b406aa174345
    icu:x64-windows-webkit@76.1.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\017ddcb2e0493fecbad3eb52acebc458353ccdb9
    lcms:x64-windows-webkit@2.16 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\781f8c60a57e793ac8b9800b3b7cfa6e46f75b44
    libjpeg-turbo:x64-windows-webkit@3.1.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\6180688844449e5724d6dc8eb49ab90124438ce2
    libjxl:x64-windows-webkit@0.11.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1b18a67135031ccaa38f55a3f8c0a2dff6082754
    libpng:x64-windows-webkit@1.6.46 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\0074ace75112e0a4ff3465de21e692c07d6e6b5f
    libpsl[core,libicu]:x64-windows-webkit@0.21.5#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1f1ba362bcb9a330a5882ff668eb7fc3a2c2b6c3
    libressl:x64-windows-webkit@4.0.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\becbc2d569c392b3f2d60027db3797b51839c53a
    libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows-webkit@1.5.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\785bb5f8a86b4f67c4186cdb2c7ee09d344dcfff
    libxml2[core,icu]:x64-windows-webkit@2.13.5#2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\90c8aae598f04d95b887f5bfd29e24ab1308bbfa
    libxslt[core,profiler,thread]:x64-windows-webkit@1.1.42#2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\00e5829fca614f1b82dc9fa5439ef0a8d35d7cb4
    nghttp2:x64-windows-webkit@1.65.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1c6c0f58fa40de3a567e40bcf361c6d448d5f7fb
    nghttp3:x64-windows-webkit@1.8.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\e2baa2babbe24c2c68c68e1dc8f66cc5f6550415
    ngtcp2[core,libressl]:x64-windows-webkit@1.11.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\aa28f3bb1e6ff83a034c6126468849699412a355
  * pixman:x64-windows-webkit@0.44.2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\39c74ae3b4a9b82eb48d08a5c80ddb171817c03c
    sqlite3[core,fts3,json1,rtree]:x64-windows-webkit@3.49.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\92c7e25e29daa51849b0f0b82bae84898ebb80d9
  * vcpkg-cmake:x64-windows@2024-04-23 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\e74aa1e8f93278a8e71372f1fa08c3df420eb840
  * vcpkg-cmake-config:x64-windows@2024-05-23 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\97a63e4bc1a17422ffe4eff71da53b4b561a7841
  * vcpkg-cmake-get-vars:x64-windows@2024-09-22 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\f23148add155147f3d95ae622d3b0031beb25acf
  * vcpkg-tool-meson:x64-windows@1.6.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\dc948c67d7f1359319f801078422e996b0a89fd0
    woff2:x64-windows-webkit@1.0.2#4 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\fbd2207ad0ad1e7e52b421b86f96deff9ed7ec65
    zlib:x64-windows-webkit@zlib-ng -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\b7e95e97d224d1a520ec9d5246f76c1e52bb4c8c
  * zlib-ng:x64-windows-webkit@2.2.3#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\8282d357a50be706405e9aed44a79a333a8e8af1
Additional packages (*) will be modified to complete this operation.
Restored 26 package(s) from NuGet in 15 s. Use --debug to see more details.
Installing 1/26 vcpkg-cmake-config:x64-windows@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 140 ms
vcpkg-cmake-config:x64-windows package ABI: 0408c0ddaacdb1609e91b76b78561e1416aa65a288ca98a83b5e6c7f6c596a8d
Installing 2/26 vcpkg-cmake:x64-windows@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows: 111 ms
vcpkg-cmake:x64-windows package ABI: 55779ee0cf97e43c44324cd2cebe8e813b3aab526fcf4715203f83a99fb6c9d1
Installing 3/26 icu:x64-windows-webkit@76.1.0...
Elapsed time to handle icu:x64-windows-webkit: 2.8 s
icu:x64-windows-webkit package ABI: 6767277326c700e71d1ba0c88c21418acebce9d630ac65a534ead5534a34f056
Installing 4/26 zlib-ng:x64-windows-webkit@2.2.3#1...
Elapsed time to handle zlib-ng:x64-windows-webkit: 240 ms
zlib-ng:x64-windows-webkit package ABI: 743b38b5169e58949b803e502c44e270319bd953bbf0d417633da74cea596837
Installing 5/26 zlib:x64-windows-webkit@zlib-ng...
Elapsed time to handle zlib:x64-windows-webkit: 66.6 ms
zlib:x64-windows-webkit package ABI: f4f7fe272f5d7de5731b3609abb0a03b9f3211c8bc04fef8fce9211eeca8f994
Installing 6/26 vcpkg-cmake-get-vars:x64-windows@2024-09-22...
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 93 ms
vcpkg-cmake-get-vars:x64-windows package ABI: 1522f2f862a248cae2cfc3ba9468da02b748d4befa0009d097f0b4cb2d8e355f
Installing 7/26 vcpkg-tool-meson:x64-windows@1.6.1...
Elapsed time to handle vcpkg-tool-meson:x64-windows: 102 ms
vcpkg-t [...]

2025-04-04 05:37 UTC, donny-dont commented
Updated config to include ICU 77.1

```
vcpkg x-update-baseline
updated registry 'https://github.com/microsoft/vcpkg': baseline '533a5fda5c0646d1771345fb572e759283444d5f' -> '9b75e789ece3f942159b8500584e35aafe3979ff'
updated registry 'https://github.com/WebKitForWindows/WebKitRequirements': baseline 'aee032959456f198c4cad0d9be09475fa1432629' -> '1da9e582b871b47fbf6d8fb881d25de3bd37cc08'
```

2025-04-04 05:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/616c811d26b5e89202086a541a20a1941fb6bb40. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-04-04 05:51 UTC, donny-dont commented
Added the vcpkg binary caching as requested to https://github.com/WebKitForWindows/docker-webkit-dev/pull/408

I ran it locally with the updated requirements and 👇 was pushed. The latest change updated ICU to 77.1.

![icu-77](https://github.com/user-attachments/assets/46ea7d1f-f70a-4b78-b978-5717a3fb3a35)

2025-04-05 01:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5e5416a136a57febc32bb06b13f5d8d301c454c2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-04-07 20:40 UTC, donny-dont commented
Using GitHub Packages as a NuGet feed for `vcpkg` was verified in EWS.

The cache was populated in https://ews-build.webkit.org/#/builders/59/builds/49007 . As an example here's icu 👇 

```
Installing 3/26 icu:x64-windows-webkit@77.1.0...
Building icu:x64-windows-webkit@77.1.0...
C:\BW\Win-Build-EWS\build\WebKitLibraries\triplets\x64-windows-webkit.cmake: info: loaded overlay triplet from here
C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\ea40f10ddf278b30180b541393a9045baebe740c: info: installing overlay port from here
Downloading https://github.com/unicode-org/icu/releases/download/release-77-1/icu4c-77_1-src.tgz -> icu4c-77_1-src.tgz
Successfully downloaded icu4c-77_1-src.tgz
-- Extracting source C:/vcpkg/downloads/icu4c-77_1-src.tgz
-- Applying patch C:/Users/ContainerAdministrator/AppData/Local/vcpkg/registries/git-trees/ea40f10ddf278b30180b541393a9045baebe740c/patches/0001-Add-CMake-platform.patch
-- Applying patch C:/Users/ContainerAdministrator/AppData/Local/vcpkg/registries/git-trees/ea40f10ddf278b30180b541393a9045baebe740c/patches/0002-Remove-install-suffix-on-Windows.patch
-- Using source at C:/vcpkg/buildtrees/icu/src/c-77_1-src-e4739f0a52.clean
-- Configuring x64-windows-webkit
-- Building x64-windows-webkit-dbg
-- Building x64-windows-webkit-rel
Downloading msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst, trying https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst
Successfully downloaded msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst
Downloading msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst, trying https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst
Successfully downloaded msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst
-- Using msys root at C:/vcpkg/downloads/tools/msys2/21caed2f81ec917b
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/lib/pkgconfig
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/lib/pkgconfig/icu-i18n.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/lib/pkgconfig/icu-io.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/lib/pkgconfig/icu-uc.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/debug/lib/pkgconfig
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/debug/lib/pkgconfig/icu-i18n.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/debug/lib/pkgconfig/icu-io.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/debug/lib/pkgconfig/icu-uc.pc
-- Installing: C:/vcpkg/packages/icu_x64-windows-webkit/share/icu/copyright
-- Performing post-build validation
Starting submission of icu:x64-windows-webkit@77.1.0 to 1 binary cache(s) in the background
Elapsed time to handle icu:x64-windows-webkit: 2.8 min
icu:x64-windows-webkit package ABI: 94d1add935157941e2392ad56e7246e188e78065d71b85fecdd32b70fbeffa8a
```

The hash from ☝️ is represented in the package listing 👇 .

![image](https://github.com/user-attachments/assets/47e24c16-76a7-4d4b-b875-6b32d921c963)

The next build then restored from cache on a different bot because the build environment hash was the same. (this is why the counter is 1 for ☝️). See https://ews-build.webkit.org/#/builders/59/builds/49018 for the complete build.

```
The following packages will be built and installed:
    brotli:x64-windows-webkit@1.1.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\4e5b5ae1ad26c80535c893cc0307121f0398549e
    cairo:x64-windows-webkit@1.18.2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\d66ade1c9bb9ec902032fad20ac0d975208fedb4
    curl[core,http3,ipv6,libressl]:x64-windows-webkit@8.13.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\cc5115020dc054ffead1ff27fb41a39b9ef9c31b
  * highway:x64-windows-webkit@1.2.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\6084fa0969d208dd78997f44e8b4b406aa174345
    icu:x64-windows-webkit@77.1.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\ea40f10ddf278b30180b541393a9045baebe740c
    lcms:x64-windows-webkit@2.16 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\781f8c60a57e793ac8b9800b3b7cfa6e46f75b44
    libjpeg-turbo:x64-windows-webkit@3.1.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\6180688844449e5724d6dc8eb49ab90124438ce2
    libjxl:x64-windows-webkit@0.11.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1b18a67135031ccaa38f55a3f8c0a2dff6082754
    libpng:x64-windows-webkit@1.6.46 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\0074ace75112e0a4ff3465de21e692c07d6e6b5f
    libpsl[core,libicu]:x64-windows-webkit@0.21.5#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1f1ba362bcb9a330a5882ff668eb7fc3a2c2b6c3
    libressl:x64-windows-webkit@4.0.0#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\becbc2d569c392b3f2d60027db3797b51839c53a
    libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows-webkit@1.5.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\785bb5f8a86b4f67c4186cdb2c7ee09d344dcfff
    libxml2[core,icu]:x64-windows-webkit@2.13.5#2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\90c8aae598f04d95b887f5bfd29e24ab1308bbfa
    libxslt[core,profiler,thread]:x64-windows-webkit@1.1.42#2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\00e5829fca614f1b82dc9fa5439ef0a8d35d7cb4
    nghttp2:x64-windows-webkit@1.65.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\1c6c0f58fa40de3a567e40bcf361c6d448d5f7fb
    nghttp3:x64-windows-webkit@1.8.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\e2baa2babbe24c2c68c68e1dc8f66cc5f6550415
    ngtcp2[core,libressl]:x64-windows-webkit@1.11.0 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\aa28f3bb1e6ff83a034c6126468849699412a355
  * pixman:x64-windows-webkit@0.44.2 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\39c74ae3b4a9b82eb48d08a5c80ddb171817c03c
    sqlite3[core,fts3,json1,rtree]:x64-windows-webkit@3.49.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\92c7e25e29daa51849b0f0b82bae84898ebb80d9
  * vcpkg-cmake:x64-windows@2024-04-23 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\e74aa1e8f93278a8e71372f1fa08c3df420eb840
  * vcpkg-cmake-config:x64-windows@2024-05-23 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\97a63e4bc1a17422ffe4eff71da53b4b561a7841
  * vcpkg-cmake-get-vars:x64-windows@2024-09-22 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\f23148add155147f3d95ae622d3b0031beb25acf
  * vcpkg-tool-meson:x64-windows@1.6.1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\dc948c67d7f1359319f801078422e996b0a89fd0
    woff2:x64-windows-webkit@1.0.2#4 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\fbd2207ad0ad1e7e52b421b86f96deff9ed7ec65
    zlib:x64-windows-webkit@zlib-ng -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\b7e95e97d224d1a520ec9d5246f76c1e52bb4c8c
  * zlib-ng:x64-windows-webkit@2.2.3#1 -- C:\Users\ContainerAdministrator\AppData\Local\vcpkg\registries\git-trees\8282d357a50be706405e9aed44a79a333a8e8af1
Additional packages (*) will be modified to complete this operation.
Restored 26 package(s) from NuGet in 13 s. Use --debug to see more details.
```

So a restore only took 13s. This seems more efficient than the `WebKitRequirements.zip`.

Overall this is ready to go. The request for binary caching has been done for all bots using Docker. A bot provided by Playwright folks is not using Docker, ews-004, and does not have vcpkg installed. I believe this is due to Visual Studio 2022 build tools which does not pac [...]

2025-04-08 07:28 UTC, fujii commented
debug builds still have a problem https://bugs.webkit.org/show_bug.cgi?id=287815

2025-04-17 07:47 UTC, rkirsling commented
Given that the test failure in the linked bug literally says `Fatal because this is a curl debug build`, it certainly seems reasonable that these be marked as debug failures in a test gardening patch—is there any reason to view these as a blocker for merging this PR?

2025-04-17 07:58 UTC, fujii commented
I know it's not a problem for you. You don't maintain Windows WebKit. You don't fix problems for Windows WebKit.
Please adopt vcpkg manifest mode to PlayStation port beforehand. I'm confident it will cause trouble. If it is really nice, I will change my mind.

2025-04-17 08:33 UTC, donny-dont commented
Given the needs of the community shipping the Windows port I am confident this solves all the issues with WebKitRequirements.zip. Their concerns with the status quo are valid and need to be prioritized.

This patch has already identified issues in the codebase that weren’t caught because the release crt was used. Using fully debug libraries might identify more issues.

Hypotheticals aren’t a reason to block this patch and not landing this patch is making the windows port less secure.

2025-04-25 18:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9853c43d740f2cbf483560047ef2e999ac7695bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-05-09 13:54 UTC, rkirsling approved these changes

2025-05-12 19:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/419c15ea29e571c126e4269ceb3a21df7dbf5640. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-05-13 22:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9237033312bfc38be24e0380ebe58cde6c07590c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36366

2025-05-16 23:41 UTC, webkit-commit-queue commented
Committed 295042@main (32342c72df2d): <https://commits.webkit.org/295042@main>

Reviewed commits have been landed. Closing PR #36366 and removing active labels.

2025-05-16 23:41 UTC, merged