Remove WebAutomationSession.messages.in
WebKit/WebKit pull request #36540
Opened 2024-11-12 19:20 UTC by achristensen07

#### 6940b2e83fc80258866c3998d6add1931b423b44
<pre>
Remove WebAutomationSession.messages.in
<a href="https://bugs.webkit.org/show_bug.cgi?id=283000">https://bugs.webkit.org/show_bug.cgi?id=283000</a>
<a href="https://rdar.apple.com/61789956">rdar://61789956</a>

Reviewed by NOBODY (OOPS!).

sendWithAsyncReply can replace it entirely.

* Source/WebKit/CMakeLists.txt:
* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/UIProcess/Automation/WebAutomationSession.cpp:
(WebKit::WebAutomationSession::setProcessPool):
(WebKit::WebAutomationSession::takeScreenshot):
(WebKit::WebAutomationSession::didTakeScreenshot): Deleted.
* Source/WebKit/UIProcess/Automation/WebAutomationSession.h:
* Source/WebKit/UIProcess/Automation/WebAutomationSession.messages.in: Removed.
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::sendToProcessContainingFrameWithoutDestinationIdentifier): Deleted.
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Source/WebKit/WebProcess/Automation/WebAutomationSessionProxy.cpp:
(WebKit::WebAutomationSessionProxy::takeScreenshot):
* Source/WebKit/WebProcess/Automation/WebAutomationSessionProxy.h:
* Source/WebKit/WebProcess/Automation/WebAutomationSessionProxy.messages.in:
</pre>

2024-11-12 19:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6940b2e83fc80258866c3998d6add1931b423b44. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36540

2024-11-12 22:08 UTC, szewai approved these changes

2024-11-12 22:15 UTC, burg requested changes

2024-11-12 22:15 UTC, burg commented on Source/WebKit/UIProcess/Automation/WebAutomationSession.cpp
> +            if (!imageDataHandle)
This was an existing logic bug, but.. the command will hang if we return here without calling `callback`. Please do 

`ASYNC_FAIL_WITH_PREDEFINED_ERROR(InternalError);`

like we do in the next case.

2024-11-12 23:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c4cf2b12617a0a414cfbe855bd9944b409e07383. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36540

2024-11-12 23:18 UTC, burg approved these changes

2024-11-13 04:07 UTC, webkit-commit-queue commented
Committed 286516@main (dbfc540858e6): <https://commits.webkit.org/286516@main>

Reviewed commits have been landed. Closing PR #36540 and removing active labels.

2024-11-13 04:07 UTC, merged