Use monospaced font https://bugs.webkit.org/show_bug.cgi?id=283303
WebKit/WebKit pull request #36806
Opened 2024-11-18 17:51 UTC by eocanha

#### a3d95e88f28cdecd052290fb9e6ccdc813669826
<pre>
Use monospaced font <a href="https://bugs.webkit.org/show_bug.cgi?id=283303">https://bugs.webkit.org/show_bug.cgi?id=283303</a>

Reviewed by NOBODY (OOPS!).

It&apos;s not uncommon for comments in bug reports to include pieces of code
or other text-based content. An example of this is this is the file
format dump in <a href="https://bugs.webkit.org/show_bug.cgi?id=254222.">https://bugs.webkit.org/show_bug.cgi?id=254222.</a> For this
kind of content, it makes more sense to use monospaced font in comment
text boxes, which was a feature available in the previous Bugzilla
version.

This patch changes the right style to use monospace font.

* Websites/bugs.webkit.org/skins/custom/global.css:
(.bz_comment_text): Use monospace font.
</pre>

2024-11-18 17:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a3d95e88f28cdecd052290fb9e6ccdc813669826. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36806

2024-11-18 18:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/21b2fb9329fa9ed22b965a8b08a1411e9f6f48ed. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36806

2024-11-19 22:20 UTC, fujii approved these changes

2024-11-20 19:24 UTC, aproskuryakov requested changes
This was an intentional change, we think that using a proportional font is commonly better.

Agreed that it's not so great for code or ASCII art, we should merge Markdown support from upstream.

2024-11-20 19:45 UTC, eocanha commented
Thanks for the clarification. I'm withdrawing this PR.

2024-11-20 19:45 UTC, closed without merging

2024-11-20 21:07 UTC, fujii commented
I think Markdown can't be a solution. Do you plan to convert all Bugzilla comments? How to convert? Can you detect which part is code or ASCII arts?

2024-11-20 21:23 UTC, aproskuryakov commented
Mozilla had a date cut-off as far as I know, so Markdown processing is only applied to newer comments. Seems likely that we'd do the same.

2024-11-20 22:00 UTC, aproskuryakov commented
I agree that some of the comments don't look ideal now. I still think that the negative consequences are small enough and are not worth using a monospace font everywhere just because of a few ASCII graphics posted in the past.

2024-11-27 19:34 UTC, mcatanzaro commented
> Then, we should apply monospace font to old comments such like https://bugs.webkit.org/show_bug.cgi?id=254222

This is case in point for why monospace is important.

Fujii found another example: https://bugs.webkit.org/show_bug.cgi?id=283598

My own example of proportional font making things harder to read is [here](https://bugs.webkit.org/show_bug.cgi?id=283768) where the `~~~~^~` is displayed in the wrong place. For example:

```
 1508 |     m_result[directoryEntryOffset] = identifier[0];
      |                                      ~~~~~~~~~~^~
```

With a monospace font it's clear that the broken code is identifier[0],  but with proportional font it looks like the problem is somewhere in the middle of m_result[dictionaryEntryOffset]. I wasn't sure which side of the expression needed to be fixed until I realized that I should look in my terminal rather than Bugzilla.

2025-01-06 20:56 UTC, mcatanzaro commented
Can we reopen/reconsider this please? It's just making Bugzilla harder without clear benefit.

2025-01-06 21:01 UTC, aproskuryakov commented
We're working on Markdown support, and don't plan to switch the default.

> without clear benefit

I disagree with this assessment. Using a proportional font improves more existing content in Bugzilla than it makes worse.

2025-01-06 21:58 UTC, mcatanzaro commented
Markdown sounds great, but will Bugzilla use a monospace font for old comments that predate Markdown?

[Another example bug](https://bugs.webkit.org/show_bug.cgi?id=285462) which is very hard to read due to proportional-width font

2025-01-06 23:33 UTC, aproskuryakov commented
Given that using a proportional font improves more existing content in Bugzilla than it makes worse, we're not intending to revert to monospace.

2025-03-29 01:36 UTC, smfr commented
>  using a proportional font improves more existing content in Bugzilla than it makes worse
I disagree.