[Fuzzer Binaries] Add libwebrtc fuzzers
WebKit/WebKit pull request #36909
Opened 2024-11-20 19:04 UTC by JonWBedard

#### 40d1afd4321683f842a9c1706025f079a23e2f46
<pre>
[Fuzzer Binaries] Add libwebrtc fuzzers
<a href="https://bugs.webkit.org/show_bug.cgi?id=283432">https://bugs.webkit.org/show_bug.cgi?id=283432</a>
<a href="https://rdar.apple.com/140288399">rdar://140288399</a>

Reviewed by NOBODY (OOPS!).

* Source/ThirdParty/libwebrtc/Configurations/h264_bitstream_parser_fuzzer.xcconfig: Install when ENABLE_LIBFUZZER is true.
* Source/ThirdParty/libwebrtc/Configurations/h264_depacketizer_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/h265_bitstream_parser_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/h265_depacketizer_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/rtp_depacketizer_av1_assemble_frame_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/rtp_packetizer_av1_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/sdp_integration_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp8_dec_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp8_depacketizer_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp8_qp_parser_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp8_replay_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp9_dec_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp9_depacketizer_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp9_qp_parser_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/vp9_replay_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/Configurations/webm_fuzzer.xcconfig: Ditto.
* Source/ThirdParty/libwebrtc/libwebrtc.xcodeproj/project.pbxproj: Build fuzzers as part of libwebrtc. Exclude sdp_integration_fuzzer
since it does not build.
* Source/ThirdParty/libwebrtc/libwebrtc.xcodeproj/xcshareddata/xcschemes/libwebrtc.xcscheme: Rename libwebrtc to libwebrtc.dylib so
that libwebrtc can target fuzzers too.
</pre>

2024-11-20 19:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/40d1afd4321683f842a9c1706025f079a23e2f46. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36909

2024-11-21 01:04 UTC, ddkilzer requested changes
Need to understand why `sdp_integration_fuzzer` broke before we land this.

I'm looking at that now.

2024-11-21 05:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ce44b15d3b59abcf12ac403aa9381e8d52f6d707. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36909

2024-11-22 20:52 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/908cdb944c24754a40a31dd91e0177e2b06045d6)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/77836 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/48/builds/56869 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/49/builds/66027 "Build is in progress. Recent messages:") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-Sequoia-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/80904 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/49/builds/66027 "Build is in progress. Recent messages:") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/49/builds/66027 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/49/builds/66027 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/83846 "Build is in progress. Recent messages:Running configuration") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-2-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Sequoia-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/83846 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/83846 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-intel-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2025-02-06 00:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e3d27753ba6e2da9e2a29d7942b0eb7d6ccf4136. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36909

2025-02-06 05:14 UTC, ddkilzer approved these changes
r=me, but please make sure we have a bug/radar tracking tracking the fix for `sdp_integration_fuzzer`.

Also, make sure we add the `EXCLUDED_SOURCE_FILE_NAMES` macros as needed for other `*.xcconfig` files.

2025-02-06 05:14 UTC, ddkilzer commented on Source/ThirdParty/libwebrtc/Configurations/h264_bitstream_parser_fuzzer.xcconfig
> +EXCLUDED_SOURCE_FILE_NAMES_YES = ;
Why are these needed in some targets, but not (for example) `aom_av1_encoder_fuzzer.xcconfig`?

Or maybe `aom_av1_encoder_fuzzer.xcconfig` just needs this added?  :)

2025-02-06 05:14 UTC, ddkilzer commented on Source/ThirdParty/libwebrtc/Configurations/vp8_encoder_fuzzer.xcconfig
> +
Do we need to add these lines here?

```suggestion

EXCLUDED_SOURCE_FILE_NAMES = $(EXCLUDED_SOURCE_FILE_NAMES_$(ENABLE_LIBFUZZER));
EXCLUDED_SOURCE_FILE_NAMES_ = *;
EXCLUDED_SOURCE_FILE_NAMES_YES = ;

```

2025-02-06 05:14 UTC, ddkilzer commented on Source/ThirdParty/libwebrtc/Configurations/vp9_encoder_fuzzer.xcconfig
> +
Do we need to add these lines here?

```suggestion

EXCLUDED_SOURCE_FILE_NAMES = $(EXCLUDED_SOURCE_FILE_NAMES_$(ENABLE_LIBFUZZER));
EXCLUDED_SOURCE_FILE_NAMES_ = *;
EXCLUDED_SOURCE_FILE_NAMES_YES = ;

```

2025-02-06 05:14 UTC, ddkilzer commented on Source/ThirdParty/libwebrtc/libwebrtc.xcodeproj/project.pbxproj
> -		};
Is there a way we can be clever and disable building `sdp_integration_fuzzer` when building with automation, but leave `sdp_integration_fuzzer` enabled when building at desk for engineers?

Maybe this isn't a common enough use case to do this, though.

We should have a bug or radar tracking the fix, though.  (We probably do, but it's late, and I'm too tired to look it up.)

2025-02-06 16:13 UTC, JonWBedard commented on Source/ThirdParty/libwebrtc/Configurations/vp9_encoder_fuzzer.xcconfig
> +
We do, this is an oversight. (actually somewhat surprised this built in EWS without these lines)

2025-02-06 16:15 UTC, JonWBedard commented on Source/ThirdParty/libwebrtc/Configurations/h264_bitstream_parser_fuzzer.xcconfig
> +EXCLUDED_SOURCE_FILE_NAMES_YES = ;
These lines should be added for everything, I missed some of the fuzzers you just added in https://commits.webkit.org/289734@main

2025-02-06 16:16 UTC, JonWBedard commented on Source/ThirdParty/libwebrtc/libwebrtc.xcodeproj/project.pbxproj
> -		};
I think this is not common enough to do. My hope is also that this is short-lived.

Tracked in https://bugs.webkit.org/show_bug.cgi?id=287154, which I'll be mentioning in the new commit message.

2025-02-06 17:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f5d9568dd1c9fba556c278c6cefdb5835138614d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36909

2025-02-06 19:00 UTC, webkit-commit-queue commented
Committed 289949@main (3a69dff897c1): <https://commits.webkit.org/289949@main>

Reviewed commits have been landed. Closing PR #36909 and removing active labels.

2025-02-06 19:00 UTC, merged