[WebGPUSwift] Swift Implementation of copyTextureToBuffer
WebKit/WebKit pull request #36981
Opened 2024-11-21 23:49 UTC by nmahendru

#### f2bacadca2575d7c12882f4eb2d76a487f5cd578
<pre>
[WebGPUSwift] Swift Implementation of copyTextureToBuffer
<a href="https://rdar.apple.com/140317728">rdar://140317728</a>
<a href="https://bugs.webkit.org/show_bug.cgi?id=283458">https://bugs.webkit.org/show_bug.cgi?id=283458</a>

Reviewed by NOBODY (OOPS!).

1-to-1 replacement of the ObjectiveC version.

roundUpToMultipleOfNonPowerOfTwo had to be specialized as Swift does not support
templates.

Testing: Manual test using:
./LayoutTests/http/tests/webgpu/webgpu/api/operation/command_buffer/image_copy.html

* Source/WebGPU/WebGPU/CommandEncoder.h:
* Source/WebGPU/WebGPU/CommandEncoder.mm:
* Source/WebGPU/WebGPU/CommandEncoder.swift:
(WebGPU.hasValidDimensions(_:width:height:depth:)):
(WebGPU.copyTextureToBuffer(_:destination:copySize:)):
* Source/WebGPU/WebGPU/Internal/WebGPUSwiftInternal.h:
(roundUpToMultipleOfNonPowerOfTwo_CheckedUInt32_UnsignedLongInt):
</pre>
----------------------------------------------------------------------
#### 2dc59d43e4cf319a6930b33764de544bd86ee812
<pre>
WIP
</pre>
----------------------------------------------------------------------
#### 4fb240d224594000caeee8c77ba6a723ebf72cca
<pre>
[WebGPUSwift] Replace copyBufferToTexture with a Swift implementation
<a href="https://bugs.webkit.org/show_bug.cgi?id=281757">https://bugs.webkit.org/show_bug.cgi?id=281757</a>
<a href="https://rdar.apple.com/138188859">rdar://138188859</a>

Reviewed by NOBODY (OOPS!).

The replacement is 1-for-1 but are disabled by default.
One thing which is not the best is that we had to do a lot of Integer
conversions which are always explicit in Swift but implicit in C++.
NSUInteger has been mapped to UInt.

The return values of APIConversions.h::fromAPI are usable in Swift and Swift should
do it&apos;s counting to hold a strong reference until it needs that value. So there is no
need for Ref&lt;Buffer&gt;(apiBuffer) and Ref&lt;Texture&gt;(destinationTexture) as used in the C++ Implementation.

Also a fly by change here is to start using Swift 6 mode. Well not really a fly by but I guess it&apos;s fine.

Some workarounds:
1. Some functions in libpas have been hidden behind __swift__ as they are not supported.
   The side effect is that we have no malloc logging from swift originating calls.
2. There is no equivalent of ASSERT() in swift. Need to work on that in a follow up.

Testing:
Manually ran the test:
./LayoutTests/http/tests/webgpu/webgpu/api/operation/command_buffer/image_copy.html

Combined changes:
* Source/WTF/wtf/CMakeLists.txt:
* Source/WTF/wtf/Ref.h:
(WTF::Ref::get const): Deleted.
* Source/WTF/wtf/RetainReleaseSwift.h:
* Source/WebGPU/Configurations/WebGPU.xcconfig:
* Source/WebGPU/WebGPU/CommandEncoder.h:
* Source/WebGPU/WebGPU/CommandEncoder.mm:
* Source/WebGPU/WebGPU/CommandEncoder.swift:
(CommandEncoder_copyBufferToTexture_thunk(_:source:destination:copySize:)):
(WebGPU.copyBufferToTexture(_:destination:copySize:)):
* Source/WebGPU/WebGPU/Device.h:
(WebGPU::Device::limits const): Deleted.
* Source/WebGPU/WebGPU/Internal/WebGPUSwiftInternal.h:
* Source/WebGPU/WebGPU/Texture.h:
(retainTexture):
(releaseTexture):
* Source/WebGPU/WebGPU/WebGPUExt.h:
* Source/bmalloc/libpas/src/libpas/pas_darwin_spi.h:
* Source/bmalloc/libpas/src/libpas/pas_lock.h:
* Source/bmalloc/libpas/src/libpas/pas_malloc_stack_logging.h:
(pas_msl_malloc_logging):
(pas_msl_free_logging):
</pre>

2024-11-21 23:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f2bacadca2575d7c12882f4eb2d76a487f5cd578. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-11-21 23:59 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/Device.h
> +    const WGPULimits& limits() const SWIFT_RETURNS_INDEPENDENT_VALUE { return m_capabilities.limits; }
But this value isn't independent, right? It's a reference to memory inside this object.

2024-11-22 00:00 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/Texture.h
> +    WTF::retainRefCounted(obj);
WTF::retainRefCounted still needs to be cleaned up. It can just call object->ref(). No need for RELEASE_ASSERT, static_assert, or static_cast.

2024-11-22 00:02 UTC, geoffreygaren commented on Source/bmalloc/libpas/src/libpas/pas_darwin_spi.h
> +// Swift Interop does not allow headers inside extern "C".
This is kind of mysterious. Can we make it less mysterious? What specifically is problematic about including a header inside an extern C block?

2024-11-22 00:03 UTC, geoffreygaren commented on Source/bmalloc/libpas/src/libpas/pas_darwin_spi.h
> +// The side effect is that we don't have malloc logging for calls originating from Swift. Probably fine.
I would just say "// Workaround for rdar://119319825".

2024-11-22 00:05 UTC, geoffreygaren commented on Source/bmalloc/libpas/src/libpas/pas_malloc_stack_logging.h
> +#if PAS_OS(DARWIN) && !defined(__swift__) // FIXME: no malloc_logger for swift. see pas_darwin_spi.h
To be consistent and avoid cluttering all our code with lots of explanation about what's still under development in Swift interop, I would just say "// Workaround for rdar://119319825".

2024-11-22 00:05 UTC, geoffreygaren commented on Source/bmalloc/libpas/src/libpas/pas_malloc_stack_logging.h
> +#if PAS_OS(DARWIN) && !defined(__swift__) // FIXME: no malloc_logger for swift. see pas_darwin_spi.h
Ditto

2024-11-22 00:07 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/CommandEncoder.swift
> +                for layer in 0...copySize.depthOrArrayLayers {
This is off by one. The old code said

`        for (uint32_t layer = 0; layer < copySize.depthOrArrayLayers; ++layer) {`

You need `..<`

2024-11-22 00:07 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/CommandEncoder.swift
> +        for layer in 0...sliceCount {
Off by one

2024-11-22 00:07 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/CommandEncoder.swift
> +                for y in 0...copySize.height {
Off by one

2024-11-22 00:07 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/CommandEncoder.swift
> +        for layer in 0...copySize.depthOrArrayLayers {
Off by one

2024-11-22 00:10 UTC, geoffreygaren commented on Source/bmalloc/libpas/src/libpas/pas_darwin_spi.h
> +// Swift Interop does not allow headers inside extern "C".
One way to be less mysterious is to pair this with a Radar and a workaround comment.

2024-11-22 00:11 UTC, geoffreygaren requested changes
Looks good but I think I found some bugs.

Seems like a good opportunity to check whether this passes or fails regression tests locally.

2024-11-22 00:25 UTC, nmahendru commented on Source/WebGPU/WebGPU/Device.h
> +    const WGPULimits& limits() const SWIFT_RETURNS_INDEPENDENT_VALUE { return m_capabilities.limits; }
It's not. In the current use case the Lifetime of CommandEncoder outlives the Device and it's safe.
I could add another limits which returns `WGPULimits(copy)` and not a reference so that I don't have to add `SWIFT_RETURNS_INDEPENDENT_VALUE`.

2024-11-22 04:43 UTC, rr-codes commented on Source/WebGPU/WebGPU/CommandEncoder.swift
> +                //precondition(false, "ASSERT_NOT_REACHED")
can this just be `assertionFailure`?

2024-11-22 06:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c94eca79073fd57058117c1a4a1d90ab29c05223. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-11-22 19:46 UTC, geoffreygaren commented on Source/WebGPU/WebGPU/Device.h
> +    const WGPULimits& limits() const SWIFT_RETURNS_INDEPENDENT_VALUE { return m_capabilities.limits; }
m_capabilities is a data member of Device, and &m_capabilities.limits is an address inside Device, no?

I’m not sure why it helps that CommandEncoder outlives Device. If CommandEncoder calls this function, and then outlives Device, that’s what creates a risk of use after free. 

In any case, we want to use local reasoning for lifetimes, and locally this annotation is incorrect. The returned value is a pointer into the Device object, so it is not independent.

2024-12-02 17:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8482c0fc5c6d481054827c1ce3cefc49314d53f8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-02 18:28 UTC, geoffreygaren approved these changes
r=me

You can fix the FIXME using assertionFailure().

2024-12-04 02:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a8d327ece4690e2a36d22d3a5b0666a9af38d701. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-04 02:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a4b8042dd0e5752a713e4b4451c4dafb14e25f38. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-04 02:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/972b0f4662e520ed84800326c6c1353efd6778a8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-04 02:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0c75c81c2ad0690501a3055756fa329dc3970e46. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-04 02:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/41868128f5286dd354944b1ead71894899d2e1cc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/36981

2024-12-04 03:12 UTC, webkit-commit-queue commented
Committed 287323@main (0c5b39edcadd): <https://commits.webkit.org/287323@main>

Reviewed commits have been landed. Closing PR #36981 and removing active labels.

2024-12-04 03:12 UTC, merged