fix order of WebCore::TransformationMatrix to SkM44
WebKit/WebKit pull request #37116
Opened 2024-11-25 07:26 UTC by vimerzhao

## Construct SkM44 from TransformationMatrix is wrong 

https://bugs.webkit.org/show_bug.cgi?id=283664

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2024-11-25 07:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c993a67e0cd4273ca1c237da4f944197513c808a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37116

2024-11-25 07:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c993a67e0cd4273ca1c237da4f944197513c808a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37116

2024-11-25 09:34 UTC, nikolaszimmermann requested changes
Thanks for the contribution @vimerzhao and good catch.

You have to regenerate the commit message, it doesn't follow the standard WebKit style: `git webkit pr` should be used, which takes care of it.

And this is lacking a testcase -- we need to assure this doesn't regress in future.
How did you notice the problem? Can you craft a simple testcase, that exposes the problem?

2024-11-26 03:33 UTC, vimerzhao commented
@nikolaszimmermann 
- another pr has been created: https://github.com/WebKit/WebKit/pull/37143
- It seems that there is no platform/graphics/skia test to use as my example
- It Hard to explain why I find this bug. I'm tring to implement a skia render for TextureMapper.

2024-11-26 07:02 UTC, nikolaszimmermann commented
Oh I was talking about a HTML testcase using 3D transforms, not a unit test.

I would be interested to hear about your plan in using Skia for TextureMapper!

2024-11-27 02:27 UTC, vimerzhao commented
Normally, there is no code in WebKit that uses `TransformationMatrix::operator SkM44() const`, as this method was added for the WPE Port.

In my scenario, I want WebKit to run on a low-end device with limited resources and no GPU. Using TextureMapper+ (llvmpipe/swiftshader) would result in very poor performance, approximately 500ms per frame. 

Therefore, I hope to use Skia's SkRasterSurface to accomplish this work and achieve 60fps rendering.

new pr #37143

2026-04-21 12:18 UTC, nikolaszimmermann commented
We have fixed this by now.

2026-04-21 12:18 UTC, closed without merging