[git-webkit] Replace symbols with '-' when converting a bug title to a branch name
WebKit/WebKit pull request #37213
Opened 2024-11-28 05:01 UTC by fujii

#### 308ca45471618ade5fbe55d3ce652d4e3af1e735
<pre>
[git-webkit] Replace symbols with &apos;-&apos; when converting a bug title to a branch name
<a href="https://bugs.webkit.org/show_bug.cgi?id=283781">https://bugs.webkit.org/show_bug.cgi?id=283781</a>

Reviewed by NOBODY (OOPS!).

If a bug title contains &quot;REGRESSION(123@main):&quot;, git-webkit branch
just dropped symbols and converted it to a branch name
&quot;REGRESSION123main&quot;.

Replace symbols with &apos;-&apos;. The above example yields &quot;REGRESSION-123-main&quot;.

* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py:
(Branch.to_branch_name):
* Tools/Scripts/libraries/webkitscmpy/webkitscmpy/test/branch_unittest.py:
</pre>

2024-11-28 05:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/308ca45471618ade5fbe55d3ce652d4e3af1e735. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37213

2024-11-30 12:09 UTC, gsnedders requested changes
Please see my comment below about `re.sub` + `str.strip`, because that would make this simpler to understand.

And, far as I can see, I don't think this is ever used accept when we're creating a new branch, so we can change the behaviour with no concerns about backwards compatibility, so changing this seems safe.

Also, mostly to note for future reference for anyone looking here in the future, looking at https://git-scm.com/docs/git-check-ref-format/2.43.0#_description, the format actually allowed is kinda complicated — while we can certainly be super-aggressive at removing symbols, we could also allow them sometimes.

2024-11-30 12:09 UTC, gsnedders commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py
> +        return string_utils.encode('-'.join(strings), target_type=str)
Is there any reason not to use `re.sub(r'\w+', '-', string_utils.decode(value)).strip('-')`? Rather than the split/join logic, which took me a minute or two to understand (and having to check what exactly `re.split`'s behaviour is), I'd rather we just did that. (`string_utils.encode(..., target_type=str)` is totally redundant at this point, given `str` is always the Python 3 `str` now.)

That said, this also changes `to_branch_name('foo_bar')` from `foo_bar` to `foo-bar`.

2024-11-30 12:21 UTC, fujii commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py
> +        return string_utils.encode('-'.join(strings), target_type=str)
Good idea. Will revise.
We have a test case of `_`. We should keep `_`.

2024-11-30 12:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e74f8c7e8a27da1937729ed6b2639b7dc909cc49. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37213

2024-11-30 12:37 UTC, fujii commented on Tools/Scripts/libraries/webkitscmpy/webkitscmpy/program/branch.py
> +        return string_utils.encode('-'.join(strings), target_type=str)
Fixed.

2024-12-02 20:26 UTC, JonWBedard approved these changes

2024-12-02 20:27 UTC, fujii commented
Thank you for the review.

2024-12-02 20:29 UTC, webkit-commit-queue commented
Committed 287228@main (3f0d9a2960cc): <https://commits.webkit.org/287228@main>

Reviewed commits have been landed. Closing PR #37213 and removing active labels.

2024-12-02 20:29 UTC, merged