Add virtual destructor to StyleRuleBase
WebKit/WebKit pull request #37285
Opened 2024-12-01 05:11 UTC by tuankiet65

#### 73deabe5acac5fad065af86e172124e36bd2db48
<pre>
Add virtual destructor to StyleRuleBase
<a href="https://rdar.apple.com/140739786">rdar://140739786</a>
<a href="https://bugs.webkit.org/show_bug.cgi?id=283864">https://bugs.webkit.org/show_bug.cgi?id=283864</a>

Reviewed by NOBODY (OOPS!).

mac-safer-cpp points out that StyleRuleBase is a base class, yet its
destructor is not virtual.

* Source/WebCore/css/StyleRule.cpp: increase maximum size of StyleRuleBase to
  16 bytes, now that it has to accomodate a pointer to the vtable.
* Source/WebCore/css/StyleRule.h: added virtual destructor to StyleRuleBase.
</pre>

2024-12-01 05:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/73deabe5acac5fad065af86e172124e36bd2db48. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37285

2024-12-01 16:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2dc2d4729ca6cc0aa7887b613482a31d427761f3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37285

2024-12-01 17:07 UTC, weinig commented
StyleRuleBase (along with a few other CSS types) has a bespoke switch-based manner in which it destroys things, done in a manner intended to avoid a v-table. See StyleRuleBase::operator delete for where this happens.

I am not sure this change is the right choice here. Or, it is, we should probably remove the bespoke destruction at the same time.

2024-12-02 06:06 UTC, tuankiet65 commented
> StyleRuleBase (along with a few other CSS types) has a bespoke switch-based manner in which it destroys things, done in a manner intended to avoid a v-table. See StyleRuleBase::operator delete for where this happens.

‼️ 

I didn't notice the `StyleRuleBase::operator delete(StyleRuleBase*, std::destroying_delete_t)` until you mentioned it (also I get to learn about this "destroying delete" feature to eliminate vtables). I suppose that this is safe and well-defined C++ code, but it'll cause the "base class without virtual destructor" false positive, unless we fix the checker to ignore classes with destroying deletes. I'm looking to add a new derived class of `StyleRuleBase`, and I'd have to add a new checker exception for that class, which I guess is undesirable?

2024-12-02 09:33 UTC, mdubet commented
`StyleRuleBase` has no vtable on purpose for memory reason (it does show on benchmark).
We have several other usage of this "manual vtable switch" in the codebase ; if it trips the static analyzer we should rather fix the analyzer :)

2024-12-02 09:34 UTC, mdubet requested changes
Cf comment

2024-12-02 20:07 UTC, tuankiet65 commented
Surprising this shows up in benchmarks, I'll close this then.

2024-12-02 20:07 UTC, closed without merging