Annotate VideoPresentationManagerProxy endpoints with feature flag
WebKit/WebKit pull request #37322
Opened 2024-12-02 17:57 UTC by darryl-apple

#### 1a74fae98646b8291ebc01a3991f11139587426d
<pre>
Annotate VideoPresentationManagerProxy endpoints with feature flag
<a href="https://bugs.webkit.org/show_bug.cgi?id=283916">https://bugs.webkit.org/show_bug.cgi?id=283916</a>
<a href="https://rdar.apple.com/140798582">rdar://140798582</a>

Reviewed by NOBODY (OOPS!).

Annotate VideoPresentationManagerProxy endpoints with feature flag

* Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.messages.in:
</pre>

2024-12-04 21:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e584a3a3075e37a25d4adb594bcb5c644b1ba0d4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-05 12:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/56ee0154856b23ff608271169bf33e08e6a8b35f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-06 16:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b9c1da7c7caa5cbfdb99273534f49649f941a091. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-06 20:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d92f33c7b32f85bf86020b42dde73c57b5c68113. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-09 19:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/148ad03a1b936965865123a14aaced06a47cc7f3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-10 11:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0696fd1865d0f853840ac9941c2945c179f5d0c7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-10 14:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ee88223241c6782cdc8817166a1db6817dcd443e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-12 15:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/026b26cb6a914d345b47c1083e060b56d5e532c2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-16 20:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad6ffd9c0da51535c9471b2601b3bf205c328872. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-17 18:44 UTC, aestes commented
I don't think this is correct on visionOS, where `VideoPresentationModeAPIEnabled` is off but `VideoPresentationManagerProxy` is still used.

2024-12-17 18:45 UTC, aestes requested changes
I don't think this is correct on visionOS, where `VideoPresentationModeAPIEnabled` is off but `VideoPresentationManagerProxy` is still used.

2024-12-17 22:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dc79a8255a279537de67d01e27f8fede7bdab984. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-18 11:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/026138bb29665de8ef77d217b6df27d8a6538020. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2024-12-18 16:17 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/7f13e831a0e70fd421991c6672c5cf4dd3d9041c)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/81688 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/1213 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/86229 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/1244 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/9032 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/86229 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/1244 "Build is in progress. Recent messages:") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/86229 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/1244 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/31133 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/1244 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/87667 "Build is in progress. Recent messages:Running configuration") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/8925 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/9032 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/87667 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/9109 "Build is in progress. Recent messages:Running configuration") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/87667 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-intel-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/103153 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/8877 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/35/builds/103153 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv-sim](https://ews-build.webkit.org/#/builders/125/builds/8717 "Build is in progress. Recent messages:") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/129/builds/12238 "Build is in progress. Recent messages:") | | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/124/builds/10526 "Build is in progress. Recent messages:") | | | </details>

2024-12-20 23:15 UTC, aestes requested changes
Instead of duplicating the message signatures, can we instead add a new preference (in UnifiedWebPreferences.yaml) that is enabled on visionOS, then do `EnabledBy = VideoPresentationModeAPIEnabled || NewFeatureEnabled`?

2024-12-23 12:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5d232fa0a8e6927f4bcfb1f096bb3683e8e0463. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-02 12:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0af65c1948df903fec229c45af2ce07d34928ab9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-02 12:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0af65c1948df903fec229c45af2ce07d34928ab9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-07 19:01 UTC, aestes approved these changes
r=me with a nit and a question.

2025-01-07 19:01 UTC, aestes commented on Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
> +SpatialVideoFullscreenEnabled:
Nit: spatial video has a specific meaning on visionOS (stereoscopic video), but VideoPresentationManagerProxy is used for monoscopic video as well on visionOS. Perhaps a better name would be `VideoPresentationManagerEnabled`.

2025-01-07 19:01 UTC, aestes commented on Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.messages.in
> -    DispatchedTo=UI
Just confirming that you intended to remove `DispatchedFrom` and `DispatchedTo`.

2025-01-08 10:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c79c0fb7c20e1bab5a905f1b43f3db53fd51dcb5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-08 10:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fe3ac5e0b788173541ec2759c834eef6dae0036a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-08 10:51 UTC, darryl-apple commented on Source/WebKit/UIProcess/Cocoa/VideoPresentationManagerProxy.messages.in
> -    DispatchedTo=UI
I did not, thanks for flagging. Fixed

2025-01-08 10:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/aed9aeb5f38c8aadefba7d5154eb116cade6eac5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37322

2025-01-09 11:57 UTC, webkit-commit-queue commented
Committed 288653@main (19b4684c588f): <https://commits.webkit.org/288653@main>

Reviewed commits have been landed. Closing PR #37322 and removing active labels.

2025-01-09 11:57 UTC, merged