Convert two external paintserver tests in svg/custom/ to reftests
WebKit/WebKit pull request #37753
Opened 2024-12-11 02:16 UTC by Ahmad-S792

#### 49f1659510626e6f6b61b7ba5ff581e669343e00
<pre>
Convert two external paintserver tests in svg/custom/ to reftests

<a href="https://bugs.webkit.org/show_bug.cgi?id=284430">https://bugs.webkit.org/show_bug.cgi?id=284430</a>
<a href="https://rdar.apple.com/141255575">rdar://141255575</a>

Reviewed by NOBODY (OOPS!).

Merge: <a href="https://source.chromium.org/chromium/chromium/src/+/6bfac6ae76afebd09ad6f141205b22643d7566a1">https://source.chromium.org/chromium/chromium/src/+/6bfac6ae76afebd09ad6f141205b22643d7566a1</a>

This patch is to make these two tests reftest.

* LayoutTests/platform/gtk/svg/custom/external-paintserver-reference-expected.png: Removed.
* LayoutTests/platform/gtk/svg/custom/uri-reference-handling-expected.png: Removed.
* LayoutTests/platform/mac-sonoma-wk2-lbse-text/svg/custom/external-paintserver-reference-expected.png: Removed.
* LayoutTests/platform/mac-sonoma-wk2-lbse-text/svg/custom/external-paintserver-reference-expected.txt: Removed.
* LayoutTests/platform/mac-sonoma-wk2-lbse-text/svg/custom/uri-reference-handling-expected.txt: Removed.
* LayoutTests/platform/mac-sonoma-wk2-pixel/svg/custom/external-paintserver-reference-expected.png: Removed.
* LayoutTests/platform/mac-sonoma-wk2-pixel/svg/custom/uri-reference-handling-expected.png: Removed.
* LayoutTests/platform/mac/svg/custom/external-paintserver-reference-expected.png: Removed.
* LayoutTests/platform/mac/svg/custom/uri-reference-handling-expected.png: Removed.
* LayoutTests/svg/custom/external-paintserver-reference-expected.txt: Removed.
* LayoutTests/svg/custom/uri-reference-handling-expected.png: Removed.
* LayoutTests/svg/custom/uri-reference-handling-expected.txt: Removed.
* LayoutTests/svg/custom/external-paintserver-reference-expected.svg:
* LayoutTests/svg/custom/uri-reference-handling-expected.svg:
</pre>

2024-12-11 02:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/49f1659510626e6f6b61b7ba5ff581e669343e00. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37753

2025-02-15 05:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/314cfcb157fa4043b9f85380646a524b8f4a04b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37753

2025-03-06 21:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7e784b46cd017af2edd5cafc53a5595210f4dc1b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37753

2025-03-07 01:51 UTC, Ahmad-S792 commented
`[gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/80630)` is flaky failure in View Transition test case - see it quite often on many PRs.

2025-03-07 07:22 UTC, annevk requested changes

2025-03-07 07:22 UTC, annevk commented on LayoutTests/svg/custom/uri-reference-handling.svg
> +<meta name="fuzzy" content="maxDifference=1; totalPixels=0-2157" />
This hides regressions on certain platforms. E.g., the Skia rendering is currently as expected, but if it regresses we wouldn't catch that now.

2025-03-07 07:35 UTC, Ahmad-S792 commented on LayoutTests/svg/custom/uri-reference-handling.svg
> +<meta name="fuzzy" content="maxDifference=1; totalPixels=0-2157" />
It is gradient noise - which WebKit adds (due to fingerprinting) and it leads to 1px differences and we fail some WPT due to it as well. See below, it is noise rather than regression and it is just 1px tolerance, so I don't agree that it is regression.

<img width="810" alt="image" src="https://github.com/user-attachments/assets/5e97833f-2832-4df8-9f7d-2217081ff28d" />

2025-03-07 07:43 UTC, karlcow commented on LayoutTests/svg/custom/uri-reference-handling.svg
> +<meta name="fuzzy" content="maxDifference=1; totalPixels=0-2157" />
Yes there are plenty of WPT gradient tests failing because of this noise. 
Where fuzziness should be added.

2025-03-07 07:44 UTC, annevk commented on LayoutTests/svg/custom/uri-reference-handling.svg
> +<meta name="fuzzy" content="maxDifference=1; totalPixels=0-2157" />
I thought we only added such noise to canvas?

2025-03-07 07:46 UTC, Ahmad-S792 commented on LayoutTests/svg/custom/uri-reference-handling.svg
> +<meta name="fuzzy" content="maxDifference=1; totalPixels=0-2157" />
We definitely do it to gradients as well.

2025-12-15 05:12 UTC, Ahmad-S792 commented
@annevk - Can you review it so we can merge it?

2025-12-16 07:18 UTC, annevk commented on LayoutTests/svg/custom/external-paintserver-reference-expected.svg
> +<html xmlns="http://www.w3.org/1999/xhtml" style="height:100%"/>
I don't understand how this can be a valid reference given that `LayoutTests/svg/custom/external-paintserver-reference-expected.txt` lists a variety of colors that are no longer mentioned here.

2026-07-01 21:45 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/03f6b214391e997ceb5d9f0d67b6f37b95ca6f9e)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/172044 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/45961 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/168/builds/39379 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/181484 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/129598 "Built successfully") | [✅ 🛠 ios-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/edf50359-fa40-44ef-9f57-f0ead5008427) 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/47248 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/156/builds/45601 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/133829 "Passed tests") | [  ~~🧪 win-tests~~](https://ews-build.webkit.org/#/builders/60/builds/94404 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 mac-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/70ef17cf-8c2a-4b4a-a7c6-22958add0b9c) 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/175002 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/162/builds/37243 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/154354 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/114302 "Passed tests") | | [✅ 🛠 vision-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/1d18e587-dbd1-4999-8138-bf58fd49f8d1) 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/154/builds/35874 "Passed tests") | [✅ 🧪 api-mac-debug](https://ews-build.webkit.org/#/builders/165/builds/34138 "Passed tests") | [✅ 🛠 gtk3-libwebrtc](https://ews-build.webkit.org/#/builders/173/builds/30097 "Built successfully") | | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/146300 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/169/builds/33865 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/184016 "Built successfully") | | 
| | | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/161/builds/38336 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/142564 "Passed tests") | | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/45628 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/153945 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/142453 "Passed tests") | | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/46308 "Built successfully") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/170/builds/30710 "Passed tests") | [✅ 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/110971 "Built successfully") | | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/164/builds/37545 "Passed tests") | | | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/158/builds/44826 "Built successfully") | [✅ 🧪 mac-site-isolation](https://ews-build.webkit.org/#/builders/185/builds/8804 "Passed tests") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/157/builds/44226 "Built successfully") | | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/163/builds/44458 "Built successfully") | | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/152/builds/44285 "Built successfully") | | | | </details>

2026-07-01 21:50 UTC, nullhook commented
Looking at `NoiseInjectionPolicy` I only see canvas that's effected. However, the pixel diff here looks like dithering which makes it look like noise. 

I'm looking into this...

2026-07-02 16:53 UTC, nullhook commented
After looking more into this I've observed that the CG backend adds dithering to gradients to avoid banding, and here we're comparing a gradient against a solid color, which is the mismatch. If we convert the reference to paint those rects with the same gradient instead, the dither should cancel out. Perhaps, we can get to the same gradient paint from a different path. 

Overall we should have these tests as it exercises the paint-server painting path and lets us delete a pile of per-platform render tree dumps.

2026-07-02 17:15 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/907f47e49b087f5daca39fdd901698bfd599f6b7)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/172242 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/46160 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/168/builds/39588 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/181693 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/129798 "Built successfully") | [✅ 🛠 ios-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/2b9bc0c5-eb05-4004-8f63-492a53f025b6) 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/47453 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/156/builds/45802 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/133968 "Passed tests") | [  ~~🧪 win-tests~~](https://ews-build.webkit.org/#/builders/60/builds/94511 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | ⏳ 🛠 mac-apple 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/175200 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/162/builds/37399 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/154516 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/114439 "Passed tests") | | [✅ 🛠 vision-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/298ccc7a-044c-433d-ad24-3f0808ef53cb) 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/154/builds/36033 "Passed tests") | [  ~~🧪 api-mac-debug~~](https://ews-build.webkit.org/#/builders/165/builds/34301 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 gtk3-libwebrtc](https://ews-build.webkit.org/#/builders/173/builds/30299 "Built successfully") | | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/146463 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/169/builds/34027 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/184227 "Built successfully") | | 
| | | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/161/builds/38503 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/142732 "Passed tests") | | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/45832 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/154099 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/142612 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/38504 "Built successfully and passed tests") | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/46510 "Built successfully") | [  ~~🧪 mac-intel-wk2~~](https://ews-build.webkit.org/#/builders/170/builds/30868 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/111224 "Built successfully") | | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/164/builds/37685 "Passed tests") | | | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/158/builds/45027 "Built successfully") | [❌ 🧪 mac-site-isolation](https://ews-build.webkit.org/#/builders/185/builds/8967 "") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/157/builds/44427 "Built successfully") | | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/163/builds/44659 "Built successfully") | | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/152/builds/44486 "Built successfully") | | | | </details>

2026-07-02 17:16 UTC, nullhook approved these changes

2026-07-02 20:59 UTC, webkit-commit-queue commented
Committed 316417@main (f8806ab8f6fe): <https://commits.webkit.org/316417@main>

Reviewed commits have been landed. Closing PR #37753 and removing active labels.

2026-07-02 20:59 UTC, merged