[css-anchor-position-1] Implement anchor name encapsulation within shadow trees
WebKit/WebKit pull request #37826
Opened 2024-12-12 09:52 UTC by Scony

#### f3a7007a00c6ced3e77350cbaf398b43d7c170e5
<pre>
[css-anchor-position-1] Implement anchor name encapsulation within shadow trees
<a href="https://bugs.webkit.org/show_bug.cgi?id=281963">https://bugs.webkit.org/show_bug.cgi?id=281963</a>

Reviewed by NOBODY (OOPS!).

This change makes anchor names encapsulated within shadow trees as specified in:
<a href="https://drafts.csswg.org/css-anchor-position-1/#target">https://drafts.csswg.org/css-anchor-position-1/#target</a>

Effectively, this change spreads the data (originally stored only in AnchorPositionedStates
of Document&apos;s Style::Scope) across all the Style::Scopes - including ones of shadow trees.
The above means that the anchor names defined by styles in one shadow tree won’t be seen
by anchor functions in styles in a different shadow tree.

This change leaves the &apos;::part()&apos; code path not implemented as it requires different kind of
changes all across the anchoring code. Namely, any reference to AnchorPositionedStates will
have to be done in the context of particular Style::Scope that is applicable due to certain
part being used. This in turn may require major refactoring. Therefore this part is left
for a follow-up.

* LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-name-cross-shadow-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-name-in-shadow-002-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-name-in-shadow-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-scope-shadow-flat-tree-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-anchor-position/anchor-transition-002-expected.txt:
* Source/WebCore/dom/Document.cpp:
(WebCore::Document::resolveStyle):
* Source/WebCore/rendering/RenderElement.cpp:
(WebCore::RenderElement::defaultAnchor const):
* Source/WebCore/style/AnchorPositionEvaluator.cpp:
(WebCore::Style::AnchorPositionEvaluator::findAnchorAndAttemptResolution):
(WebCore::Style::isAcceptableAnchorElement):
(WebCore::Style::AnchorPositionEvaluator::updateAnchorPositioningStatesAfterInterleavedLayout):
(WebCore::Style::AnchorPositionEvaluator::updateSnapshottedScrollOffsets):
(WebCore::Style::AnchorPositionEvaluator::visitAllAnchorPositionedStates):
(WebCore::Style::AnchorPositionEvaluator::cleanupAnchorPositionedState): Deleted.
* Source/WebCore/style/AnchorPositionEvaluator.h:
* Source/WebCore/style/MatchedDeclarationsCache.cpp:
(WebCore::Style::MatchedDeclarationsCache::isCacheable):
* Source/WebCore/style/StyleSharingResolver.cpp:
(WebCore::Style::SharingResolver::canShareStyleWithElement const):
* Source/WebCore/style/StyleTreeResolver.cpp:
(WebCore::Style::TreeResolver::resolve):
(WebCore::Style::TreeResolver::updateAnchorPositioningState):
</pre>

2024-12-12 09:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f3a7007a00c6ced3e77350cbaf398b43d7c170e5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2024-12-12 10:11 UTC, nt1m commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +    if (&Style::Scope::forNode(*static_cast<const RenderObject&>(anchorRenderer).node()) != &Style::Scope::forNode(anchorPositionedElement))
Why the static cast?

2024-12-13 15:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ac5c684d248e9326ec14b7f84f17ec8700f17a8f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2024-12-16 09:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/aafff017f79b0a535bdab8edb8c0b970c7542e4a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2024-12-16 09:44 UTC, nt1m commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +    visitAllAnchorPositionedStates(document, [&document](AnchorPositionedStates& states) {
```suggestion
    visitAllAnchorPositionedStates(document, [&document](auto& states) {
```

2024-12-16 09:44 UTC, nt1m commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +    visitAllAnchorPositionedStates(document, [](AnchorPositionedStates& states) {
ditto

2024-12-16 09:44 UTC, nt1m commented on Source/WebCore/style/StyleTreeResolver.cpp
> +        AnchorPositionEvaluator::visitAllAnchorPositionedStates(m_document.get(), [](AnchorPositionedStates& states) {
ditto

2024-12-16 16:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6a782ae7c7ec6b123702a10e50b2a467edfe44b1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2025-01-29 14:00 UTC, anttijk requested changes

2025-01-29 14:00 UTC, anttijk commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +
This is equivalent to `anchorElement.containingShadowRoot() != anchorPositionedElement.containingShadowRoot()` I think. 

It does not look correct though, the spec says 

> However, elements in different shadow trees can still anchor to each other, so long as both the anchor-name and anchor function come from styles in the same tree, such as by using [::part()](https://drafts.csswg.org/css-shadow-parts-1/#selectordef-part) to style an element inside a shadow.

We should be making name lookup taking the scope ordinary in ScopedName into account.

This looks like a substantive change it itself. Can you do it first separately?

2025-01-29 14:00 UTC, anttijk commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +    visitAllAnchorPositionedStates(document, [&document](auto& states) {
Can you explain what moving the anchor positioned element map to individual style scopes achieves concretely?

2025-02-13 13:01 UTC, Scony commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +    visitAllAnchorPositionedStates(document, [&document](auto& states) {
It basically introduces a true isolation of anchoring-related data. This way it's possible e.g. to have same anchor names in unrelated shadow trees and not run into conflicts.

In my mind, such separation was the easiest first step to have basic shadow tree isolation working with our current implementation without introducing any substantial refactoring or implementing support for shadow parts at the same time.

2025-02-13 13:03 UTC, Scony commented on Source/WebCore/style/AnchorPositionEvaluator.cpp
> +
I don't know much about CSS Shadow Parts - can you elaborate what do you mean by _"We should be making name lookup taking the scope ordinary in ScopedName into account."_ ?

2025-02-13 13:05 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/eaa5b0bad5780a02dd82222e186d1d292e07a706)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/89728 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/9255 "Build is in progress. Recent messages:OS: Sequoia (15.2), Xcode: 16.2") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/94721 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/40495 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/91780 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/9644 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/17534 "Build is in progress. Recent messages:OS: Sequoia (15.3), Xcode: 16.2") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/94721 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 win-tests](https://ews-build.webkit.org/#/builders/59/builds/40495 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/92729 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/9644 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/94721 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/9644 "Build is in progress. Recent messages:OS: Sequoia (15.2), Xcode: 16.2") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/39629 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/9644 "Build is in progress. Recent messages:OS: Sequoia (15.2), Xcode: 16.2") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/96548 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/128/builds/16910 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/17534 "Build is in progress. Recent messages:OS: Sequoia (15.3), Xcode: 16.2") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/96548 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/17166 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/96548 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/44608 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/10082 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/127/builds/16923 "Build is in progress. Recent messages:OS: Sequoia (15.2), Xcode: 16.2") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/110996 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6- [...]

2025-02-27 13:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1c9f839cd5c624c3954b8425af542475bc8a9f5d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2025-03-10 11:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/10a898c7b0a5fe09f87a2d544bbf5060a08af7bd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2025-03-21 14:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bffa46700a43cc1d8073fe9fc3b6a21ce927510e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2025-03-26 12:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/30aac5e2e9c0f97aef399d2bab34a3b87505d831. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/37826

2025-05-23 00:56 UTC, tuankiet65 commented
I have a different solution to this problem (#45803): each anchor is uniquely identified by its anchor name and which Scope object it belongs to 🤔 . This way, we don't have to spread the `AnchorPositionedStates` across multiple Scope objects

2025-05-23 08:13 UTC, Scony commented
> I have a different solution to this problem (#45803): each anchor is uniquely identified by its anchor name and which Scope object it belongs to 🤔 . This way, we don't have to spread the `AnchorPositionedStates` across multiple Scope objects

Sounds like a very good idea. I haven't thought about such an approach. Let me take a look then.

2025-05-28 09:02 UTC, Scony commented
Superseded by https://github.com/WebKit/WebKit/pull/45803

2025-05-28 09:02 UTC, closed without merging