Remove unneeded permissions cache in WebPermissionController
WebKit/WebKit pull request #3783
Opened 2022-08-29 21:28 UTC by RupinMittal

#### 72505f1e160bd2554a7ba84c291c9d6af307992b
<pre>
Remove unneeded permissions cache in WebPermissionController
<a href="https://bugs.webkit.org/show_bug.cgi?id=244514">https://bugs.webkit.org/show_bug.cgi?id=244514</a>

Reviewed by NOBODY (OOPS!).

The &quot;m_cachedPermissionEntries&quot; permissions cache is currently not in use.
Since the eventual goal is to implement the on-change even for the
Permissions API, this cache won&apos;t be needed at all.

* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::queryPermission):
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/UIProcess/WebPermissionControllerProxy.cpp:
(WebKit::WebPermissionControllerProxy::query):
* Source/WebKit/UIProcess/WebPermissionControllerProxy.h:
* Source/WebKit/UIProcess/WebPermissionControllerProxy.messages.in:
* Source/WebKit/WebProcess/WebCoreSupport/WebPermissionController.cpp:
(WebKit::WebPermissionController::query):
(WebKit::WebPermissionController::tryProcessingRequests):
(WebKit::WebPermissionController::queryCache): Deleted.
(WebKit::WebPermissionController::updateCache): Deleted.
* Source/WebKit/WebProcess/WebCoreSupport/WebPermissionController.h:
</pre>

2022-08-29 21:28 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/72505f1e160bd2554a7ba84c291c9d6af307992b

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/87495 "Build is in progress") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/29948 "Build is in progress") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/29948 "Build is in progress") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/29948 "Build is in progress") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/86580 "Build is in progress") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-8-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/75843 "Build is in progress") | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-8-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/37/builds/75843 "Build is in progress") |

2022-08-29 21:33 UTC, cdumez requested changes
I don't understand this change. I don't see any reason not to have a cache? It avoids IPC in the case where the WebProcess already knows the answer. The only thing missing to make this cache work is clearing the cache once permissions have changed, which will be trivial when we implement the change event.

Note that in the Notification.permission cache, the cache is even more useful since it'd avoid a sync IPC.

2022-08-29 21:40 UTC, cdumez reviewed
I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.

2022-08-29 21:48 UTC, szewai commented
> I don't understand this change. I don't see any reason not to have a cache? It avoids IPC in the case where the WebProcess already knows the answer. The only thing missing to make this cache work is clearing the cache once permissions have changed, which will be trivial when we implement the change event.
> 
> Note that in the Notification.permission cache, the cache is even more useful since it'd avoid a sync IPC.

The reason we don't need this cache is that we may use m_observers as cache.
I think the map cache is not going to be used anyways because it does not consider the case that different pages/contexts can have different permissions; we can add a more appropriate cache when we implement change event if needed.

2022-08-29 21:58 UTC, szewai commented
> I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.

Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
1. drop the not-working cache
2. implement change event and PermissionObserver (a working cache)
3. implement Notification.permission with PermissionController

2022-08-29 22:03 UTC, cdumez commented
> > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> 
> Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:

Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?

2022-08-29 22:07 UTC, szewai commented
> > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > 
> > 
> > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> 
> Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?

We can make Notification own a PermissionObserver more precisely, like creating one PermissionObserver when Notification.permission is called

2022-08-29 22:09 UTC, cdumez commented
> > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > 
> > 
> > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> 
> Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?


> > > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > > 
> > > 
> > > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> > 
> > 
> > Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?
> 
> We can make Notification own a PermissionObserver more precisely, like creating one PermissionObserver when Notification.permission is called

I don't understand this comment. There is no Notification instance when you call Notification.permission(), since it is static.

2022-08-29 22:14 UTC, szewai commented
> > > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > > 
> > > 
> > > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> > 
> > 
> > Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?
> 
> > > > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > > > 
> > > > 
> > > > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> > > 
> > > 
> > > Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?
> > 
> > 
> > We can make Notification own a PermissionObserver more precisely, like creating one PermissionObserver when Notification.permission is called
> 
> I don't understand this comment. There is no Notification instance when you call Notification.permission(), since it is static.

Sorry I think it's WebNotificationClient (or whoever currently holds the cache)

2022-08-29 22:17 UTC, cdumez commented
> WebNotificationClient



> > > > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > > > 
> > > > 
> > > > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> > > 
> > > 
> > > Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?
> > 
> > 
> > > > > > I'm not opposed to dropping the cache but I don't really understand the decision. Also Rupin has another patch up for review which seems to rely quite a bit on this cache so it is a bit confusing.
> > > > > 
> > > > > 
> > > > > Since that patch relies on a functional cache in web process (otherwise gtk tests fail), I suggested that Rupin implements the change event first, and make Notification a PermissionObserver, so the ordering is:
> > > > 
> > > > 
> > > > Note that Notification.permission() is a static function so the observer would have to be a global static it seems. Does this mean every WebProcess would always have a permission observer for Notification? Would that happen only the first time that the WebProcess uses Notifications (or Notification.permission)?
> > > 
> > > 
> > > We can make Notification own a PermissionObserver more precisely, like creating one PermissionObserver when Notification.permission is called
> > 
> > 
> > I don't understand this comment. There is no Notification instance when you call Notification.permission(), since it is static.
> 
> Sorry I think it's WebNotificationClient (or whoever currently holds the cache)

Oh I see. Yes, I think WebNotificationClient would make sense indeed. Ok. Let's go for your plan.

2022-08-29 22:32 UTC, szewai approved these changes
r=me if Chris and EWS bots are happy

2022-08-29 22:33 UTC, cdumez approved these changes
Sure, assuming the bots are happy.

2022-08-30 17:02 UTC, closed without merging

2022-08-30 17:02 UTC, webkit-commit-queue commented
Committed 253950@main (71edab7c9f26): <https://commits.webkit.org/253950@main>

Reviewed commits have been landed. Closing PR #3783 and removing active labels.