Range.getClientRects should take surrogate pairs into account
WebKit/WebKit pull request #38267
Opened 2024-12-20 16:20 UTC by rwlbuis

#### a7f56d6ad9556481aae6aebc3de8c889aa57d587
<pre>
Range.getClientRects should take surrogate pairs into account
<a href="https://bugs.webkit.org/show_bug.cgi?id=285023">https://bugs.webkit.org/show_bug.cgi?id=285023</a>

Reviewed by NOBODY (OOPS!).

WIP.

* Source/WebCore/rendering/RenderObject.cpp:
(WebCore::absoluteRectsForRangeInText):
</pre>

2024-12-20 16:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a7f56d6ad9556481aae6aebc3de8c889aa57d587. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2024-12-20 18:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f384a5d0efc518e4c3ec140a1cbed87990c74ac5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2024-12-22 15:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/429982cb874d51d4f7fa10e605deeb27ed4053c6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2025-01-05 17:06 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.start]) && offsetRange.start > 0 && U16_IS_LEAD(node.data()[offsetRange.start - 1]))
Nit: offsetRange.start > 0 -> offsetRange.start

2025-01-05 17:06 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end > 0 && U16_IS_LEAD(node.data()[offsetRange.end - 1]))
Ditto.

2025-01-05 17:10 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end > 0 && U16_IS_LEAD(node.data()[offsetRange.end - 1]))
How does this make sense? Should this be checking U16_IS_LEAD on offsetRange.end and U16_IS_TRAIL on offsetRange.end + 1?

2025-01-06 11:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eaace38cfab364c452629bcdc943b73b0096724d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2025-01-06 15:27 UTC, rwlbuis commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.start]) && offsetRange.start > 0 && U16_IS_LEAD(node.data()[offsetRange.start - 1]))
Fixed.

2025-01-06 15:30 UTC, rwlbuis commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end > 0 && U16_IS_LEAD(node.data()[offsetRange.end - 1]))
I think that is the correct behaviour when taking into account what the spec text says:
"If the range covers a partial [typographic character unit](https://drafts.csswg.org/css-text-4/#typographic-character-unit) (e.g. half a surrogate pair or part of a grapheme cluster), the full typographic character unit must be included for the purpose of computing the bounds of the relevant [DOMRect](https://drafts.fxtf.org/geometry-1/#domrect)." So the complete surrogate pair would need to be included both at the start and end of the range.

2025-01-07 04:28 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end > 0 && U16_IS_LEAD(node.data()[offsetRange.end - 1]))
I get that the desired effect. What I don't think right is the code in PR:
```
U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end && U16_IS_LEAD(node.data()[offsetRange.end - 1])
```

Oh right, `node.data()[offsetRange.end]` grabs the character after the end, not the one before it. But I think we still need to also check that `offsetRange.end` is less than node.date()'s length. Otherwise, we can end up reading past the end of the buffer.

2025-01-07 10:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6a37138dc84d5e2aa6a4daf59e541ba8f490ab46. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2025-01-07 11:19 UTC, rwlbuis commented on Source/WebCore/rendering/RenderObject.cpp
> +    if (U16_IS_TRAIL(node.data()[offsetRange.end]) && offsetRange.end > 0 && U16_IS_LEAD(node.data()[offsetRange.end - 1]))
I checked, an exception is thrown when a start/end offset is set on the DOM level. However, for some added security I added two ASSERTS checking both start and end offset values.

2025-01-07 13:24 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    ASSERT(offsetRange.start < node.data().length());
I don't think this assertion makes sense. It's totally possible for the start to be the end of a text node:
e.g.
```js
document.body.innerHTML = 'hello';
r = document.createRange();
r.setStart(document.body.firstChild, 5);
```

2025-01-07 13:25 UTC, rniwa commented on Source/WebCore/rendering/RenderObject.cpp
> +    ASSERT(offsetRange.end < node.data().length());
Ditto. Also, we need to clamp the end at the actual end of the current node since characterDataOffsetRange will return `std::numeric_limits<unsigned>::max()` when the node isn't the end container.

2025-01-07 13:26 UTC, rniwa requested changes
I don't think we can land this as is.

2025-01-07 16:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c9b9ba773fcd66599de8fa78a19ee307ee5e1549. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2025-01-07 16:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e77ee3f86e3655b03127b8d21660cc7299d1e5e4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38267

2025-01-07 22:25 UTC, rwlbuis commented on Source/WebCore/rendering/RenderObject.cpp
> +    ASSERT(offsetRange.start < node.data().length());
Thanks for pointing that out.

2025-01-07 22:28 UTC, rwlbuis commented on Source/WebCore/rendering/RenderObject.cpp
> +    ASSERT(offsetRange.end < node.data().length());
I think we can avoid doing anything at the very start and end of ranges as we are testing for the case where we are indexing into the surrogate pair, so also no need to clamp.
I added a subtest where the range consists of a different start and end text container to test the case where std::numeric_limits<unsigned>::max() is returned.

2025-01-07 23:14 UTC, rniwa approved these changes

2025-01-08 09:52 UTC, webkit-commit-queue commented
Committed 288589@main (7d8be0b05d9e): <https://commits.webkit.org/288589@main>

Reviewed commits have been landed. Closing PR #38267 and removing active labels.

2025-01-08 09:52 UTC, merged