WebTransport should send network errors to JS for failure points
WebKit/WebKit pull request #38327
Opened 2024-12-23 01:20 UTC by AnkshitJain

#### 72c7db032a68f98c447dee4c34629e6d6036283e
<pre>
WebTransport should send network errors to JS for failure points
<a href="https://bugs.webkit.org/show_bug.cgi?id=285087">https://bugs.webkit.org/show_bug.cgi?id=285087</a>
<a href="https://rdar.apple.com/136263051">rdar://136263051</a>

Reviewed by NOBODY (OOPS!).

Network connections are canceled when the session is terminated.
Streams handle completion and error for reads and writes.
Incoming connections are canceled if the incoming streams reader is closed.

* Source/WebCore/Modules/streams/ReadableStreamSource.h:
* Source/WebCore/Modules/webtransport/DatagramSink.cpp:
(WebCore::DatagramSink::write):
(WebCore::DatagramSink::send):
* Source/WebCore/Modules/webtransport/DatagramSink.h:
* Source/WebCore/Modules/webtransport/DatagramSource.cpp:
(WebCore::DatagramSource::receiveDatagram):
(WebCore::DatagramSource::doCancel):
* Source/WebCore/Modules/webtransport/DatagramSource.h:
* Source/WebCore/Modules/webtransport/WebTransport.cpp:
(WebCore::WebTransport::receiveDatagram):
(WebCore::WebTransport::receiveIncomingUnidirectionalStream):
(WebCore::WebTransport::receiveBidirectionalStream):
* Source/WebCore/Modules/webtransport/WebTransport.h:
* Source/WebCore/Modules/webtransport/WebTransportBidirectionalStreamSource.cpp:
(WebCore::WebTransportBidirectionalStreamSource::receiveIncomingStream):
* Source/WebCore/Modules/webtransport/WebTransportBidirectionalStreamSource.h:
* Source/WebCore/Modules/webtransport/WebTransportReceiveStreamSource.cpp:
(WebCore::WebTransportReceiveStreamSource::receiveIncomingStream):
* Source/WebCore/Modules/webtransport/WebTransportReceiveStreamSource.h:
* Source/WebCore/Modules/webtransport/WebTransportSession.h:
* Source/WebCore/Modules/webtransport/WebTransportSessionClient.h:
* Source/WebCore/PAL/pal/cocoa/NetworkSoftLink.h:
* Source/WebCore/PAL/pal/cocoa/NetworkSoftLink.mm:
* Source/WebCore/PAL/pal/spi/cocoa/NetworkSPI.h:
* Source/WebCore/bindings/js/ReadableStreamDefaultController.h:
* Source/WebKit/NetworkProcess/webtransport/NetworkTransportSession.cpp:
(WebKit::NetworkTransportSession::sendDatagram):
(WebKit::NetworkTransportSession::streamSendBytes):
(WebKit::NetworkTransportSession::terminate):
(WebKit::NetworkTransportSession::receiveDatagram):
(WebKit::NetworkTransportSession::streamReceiveBytes):
(WebKit::NetworkTransportSession::receiveIncomingUnidirectionalStream):
(WebKit::NetworkTransportSession::receiveBidirectionalStream):
(WebKit::NetworkTransportSession::cancelReceiveStream):
(WebKit::NetworkTransportSession::cancelSendStream):
(WebKit::NetworkTransportSession::destroyStream):
(WebKit::NetworkTransportSession::sendStreamSendBytes): Deleted.
(WebKit::NetworkTransportSession::destroyOutgoingUnidirectionalStream): Deleted.
(WebKit::NetworkTransportSession::destroyBidirectionalStream): Deleted.
* Source/WebKit/NetworkProcess/webtransport/NetworkTransportSession.h:
* Source/WebKit/NetworkProcess/webtransport/NetworkTransportSession.messages.in:
* Source/WebKit/NetworkProcess/webtransport/NetworkTransportStream.cpp:
(WebKit::NetworkTransportStream::NetworkTransportStream):
(WebKit::NetworkTransportStream::sendBytes):
(WebKit::NetworkTransportStream::cancelReceive):
(WebKit::NetworkTransportStream::cancelSend):
(WebKit::NetworkTransportStream::cancel):
* Source/WebKit/NetworkProcess/webtransport/NetworkTransportStream.h:
* Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm:
(WebKit::NetworkTransportSession::initialize):
(WebKit::NetworkTransportSession::setupDatagramConnection):
(WebKit::NetworkTransportSession::sendDatagram):
(WebKit::NetworkTransportSession::setupConnectionHandler):
(WebKit::NetworkTransportSession::createStream):
(WebKit::NetworkTransportSession::receiveDatagramLoop):
(WebKit::NetworkTransportSession::terminate):
* Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm:
(WebKit::NetworkTransportStream::NetworkTransportStream):
(WebKit::NetworkTransportStream::sendBytes):
(WebKit::NetworkTransportStream::receiveLoop):
(WebKit::NetworkTransportStream::setErrorCodeForStream):
(WebKit::NetworkTransportStream::cancel):
(WebKit::NetworkTransportStream::cancelReceive):
(WebKit::NetworkTransportStream::cancelSend):
* Source/WebKit/WebProcess/Network/WebTransportReceiveStreamSource.cpp:
(WebKit::WebTransportReceiveStreamSource::receiveBytes):
(WebKit::WebTransportReceiveStreamSource::doCancel):
* Source/WebKit/WebProcess/Network/WebTransportReceiveStreamSource.h:
* Source/WebKit/WebProcess/Network/WebTransportSendStreamSink.cpp:
(WebKit::WebTransportSendStreamSink::write):
(WebKit::WebTransportSendStreamSink::close):
(WebKit::WebTransportSendStreamSink::error):
(WebKit::WebTransportSendStreamSink::sendBytes):
* Source/WebKit/WebProcess/Network/WebTransportSendStreamSink.h:
* Source/WebKit/WebProcess/Network/WebTransportSession.cpp:
(WebKit::WebTransportSession::receiveDatagram):
(WebKit::WebTransportSession::receiveIncomingUnidirectionalStream):
(WebKit::WebTransportSession::receiveBidirectionalStream):
(WebKit::WebTransportSession::streamReceiveBytes):
(WebKit::WebTransportSession::sendDatagram):
(WebKit::WebTransportSession::streamSendBytes):
(WebKit::WebTransportSession::cancelReceiveStream):
(WebKit::WebTransportSession::cancelSendStream):
(WebKit::WebTransportSession::destroyStream):
* Source/WebKit/WebProcess/Network/WebTransportSession.h:
* Source/WebKit/WebProcess/Network/WebTransportSession.messages.in:
* Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm:
(TestWebKitAPI::TEST(WebTransport, DISABLED_ClientBidirectional)):
(TestWebKitAPI::TEST(WebTransport, DISABLED_Datagram)):
(TestWebKitAPI::TEST(WebTransport, DISABLED_Unidirectional)):
(TestWebKitAPI::TEST(WebTransport, DISABLED_ServerBidirectional)):
</pre>

2024-12-23 01:20 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/72c7db032a68f98c447dee4c34629e6d6036283e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 01:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/255b6a3ec2a09ecec87a093b9e24e8eb733b51be. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 02:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0091a77d49f0c2717287630cb7a684bc25e465d8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 03:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b724d13c6d9dfb2bd635fb113d8cd391d72ad305. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 19:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/121c75e04ce340ad93f041ac29578c8b69ded174. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 19:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/71d94d70fee34085107be09559d8fd1aabfbab2f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2024-12-23 20:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eb1fd375791f6e547677855fee1e47b5fa8f18fc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-02 18:11 UTC, achristensen07 requested changes

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +        completionHandler = nullptr;
This is not necessary.  A CompletionHandler becomes null when it is called.

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/WebProcess/Network/WebTransportReceiveStreamSource.cpp
> +        clean();
I'm not very familiar with these calls.  Do you know what happens when clean is not called?

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +            return;
If it's not a posix cancelled error, we won't ever call the completionHandler, which will assert.  It looks like we're missing a completionHandler(std::nullopt)

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +    if (metadata) {
if (RetainPtr metadata = adoptNS(...))
Then metadata has the right scope and you don't need to explicitly set it to null.  Also, the nw_retain call looks like it'll cause a memory leak.

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +            return;
Ditto.  completionHandler should be called in all possible flows.

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +                dispatch_data_apply_span(content, [&](std::span<const uint8_t> buffer) {
Is dispatch_data_apply_span API?  Can we just use dispatch_data_apply instead?

2025-01-02 18:11 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +    RetainPtr metadata = adoptNS(nw_connection_copy_protocol_metadata(m_connection.get(), nw_protocol_copy_webtransport_definition()));
nw_protocol_copy_webtransport_definition needs adoptNS or it will leak.

2025-01-05 01:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a432ef40caf47541ac1115b5607330b41d6e4b7b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 01:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a432ef40caf47541ac1115b5607330b41d6e4b7b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 01:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff5cf1d0df65b607b306a4f33a5ed7e56e7e68d6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 01:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff5cf1d0df65b607b306a4f33a5ed7e56e7e68d6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff87d3b53c2f98b105df8eccadff68f82047f489. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff87d3b53c2f98b105df8eccadff68f82047f489. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f7623aa8d7981bb611380cdb2d140f8e60cd5d79. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f7623aa8d7981bb611380cdb2d140f8e60cd5d79. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/986223714ea5512b9c622847849998bd3c12b0e9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 02:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/986223714ea5512b9c622847849998bd3c12b0e9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 06:30 UTC, achristensen07 commented on Source/WebCore/Modules/webtransport/DatagramSource.cpp
> -
nit: leave this space here.

2025-01-05 06:30 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/NetworkTransportStream.h
> +    void cancelReceive(std::optional<unsigned>);
Are error codes 32 bits?  If so, I think we should do something like this:
using NetworkTransportErrorCode = uint32_t
Otherwise it's a little unclear what the unsigned is.

2025-01-05 06:30 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +    if (metadata)
nit: variable declaration can be inside the if statement to match its scope.

2025-01-05 06:30 UTC, achristensen07 commented on Source/WebKit/WebProcess/Network/WebTransportSendStreamSink.cpp
> +        session->streamSendBytes(m_identifier, std::span<const uint8_t>(), true);
We can probably just use { } for the span.  We might want to use a 2-state enum for WithFin to make the "true" easier to tell what it means to a future reader.

2025-01-05 06:30 UTC, achristensen07 commented on Tools/TestWebKitAPI/Tests/WebKitCocoa/WebTransport.mm
> +        "    await r.cancel();"
To test a lot of this I think it would be useful to make it so the server can terminate connections without having been asked to by JS.

2025-01-05 18:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e25684be523f5bd222ca88bc455b36d760bf0aa0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-05 18:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e25684be523f5bd222ca88bc455b36d760bf0aa0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-06 17:20 UTC, achristensen07 requested changes

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +    // FIXME: Implement once rdar://141886375 is available in OS builds.
We could probably do this before then with optional soft linking.

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +            // If we were cancelled, exit gracefully
Do we want to do anything with the error if it is not ECANCELED?  This comment is a little mysterious.

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +        return;
This is unreachable.  This whole thing could just be RELEASE_ASSERT(m_streamState != NetworkTransportStreamState::ReadClosed)

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +            completionHandler(nullptr);
This needs to return or it will call the completion handler twice which will dereference null the second time because CompletionHandler sets itself to null when it is called.

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +            session = nullptr;
I don't think this is needed.

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/WebProcess/Network/WebTransportSession.cpp
> +    ASSERT(RunLoop::isMain());
I don't think this is correct.  WorkerWebTransportSession::cancelReceiveStream calls this directly from the non-main run loop.  I'd just remove these.

2025-01-06 17:20 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportSessionCocoa.mm
> +    m_streams.clear();
Instead of this, you could iterate std::exchange(m_streams, { }).values() to do both at the same time.  Not too important though.

2025-01-06 18:33 UTC, AnkshitJain commented on Source/WebKit/NetworkProcess/webtransport/cocoa/NetworkTransportStreamCocoa.mm
> +    // FIXME: Implement once rdar://141886375 is available in OS builds.
I'll add this in a separate PR.

2025-01-06 18:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b03a376cc3e9d24a4021eee061b371a8f44013b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-06 18:46 UTC, achristensen07 approved these changes

2025-01-06 18:46 UTC, achristensen07 commented on Source/WebCore/Modules/webtransport/WebTransportReceiveStreamSource.cpp
> +    , m_identifier(std::nullopt)
These lines don't do anything.  Let's remove them.

2025-01-06 23:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6277266442368fb44f6955aeccd25f0d11a557f2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-06 23:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f9a601adfcaf6ee992a50d0ceca3edd2b808a5e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38327

2025-01-06 23:32 UTC, achristensen07 approved these changes

2025-01-07 01:18 UTC, webkit-commit-queue commented
Committed 288498@main (d09b3b34e3e9): <https://commits.webkit.org/288498@main>

Reviewed commits have been landed. Closing PR #38327 and removing active labels.

2025-01-07 01:18 UTC, merged