Adopt more smart pointers in Network Process
WebKit/WebKit pull request #38337
Opened 2024-12-23 16:42 UTC by RupinMittal

#### 9d666430ea75118217f201507d6e763cf02a6332
<pre>
Adopt more smart pointers in Network Process
<a href="https://bugs.webkit.org/show_bug.cgi?id=285103">https://bugs.webkit.org/show_bug.cgi?id=285103</a>
<a href="https://rdar.apple.com/141945657">rdar://141945657</a>

Reviewed by NOBODY (OOPS!).

Smart pointer adoption as per the static analyzer.

* Source/WebCore/workers/service/server/SWServer.h:
(WebCore::SWServer::Connection::isWebSWServerConnection const):
* Source/WebCore/workers/service/server/SWServerToContextConnection.h:
* Source/WebKit/NetworkProcess/Cookies/WebCookieManager.cpp:
(WebKit::WebCookieManager::startObservingCookieChanges):
* Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.cpp:
(WebKit::NetworkConnectionToWebProcess::initializeWebTransportSession):
* Source/WebKit/NetworkProcess/NetworkProcess.cpp:
(WebKit::NetworkProcess::didClose):
(WebKit::NetworkProcess::prepareToSuspend):
* Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp:
(WebKit::NetworkResourceLoader::startRequest):
(WebKit::NetworkResourceLoader::retrieveCacheEntry):
(WebKit::NetworkResourceLoader::processClearSiteDataHeader):
(WebKit::NetworkResourceLoader::continueWillSendRedirectedRequest):
* Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp:
(WebKit::ServiceWorkerFetchTask::loadBodyFromPreloader):
(WebKit::ServiceWorkerFetchTask::convertToDownload):
* Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerConnection.cpp:
(WebKit::WebSWServerConnection::controlClient):
(WebKit::WebSWServerConnection::startFetch):
(WebKit::WebSWServerConnection::postMessageToServiceWorkerClient):
(WebKit::WebSWServerConnection::registerServiceWorkerClientInternal):
(WebKit::WebSWServerConnection::unregisterServiceWorkerClient):
(WebKit::WebSWServerConnection::computeThrottleState const):
(WebKit::WebSWServerConnection::updateThrottleState):
(WebKit::WebSWServerConnection::contextConnectionCreated):
(WebKit::WebSWServerConnection::sendToContextProcess):
* Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerConnection.h:
(isType):
* Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerToContextConnection.h:
(isType):
* Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.cpp:
(WebKit::WebSharedWorkerServerToContextConnection::launchSharedWorker):
* Source/WebKit/NetworkProcess/webrtc/NetworkRTCProvider.cpp:
(WebKit::NetworkRTCProvider::NetworkRTCProvider):
(WebKit::NetworkRTCProvider::attributedBundleIdentifierFromPageIdentifier):
* Source/WebKit/SaferCPPExpectations/MemoryUnsafeCastCheckerExpectations:
* Source/WebKit/SaferCPPExpectations/UncountedCallArgsCheckerExpectations:
* Source/WebKit/SaferCPPExpectations/UncountedLambdaCapturesCheckerExpectations:
* Source/WebKit/Shared/API/Cocoa/_WKRemoteObjectRegistry.mm:
(-[_WKRemoteObjectRegistry _callReplyWithID:blockInvocation:]):
* Source/WebKit/Shared/ApplePay/WebPaymentCoordinatorProxy.cpp:
(WebKit::WebPaymentCoordinatorProxy::showPaymentUI):
* Source/WebKit/UIProcess/AuxiliaryProcessProxy.cpp:
(WebKit::AuxiliaryProcessProxy::shutDownProcess):
* Source/WebKit/WebProcess/Storage/WebServiceWorkerFetchTaskClient.cpp:
(WebKit::WebServiceWorkerFetchTaskClient::didReceiveRedirection):
(WebKit::WebServiceWorkerFetchTaskClient::didReceiveResponse):
(WebKit::WebServiceWorkerFetchTaskClient::didReceiveDataInternal):
(WebKit::WebServiceWorkerFetchTaskClient::didReceiveFormDataAndFinishInternal):
(WebKit::WebServiceWorkerFetchTaskClient::didReceiveBlobChunk):
(WebKit::WebServiceWorkerFetchTaskClient::didFailInternal):
(WebKit::WebServiceWorkerFetchTaskClient::didFinishInternal):
(WebKit::WebServiceWorkerFetchTaskClient::didNotHandleInternal):
(WebKit::WebServiceWorkerFetchTaskClient::usePreload):
(WebKit::WebServiceWorkerFetchTaskClient::contextIsStopping):
* Source/WebKit/WebProcess/Storage/WebServiceWorkerFetchTaskClient.h:
</pre>

2024-12-23 16:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9d666430ea75118217f201507d6e763cf02a6332. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38337

2025-01-03 22:01 UTC, RupinMittal commented on Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.cpp
> +        connection->postConnectEvent(sharedWorker, port, [](bool) { });
Ref'ing `this` here is causing a crash with `ASSERTION FAILED: !m_adoptionIsRequired` (linked below). 

This is because in `WebSharedWorkerServerToContextConnection`'s constructor, we pass `*this` to `WebSharedWorkerServer::addContextConnection` and that un-adopted reference is eventually used by `WebSharedWorkerServer` to call this function here--resulting in this crash. 

How can I fix this? It seems wrong to use adoptRef in the constructor: `server.addContextConnection(adoptRef(*this));`

https://ews-build.s3-us-west-2.amazonaws.com/macOS-Sequoia-Debug-WK2-Tests-EWS/9d666430-6824/imported/w3c/web-platform-tests/content-security-policy/sandbox/shared-worker-sandbox-crash-log.txt

2025-01-03 22:04 UTC, cdumez commented on Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.cpp
> +        connection->postConnectEvent(sharedWorker, port, [](bool) { });
Call `relaxAdoptionRequirement();` in the class constructor.

2025-01-03 22:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fbbfca26161cc619bc4d62d96a2f52343b33f3e9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38337

2025-01-03 22:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fbbfca26161cc619bc4d62d96a2f52343b33f3e9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38337

2025-01-04 01:59 UTC, cdumez requested changes

2025-01-04 01:59 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkProcess.cpp
> +    forEachNetworkSession([process = Ref { *this }, callbackAggregator = WTFMove(callbackAggregator)](auto& session) {
`process` -> `protectedThis` ?

2025-01-04 01:59 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkProcess.cpp
> +        if (!weakThis)
Early return is definitely not OK here as we'd fail to call the completion handler

2025-01-04 01:59 UTC, cdumez commented on Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp
> +    auto serviceWorkerDownloadLoad = NetworkLoad::create(*protectedLoader(), *session, [&serviceWorkerDownloadTask, &session, &serviceWorkerConnection, serviceWorkerIdentifier = m_serviceWorkerIdenti
The new code is less readable. Why did we have to expand the `&` here?

2025-01-04 01:59 UTC, cdumez commented on Source/WebKit/NetworkProcess/webrtc/NetworkRTCProvider.cpp
> +    return m_attributedBundleIdentifiers.ensure(pageIdentifier, [checkedThis = CheckedPtr { this }, pageIdentifier]() -> String {
Seems we should create a `protectedThis` right away here instead of a `CheckedThis` since you end up synchronously constructing a protectedThis` a few lines below anyway.

2025-01-04 01:59 UTC, cdumez commented on Source/WebKit/WebProcess/Storage/WebServiceWorkerFetchTaskClient.h
>          Ref<WebServiceWorkerFetchTaskClient> client;
can't we simply mark this as `const` to avoid the smart pointer warnings instead of having an unnecessary `protectedClient()`?

2025-01-04 02:02 UTC, RupinMittal commented on Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp
> +    auto serviceWorkerDownloadLoad = NetworkLoad::create(*protectedLoader(), *session, [&serviceWorkerDownloadTask, &session, &serviceWorkerConnection, serviceWorkerIdentifier = m_serviceWorkerIdenti
The analyzer said that implicitly capturing `this` with the & was unsafe: https://build.webkit.org/results/Apple-Sequoia-Safer-CPP-Checks/288318@main%20(1002)/scan-build-output/StaticAnalyzer/WebKit/StaticAnalyzerReports/report-ServiceWorkerFetchTask.cpp-unknown-0-1b1184.html#EndPath

2025-01-04 04:06 UTC, cdumez commented on Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp
> +    auto serviceWorkerDownloadLoad = NetworkLoad::create(*protectedLoader(), *session, [&serviceWorkerDownloadTask, &session, &serviceWorkerConnection, serviceWorkerIdentifier = m_serviceWorkerIdenti
So don't use `this` inside the lambda and keep capturing `[&]` ?

2025-01-06 16:52 UTC, RupinMittal commented on Source/WebKit/NetworkProcess/ServiceWorker/ServiceWorkerFetchTask.cpp
> +    auto serviceWorkerDownloadLoad = NetworkLoad::create(*protectedLoader(), *session, [&serviceWorkerDownloadTask, &session, &serviceWorkerConnection, serviceWorkerIdentifier = m_serviceWorkerIdenti
Hmm, I'm confused about how I can avoid using `this`? For example, `serviceWorkerIdentifier` is a member of `this`, so unless it's captured explicitly by value in the lambda, `this` will be used.

But either way, I believe we use NOESCAPE here. Is this correct?

2025-01-06 21:00 UTC, cdumez approved these changes

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/ServiceWorker/WebSWServerConnection.cpp
> +    server->postMessageToServiceWorkerClient(destinationContextIdentifier, message, sourceIdentifier, sourceOrigin, [connection = Ref { *this }] (auto destinationContextIdentifier, auto& message, aut
`connection` -> `protectedThis`

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/SharedWorker/WebSharedWorkerServerToContextConnection.cpp
> +    sharedWorker.forEachSharedWorkerObject([connection = Ref { *this }, sharedWorker = Ref { sharedWorker }](auto, auto& port) {
`connection` -> `protectedThis`

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/Cookies/WebCookieManager.cpp
> +            RefPtr protectedThis = weakThis.get();
Would be more concise without the early return:
```
if (RefPtr protectedThis = weakThis.get())
    protectedThis->notifyCookiesDidChange(sessionID);
```

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkProcess.cpp
> +    auto callbackAggregator = CallbackAggregator::create([process = Ref { *this }] {
`process` -> `protectedThis`

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkProcess.cpp
> +    RefPtr<CallbackAggregator> callbackAggregator = CallbackAggregator::create([weakThis = WeakPtr { *this }, completionHandler = WTFMove(completionHandler)]() mutable {
Can omit `<CallbackAggregator>`

2025-01-06 21:00 UTC, cdumez commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +                [protectedThis] (ResourceError& error) {
Is there no way to mark the lambdas passed to `WTF::switchOn()` as `NOESCAPE` instead?

2025-01-06 23:53 UTC, rniwa commented on Source/WebKit/NetworkProcess/NetworkLoad.cpp
> +NetworkLoad::NetworkLoad(NetworkLoadClient& client, NetworkSession& networkSession, NOESCAPE const Function<RefPtr<NetworkDataTask>(NetworkDataTaskClient&)>& createTask)
You don't need to specify NOESCAPE in the function definition. Just put that on declaration.

2025-01-07 08:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e54ee609cf752cdc2989069b3405d8a3a8f4f3c2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38337

2025-01-07 08:27 UTC, RupinMittal commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +                [protectedThis] (ResourceError& error) {
That's a good question. I'm not sure. @rniwa, do you know?

2025-01-07 21:52 UTC, RupinMittal commented on Source/WebKit/NetworkProcess/NetworkResourceLoader.cpp
> +                [protectedThis] (ResourceError& error) {
Seems like WTF::switchOn() should be hard-coded to ignore captured arguments. I've filed a bug about this.

2025-01-07 21:53 UTC, webkit-commit-queue commented
Committed 288561@main (3d3c125c9682): <https://commits.webkit.org/288561@main>

Reviewed commits have been landed. Closing PR #38337 and removing active labels.

2025-01-07 21:53 UTC, merged