Fix to return `initial value` for SVG Length in case of parser error and being invalid
WebKit/WebKit pull request #38414
Opened 2024-12-29 15:02 UTC by Ahmad-S792

#### 8b61385c97f5222cd48ccd140ba7f9496af3f6a7
<pre>
Fix to return `initial value` for SVG Length in case of parser error and being invalid

<a href="https://bugs.webkit.org/show_bug.cgi?id=279379">https://bugs.webkit.org/show_bug.cgi?id=279379</a>
<a href="https://rdar.apple.com/136102554">rdar://136102554</a>

Reviewed by NOBODY (OOPS!).

Our current implementation for initial values was not taking account when there
was any parser error or when the value was empty string or null, this patch fixes
the bug by ensuring that we return the initial value as per web-standard in those cases.

Similarly, it was noted that the initial value was not set for `fx` and `fy` on
SVGRadialGradientElement, this also fixes it.

Test Merge: <a href="https://chromium.googlesource.com/chromium/src/+/db0702d6bdda54529bef038201752b37a3eadf8e">https://chromium.googlesource.com/chromium/src/+/db0702d6bdda54529bef038201752b37a3eadf8e</a>

* Source/WebCore/svg/SVGFilterElement.cpp:
(WebCore::SVGFilterElement::attributeChanged):
* Source/WebCore/svg/SVGFilterPrimitiveStandardAttributes.cpp:
(WebCore::SVGFilterPrimitiveStandardAttributes::attributeChanged):
* Source/WebCore/svg/SVGLinearGradientElement.cpp:
(WebCore::SVGLinearGradientElement::attributeChanged):
* Source/WebCore/svg/SVGMarkerElement.cpp:
(WebCore::SVGMarkerElement::attributeChanged):
* Source/WebCore/svg/SVGMaskElement.cpp:
(WebCore::SVGMaskElement::attributeChanged):
* Source/WebCore/svg/SVGRadialGradientElement.cpp:
(WebCore::SVGRadialGradientElement::attributeChanged):
* Source/WebCore/svg/SVGRadialGradientElement.h:
* LayoutTests/svg/dom/svganimatedlength-initial-values-expected.txt:
* LayoutTests/svg/dom/svganimatedlength-initial-values.html:
</pre>

2024-12-29 15:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8b61385c97f5222cd48ccd140ba7f9496af3f6a7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2024-12-29 15:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8b61385c97f5222cd48ccd140ba7f9496af3f6a7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2024-12-29 20:05 UTC, weinig commented
Would be great if this could be a bit more table / data driven, and avoid some the duplicated logic here.

2024-12-29 21:17 UTC, Ahmad-S792 commented
> Would be great if this could be a bit more table / data driven, and avoid some the duplicated logic here.

I looked into current way - how we are passing 80+ test cases and then opted to go with current way. I can definitely think we can do enum or other better ways but I just wanted to squeeze 48 passes on failing test case. :-)

2025-01-03 02:10 UTC, shallawa commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
I think the specs do not say the initial values of `fx` and `fy` are 50% and 50%. Where did you get these initial values from?

2025-01-03 02:10 UTC, shallawa commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
This code is repeated multiple times in this PR. It parses an `SVGLengthValue` if it is invalid it sets the baseVal of the `SVGAnimatedProperty` to the initial value. Should not this code be put in one function so this change is smaller?

2025-01-03 02:32 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementFXAttribute

When it is not specified, it coincides with `cx` and same for `fy`.

2025-01-03 02:33 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
It is something currently done as well, so I opted for this. I am OK with using helper function or reduce repetition but I was thinking of doing it as future follow-up.

2025-01-03 23:59 UTC, shallawa commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
This is the only thing we do in `SVGRadialGradientElement::collectGradientAttributes()` to respect this part of the specs:

```
    // Handle default values for fx/fy
    if (!attributes.hasFx())
        attributes.setFx(attributes.cx());

    if (!attributes.hasFy())
        attributes.setFy(attributes.cy());
```

But I do not see that we change the fx and fy properties every time the fx, fy, cx are cy attributes change. For example:

1. If the fx attribute is removed, we should set the fx property to the value of the cx property.
2. If cx attribute changes and fx is not specified, the new value of cx is set to fx.

2025-01-04 00:04 UTC, shallawa commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
I think using table / data driven as Sam suggested or a single function to set the properties should be a better approach. Adding repeated code in multiple places and then trying to shorten it later does not seem an efficient way to do things.

2025-01-05 21:27 UTC, darinadler commented on LayoutTests/svg/dom/svganimatedlength-initial-values-expected.txt
> +CONSOLE MESSAGE: Error: Invalid value for <circle> attribute cx="foobar"
Is it good to log these in the console? I guess maybe it's helpful for website developers?

2025-01-05 21:27 UTC, darinadler commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
I agree that we should include the helper function in the initial patch. The pattern is simple enough that I expect it can be done cleanly.

2025-01-05 21:27 UTC, darinadler commented on Source/WebCore/svg/SVGFilterPrimitiveStandardAttributes.cpp
> +        Ref { m_x }->setBaseValInternal(length);
```suggestion
        parse(m_x, SVGLengthMode::Width, "0%"_s);
```
The `parse` function should be easy to write.

2025-03-27 01:28 UTC, karlcow commented on Source/WebCore/svg/SVGFilterPrimitiveStandardAttributes.cpp
> +        Ref { m_x }->setBaseValInternal(length);
Should the function be in SVGParserUtilities.cpp

2025-03-27 01:30 UTC, karlcow commented
> Would be great if this could be a bit more table / data driven, and avoid some the duplicated logic here.

@weinig Is there a similar example of the  "table / data driven" approach you are recommending elsewhere in the code.

2025-05-26 08:52 UTC, karlcow commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
@Ahmad-S792 

in `SVGParserUtilities.h`

```
void parseAndSetLengthValue(Ref<SVGAnimatedLength>& animatedLength, SVGLengthMode mode, const AtomString& newValue, const String& fallbackValue);
```

in `SVGParserUtilities.cpp`

```
void parseAndSetLengthValue(Ref<SVGAnimatedLength>& animatedLength, SVGLengthMode mode, const AtomString& newValue, const String& fallbackValue);
{
    SVGParsingError parseError = NoError;
    auto length = SVGLengthValue::construct(mode, newValue, parseError);
    if (parseError != NoError || newValue.isNull())
        length = SVGLengthValue(mode, fallbackValue);
    Ref { animatedLength }->setBaseValInternal(length);
}
```


So you can rewrite with:

```
case AttributeNames::xAttr: {
    SVGParserUtilities::parseAndSetLengthValue(m_x, SVGLengthMode::Width, newValue, "-10%"_s);
    break;
}
case AttributeNames::yAttr: {
    SVGParserUtilities::parseAndSetLengthValue(m_y, SVGLengthMode::Height, newValue, "-10%"_s);
    break;
}
case AttributeNames::widthAttr: {
    SVGParserUtilities::parseAndSetLengthValue(m_width, SVGLengthMode::Width, newValue, "120%"_s);
    break;
}
case AttributeNames::heightAttr: {
    SVGParserUtilities::parseAndSetLengthValue(m_height, SVGLengthMode::Height, newValue, "120%"_s);
    break;
}
```

2025-05-26 11:14 UTC, karlcow commented on Source/WebCore/svg/SVGFilterPrimitiveStandardAttributes.cpp
> +        Ref { m_x }->setBaseValInternal(length);
see https://github.com/WebKit/WebKit/pull/38414/files#r2106870367

2025-05-27 22:33 UTC, brentfulgham requested changes
Please revise your patch to create and adopt a 'parse' function as @karlcow and @darinadler suggested.

2025-05-27 22:33 UTC, brentfulgham commented on Source/WebCore/svg/SVGFilterElement.cpp
> +        Ref { m_x }->setBaseValInternal(length);
I agree with @darinadler and @karlcow ! This will be much easier to read and reason about.

2025-05-28 08:16 UTC, karlcow commented
@Ahmad-S792 should it not fixed also these tests?
https://wpt.fyi/results/svg/types/scripted/SVGAnimatedLength-initial-values.html?label=master&label=experimental&aligned&q=firefox%3Apass%20chrome%3Apass%20safari%3Afail

https://github.com/WebKit/WebKit/blob/main/LayoutTests/imported/w3c/web-platform-tests/svg/types/scripted/SVGAnimatedLength-initial-values.html

which would also mean it would be possible to remove these two.

* LayoutTests/svg/dom/svganimatedlength-initial-values-expected.txt:
* LayoutTests/svg/dom/svganimatedlength-initial-values.html:

2025-06-14 02:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5c199f41d6e0abb2948e209199b03acae5437e91. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2025-06-14 02:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5c199f41d6e0abb2948e209199b03acae5437e91. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2025-06-14 02:11 UTC, Ahmad-S792 commented
I just rebased and push fix with helper function but I think we still have two things:

- Current function does not handle 'SVGLengthNegativeValuesMode::Forbid' part
- Current also does not handle invalid value 'foobar' (notice removed 'console' errors)

Still on right track IMO.

2025-06-14 03:43 UTC, darinadler requested changes

2025-06-14 03:43 UTC, darinadler commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue constructLengthValueWithFallback(SVGLengthMode, const AtomString&, const String&);
```suggestion
    static SVGLengthValue construct(SVGLengthMode, StringView value, ASCIILiteral fallback);
```
This is a member of the `SVGLengthValue` class and so we don't need to repeat words from the name of the class here. Also, this should take a `StringView` since that's what the constructor takes and for the fallback I suggest taking `ASCIILiteral` so we don't create and destroy a String when we are not falling back. Without argument names it's not clear what the two different strings are. I think we can name this without the words "with fallback" because the overloading makes it unambiguous enough.

2025-06-14 03:43 UTC, darinadler commented on Source/WebCore/svg/SVGFilterElement.cpp
>          break;
```suggestion
    case AttributeNames::xAttr:
        Ref { m_x }->setBaseValInternal(SVGLengthValue::construct(SVGLengthMode::Width, newValue, "-10%"_s));
```
It's not an improvement to add a local variable, we shouldn't do that.

2025-06-14 15:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/66728fea3cccfa8d5ed4278884ef0fc2c05f18a3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2025-06-14 15:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/66728fea3cccfa8d5ed4278884ef0fc2c05f18a3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38414

2025-06-14 15:48 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGFilterElement.cpp
>          break;
Refactored and addressed this feedback. :-)

2025-06-14 15:48 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue constructLengthValueWithFallback(SVGLengthMode, const AtomString&, const String&);
Refactored and addressed this feedback. :-)

2025-06-15 16:12 UTC, darinadler requested changes
I think we need to resolve the comment from @shallawa before landing this.

2025-06-15 16:12 UTC, darinadler commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue construct(SVGLengthMode, StringView, ASCIILiteral);
```suggestion
    static SVGLengthValue construct(SVGLengthMode, StringView, ASCIILiteral, SVGLengthNegativeValuesMode = SVGLengthNegativeValuesMode::Allow);
```

2025-06-15 16:12 UTC, darinadler commented on Source/WebCore/svg/SVGRadialGradientElement.cpp
> +    }
```suggestion
    case AttributeNames:frAttr:
        Ref { m_fr }->setBaseValInternal(SVGLengthValue::construct(SVGLengthMode::Other, newValue, "0%"_s, SVGLengthNegativeValuesMode::Forbid);
        break;
```

2025-06-15 22:58 UTC, Ahmad-S792 commented
Yes - it is not fully ready, so I am chipping at this PR slowly. :-)

2025-11-25 01:30 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/3eb19696aeb8d0552070a68ae5f2ddffe6d4cbb9)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/132673 "Passed style check") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/5168 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") | ⏳ 🛠 ios-apple 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/134543 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/5405 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/156/builds/4927 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") | ⏳ 🛠 mac-apple 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/135619 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/155/builds/5405 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | | ⏳ 🛠 vision-apple 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/155/builds/5405 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac-debug](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/155/builds/5405 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/142856 "Build is in progress. Recent messages:") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/4838 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/142856 "Build is in progress. Recent messages:") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/4920 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/156/builds/4927 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/142856 "Build is in progress. Recent messages:") | | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-26-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/138/builds/43744 "Build is in progress. Recent messages:OS: Sonoma (14.7.3), Xcode: 15.4; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/58312 "Build is in progress. Recent messages:Printed configuration; Skipping applying patch since patch_id isn't provided; Checked out pull request; [...]

2025-11-25 01:58 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
@karlcow - Can we address this in specification or if you can shed some night.

2025-11-25 04:10 UTC, Ahmad-S792 commented
@darinadler - Whenever you have free time to look into all combined changes, it would be good to get feedback. I also asked @karlcow to get clarification around specification issue which @shallawa raised.

2025-11-25 13:51 UTC, darinadler approved these changes

2025-11-25 13:51 UTC, darinadler commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue construct(SVGLengthMode, StringView, SVGParsingError&, SVGLengthNegativeValuesMode = SVGLengthNegativeValuesMode::Allow, std::optional<ASCIILiteral> fallbackValue = std::nul
`ASCIILiteral` has a null value, so `fallbackValue` can just be an `ASCIILiteral` rather than a `std::optional<ASCIILiteral>`.

Not new to this patch, to consider for future improvement: the name `construct` is not a typical name for a parsing function. It's more important that it parses than the fact that the value it returns is "constructed". I think this should eventually be renamed `parse` and should be changed to return `std::tuple<SVGLengthValue, SVGParserError>` rather than using an out argument. We would refactor the call sites a bit.

2025-11-26 01:29 UTC, karlcow commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementFXAttribute

> [initial value](https://svgwg.org/svg2-draft/types.html#TermInitialValue)
see below
> [Animatable](https://svgwg.org/specs/animations/#Animatable)
yes

Let's look below. (The spec would deserve example each time there is this kind of prose.)

> 1. If attribute ‘[fx](https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementFXAttribute)’ is not specified, ‘[fx](https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementFXAttribute)’ will coincide with the presentational value of ‘[cx](https://svgwg.org/svg2-draft/pservers.html#RadialGradientElementCXAttribute)’ for the element whether the value for 'cx' was inherited or not. 
> 2. If the element references an element that specifies a value for 'fx', then the value of 'fx' is inherited from the referenced element.

* if `cx="40"` and no `fx` is in the markup, then `fx` value is `40` (`cx` is not necessarily defined here and can be inherited too. **Though I wonder how you inherit the value of `cx`? What would be the markup for this case**)
* the case in 2 is for `<defs>` I guess. This could be clearer in the spec too. 

So the initial value of `fx` when 
* it is not specified, aka `<radialGradient cx="40" cy="40" r="40">…`,  is the current value of `cx`, aka 40.
* of if the value is empty, aka `<radialGradient cx="40" cy="40" r="40" fx="">…` is the current value of `cx` aka 40.

if the value of `cx` was not specified then yes it would be "50%" aka `<radialGradient cy="40" r="40">…` 

See my test cases in https://codepen.io/webcompat/full/GgZQMgZ
<img width="2646" height="1251" alt="Screenshot 2025-11-26 at 10 27 25" src="https://github.com/user-attachments/assets/ffbdbd21-6060-41a3-bf75-6dfac240388f" />

right now, interop is failing for the case: **`cx=40 / fx=""`**


```
    <svg viewBox="0 0 80 80">
      <defs>
        <radialGradient id="MyGradient11" gradientUnits="userSpaceOnUse" cx="40" fx="" cy="40" r="40">
          <stop offset="0%" stop-color="#A8F" />
          <stop offset="50%" stop-color="#FDC" />
          <stop offset="100%" stop-color="#A8F" />
        </radialGradient>
      </defs>

      <!-- The rectangle is filled using a radial gradient paint server -->
      <rect fill="url(#MyGradient11)" stroke="black" stroke-width="2" x="0" y="0" width="80" height="80" />
    </svg>
```

2025-11-26 01:30 UTC, karlcow commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
And **`cx=40 / fx=80ABC`**

```
<svg viewBox="0 0 80 80">
      <defs>
        <radialGradient id="MyGradient9" gradientUnits="userSpaceOnUse" cx="40" fx="80ABC" cy="40" r="40">
          <stop offset="0%" stop-color="#A8F" />
          <stop offset="50%" stop-color="#FDC" />
          <stop offset="100%" stop-color="#A8F" />
        </radialGradient>
      </defs>

      <!-- The rectangle is filled using a radial gradient paint server -->
      <rect fill="url(#MyGradient9)" stroke="black" stroke-width="2" x="0" y="0" width="80" height="80" />
    </svg>
```

2025-11-26 04:41 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/fc6395532a8eed1258678c9e3aacc3e7d030b67c)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/132818 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/5319 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/43902 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/140350 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/84846 "Built successfully") | [✅ 🛠 ios-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/cbf699d4-5c6d-4cc4-942f-d99be956c06c) 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/134688 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/5651 "Built successfully") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/156/builds/5182 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 wpe-wk2~~](https://ews-build.webkit.org/#/builders/34/builds/101555 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🧪 win-tests](https://ews-build.webkit.org/#/builders/Win-Tests-EWS "Waiting to run tests") | [✅ 🛠 mac-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/8cd9f26f-a5c2-4701-9683-7fdd51b4c880) 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/135764 "Passed tests") | [⏳ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/iOS-26-Simulator-WK2-Tests-EWS "Waiting to run tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/18/builds/118994 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 api-wpe~~](https://ews-build.webkit.org/#/builders/41/builds/82348 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | [✅ 🛠 vision-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/a5bd1345-4815-4079-a07d-22462cc978be) 
| | [⏳ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/iOS-26-Simulator-WPT-WK2-Tests-EWS "Waiting to run tests") | [⏳ 🧪 api-mac-debug](https://ews-build.webkit.org/#/builders/macOS-Tahoe-Debug-API-Tests-EWS "Waiting to run tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/83583 "Built successfully") | | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/13/builds/112843 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/135/builds/37112 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/143005 "Built successfully") | | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/4988 "Built successfully") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/136/builds/37697 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/1/builds/109928 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/5070 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/156/builds/5182 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/110106 "Passed tests") | | 
| | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/164/builds/3815 "Passed tests") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/8/builds/115260 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/58503 "Built successfully") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/158/builds/5042 "Built successfully") | [  ~~🧪 mac-intel-wk2~~](https://ews-build.webkit.org/#/builders/137/builds/33613 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/157/builds/4880 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/68494 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/163/builds/5132 "Built successfully") | | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/152/builds/5000 "Built successfully") | | | | </details>

2025-11-26 04:42 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
@karlcow - I undid the change, we can explore it in future but just to flag adding this does not regress your test case.

2025-11-26 05:16 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/187e6588070eb4207fd4d58556489cd72cae126f)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/132821 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/5322 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/138/builds/43906 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/140353 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/84849 "Built successfully") | [✅ 🛠 ios-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/d9caa900-5723-4c0e-a941-faf417969012) 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/134691 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/5655 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/156/builds/5185 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/101556 "Passed tests") | [✅ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/68857 "Passed tests") | [✅ 🛠 mac-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/c10158c1-ea86-4825-a545-9f4c4575f7a1) 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/135767 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/162/builds/3969 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/118996 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/82349 "Passed tests") | | [✅ 🛠 vision-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/f2c6d2ed-bd8b-4d70-a499-64172ae81bd0/cb9ee19b-2e14-44c5-8b7e-5f5cd469bbbe) 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/154/builds/3856 "Passed tests") | [✅ 🧪 api-mac-debug](https://ews-build.webkit.org/#/builders/165/builds/1542 "Passed tests") | [✅ 🛠 wpe-cairo](https://ews-build.webkit.org/#/builders/65/builds/83586 "Built successfully") | | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/112844 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/135/builds/37114 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/143008 "Built successfully") | | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/4991 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/136/builds/37699 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/109930 "Passed tests") | | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/5073 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/161/builds/4294 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/110108 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/19/builds/27924 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/164/builds/3816 "Passed tests") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/115262 "Passed tests") | [✅ 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/58506 "Built successfully") | | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 tv](https://ews-build.webkit.org/#/builders/158/builds/5045 "Build is in progress. Recent messages:OS: Tahoe (26.0), Xcode: 26.0.1; Skipping applying patch since patch_id isn't provided; Checked out pull request; Compiled WebKit (warnings)") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/137/builds/33615 "Passed tests") | | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/157/builds/4883 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/68497 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/163/builds/5135 "Built successfully") | | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/152/builds/5003 "Built successfully") | | | | </details>

2025-11-26 05:18 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue construct(SVGLengthMode, StringView, SVGParsingError&, SVGLengthNegativeValuesMode = SVGLengthNegativeValuesMode::Allow, std::optional<ASCIILiteral> fallbackValue = std::nul
@darinadler - Thanks for review, I updated now and accommodated your feedback of `ASCIILiteral` instead of `std::optional<ASCIILiteral>`. As for future work, I will file follow-up bug to see, if it is something I can tackle myself but thanks a lot for help. I also undid Said's concern on other change and I am in discussion with Karl on how to proceed, so I think it is now ready to land. After green EWS, I will land it. :-)

2025-11-26 19:18 UTC, Ahmad-S792 commented on Source/WebCore/svg/SVGLengthValue.h
> +    static SVGLengthValue construct(SVGLengthMode, StringView, SVGParsingError&, SVGLengthNegativeValuesMode = SVGLengthNegativeValuesMode::Allow, std::optional<ASCIILiteral> fallbackValue = std::nul
https://bugs.webkit.org/show_bug.cgi?id=303150 <- for future work.

2025-11-26 19:41 UTC, webkit-commit-queue commented
Committed 303577@main (38b65cc65f13): <https://commits.webkit.org/303577@main>

Reviewed commits have been landed. Closing PR #38414 and removing active labels.

2025-11-26 19:41 UTC, merged

2026-01-20 07:14 UTC, karlcow commented on Source/WebCore/svg/SVGRadialGradientElement.h
> +    Ref<SVGAnimatedLength> m_fy { SVGAnimatedLength::create(this, SVGLengthMode::Height, "50%"_s) };
I created a test to observer the behavior of browsers. 

with regards to what @shallawa says:

> 1. If the fx attribute is removed, we should set the fx property to the value of the cx property.

Both Firefox and Chrome do not respect this. 
They set the value to 50%. They do not follow the spec. 

> 2. If cx attribute changes and fx is not specified, the new value of cx is set to fx.

Both Firefox and Chrome do not respect this. 
They set the value to 50%. They do not follow the spec. 


I think the spec needs to change. @Ahmad-S792 opened an issue.
https://github.com/w3c/svgwg/issues/1054
I put in on the agenda for this week. 

The current WPT tests do not showcase this part of the spec. 

See the test I uploaded in 
https://github.com/user-attachments/files/24730583/gradient-test.html

So the fix to default to 50% brings WebKit closer to the actual other browsers behavior.

Depending on the outcome of the discussion this week in the SVGWG.
We could  fix the dependency of fx/cx, fy/cy if necessary. Or just ignore if the spec is changing. 

In the meantime I think we should merge this, with a default value of 50%. because it is basically what browsers are doing.