[WPE] Fix compilation issue with USE_GBM=OFF and USE_LIBDRM=OFF
WebKit/WebKit pull request #38415
Opened 2024-12-29 18:15 UTC by zhani

#### e6c32e6cd85f0290035c332b389b571876be7b5b
<pre>
[WPE] Fix compilation issue with USE_GBM=OFF and USE_LIBDRM=OFF
<a href="https://bugs.webkit.org/show_bug.cgi?id=285229">https://bugs.webkit.org/show_bug.cgi?id=285229</a>

When USE_GBM=OFF and USE_LIBDRM=OFF, WPE platform compilation fails.
This combination also implies ENABLE_GPU_PROCESS=OFF. The patch
adds necessary ifdefs and includes to resolve the issue.

* Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp:
(WebKit::WebKitProtocolHandler::handleGPU):
* Source/WebKit/UIProcess/wpe/WebPageProxyWPE.cpp:
* Source/WebKit/WebProcess/WebCoreSupport/WebChromeClient.cpp:
</pre>

2024-12-29 18:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e6c32e6cd85f0290035c332b389b571876be7b5b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38415

2024-12-29 18:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e6c32e6cd85f0290035c332b389b571876be7b5b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38415

2024-12-29 19:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/95443d6b2c3b82dc23ae206ddb4af493c09e4f19. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38415

2024-12-29 19:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/95443d6b2c3b82dc23ae206ddb4af493c09e4f19. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38415

2025-01-10 08:59 UTC, carlosgcampos requested changes
Thanks, I have a few minor comments

2025-01-10 08:59 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp
> +#if PLATFORM(GTK) || (PLATFORM(WPE) && USE(LIBDRM) && ENABLE(WPE_PLATFORM))
I know it's existing code, but we don't really need PLATFORM(WPE) && ENABLE(WPE_PLATFORM) since WPE_PLATFORM is only defined for WPE. Also, LIBDRM is optional for gtk too, so we should first check LIBDRM and then platforms

2025-01-10 08:59 UTC, carlosgcampos commented on Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp
> +#elif PLATFORM(WPE) && USE(LIBDRM) && ENABLE(WPE_PLATFORM)
Same here

2025-01-10 08:59 UTC, carlosgcampos commented on Source/WebKit/UIProcess/wpe/WebPageProxyWPE.cpp
> +#if PLATFORM(WPE) && USE(GBM) && ENABLE(WPE_PLATFORM)
So, no need to add the PLATFORM(WPE) here

2025-01-10 08:59 UTC, carlosgcampos commented on Source/WebKit/WebProcess/WebCoreSupport/WebChromeClient.cpp
> +#include <WebCore/BarcodeDetectorInterface.h>
This looks unrelated to GBM or LIBDRM, I guess it's a unified build issue that can be fixed in separate commit without review.

2025-01-12 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9f57af251dec55a0961c8d4a704390ad6e59bf47. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38415

2025-01-12 21:38 UTC, zhani commented on Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp
> +#if PLATFORM(GTK) || (PLATFORM(WPE) && USE(LIBDRM) && ENABLE(WPE_PLATFORM))
There was already another commit in upstream fixing this issue so this change is obsolete

2025-01-12 21:38 UTC, zhani commented on Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp
> +#elif PLATFORM(WPE) && USE(LIBDRM) && ENABLE(WPE_PLATFORM)
There was already another commit in upstream fixing this issue so this change is obsolete

2025-01-12 21:38 UTC, zhani commented on Source/WebKit/UIProcess/wpe/WebPageProxyWPE.cpp
> +#if PLATFORM(WPE) && USE(GBM) && ENABLE(WPE_PLATFORM)
Fixed

2025-01-12 21:40 UTC, zhani commented on Source/WebKit/WebProcess/WebCoreSupport/WebChromeClient.cpp
> +#include <WebCore/BarcodeDetectorInterface.h>
I don't have commit rights to push without review. I added this change as a separate commit to this patch so it gets merged with this

2025-01-13 11:07 UTC, carlosgcampos commented
I don't think commit-queue can handle more than one patch per PR

2025-01-13 14:43 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/eeb8698c4910f4329544df885192ebfe377ea24e)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/84460 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/131/builds/4085 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/89542 "Build is in progress. Recent messages:") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/86545 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/4170 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/12069 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/5/builds/89542 "Build is in progress. Recent messages:") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/87506 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/4170 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-mac](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-wpe](https://ews-build.webkit.org/#/builders/5/builds/89542 "Build is in progress. Recent messages:") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/4170 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/4170 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/90922 "Build is in progress. Recent messages:Running configuration") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/83477 "Build is in progress. Recent messages:") | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-2-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/12069 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/90922 "Build is in progress. Recent messages:Running configuration") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 vision-sim](https://ews-build.webkit.org/#/builders/121/builds/11954 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/90922 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/55/builds/38765 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 playstation ](https://ews-build.webkit.org/#/builders/PlayStation-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2025-01-13 14:45 UTC, zhani commented
> I don't think commit-queue can handle more than one patch per PR

Good to know. I created separate PR for it https://github.com/WebKit/WebKit/pull/38935

2025-01-14 08:32 UTC, carlosgcampos approved these changes

2025-01-14 08:34 UTC, merged