Web processes should only commit history state for navigating frames and their children
WebKit/WebKit pull request #38410
Opened 2024-12-29 02:37 UTC by charliewolfe

#### 8e79405c4a291f40a104001e16895d4a378555ed
<pre>
Web processes should only commit history state for navigating frames and their children
<a href="https://bugs.webkit.org/show_bug.cgi?id=285224">https://bugs.webkit.org/show_bug.cgi?id=285224</a>
<a href="https://rdar.apple.com/142134339">rdar://142134339</a>

Reviewed by NOBODY (OOPS!).

Currently, when a frame navigates, the web process creates history state for the entire frame tree to be
committed to the UI process. This needs to change with site isolation because a navigating iframe may
have parent frames that are out-of-process, for which we cannot synchronously create history state.
Instead, when a frame navigates, the web process should only create and commit history state for the
navigating frame and its children. If the navigating frame is a child frame, we can use the current item
in the UI process&apos;s back/forward list to populate the history state for its parent frames.

This change should not affect behavior yet (hopefully). More details below.

* Source/WebCore/history/BackForwardClient.h:
* Source/WebCore/history/BackForwardController.cpp:
(WebCore::BackForwardController::addItem):
* Source/WebCore/history/BackForwardController.h:
* Source/WebCore/loader/EmptyClients.cpp:
The parameter indicating which frame is being navigated can be removed, since the frame at the top of the
tree being committed will now always be the navigating frame.

* Source/WebCore/loader/HistoryController.cpp:
(WebCore::HistoryController::goToItem):
(WebCore::HistoryController::goToItemForNavigationAPI):
Removed the isRootFrame assertions, as they are no longer valid.

(WebCore::HistoryController::updateBackForwardListClippedAtTarget):
Call createItemTree on the navigating frame instead of the root frame.

(WebCore::HistoryController::pushState):
* Source/WebCore/page/Page.cpp:
(WebCore::Page::goToItem):
(WebCore::Page::goToItemForNavigationAPI):
* Source/WebKit/Shared/SessionState.cpp:
(WebKit::FrameState::replaceChildFrameState):
* Source/WebKit/Shared/SessionState.h:
* Source/WebKit/Shared/WebBackForwardListFrameItem.cpp:
(WebKit::WebBackForwardListFrameItem::url const):
(WebKit::WebBackForwardListFrameItem::mainFrame):
* Source/WebKit/Shared/WebBackForwardListFrameItem.h:
* Source/WebKit/Shared/WebBackForwardListItem.cpp:
(WebKit::WebBackForwardListItem::create):
(WebKit::WebBackForwardListItem::WebBackForwardListItem):
(WebKit::WebBackForwardListItem::~WebBackForwardListItem):
(WebKit::WebBackForwardListItem::itemIsInSameDocument const):
(WebKit::WebBackForwardListItem::itemIsClone):
(WebKit::WebBackForwardListItem::itemID const):
(WebKit::WebBackForwardListItem::navigatedFrameState const):
(WebKit::WebBackForwardListItem::mainFrameState const):
(WebKit::WebBackForwardListItem::originalURL const):
(WebKit::WebBackForwardListItem::url const):
(WebKit::WebBackForwardListItem::title const):
(WebKit::WebBackForwardListItem::wasCreatedByJSWithoutUserInteraction const):
(WebKit::WebBackForwardListItem::setWasRestoredFromSession):
(WebKit::WebBackForwardListItem::navigatedFrameItem const):
(WebKit::WebBackForwardListItem::protectedNavigatedFrameItem const):
(WebKit::WebBackForwardListItem::mainFrameItem const):
(WebKit::WebBackForwardListItem::setRootFrameState): Deleted.
(WebKit::WebBackForwardListItem::rootFrameState const): Deleted.
(WebKit::WebBackForwardListItem::rootFrameItem): Deleted.
Replace rootFrameState() and rootFrameItem() with mainFrameState() and mainFrameItem(), as each item
should now have a WebBackForwardListFrameItem for the main frame.

(WebKit::WebBackForwardListItem::protectedRootFrameItem): Deleted.
(WebKit::WebBackForwardListItem::setParentFromItem): Deleted.
This function is no longer needed because items for remote child frame navigations now have their parents
set during WebBackForwardListItem construction.

* Source/WebKit/Shared/WebBackForwardListItem.h:
(WebKit::WebBackForwardListItem::setNavigatedFrameID): Deleted.
* Source/WebKit/UIProcess/API/APINavigation.cpp:
(API::Navigation::Navigation):
* Source/WebKit/UIProcess/API/APINavigation.h:
(API::Navigation::create):
(API::Navigation::targetItem const):
(API::Navigation::protectedTargetItem const):
(API::Navigation::targetFrameItem const):
Changed m_targetItem to hold a WebBackForwardListFrameItem, so we can use it to navigate the correct
frame in ProvisionalPageProxy::goToBackForwardItem().

* Source/WebKit/UIProcess/API/Cocoa/WKBackForwardListItem.mm:
(-[WKBackForwardListItem _scrollPosition]):
* Source/WebKit/UIProcess/ProvisionalPageProxy.cpp:
(WebKit::ProvisionalPageProxy::goToBackForwardItem):
(WebKit::ProvisionalPageProxy::backForwardAddItem):
* Source/WebKit/UIProcess/ProvisionalPageProxy.h:
* Source/WebKit/UIProcess/WebBackForwardList.cpp:
(WebKit::WebBackForwardList::addItem):
(WebKit::WebBackForwardList::backForwardListState const):
(WebKit::WebBackForwardList::restoreFromState):
completeFrameStateForNavigation() needs to refer to the current back/forward item to correctly complete
frame state for navigating child frame items. So, m_provisionalIndex is cleared earlier, and
m_currentIndex now points to the last entry in m_entries during restoration of the back/forward list.

(WebKit::WebBackForwardList::completeFrameStateForNavigation):
This function completes the FrameState for navigating child frames. The BackForwardItemIdentifiers from
the current item are regenerated when set on the new item, as the web process must be able to uniquely
address each WebBackForwardListFrameItem.

* Source/WebKit/UIProcess/WebBackForwardList.h:
* Source/WebKit/UIProcess/WebNavigationState.cpp:
(WebKit::WebNavigationState::createBackForwardNavigation):
* Source/WebKit/UIProcess/WebNavigationState.h:
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::launchProcessForReload):
(WebKit::WebPageProxy::goForward):
(WebKit::WebPageProxy::goBack):
(WebKit::WebPageProxy::goToBackForwardItem):
(WebKit::WebPageProxy::continueNavigationInNewProcess):
(WebKit::WebPageProxy::decidePolicyForNavigationAction):
(WebKit::WebPageProxy::backForwardAddItem):
(WebKit::WebPageProxy::backForwardAddItemShared):
(WebKit::WebPageProxy::backForwardItemAtIndex):
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/UIProcess/WebPageProxy.messages.in:
* Source/WebKit/WebProcess/WebPage/WebBackForwardListProxy.cpp:
(WebKit::WebBackForwardListProxy::addItem):
* Source/WebKit/WebProcess/WebPage/WebBackForwardListProxy.h:
* Source/WebKitLegacy/mac/History/BackForwardList.h:
* Source/WebKitLegacy/mac/History/BackForwardList.mm:
(BackForwardList::addItem):
* Source/WebKitLegacy/mac/History/WebBackForwardList.mm:
(-[WebBackForwardList addItem:]):
(-[WebBackForwardList setToMatchDictionaryRepresentation:]):
* Source/WebKitLegacy/mac/WebView/WebView.mm:
(-[WebView _loadBackForwardListFromOtherView:]):
</pre>

2024-12-29 02:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8e79405c4a291f40a104001e16895d4a378555ed. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-29 02:37 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/8e79405c4a291f40a104001e16895d4a378555ed)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/82480 "Build is in progress. Recent messages:Running configuration") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/33541 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/84582 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/2212 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/10035 "Build is in progress. Recent messages:") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 win-tests](https://ews-build.webkit.org/#/builders/59/builds/33541 "Build is in progress. Recent messages:Printed configuration") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/85545 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/2212 "Build is in progress. Recent messages:") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🧪 webkitpy ](https://ews-build.webkit.org/#/builders/WebKitPy-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/2212 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/2212 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/88969 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-2-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/10035 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/2/builds/88969 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/2/builds/88969 "Build is in progress. Recent messages:Running configuration") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-intel-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 playstation ](https://ews-build.webkit.org/#/builders/PlayStation-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2024-12-29 02:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/287f7c0655ae30c4eba4b955b666a5f1544dcd6b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-29 02:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/287f7c0655ae30c4eba4b955b666a5f1544dcd6b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 02:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a5f799f768557998a5b027ee12626b025ef4a50. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 02:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a5f799f768557998a5b027ee12626b025ef4a50. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/945614f185fdbb4ce4997b4c450a06b27242e631. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/945614f185fdbb4ce4997b4c450a06b27242e631. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/758d05c7def7d6ffd27b307845c02f27e5776feb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:30 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/758d05c7def7d6ffd27b307845c02f27e5776feb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/98c931a3ad6bfeb3c073e309ed26a4e1a788fdf6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2024-12-31 03:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/98c931a3ad6bfeb3c073e309ed26a4e1a788fdf6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-01 05:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2a86dfa16962f06dd65368bffeae6c00f796ce00. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-01 05:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2a86dfa16962f06dd65368bffeae6c00f796ce00. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-02 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/37283ec633a358a77805390af43094272a95278a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-02 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/37283ec633a358a77805390af43094272a95278a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-02 21:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d01c9d781adba9adbb9227129b213d2314adb7b2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-02 21:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d01c9d781adba9adbb9227129b213d2314adb7b2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-02 22:39 UTC, achristensen07 requested changes

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/UIProcess/WebPageProxy.cpp
> +    Ref frameState = WebFrameProxy::webFrame(frameItem.frameID()) ? frameItem.copyFrameStateWithChildren() : item->mainFrameState();
I don't think I understand this condition or when it would fail.

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/UIProcess/WebBackForwardList.cpp
> +    auto* item = WebBackForwardListItem::itemForID(identifier);
RefPtr

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/UIProcess/ProvisionalPageProxy.cpp
> +    page->maybeInitializeSandboxExtensionHandle(process(), itemURL, item.resourceDirectoryURL(), true, [weakThis = WeakPtr { *this }, itemURL, frameState = WTFMove(frameState), navigationLoadType = *
This capture list may be worth putting each item on its own line.

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/APINavigation.h
> +#include "WebBackForwardListFrameItem.h"
Can a forward declaration suffice?

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/Shared/WebBackForwardListFrameItem.cpp
> +const String& WebBackForwardListFrameItem::url() const
urlString?

2025-01-02 22:39 UTC, achristensen07 commented on Source/WebKit/Shared/WebBackForwardListFrameItem.cpp
> +    return *m_frameState->frameItemID;
Can we express in the type that this is always present without dereferencing an optional?

2025-01-02 22:39 UTC, achristensen07 commented on Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
> +UpdateHistoryByNavigatingFrame:
Could we use a FrameLoaderClient call instead of adding a preference?  This is just to distinguish WebKitLegacy from modern WebKit, right?  We don't actually need this to be runtime configurable.

2025-01-02 23:22 UTC, charliewolfe commented on Source/WebKit/UIProcess/WebPageProxy.cpp
> +    Ref frameState = WebFrameProxy::webFrame(frameItem.frameID()) ? frameItem.copyFrameStateWithChildren() : item->mainFrameState();
If a frame no longer exists for some reason, such as when the web process crashes and the page is reloaded, we cannot instruct the web process to load a history item into it and should instead send the entire frame tree. I’ll mention this in the commit message.

2025-01-02 23:23 UTC, charliewolfe commented on Source/WebKit/Shared/WebBackForwardListFrameItem.cpp
> +const String& WebBackForwardListFrameItem::url() const
This matches `WebBackForwardListItem::url()`. I can change both but maybe not in this PR?

2025-01-02 23:23 UTC, charliewolfe commented on Source/WebKit/UIProcess/API/APINavigation.h
> +#include "WebBackForwardListFrameItem.h"
Yes

2025-01-03 02:47 UTC, webkit-early-warning-system commented
EWS run on current version of this PR (hash https://github.com/WebKit/WebKit/commit/3f3a3fce4d55771f058b31d4ebecb3308fd79a4a)<details>

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/83018 "Build is in progress. Recent messages:") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 win ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/85110 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/130/builds/2734 "Build is in progress. Recent messages:") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/123/builds/10579 "Build is in progress. Recent messages:") | [⏳ 🧪 wpe-wk2 ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 win-tests ](https://ews-build.webkit.org/#/builders/Win-Build-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/130/builds/2734 "Build is in progress. Recent messages:") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-wpe ](https://ews-build.webkit.org/#/builders/WPE-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🧪 webkitpy ](https://ews-build.webkit.org/#/builders/WebKitPy-Tests-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/130/builds/2734 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe-cairo ](https://ews-build.webkit.org/#/builders/WPE-Cairo-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/130/builds/2734 "Build is in progress. Recent messages:") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 🧪 jsc-arm64](https://ews-build.webkit.org/#/builders/12/builds/82063 "Build is in progress. Recent messages:") | [⏳ 🛠 vision ](https://ews-build.webkit.org/#/builders/visionOS-2-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/123/builds/10579 "Build is in progress. Recent messages:") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 vision-sim ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 vision-wk2 ](https://ews-build.webkit.org/#/builders/visionOS-2-Simulator-WK2-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-intel-wk2 ](https://ews-build.webkit.org/#/builders/macOS-Ventura-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 playstation ](https://ews-build.webkit.org/#/builders/PlayStation-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-18-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-safer-cpp ](https://ews-build.webkit.org/#/builders/macOS-Safer-CPP-Checks-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-18-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-11-Build-EWS "Waiting in queue, processing has not started yet") | | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-11-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | | | </details>

2025-01-03 02:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f3a3fce4d55771f058b31d4ebecb3308fd79a4a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-03 03:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2b2125d1986978da5ba1cd5b5c81995dbf2b821a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-03 03:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2b2125d1986978da5ba1cd5b5c81995dbf2b821a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-03 10:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9dc8a16c48ff760d73867190193de6fd278ebcda. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-03 10:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9dc8a16c48ff760d73867190193de6fd278ebcda. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/38410

2025-01-03 15:12 UTC, achristensen07 commented on Source/WebKit/Shared/WebBackForwardListFrameItem.cpp
> +const String& WebBackForwardListFrameItem::url() const
no, this is fine.

2025-01-03 15:12 UTC, achristensen07 approved these changes

2025-01-03 18:38 UTC, webkit-commit-queue commented
Committed 288409@main (9b13b53b41a1): <https://commits.webkit.org/288409@main>

Reviewed commits have been landed. Closing PR #38410 and removing active labels.

2025-01-03 18:38 UTC, merged