Upstream macOS Ventura results from internal to open source
WebKit/WebKit pull request #3874
Opened 2022-08-31 20:30 UTC by robert-jenner

#### 8f4cc8c44299a91bf12ea73ebc05f99c9d91840e
<pre>
Upstream macOS Ventura results from internal to open source
<a href="https://bugs.webkit.org/show_bug.cgi?id=244551">https://bugs.webkit.org/show_bug.cgi?id=244551</a>

Reviewed by NOBODY (OOPS!).

* LayoutTests/platform/mac-ventura-wk1/TestExpectations: Added.
* LayoutTests/platform/mac-ventura-wk1/fast/events/wheel/wheelevent-in-horizontal-scrollbar-in-rtl-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk1/fast/events/wheel/wheelevent-in-vertical-scrollbar-in-rtl-expected.txt: Added.
* LayoutTests/platform/mac-ventura-wk2/TestExpectations: Added.
* LayoutTests/platform/mac-ventura-wk2/imported/w3c/web-platform-tests/html/canvas/element/manual/wide-gamut-canvas/canvas-createImageBitmap-e_srgb-expected.txt: Added.
* LayoutTests/platform/mac-ventura/TestExpectations: Added.
* LayoutTests/platform/mac-ventura/accessibility/math-multiscript-attributes-expected.txt: Added.
* LayoutTests/platform/mac-ventura/fast/events/mouse-cursor-multiframecur-expected.txt: Added.
* LayoutTests/platform/mac-ventura/fast/invalid/missing-end-tag-expected.txt: Added.
* LayoutTests/platform/mac-ventura/http/tests/security/xss-DENIED-xsl-external-entity-expected.txt: Added.
* LayoutTests/platform/mac-ventura/http/tests/security/xss-DENIED-xsl-external-entity-redirect-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/cookies/value/value-ctl-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/html/dom/documents/resource-metadata-management/document-cookie-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/display-2-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/ignored-properties-001-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/not-participating-to-parent-layout-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/padding-border-margin/border-002-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/padding-border-margin/margin-003-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/css-styling/padding-border-margin/padding-002-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/mathml/relations/html5-tree/dynamic-childlist-001-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/svg/import/animate-elem-35-t-manual-expected.txt: Added.
* LayoutTests/platform/mac-ventura/imported/w3c/web-platform-tests/svg/path/distance/pathlength-path-expected.txt: Added.
* LayoutTests/platform/mac-ventura/math-multiscript-attributes-expected.txt: Added.
* LayoutTests/platform/mac-ventura/media/media-can-play-av1-expected.txt: Added.
* LayoutTests/platform/mac-ventura/svg/custom/use-invalid-pattern-expected.txt: Added.
* LayoutTests/platform/mac-ventura/svg/custom/use-invalid-style-expected.txt: Added.
* LayoutTests/platform/mac-ventura/svg/hixie/error/012-expected.txt: Added.
* Tools/Scripts/webkitpy/port/mac.py:
(MacPort):
* Tools/Scripts/webkitpy/port/mac_unittest.py:
(MacTest.test_ventura_baseline_search_path):
(MacTest.test_monterey_baseline_search_path): Deleted.
</pre>

2022-08-31 20:31 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/8f4cc8c44299a91bf12ea73ebc05f99c9d91840e

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [⏳ 🧪 style ](https://ews-build.webkit.org/#/builders/Style-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 bindings ](https://ews-build.webkit.org/#/builders/Bindings-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitpy](https://ews-build.webkit.org/#/builders/5/builds/91378 "Build is in progress") | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/86853 "Build is in progress") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-8-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-mips ](https://ews-build.webkit.org/#/builders/JSC-MIPSEL-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-8-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 jsc-mips-tests ](https://ews-build.webkit.org/#/builders/JSC-MIPSEL-32bits-Build-EWS "Waiting in queue, processing has not started yet") |

2022-08-31 21:01 UTC, JonWBedard approved these changes

2022-08-31 21:07 UTC, JonWBedard requested changes

2022-08-31 21:07 UTC, JonWBedard commented on Tools/Scripts/webkitpy/port/mac.py
> +    CURRENT_VERSION = Version(13, 0)
This might be breaking more webkitpy tests, by the look of EWS.

2022-08-31 22:13 UTC, robert-jenner commented on Tools/Scripts/webkitpy/port/mac.py
> +    CURRENT_VERSION = Version(13, 0)
Interesting. I wonder why? It's the same change that we have done in the past. Just bumping up the OS version number.

2022-09-01 00:10 UTC, JonWBedard commented on Tools/Scripts/webkitpy/port/mac.py
> +    CURRENT_VERSION = Version(13, 0)
Investigated the root cause of this and fixing it in #3889

2022-09-01 00:11 UTC, JonWBedard approved these changes

2022-09-01 01:13 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/2dec5e4130d8254799769385291cb79d315e77a9

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/87830 "failed Failed to checkout and rebase branch from PR 3874") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/31923 "failed Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 bindings ](https://ews-build.webkit.org/#/builders/Bindings-Tests-EWS "Waiting in queue, processing has not started yet") | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/30285 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/30285 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [❌ 🧪 webkitpy](https://ews-build.webkit.org/#/builders/5/builds/91435 "failed Failed to checkout and rebase branch from PR 3874") | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/30285 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/86903 "Build is in progress") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [❌ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/29628 "failed Failed to checkout and rebase branch from PR 3874") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-8-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | |

2022-09-01 01:31 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/9605555d4568b17bf744a99f6561593813ff8002

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/87832 "failed Failed to checkout and rebase branch from PR 3874") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/31926 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| [❌ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/91800 "failed Failed to checkout and rebase branch from PR 3874") | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/30288 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/93447 "Build is in progress") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/30288 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 webkitpy](https://ews-build.webkit.org/#/builders/5/builds/91437 "Build is in progress") | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/30288 "Failed to checkout and rebase branch from PR 3874") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/86905 "Build is in progress") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [❌ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/29631 "failed Failed to checkout and rebase branch from PR 3874") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [❌ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/29519 "failed Failed to checkout and rebase branch from PR 3874") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | |

2022-09-01 01:31 UTC, closed without merging

2022-09-01 01:31 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/d636fb995b38d7bd803665f1eb1899e02231389c

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [  ~~🧪 style~~](https://ews-build.webkit.org/#/builders/6/builds/87835 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/31928 "failed Failed to checkout and rebase branch from PR 3874") | [  ~~🛠 mac~~](https://ews-build.webkit.org/#/builders/43/builds/18552 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wpe~~](https://ews-build.webkit.org/#/builders/8/builds/97011 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 🧪 win~~](https://ews-build.webkit.org/#/builders/10/builds/151516 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [  ~~🧪 bindings~~](https://ews-build.webkit.org/#/builders/11/builds/91803 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/30290 "failed Failed to checkout and rebase branch from PR 3874") | [  ~~🛠 mac-debug~~](https://ews-build.webkit.org/#/builders/71/builds/26347 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/79922 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🛠 wincairo~~](https://ews-build.webkit.org/#/builders/12/builds/91755 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") 
| [  ~~🧪 webkitperl~~](https://ews-build.webkit.org/#/builders/19/builds/93449 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/64/builds/30290 "failed Failed to checkout and rebase branch from PR 3874") | [  ~~🛠 mac-AS-debug~~](https://ews-build.webkit.org/#/builders/61/builds/74554 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 gtk-wk2~~](https://ews-build.webkit.org/#/builders/36/builds/79922 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| [  ~~🧪 webkitpy~~](https://ews-build.webkit.org/#/builders/5/builds/91440 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [❌ 🧪 api-ios](https://ews-build.webkit.org/#/builders/64/builds/30290 "failed Failed to checkout and rebase branch from PR 3874") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/43/builds/18552 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/36/builds/79922 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | 
| | [  ~~🛠 tv~~](https://ews-build.webkit.org/#/builders/66/builds/27956 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/43/builds/18552 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 tv-sim~~](https://ews-build.webkit.org/#/builders/67/builds/27940 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2~~](https://ews-build.webkit.org/#/builders/43/builds/18552 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [❌ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/29633 "failed Failed to checkout and rebase branch from PR 3874") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/61/builds/74554 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [  ~~🛠 watch-sim~~](https://ews-build.webkit.org/#/builders/65/builds/29521 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [  ~~🧪 mac-wk2-stress~~](https://ews-build.webkit.org/#/builders/43/builds/18552 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | |