Remove extra whitespace
WebKit/WebKit pull request #3999
Opened 2022-09-03 22:36 UTC by ChaseKnowlden

#### e43ec0c7e6e2299384750f3b4c22275e5c77e093
<pre>
Remove extra whitespace
</pre>
----------------------------------------------------------------------
#### 9a9b5e21bc61baafc73eb7ffd8c12296b26c739a
<pre>
Add whitespace
</pre>
----------------------------------------------------------------------
#### ffbf79fdece083b5988176a42dc02ca0b38220fb
<pre>
Add closing brackets to overflow
</pre>

2022-09-03 22:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e43ec0c7e6e2299384750f3b4c22275e5c77e093. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/3999

2022-09-06 20:20 UTC, fujii commented on Source/WebCore/css/parser/CSSPropertyParser.cpp
>          yValueID = m_range.consumeIncludingWhitespace().id();
I think this change doesn't conform to WebKit style. https://webkit.org/code-style-guidelines/#braces-one-line

2022-09-08 01:06 UTC, smfr requested changes
Please use `git webkit pr` to generate the PR, which should have a corresponding bugs.webkit.org entry describing the bug being fixed.

2022-09-22 21:10 UTC, ChaseKnowlden commented
Sorry about that

2022-09-22 21:10 UTC, closed without merging