Add _WKWebsiteDataStoreConfiguration SPI to set resourceLoadStatisticsDebugMode on WebsiteDataStore creation
WebKit/WebKit pull request #4089
Opened 2022-09-07 06:57 UTC by szewai

#### 1a5e981285ba7afa59533547711790567603bd80
<pre>
Add _WKWebsiteDataStoreConfiguration SPI to set resourceLoadStatisticsDebugMode on WebsiteDataStore creation
<a href="https://bugs.webkit.org/show_bug.cgi?id=244880">https://bugs.webkit.org/show_bug.cgi?id=244880</a>

Reviewed by NOBODY (OOPS!).

WebKit should let client pass the value instead of reading it from NSUserDefaults.

* Source/WebKit/UIProcess/API/C/WKWebsiteDataStoreConfigurationRef.cpp:
(WKWebsiteDataStoreConfigurationGetResourceLoadStatisticsDebugModeEnabled):
(WKWebsiteDataStoreConfigurationSetResourceLoadStatisticsDebugModeEnabled):
* Source/WebKit/UIProcess/API/C/WKWebsiteDataStoreConfigurationRef.h:
* Source/WebKit/UIProcess/API/Cocoa/_WKWebsiteDataStoreConfiguration.h:
* Source/WebKit/UIProcess/API/Cocoa/_WKWebsiteDataStoreConfiguration.mm:
(-[_WKWebsiteDataStoreConfiguration resourceLoadStatisticsDebugModeEnabled]):
(-[_WKWebsiteDataStoreConfiguration setResourceLoadStatisticsDebugModeEnabled:]):
* Source/WebKit/UIProcess/WebsiteData/Cocoa/WebsiteDataStoreCocoa.mm:
(WebKit::WebsiteDataStore::platformSetNetworkParameters):
* Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp:
(WebKit::WebsiteDataStore::WebsiteDataStore):
(WebKit::WebsiteDataStore::parameters):
* Source/WebKit/UIProcess/WebsiteData/WebsiteDataStoreConfiguration.cpp:
(WebKit::WebsiteDataStoreConfiguration::copy const):
* Source/WebKit/UIProcess/WebsiteData/WebsiteDataStoreConfiguration.h:
(WebKit::WebsiteDataStoreConfiguration::resourceLoadStatisticsDebugModeEnabled const):
(WebKit::WebsiteDataStoreConfiguration::setResourceLoadStatisticsDebugModeEnabled):
</pre>

2022-09-07 06:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1a5e981285ba7afa59533547711790567603bd80. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4089

2022-09-07 17:02 UTC, smfr approved these changes

2022-09-07 19:35 UTC, achristensen07 requested changes

2022-09-07 19:35 UTC, achristensen07 commented on Source/WebKit/UIProcess/API/C/WKWebsiteDataStoreConfigurationRef.h
> +WK_EXPORT bool WKWebsiteDataStoreConfigurationGetResourceLoadStatisticsDebugModeEnabled(WKWebsiteDataStoreConfigurationRef configuration);
Please don't add new C API unless absolutely necessary, and I don't think it is in this case.

2022-09-08 16:12 UTC, webkit-early-warning-system commented
https://github.com/WebKit/WebKit/commit/07660b605330465aa440f7fcfe7605b58e5b4f08

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/88607 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/33169 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/19494 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/97799 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/31661 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/27249 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/80832 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/92435 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/94237 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/68/builds/25117 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/75553 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/25055 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/80002 "Passed tests") | [  ~~🧪 api-mac~~](https://ews-build.webkit.org/#/builders/3/builds/80073 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/68018 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/29336 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/14072 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/29191 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/15085 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/3023 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/32609 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/38013 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/31316 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/34194 "Passed tests") | |

2022-09-08 19:32 UTC, webkit-commit-queue commented
Committed 254280@main (6663b6575694): <https://commits.webkit.org/254280@main>

Reviewed commits have been landed. Closing PR #4089 and removing active labels.

2022-09-08 19:32 UTC, merged