The DecompressionStream constructor incorrectly throws when the parameter is not a String
WebKit/WebKit pull request #4149
Opened 2022-09-09 03:14 UTC by cdumez

#### eaf89255fa1eded03a5628aaed207791d42db75a
<pre>
The DecompressionStream constructor incorrectly throws when the parameter is not a String
<a href="https://bugs.webkit.org/show_bug.cgi?id=244958">https://bugs.webkit.org/show_bug.cgi?id=244958</a>

Reviewed by NOBODY (OOPS!).

* LayoutTests/imported/w3c/web-platform-tests/compression/decompression-constructor-error.tentative.any-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/compression/decompression-constructor-error.tentative.any.serviceworker-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/compression/decompression-constructor-error.tentative.any.sharedworker-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/compression/decompression-constructor-error.tentative.any.worker-expected.txt:
* Source/WebCore/Modules/compression/DecompressionStream.js:
(initializeDecompressionStream):
</pre>

2022-09-09 03:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eaf89255fa1eded03a5628aaed207791d42db75a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4149

2022-09-09 14:04 UTC, stwrt requested changes
Overall this change looks pretty good; just would like to see the equivalent changes in CompressionStream.js.

2022-09-09 14:04 UTC, stwrt commented on Source/WebCore/Modules/compression/DecompressionStream.js
> +    const lowercaseFormat = String(arguments[0]).toLowerCase();
Can you please make the equivalent change in CompressionStream.js.

We should also add a WPT test for compression constructor errors, but that is out of scope of this patch.

2022-09-09 15:10 UTC, youennf approved these changes

2022-09-09 15:12 UTC, cdumez commented
WPT test PR: https://github.com/web-platform-tests/wpt/pull/35847

2022-09-09 15:21 UTC, stwrt commented
LGTM

2022-09-09 17:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8b59070f31d1843df9ccec7d00fa07a0f220b704. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4149

2022-09-12 21:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/30d232ffaa3d25b7aaa3fefa68606a8af95f1cc1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4149

2022-09-12 22:29 UTC, merged

2022-09-12 22:30 UTC, webkit-commit-queue commented
Committed 254411@main (03f571c3f5f8): <https://commits.webkit.org/254411@main>

Reviewed commits have been landed. Closing PR #4149 and removing active labels.