Remove checks for A8 devices now that they are no longer supported
WebKit/WebKit pull request #4162
Opened 2022-09-09 13:30 UTC by AtariDreams

As of iOS 16, A8 devices are no longer supported

2022-09-09 17:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/df1b8cb7a9942d9245bbf9f9412ef4409b95f743. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4162

2022-09-09 22:53 UTC, Constellation commented
Thanks! Can you follow the instructions in https://webkit.org/contributing-code/ and https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code
WebKit requires a certain format of commit message describing the change in detail.

2022-09-11 20:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a583d53ad46795c9f09b7b65b6658eaf644df0b1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4162

2022-11-02 17:04 UTC, Constellation requested changes

2022-11-02 17:04 UTC, Constellation commented on Source/bmalloc/bmalloc/Mutex.cpp
> +        for (size_t i = aLot; i > 0; --i) {
We do not need this change in this PR.

2022-11-02 17:04 UTC, Constellation commented on .gitignore
> +/Index
We do not need this change in this PR.

2022-11-08 21:12 UTC, AtariDreams commented
Fixed!

2022-11-08 21:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/001f2b06cfb6e34c9ae5b82973ce1f953c3ed162. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4162

2022-11-08 21:22 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/4e463f328d0218dba8dae53746ce5e468879ca4f)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [⏳ 🧪 style ](https://ews-build.webkit.org/#/builders/Style-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 bindings ](https://ews-build.webkit.org/#/builders/Bindings-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [⏳ 🧪 webkitperl ](https://ews-build.webkit.org/#/builders/WebKitPerl-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-15-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| [⏳ 🧪 services ](https://ews-build.webkit.org/#/builders/Services-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-15-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-8-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [⏳ 🛠 watch-sim ](https://ews-build.webkit.org/#/builders/watchOS-8-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | </details>

2022-11-09 14:18 UTC, AtariDreams commented on Source/bmalloc/bmalloc/Mutex.cpp
> +        for (size_t i = aLot; i > 0; --i) {
Fixed!

2022-11-09 14:18 UTC, AZero13 commented on .gitignore
> +/Index
Fixed!

2023-01-19 16:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e55524565ba27531d4ab992825569a1c127a360b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4162

2023-01-19 16:52 UTC, AtariDreams commented
@Constellation Could you please look at this now?

2023-01-20 20:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f05fdd19144eb40dfaafc422d35233b6c442bc18. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4162

2023-01-21 01:04 UTC, closed without merging