fix(css): unprefixed keyframes name now support <string> name
WebKit/WebKit pull request #4234
Opened 2022-09-11 10:00 UTC by CGQAQ

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2022-09-11 10:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cc5722ab3531eaa230aed4a8326ea710c3d2263c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4234

2022-09-13 01:54 UTC, nt1m requested changes
Thanks for the PR! Can you please fix the build error (unused parameter webkitPrefixed)?

2022-09-13 02:02 UTC, CGQAQ commented
> Thanks for the PR! Can you please fix the build error (unused parameter webkitPrefixed)?

sure, I'll fix it tonight

2022-09-13 12:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f985444bc396a8b0ac89105eea4ab6d26d5d44c7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4234

2022-09-13 12:18 UTC, nt1m approved these changes
This looks good, thanks! Though in order for the PR to land through the bots, you need to squash your commits and edit your commit message to something like this:

```
Support <string> as unprefixed keyframe name
https://bugs.webkit.org/show_bug.cgi?id=245132

Reviewed by Tim Nguyen.

Source: https://drafts.csswg.org/css-animations/#keyframes

> Keyframes are specified using the @keyframes at-rule, defined as follows:
> @keyframes = @keyframes <keyframes-name> { <rule-list> }
> <keyframes-name> = <custom-ident> | <string>

* Source/WebCore/css/parser/CSSParserImpl.cpp:
(CSSParserImpl::consumeAtRule)
(CSSParserImpl::consumeKeyframesRule):
* Source/WebCore/css/parser/CSSParserImpl.h:
```

Normally `git-webkit setup` then `git-webkit commit -i 245132 -a` should just auto-generate that for you, but squashing and changing the commit message to what I quoted should be sufficient. Let me know if you need help doing this.

2022-09-13 12:21 UTC, nt1m commented
I can just force-push to your branch with those changes if you want.

2022-09-13 15:25 UTC, CGQAQ commented
squashed @nt1m

2022-09-13 15:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2e0ee2ebfd1e75273e698069dcc6e7bbbf126f07. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4234

2022-09-13 17:05 UTC, webkit-commit-queue commented
Committed 254444@main (7c27f43d202e): <https://commits.webkit.org/254444@main>

Reviewed commits have been landed. Closing PR #4234 and removing active labels.

2022-09-13 17:05 UTC, merged

2022-09-15 03:10 UTC, yisibl commented
@nt1m Do you know which version of Safari Technology Preview this is expected to be released to?

CGQAQ and I are working on implementing interoperability of `<keyframes-name>` across browsers( [Blink CL](https://chromium-review.googlesource.com/c/chromium/src/+/3865188)).

2022-09-15 05:19 UTC, nt1m commented
@yisibl I don't know exactly, but the timing of previous STPs should give an estimate: https://webkit.org/blog/category/safari-technology-preview/

2022-09-19 04:55 UTC, yisibl commented
Before this commit, if you want to use `@keyframes <string>` you must prefix it with `-webkit-`. That means prefix-less `animation-name` supports `<string>` but not in `@keyframes`.

## Test case

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test @keyframes `<string>`</title>
    <style>
        /* For Safari 16.1- */
        @-webkit-keyframes "foo" {
            to {
                background: green
            }
        }
        
        /* For Safari 16.1+  */
        @keyframes "foo" {
            to {
                background: green
            }
        }

        body {
            background: red;
            animation: "foo" 0s ease 1 both;
        }
    </style>
</head>

<body>
</body>
</html>
```