Prevent calling an AT-SPI observer from invalidating map iterators
WebKit/WebKit pull request #4377
Opened 2022-09-15 11:26 UTC by obyknovenius

#### 13551af0bd1a99edaa484e7c7f031cdc5233dfe3
<pre>
Prevent calling an AT-SPI observer from invalidating map iterators
<a href="https://bugs.webkit.org/show_bug.cgi?id=245214">https://bugs.webkit.org/show_bug.cgi?id=245214</a>

Reviewed by NOBODY (OOPS!).

Calling an AT-SPI observer while iterating over the map of observers can
exectute arbitrary code, including removing the observer from the map
and thus invalidating the iterator.

To prevent this, we first collect all the observers into a vector and
then call them.

* Source/WebCore/accessibility/atspi/AccessibilityAtspi.cpp:
(WebCore::AccessibilityAtspi::notify const):
(WebCore::AccessibilityAtspi::notifyStateChanged const):
(WebCore::AccessibilityAtspi::notifySelectionChanged const):
(WebCore::AccessibilityAtspi::notifyMenuSelectionChanged const):
(WebCore::AccessibilityAtspi::notifyTextChanged const):
(WebCore::AccessibilityAtspi::notifyTextCaretMoved const):
(WebCore::AccessibilityAtspi::notifyValueChanged const):
(WebCore::AccessibilityAtspi::notifyLoadEvent const):
* Source/WebCore/accessibility/atspi/AccessibilityAtspi.h:
</pre>

2022-09-15 11:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13551af0bd1a99edaa484e7c7f031cdc5233dfe3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4377

2022-09-15 11:28 UTC, obyknovenius commented on Source/WebCore/accessibility/atspi/AccessibilityAtspi.cpp
> +        (*observer)(atspiObject, name, parameter);
Is there a better way to express it?

2022-09-15 15:22 UTC, mcatanzaro commented
Looks like this broke several a11y tests. :(

2022-09-15 15:39 UTC, mcatanzaro requested changes

2022-09-15 15:39 UTC, mcatanzaro commented on Source/WebCore/accessibility/atspi/AccessibilityAtspi.cpp
> +    Vector<const NotificationObserver*> observers(m_notificationObservers.size());
I don't think this is enough, because the observers are owned by the map `m_notificationObservers` but not by your vector here. So if they're removed from the map, then calling them from here would be a use-after-free.

I think you could copy them, though.

2022-09-16 14:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fb4a3060068c332b3f15ba5108b6c187dfbf8382. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4377

2022-09-18 16:41 UTC, philn commented
> Looks like this broke several a11y tests. :(

Gardening in https://bugs.webkit.org/show_bug.cgi?id=245338

2022-09-18 16:45 UTC, philn commented
> > Looks like this broke several a11y tests. :(
> 
> Gardening in https://bugs.webkit.org/show_bug.cgi?id=245338

@obyknovenius Please unflag those tests in the patch fixing the crashes.

2022-09-18 17:36 UTC, mcatanzaro commented
This didn't land yet. I was only noting failures on the EWS.

2022-09-18 17:46 UTC, philn commented
> This didn't land yet. I was only noting failures on the EWS.

Ah OK. The ones I flagged are happening right now on post-landing test bots.

2022-09-19 08:16 UTC, carlosgcampos reviewed
I think the fix is easier, we just need to replace m_notificationObservers.values() in all for loops by copyToVector(m_notificationObservers.values()).

2022-09-19 16:37 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/06d23143f150c934172ab95b4aef2bf8dbb20f4b)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/89711 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/69/builds/34263 "Built successfully") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 🧪 win ](https://ews-build.webkit.org/#/builders/Windows-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/93719 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/64/builds/32757 "Built successfully") | [⏳ 🛠 mac-debug ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/95358 "Passed tests") | [  ~~🧪 ios-wk2~~](https://ews-build.webkit.org/#/builders/68/builds/26033 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 gtk-wk2 ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/80911 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-gtk ](https://ews-build.webkit.org/#/builders/GTK-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/30511 "Built successfully") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/30260 "Built successfully") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/33709 "Built successfully") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Big-Sur-Debug-Build-EWS "Waiting in queue, processing has not started yet") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/32420 "Built successfully") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | | </details>

2022-09-19 16:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0174ba8df09ae946cc1c00c1fe8bd7a243ce2055. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4377

2022-09-20 07:19 UTC, carlosgcampos approved these changes

2022-09-20 07:33 UTC, philn requested changes
Please un-flag the tests from TestExpectations

2022-09-20 08:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b40d970f985b4fac0057108a702abcff164e3787. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4377

2022-09-20 08:10 UTC, philn commented
Thanks :)

2022-09-21 12:53 UTC, webkit-commit-queue commented
Committed 254722@main (f170deb76702): <https://commits.webkit.org/254722@main>

Reviewed commits have been landed. Closing PR #4377 and removing active labels.

2022-09-21 12:53 UTC, merged