Do not expose -webkit-text CSS value in quirks mode
WebKit/WebKit pull request #4665
Opened 2022-09-24 15:09 UTC by nt1m

#### aa9a542eefb604a351d64968c859d9d6b4c3263a
<pre>
Do not expose -webkit-text CSS value in quirks mode
<a href="https://bugs.webkit.org/show_bug.cgi?id=154164">https://bugs.webkit.org/show_bug.cgi?id=154164</a>

Reviewed by NOBODY (OOPS!).

Rename -webkit-text value for color to -internal-document-text-color and only expose it for UA sheets.

Test: LayoutTests/fast/css/webkit-text-quirks-mode.html

* Source/WebCore/css/CSSValueKeywords.in:
* Source/WebCore/css/parser/CSSParserIdioms.cpp:
(WebCore::isValueAllowedInMode):
* Source/WebCore/css/quirks.css:
(table):
* Source/WebCore/style/StyleBuilderState.cpp:
(WebCore::Style::BuilderState::isColorFromPrimitiveValueDerivedFromElement):
(WebCore::Style::BuilderState::colorFromPrimitiveValue const):
* LayoutTests/fast/css/webkit-text-quirks-mode-expected.html: Added.
* LayoutTests/fast/css/webkit-text-quirks-mode.html: Added.
</pre>

2022-09-24 15:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/aa9a542eefb604a351d64968c859d9d6b4c3263a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-24 15:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5fc9bd9aac620da637c188a94bca7c72f58d8d2e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-24 15:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4bbaa68e7e10d6a459b848c460dff93080b70f00. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-24 15:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/49f839479399ddffa89e9168ad390a820f6622a4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-24 15:40 UTC, weinig commented
Is `-internal-document-text-color;` actually getting parsed a color for the UA stylesheet? I think it probably needs to be added to one of the predicates in StyleColor for it to ever match something.

2022-09-24 15:45 UTC, nt1m commented
> Is `-internal-document-text-color;` actually getting parsed a color for the UA stylesheet? I think it probably needs to be added to one of the predicates in StyleColor for it to ever match something.

Yeah, I just fixed that.

2022-09-27 14:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dfcb46e8f78f4b33114628a88fdaf27facf77a46. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-27 16:20 UTC, weinig requested changes

2022-09-27 16:20 UTC, weinig commented on Source/WebCore/css/CSSValueKeywords.in
> +-internal-document-text-color
Can you add a test that shows this doesn't work in non-UA stylesheets?

2022-09-27 17:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f5233e850f22cfe697c46e4ccedbca749e1b6ef4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4665

2022-09-27 17:15 UTC, nt1m commented on Source/WebCore/css/CSSValueKeywords.in
> +-internal-document-text-color
done

2022-09-27 22:51 UTC, weinig approved these changes
Nice!

2022-09-27 22:57 UTC, weinig commented
We have one other weird one I couldn't find in any spec: `activebuttontext`

2022-09-27 23:46 UTC, webkit-commit-queue commented
Committed 254935@main (25abb3d63d29): <https://commits.webkit.org/254935@main>

Reviewed commits have been landed. Closing PR #4665 and removing active labels.

2022-09-27 23:46 UTC, closed without merging