Remove `text` value for <color>
WebKit/WebKit pull request #4671
Opened 2022-09-24 23:43 UTC by nt1m

#### dd9c57b36a914e7cbda7b2af9fa2ba9a0bccc726
<pre>
Remove `text` value for &lt;color&gt;
<a href="https://bugs.webkit.org/show_bug.cgi?id=245626">https://bugs.webkit.org/show_bug.cgi?id=245626</a>
&lt;rdar://100364547&gt;

Reviewed by NOBODY (OOPS!).

`color: text` is non standard, and is equivalent to CanvasText. WebKit is the only browser engine that supports it.

* LayoutTests/css-dark-mode/color-scheme-css.html:
* LayoutTests/css-dark-mode/color-scheme-meta.html:
* LayoutTests/css-dark-mode/color-scheme-priority.html:
* LayoutTests/css-dark-mode/older-syntax/supported-color-schemes-css.html:
* LayoutTests/css-dark-mode/older-syntax/supported-color-schemes-meta.html:
* LayoutTests/css-dark-mode/older-systems/color-scheme-css.html:
* LayoutTests/css-dark-mode/older-systems/color-scheme-meta.html:
* LayoutTests/css-dark-mode/older-systems/prefers-color-scheme.html:
* LayoutTests/css-dark-mode/prefers-color-scheme.html:
* LayoutTests/css3/color-filters/color-filter-ignore-semantic-expected.html:
* LayoutTests/css3/color-filters/color-filter-ignore-semantic.html:
* Source/WebCore/css/StyleColor.cpp:
(WebCore::StyleColor::isSystemColorKeyword):
* Source/WebCore/platform/ScrollSnapAnimatorState.cpp:
(WebCore::ScrollSnapAnimatorState::resnapAfterLayout):
* Source/WebCore/rendering/RenderTheme.cpp:
(WebCore::RenderTheme::systemColor const):
* Source/WebCore/rendering/RenderThemeAdwaita.cpp:
(WebCore::RenderThemeAdwaita::systemColor const):
* Source/WebCore/rendering/RenderThemeIOS.mm:
(WebCore::cssValueSystemColorInformationList):
* Source/WebCore/rendering/RenderThemeMac.mm:
(WebCore::RenderThemeMac::systemColor const):
* Websites/bugs.webkit.org/PrettyPatch/PrettyPatch.rb:
</pre>

2022-09-24 23:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dd9c57b36a914e7cbda7b2af9fa2ba9a0bccc726. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4671

2022-09-25 00:21 UTC, pxlcoder commented
How do we know this change is safe from a compat standpoint?

2022-09-25 00:22 UTC, nt1m commented
> How do we know this change is safe from a compat standpoint?

Chrome & Firefox do not ship this. See rdar://100364607 & rdar://100364638 & rdar://100364656 for internal usages.

2022-09-25 00:28 UTC, pxlcoder commented
I think this would be better with an LOA check.

2022-09-25 00:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/56fb2fb834be8134a8662f76e4edabe131d48465. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4671

2022-09-25 01:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2d95722297ef406fe4b37ace29fdabe08e281078. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4671

2022-09-29 01:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/652bbee5458347ee036dee2f951cead08b527adf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4671

2022-10-17 18:38 UTC, litherum commented
> > How do we know this change is safe from a compat standpoint?
> 
> Chrome & Firefox do not ship this. See rdar://100364607 & rdar://100364638 & rdar://100364656 for internal usages.

This is not sufficient to remove features. We at least need to make sure it isn't used in Books + apps.

2022-10-17 18:39 UTC, litherum requested changes
Marking as r- until we are more confident we can remove this feature.

2025-08-31 11:03 UTC, closed without merging