Fix ASAN false positives when dumping dissassembly
WebKit/WebKit pull request #4877
Opened 2022-09-30 20:44 UTC by justinmichaud

#### 1a39dd6a08839e5567bcbd356e9e78114388598f
<pre>
Fix ASAN false positives when dumping dissassembly
<a href="https://bugs.webkit.org/show_bug.cgi?id=245896">https://bugs.webkit.org/show_bug.cgi?id=245896</a>

Reviewed by NOBODY (OOPS!).

* Source/JavaScriptCore/b3/B3Value.h:
* Source/JavaScriptCore/bytecode/CodeBlock.cpp:
(JSC::dumpDetail):
(JSC::CodeBlock::jettison):
* Source/WTF/wtf/Assertions.h:
</pre>

2022-09-30 20:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1a39dd6a08839e5567bcbd356e9e78114388598f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4877

2022-09-30 20:46 UTC, Constellation reviewed
I think StackTrace related part would be requiring https://github.com/WebKit/WebKit/pull/4830

2022-11-02 20:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c4e2d2b0d3da16ac1e06537387eb66389cebdac3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4877

2022-11-02 20:57 UTC, Constellation approved these changes
r=me

2022-11-02 21:57 UTC, ddkilzer commented on Source/WTF/wtf/Assertions.h
> +WTF_EXPORT_PRIVATE SUPPRESS_ASAN void WTFPrintBacktrace(void** stack, int size);
This feels super weird because I see use-after-free crashes in logging code all the time.

Are these functions only ever called from the debugger?  (And if so, why do they need to be exported?)

2022-11-04 20:08 UTC, ddkilzer requested changes
Let's try to understand why `SUPPRESS_ASAN` is needed on the `WTF*Backtrace*()` macros.

2023-03-14 23:26 UTC, justinmichaud commented
No longer reproduces

2023-03-14 23:26 UTC, closed without merging