Allow an element "aria-labelledby" itself
WebKit/WebKit pull request #4921
Opened 2022-10-03 09:58 UTC by obyknovenius

#### c0644b31cadc16b8440e99d1761ad17d51252620
<pre>
Allow an element &quot;aria-labelledby&quot; itself
<a href="https://bugs.webkit.org/show_bug.cgi?id=245956">https://bugs.webkit.org/show_bug.cgi?id=245956</a>

Reviewed by NOBODY (OOPS!).

It is allowed for an element to list its own id in &quot;aria-labelledby&quot; attribute.

Fixes a crash in &quot;accessibility/aria-labelledby-overrides-label.html&quot;
with assertions enabled.

* Source/WebCore/accessibility/AXObjectCache.cpp:
(WebCore::AXObjectCache::addRelation):
</pre>

2022-10-03 09:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c0644b31cadc16b8440e99d1761ad17d51252620. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/4921

2022-10-05 01:48 UTC, twilco commented
Looks good to me, but I'm not a reviewer.

@fleizach or @AndresGonzalezApple, could you please review this?

2022-10-05 01:54 UTC, fleizach commented
Need a layout test for this

2022-10-05 08:45 UTC, obyknovenius commented
We already have this case in `accessibility/aria-labelledby-overrides-label.html`. This is how I discovered this issue. Do we need a dedicated test?
https://github.com/WebKit/WebKit/blob/a8ab43132b0d66e1dd1fc9d519d22710fa897962/LayoutTests/accessibility/aria-labelledby-overrides-label.html#L10

2022-11-23 01:27 UTC, darinadler approved these changes

2022-11-23 01:28 UTC, darinadler commented
> We already have this case in `accessibility/aria-labelledby-overrides-label.html`. This is how I discovered this issue. Do we need a dedicated test?
> 
> https://github.com/WebKit/WebKit/blob/a8ab43132b0d66e1dd1fc9d519d22710fa897962/LayoutTests/accessibility/aria-labelledby-overrides-label.html#L10

We do need a test because this pull request does not show us expecting to pass something that was previously failing.

2022-11-23 01:29 UTC, darinadler requested changes
Need a test showing this now works. Either a passing result for an existing test or a new test.

2022-11-28 12:35 UTC, closed without merging