[CoordinatedGraphics] Issue with shadow rendering for image elements
WebKit/WebKit pull request #5047
Opened 2022-10-05 20:17 UTC by ukoneru

https://bugs.webkit.org/show_bug.cgi?id=236609

Reviewed by NOBODY (OOPS!).

Notify software filters flag in the renderview  to trigger correct repaint rect for filters shadow/blur.repaint rect determined at RenderObject::containerForRepaint()

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2022-10-05 20:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ea500e687fffb54c95e0e2defa6fb69d1fa9dcdc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5047

2022-10-05 21:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/df7522c33ce586d470199a54a5457ca5b8060907. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5047

2022-10-11 20:21 UTC, fujii requested changes
You should add a ref test. You don't have to create a new one if you find out existing test.
This looks like same bug with <https://bugs.webkit.org/show_bug.cgi?id=118411>.
Could you recreate a new PR for it?

2023-02-05 13:32 UTC, Ahmad-S792 commented
Closing this in favor of [6531](https://github.com/WebKit/WebKit/pull/6531).

2023-02-05 13:32 UTC, closed without merging