The EUC-TW encoding doesn't have a canonical name
WebKit/WebKit pull request #5160
Opened 2022-10-08 01:10 UTC by litherum

#### 04187e576898cfbf173ffd36a3f4c586a6937aaf
<pre>
The EUC-TW encoding doesn&apos;t have a canonical name
<a href="https://bugs.webkit.org/show_bug.cgi?id=246242">https://bugs.webkit.org/show_bug.cgi?id=246242</a>
rdar://100893154

Reviewed by NOBODY (OOPS!).

ucnv_getCanonicalName(&quot;EUC-TW&quot;, &quot;IANA&quot;) is returning nullptr, which is causing
us to memcmp(nullptr, ...). This patch follows the previous pattern of hardcoding
these canonical names according to what ucnv_getName() says.

Test: <a href="http://wpt.live/encoding/unsupported-labels.window.html">http://wpt.live/encoding/unsupported-labels.window.html</a>

* Source/WebCore/PAL/pal/text/TextCodecICU.cpp:
(PAL::TextCodecICU::registerCodecs):
(PAL::TextCodecICU::TextCodecICU):
</pre>

2022-10-08 01:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/04187e576898cfbf173ffd36a3f4c586a6937aaf. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-10-08 01:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e5036e94431f8a4fa5d3a8d8b70e94392bcd3f9d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-10-08 05:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f1d580ae8f73555db9121fe594e5bdd342381cc6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-10-08 07:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/735c862146b7bb6a25eacff5ad3c8e2d573b51ac. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-10-08 21:06 UTC, aproskuryakov commented
Can this have a regression test?

2022-10-08 21:10 UTC, aproskuryakov commented
The code change looks good. One thing that's a little unclear is whether `windows-949` actually gets us `windows-949-2000`, and will in the future. Depending on future ICU decisions seems suboptimal.

2022-10-10 06:23 UTC, annevk commented
I'm not sure I entirely understand what this is doing. E.g., windows-949 maps to EUC-KR and as far as I can tell we don't use ICU for that, we use `EncodingTables.cpp`. See also bc3715d824ffde84c98cd0e4870676410ac055a8.

I suspect Alex would be a good reviewer here.

2022-10-13 16:08 UTC, achristensen07 requested changes

2022-10-13 16:08 UTC, achristensen07 commented on Source/WebCore/PAL/pal/text/TextCodecICU.cpp
> +            assert(U_SUCCESS(error));
Lowercase assert is a different function that we don't use in WebKit.

2022-10-13 16:08 UTC, achristensen07 commented on Source/WebCore/PAL/pal/text/TextCodecICU.cpp
>          registrar(name, [name, canonicalConverterName] {
It probably wouldn't hurt to add another if (!canonicalConverterName) { ASSERT_NOT_REACHED(); continue; } to be on the safe side.

2022-11-07 21:28 UTC, litherum commented
> One thing that's a little unclear is whether `windows-949` actually gets us `windows-949-2000`

It does.

> and will in the future

2022-11-07 22:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20deaa64fb0cd50a410508f1f8cc868bbc36f40d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-11-07 22:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/20deaa64fb0cd50a410508f1f8cc868bbc36f40d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-11-07 22:38 UTC, achristensen07 approved these changes

2022-11-07 23:55 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/df96a4ffc93e3a0bb7f3725fb9d52564e5b91240. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5160

2022-11-08 06:25 UTC, webkit-commit-queue commented
Committed 256438@main (996fc9db28be): <https://commits.webkit.org/256438@main>

Reviewed commits have been landed. Closing PR #5160 and removing active labels.

2022-11-08 06:41 UTC, closed without merging