Update fuzziness in fast/ for accelerated drawing
WebKit/WebKit pull request #5664
Opened 2022-10-22 01:24 UTC by nmoucht

#### 2f270f4e38bb9dac4bbc19694ce58fa81043d18e
<pre>
Update fuzziness in fast/ for accelerated drawing
<a href="https://bugs.webkit.org/show_bug.cgi?id=246837">https://bugs.webkit.org/show_bug.cgi?id=246837</a>
rdar://101449704

Reviewed by NOBODY (OOPS!).

Update fuzziness in fast/ for when accelerated drawing is enabled by default.

* LayoutTests/fast/backgrounds/background-opaque-clipped-gradients.html:
* LayoutTests/fast/backgrounds/generated-bck-image-with-small-relative-size.html:
* LayoutTests/fast/backgrounds/hidpi-background-image-contain-cover-scale-needs-more-precision.html:
* LayoutTests/fast/backgrounds/scaled-gradient-background.html:
* LayoutTests/fast/borders/border-image-fill-inline-no-border.html:
* LayoutTests/fast/borders/border-image-repeat-stretch.html:
* LayoutTests/fast/borders/border-painting-correctness-dashed.html:
* LayoutTests/fast/borders/border-painting-correctness-dotted.html:
* LayoutTests/fast/borders/hidpi-double-border-with-border-radius-always-produce-solid-line.html:
* LayoutTests/fast/borders/outline-border-radius-simple.html:
* LayoutTests/fast/box-shadow/box-shadow-with-zero-radius.html:
* LayoutTests/fast/box-shadow/inset-box-shadow.html:
* LayoutTests/fast/css/text-decorations-on-first-line-and-containing-block.html:
* LayoutTests/fast/filter-image/clipped-filter.html:
* LayoutTests/fast/forms/date/date-editable-components/date-editable-components-placeholder-color.html:
* LayoutTests/fast/gradients/conic-center-outside-box.html:
* LayoutTests/fast/gradients/radial-two-hints.html:
* LayoutTests/fast/images/async-image-background-image-repeated.html:
* LayoutTests/fast/images/exif-orientation-background-image-repeat.html:
* LayoutTests/fast/images/hidpi-image-position-on-device-pixels-with-border-radius.html:
* LayoutTests/fast/images/image-map-outline-with-paint-root-offset.html:
* LayoutTests/fast/images/sprite-sheet-image-draw.html:
* LayoutTests/fast/layers/parent-clipping-overflow-is-overwritten-by-child-clipping.html:
* LayoutTests/fast/layers/wrong-clipping-semi-transparent-compositing-layer-on-subpixel-position.html:
* LayoutTests/fast/multicol/simple-line-layout-line-index-after-strut.html:
* LayoutTests/fast/repaint/gradients-em-stops-repaint.html:
* LayoutTests/fast/table/table-border-radius.html:
* LayoutTests/fast/text/empty-shadow.html:
* LayoutTests/fast/text/frequent-text.html:
* LayoutTests/fast/text/initial-advance-selected-text.html:
* LayoutTests/fast/transforms/skew-x-135deg-with-gradient.html:
* LayoutTests/fast/transforms/skew-y-135deg-with-gradient.html:
</pre>

2022-10-22 01:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2f270f4e38bb9dac4bbc19694ce58fa81043d18e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5664

2022-10-24 15:59 UTC, smfr requested changes

2022-10-24 15:59 UTC, smfr commented on LayoutTests/fast/borders/border-painting-correctness-dashed.html
> +<meta name="fuzzy" content="maxDifference=0-355; totalPixels=0-4808" />
255 is the largest difference.

2022-10-24 15:59 UTC, smfr commented on LayoutTests/fast/borders/border-painting-correctness-dotted.html
> +<meta name="fuzzy" content="maxDifference=0-355; totalPixels=0-15225" />
255 is the largest difference.

2022-10-24 15:59 UTC, smfr commented on LayoutTests/fast/text/frequent-text.html
> +<meta name="fuzzy" content="maxDifference=0-70; totalPixels=0-382" />
This should go in the `<head>`

2022-10-24 18:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/42bd2cb8253f9b7e8ee9423fe8c0df13e876e219. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5664

2022-10-24 18:39 UTC, nmoucht commented on LayoutTests/fast/borders/border-painting-correctness-dashed.html
> +<meta name="fuzzy" content="maxDifference=0-355; totalPixels=0-4808" />
Fixed.

2022-10-24 18:39 UTC, nmoucht commented on LayoutTests/fast/borders/border-painting-correctness-dotted.html
> +<meta name="fuzzy" content="maxDifference=0-355; totalPixels=0-15225" />
Fixed.

2022-10-24 18:39 UTC, nmoucht commented on LayoutTests/fast/text/frequent-text.html
> +<meta name="fuzzy" content="maxDifference=0-70; totalPixels=0-382" />
Fixed.

2022-10-24 19:19 UTC, smfr approved these changes

2022-10-24 19:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/78bb58b06156e1e6a36b0b4a3775fb0792a5af64. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5664

2022-10-25 18:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/196eee65392258bd899026b8f2e22ad32c6a2327. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5664

2022-10-25 19:19 UTC, merged

2022-10-25 19:19 UTC, webkit-commit-queue commented
Committed 255974@main (22276a499a28): <https://commits.webkit.org/255974@main>

Reviewed commits have been landed. Closing PR #5664 and removing active labels.