macOS Ventura Open Source Bringup
WebKit/WebKit pull request #5722
Opened 2022-10-24 23:39 UTC by robert-jenner

#### 6fb36ee7a5d28124229983729fa8180d7ec0730a
<pre>
macOS Ventura Open Source Bringup
<a href="https://bugs.webkit.org/show_bug.cgi?id=246956">https://bugs.webkit.org/show_bug.cgi?id=246956</a>

Reviewed by NOBODY (OOPS!).

* Tools/CISupport/build-webkit-org/config.json:
* Tools/CISupport/build-webkit-org/factories_unittest.py:
(TestExpectedBuildSteps):
* Tools/CISupport/build-webkit-org/public_html/dashboard/Images/Ventura.png: Added.
* Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/Dashboard.js:
* Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js:
(WebKitBuildbot):
* Tools/CISupport/build-webkit-org/public_html/dashboard/Styles/Main.css:
(table.queue-grid tr.platform.macos-monterey img.logo):
</pre>

2022-10-24 23:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6fb36ee7a5d28124229983729fa8180d7ec0730a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-24 23:43 UTC, ryanhaddad commented
I think this looks good, you will need to update `Tools/CISupport/build-webkit-org/wkbuild.py` as well.

2022-10-25 00:31 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f07296c4434af675840005dc68724e5b13c8e8fe. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 01:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/aa27cf8e8d1aba4d2ba08a76c6f7ac692f6327c1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 03:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a80bd481487b315cc71a32cbede68c7d0d8a4aa6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 03:42 UTC, robert-jenner commented
> I think this looks good, you will need to update `Tools/CISupport/build-webkit-org/wkbuild.py` as well.

@ryanhaddad I have added that, as well as made adjustments to `Tools/CISupport/build-webkit-org/factories_unittest.py` and it appears to be passing services now. So I think we may be ready for an r+ ?

2022-10-25 15:58 UTC, ryanhaddad requested changes

2022-10-25 15:58 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/public_html/dashboard/Styles/Main.css
> +table.queue-grid tr.platform.macos-monterey img.logo {
```suggestion
table.queue-grid tr.platform.macos-ventura img.logo {
```

2022-10-25 16:10 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/08d4409fe4db0dae0d3f68013581160fdbce7ec7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 16:17 UTC, ryanhaddad approved these changes

2022-10-25 16:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a5a0a4c8ba45c419a04d8062076880bb6dd8832c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 16:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8b897c3890e861ac5345f49e297bf7b65e1fbb0d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 17:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f11bb560344e77dd6f30eedbb77becdd560eb334. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5722

2022-10-25 18:09 UTC, merged

2022-10-25 18:09 UTC, webkit-commit-queue commented
Committed 255969@main (629698526289): <https://commits.webkit.org/255969@main>

Reviewed commits have been landed. Closing PR #5722 and removing active labels.