[macOS] Use RunningBoard to manage process priorities
WebKit/WebKit pull request #5759
Opened 2022-10-25 16:06 UTC by salinas-miguel

#### 15e6ad085f368f8002443c5580f98d8632522183
<pre>
[macOS] Use RunningBoard to manage process priorities
<a href="https://bugs.webkit.org/show_bug.cgi?id=245752">https://bugs.webkit.org/show_bug.cgi?id=245752</a>
rdar://100477336

Reviewed by NOBODY (OOPS!).

Now that we have integrated RunningBoard with WebKit we should start
using it to manage our process priorities. This change enables the iOS
assertion behavior on macOS behind a runtime flag. A previous version of
this patch mistakenly enabled the ProcessThrottler to send
PrepareToSuspend IPC messages to auxiliary processes even if
runningboard supression was disabled. This caused a large performance
regression which is now fixed.

* Source/WTF/Scripts/Preferences/WebPreferencesInternal.yaml:
* Source/WebKit/UIProcess/AuxiliaryProcessProxy.cpp:
(WebKit::AuxiliaryProcessProxy::didFinishLaunching):
(WebKit::AuxiliaryProcessProxy::setRunningBoardThrottlingEnabled):
* Source/WebKit/UIProcess/AuxiliaryProcessProxy.h:
* Source/WebKit/UIProcess/Cocoa/LegacyDownloadClient.mm:
(WebKit::LegacyDownloadClient::takeActivityToken):
* Source/WebKit/UIProcess/Cocoa/NavigationState.h:
* Source/WebKit/UIProcess/Cocoa/NavigationState.mm:
(WebKit::NavigationState::NavigationState):
(WebKit::NavigationState::didChangeIsLoading):
(WebKit::NavigationState::didSwapWebProcesses):
* Source/WebKit/UIProcess/GPU/GPUProcessProxy.cpp:
(WebKit::GPUProcessProxy::didFinishLaunching):
* Source/WebKit/UIProcess/Network/NetworkProcessProxy.cpp:
(WebKit::NetworkProcessProxy::didFinishLaunching):
* Source/WebKit/UIProcess/PageClient.h:
* Source/WebKit/UIProcess/ProcessAssertion.h:
* Source/WebKit/UIProcess/ProvisionalPageProxy.cpp:
(WebKit::ProvisionalPageProxy::ProvisionalPageProxy):
* Source/WebKit/UIProcess/ProvisionalPageProxy.h:
* Source/WebKit/UIProcess/SuspendedPageProxy.cpp:
(WebKit::SuspendedPageProxy::SuspendedPageProxy):
(WebKit::SuspendedPageProxy::didProcessRequestToSuspend):
* Source/WebKit/UIProcess/SuspendedPageProxy.h:
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::updateThrottleState):
(WebKit::WebPageProxy::waitForDidUpdateActivityState):
(WebKit::WebPageProxy::runJavaScriptInFrameInScriptWorld):
* Source/WebKit/UIProcess/WebPageProxy.h:
* Source/WebKit/UIProcess/WebProcessPool.cpp:
(WebKit::WebProcessPool::createWebPage):
* Source/WebKit/UIProcess/WebProcessProxy.cpp:
(WebKit::WebProcessProxy::didFinishLaunching):
* Source/WebKit/UIProcess/mac/PageClientImplMac.h:
</pre>

2022-10-25 16:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/15e6ad085f368f8002443c5580f98d8632522183. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-25 21:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7c89def62ea522bb355698633ed52810eb8c9d3d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-26 00:34 UTC, cdumez requested changes
I requested some changes offline.

2022-10-26 20:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/35d8814a687df6790405ef91ae71bec05301fb31. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-26 20:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ff58bc7424ce2d2d1a4061f5da0910e478550e42. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-26 22:13 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/047fc1983fc2a1c654f0cb324bb6991eed4bbfa7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-26 22:23 UTC, cdumez approved these changes
LGTM with nit fix.

2022-10-26 22:23 UTC, cdumez commented on Source/WebKit/UIProcess/WebProcessProxy.cpp
> +#if PLATFORM(MAC)
Let's write a single loop:
```
    for (const auto& page : m_pageMap.values()) {
#if PLATFORM(MAC)
        if (page->preferences().backgroundWebContentRunningBoardThrottlingEnabled()) {
             setRunningBoardThrottlingEnabled();
             break;
         }
#endif
        if (!page->preferences().shouldTakeSuspendedAssertions()) {
             m_throttler.setShouldTakeSuspendedAssertion(false);
             break;
         }
    }
```

2022-10-27 00:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/05331200748d42f7456a02583c8d2deab616b377. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5759

2022-10-27 00:58 UTC, salinas-miguel commented on Source/WebKit/UIProcess/WebProcessProxy.cpp
> +#if PLATFORM(MAC)
Thanks, fixed now

2022-10-27 15:17 UTC, salinas-miguel commented
Windows build failure is unrelated: `InspectorStyleSheet.cpp(583,18): error C2039: 'setRuleId': is not a member of 'Inspector::Protocol::CSS::Grouping'`
api-gtk looks like it failed due to flaky tests.
removing merging-blocked

2022-10-27 19:11 UTC, webkit-commit-queue commented
Committed 256072@main (f8166f50d036): <https://commits.webkit.org/256072@main>

Reviewed commits have been landed. Closing PR #5759 and removing active labels.

2022-10-27 19:11 UTC, merged