REGRESSION (r145541): Incorrect local to device transformation when the SVG is rendered into a separate composited layer
WebKit/WebKit pull request #5761
Opened 2022-10-25 16:28 UTC by Ahmad-S792

<pre>
REGRESSION (r145541): Incorrect local to device transformation when the SVG is rendered into a separate composited layer
<a href="https://bugs.webkit.org/show_bug.cgi?id=115072">https://bugs.webkit.org/show_bug.cgi?id=115072</a>

Reviewed by NOBODY (OOPS!).

Patch Authored by Said Abou-Hallawa

Inspired from - <a href="https://src.chromium.org/viewvc/blink?revision=169472&view=revision">https://src.chromium.org/viewvc/blink?revision=169472&view=revision</a>

calculateTransformationToOutermostCoordinateSystem() should stop at the first composited layer to match its backing resolution.
Currently, we are incorrectly taking the layer transform into account (the stop condition is off by one).

* Source/WebCore/rendering/svg/SVGRenderingContext.cpp:
(SVGRenderingContext::calculateTransformToOutermostCoordinate): Following changes:
1) Pushed "deviceScaleFactor" down with scale
2) Moved "Transform" after "Compositing" is stopped.
* LayoutTests/svg/custom/filter-css-transform-resolution.html: Added Test Case
</pre>

2022-10-25 16:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bb0b81a34fedc7903a54c9d252dbd9a99c7aeb62. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-10-25 22:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/224fedf0326f2018fcdcfa96f6744d9d313d8c5d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-10-26 10:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e1412a628a73f1949adf5db2489eddd7192de369. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-10-26 10:28 UTC, Ahmad-S792 commented
@smfr - This was patch was reviewed by Darin earlier with r+ but had test issue raised by yourself. I took the patch of Said and just added Chrome / Blink testcase. Since it is Said's patch, it will be self-review. Hence, I am not adding him but yourself and @nikolaszimmermann for review.

2022-10-29 08:02 UTC, Ahmad-S792 commented
@nikolaszimmermann - Simon mentioned on Slack that he want you to have a look. Appreciate if you can review. Thanks!

2022-11-03 17:09 UTC, nikolaszimmermann requested changes
Code change looks good. The test shows its age - can you make it a reftest?

2022-11-03 17:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2a73f1a695d6dc321e8d92399502e4f8da37149d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-03 17:39 UTC, Ahmad-S792 commented
> Code change looks good. The test shows its age - can you make it a reftest?

Trying now - let's see how EWS report back. Problem is that when I run it via JSFiddle, it shows blurry / pixelated "Green" circle so I am not sure on 'reftest' within EWS and whether it will have same pixelated issue or not. Fingers crossed!

2022-11-03 22:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cab7932d6307df70b140c86ca6980558b10f8b02. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-03 23:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/86ac1d3394a6f2a6d31459c8ba4708a88d5bb1db. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-06 13:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f5ec488f84f5efa9a44f9b99bafefa5e42f0aa38. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-06 19:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13ad9fc9c4e943f809a757edf6a41cd2cca47631. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-06 21:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/534060b1e269f0ff3b877758c4bb468dacdbcd4d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-06 22:45 UTC, Ahmad-S792 commented
> > Code change looks good. The test shows its age - can you make it a reftest?
> 
> Trying now - let's see how EWS report back. Problem is that when I run it via JSFiddle, it shows blurry / pixelated "Green" circle so I am not sure on 'reftest' within EWS and whether it will have same pixelated issue or not. Fingers crossed!

I tried but I think something in EWS is showing broken image when running this test and trying to see 'actual' result, plus using same code of test and changing it into [JSFiddle](https://jsfiddle.net/ckbz47fu/show), I get pixelated blurry image. Any idea on how to fix it?

2022-11-17 15:41 UTC, nikolaszimmermann commented
So you are saying that if you copy LayoutTests/svg/custom/filter-css-transform-resolution.html to LayoutTests/svg/custom/filter-css-transform-resolution-expected.html (remove the scripts, remove the 'transform' -- that doesn't give you the same result?

2022-11-22 20:57 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dc4df6a81c54e4964ec0960a38afc4032e5f5cb5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5761

2022-11-22 20:58 UTC, Ahmad-S792 commented
> So you are saying that if you copy LayoutTests/svg/custom/filter-css-transform-resolution.html to LayoutTests/svg/custom/filter-css-transform-resolution-expected.html (remove the scripts, remove the 'transform' -- that doesn't give you the same result?

Just pushed updated. Let's see.

2022-11-26 09:56 UTC, Ahmad-S792 commented
@nikolaszimmermann - I think I am getting hit by same issue and if I go try to see 'actual' output, I can't, it seems that the image is not getting rendered. Should I close this PR and document my conclusion on bug or revert back to old test cases? Thanks!

2022-11-26 11:22 UTC, nikolaszimmermann commented
Weird issue - I will try your patch locally on the weekend.

2022-12-21 14:16 UTC, Ahmad-S792 commented
> Weird issue - I will try your patch locally on the weekend.

@nikolaszimmermann - Any update? or should I leave this for now and come back later once we figure out what is wrong with testcase failing in EWS.

2022-12-21 16:50 UTC, nikolaszimmermann commented
Sorry Ahmad I was on sick leave for almost two weeks - lots of things to catch up. I have not forgotten about your patch, I will hopefully find some time this year 🤣Am 21.12.2022 um 15:16 schrieb Ahmad Saleem ***@***.***>:﻿

Weird issue - I will try your patch locally on the weekend.

@nikolaszimmermann - Any update? or should I leave this for now and come back later once we figure out what is wrong with testcase failing in EWS.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-02-22 01:44 UTC, closed without merging