Change m_node to being a WeakPtr
WebKit/WebKit pull request #5977
Opened 2022-10-31 21:07 UTC by chirags27

#### 63c86a3d1b189a4136c0cefeb3959394aac596d3
<pre>
Change m_node to being a WeakPtr

<a href="https://bugs.webkit.org/show_bug.cgi?id=247288">https://bugs.webkit.org/show_bug.cgi?id=247288</a>

Reviewed by Geoffrey Garen.

m_node in RenderObject used to be a plain old C++ reference to the node,
which means that if the node is de-allocated, m_node would be referring
to something that is freed. This change adds hardening so that such bugs
are manifested as crashes rather than use-after-free bugs.

* Source/WebCore/rendering/RenderObject.h:
(WebCore::RenderObject::isDocumentElementRenderer const):
(WebCore::RenderObject::node const):
(WebCore::RenderObject::document const):
(WebCore::RenderObject::nodeForNonAnonymous const):

Canonical link: <a href="https://commits.webkit.org/256282@main">https://commits.webkit.org/256282@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/960a1d7822b2a36d4dce02d66bb310c7426e481d

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/95103 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/4244 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/28018 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/104701 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/164951 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/99094 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/4336 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/32697 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/87415 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/100601 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/100771 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/3159 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/81634 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/30135 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/85069 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/86899 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/73032 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/38834 "Built successfully") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/18454 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/36655 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/19735 "Passed tests") | | 
| [✅ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/4340 "Built successfully and passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/40589 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/42431 "Passed tests") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/42571 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/38976 "Passed tests") | |

2022-10-31 21:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/37661fd0ce50f7ffdf05c6d50a8a85d9ceb506d9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5977

2022-10-31 21:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8bc1a346f1296bf6d7919e72c939d6cff4a05cf7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5977

2022-10-31 21:20 UTC, geoffreygaren commented
Antti sometimes tells me that CheckedPtr<T> is preferable in cases like this to communicate the invariant that this pointer _should not_ be null, while retaining pointer safety / protection against use after free. Should we consider CheckedPtr<T> here?

2022-10-31 21:24 UTC, chirags27 commented
> Antti sometimes tells me that CheckedPtr is preferable in cases like this to communicate the invariant that this pointer _should not_ be null, while retaining pointer safety / protection against use after free. Should we consider CheckedPtr here?

I don't know much about the implementation of CheckedPtr, but the only documentation I found online says that it is experimental and to not use it in production code. It does look like we already use it in WebKit, so maybe that would be ok. I'll defer to Antti on which one to use here.

2022-10-31 22:12 UTC, alanbaradlay commented
Please use CheckedPtr (and we already use it extensively in the new layout codebase).

2022-10-31 23:03 UTC, chirags27 commented
> Please use CheckedPtr (and we already use it extensively in the new layout codebase).

Ok, I tried changing this to CheckPtr, and it results in a ton of const correctness issues, so there might have to be way more changes to make this work. In summary, `Node* node() const` is a const method, so it will call into the `ALWAYS_INLINE const T* get() const { return PtrTraits::unwrap(m_ptr); }`

2022-10-31 23:07 UTC, alanbaradlay commented
yeah, apparently Node does not support CheckedPtr yet :/ (just learnt that myself)

2022-10-31 23:10 UTC, geoffreygaren commented
From CheckPtr.h: "...and CheckedPtr has less overhead"

Bummer! I guess we can't use it here. In that case, I'd suggest documenting our non-null expectation with an ASSERT.

2022-11-01 20:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/74cc931b2722a88036a5f52b7446ab05f155a059. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5977

2022-11-01 20:29 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/bc1614ac9e4c072e662e5fdb265598c1301e38cb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5977

2022-11-01 21:43 UTC, geoffreygaren commented on Source/WebCore/rendering/RenderObject.h
> +    bool isDocumentElementRenderer() const { return document().documentElement() == m_node.get(); }
We have operator==(T* a, const WeakPtr<U, WeakPtrImpl>& b). Can we remove .get() here?

2022-11-01 21:43 UTC, geoffreygaren commented on Source/WebCore/rendering/RenderObject.h
> +    Document& document() const { ASSERT(m_node.get()); return (*m_node).document(); }
WebKit style ism_node->document().

2022-11-01 21:45 UTC, geoffreygaren commented on Source/WebCore/rendering/RenderObject.h
> +    Node& nodeForNonAnonymous() const { ASSERT(!isAnonymous()); ASSERT(m_node.get()); return *m_node; }
We have WeakPtrImplBase::operator bool(). Can we remove .get() here?

2022-11-01 21:45 UTC, geoffreygaren requested changes
This seems like the right approach but I have some style comments.

2022-11-01 22:11 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/960a1d7822b2a36d4dce02d66bb310c7426e481d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/5977

2022-11-01 22:15 UTC, geoffreygaren approved these changes
r=me

2022-11-02 17:01 UTC, anttijk commented
Same type being both CanMakeWeakPtr and CanMakeCheckedPtr seems bit silly. Maybe there could be semantically non-null version of WeakPtr (WeakRef?) that could assert it isn't nulled.

2022-11-03 18:36 UTC, webkit-commit-queue commented
Committed 256282@main (63c86a3d1b18): <https://commits.webkit.org/256282@main>

Reviewed commits have been landed. Closing PR #5977 and removing active labels.

2022-11-03 18:36 UTC, merged