Fix -Wformat errors in logs added in 256087@main
WebKit/WebKit pull request #6051
Opened 2022-11-02 21:31 UTC by donny-dont

#### 420cd6de672c0e7c4186ca952174dfdd14a71c9a
<pre>
Fix -Wformat errors in logs added in 256087@main
<a href="https://bugs.webkit.org/show_bug.cgi?id=247376">https://bugs.webkit.org/show_bug.cgi?id=247376</a>

Reviewed by NOBODY (OOPS!).

Clang 15 reports the error : using &apos;public&apos; format specifier annotation
outside of os_log()/os_trace() [-Werror,-Wformat]. Use %s instead as the
format specifier since os_log is Cocoa specific.

* Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.cpp:
* Source/WebKit/Platform/IPC/Connection.h:
</pre>

2022-11-02 21:32 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/420cd6de672c0e7c4186ca952174dfdd14a71c9a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6051

2022-11-02 23:45 UTC, achristensen07 requested changes
Please leave the behavior on Cocoa platforms unchanged.

2022-11-03 00:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/be32f9a0f111d8243db7e492dc73d4cd8c33e304. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6051

2022-11-03 00:20 UTC, donny-dont commented
Updated to use `PUBLIC_LOG_STRING`

2022-11-03 02:31 UTC, achristensen07 approved these changes

2022-11-03 02:32 UTC, achristensen07 approved these changes

2022-11-03 02:32 UTC, achristensen07 commented on Source/WebKit/NetworkProcess/NetworkConnectionToWebProcess.cpp
> +        RELEASE_LOG_FAULT(IPC, __FILE__ ADD_QUOTES(__LINE__) ": Invalid message dispatched %" PUBLIC_LOG_STRING, WTF_PRETTY_FUNCTION); \
It also might be worth adding a space (" ") between the file and line strings in both places.

2022-11-03 17:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e2707432a04eabb058448661bd66b08777d4576d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6051

2022-11-03 19:10 UTC, webkit-commit-queue commented
Committed 256283@main (8c10d15cd232): <https://commits.webkit.org/256283@main>

Reviewed commits have been landed. Closing PR #6051 and removing active labels.

2022-11-03 19:10 UTC, merged