The crashy WebKit XPC service causes Safari to Crash on iOS
WebKit/WebKit pull request #6066
Opened 2022-11-03 00:32 UTC by msaboff

#### 6f269df61183f08c3ff3ce1499004a5ae1a30824
<pre>
The crashy WebKit XPC service causes Safari to Crash on iOS
<a href="https://bugs.webkit.org/show_bug.cgi?id=247395">https://bugs.webkit.org/show_bug.cgi?id=247395</a>
rdar://101876374

Reviewed by NOBODY (OOPS!).

When calling sendToAllProcessesForSession(), we look for all processes with the matching SessionID.
Since the SessionID is stored in the WebsiteDataStore* attached to the WebProcessProxy and the proxy for a
crashy WebProcess doesn&apos;t have a WebsiteDataStore* we crash accessing the SessionID.
Since we don&apos;t want the crashy WebProcess to be associated with any active session, changed it so that a
crashy WebProcess has an invalid SessionID.

* Source/WebCore/PAL/pal/SessionID.h:
(PAL::SessionID::invalidSessionID):
* Source/WebKit/UIProcess/WebProcessProxy.cpp:
(WebKit::WebProcessProxy::sessionID const):
* Source/WebKit/UIProcess/WebProcessProxy.h:
(WebKit::WebProcessProxy::isCrashyProcess const):
(WebKit::WebProcessProxy::isCrashyProcess): Deleted.
</pre>

2022-11-03 00:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6f269df61183f08c3ff3ce1499004a5ae1a30824. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6066

2022-11-03 05:47 UTC, achristensen07 requested changes
This seems to be a consequence of not passing isPrewarmed to initializeNewWebProcess(crashyProcessProxy, nullptr); which makes it so !process->isPrewarmed() is always true.  I think that should be done instead, and if that doesn't fix this or can't be done, then we should make a WebProcessProxy::optionalSessionID() that returns a std::optional<PAL::SessionID> and returns nullopt if there's no WebsiteDataStore, then call that from sendToAllRemoteWorkerProcesses instead.

2022-11-03 15:11 UTC, msaboff commented
> This seems to be a consequence of not passing isPrewarmed to initializeNewWebProcess(crashyProcessProxy, nullptr); which makes it so !process->isPrewarmed() is always true. I think that should be done instead, and if that doesn't fix this or can't be done, then we should make a WebProcessProxy::optionalSessionID() that returns a std::optionalPAL::SessionID and returns nullopt if there's no WebsiteDataStore, then call that from sendToAllRemoteWorkerProcesses instead.

I'll investigate those changes.

2022-11-03 16:25 UTC, szewai commented
If marking crashy process prewarmed does not work, an alternative might be creating an ephemeral WebsiteDataStore for the crashy process (or making a global ephemeral WebsiteDataStore that is used for all crashy processes). Our current implementation assumes a web process either has a valid WebsiteDataStore(session) or is prewarmed (I think there are many checks for this).

2022-11-03 16:57 UTC, cdumez requested changes
The existing code is:
```
template<typename T>
void WebProcessPool::sendToAllProcessesForSession(const T& message, PAL::SessionID sessionID)
{
    for (auto& process : m_processes) {
        if (process->canSendMessage() && !process->isPrewarmed() && process->sessionID() == sessionID)
            process->send(T(message), 0);
    }
}
```

Note how it explicitly disregards prewarmed processes. I think we should explicitly ignore crashy processes too instead of returning an invalid ID (which is a new thing I'd rather not have to deal with).

2022-11-07 20:17 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/4a65361f1e5ad4d0fbb5fdf75e2f0e97f1ee523a)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/95699 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/4958 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/28745 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/105279 "Built successfully") | 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/5034 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/33718 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/88078 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/101123 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/101359 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/3698 "Passed tests") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/82319 "Built successfully") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/30755 "Passed tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/85563 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/87469 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/73585 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/66/builds/39448 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/19009 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/67/builds/37144 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/20323 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/63/builds/41140 "Built successfully") | [  ~~🧪 mac-AS-debug-wk2~~](https://ews-build.webkit.org/#/builders/60/builds/42971 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/65/builds/43126 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/39574 "Passed tests") | | </details>

2022-11-07 20:21 UTC, msaboff commented
> The existing code is:
> 
> ```
> template<typename T>
> void WebProcessPool::sendToAllProcessesForSession(const T& message, PAL::SessionID sessionID)
> {
>     for (auto& process : m_processes) {
>         if (process->canSendMessage() && !process->isPrewarmed() && process->sessionID() == sessionID)
>             process->send(T(message), 0);
>     }
> }
> ```
> 
> Note how it explicitly disregards prewarmed processes. I think we should explicitly ignore crashy processes too instead of returning an invalid ID (which is a new thing I'd rather not have to deal with).

I posted an updated PR with the explicit crash process check.

2022-11-07 20:30 UTC, cdumez commented on Source/WebKit/UIProcess/WebProcessProxy.h
> +    bool isCrashyProcess() { return m_isWebContentCrashyProcess; }
Function should be marked as const.

2022-11-07 20:31 UTC, cdumez approved these changes
LGTM with change.

2022-11-07 21:17 UTC, msaboff commented on Source/WebKit/UIProcess/WebProcessProxy.h
> +    bool isCrashyProcess() { return m_isWebContentCrashyProcess; }
Changed locally.

2022-11-08 00:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4863429e1cc7b87aa67f4d7bfc126021e1e004f6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6066

2022-11-08 01:20 UTC, webkit-commit-queue commented
Committed 256434@main (2fb42dcd321a): <https://commits.webkit.org/256434@main>

Reviewed commits have been landed. Closing PR #6066 and removing active labels.

2022-11-08 01:20 UTC, merged