Further adoption of the new CoreIPC serialization mechanism
WebKit/WebKit pull request #6091
Opened 2022-11-03 18:13 UTC by gavin-apple

#### 7911b6cc27a64baadbb660a49b82939f3cc53f41
<pre>
Further adoption of the new CoreIPC serialization mechanism
<a href="https://bugs.webkit.org/show_bug.cgi?id=247422">https://bugs.webkit.org/show_bug.cgi?id=247422</a>
rdar://101921684

Further porting of WebCoreArgumentCoders over to the new serialization
form. This change includes:
        - DiagnosticLoggingDomain
        - BackForwardItemIdentifier
        - PlatformColorSpace
        - DestinationColorSpace
        - WindowFeatures
        - CompositionUnderlineColor
        - CompositionUnderline
        - MediaCaptureType
        - FileChooserSettings
        - GrammarDetail
        - TextCheckingType
        - TextCheckingResult
        - TextCheckingProcessType
        - TextCheckingRequestData

Reviewed by NOBODY (OOPS!).

* Source/WebCore/editing/Editor.cpp:
(WebCore::Editor::replaceSelectionWithFragment):
(WebCore::Editor::markAllMisspellingsAndBadGrammarInRanges):
* Source/WebCore/history/BackForwardItemIdentifier.h:
(WebCore::operator!=):
(): Deleted.
(WebCore::BackForwardItemIdentifier::encode const): Deleted.
(WebCore::BackForwardItemIdentifier::decode): Deleted.
* Source/WebCore/html/HTMLInputElement.cpp:
(WebCore::HTMLInputElement::mediaCaptureType const):
* Source/WebCore/page/DiagnosticLoggingDomain.h:
* Source/WebCore/platform/FileChooser.h:
* Source/WebCore/platform/graphics/DestinationColorSpace.h:
(WebCore::DestinationColorSpace::encode const): Deleted.
(WebCore::DestinationColorSpace::decode): Deleted.
* Source/WebCore/platform/graphics/PlatformColorSpace.h:
* Source/WebCore/platform/text/TextChecking.h:
* Source/WebKit/CMakeLists.txt:
* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/Scripts/webkit/messages.py:
(serialized_identifiers):
* Source/WebKit/Shared/ModelIdentifier.h:
(WebKit::ModelIdentifier::encode const): Deleted.
(WebKit::ModelIdentifier::decode): Deleted.
* Source/WebKit/Shared/WebCoreArgumentCoders.cpp:
(IPC::ArgumentCoder&lt;WindowFeatures&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;WindowFeatures&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;CompositionUnderline&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;CompositionUnderline&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;FileChooserSettings&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;FileChooserSettings&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;GrammarDetail&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;GrammarDetail&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;TextCheckingRequestData&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;TextCheckingRequestData&gt;::decode): Deleted.
(IPC::ArgumentCoder&lt;TextCheckingResult&gt;::encode): Deleted.
(IPC::ArgumentCoder&lt;TextCheckingResult&gt;::decode): Deleted.
* Source/WebKit/Shared/WebCoreArgumentCoders.h:
* Source/WebKit/Shared/WebCoreArgumentCoders.serialization.in:
* Source/WebKit/UIProcess/ios/forms/WKFileUploadPanel.mm:
(cameraDeviceForMediaCaptureType):
(-[WKFileUploadPanel presentWithParameters:resultListener:]):
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Source/WebKitLegacy/ios/WebCoreSupport/WebChromeClientIOS.mm:
(webMediaCaptureType):
</pre>

2022-11-03 18:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7911b6cc27a64baadbb660a49b82939f3cc53f41. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-03 21:09 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9aff1836ae25207dc9b00af2ae626a63fafb173e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-04 06:10 UTC, pxlcoder commented on Source/WebCore/platform/text/TextChecking.h
> +enum class TextCheckingProcessType : uint8_t {
`uint8_t` -> `bool`

2022-11-07 11:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d6b1df06f92bd55b76b2b020a19f8935180076d5. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-07 12:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5cfcad6b2edc120b923ec034870a447f39a3f89f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-07 13:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa6b9a0dda0481acfadd6500f42d2b1db2d87249. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-07 14:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f6084c49b5c8bf4f989cfdba48c0b83b71498d2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-07 14:25 UTC, gavin-apple commented on Source/WebCore/platform/text/TextChecking.h
> +enum class TextCheckingProcessType : uint8_t {
Done

2022-11-07 18:11 UTC, achristensen07 requested changes

2022-11-07 18:11 UTC, achristensen07 commented on Source/WebCore/history/BackForwardItemIdentifier.h
> +    enum class ItemIdentifierType : uint8_t { };
This is suspicious.  I think BackForwardItemIdentifier should probably just be changed to use ProcessQualified.  ObjectIdentifiers are exposed through serialized_identifiers in messages.py

2022-11-07 18:11 UTC, achristensen07 commented on Source/WebKit/Scripts/generate-serializers.py
> +            if len(enum.valid_values) == 0:
This shouldn't be necessary.  We shouldn't be serializing enums with 0 valid values.

2022-11-08 20:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/17e535653f46d6b7f0ae3d46967bcfc95a8ed328. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-08 20:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/76359c7dadb4d66bc5fb0af1a3f4e0baeda0cdb0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-08 21:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/54821221e10efbc7a4d77c1a1ec9958cab25da89. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-08 21:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6b3572caef2e783023205f92427787d47630d49b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-09 10:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/77258b850713e2cbd09119e526ca2f36cfa7c1a9. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6091

2022-11-09 15:37 UTC, achristensen07 approved these changes

2022-11-09 15:40 UTC, webkit-commit-queue commented
Committed 256485@main (259c58ed79ec): <https://commits.webkit.org/256485@main>

Reviewed commits have been landed. Closing PR #6091 and removing active labels.

2022-11-09 15:40 UTC, merged