Remove idlharness.window test failure expectation
WebKit/WebKit pull request #6273
Opened 2022-11-08 23:16 UTC by salinas-miguel

#### 9beec60270e12ab4d375a5f01cf27215d436cad7
<pre>
Remove idlharness.window test failure expectation
<a href="https://bugs.webkit.org/show_bug.cgi?id=247650">https://bugs.webkit.org/show_bug.cgi?id=247650</a>
rdar://97228542

Reviewed by NOBODY (OOPS!).

The test seems to be passing for me locally.

* LayoutTests/platform/ios-wk2/TestExpectations:
</pre>

2022-11-08 23:18 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9beec60270e12ab4d375a5f01cf27215d436cad7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6273

2022-11-09 02:50 UTC, aproskuryakov requested changes
The test is still failing on the bots: https://results.webkit.org/?suite=layout-tests&test=imported%2Fw3c%2Fweb-platform-tests%2Fspeech-api%2Fidlharness.window.html

2022-11-11 22:10 UTC, salinas-miguel commented
Moving this out of "Draft" so that EWS can run this. I'm getting debug info from the iOS simulator bot failures.

2022-11-11 22:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8a3006d056d93dde7c68db109e426d3c8f6dd404. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6273

2022-11-15 20:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1b35b61148bf1ca58416a5cf0068a8c201a40422. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6273

2022-11-19 19:54 UTC, closed without merging