Mismatched whitespace widths cause a wrong width of inline box
WebKit/WebKit pull request #6342
Opened 2022-11-10 09:43 UTC by Ahmad-S792

<pre>
Mismatched whitespace widths cause a wrong width of inline box
<a href="https://bugs.webkit.org/show_bug.cgi?id=247722">https://bugs.webkit.org/show_bug.cgi?id=247722</a>

Reviewed by NOBODY (OOPS!).

Merge - <a href="https://src.chromium.org/viewvc/blink?view=revision&revision=195307">https://src.chromium.org/viewvc/blink?view=revision&revision=195307</a>

When we strip out trailing spaces in stripTrailingSpace(), we just subtract a raw space width without ceiling. This causes inline box including only image and whitespaces is wider than expected for some fonts. To fix this, we can simply subtract the trailing whitespace width after applying ceiling for consistence.

* Source/WebCore/rendering/RenderBlockFlow.cpp:
(RenderBlockFlow::stripTrailingSpace): Apply "ceiling" to "inlineMax"
* LayoutTests/fast/inline/inline-width-containing-collapsed-whitespace-and-image-in-float.html: Added Test Case
* LayoutTests/fast/inline/inline-width-containing-collapsed-whitespace-and-image-in-float-expected.txt: Added Test Case Expectations
</pre>

2022-11-10 09:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b3aa1d97f68c35604dd49c8277f2175cf7a5c42c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6342

2022-11-10 10:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0a165597e50b7f12fcf6eb31987e176da3177771. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6342

2022-11-11 23:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/43db0fc848299daca6c5e06fd0206aacad40a25e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6342

2022-11-12 12:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cedf37079962ae0553d1588f0c9e5d92d9784227. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6342

2022-11-12 14:18 UTC, alanbaradlay requested changes
This blink patch does not seem to be correct. It actually breaks simple-line-layout-fallback-space-glyph.html.

2022-11-12 14:23 UTC, Ahmad-S792 commented
> This blink patch does not seem to be correct. It actually breaks simple-line-layout-fallback-space-glyph.html.

If I go to failure of test case, it shows unexpected result in Expected with weird spaces of 0 being pushed down and 2 being on first line broken behavior and actual is similar to current behavior as this in [JSFiddle](https://jsfiddle.net/uv7149fL/show).

2022-11-12 14:25 UTC, alanbaradlay commented
surely it fixes some cases, but since it also brakes some other cases means that the blink patch is not complete.

2022-11-12 14:36 UTC, Ahmad-S792 commented
> surely it fixes some cases, but since it also brakes some other cases means that the blink patch is not complete.

Apologise, if I didn't get it, does this patch break more cases than shown from our test coverage, if Yes then I am happy to close this but if I go by this [test results](https://ews-build.s3-us-west-2.amazonaws.com/iOS-16-Simulator-WK2-Tests-EWS/43db0fc8-4173-rerun/fast/text/simple-line-layout-fallback-space-glyph-diffs.html), if I see expected and then actual, I think we now get correct result and it matches with all other browsers (Chrome Canary 109, Firefox Nightly 108) as well. Sorry, if I am confused. Apology in advance.

2022-11-12 14:55 UTC, alanbaradlay commented
1. this blink patch only affects the legacy line layout codepath.
2. simple-line-layout-fallback-space-glyph-expected.html is supposed to go down the legacy line layout codepath (the point of this test is to ensure that legacy and modern line layout agree).
3. You changed it so that it takes the modern line layout codepath now (and btw  .html and -expected.html look exactly the same now)
4. the failure [here](https://ews-build.s3-us-west-2.amazonaws.com/macOS-BigSur-Release-WK1-Tests-EWS/0a165597-19287/fast/text/simple-line-layout-fallback-space-glyph-diffs.html) shows the legacy line layout regression (which, again gets covered by the test file change)

2022-11-12 15:06 UTC, Ahmad-S792 commented
> 1. this blink patch only affects the legacy line layout codepath.
> 
> 2. simple-line-layout-fallback-space-glyph-expected.html is supposed to go down the legacy line layout codepath (the point of this test is to ensure that legacy and modern line layout agree).
> 
> 3. You changed it so that it takes the modern line layout codepath now (and btw  .html and -expected.html look exactly the same now)
> 
> 4. the failure [here](https://ews-build.s3-us-west-2.amazonaws.com/macOS-BigSur-Release-WK1-Tests-EWS/0a165597-19287/fast/text/simple-line-layout-fallback-space-glyph-diffs.html) shows the legacy line layout regression (which, again gets covered by the test file change)

Perfect! Make sense! I will look into any pre-requisite and see if bringing it does not regress behavior and if I didn't manage to find, I will close this. Thanks for clarifying and it helps in my learning. Apologies if I annoyed you with my queries. Thanks!

2022-11-12 15:30 UTC, alanbaradlay commented
> Perfect! Make sense! I will look into any pre-requisite and see if bringing it does not regress behavior and if I didn't manage to find, I will close this. Thanks for clarifying and it helps in my learning. Apologies if I annoyed you with my queries. Thanks!
Not at all!

2022-11-17 16:15 UTC, closed without merging