Fix order between initializing x and this.x in strict mode
WebKit/WebKit pull request #6438
Opened 2022-11-13 08:15 UTC by hyjorc1

#### 6b1504abf694f20c9169373c8d95cad0dd4c6e7a
<pre>
Fix order between initializing x and this.x in strict mode
<a href="https://bugs.webkit.org/show_bug.cgi?id=247493">https://bugs.webkit.org/show_bug.cgi?id=247493</a>
rdar://102064848

Reviewed by NOBODY (OOPS!).

Given following JavaScript program:
```
&quot;use strict&quot;;
x = this.x = 0;
```

It should throw ReferenceError since

<a href="https://tc39.es/ecma262/2022/multipage/ecmascript-language-expressions.html#sec-assignment-operators-runtime-semantics-evaluation">https://tc39.es/ecma262/2022/multipage/ecmascript-language-expressions.html#sec-assignment-operators-runtime-semantics-evaluation</a>
```
AssignmentExpression : LeftHandSideExpression = AssignmentExpression
1. If LeftHandSideExpression is neither an ObjectLiteral nor an ArrayLiteral, then
    ...
    e. Perform ? PutValue(lref, rval).
```

and

<a href="https://tc39.es/ecma262/2022/multipage/ecmascript-data-types-and-values.html#sec-putvalue">https://tc39.es/ecma262/2022/multipage/ecmascript-data-types-and-values.html#sec-putvalue</a>
```
4. If IsUnresolvableReference(V) is true, then
    a. If V.[[Strict]] is true, throw a ReferenceError exception
```

* JSTests/stress/put-to-scope-reference-error.js: Added.
(shouldThrow):
(shouldNotThrow):
* Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:
(JSC::LLInt::LLINT_SLOW_PATH_DECL):
</pre>

2022-11-13 08:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6b1504abf694f20c9169373c8d95cad0dd4c6e7a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6438

2022-11-13 09:31 UTC, Constellation requested changes
I think you need to fix the same thing in Baseline JIT, DFG, and FTL.

2022-11-13 10:19 UTC, rkirsling commented
Hmm, I'm not actually certain whether this change is web compatible, as it appears that no other browsers pass the test case in question either (_though engine262 does, which confirms the reporter's reading of the spec_).

The same reporter filed issues with [V8](https://bugs.chromium.org/p/v8/issues/detail?id=13453) and [SM](https://bugzilla.mozilla.org/show_bug.cgi?id=1799290); SM closed theirs as a duplicate of a 12(!)-year-old [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=605515), but it doesn't give a reason for not fixing it.

We definitely need to investigate this situation further before proceeding.

2022-11-14 01:22 UTC, rkirsling commented
Sure enough, this is web reality, not something for JSC to fix: https://github.com/tc39/ecma262/pull/2205

2022-11-14 17:35 UTC, Constellation commented
@rkirsling Oh, this is nice catch!

2022-11-14 18:27 UTC, closed without merging