Fix handling of calculated values in CSSStyleValue.parse()
WebKit/WebKit pull request #6874
Opened 2022-11-28 20:46 UTC by cdumez

#### b43488d79be12e40560c3402b4ed864726232249
<pre>
Fix handling of calculated values in CSSStyleValue.parse()
<a href="https://bugs.webkit.org/show_bug.cgi?id=248414">https://bugs.webkit.org/show_bug.cgi?id=248414</a>

Reviewed by NOBODY (OOPS!).

Calling CSSStyleValue.parse() with a `calc()` would return a generic CSSStyleValue
instead of the correct CSSMathValue subclass (e.g. CSSMathSum). This was causing
the CSSMathSum tests to fail in idlharness.html.

* LayoutTests/imported/w3c/web-platform-tests/css/css-typed-om/idlharness-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/css/css-typed-om/stylevalue-normalization/transformvalue-normalization.tentative-expected.txt:
* Source/WebCore/css/calc/CSSCalcValue.h:
* Source/WebCore/css/typedom/CSSNumericValue.cpp:
(WebCore::reifyMathExpression):
(WebCore::reifyMathExpressions):
(WebCore::CSSNumericValue::reifyMathExpression):
* Source/WebCore/css/typedom/CSSNumericValue.h:
* Source/WebCore/css/typedom/CSSStyleValue.cpp:
(WebCore::CSSStyleValue::parse):
* Source/WebCore/css/typedom/CSSStyleValueFactory.cpp:
(WebCore::CSSStyleValueFactory::reifyValue):
</pre>

2022-11-28 20:49 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b43488d79be12e40560c3402b4ed864726232249. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6874

2022-11-29 16:17 UTC, graouts requested changes

2022-11-29 16:17 UTC, graouts commented on Source/WebCore/css/typedom/CSSStyleValue.cpp
> +    WTFLogAlways("CHRIS: getType: %u", (unsigned)returnValue.at(0)->getType());
Might want to get rid of that one :)

2022-11-29 16:17 UTC, graouts commented on Source/WebCore/css/typedom/CSSStyleValueFactory.cpp
> +    WTFLogAlways("CHRIS: CSSStyleValueFactory::reifyValue() isPrimitiveValue? %d", is<CSSPrimitiveValue>(cssValue));
And that one too.

2022-11-29 17:29 UTC, cdumez commented on Source/WebCore/css/typedom/CSSStyleValue.cpp
> +    WTFLogAlways("CHRIS: getType: %u", (unsigned)returnValue.at(0)->getType());
Oops, fixed.

2022-11-29 17:29 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/cb92b17c248d422cda83391b0fcbe196739ae368)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/97991 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/7212 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/31152 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/107459 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/167740 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/101930 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/7672 "Built successfully") | [✅ 🛠 mac-debug](https://ews-build.webkit.org/#/builders/71/builds/36115 "Built successfully") | [  ~~🛠 gtk~~](https://ews-build.webkit.org/#/builders/36/builds/90697 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [💥 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/104078 "An unexpected error occured. Recent messages:Failed to print configuration") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/103632 "Passed tests") | [❌ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/5787 "Found 3 new test failures: imported/w3c/web-platform-tests/css/css-properties-values-api/typedom.html, imported/w3c/web-platform-tests/css/css-typed-om/the-stylepropertymap/declared/append.tentative.html, imported/w3c/web-platform-tests/css/css-typed-om/the-stylepropertymap/inline/append.tentative.html (failure)") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/84606 "Built successfully") | [❌ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/32937 "layout-tests (failure)") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/87654 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/89376 "Passed tests") | [  ~~🧪 api-gtk~~](https://ews-build.webkit.org/#/builders/34/builds/75858 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/1192 "Built successfully") | [  ~~🧪 mac-wk1~~](https://ews-build.webkit.org/#/builders/73/builds/20805 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/1166 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/22314 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/5999 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/44768 "Found 1 new test failure: http/wpt/service-workers/fetch-service-worker-preload-changing-request.https.html (failure)") | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/2457 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/41717 "Passed tests") | | </details>

2022-11-30 07:50 UTC, graouts commented
Sadly the iOS bot won't let me see the diff but there are a few tests that likely need rebase lining on that platform.

2022-11-30 16:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dba7f075c5906ccff2e2c138acdb061ee79c6da6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/6874

2022-11-30 18:33 UTC, cdumez commented
> Sadly the iOS bot won't let me see the diff but there are a few tests that likely need rebase lining on that platform.

I built for iOS locally and ran those tests and they passed. Not sure what's going on so I re-uploaded the same patch.

2022-11-30 19:19 UTC, graouts commented
> I built for iOS locally and ran those tests and they passed. Not sure what's going on so I re-uploaded the same patch.

Just need to wait 7 hours and all will be revealed.

2022-11-30 21:05 UTC, geoffreygaren approved these changes
r=me

2022-12-01 03:12 UTC, webkit-commit-queue commented
Committed 257215@main (ec3382a6412f): <https://commits.webkit.org/257215@main>

Reviewed commits have been landed. Closing PR #6874 and removing active labels.

2022-12-01 03:12 UTC, merged