[JSC] Fix race condition in Atomic.{wait,waitAsync}
WebKit/WebKit pull request #7048
Opened 2022-12-01 22:44 UTC by jjgriego

#### 1c71f8bd4e6f91ddc3450061f4ee97e575200b58
<pre>
[JSC] Fix race condition in Atomic.{wait,waitAsync}
<a href="https://bugs.webkit.org/show_bug.cgi?id=248631">https://bugs.webkit.org/show_bug.cgi?id=248631</a>

Reviewed by NOBODY (OOPS!).

At the moment, this is manifesting as intermittent timeouts in the arm32 linux
test runner, for example: <a href="https://build.webkit.org/#/builders/24/builds/17430">https://build.webkit.org/#/builders/24/builds/17430</a>

After investigation, this is the test `stress/waitasync-waiter-list-order.js`
hanging; this manifests as some of the workers hanging on the initial
`Atomic.wait` call in that test--using a debugger to examine the memory being
waited on reveals that they should all have woken up and moved on.

The implementation of both `Atomic.wait` and `Atomic.waitAsync` begin by
atomically reading from the array and comparing the result to the expected
value, then obtaining a lock on the list of waiters and proceeding from
there--this is contrary to the spec [1], which requires that the atomic read
happens while the list of waiters is exclusively locked and allows a race where
the following interleaving results in A hanging indefinitely if no other calls
to Atomic.notify on that address occur:

    thread A: begin Atomic.wait(buffer, idx, expected_value)
    thread A: read buffer[idx], get expected_value

    thread B: perform Atomic.store(buffer, idx, unexpected_value)
    thread B: perform Atomic.notify(buffer, idx) [nothing is notified since the list of waiters is empty]

    thread A: lock list of waiters, wait on condition variable, hang waiting for next notify

----

This is fixed by performing the atomic read while the lock on the list of
waiters is held; though, I had to rearrange several things to avoid pushing the
`ValueType` template parameter of `atomicsWaitImpl` further into the
implementation; the API to WaiterListManager is changed to allow its clients to
acquire the waiter list directly. I am happy to change this approach if
something else is preferred. (I considered passing the `Locker` object around
directly but this seems to expose less detail about the implementation and keeps
the public interface small)

[1] <a href="https://tc39.es/ecma262/multipage/structured-data.html#sec-atomics.wait">https://tc39.es/ecma262/multipage/structured-data.html#sec-atomics.wait</a>

* Source/JavaScriptCore/runtime/AtomicsObject.cpp:
(JSC::atomicsWaitImpl):
* Source/JavaScriptCore/runtime/WaiterListManager.cpp:
(JSC::LockedWaiterList::waitSync):
(JSC::LockedWaiterList::waitAsync):
(JSC::WaiterListManager::getLockedWaiterList):
(JSC::WaiterListManager::handleAsyncWaiterTimeout):
(JSC::WaiterListManager::wait): Deleted.
(JSC::WaiterListManager::addAsyncWaiter): Deleted.
* Source/JavaScriptCore/runtime/WaiterListManager.h:
(JSC::LockedWaiterList::LockedWaiterList):
</pre>

2022-12-01 22:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1c71f8bd4e6f91ddc3450061f4ee97e575200b58. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-01 23:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/73db99d3a9e2defb684744f1004843aa06fa0c9f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-01 23:18 UTC, jjgriego commented
Hm, this was passing all tests locally before, and is not now, moving to draft until I sort things out

2022-12-02 00:10 UTC, jjgriego commented
(OK, apparently also this way of formulating things does not satisfy `-Wthread-safety-analysis`, more reasons it's not ready for review )

2022-12-02 01:41 UTC, Constellation requested changes
Commented.

2022-12-02 01:41 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.h
> +    Locker<WTF::Lock> m_locker;
Locker should not be in a member of some objects since this is really dangerous idiom for locking.

2022-12-02 01:41 UTC, Constellation commented on Source/JavaScriptCore/runtime/AtomicsObject.cpp
> +    }
I think we should move these code in `WaiterListManager`. Extracting these part from `WaiterListManager` is making lock management harder (e.g., `LockedWaiterList` should not have Locker field.)

2022-12-02 01:41 UTC, Constellation commented on Source/JavaScriptCore/runtime/AtomicsObject.cpp
> +    switch (type) {
I think we can just have `wait32` and `wait64`, based on type of `ptr`.

2022-12-02 01:48 UTC, Constellation commented on Source/JavaScriptCore/runtime/AtomicsObject.cpp
> +    switch (type) {
Or, we can pass width, 4 or 8. and read based on that passed size.

2022-12-02 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/81d67b4b6ee05646297763aacff31ca40f5496d1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-02 21:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/81d67b4b6ee05646297763aacff31ca40f5496d1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-02 22:25 UTC, Constellation approved these changes
r=me with comments.

2022-12-02 22:25 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.cpp
> +                Ref<Waiter> waiter = adoptRef(*new Waiter(promise));
Do not perform GC allocation after taking a lock. It is unfortunate, but we should allocate promise before taking a lock.

2022-12-02 22:25 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.cpp
> +            return object;
Do these things after releasing lock, since it can have potential GC allocations.

2022-12-02 22:25 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.cpp
> +void WaiterListManager::timeoutAsyncWaiter(void* ptr, Ref<Waiter> waiter)
Take `Ref<Waiter>&&`.

2022-12-05 19:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5f5f93df2a92dd4f0af4908d470979596ef021a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-05 21:43 UTC, webkit-commit-queue commented
@jjgriego does not have committer permissions according to https://raw.githubusercontent.com/WebKit/WebKit/main/metadata/contributors.json.

If you do have committer permmissions, please ensure that your GitHub username is added to contributors.json.

Rejecting d5f5f93df2a92dd4f0af4908d470979596ef021a from merge queue.

2022-12-05 21:53 UTC, jjgriego commented
Actually it looks like some tests are hanging with this latest version... :/ I'll see if I can figure out why--maybe this surfaced some other bug?

2022-12-06 01:15 UTC, Constellation commented
Ah, looks like test failures are happening.

2022-12-06 06:43 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.cpp
> +        Ref<Waiter> waiter = adoptRef(*new Waiter(promise));
You should not create waiter when it is not added to the list.

2022-12-06 06:44 UTC, Constellation requested changes
Commented about the bug

2022-12-06 06:45 UTC, Constellation commented on Source/JavaScriptCore/runtime/WaiterListManager.cpp
> +        dataLogLnIf(WaiterListsManagerInternal::verbose && isAsync, "WaiterListManager added a new AsyncWaiter ", RawPointer(waiter.ptr()), " to a waiterList for ptr ", RawPointer(ptr));
This looks not so great, in particular, `isAsync`.
You should only use `WaiterListsManagerInternal::verbose` for disable / enable of this dataLog.

2022-12-06 16:51 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/698248f6519bb13180c5081c517d9ce9177d82ea. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7048

2022-12-06 20:10 UTC, webkit-commit-queue commented
Commit message contains (OOPS!) and no reviewer found, blocking PR #7048

2022-12-06 20:28 UTC, Constellation approved these changes

2022-12-06 20:31 UTC, webkit-commit-queue commented
Committed 257423@main (bb3be5c8f260): <https://commits.webkit.org/257423@main>

Reviewed commits have been landed. Closing PR #7048 and removing active labels.

2022-12-06 20:31 UTC, merged