Consume user gesture on window.open
WebKit/WebKit pull request #7156
Opened 2022-12-05 19:21 UTC by pascoej

#### a6f2a138b3098fcc7675e16eec3631a7a7981a4a
<pre>
Consume user gesture on window.open
<a href="https://bugs.webkit.org/show_bug.cgi?id=248767">https://bugs.webkit.org/show_bug.cgi?id=248767</a>
rdar://101191699

Reviewed by Geoff Garen.

* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::createNewPage):
Consume the user gesture on window.open, where it is currently not consumed.
Tools/TestWebKitAPI/Tests/WebKitCocoa/OpenAndCloseWindow.mm:
Test for above behavior.
</pre>
https://github.com/WebKit/WebKit/commit/a6f2a138b3098fcc7675e16eec3631a7a7981a4a

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/101044 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/10200 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/34099 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/110347 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/170603 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/105031 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/11130 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/1085 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/93477 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/108180 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/106827 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/8427 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/91694 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/35050 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/9/builds/90332 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/23090 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/34/builds/78041 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/3868 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/24607 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/3896 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/84/builds/1020 "Passed tests") | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/10008 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/44115 "Passed tests") | | 
| [  ~~🛠 🧪 merge~~](https://ews-build.webkit.org/#/builders/74/builds/5638 "The change is no longer eligible for processing.") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/5664 "Built successfully") | | | 
| | | | |

2022-12-05 19:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c541052cc4233e1923db3143952c790d418a186e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7156

2022-12-05 23:27 UTC, geoffreygaren approved these changes
r=me

Can you add an API test for this? I think you could write a test webpage that tried to window.open twice in response to a click, and then the API test could verify that -createWebViewWithConfiguration: only got called once.

2022-12-19 23:47 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2d35c7aa3a1b733307653d6fae557321c80ae373. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7156

2022-12-20 18:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a6f2a138b3098fcc7675e16eec3631a7a7981a4a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7156

2022-12-21 19:35 UTC, cdumez reviewed
It is not clear to me that this patch does anything useful.

The whole point of consuming a user gesture is to prevent using the same user gesture to do several operations that require a user gesture.

Note that the test only calls window.open once so it doesn't actually validate that we did anything.

The patch merely makes the user gesture as consumed in the UIProcess when window.open() gets called. AFAIK, this has zero impact on the WebProcess and follow-up calls to window.open() will have a non-consumed user gesture again.

Finally, we currently rely on the legacy UserGesture class for window.open. We should probably port the code over to the newer user activation logic (DOMWindow.consumeTransientActivation()). Any consuming should happen on the WebProcess side.

2022-12-21 19:37 UTC, cdumez requested changes
Please see comments above. At the very least the API test needs to be updated to prove that we can use a single user gesture to call window.open() several times.

2022-12-21 21:54 UTC, pascoej commented
> The whole point of consuming a user gesture is to prevent using the same user gesture to do several operations that require a user gesture.
Yes, this patch accomplishes that when tested via Safari.

> Note that the test only calls window.open once so it doesn't actually validate that we did anything.
Not true. It calls window.open twice. 
`evaluateJavaScript:@"window.open(\"about:blank\");window.open(\"about:blank\")"`

`The patch merely makes the user gesture as consumed in the UIProcess when window.open() gets called. AFAIK, this has zero impact on the WebProcess and follow-up calls to window.open() will have a non-consumed user gesture again.`
We don't trust the web process here, this does prevent a website from opening two windows from one button click.

`Finally, we currently rely on the legacy UserGesture class for window.open. We should probably port the code over to the newer user activation logic (DOMWindow.consumeTransientActivation()). Any consuming should happen on the WebProcess side.`
No, this is to handle something in a model where we do not trust the web process.

2022-12-21 22:35 UTC, cdumez commented
> We don't trust the web process here, this does prevent a website from opening two windows from one button click.

So why not write a test to prove it?

2022-12-21 22:37 UTC, cdumez commented
> > The whole point of consuming a user gesture is to prevent using the same user gesture to do several operations that require a user gesture.
> 
> Yes, this patch accomplishes that when tested via Safari.
> 
> > Note that the test only calls window.open once so it doesn't actually validate that we did anything.
> 
> Not true. It calls window.open twice.
> 
> `evaluateJavaScript:@"window.open(\"about:blank\");window.open(\"about:blank\")"`

I indeed missed that but your test doesn't check that createWebViewWithConfiguration is only called once?

2023-01-07 00:04 UTC, closed without merging