Update test262 bot to Ventura
WebKit/WebKit pull request #7364
Opened 2022-12-09 00:35 UTC by chgibb-apple

#### 802468c4036645aac3473ee5077ce81fab53adda
<pre>
Update test262 bot to Ventura
<a href="https://bugs.webkit.org/show_bug.cgi?id=248992">https://bugs.webkit.org/show_bug.cgi?id=248992</a>
rdar://102916599

Reviewed by Ryan Haddad.

Update test262 bot to Ventura

* Tools/CISupport/build-webkit-org/config.json:
* Tools/CISupport/build-webkit-org/factories_unittest.py:
(TestExpectedBuildSteps):
* Tools/CISupport/build-webkit-org/public_html/dashboard/Scripts/WebKitBuildbot.js:
(WebKitBuildbot):

Canonical link: <a href="https://commits.webkit.org/257813@main">https://commits.webkit.org/257813@main</a>
</pre>

2022-12-09 00:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2ed08e013f2eb8cf59b1547fbfab43d2edf877aa. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7364

2022-12-09 00:50 UTC, ryanhaddad requested changes
You'll need to move the trigger for this queue from `Apple-Monterey-Release-Build` to `Apple-Ventura-Release-Build`

2022-12-09 01:07 UTC, chgibb-apple commented
I think I've made the relevant changes to the trigger now.

2022-12-09 01:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0875e6d722be5c5e94c58136a15987c1662704bb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7364

2022-12-09 19:17 UTC, ryanhaddad requested changes

2022-12-09 19:17 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                        "ventura-release-tests-test262"
```suggestion
                        "ventura-applesilicon-release-tests-test262"
```

2022-12-09 19:17 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
> +                    },
This isn't needed since you're only moving the AppleSilicon queue.

2022-12-09 19:17 UTC, ryanhaddad commented on Tools/CISupport/build-webkit-org/config.json
>                      { "type": "Triggerable", "name": "monterey-applesilicon-release-tests-test262",
```suggestion
                    { "type": "Triggerable", "name": "ventura-applesilicon-release-tests-test262",
```

2022-12-12 23:19 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/23f666fae53593067df37e1cdb8e1bf24f95b8c1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7364

2022-12-12 23:35 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/d90d918d97b4ad969564d30b1160ff2bb481591b)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/99950 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/9115 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/43/builds/33026 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/109296 "Built successfully") | [✅ 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/169533 "Built successfully and passed tests") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/103949 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/9998 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/61/builds/86412 "Built successfully") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/92395 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/12/builds/107199 "Built successfully") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/105718 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/78/builds/7555 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/3/builds/90828 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/35/builds/34269 "Passed tests") | 
| | [  ~~🧪 api-ios~~](https://ews-build.webkit.org/#/builders/9/builds/89461 "The change is no longer eligible for processing. Commit was outdated when EWS attempted to process it.") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/73/builds/22219 "Passed tests") | [⏳ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/API-Tests-GTK-EWS "Waiting to run tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/81/builds/2916 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/70/builds/23732 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/2874 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/60/builds/46109 "Passed tests") | | 
| [✅ 🧪 services](https://ews-build.webkit.org/#/builders/20/builds/98873 "Passed tests") | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/9007 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/62/builds/43206 "Passed tests") | | 
| [❌ 🛠 🧪 merge](https://ews-build.webkit.org/#/builders/74/builds/5329 "Commit message contains (OOPS!)") | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/4724 "Built successfully") | | | 
| | | | | </details>

2022-12-12 23:44 UTC, ryanhaddad approved these changes

2022-12-13 00:55 UTC, webkit-commit-queue commented
Commit message contains (OOPS!), blocking PR #7364

2022-12-13 21:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b8ce3be7ab5014f088e8aedd8e4c82c4d34c474b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7364

2022-12-13 22:33 UTC, merged

2022-12-13 22:33 UTC, webkit-commit-queue commented
Committed 257813@main (802468c40366): <https://commits.webkit.org/257813@main>

Reviewed commits have been landed. Closing PR #7364 and removing active labels.