CSS `::marker` does not support defining CSS variables
WebKit/WebKit pull request #7376
Opened 2022-12-09 05:06 UTC by karlcow

#### 13f620ff9e1bfb79fe64e825de07a99f74f36c1e
<pre>
CSS `::marker` does not support defining CSS variables
<a href="https://bugs.webkit.org/show_bug.cgi?id=241566">https://bugs.webkit.org/show_bug.cgi?id=241566</a>
rdar://problem/95551387

Reviewed by NOBODY (OOPS!).

This aligns WebKit with Firefox and Chrome. It adds
CSSPropertyCustom into isValidMarkerStyleProperty.

* Source/WebCore/style/PropertyAllowlist.cpp:
(WebCore::Style::isValidMarkerStyleProperty):
(WebCore::Style::isValidCueStyleProperty):
</pre>

2022-12-09 05:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/13f620ff9e1bfb79fe64e825de07a99f74f36c1e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7376

2022-12-09 07:50 UTC, nt1m requested changes
Please add a reftest (WPT would be the preference).

2022-12-09 08:49 UTC, anttijk approved these changes

2022-12-09 08:52 UTC, anttijk commented
A test would be cool.

2022-12-09 13:22 UTC, karlcow commented
> Please add a reftest (WPT would be the preference).

@nt1m https://github.com/web-platform-tests/wpt/pull/37427/files
would that work.

I tried an automated test, but I can't extract the color with `window.getComputedStyle` (maybe anti-fingerprinting?)

2022-12-09 16:47 UTC, brandonmcconnell commented
@karlcow I'm able to extract the colors for `::marker` using `window.getComputedStyle`'s second arg. Both should work in Safari as well once the fix has been added. Currently, a color value is extracted in both browsers, but—due to this bug—Safari shows `rgb(0, 0, 0)` for the second test, which should change once this fix is in place:
* Test #1: https://codepen.io/brandonmcconnell/pen/XWYQXVx/00443c64dda4b652a5aa9e799e68a8bf
* Test #2: https://codepen.io/brandonmcconnell/pen/XWYQKYa/bce9808bf5d624fab3a81ee35a778d47

Hope this helps 🙂

```js
for (const li of document.querySelectorAll('li')) {
  const markerStyles = window.getComputedStyle(li, 'marker');
  const markerColor = markerStyles.color; // <-- the extracted color
}
```

| Test | Chrome | Safari |
| - | - | - |
| 1 | ![Screenshot 2022-12-09 at 11 40 34 AM](https://user-images.githubusercontent.com/5913254/206750569-92ef3789-1361-4fed-b5a2-8c30df6abdb8.png) | ![Screenshot 2022-12-09 at 11 43 23 AM](https://user-images.githubusercontent.com/5913254/206750589-bbe896d6-9bbb-4279-b4dc-422f194ac639.png) |
| 2 | ![Screenshot 2022-12-09 at 11 40 43 AM](https://user-images.githubusercontent.com/5913254/206750579-b87ddeb7-6ba2-45f3-be5a-225b431daa5a.png) | ![Screenshot 2022-12-09 at 11 43 31 AM](https://user-images.githubusercontent.com/5913254/206750617-244118f1-b227-4bb1-b419-26f23f7df6a1.png) |

2022-12-10 00:18 UTC, karlcow commented
> @karlcow I'm able to extract the colors for `::marker` using `window.getComputedStyle`'s second arg. 

doh! I realized my mistake this morning. OK. I have an automated test. 
conundrum. Firefox fails the automated test, while still doing the right thing for the color.

2022-12-10 05:27 UTC, nt1m approved these changes
Can you import the 2 tests you've added as part of this patch?

2022-12-12 02:16 UTC, karlcow commented
> Can you import the 2 tests you've added as part of this patch?

@nt1m DONE!

2022-12-12 02:17 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eab5e35e8e613dd793e44b5344ad47e5195570ee. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7376

2022-12-12 04:14 UTC, webkit-commit-queue commented
Committed 257711@main (52052a276f0d): <https://commits.webkit.org/257711@main>

Reviewed commits have been landed. Closing PR #7376 and removing active labels.

2022-12-12 04:14 UTC, merged