[GStreamer] refactor video decoder limit customization
WebKit/WebKit pull request #7381
Opened 2022-12-09 10:24 UTC by pgorszkowski-igalia

#### 3f4aec5cc7859ce9426e31c2a4e69d5d61a60b29
<pre>
[GStreamer] refactor video decoder limit customization
<a href="https://bugs.webkit.org/show_bug.cgi?id=248961">https://bugs.webkit.org/show_bug.cgi?id=248961</a>

Reviewed by NOBODY (OOPS!).

Moved the same functionality to one place - from
MediaPlayerPrivateGStreamerMSE::supportsType to
GStreamerRegistryScanner::isContentTypeSupported.

* Source/WebCore/platform/GStreamer.cmake:
* Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp:
(videoDecoderLimitsDefaults):
(WebCore::GStreamerRegistryScanner::isContentTypeSupported const):
* Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp:
(WebCore::MediaPlayerPrivateGStreamerMSE::supportsType):
(videoDecoderLimitsDefaults): Deleted.
</pre>

2022-12-09 10:25 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3f4aec5cc7859ce9426e31c2a4e69d5d61a60b29. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7381

2022-12-09 11:13 UTC, eocanha requested changes
Appart from the comments, the rest of the changes look fine to me.

2022-12-09 11:13 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
> +            ASSERT_NOT_REACHED();
The style checker complained about this. Try adding `return SupportsType::IsNotSupported;` after this line to ensure that an early return happens in case assertions are disabled at runtime.

2022-12-09 11:13 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
> +        {
I think this should be one tab less, like in [this example](https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/graphics/gstreamer/mse/GStreamerMediaDescription.h#L51).

2022-12-13 12:57 UTC, pgorszkowski-igalia commented on Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
> +            ASSERT_NOT_REACHED();
Do we really want to return IsNotSupport in case of wrongly set VIDEO_DECODING_LIMIT? The consequence will be that none of the stream will be played.

2022-12-13 13:13 UTC, eocanha commented on Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
> +            ASSERT_NOT_REACHED();
If the packager has decided to enable VIDEO_DECODING_LIMIT in CMake, then they should take care of properly defining the limit. Getting all the videos failing is a good way of noticing that something is wrong, so it's acceptable to me (although I'm not a reviewer).

2022-12-13 16:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b0cc7e312ae3570afd66eb8d5606da387ed9693c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7381

2023-02-20 10:56 UTC, philn requested changes
Could these checks be done only when `configuration == Configuration::Decoding`?

2023-03-03 08:17 UTC, pgorszkowski-igalia commented
> Could these checks be done only when configuration == Configuration::Decoding?

Sorry for late response, I will add it ASAP.

2023-04-03 10:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/44771436519e38513bc8c9e463978f8e23ec473b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7381

2023-04-24 14:32 UTC, philn commented on Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp
> +    });
This looks a bit convoluted, instead of reusing `entries`, maybe build a new vector? `auto widthAndHeight = entries[0].split('x');`?

2023-04-25 14:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/7e64ee9fe2b1c0dd664ce9f5c126fc78710cdb50. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7381

2023-04-25 15:09 UTC, philn approved these changes

2023-04-26 06:14 UTC, pgorszkowski-igalia commented
It works with correct value e.g.:
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024x768@25

I tested it also with few incorrect values:
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024x768@
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024x768
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024x
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024
Tools/Scripts/build-webkit --gtk --cmakeargs=-DVIDEO_DECODING_LIMIT=1024@25

In  case of incorrect value the limit is not applied - as expected.

For testing I used dashjs reference player: 
Tools/Scripts/run-minibrowser --gtk https://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

2023-04-26 08:18 UTC, webkit-commit-queue commented
Committed 263408@main (c36758395b16): <https://commits.webkit.org/263408@main>

Reviewed commits have been landed. Closing PR #7381 and removing active labels.

2023-04-26 08:18 UTC, merged