JetStream3 harness: reset seed of Math.random() on every benchmark iteration
WebKit/WebKit pull request #7858
Opened 2022-12-19 18:41 UTC by shvaikalesh

#### 1e35def308d6280321e611c96c1fb7c3e401ef49
<pre>
JetStream3 harness: reset seed of Math.random() on every benchmark iteration
<a href="https://bugs.webkit.org/show_bug.cgi?id=249592">https://bugs.webkit.org/show_bug.cgi?id=249592</a>

Reviewed by NOBODY (OOPS!).

This change extracts Math.random() implementation, which resets its seed on every iteration,
from simple/file-system.js to be used for all other tests, including newly-added BigInt crypto
tests that heavily rely on Math.random().

* PerformanceTests/JetStream3/JetStreamDriver.js:
(prototype.get runnerCode):
(prototype.get preiterationCode):
(prototype.async run):
(AsyncBenchmark.get runnerCode.return.async doRun):
(AsyncBenchmark.prototype.get runnerCode):
(AsyncBenchmark):
* PerformanceTests/JetStream3/simple/file-system.js:
(Benchmark.prototype.async runIteration):
(Benchmark):
(resetSeed): Deleted.
(Math.random): Deleted.
</pre>

2022-12-19 18:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1e35def308d6280321e611c96c1fb7c3e401ef49. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/7858

2022-12-19 18:53 UTC, Constellation requested changes
I think we should just use this deterministic random thing for crypto test too since `__resetSeed` is not a standard function.
V8 / SpiderMonkey will not support it, and exposing different results due to non-standard function is not OK as a performance benchmark test.

2022-12-19 19:22 UTC, Constellation approved these changes
Oops, sorry. I completely misunderstood the patch!! (I wasm thinking about the opposite thing). This patch is applying the deterministic random to the other benchmarks. This is totally making sense.

2022-12-21 21:34 UTC, shvaikalesh commented
Thanks Yusuke!

2022-12-21 21:37 UTC, webkit-commit-queue commented
Committed 258213@main (7bca60ef1a17): <https://commits.webkit.org/258213@main>

Reviewed commits have been landed. Closing PR #7858 and removing active labels.

2022-12-21 21:37 UTC, merged