Add exclusive "shouldBeGreaterThan" function to js-test.js similar to Chromium
WebKit/WebKit pull request #8321
Opened 2023-01-06 21:43 UTC by Ahmad-S792

<pre>
Add exclusive "shouldBeGreaterThan" function to js-test.js similar to Chromium
<a href="https://bugs.webkit.org/show_bug.cgi?id=250227">https://bugs.webkit.org/show_bug.cgi?id=250227</a>

Reviewed by NOBODY (OOPS!).

This patch adds exclusive "shouldBeGreaterThan" function to check values greater than
without "equal" part and it is pre-requisite for one of SVG SMIL animation test case.

* LayoutTests/resources/js-test.js: Add "shouldBeGreaterThan" function
</pre>

2023-01-06 21:44 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f9e278accd9f5a9cf8888ce531879bb2c2a5f73f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8321

2023-01-06 23:07 UTC, rniwa approved these changes
Maybe also update the copyright text?

2023-01-06 23:20 UTC, Ahmad-S792 commented
> Maybe also update the copyright text?

This file (js-test.js) and in Chromium both don't have any COPYRIGHT text, so I just added two lines:

`// Copyright 2014 Google Inc.  All rights reserved.` (Because the commit, I am merging is of 2014 and at that time, this existed.)
`// Copyright 2023 Google Inc.  All rights reserved.`

2023-01-06 23:24 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/09c5f67caeab35d35d62bc8f8c1ed3104cecd575. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8321

2023-01-06 23:28 UTC, aproskuryakov commented
I would expect any addition to this file to touch multiple files, not one. Also js-test-pre.js, and several copies of those in the repository.

2023-01-06 23:31 UTC, rniwa commented
> I would expect any addition to this file to touch multiple files, not one. Also js-test-pre.js, and several copies of those in the repository.

They're already out of sync with one another. I don't think we need to add this functionality to all the files.

2023-01-06 23:33 UTC, Ahmad-S792 commented
> > I would expect any addition to this file to touch multiple files, not one. Also js-test-pre.js, and several copies of those in the repository.
> 
> They're already out of sync with one another. I don't think we need to add this functionality to all the files.

> I would expect any addition to this file to touch multiple files, not one. Also js-test-pre.js, and several copies of those in the repository.

Plus, I checked via searchfox.org (wubkat) to see how many copies of "js-test.js", we have and we only have one. As for 'js-test-pre.js', I didn't updated because we are discouraging use of it. Hence, I didn't update it.

2023-01-06 23:33 UTC, aproskuryakov commented
> They're already out of sync with one another. I don't think we need to add this functionality to all the files.

Why not? I am pretty strongly against making our test harness more inconsistent and confusing, and object to landing as is.

2023-01-06 23:33 UTC, aproskuryakov requested changes
Please update other copies of the test harness.

2023-01-06 23:36 UTC, Ahmad-S792 commented
> Please update other copies of the test harness.

Should I update all of these (js-test-pre) files?

<img width="488" alt="image" src="https://user-images.githubusercontent.com/52317531/211117388-d8afb4b2-dc15-42b9-8eba-9c52a86df1d8.png">

2023-01-06 23:47 UTC, aproskuryakov commented
I think that we want to keep non-imported copies in sync, so `webgl/2.0.0`, `webgl/1.0.3` and `js/mozilla` shouldn't be updated. Not entirely sure about the unversioned webgl ones, but most of all, `resources/js-test-pre.js`and `http/tests/resources/js-test-pre.js` should not diverge, because that's just crazy for these to be different.

2023-01-06 23:47 UTC, rniwa commented
> > They're already out of sync with one another. I don't think we need to add this functionality to all the files.
> 
> Why not? I am pretty strongly against making our test harness more inconsistent and confusing, and object to landing as is.

Because js-test-pre.js is deprecated. Nobody should be using that for new tests.

2023-01-06 23:48 UTC, rniwa commented
> I think that we want to keep non-imported copies in sync, so `webgl/2.0.0`, `webgl/1.0.3` and `js/mozilla` shouldn't be updated. Not entirely sure about the unversioned webgl ones, but most of all, `resources/js-test-pre.js`and `http/tests/resources/js-test-pre.js` should not diverge, because that's just crazy for these to be different.

They're already vastly different / divergent. That ship has sailed long ago.

2023-01-06 23:51 UTC, rniwa commented
> > I think that we want to keep non-imported copies in sync, so `webgl/2.0.0`, `webgl/1.0.3` and `js/mozilla` shouldn't be updated. Not entirely sure about the unversioned webgl ones, but most of all, `resources/js-test-pre.js`and `http/tests/resources/js-test-pre.js` should not diverge, because that's just crazy for these to be different.
> 
> They're already vastly different / divergent. That ship has sailed long ago.

Take a look at `diff LayoutTests/resources/js-test.js LayoutTests/resources/js-test-pre.js`. That diff is ginormous. There really isn't much benefit in trying to keep them in sync anymore.

2023-01-06 23:52 UTC, aproskuryakov commented
> Because js-test-pre.js is deprecated. Nobody should be using that for new tests.

That's almost correct, but not 100%. `js-test.js` machinery is more complex, and doesn't play great with some tests, like those that navigate, and I think I saw some other cases where pre/post variant was more appropriate.

2023-01-06 23:52 UTC, Ahmad-S792 commented
I am happy to do changes but I do agree with @rniwa that since we discourage use of js-test-pre now, it wouldn't matter if we don't update it. Since contributor like myself should use 'js-test.js' and I also update any impacting test using old script with my other PRs and I update them to newer script as well.

2023-01-06 23:54 UTC, Ahmad-S792 commented
I have already all changes in PR ready to squash and force push as new one. So it wouldn't take much of my time.

2023-01-07 00:57 UTC, Ahmad-S792 commented
@aproskuryakov - Updated commit message and PR title and also two js-test-pre scripts as mentioned in your comment. I didn't touched "WebGL" ones.

2023-01-07 00:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/879d5d522d3f620448c0ab0baca29505c2757102. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8321

2023-01-07 00:59 UTC, aproskuryakov approved these changes

2023-01-07 14:40 UTC, webkit-commit-queue commented
Committed 258613@main (24d9e4a1e3d3): <https://commits.webkit.org/258613@main>

Reviewed commits have been landed. Closing PR #8321 and removing active labels.

2023-01-07 14:40 UTC, merged