[ iOS macOS ] 4X imported/w3c/web-platform-tests/html/cross-origin-opener-policy/(Layout tests) are flaky failures
WebKit/WebKit pull request #8651
Opened 2023-01-14 03:03 UTC by cdumez

#### ad1e8853bdf3b4149ea751d1081d7a5acbd6e766
<pre>
[ iOS macOS ] 4X imported/w3c/web-platform-tests/html/cross-origin-opener-policy/(Layout tests) are flaky failures
<a href="https://bugs.webkit.org/show_bug.cgi?id=244358">https://bugs.webkit.org/show_bug.cgi?id=244358</a>
rdar://99153669

Reviewed by NOBODY (OOPS!).

Improve support for WPT test variants so that tests correctly get split up into
variants. This is a way that is frequently used to split slow tests and avoid
time outs.

* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/coep-navigate-popup.https_0-1-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/coep-navigate-popup.https_2-3-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/coep-navigate-popup.https_4-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/header-parsing-failures.https_1-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/header-parsing-failures.https_12-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/header-parsing-failures.https_5-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/header-parsing-failures.https_9-12-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin-allow-popups.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin-allow-popups.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin-allow-popups.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin-allow-popups.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin-allow-popups.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-same-origin.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-cross-origin-popup.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-cross-origin-popup.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-cross-origin-popup.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-cross-origin-popup.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-cross-origin-popup.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-origin-popup.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-origin-popup.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-origin-popup.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-origin-popup.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-origin-popup.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-site-popup.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-site-popup.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-site-popup.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-site-popup.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none-same-site-popup.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https-expected.txt: Removed.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-allow-popups-to-unsafe-none.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-same-origin.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-same-origin.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-same-origin.https_5-6-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-same-origin.https_7-8-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-same-origin.https_9-last-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-unsafe-none.https_1-2-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-unsafe-none.https_3-4-expected.txt: Added.
* LayoutTests/imported/w3c/web-platform-tests/html/cross-origin-opener-policy/iframe-popup-same-origin-to-unsafe-none.https_5-6-expected.txt: Added.
* LayoutTests/impor [...]

2023-01-14 03:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad1e8853bdf3b4149ea751d1081d7a5acbd6e766. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-14 04:52 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/231dbc0996ef28d728216a7e329f1facc71634ac. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-14 23:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/225e0e9414813cabbca96df1ddfc867bff4cf44e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-14 23:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/225e0e9414813cabbca96df1ddfc867bff4cf44e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-15 20:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/fa89c4e059e7da97efc054e716e0f14a22a03fc0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 15:47 UTC, JonWBedard requested changes
Looks like this breaks `webkitpy` unit tests, EWS didn't run them, probably because too many files changed and we hit our pagination limit in EWS, will be looking into that. In any case, the problem readily reproduces locally.

2023-01-17 16:23 UTC, cdumez commented
> Looks like this breaks `webkitpy` unit tests, EWS didn't run them, probably because too many files changed and we hit our pagination limit in EWS, will be looking into that. In any case, the problem readily reproduces locally.

Ok, will take a look. Thanks.

2023-01-17 17:08 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/5d1fe7bc68efba332a07588578d8f930445f7e4d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 17:35 UTC, cdumez commented
I have addressed all the webkitpy failures.

2023-01-17 17:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/43d258dd849e27a92ea6853aeaece6375a40aa30. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 17:35 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/43d258dd849e27a92ea6853aeaece6375a40aa30. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 18:07 UTC, pascoej approved these changes
This LGTM. Thanks for adding this.

2023-01-17 18:39 UTC, JonWBedard commented on Tools/Scripts/webkitpy/layout_tests/controllers/single_test_runner.py
> +            (output_basename, variant) = output_basename.split('?')
Should use `.split('?', 1)`, even though having a `?` in a variant would kind of be crazy.

2023-01-17 18:39 UTC, JonWBedard commented on Tools/Scripts/webkitpy/layout_tests/controllers/test_result_writer.py
> +            (test_name, variant) = test_name.split('?')
Ditto use `.split('?', 1)`

2023-01-17 18:39 UTC, JonWBedard commented on Tools/Scripts/webkitpy/port/base.py
> +            (test_name, variant) = test_name.split('?')
Ditto use `.split('?', 1)`

2023-01-17 18:39 UTC, JonWBedard approved these changes

2023-01-17 18:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/148884582d5ae999700cae1b536cdc4094018870. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 18:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/148884582d5ae999700cae1b536cdc4094018870. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8651

2023-01-17 23:09 UTC, webkit-commit-queue commented
Committed 259006@main (9833f67e85a7): <https://commits.webkit.org/259006@main>

Reviewed commits have been landed. Closing PR #8651 and removing active labels.

2023-01-17 23:10 UTC, merged