Clean up WebKitAdditions logic in postprocess-header-rule
WebKit/WebKit pull request #8747
Opened 2023-01-18 01:45 UTC by emw-apple

#### a79898f51c577e596d64b53d834e13b6e10824ce
<pre>
Clean up WebKitAdditions logic in postprocess-header-rule
<a href="https://bugs.webkit.org/show_bug.cgi?id=250740">https://bugs.webkit.org/show_bug.cgi?id=250740</a>
rdar://104354248

Reviewed by NOBODY (OOPS!).

postprocess-framework-headers-definitions is no longer needed for
internal builds.

* Source/JavaScriptCore/Scripts/postprocess-header-rule:

Reland 259000@main, which is fixed in internal builds by the underlying
change.

* Source/JavaScriptCore/API/JSRemoteInspector.cpp:
(JSRemoteInspectorGetInspectionFollowsInternalPolicies):
(JSRemoteInspectorSetInspectionFollowsInternalPolicies):
* Source/JavaScriptCore/API/JSRemoteInspector.h:
* Source/JavaScriptCore/inspector/JSGlobalObjectInspectorController.cpp:
(Inspector::JSGlobalObjectInspectorController::developerExtrasEnabled const):
* Source/JavaScriptCore/inspector/remote/RemoteInspectionTarget.cpp:
(Inspector::RemoteInspectionTarget::remoteControlAllowed const):
(Inspector::RemoteInspectionTarget::allowsInspectionByPolicy const):
(Inspector::RemoteInspectionTarget::inspectable const):
(Inspector::RemoteInspectionTarget::setInspectable):
(Inspector::RemoteInspectionTarget::pauseWaitingForAutomaticInspection):
* Source/JavaScriptCore/inspector/remote/RemoteInspectionTarget.h:
* Source/JavaScriptCore/inspector/remote/cocoa/RemoteInspectorCocoa.mm:
(Inspector::RemoteInspector::listingForInspectionTarget const):
* Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorGlib.cpp:
(Inspector::RemoteInspector::listingForInspectionTarget const):
* Source/JavaScriptCore/inspector/remote/socket/RemoteInspectorSocket.cpp:
(Inspector::RemoteInspector::listingForInspectionTarget const):
* Source/WebCore/bindings/js/JSDOMGlobalObject.cpp:
(WebCore::JSDOMGlobalObject::finishCreation):
* Source/WebKit/UIProcess/API/Cocoa/APISerializedScriptValueCocoa.mm:
(API::SharedJSContext::ensureContext):

Co-authored-by: Patrick Angle &lt;pangle@apple.com&gt;
</pre>

2023-01-18 01:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a79898f51c577e596d64b53d834e13b6e10824ce. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8747

2023-01-18 22:10 UTC, aproskuryakov requested changes
Marking as "request changes" for now, while we are discussing in internal PR.

2023-01-18 22:17 UTC, patrickangle reviewed
This patch will not need to roll back in the remote inspection fix. That fix is re-landing in https://github.com/WebKit/WebKit/pull/8773 with a workaround. When this is ready, there is a FIXME in that PR to add the availability annotations to the new methods though.

2023-02-17 18:57 UTC, emw-apple commented
Closing this, I've moved forward with a different approach.

2023-02-17 18:57 UTC, closed without merging