Fix use-after-move on navigationActionData
WebKit/WebKit pull request #8822
Opened 2023-01-19 10:26 UTC by charliewolfe

#### 4fe3368f79fd9cfaadd9bb191f64761b98bff6dd
<pre>
Fix use-after-move on navigationActionData
<a href="https://bugs.webkit.org/show_bug.cgi?id=250826">https://bugs.webkit.org/show_bug.cgi?id=250826</a>
rdar://104420066

Reviewed by NOBODY (OOPS!).

This patch fixes a use-after-move on `navigationActionData`. This is
benign, but we should still change this to fix the clang-tidy warning.

* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::decidePolicyForNavigationAction):
</pre>

2023-01-19 10:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4fe3368f79fd9cfaadd9bb191f64761b98bff6dd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8822

2023-01-19 14:19 UTC, youennf approved these changes

2023-01-19 14:19 UTC, youennf commented on Source/WebKit/UIProcess/WebPageProxy.cpp
> +            auto navigationAction = API::NavigationAction::create(WTFMove(navigationActionData), sourceFrameInfo.get(), destinationFrameInfo.ptr(), std::nullopt, ResourceRequest(request), originalReq
Could be moved closer to receivedPolicyDecision call.

2023-01-19 21:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e2fe6f4ab7c24ed1bd2b253ea4210fba41a8ed88. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8822

2023-01-20 17:15 UTC, ddkilzer requested changes
I think we should switch to using `navigationAction.data()` to access `navigationActionData` values after creating the `navigationAction` object.

2023-01-20 17:15 UTC, ddkilzer commented on Source/WebKit/UIProcess/WebPageProxy.cpp
> -    auto navigationAction = API::NavigationAction::create(WTFMove(navigationActionData), sourceFrameInfo.get(), destinationFrameInfo.ptr(), std::nullopt, ResourceRequest(request), originalRequest.url
Overall, this is an okay change, but taking one line of code and duplicating it into three places, which makes it harder to keep all the copies in sync.

Are we able to get to the `navigationData` from the `navigationAction` object after it's created?  Yes, we can through the `data()` method, so let's just keep this one line, and change the code below to stop using `navigationActionData` directly.

For example, `navigationActionData.` becomes `navigationAction.data().` on Line 5731:
```
    bool canHandleRequest = navigationActionData.canHandleRequest || m_urlSchemeHandlersByScheme.contains<StringViewHashTranslator>(request.url().protocol());
```

To this:
```
    bool canHandleRequest = navigationAction.data().canHandleRequest || m_urlSchemeHandlersByScheme.contains<StringViewHashTranslator>(request.url().protocol());
```

Line 5732 is the only other change I think.

2023-01-20 22:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/db2860288ee89b9bafb2921322000e75aef53bf7. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8822

2023-01-21 04:25 UTC, ddkilzer approved these changes
r=me

2023-01-21 05:31 UTC, webkit-commit-queue commented
Committed 259164@main (2f177bcd375a): <https://commits.webkit.org/259164@main>

Reviewed commits have been landed. Closing PR #8822 and removing active labels.

2023-01-21 05:31 UTC, merged