[ResizeObserver] The initial value of the last reported size should be -1x-1
WebKit/WebKit pull request #8839
Opened 2023-01-19 17:37 UTC by cathiechen

#### ac99702375bd79af9707ab22aa3162aef81690a3
<pre>
[ResizeObserver] The initial value of the last reported size should be -1x-1
<a href="https://bugs.webkit.org/show_bug.cgi?id=157743">https://bugs.webkit.org/show_bug.cgi?id=157743</a>

Reviewed by NOBODY (OOPS!).

The conclusion of [1] indicates that when first observing an element with ResizeObserver,
lastReportedSize gets initialized with a -1 x -1 size.

[1] <a href="https://bugs.webkit.org/show_bug.cgi?id=250836">https://bugs.webkit.org/show_bug.cgi?id=250836</a>

* LayoutTests/imported/w3c/web-platform-tests/resize-observer/notify-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/resize-observer/observe-expected.txt:
* LayoutTests/imported/w3c/web-platform-tests/resize-observer/svg-expected.txt:
* LayoutTests/platform/mac/imported/w3c/web-platform-tests/resize-observer/svg-expected.txt:
* Source/WebCore/page/ResizeObservation.cpp:
</pre>

2023-01-19 17:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ac99702375bd79af9707ab22aa3162aef81690a3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8839

2023-01-19 17:46 UTC, Loirooriol commented
The commit message seems wrong.

The bug for this is https://bugs.webkit.org/show_bug.cgi?id=250836 instead of https://bugs.webkit.org/show_bug.cgi?id=157743
And the link should point to https://github.com/w3c/csswg-drafts/issues/3664 instead of https://bugs.webkit.org/show_bug.cgi?id=250836

2023-01-19 17:47 UTC, Loirooriol approved these changes
LGTM if you fix the commit message

2023-01-19 18:04 UTC, cathiechen commented
> The commit message seems wrong.
> 
> The bug for this is https://bugs.webkit.org/show_bug.cgi?id=250836 instead of https://bugs.webkit.org/show_bug.cgi?id=157743 And the link should point to [w3c/csswg-drafts#3664](https://github.com/w3c/csswg-drafts/issues/3664) instead of https://bugs.webkit.org/show_bug.cgi?id=250836

Ah, indeed! Fixed, thanks a lot!

2023-01-23 05:54 UTC, Loirooriol reviewed
You edited the comment, but the commit was not updated. I suspect this won't do.

2023-01-23 06:04 UTC, Loirooriol requested changes
I guess [observe-disconnected-target-crash.html](https://github.com/WebKit/WebKit/blob/main/LayoutTests/resize-observer/observe-disconnected-target-crash.html) fails because you need something like https://github.com/WebKit/Webkit/commit/1a04d71fd0c83f072d19295920c6c9c1ac8cfadd

2023-01-23 09:02 UTC, cathiechen commented
> You edited the comment, but the commit was not updated. I suspect this won't do.

I will try to upload a new commit, see if it works:)

2023-01-23 09:03 UTC, cathiechen commented
> I guess [observe-disconnected-target-crash.html](https://github.com/WebKit/WebKit/blob/main/LayoutTests/resize-observer/observe-disconnected-target-crash.html) fails because you need something like [1a04d71](https://github.com/WebKit/WebKit/commit/1a04d71fd0c83f072d19295920c6c9c1ac8cfadd)

Thanks, I'll take a look

2023-01-23 17:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/91f24ff5be182c5595eec41e8e4718c94ae0db64. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8839

2023-02-01 10:56 UTC, closed without merging