Create compile-time CFString instead of passing C literal
WebKit/WebKit pull request #8906
Opened 2023-01-21 01:45 UTC by AtariDreams

Need the bug URL (OOPS!).

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

# Pull Request Template

## File a Bug

All changes should be associated with a bug. The WebKit project is currently using [Bugzilla](https://bugs.webkit.org) as our bug tracker. Note that multiple changes may be associated with a single bug.

## Provided Tooling

The WebKit Project strongly recommends contributors use [`Tools/Scripts/git-webkit`](https://github.com/WebKit/WebKit/tree/main/Tools/Scripts/git-webkit) to generate pull requests. See [Setup](https://github.com/WebKit/WebKit/wiki/Contributing#setup) and [Contributing Code](https://github.com/WebKit/WebKit/wiki/Contributing#contributing-code) for how to do this.

## Template

If a contributor wishes to file a pull request manually, the template is below. Manually-filed pull requests should contain their commit message as the pull request description, and their commit message should be formatted like the template below.

Additionally, the pull request should be mentioned on [Bugzilla](https://bugs.webkit.org), labels applied to the pull request matching the component and version of the [Bugzilla](https://bugs.webkit.org) associated with the pull request and the pull request assigned to its author.

<pre>
< bug title >
<a href="https://bugs.webkit.org/enter_bug.cgi">https://bugs.webkit.org/show_bug.cgi?id=#####</a>

Reviewed by NOBODY (OOPS!).

Explanation of why this fixes the bug (OOPS!).

* path/changed.ext:
(function):
(class.function):

</pre>

2023-01-21 01:46 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/119229d5773f74350df57fda9fa2c289a62217ad. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-21 03:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/1eff58fee1155367adac93af59e361e8fb6e01c1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-21 03:40 UTC, Constellation requested changes
Ah, please follow to https://github.com/WebKit/WebKit/wiki/Contributing / https://webkit.org/contributing-code/ carefully. Every patch needs bugzilla URL, and it needs to be stored in the commit message. See https://webkit.org/contributing-code/'s commit message section.

@JonWBedard will help for the commit procedure.

2023-01-21 16:46 UTC, AtariDreams commented
> Ah, please follow to https://github.com/WebKit/WebKit/wiki/Contributing / https://webkit.org/contributing-code/ carefully. Every patch needs bugzilla URL, and it needs to be stored in the commit message. See https://webkit.org/contributing-code/'s commit message section.
> 
> @JonWBedard will help for the commit procedure.

What if I don't have a bugzilla URL for this?

2023-01-21 17:15 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c5ab4e6f102ea8a0f248e54c62302514e048ce25. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-21 17:28 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4e1c084bf4ad386a395c6b5c6b59063b350e3827. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-21 17:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/da9520b7ed8add1818c9b2787ce30ca5132523cd. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-21 20:14 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3e4f371485f3afd1d85776920fb16aca188e9eb6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-23 21:09 UTC, AtariDreams commented
@Constellation Finished!

2023-01-26 19:06 UTC, AtariDreams commented
Thoughts @alanbaradlay? @achristensen07?

2023-01-28 17:43 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/421bc387f26fd9956bf9eb1d1d7962015bc3c5c4. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-28 18:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ef9ad62dd641db013a1e1df27da9b6dcdf0b5819. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-30 15:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0e75958905dbe0e714dd75cc5eeefdfb5dc5029f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8906

2023-01-30 15:50 UTC, closed without merging