[WebGPU] Add CompositorIntegration object
WebKit/WebKit pull request #8933
Opened 2023-01-22 00:47 UTC by litherum

#### c0636d45dc7b7532a3c6c122d68252cb802fef99
<pre>
[WebGPU] Add CompositorIntegration object
<a href="https://bugs.webkit.org/show_bug.cgi?id=250955">https://bugs.webkit.org/show_bug.cgi?id=250955</a>
rdar://104517402

Reviewed by NOBODY (OOPS!).

Right now, the data flow that WebGPU uses to interact with the compositor doesn&apos;t match either the
WebGPU spec&apos;s API nor WebGPU.h. Ideally, we&apos;d align them, for conceptual simplicity and to make
future hacking on this system easier.

The way this is supposed to work is the Surface gets created with a reference to a compositor
integration object. In the simple case, that&apos;s a CAMetalLayer, but in WebKit we don&apos;t use CAMetalLayer.
Instead, this patch creates an analogue for CAMetalLayer that contains the functionality to
integrate WebGPU with WebKit&apos;s compositor. Having this object means we can (eventually) get rid of
the custom APIs added to WebGPU.framework which cause leaky abstractions.

Just like CAMetalLayer, this object, named CompositorIntegration, is the owner of multiple IOSurfaces
used for render destinations. It has an API to recreate its IOSurfaces, which is mean to be called
whenever their attributes need to be changed. (For WebGPU, the creation of a swap chain indicates that
the IOSurfaces&apos; attributes need to be changed.) CompositorIntegration also has an IPC message receiver,
like almost all of the WebGPU types, and has one exposed message which returns the current IOSurfaces.
This is meant to be called just after they get recreated, so GPUSwapChain can get access to the
IOSurfaces, so GPUSwapChain can set them as the appropriate layer&apos;s contents.

There is no WGPU analog of CompositorIntegration; just like CAMetalLayer, it exists outside of
WebGPU.framework.

Other than the creation and retention of IOSurfaces, there&apos;s nothing really special about this object;
it&apos;s set up pretty much identically to every other WebGPU object.

* Source/WebCore/Modules/WebGPU/GPUCompositorIntegration.cpp: Added.
(WebCore::GPUCompositorIntegration::getRenderBuffers const):
* Source/WebCore/Modules/WebGPU/GPUCompositorIntegration.h: Added.
(WebCore::GPUCompositorIntegration::create):
(WebCore::GPUCompositorIntegration::backing):
(WebCore::GPUCompositorIntegration::backing const):
(WebCore::GPUCompositorIntegration::GPUCompositorIntegration):
* Source/WebCore/PAL/PAL.xcodeproj/project.pbxproj:
* Source/WebCore/PAL/pal/CMakeLists.txt:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUCompositorIntegrationImpl.cpp: Added.
(PAL::WebGPU::CompositorIntegrationImpl::CompositorIntegrationImpl):
(PAL::WebGPU::CompositorIntegrationImpl::getRenderBuffers):
(PAL::WebGPU::toCFNumber):
(PAL::WebGPU::CompositorIntegrationImpl::recreateIOSurfaces):
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUCompositorIntegrationImpl.h: Added.
* Source/WebCore/PAL/pal/graphics/WebGPU/WebGPUCompositorIntegration.h: Added.
* Source/WebCore/Sources.txt:
* Source/WebCore/WebCore.xcodeproj/project.pbxproj:
* Source/WebKit/CMakeLists.txt:
* Source/WebKit/DerivedSources-input.xcfilelist:
* Source/WebKit/DerivedSources-output.xcfilelist:
* Source/WebKit/DerivedSources.make:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteCompositorIntegration.cpp: Added.
(WebKit::RemoteCompositorIntegration::RemoteCompositorIntegration):
(WebKit::RemoteCompositorIntegration::stopListeningForIPC):
(WebKit::RemoteCompositorIntegration::getRenderBuffers):
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteCompositorIntegration.h: Added.
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteCompositorIntegration.messages.in: Added.
* Source/WebKit/Sources.txt:
* Source/WebKit/WebKit.xcodeproj/project.pbxproj:
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteCompositorIntegrationProxy.cpp: Added.
(WebKit::WebGPU::RemoteCompositorIntegrationProxy::RemoteCompositorIntegrationProxy):
(WebKit::WebGPU::RemoteCompositorIntegrationProxy::getRenderBuffers):
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteCompositorIntegrationProxy.h: Added.
</pre>

2023-01-22 00:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c0636d45dc7b7532a3c6c122d68252cb802fef99. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 00:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0789ab9bcb131464bc991e00ddf585059892d131. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 01:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/34dc4bf7245283b174405d045da8e9124805257c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 02:14 UTC, litherum commented
The iOS failures are due to https://github.com/WebKit/WebKit/pull/8932 not being merged yet.

2023-01-22 02:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/719720f305bb387f11c90e9bde581459b5cfcd4a. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 07:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a64faf79e44afcd133d03ce2c8d15f79c7280555. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 07:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/83f94ae911c69e23428f29cd0cdedd75fa7f7db0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 08:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e43885fd79a96c352f66a4c48fa26ebcf0920f9b. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 09:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a5c4814ac576dea92dfa4f3083b63098b0082519. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-22 20:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/61126ff2ea46b6b41a86edb230a638f60737247f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-23 00:45 UTC, litherum commented
Looks like the GTK failures are unrelated.

2023-01-23 23:50 UTC, mwyrzykowski commented
It seems unnecessary to have `Surface`, `SwapChain`, and `CompositorIntegration` when they are basically 3 objects serving a single purpose. Can't we have just one object? That is the direction the web API specification has moved with GPUCanvasContext.

2023-01-24 00:05 UTC, mwyrzykowski requested changes
I think this patch adds unnecessary complexity to what is already a complex system. Instead I think we should go the other way, remove Surface or SwapChain and have a single Canvas object which would be the analogue to CAMetalLayer

This is the direction the specification has already headed with GPUCanvasContext.

2023-01-24 08:07 UTC, mwyrzykowski commented
> So what do you think about keeping the CompositorIntegration object as describe in this patch, but then I also write a follow up patch to unify Surface and SwapChain as much as possible?

I completely agree we should stick to the WebGPU.h header, but I don't see why we can't exchange `SwapChainImpl::prepareForDisplay` with `SwapChainImpl::getRenderBuffers` (from CompositorIntegrator::getRenderBuffers).

Then most of the changes in this patch are not needed, we don't add any new functions to public APIs (similar to what `prepareForDisplay` already does) and we really only need a single object that maps similarly to CAMetalLayer but allows us to get and create the IOSurfaces so they can be set on CALayers.


GPUSwapChain is already an internal, non-API class. I don't understand the difference between GPUSwapChain and this new GPUCompositorIntegration. They seem to be achieving the same things except CompositorIntegration creates the IOSurfaces in PAL instead of WebGPU.framework and gets all the mach ports for the IOSurfaces at creation instead of every frame.

2023-01-24 09:53 UTC, litherum commented
I think there are 2 reasons:

1. SwapChain isn't web-exposed, but it is part of the API of WebGPU.h. I'd like to avoid adding new methods to types defined in WebGPU.h, because a) that indicates a leaky abstraction, and b) when we get further in project development, I plan to swap out WebGPU.framework for Dawn and wgpu myself to do some competitive analysis, and that's more difficult if we add our own methods to existing objects. I'd like to have all the compositor integration pieces in a single object, in a single place.
2. I think it's actually important that WebGPU.framework doesn't actually create any IOSurfaces itself, just because of separation of concerns. Just like Metal doesn't create IOSurfaces or Core Animation layers, I don't think WebGPU should be constructing its own render buffers for compositing. It should be flexible enough to render to any IOSurface it's given, rather than insisting that it creates them in exactly a single specific way. The reason for this is, eventually, I'd like to hook this up to the IOSurfaces vended by CG's image queue infrastructure, so we can get better frame pacing.

2023-01-24 11:04 UTC, litherum commented
Oh, I forgot to mention; I'm trying to design this so we will be able to implement browser features (like SVG filters, for example) using WebGPU. That's another place where WebGPU.framework probably won't be able to allocate its own IOSurfaces, and another situation where adding a new method to an object, even in our internal flow, will make someone's job harder later.

2023-01-24 18:37 UTC, mwyrzykowski commented
> 1. SwapChain isn't web-exposed, but it is part of the API of WebGPU.h. I'd like to avoid adding new methods to types defined in WebGPU.h
I'm not suggesting we add any new wgpu* functions and having custom C++ member functions doesn't interfere with the way we call the wgpu* functions right?

> 2. I think it's actually important that WebGPU.framework
That's a good idea, but why not move the IOSurface creation in this patch from:
`Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUCompositorIntegrationImpl.cpp`
to 
`Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSwapChainImpl.cpp`

I am not so strongly opposed to adding CompositorIntegration, it just seems to overlap with SwapChain a bit.

2023-01-28 00:45 UTC, litherum commented
Right, I see now what you're proposing.

The reason I didn't want to do that originally was because it would cause our own internal interfaces for PresentationContext to no longer match either the IDL spec or WebGPU.h. I think there's real value to sticking rigorously to the division-of-labor of objects in the spec/WebGPU.h when we have objects which represent objects there. PresentationContext represents what the IDL spec calls GPUCanvasContext and what WebGPU.h calls WGPUSurface & WGPUSwapChain. If we start adding methods to this object that don't exist in _either_ of these upstream places - even if the additions are in our internal interfaces - I worry that PresentationContext's meaning will become muddled and difficult to grok.

The solution that this patch attempts to implement is to put all our own custom stuff in our own object - an object which intentionally has no analogue in either the IDL spec nor WebGPU.h. That's sort of our own playground, where we can write whatever APIs we want, call them whenever we want, and we don't have to abide by the protocols, division-of-labor, and object lifetimes described by upstream.

However, on the other hand, I do understand the aversion to "yet one more object." I do think that https://commits.webkit.org/259508@main helped a lot, but you're right that an object has more lines of code, and more to read, than simply just adding in a single method on an object that already exists.

With that in mind, do you still think we should insert `getRenderBuffers()` into `PresentationContext`, or do you think we should put it in a new WebKit-specific object?

2023-01-28 18:50 UTC, mwyrzykowski approved these changes

2023-01-28 18:53 UTC, mwyrzykowski commented
> That's sort of our own playground, where we can write whatever APIs we want, call them whenever we want, and we don't have to abide by the protocols, division-of-labor, and object lifetimes described by upstream.

This is a great point, I don't think its a bad idea if our objects deviate a little bit, but we could use this new object to handle all of the IOSurface communication + present + interaction between webkit process waiting for the gpu process to finish a render logic

I think the new object should take on the present logic away from PresentationContext since GPUCanvasContext doesn't have present in the API, that could be done in a separate PR.

2023-01-28 21:59 UTC, litherum commented
> I think the new object should take on the present logic away from PresentationContext since GPUCanvasContext doesn't have present in the API, that could be done in a separate PR.

oh yeah, that's a great idea!

2023-01-30 09:48 UTC, tadeuzagallo approved these changes

2023-01-30 18:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/717f7d1ea3ee7552a9417b521fa88c47bd7b4b07. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-30 21:34 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/829f7b38317b9ff37685db80d3f90f68013ecaab. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8933

2023-01-30 22:48 UTC, webkit-commit-queue commented
Committed 259588@main (98794f128842): <https://commits.webkit.org/259588@main>

Reviewed commits have been landed. Closing PR #8933 and removing active labels.

2023-01-30 22:49 UTC, merged