[WebGPU] Fix assertion when loading textured-cube-shader-constants.html
WebKit/WebKit pull request #8935
Opened 2023-01-22 01:03 UTC by litherum

#### d04d93c14d6bed9b10bf4b8ee959aff48e288491
<pre>
[WebGPU] Fix assertion when loading textured-cube-shader-constants.html
<a href="https://bugs.webkit.org/show_bug.cgi?id=250956">https://bugs.webkit.org/show_bug.cgi?id=250956</a>
rdar://104517995

Reviewed by NOBODY (OOPS!).

The assertion says:

-[MTLDebugDevice newDepthStencilStateWithDescriptor:]:929: failed assertion `descriptor must not be nil.&apos;

...So let&apos;s make it not nil.

* Source/WebGPU/WebGPU/RenderPipeline.mm:
(WebGPU::Device::createRenderPipeline):
</pre>

2023-01-22 01:07 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d04d93c14d6bed9b10bf4b8ee959aff48e288491. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8935

2023-01-22 01:32 UTC, mwyrzykowski requested changes
We don’t need to unconditionally create the descriptor. Instead we should not create the depth stencil state when the descriptor is nil.

2023-01-22 02:23 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c8e0349248b258bd8d79949898cf95d10731082e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8935

2023-01-22 03:39 UTC, mwyrzykowski approved these changes

2023-01-22 04:12 UTC, webkit-commit-queue commented
@mwyrzykowski does not have reviewer permissions according to https://raw.githubusercontent.com/WebKit/WebKit/main/metadata/contributors.json.

If you do have reviewer permmissions, please ensure that your GitHub username is added to contributors.json.

Rejecting c8e0349248b258bd8d79949898cf95d10731082e from merge queue.

2023-01-23 07:35 UTC, tadeuzagallo approved these changes
Just a nit, but the commit message no longer reflects the contents of the change.

2023-01-23 09:59 UTC, litherum commented
Ok, will fix it up before landing.

2023-01-23 21:36 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/a85dbae001d9fc0348fe86b8851e9cbed8dc8201. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8935

2023-01-23 22:16 UTC, webkit-commit-queue commented
Committed 259241@main (e73104b88d62): <https://commits.webkit.org/259241@main>

Reviewed commits have been landed. Closing PR #8935 and removing active labels.

2023-01-23 22:16 UTC, merged