[WebGPU] Delete dead code: Surface::destroy() and SwapChain::destroy()
WebKit/WebKit pull request #8940
Opened 2023-01-22 06:38 UTC by litherum

#### 689a978b337de467960c7266970162358b143fe8
<pre>
[WebGPU] Delete dead code: Surface::destroy() and SwapChain::destroy()
<a href="https://bugs.webkit.org/show_bug.cgi?id=250962">https://bugs.webkit.org/show_bug.cgi?id=250962</a>
rdar://104522497

Reviewed by NOBODY (OOPS!).

In WebGPU, a few specific objects (Texture, Buffer, Device, and Query Set) have destroy() functions.
These are web-exposed methods that authors can call when they know they&apos;re done with an object and
don&apos;t want the GPU allocation to hang around until the next GC. These methods are not for internal
use, which means that Surface::destroy() and SwapChain::destroy() are dead code and can be deleted.

* Source/WebCore/Modules/WebGPU/GPUSurface.cpp:
(WebCore::GPUSurface::destroy): Deleted.
* Source/WebCore/Modules/WebGPU/GPUSurface.h:
* Source/WebCore/Modules/WebGPU/GPUSwapChain.cpp:
(WebCore::GPUSwapChain::destroy): Deleted.
* Source/WebCore/Modules/WebGPU/GPUSwapChain.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSurfaceImpl.cpp:
(PAL::WebGPU::SurfaceImpl::~SurfaceImpl):
(PAL::WebGPU::SurfaceImpl::destroy): Deleted.
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSurfaceImpl.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSwapChainImpl.cpp:
(PAL::WebGPU::SwapChainImpl::destroy): Deleted.
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSwapChainImpl.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/WebGPUSurface.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/WebGPUSwapChain.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSurface.cpp:
(WebKit::RemoteSurface::destroy): Deleted.
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSurface.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSurface.messages.in:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.cpp:
(WebKit::RemoteSwapChain::destroy): Deleted.
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.messages.in:
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSurfaceProxy.cpp:
(WebKit::WebGPU::RemoteSurfaceProxy::destroy): Deleted.
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSurfaceProxy.h:
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSwapChainProxy.cpp:
(WebKit::WebGPU::RemoteSwapChainProxy::destroy): Deleted.
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSwapChainProxy.h:
</pre>

2023-01-22 06:41 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/689a978b337de467960c7266970162358b143fe8. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8940

2023-01-22 07:12 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c686a58cdac9254e69b6ab9d128c7843815f3580. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8940

2023-01-22 07:22 UTC, mwyrzykowski requested changes
I use these destroy methods in https://github.com/WebKit/WebKit/pull/8856/files

How will Surface and SwapChain be removed from the object heap if we don't have such IPC methods?

2023-01-22 08:32 UTC, litherum commented
Marking as a draft until I can reconcile this with https://github.com/WebKit/WebKit/pull/8856

2023-01-27 08:55 UTC, litherum commented
Dup of https://github.com/WebKit/WebKit/pull/9206

2023-01-27 08:55 UTC, closed without merging