[WebGPU] Migrate from prepareForDisplay()/createSurfaceTexture() to present()/getCurrentTexture()
WebKit/WebKit pull request #8963
Opened 2023-01-23 04:39 UTC by litherum

#### e0c89eca9d05dbf8d1a22327088cbd0c9fb169e6
<pre>
[WebGPU] Migrate from prepareForDisplay()/createSurfaceTexture() to present()/getCurrentTexture()
<a href="https://bugs.webkit.org/show_bug.cgi?id=250995">https://bugs.webkit.org/show_bug.cgi?id=250995</a>
rdar://104541617

Reviewed by NOBODY (OOPS!).

The spec and WebGPU.h already have affordances for how to interact with the current renderbuffers in
the swap chain: present()/getCurrentTexture(). Previously, we had our own custom interaction methods,
but we should migrate to the standard ones for the purposes of understandability, hackability, and
simplicity.

* Source/WebCore/Modules/WebGPU/GPUDevice.cpp:
(WebCore::GPUDevice::createSurfaceTexture): Deleted.
* Source/WebCore/Modules/WebGPU/GPUDevice.h:
* Source/WebCore/Modules/WebGPU/GPUSwapChain.cpp:
(WebCore::GPUSwapChain::prepareForDisplay): Deleted.
* Source/WebCore/Modules/WebGPU/GPUSwapChain.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUDeviceImpl.cpp:
(PAL::WebGPU::DeviceImpl::createTexture):
(PAL::WebGPU::DeviceImpl::createSurfaceTexture): Deleted.
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUDeviceImpl.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSurfaceImpl.cpp:
(PAL::WebGPU::SurfaceImpl::drawingBuffer const): Deleted.
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSurfaceImpl.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSwapChainImpl.cpp:
(PAL::WebGPU::SwapChainImpl::prepareForDisplay): Deleted.
* Source/WebCore/PAL/pal/graphics/WebGPU/Impl/WebGPUSwapChainImpl.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/WebGPUDevice.h:
* Source/WebCore/PAL/pal/graphics/WebGPU/WebGPUSwapChain.h:
* Source/WebCore/html/HTMLCanvasElement.cpp:
(WebCore::HTMLCanvasElement::getContext):
(WebCore::HTMLCanvasElement::createContextWebGPU):
(WebCore::HTMLCanvasElement::getContextWebGPU):
* Source/WebCore/html/HTMLCanvasElement.h:
* Source/WebCore/html/canvas/GPUCanvasContext.cpp:
(WebCore::GPUCanvasContext::create):
(WebCore::getCanvasWidth):
(WebCore::getCanvasHeight):
(WebCore::GPUCanvasContext::GPUCanvasContext):
(WebCore::GPUCanvasContext::reshape):
(WebCore::GPUCanvasContext::configure):
(WebCore::GPUCanvasContext::unconfigure):
(WebCore::GPUCanvasContext::getCurrentTexture):
(WebCore::GPUCanvasContext::prepareForDisplay):
(WebCore::getCanvasSizeAsIntSize): Deleted.
(WebCore::GPUCanvasContext::createSwapChainIfNeeded): Deleted.
* Source/WebCore/html/canvas/GPUCanvasContext.h:
* Source/WebGPU/WebGPU/Instance.mm:
(wgpuGetProcAddress):
* Source/WebGPU/WebGPU/PresentationContextIOSurface.h:
(WebGPU::PresentationContextIOSurface::displayBuffer const): Deleted.
(WebGPU::PresentationContextIOSurface::drawingBuffer const): Deleted.
* Source/WebGPU/WebGPU/PresentationContextIOSurface.mm:
(WebGPU::PresentationContextIOSurface::PresentationContextIOSurface):
(WebGPU::PresentationContextIOSurface::configure):
(WebGPU::PresentationContextIOSurface::present):
(WebGPU::PresentationContextIOSurface::getCurrentTextureView):
(WebGPU::optionsFor32BitSurface): Deleted.
(WebGPU::createIOSurface): Deleted.
(WebGPU::createSurfaceFromDescriptor): Deleted.
(WebGPU::PresentationContextIOSurface::nextDrawable): Deleted.
(wgpuSurfaceCocoaCustomSurfaceGetDisplayBuffer): Deleted.
(wgpuSurfaceCocoaCustomSurfaceGetDrawingBuffer): Deleted.
* Source/WebGPU/WebGPU/Texture.h:
* Source/WebGPU/WebGPU/Texture.mm:
(WebGPU::Texture::usage):
(WebGPU::storageMode):
(WebGPU::Device::createTexture):
(WebGPU::Device::validateCreateIOSurfaceBackedTexture): Deleted.
(WebGPU::usage): Deleted.
* Source/WebGPU/WebGPU/WebGPUExt.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteDevice.cpp:
(WebKit::RemoteDevice::createSurfaceTexture): Deleted.
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteDevice.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteDevice.messages.in:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.cpp:
(WebKit::RemoteSwapChain::prepareForDisplay): Deleted.
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.h:
* Source/WebKit/GPUProcess/graphics/WebGPU/RemoteSwapChain.messages.in:
* Source/WebKit/WebKit.xcodeproj/xcshareddata/xcschemes/WebKit.xcscheme:
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteDeviceProxy.cpp:
(WebKit::WebGPU::RemoteDeviceProxy::createTexture):
(WebKit::WebGPU::RemoteDeviceProxy::createSurfaceTexture): Deleted.
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteDeviceProxy.h:
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSwapChainProxy.cpp:
(WebKit::WebGPU::RemoteSwapChainProxy::prepareForDisplay): Deleted.
* Source/WebKit/WebProcess/GPU/graphics/WebGPU/RemoteSwapChainProxy.h:
</pre>

2023-01-23 04:42 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e0c89eca9d05dbf8d1a22327088cbd0c9fb169e6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8963

2023-02-02 23:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/60b449017b0ae3f49b4f72afb02670d8d817ef3e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8963

2023-02-03 00:44 UTC, litherum commented
This patch is ready to go as soon as https://github.com/WebKit/WebKit/pull/8936 is landed.

2023-02-04 08:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2bb227485dc287a23fdf893dd1ba4b4705e92798. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8963

2023-02-04 20:10 UTC, mwyrzykowski approved these changes

2023-02-04 20:35 UTC, mwyrzykowski requested changes
Seems to cause a regression on webgpu/instanced-textured-cube.html

2023-02-04 20:51 UTC, litherum commented
This depends on https://github.com/WebKit/WebKit/pull/8936, it will work if you apply both (at least according to my testing)

2023-02-04 20:51 UTC, mwyrzykowski approved these changes

2023-02-05 08:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b1a1ce0fd1f31b1c984c0cbcbce6480bc562da08. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/8963

2023-02-06 09:40 UTC, tadeuzagallo approved these changes

2023-02-06 10:07 UTC, webkit-commit-queue commented
Committed 259884@main (501cc5c18513): <https://commits.webkit.org/259884@main>

Reviewed commits have been landed. Closing PR #8963 and removing active labels.

2023-02-06 10:07 UTC, merged