[GTK] Fix cmake build when ENABLE_MHTML flag is off
WebKit/WebKit pull request #9243
Opened 2023-01-27 18:52 UTC by kiranpradeep

#### 62443ea5c3eaec46a8f0446e070effeef9d92655
<pre>
[GTK] Fix cmake build when ENABLE_MHTML flag is off
<a href="https://bugs.webkit.org/show_bug.cgi?id=146905">https://bugs.webkit.org/show_bug.cgi?id=146905</a>

Unreviewed test gardening

ENABLE(MHTML) Preprocessor guards are added to WebKitWebView.cpp.
This approach  is copied from WKPageGetContentsAsMHTMLData() method
in file WKPage.cpp (path: UIProcess/API/C)

* Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:
(webkit_web_view_save):
(webkit_web_view_save_to_file):
</pre>

2023-01-27 18:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/62443ea5c3eaec46a8f0446e070effeef9d92655. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9243

2023-01-27 18:55 UTC, mcatanzaro requested changes
Hi, you need to make sure the callback always gets called. What you have now breaks if ENABLE(MHTML) is disabled: the call will never finish.

P.S. This is not a public build option and disabling it is not supported, but whatever, adding two guards is hardly a big deal.

2023-01-27 19:38 UTC, kiranpradeep commented
@mcatanzaro oh private flags - my bad. I was using cmake-gui which did not differentiate what was private flags from public ones. I was trying to build gtk port with just 3 options (Webkit, Webcore, JavascriptCore) enabled (I disabled everything else in cmake-gui). And hit this issue.

I could not test this with minibrowser. So followed what was already in WKPage.cpp line [2673](https://github.com/WebKit/WebKit/blob/0c8fb49c7a40115abe543963829eb8268b96d048/Source/WebKit/UIProcess/API/C/WKPage.cpp#L2673). I am abandoing this PR as it is not expected to be used by public,

2023-01-27 19:38 UTC, closed without merging

2023-01-27 20:58 UTC, mcatanzaro commented
I think cmake-gui should distinguish between ADVANCED options (for developers/experts) vs. user-facing options?

You'll have a real tough time with _everything_ disabled. :)

2023-01-27 21:00 UTC, mcatanzaro commented
> I could not test this with minibrowser. So followed what was already in WKPage.cpp line [2673](https://github.com/WebKit/WebKit/blob/0c8fb49c7a40115abe543963829eb8268b96d048/Source/WebKit/UIProcess/API/C/WKPage.cpp#L2673). I am abandoing this PR as it is not expected to be used by public,

You actually found a bug there! The callback should always be executed. Feel free to file a bug report if you want.

2023-01-30 13:40 UTC, kiranpradeep commented
> You actually found a bug there! The callback should always be executed. Feel free to file a bug report if you want.

@mcatanzaro Raised [251353](https://bugs.webkit.org/show_bug.cgi?id=251353). But it feels incomplete info as I could not find info on what should values of WKDataRef/WKErrorRef when callback is invoked (with MHTML off).