Add WebKit SPI to specify User Agent details for preconnect
WebKit/WebKit pull request #934
Opened 2022-05-23 20:11 UTC by pvollan

#### ea195112c2d2e72e6c1bcac383532a94c9d1dcd8
<pre>
Add WebKit SPI to specify User Agent details for preconnect
<a href="https://bugs.webkit.org/show_bug.cgi?id=240818">https://bugs.webkit.org/show_bug.cgi?id=240818</a>

Reviewed by NOBODY (OOPS!).

Add WebKit SPI to specify application name and whether a desktop user agent should be used in the preconnect.
This is in preparation of fixing the issue where we are always preconnecting with the incorrect user agent on
iPad. This causes the preconnected socket to be unused, and is a page load performance issue.

* Source/WebKit/UIProcess/API/Cocoa/WKWebView.mm:
(-[WKWebView _setUserAgentDetailsForPreconnect:desktopUserAgent:]):
* Source/WebKit/UIProcess/API/Cocoa/WKWebViewPrivate.h:
(-[WKWebView _dataTaskWithRequest:completionHandler:]): Deleted.
* Source/WebKit/UIProcess/Cocoa/WebPageProxyCocoa.mm:
(WebKit::WebPageProxy::setUserAgentDetailsForPreconnect):
* Source/WebKit/UIProcess/WebPageProxy.cpp:
(WebKit::WebPageProxy::preconnectTo):
* Source/WebKit/UIProcess/WebPageProxy.h:
</pre>

2022-05-23 20:23 UTC, cdumez requested changes
This looks very hackish and I doubt this is the right way forward for the following reasons:
- User agents are normally per URL (not global)
- Preconnecting should in theory have nothing to do with user agents. Connecting a a server happens before we send the request (which contains the user agent). Therefore, It shouldn't matter what user agent we use for the pre-connect since it shouldn't be used by the pre-connect. Sounds like the issue may be at CFNetwork level?
- Why is the user agent set on the page incorrect? Why would the one used for preconnect be different than the one set on the page?

It looks like this is about desktop mode on iOS. I don't remember all the details about desk mode mode but if most loads use a desktop user agent, then it sounds like the default user agent should be the desktop one. If this choosing desktop mode on not is done on a per URL basis (which I suspect it is), then having a global "preconnect" user agent doesn't make much sense either.

2022-05-24 03:20 UTC, bnham commented
There is a long-standing [CFNetwork issue](rdar://59462497) that causes preconnects via an HTTPS proxy to only be used if the User-Agent of the preconnect request matches the UA of the eventual HTTP request. It doesn't make any sense, but that's just the way it is. Maybe we can see if we can get the issue fixed at that layer?

On the other hand, we already have a previous [hacky commit](https://github.com/WebKit/WebKit/commit/5d5203e4a3226babe5e14f5f54dc2600ad322425) in WebKit to address this issue on iPhone, so extending the hack wouldn't be unprecedented.

I think the UA on iPad is only chosen in the navigation delegate (since it can be controlled by per-origin settings). So it's true this hack cannot be 100% effective. But I think this is trying to address the issue that there is some default UA that is chosen as a fallback and I think that might not be matching in some cases. Is that what this patch is trying to address?

2022-05-24 14:38 UTC, pvollan commented
> This looks very hackish and I doubt this is the right way forward for the following reasons:
> 
> * User agents are normally per URL (not global)
> * Preconnecting should in theory have nothing to do with user agents. Connecting a a server happens before we send the request (which contains the user agent). Therefore, It shouldn't matter what user agent we use for the pre-connect since it shouldn't be used by the pre-connect. Sounds like the issue may be at CFNetwork level?
> * Why is the user agent set on the page incorrect? Why would the one used for preconnect be different than the one set on the page?
> 
> It looks like this is about desktop mode on iOS. I don't remember all the details about desk mode mode but if most loads use a desktop user agent, then it sounds like the default user agent should be the desktop one. If this choosing desktop mode on not is done on a per URL basis (which I suspect it is), then having a global "preconnect" user agent doesn't make much sense either.

Yes, these are good points. As you point out, this is an issue at the CFNetwork level, where the pre-connected socket is not reused, because the user agent on the request does not match the user agent on the request for the actual load. This happens because we pre-connect before we get the required user agent information from the client, and the preconnect will use the standard user agent, which is the mobile user agent on iOS. The user agent information is received when we get the policy decision from the client. This is only an issue on iPad, when we preconnect with the standard mobile user agent, but then use the desktop user agent for the actual load. 

I think our current plan is to pass the required user agent information in the default Web page policies, which will remove the need for new SPI. This will likely be done in a new PR.

Thanks for reviewing!

2022-05-24 14:46 UTC, pvollan commented
> There is a long-standing CFNetwork issue that causes preconnects via an HTTPS proxy to only be used if the User-Agent of the preconnect request matches the UA of the eventual HTTP request. It doesn't make any sense, but that's just the way it is. Maybe we can see if we can get the issue fixed at that layer?
> 

Yes, that is a good point, I will follow up on that.

> On the other hand, we already have a previous [hacky commit](https://github.com/WebKit/WebKit/commit/5d5203e4a3226babe5e14f5f54dc2600ad322425) in WebKit to address this issue on iPhone, so extending the hack wouldn't be unprecedented.
> 
> I think the UA on iPad is only chosen in the navigation delegate (since it can be controlled by per-origin settings). So it's true that something like this cannot be 100% effective. But I think this is trying to address the issue that there is some default UA that is chosen as a fallback and I think that might not be matching in some cases (or maybe all cases on the iPad). Is that what this patch is trying to address?

Yes, exactly. On iPad, the preconnect request will always have the standard mobile user agent, while the actual load is (normally) done with the desktop class user agent. As you say, this prevents the preconnected sockets from being used in the load.

The intention behind this SPI is to call it from the client right before loadRequest is called. At this time the URL is known, and we can get the correct user agent information on the client side, including exceptions for specific URLs. This should in theory make the preconnect user agent always match the user agent for the actual load, also when e.g. the user is requesting the desktop version on an iPhone.   

Thanks for reviewing!

2022-05-24 14:53 UTC, pvollan commented
This patch should not set the custom user agent, but rather store the preconnect user agent information separately, and only use it in the preconnect.

2022-07-01 21:45 UTC, closed without merging