[GStreamer][WebRTC] Implement GstMappedRtpBuffer
WebKit/WebKit pull request #9373
Opened 2023-01-31 10:21 UTC by philn

#### 7878d72b0fd7c5c84e185733ffc2d6ed65bccc02
<pre>
[GStreamer][WebRTC] Implement GstMappedRtpBuffer
<a href="https://bugs.webkit.org/show_bug.cgi?id=251428">https://bugs.webkit.org/show_bug.cgi?id=251428</a>

Reviewed by Xabier Rodriguez-Calvar.

With this new RAII object for mapping RTP buffers we don&apos;t need to manually unmap anymore.

Canonical link: <a href="https://commits.webkit.org/261074@main">https://commits.webkit.org/261074@main</a>
</pre>

2023-01-31 10:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/793f93711ceaf90df9b72ad246888e0734f55eac. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9373

2023-01-31 11:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/23e2bb823d1dcd2b4bb9bd7af15df86dcf085782. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9373

2023-02-01 08:55 UTC, calvaris requested changes
If this implementation is the same as the GstMappedBuffer with the only difference of map/unmap functions, I think we should do some templating here.

2023-02-01 09:16 UTC, philn commented
> If this implementation is the same as the `GstMappedBuffer` with the only difference of map/unmap functions, I think we should do some templating here and optionally pass the map/unmap functions. Then, if you want, you can create the `GstRTPMappedBuffer` with a `using`.

The public API differs though.

2023-02-02 07:39 UTC, calvaris commented
In what, other than the type?

2023-02-02 08:31 UTC, philn commented
> In what, other than the type?

GstMappedBuffer has `::size()` and `::createVector()`

2023-02-03 01:23 UTC, shivamidow commented on Source/WebCore/Modules/mediastream/gstreamer/GStreamerWebRTCUtils.h
> +        if (m_isValid) {
* Unofficial review *
Nit. We may want an early return instead.

2023-02-03 07:09 UTC, calvaris commented
> GstMappedBuffer has `::size()` and `::createVector()`

I still think it is worth trying. It does not hurt to have them. You need four template parameters, but nothing outstanding. If you want, you can avoid using default parameters and create a GstBufferBaseMappedBuffer with the four template parameters (GstBuffer, GstMapInfo (which also seems to differ for RTP), map and unmap). Then you create GstBufferMap with a `using`

2023-02-03 09:21 UTC, philn commented
> > GstMappedBuffer has `::size()` and `::createVector()`
> 
> I still think it is worth trying. It does not hurt to have them. You need four template parameters, but nothing outstanding. If you want, you can avoid using default parameters and create a GstBufferBaseMappedBuffer with the four template parameters (GstBuffer, GstMapInfo (which also seems to differ for RTP), map and unmap). Then you create GstBufferMap with a `using`.
> 
> We would be reducing a lot the code duplication.

Yes and I tried this already :) `::createVector()`  doesn't make much sense for RTP buffers though.

2023-02-07 07:11 UTC, calvaris commented
> Yes and I tried this already :) `::createVector()` doesn't make much sense for RTP buffers though.

You don't need to use all the API. I am very reluctant to create something that is almost equal in code to something that can change a couple of types and functions. That's what templates are for, right?

2023-02-08 07:29 UTC, calvaris commented
For me, one use is enough and templating is the way to go :relaxed:

2023-03-02 12:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0ffe5ca34ed2ec179e12e4b543e5ba7ac0183860. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9373

2023-03-02 12:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/0ffe5ca34ed2ec179e12e4b543e5ba7ac0183860. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9373

2023-03-02 16:42 UTC, calvaris approved these changes
B E A U T I F U L !

2023-03-02 17:04 UTC, merged

2023-03-02 17:04 UTC, webkit-commit-queue commented
Committed 261074@main (7878d72b0fd7): <https://commits.webkit.org/261074@main>

Reviewed commits have been landed. Closing PR #9373 and removing active labels.