Use CheckedPtr for m_preloads in CachedResourceLoader
WebKit/WebKit pull request #9386
Opened 2023-01-31 17:35 UTC by rniwa

#### b572acb5aaff48a236c2cbb19eeaf7ec79b72b21
<pre>
Use CheckedPtr for m_preloads in CachedResourceLoader
<a href="https://bugs.webkit.org/show_bug.cgi?id=251440">https://bugs.webkit.org/show_bug.cgi?id=251440</a>

Reviewed by NOBODY (OOPS!).

Made it possible to make CheckedPtr for CachedResource and deployed it in CachedResourceLoader::m_preloads.

* Source/WebCore/loader/cache/CachedResource.h:
(WebCore::CachedResource::isLinkPreload const):
(WebCore::CachedResource::isLinkPreload): Made this accessor function const.
* Source/WebCore/loader/cache/CachedResourceLoader.cpp:
(WebCore::CachedResourceLoader::preload):
(WebCore::CachedResourceLoader::clearPreloads):
* Source/WebCore/loader/cache/CachedResourceLoader.h:
</pre>

2023-01-31 17:37 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b572acb5aaff48a236c2cbb19eeaf7ec79b72b21. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9386

2023-01-31 21:55 UTC, achristensen07 approved these changes

2023-01-31 21:56 UTC, achristensen07 requested changes
Test failures look related

2023-02-01 00:09 UTC, rniwa commented
> Test failures look related

Indeed...

2023-02-02 05:24 UTC, closed without merging