REGRESSION({259017,259250}@main): [JSC] fix ENABLE(WEBASSEMBLY)
WebKit/WebKit pull request #9518
Opened 2023-02-02 14:53 UTC by ThomasDevoogdt

https://bugs.webkit.org/show_bug.cgi?id=251357

Reviewed by NOBODY (OOPS!).

FTL: macros can't hold any #defines, so add a new set:

    FOR_EACH_ABSTRACT_FIELD_WASM

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>

2023-02-02 14:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/d5a211f367413c0d0cf740b898865e1d06968016. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9518

2023-02-02 20:14 UTC, Constellation commented
We are not supporting environments which does not support WebAssembly while supporting FTL on x64 / ARM64.
If you would like to disable WebAssembly, set environment variable `JSC_useWebassembly=0` instead.

2023-02-02 21:38 UTC, Constellation commented
CC @JonWBedard

2023-02-08 18:44 UTC, Constellation requested changes
r- based on my comment.

2023-02-24 09:42 UTC, ThomasDevoogdt commented
> We are not supporting environments which do not support WebAssembly while supporting FTL on x64 / ARM64. If you would like to disable WebAssembly, set environment variable `JSC_useWebassembly=0` instead.

Not sure what exactly needs to be changed. But in the meantime, I found out about the `ENABLE_JIT` flag which sets some dependencies right. Controlling the individual `ENABLE_WEBASSEMBLY{_B3JIT}` flags almost always causes a bunch of compile errors. And I do not per se need JIT, so just disable it all. To you to decide if this issue can be closed, or if some commit change is required, feel free to push to this PR.

2023-03-16 17:52 UTC, closed without merging