Drop tag arguments early on backends than don't use them
WebKit/WebKit pull request #9532
Opened 2023-02-02 17:54 UTC by aoikonomopoulos

#### 6487354110be2bab4265b4ab3c88b65851ec6ef2
<pre>
Drop tag arguments early on backends than don&apos;t use them
<a href="https://bugs.webkit.org/show_bug.cgi?id=251603">https://bugs.webkit.org/show_bug.cgi?id=251603</a>

Reviewed by NOBODY (OOPS!).

The extra arguments to call/jmp for pointer tagging are only used on
arm64e. However, on all risc platforms, riscLowerMalformedImmediates
will emit extra code to load the values in a register.

Instead, drop the extra tag arguments early so that none of the other
passes can get confused.

* Source/JavaScriptCore/offlineasm/arm.rb:
* Source/JavaScriptCore/offlineasm/arm64.rb:
* Source/JavaScriptCore/offlineasm/mips.rb:
* Source/JavaScriptCore/offlineasm/risc.rb:
* Source/JavaScriptCore/offlineasm/riscv64.rb:
</pre>

2023-02-02 17:54 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6487354110be2bab4265b4ab3c88b65851ec6ef2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9532

2023-02-02 23:10 UTC, Constellation requested changes
I think it is breaking ARM64E since ARM64E getModifiedListARM64E is calling getModifiedListARM64.

2023-02-06 10:33 UTC, aoikonomopoulos commented
> I think it is breaking ARM64E since ARM64E getModifiedListARM64E is calling getModifiedListARM64.

Ah, missed that, thanks! Pushed an updated version.

2023-02-06 13:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e0dab755559f09cabfeda8b080e128ddd9ffdfcc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9532

2023-02-06 13:54 UTC, aoikonomopoulos commented
Fixed the changed files in the commit message.

2023-02-10 08:42 UTC, aoikonomopoulos commented
Ping. Is this OK on arm64e now?

2023-02-16 01:07 UTC, Constellation approved these changes
r=me

2023-02-16 11:37 UTC, webkit-commit-queue commented
Committed 260359@main (0faaa00680c0): <https://commits.webkit.org/260359@main>

Reviewed commits have been landed. Closing PR #9532 and removing active labels.

2023-02-16 11:37 UTC, merged