[GTK][WPE] Remove webkit_web_view_new_with_related_view from new API too
WebKit/WebKit pull request #9593
Opened 2023-02-03 10:57 UTC by carlosgcampos

#### f3d3a993235516e09804bfab23293b8626d94ecb
<pre>
[GTK][WPE] Remove webkit_web_view_new_with_related_view from new API too
<a href="https://bugs.webkit.org/show_bug.cgi?id=251426">https://bugs.webkit.org/show_bug.cgi?id=251426</a>

Reviewed by NOBODY (OOPS!).

It&apos;s confusing because it&apos;s not equivalent to just calling
g_object_new() with releated-view property set.

* Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp:
(webkit_web_view_class_init):
* Source/WebKit/UIProcess/API/glib/WebKitWebView.h.in:
* Source/WebKit/UIProcess/API/gtk/WebKitWebViewGtk.cpp:
* Source/WebKit/UIProcess/API/wpe/WebKitWebViewWPE.cpp:
* Tools/TestWebKitAPI/Tests/WebKitGtk/TestPrinting.cpp:
* Tools/TestWebKitAPI/glib/WebKitGLib/TestMain.h:
(Test::createWebView):
</pre>

2023-02-03 10:58 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/f3d3a993235516e09804bfab23293b8626d94ecb. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9593

2023-02-03 12:16 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4bcc3f4712e72b7dfe6c05ad5f3a3f4ca3eced53. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9593

2023-02-03 14:39 UTC, mcatanzaro requested changes
OK, you convinced me this is a good idea, but I'm still going to request changes here:

 * Add a critical in `constructed` if the object is constructed with `related-view` and also `web-context` or `network-session`
 * What about `is-controlled-by-automation`?
 * Please update the migration guide; it currently says this constructor is the only one that was not removed

2023-02-03 21:32 UTC, aperezdc commented
Removing the function from the new API looks good to me, and I think we can land this with @mcatanzaro's suggestions applied 👌🏼

2023-02-04 07:14 UTC, carlosgcampos commented
I think a warning is enough, it's not a fatal error and we just ignore the passed values.

2023-02-04 11:43 UTC, carlosgcampos commented
So, if web-context/network-session were passed with a `NULL` value, or is-ephemeral/is-controlled-by-automation with `FALSE`, how do I know in constructor whether it was provided to g_object_new or not?

2023-02-04 14:59 UTC, mcatanzaro commented
> I think a warning is enough, it's not a fatal error and we just ignore the passed values.

It is a programmer error though. g_critical() is the appropriate warning level for programmer errors.

> So, if web-context/network-session were passed with a NULL value, or is-ephemeral/is-controlled-by-automation with FALSE, how do I know in constructor whether it was provided to g_object_new or not?

Uh, you would have to override `constructor` and do it there rather than in `constructed`, which is admittedly probably not worth the effort. I'll let you decide whether to attempt this or not. You can still warn if they're set to non-default values though!

2023-02-04 15:09 UTC, carlosgcampos commented
I think you always get all construct properties in constructor, with the value set to the default one already. So, still you don't know if it was et explicitly or not. I don't think it's worth the effort to be honest.

2023-02-04 18:09 UTC, mcatanzaro commented
OK.

You can still warn if they're set to non-default values though! That's easy to check, and you know it's a mistake for sure.

2023-02-06 09:04 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/4cdee52097171b9249ad4c39c37360af36672f70. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9593

2023-02-06 09:37 UTC, webkit-commit-queue commented
Commit message contains (OOPS!) and no reviewer found, blocking PR #9593

2023-02-06 10:26 UTC, aperezdc approved these changes

2023-02-06 10:32 UTC, webkit-commit-queue commented
Committed 259885@main (57a26786ef09): <https://commits.webkit.org/259885@main>

Reviewed commits have been landed. Closing PR #9593 and removing active labels.

2023-02-06 10:32 UTC, merged