Simplify bitwise operations
WebKit/WebKit pull request #9611
Opened 2023-02-03 19:05 UTC by AtariDreams

#### ad6823ef3c359837ec54219861dd069089330f0c
<pre>
Simplify bitwise operations
Need the bug URL (OOPS!).

Reviewed by NOBODY (OOPS!).

This will ensure the compiler does all the bitwise operations via one
instruction.

*Source\JavaScriptCore\dfg\DFGBackwardsPropagationPhase.cpp:
*Source\WTF\wtf\WordLock.cpp:
*Tools\WebKitTestRunner\ios\HIDEventGenerator.mm:
</pre>

2023-02-03 19:06 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ad6823ef3c359837ec54219861dd069089330f0c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9611

2023-02-03 19:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6d02adcae306876dfc5b046710e693d9b1a163e0. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9611

2023-02-03 20:11 UTC, fujii commented
What compiler are you using?  You should use a better optimizing compiler.
https://godbolt.org/z/xYjqa4se4

2023-02-03 22:00 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b6b2e82ef32d16a51127ff07ddcb0a13a4b54ba2. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9611

2023-02-04 03:33 UTC, Constellation requested changes
The compiler does these changes. So readability etc. is more important here.

2023-02-04 17:07 UTC, closed without merging