Remove setWithoutBarrier
WebKit/WebKit pull request #9696
Opened 2023-02-06 17:36 UTC by AtariDreams

#### 51c95ed707804ecc7a44189e658c9c114b524263
<pre>
Remove setWithoutBarrier
<a href="https://bugs.webkit.org/show_bug.cgi?id=236278">https://bugs.webkit.org/show_bug.cgi?id=236278</a>

Reviewed by NOBODY (OOPS!).

The parsing bug has been fixed.

*Source\JavaScriptCore\runtime\AuxiliaryBarrier.h:
*Source\JavaScriptCore\runtime\CagedBarrierPtr.h:
*Source\JavaScriptCore\runtime\JSArrayBufferView.cpp:
*Source\WebCore\bindings\js\JSValueInWrappedObject.h:
</pre>
https://github.com/WebKit/WebKit/commit/51c95ed707804ecc7a44189e658c9c114b524263

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/106368 "Passed style check") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios](https://ews-build.webkit.org/#/builders/77/builds/15416 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 wpe](https://ews-build.webkit.org/#/builders/8/builds/115561 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated wpe dependencies; Running compile-webkit") | [💥 🛠 🧪 win](https://ews-build.webkit.org/#/builders/10/builds/175661 "An unexpected error occured. Recent messages:Pull request contains relevant changes; Failed to print configuration") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/110276 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 ios-sim](https://ews-build.webkit.org/#/builders/76/builds/16896 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/85/builds/6638 "Build is in progress. Recent messages:Pull request contains relevant changes; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; killing old processes; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/98586 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; 'python3 Tools/Scripts/git-webkit ...'; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/112133 "Passed tests") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/76/builds/16896 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/36/builds/98586 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; 'python3 Tools/Scripts/git-webkit ...'; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-ios](https://ews-build.webkit.org/#/builders/76/builds/16896 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/36/builds/98586 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; 'python3 Tools/Scripts/git-webkit ...'; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/38/builds/95377 "Built successfully") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/82/builds/9168 "Built successfully") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/85/builds/6638 "Build is in progress. Recent messages:Pull request contains relevant changes; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; killing old processes; Running compile-webkit") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/46/builds/30612 "Build is in progress. Recent messages:Pull request contains relevant changes; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; killing old processes; Running jscore-test") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch](https://ews-build.webkit.org/#/builders/80/builds/14797 "Build is in progress. Recent messages:Running worker_preparation") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [✅ 🛠 jsc-mips](https://ews-build.webkit.org/#/builders/37/builds/104116 "Built successfully") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/10725 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Running compile-webkit") | | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 jsc-mips-tests](https://ews-build.webkit.org/#/builders/45/builds/25800 "Build is in progress. Recent messages:Pull request contains relevant changes; Cleaned up git repository; Skip [...]

2023-02-06 17:38 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/51c95ed707804ecc7a44189e658c9c114b524263. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9696

2023-02-06 18:01 UTC, Constellation requested changes
setWithoutWriteBarrier is fundamental important method we cannot remove.

2023-02-06 18:04 UTC, AtariDreams commented
Did I misunderstand the FIXME comment then?

2023-02-06 18:06 UTC, AtariDreams commented
> setWithoutWriteBarrier

This is setWithoutBarrier though

2023-02-07 02:49 UTC, rkirsling commented
I think the issue here is that the WebCore changes are likely justified, but the JSC changes appear to be unrelated. The lines being removed in JSArrayBufferView.cpp aren't dead or extraneous code—without them, every typed array constructor will behave, since m_vector will go uninitialized.

2023-02-07 14:33 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/3a6828c598dd1da2ace61624fff37a1ae20d9919. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9696

2023-02-07 15:29 UTC, AtariDreams commented
@Constellation

2023-02-07 18:21 UTC, Constellation approved these changes

2023-02-07 21:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e082b2d46a89f735c05f7ed21276531b5a3d47ae. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9696

2023-02-08 15:27 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/8124366c4d96ad05514b2b0d2d72cbc5cff02041. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9696

2023-02-09 15:22 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/62ac9b0a763b4eefe754f64b222c31cf1af2af7f. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9696

2023-02-09 19:24 UTC, webkit-commit-queue commented
Committed 260073@main (4d3456e83828): <https://commits.webkit.org/260073@main>

Reviewed commits have been landed. Closing PR #9696 and removing active labels.

2023-02-09 19:24 UTC, merged