[JSC] Fix wasm tests on MIPS
WebKit/WebKit pull request #9814
Opened 2023-02-08 15:52 UTC by mikhailramalho

#### 6767f1e0f7fc2e9536ea44755c07761a931154ee
<pre>
[JSC] Fix wasm tests on MIPS
<a href="https://bugs.webkit.org/show_bug.cgi?id=251917">https://bugs.webkit.org/show_bug.cgi?id=251917</a>

Unreviewed test gardening. Prevent MIPS failure by checking if wasm is available.

* JSTests/wasm/stress/throw-from-wasm-catch-in-baseline-JIT.js:
(vm.isWasmSupported):
(foo): Deleted.
* JSTests/wasm/stress/timer-exception.js:
(async let): Deleted.
</pre>

2023-02-08 15:53 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/6767f1e0f7fc2e9536ea44755c07761a931154ee. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9814

2023-02-08 18:11 UTC, Constellation requested changes
This is `JSTests/wasm`. If the engine is not supporting wasm, then it should not run any of these tests.

2023-02-08 18:49 UTC, mikhailramalho commented
> This is `JSTests/wasm`. If the engine is not supporting wasm, then it should not run any of these tests.

By adding the check, we don't have to go back and re-enable the test when we port wasm to mips.

2023-02-08 18:52 UTC, mikhailramalho commented
either that or we have to also remove/prevent the following test from running (they also include the `$vm.isWasmSupported()` check):
```
JSTests/stress/sampling-profiler-wasm.js
JSTests/stress/wasm-error-message-cross-threads.js
JSTests/stress/sampling-profiler-wasm-name-section.js
JSTests/stress/wasm-loop-consistency.js
JSTests/microbenchmarks/interpreter-wasm.js
```

2023-02-08 18:59 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c481d03721b2635e808e6b2f24ac7d47bdcb06b3. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9814

2023-02-08 19:02 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/536f9d10fefa98de4f0fe54b42f072ffe23b5729. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9814

2023-02-08 19:35 UTC, jjgriego commented
> This is JSTests/wasm. If the engine is not supporting wasm, then it should not run any of these tests.

It looks to me like these tests are running despite mips not being `$isWasmPlatform` because there's a `run<...>` call in the `//@` line which gets run unconditionally by `parseRunCommands` for wasm/stress--maybe we should exclude `wasm.yaml` entirely from the list of tests when `!$isWasmPlatform` ?

2023-02-08 22:04 UTC, Constellation commented
> > This is JSTests/wasm. If the engine is not supporting wasm, then it should not run any of these tests.
> 
> 
> 
> It looks to me like these tests are running despite mips not being `$isWasmPlatform` because there's a `run<...>` call in the `//@` line which gets run unconditionally by `parseRunCommands` for wasm/stress--maybe we should exclude `wasm.yaml` entirely from the list of tests when `!$isWasmPlatform` ?

Yes

2023-02-09 10:02 UTC, aoikonomopoulos commented
FWIW I think we may want to change the `//@ run*` commands in `wasm/**.js` files to use the `run*Wasm*` commands defined in #9690 for consistency (so that the options are automatically kept in sync), in which case this would also get fixed, since those would return if `!$isWasmPlatform`.

2023-02-14 17:18 UTC, mikhailramalho commented
Thanks for the feedback folks, I close this PR as @aoikonomopoulos' patch seems like a better solution.

2023-02-14 17:18 UTC, closed without merging

2023-03-01 21:38 UTC, aoikonomopoulos commented
@Constellation What do you think about https://github.com/WebKit/WebKit/pull/9690 as (part of) a proper fix for this? I can change the run commands to use `run*Wasm*` as described above if that gets accepted.