Make mainFrame() return an AbstractFrame
WebKit/WebKit pull request #9958
Opened 2023-02-11 00:36 UTC by chirags27

#### 2559a76a62997ddb96ef6a37f8fc190946fbedff
<pre>
Make mainFrame() return an AbstractFrame
Include a Radar link (OOPS!).

Reviewed by NOBODY (OOPS!).

Work in progress...

* Source/WebCore/accessibility/AccessibilityObject.cpp:
(WebCore::AccessibilityObject::mainFrame const):
* Source/WebCore/contentextensions/ContentExtensionsBackend.cpp:
(WebCore::ContentExtensions::ContentExtensionsBackend::processContentRuleListsForLoad):
* Source/WebCore/css/query/MediaQueryFeatures.cpp:
(WebCore::MQ::Features::color):
(WebCore::MQ::Features::colorGamut):
(WebCore::MQ::Features::deviceAspectRatio):
(WebCore::MQ::Features::deviceHeight):
(WebCore::MQ::Features::deviceWidth):
(WebCore::MQ::Features::dynamicRange):
(WebCore::MQ::Features::monochrome):
* Source/WebCore/dom/Document.cpp:
(WebCore::Document::resolveStyle):
(WebCore::Document::topDocument const):
(WebCore::computeIntersectionState):
* Source/WebCore/dom/DocumentMarkerController.cpp:
(WebCore::updateMainFrameLayoutIfNeeded):
* Source/WebCore/dom/EventDispatcher.cpp:
(WebCore::shouldSuppressEventDispatchInDOM):
* Source/WebCore/editing/Editor.cpp:
(WebCore::Editor::canPaste const):
(WebCore::Editor::shouldInsertText const):
* Source/WebCore/editing/EditorCommand.cpp:
(WebCore::allowExecutionWhenDisabledPaste):
* Source/WebCore/html/HTMLAnchorElement.cpp:
(WebCore::HTMLAnchorElement::mainDocumentRegistrableDomainForPCM const):
(WebCore::HTMLAnchorElement::parsePrivateClickMeasurement const):
* Source/WebCore/html/MediaElementSession.cpp:
(WebCore::isElementMainContentForPurposesOfAutoplay):
(WebCore::isElementRectMostlyInMainFrame):
(WebCore::isElementLargeRelativeToMainFrame):
* Source/WebCore/loader/DocumentLoader.cpp:
(WebCore::DocumentLoader::disallowWebArchive const):
* Source/WebCore/loader/FrameLoader.cpp:
(WebCore::FrameLoader::checkLoadComplete):
(WebCore::FrameLoader::userAgent const):
(WebCore::FrameLoader::navigatorPlatform const):
(WebCore::FrameLoader::updateRequestAndAddExtraFields):
(WebCore::FrameLoader::loadResourceSynchronously):
(WebCore::FrameLoader::continueLoadAfterNavigationPolicy):
(WebCore::FrameLoader::loadDifferentDocumentItem):
(WebCore::FrameLoader::loadProgressingStatusChanged):
* Source/WebCore/loader/HistoryController.cpp:
(WebCore::FrameLoader::HistoryController::updateForCommit):
(WebCore::FrameLoader::HistoryController::updateForSameDocumentNavigation):
(WebCore::FrameLoader::HistoryController::updateBackForwardListClippedAtTarget):
(WebCore::FrameLoader::HistoryController::pushState):
* Source/WebCore/loader/NavigationDisabler.h:
(WebCore::NavigationDisabler::NavigationDisabler):
(WebCore::NavigationDisabler::~NavigationDisabler):
(WebCore::NavigationDisabler::isNavigationAllowed):
* Source/WebCore/loader/cache/CachedResource.cpp:
(WebCore::CachedResource::load):
* Source/WebCore/loader/cache/CachedResourceLoader.cpp:
(WebCore::CachedResourceLoader::requestResource):
* Source/WebCore/page/AutoscrollController.cpp:
(WebCore::AutoscrollController::stopAutoscrollTimer):
* Source/WebCore/page/DOMWindow.cpp:
(WebCore::DOMWindow::outerHeight const):
(WebCore::DOMWindow::outerWidth const):
(WebCore::DOMWindow::isSameSecurityOriginAsMainFrame const):
(WebCore::DOMWindow::open):
* Source/WebCore/page/EventHandler.cpp:
(WebCore::EventHandler::hitTestResultAtPoint const):
(WebCore::EventHandler::selectCursor):
(WebCore::EventHandler::handleMousePressEvent):
(WebCore::EventHandler::internalKeyEvent):
* Source/WebCore/page/Frame.cpp:
(WebCore::Frame::abstractMainFrame const):
* Source/WebCore/page/Frame.h:
* Source/WebCore/page/Screen.cpp:
(WebCore::isLoadingInHeadlessMode):
* Source/WebCore/testing/Internals.cpp:
(WebCore::Internals::scrollBySimulatingWheelEvent):
* Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp:
(WebKit::WebLoaderStrategy::loadResource):
* Source/WebKit/WebProcess/WebCoreSupport/mac/WebDragClientMac.mm:
(WebKit::convertDragImageToBitmap):
* Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm:
(WebKit::rangeForPointInRootViewCoordinates):
</pre>

2023-02-11 00:37 UTC, chirags27 commented
This isn't ready for review yet - just opening this to get an initial full run. Need to fix many more places and then will move abstractMainFrame() --> mainFrame()

2023-02-11 00:40 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/2559a76a62997ddb96ef6a37f8fc190946fbedff. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-13 19:05 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/afb40fbac762f2848598b1b939462927e1ac0828. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-13 19:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/da5014e993f1232ce09c393230b1a774addfc31c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-13 23:21 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/cd460a44f55e461ce32f0064d386eeffbfc370b6. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-15 19:01 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/eac6f1f999940505b7497efa6f67b045fc9c9471. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-15 19:26 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/ee1e53dc543f7fee494faf45ce23427645c7161c. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-15 19:48 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/9f0a758c5f903f9f0b28ec1beae613439cfecba1. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-15 22:27 UTC, achristensen07 requested changes

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/contentextensions/ContentExtensionsBackend.cpp
> +            auto* mainDocument = localFrame->document();
This can be in the if statement below.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/css/query/MediaQueryFeatures.cpp
> +            return -1;
Let's return 8 for now, which is the default value on iOS.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/css/query/MediaQueryFeatures.cpp
> +                if (localFrame->view())
You dropped the screenSupportsExtendedColor call.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/dom/Document.cpp
> +            downcast<LocalFrame>(downcast<LocalFrame>(frameView.frame()).mainFrame()).eventHandler().dispatchFakeMouseMoveEventSoon();
Let's add dynamicDowncast and null checks here too.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/html/HTMLAnchorElement.cpp
> +    ASSERT(localFrame);
Let's just do a null check instead of an assert.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/html/MediaElementSession.cpp
> +    ASSERT(localFrame);
early return if this is null.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/html/MediaElementSession.cpp
> +    ASSERT(localFrame);
Early return if null.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/loader/DocumentLoader.cpp
> +    ASSERT(localFrame);
Early return if false.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/loader/NavigationDisabler.h
> +        auto* localFrame = dynamicDowncast<LocalFrame>(frame->mainFrame());
We need to null check frame before this dereference.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/loader/cache/CachedResource.cpp
> +        failBeforeStarting();
Let's just skip the use of topDocument if the main frame isn't local, instead of failing all loads or early returning.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/page/EventHandler.cpp
> +        ASSERT(dynamicDowncast<LocalFrame>(m_frame.mainFrame()));
Let's skip this code if it's not local.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/page/FrameView.cpp
> +        ASSERT(localMainFrame);
Let's null check this in the if statement below.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebCore/page/IntersectionObserver.cpp
> +        auto* localFrame = dynamicDowncast<LocalFrame>(frame->mainFrame());
This can be in the if statement below:
if (auto* localFrame = ...)

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebKit/WebProcess/Automation/WebAutomationSessionProxy.cpp
> +
extra space.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebKit/WebProcess/Network/WebLoaderStrategy.cpp
> +    ASSERT(localFrame);
null check.

2023-02-15 22:27 UTC, achristensen07 commented on Source/WebKit/WebProcess/Network/WebSocketChannel.cpp
> +        ASSERT(mainFrame);
null check.

2023-02-16 00:45 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/c9474ecaa5e85db2780350c452458fb705ab7b1d. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-16 00:45 UTC, webkit-early-warning-system commented
EWS run on previous version of this PR (hash https://github.com/WebKit/WebKit/commit/d4f9c0563674bf9530b33323feadc5b3f521173a)<details>

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/6/builds/108052 "1 style error") | [⏳ 🛠 ios ](https://ews-build.webkit.org/#/builders/iOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wpe ](https://ews-build.webkit.org/#/builders/WPE-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 wincairo ](https://ews-build.webkit.org/#/builders/WinCairo-EWS "Waiting in queue, processing has not started yet") 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/11/builds/111940 "Passed tests") | [⏳ 🛠 ios-sim ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 mac-AS-debug ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 gtk](https://ews-build.webkit.org/#/builders/36/builds/100250 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/19/builds/113818 "Passed tests") | [⏳ 🧪 ios-wk2 ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 api-mac ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/36/builds/100250 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | 
| | [⏳ 🧪 api-ios ](https://ews-build.webkit.org/#/builders/iOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk1 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🧪 api-gtk](https://ews-build.webkit.org/#/builders/36/builds/100250 "Build is in progress. Recent messages:Failed to print configuration; Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Updated gtk dependencies; Running compile-webkit") | 
| [⏳ 🛠 🧪 jsc ](https://ews-build.webkit.org/#/builders/JSC-Tests-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv ](https://ews-build.webkit.org/#/builders/tvOS-16-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2 ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-armv7 ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🛠 🧪 jsc-arm64 ](https://ews-build.webkit.org/#/builders/JSC-Tests-arm64-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 tv-sim ](https://ews-build.webkit.org/#/builders/tvOS-16-Simulator-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-AS-debug-wk2 ](https://ews-build.webkit.org/#/builders/macOS-AppleSilicon-Ventura-Debug-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 jsc-armv7-tests ](https://ews-build.webkit.org/#/builders/JSC-ARMv7-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| [⏳ 🧪 services ](https://ews-build.webkit.org/#/builders/Services-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 watch ](https://ews-build.webkit.org/#/builders/watchOS-9-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🧪 mac-wk2-stress ](https://ews-build.webkit.org/#/builders/macOS-BigSur-Release-Build-EWS "Waiting in queue, processing has not started yet") | [⏳ 🛠 jsc-mips ](https://ews-build.webkit.org/#/builders/JSC-MIPSEL-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | [![loading](https://user-images.githubusercontent.com/3098702/171232313-daa606f1-8fd6-4b0f-a20b-2cb93c43d19b.png) 🛠 watch-sim](https://ews-build.webkit.org/#/builders/79/builds/12310 "Build is in progress. Recent messages:Cleaned up git repository; Skipping applying patch since patch_id isn't provided; Checked out pull request; Failed to compile WebKit; Reverted pull request changes; Running compile-webkit-without-change") | | [⏳ 🧪 jsc-mips-tests ](https://ews-build.webkit.org/#/builders/JSC-MIPSEL-32bits-Build-EWS "Waiting in queue, processing has not started yet") | 
| | | | | </details>

2023-02-16 00:56 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/e83eeab9bc6671434b1701c2ed7a6b797fa8695e. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-16 18:39 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/b276a610cfb04321e21ab7fbc6515de1bc654c69. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-16 21:24 UTC, achristensen07 approved these changes

2023-02-16 21:24 UTC, achristensen07 commented on Source/WebCore/loader/cache/CachedResourceLoader.cpp
> +                if (auto* topDocument = localMainFrame->document())
nit: This can be a little more concise:
else if (auto* topDocument = localMainFrame ? localMainFrame->document() : nullptr)

2023-02-16 21:24 UTC, achristensen07 commented on Source/WebCore/page/AutoscrollController.cpp
> +    if (frame && !frame->isMainFrame() && localFrame)
if (localFrame && !localFrame->isMainFrame())

2023-02-16 21:24 UTC, achristensen07 commented on Source/WebCore/page/EventHandler.cpp
> +        if (auto* localFrame = dynamicDowncast<LocalFrame>(m_frame.mainFrame())) {
if (RefPtr mainFrame = ...) {
That way we don't need a separate line where we declare a Ref.

2023-02-16 21:50 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/dcb14451b7752e1f43d1425ff629ce0f25b6eddc. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-17 00:03 UTC, webkit-early-warning-system commented
Starting EWS tests for https://github.com/WebKit/WebKit/commit/504b16f4b44db9fed0741429cc8ae76416701f32. Live statuses available at the PR page, https://github.com/WebKit/WebKit/pull/9958

2023-02-17 02:52 UTC, webkit-commit-queue commented
Committed 260414@main (52ec37994c2d): <https://commits.webkit.org/260414@main>

Reviewed commits have been landed. Closing PR #9958 and removing active labels.

2023-02-17 02:52 UTC, merged